### ISSUE TITLE
Make FAQ 

### ISSUE THREAD

**Issue by czepluch** [raiden-network/raiden#100]
collecting expected questions in the wiki would be a good start.

**Comment by czepluch** [comment]
I guess this is ongoing, but also something that should be finalized at some point. All unanswered questions in https://github.com/raiden-network/raiden/wiki/FAQ should be answered before MVP

**Comment by hackaugusto** [comment]
Closing the issue since https://github.com/raiden-network/raiden/wiki/FAQ exists.
