### ISSUE TITLE
UPnP port mapper should not reuse existing mappings

### ISSUE THREAD

**Issue by konradkonrad** [raiden-network/raiden#1007]
## Problem Definition

During tests, we found ourselves in a situation where two LAN-IPs got the same port mapping assigned via upnp. We should make sure to ignore existing port mappings and always request a new one during start up.

**Comment by LefterisJP** [comment]
I tried the same now in another network and this did not occur. I wonder why. What factors can be network specific here?

**Comment by ulope** [comment]
We have to make sure not to re-introduce the problem solved with #696.

**Comment by LefterisJP** [comment]
I think this is solved with the `raiden_udp_ports` fixture:

https://github.com/raiden-network/raiden/blob/b2e2d35d8dde0c10b7359b6eb92be874741f1d64/raiden/tests/fixtures/variables.py#L277

If I am wrong please reopen the issue
