### ISSUE TITLE
EventTransferSentSuccess should contain `amount` and `target`

### ISSUE THREAD

**Issue by konradkonrad** [raiden-network/raiden#1010]
## Problem Definition

Currently `EventTransferSentSuccess` events are only informative, if the user keeps an out-of-band book over all initiated transfers and their respective identifiers. I.e.

```
    {
        "block_number": 1666812,
        "event_type": "EventTransferSentSuccess",
        "identifier": 1266537366290712202
    }
```

does not allow to learn anything about the details of the transfer.

## Solution

`EventTransferSentSuccess` should mirror `EventTransferReceivedSuccess` and contain the fields
- `amount`
- `target`
as well.

## Tasklist

- [x] Add `amount` and `target` to `EventTransferSentSuccess`
- [x] Add tests for correct values for these fields
- [x] Adjust the API endpoint, specs & docs to include these
- [x] Adjust the `webui` implementation to make use of these

**Comment by czepluch** [comment]
Closed with #1043
