### ISSUE TITLE
Tester: ChannelExternalStateTester implement `set_settled_block()`

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#1014]
## Problem Definition

In [ChannelExternalState](https://github.com/raiden-network/raiden/blob/3d26d3a24175c1dca91d51cbeb26436eb51a0999/raiden/channel/netting_channel.py#L39) in the netting channel we have the `settled_block` property which is set via [`set_settled()`](https://github.com/raiden-network/raiden/blob/3d26d3a24175c1dca91d51cbeb26436eb51a0999/raiden/channel/netting_channel.py#L91) when `ChannelSettled` event is read.

In the tester we have [ChannelExternalStateTester](https://github.com/raiden-network/raiden/blob/3d26d3a24175c1dca91d51cbeb26436eb51a0999/raiden/tests/utils/tester_client.py#L120) which should mimick the `ChannelExternalState`. But at the moment it does not as it has no `set_settled()` function and the `settled_block` property is [set to 0](https://github.com/raiden-network/raiden/blob/3d26d3a24175c1dca91d51cbeb26436eb51a0999/raiden/tests/utils/tester_client.py#L150)

## Solution

Make both `ChannelExternalState` and `ChannelExternalStateTester` have same behaviour around the `set_settled()` function or we may end up getting funny tester errors at some point.

**Comment by hackaugusto** [comment]
The external state was removed with the introduction of the channel based on the state machine
