### ISSUE TITLE
Make Compatible with macOS

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#1015]
## Problem Definition

Reports from users are that Raiden at the moment is [not compatible with macOS](https://twitter.com/homakov/status/908304985892499456). A user in [gitter](https://gitter.im/raiden-network/raiden?at=59b7a9b2bc464729742303a6) reported that there is a dependency problem: 

`pkg_resources.DistributionNotFound: The 'scrypt' distribution was not found and is required by ethereum, pyethapp`

It's quite possible that there are other problems as we have not really tested on Macos. Since it's a popular distro among some devs we should make this a priority.

## Solution

Test raiden on Macos and make sure all functionality works there in the same way as it does in Linux.

## Tasklist

- [x] Test Raiden in macOS and fix all incompatibilities
- [x] Run tests in Travis, or some other CI also for macOS. (Optional - perhaps make another issue for this) will be tracked in #1130
- [ ] Add a changelog entry.

**Comment by ulope** [comment]
I'll take this one (since I'm the only mac user in the team anyway I think ;))

**Comment by LefterisJP** [comment]
Thank you! I also have an old Macbook Air just for testing for that distro but having an experienced Mac user handle it is a better idea ;)

**Comment by homakov** [comment]
For me setup.py develop thrown a ton of errors but raiden bin was created nevertheless. /raiden says

```
pkg_resources.DistributionNotFound: The 'cffi>=1.3.0' distribution was not found and is required by coincurve
```

But I definitely have cffi installed. I never touched python on my machine so something needs to be tweaked for macos users here...

**Comment by tayvano** [comment]
```2 warnings generated.
scrypt-1.2.0/libcperciva/crypto/crypto_aes.c:6:10: fatal error: 'openssl/aes.h' file not found
#include <openssl/aes.h>```

Which is why I shouldnt have been lazy and not set up a VM. 😒

**Comment by mdcoon** [comment]
Just to throw in more information. I'm on Mac OS X 10.11.6, used pip install to grab pyethapp, tried virtualenv, and all seems to hang on gevent-websocket with error code 4. According to web, "error code 4" on mac equates to binary incompatibility (i.e. likely gevent-websockets is out of date and no longer binary compatible with later versions of gcc on OS X.). I tried pip installing gevent-websockets newer version (0.10) and that had same error.

**Comment by palango** [comment]
@ulope What do you think about providing a homebrew recipe for raiden if we cannot get the pyinstaller package to work?

**Comment by ulope** [comment]
@palango If we want to provide bottles we're basically back to the same problem. If not, python source packages on homebrew can be a major pain since there is (or at least has been last time I looked) no built-in virtualenv support.

I'd say if we can't currently get the pyinstaller builder to work on travis let's for now just manually produce the packages. We don't to releases that often.
