### ISSUE TITLE
Support NAT-PMP and PCP protocols

### ISSUE THREAD

**Issue by ulope** [raiden-network/raiden#1016]
## Problem Definition

We currently only support UPNP and STUN for NAT traversal. There are however also quite a few routers that support [NAT-PMP](https://en.wikipedia.org/wiki/NAT_Port_Mapping_Protocol). It's successor [PCP](https://en.wikipedia.org/wiki/Port_Control_Protocol) is intended to also work with IPv6 and carrier grade nat. 

## Solution

Add support for NAT-PMP and PCP port mapping.

## Tasklist

- [ ] Investigate which libraries are suitable
- [ ] Add support for NAT-PMP and PCP port mapping.
- [ ] Add a changelog entry.

**Comment by palango** [comment]
No more UDP transport.
