### ISSUE TITLE
Handle roaming

### ISSUE THREAD

**Issue by konradkonrad** [raiden-network/raiden#1018]
## Problem Definition

When the external endpoint changes, we need to change our entry in the registry.
So far we only check our network configuration (NAT/IP) during the client startup.

## Solution

We should regularly check if our registered address still corresponds to our physical location. If it has changed ("roaming"), we need to also check if our port-mapping (UPnP/STUN) is still valid.

Note that there are some conditions that need to be handled (if even possible):
- we may need to re-establish our port mapping
- we may have roamed into a non-mappable  NAT profile (i.e. from `restricted` to `symmetric`)
- we may have roamed into a local area network without internet access

**Comment by ulope** [comment]
FYI: By accident I discovered that NAT-PMP and PCP (#1016) support a feature which allows a client to register for announcements from the router when the external IP address changes.

**Comment by palango** [comment]
No more UDP transport.
