### ISSUE TITLE
Change to web3.py client

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/raiden#1019]
## Problem Definition

We are currently using the pyethapp rpc client, which lacks important methods and support for IPC.

## Solution

Switch to web3.py

## Related

Support `ipc` connection with ethereum node #461
Synchronize API calls that use non-constant smart contract functions #419

**Comment by andrevmatos** [comment]
If we do it right, maybe using a singleton pattern and locks for transactions, we can fix #804 in the process.

**Comment by hackaugusto** [comment]
Can't use singletons, that is global state and doesn't allow for more than one client on the same process. That would break most of our integration tests.

**Comment by andrevmatos** [comment]
Hmm, right.. single process tests.. anyway, assuring a single long-living client instance for each Raiden client, with track better track of nonces, and lock-protected transactions (not polling), could solve these issues, and this client-library change is a good opportunity to do that.

**Comment by andrevmatos** [comment]
I'll check this too, together with #87

**Comment by hackaugusto** [comment]
Closing in favor of #1019
