### ISSUE TITLE
Fix testsuite on macOS

### ISSUE THREAD

**Issue by ulope** [raiden-network/raiden#1021]
## Problem Definition

The parts of the testsuite that use geth are unable to run on macOS due to too long ipc socket paths.

On macOS temp file paths are very long (example: `/var/folders/w9/dw430b4150jgsh1_f2cx5c8r0000gp/T`). Combined with pytest's tmpdir handling this exceeds the 108 char limit for unix domain socket paths (which is even shorter at 104 on macOS). 

## Solution

Find a solution that allows the geth tests to run on macOS.

## Tasklist

- [ ] Find a solution that allows the geth tests to run on macOS.
- [ ] Add a changelog entry.

**Comment by hackaugusto** [comment]
I hit this exact problem before :/ :

https://github.com/raiden-network/raiden/pull/475#discussion_r108901202

**Comment by palango** [comment]
@ulope how is this related related to #1015
