### ISSUE TITLE
Update throw check for metropolis

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/raiden#1023]
## Problem Definition

EIP 98/658 adds the return status of the transaction in the receipt, this value must be used to check the status of a transaction (success / failure)

## Solution

Update our throw check to use the receipt instead of the gas usage.

**Comment by LefterisJP** [comment]
Some more info on this one.

To handle metropolis we swittched our logic to check if a transaction failed to a temporary hack [here](https://github.com/raiden-network/raiden/blob/f40fc962f9c4b78eb0667b367d4e1b426191ed9f/raiden/network/rpc/client.py#L81).

Until https://github.com/ethereum/EIPs/pull/658 or https://github.com/ethereum/EIPs/pull/699 is properly implemented in all clients and we have the `status` code in the receipt we are using `debug.traceTransaction(TXHASH)['structLogs'][-1]` and check if it's not a `RETURN` or a `STOP` and from that we deduce that the transaction failed or not. If it's anything other than the 2 opcodes above it has failed.

This is a temporary workaround and has to go once we got the `status` code in the transaction receipt and start checking for that instead.
