### ISSUE TITLE
Add gas table of common channel operations in our documentation

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#1024]
## Problem Definition

There is no way for (advanced developer) users to easily see a rundown of how much it would cost at any verion of raiden to perform common channel operations.

## Solution

Add a table, probably in [spec.rst](https://github.com/raiden-network/raiden/blob/master/docs/spec.rst) with gas costs of all raiden common channel operations which should be updated every time we change the logic of the contracts or if there is any considerable contract revamp.

This way we will be able to efficiently have a versioned tracking of gas costs optimizations and also a way to identify bottlenecks that require optimization.

**Comment by hackaugusto** [comment]
Related: Define the maximum number of pending transfers #439

**Comment by loredanacirstea** [comment]
This issue is moved to the smart contracts repository: https://github.com/raiden-network/raiden-contracts/issues/16
