### ISSUE TITLE
Switch channel implementation to one global contract per token

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#1025]
## Problem Definition

At the moment whenever we open a channel we create a smart contract per channel. We went with this implementation for simplicity reasons in the beginning but it is not optimal as it increases gas costs for channel opening due to the `CREATE` operation.

**EDIT**: This has been split into 2 issues:

#1171 and #1172

## Solution

Have a global contract managing all channels per token.

## Tasklist

- [ ] Replace the `NettingChannelLibrary` and `NettingChannelContract` with an equivalent contract managing all channels for a token.
- [ ] Make adjustments to the code so that it works with the new contracts.
- [ ] Change the [relevant spec entry](https://github.com/raiden-network/raiden/blob/b3fe38fd6f5939aed8e6d0b8142144657d98e4f8/docs/spec.rst#one-contract-per-channel) to reflect the new implementation and the reasoning behind it.
- [ ] Add a changelog entry.

**Comment by hackaugusto** [comment]
Related: Investigate gas usage of opening a new channel #869

**Comment by murrekatt** [comment]
@LefterisJP @hackaugusto I'm trying to understand how much flexibility Raiden Network aims to provide. Are you aiming to let people have their own channel smart contracts (that of course implements some interface) to manage channels for their own tokens?

**Comment by LefterisJP** [comment]
This has been split into 2 issues: 
#1171 and #1172

**Comment by hackaugusto** [comment]
closing this in favor of #1171 and #1172

**Comment by hackaugusto** [comment]
@murrekatt Sorry for the really late response

> I'm trying to understand how much flexibility Raiden Network aims to provide. Are you aiming to let people have their own channel smart contracts (that of course implements some interface) to manage channels for their own tokens?

This is not necessarily a goal but it is possible. But I don't see the benefit at first sight, since the alternative implementation would need to follow our interfaces and protocol.

We do think about calls from other smart contracts, making sure our interfaces allow for interaction, so that other smart contracts can use the interact with the channel's life cycle.
