### ISSUE TITLE
Include rinkeby testnet contract adresses

### ISSUE THREAD

**Issue by dcale** [raiden-network/raiden#1031]
I needed a rinkeby setup for raiden. So I deployed the contracts on it. Everything seems to work, but it would be better to have an "official" setup on rinkeby. The contracts I use so far:

--discovery-contract-address 0xD5F99DaD97FB8373519C1Bd7C49705D240253514 
--registry-contract-address 0xb93B09cB09B97A431CC3048f357E45d0bdb1Cca8

**Comment by LefterisJP** [comment]
Hello @dcale! Thanks for trying out raiden and for sharing the contract addresses you used in rinkeby with us.

Raiden will be getting very frequent updates from here and on and it's not possible for us to maintain and test on 2 different testnets. We prefer Ropsten as it's PoW, so a system identical to the mainnet.

Naturally you are more than welcome to use any testnet you want and redeploy as needed. If you want to share the addresses with other people perhaps write about it our [gitter channel](https://gitter.im/raiden-network/raiden) and see if anyone else is interested in testing on rinkeby?
