### ISSUE TITLE
Introduce upper limit for settle_timeout

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#1038]
## Problem Definition

This is not a really serious problem, but we should also think of introducing an upper limit for the contract's `settle_timeout` property.

The only reason why we would need to do that is to protect users from themselves, by not letting them enter a `settle_timeout` close to `2**256 - 1` and then have either [this](https://github.com/raiden-network/raiden/blob/ee25ac5f3f9161d196074a65ace75310e5cbf0e0/raiden/smart_contracts/NettingChannelLibrary.sol#L52) or [this](https://github.com/raiden-network/raiden/blob/ee25ac5f3f9161d196074a65ace75310e5cbf0e0/raiden/smart_contracts/NettingChannelLibrary.sol#L56) modifier check overflow and have their channel botched with the tokens trapped in there forever.

## Solution

Provide an upper limit for `settle_timeout` and enforce it in the contract.

## Tasklist

- [ ] Provide upper limit for settle timeout
- [ ] Make test for that value
- [ ] Add a changelog entry.

**Comment by ulope** [comment]
Anything above a couple million to tens of millions of blocks (~ 1 - 10 year(s) with 20s blocks) could probably be considered "forever" for most practical use cases.

**Comment by hackaugusto** [comment]
Is https://github.com/raiden-network/raiden/pull/863/ enough or do you want to add a check in the smart contract code?

**Comment by LefterisJP** [comment]
I want it in the smart contracts. It's an easy thing to add.
