### ISSUE TITLE
Differentiate "address in use" between API and Raiden service port

### ISSUE THREAD

**Issue by ulope** [raiden-network/raiden#1039]
## Problem Definition

As reported in #1032 the CLI currently doesn't differentiate between the API and Raiden service when reporting an `Address already in use` error. [The error handler](https://github.com/raiden-network/raiden/blob/03a05586f039e544d2d8ceb42307fe02e29aad15/raiden/ui/cli.py#L522) blindly assumes that the conflict was caused by the Raiden service.

## Solution

Catch the socket error at a lower level and convert it to a specific one that allows the CLI level to differentiate between API and Raiden service.

## Tasklist

- [ ] Catch `socket.error` `EADDRINUSE` nearer to opening the ports and reraise as app specific exceptions
- [ ] Provide an appropriate error message for each case
- [ ] Add a changelog entry.

**Comment by LefterisJP** [comment]
This is removed from the Red Eyes milestone.
