### ISSUE TITLE
Rename `connection` api endpoint to `connections`

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#1044]
## Problem Definition

All of our endpoints are using plural nouns since they are collections of resources. We need to make sure that `connection` endpoint follows this rule.

- [x] Rename the connection endpoint
- [x] Add a changelog entry.

**Comment by andrevmatos** [comment]
https://github.com/raiden-network/raiden/pull/1001#discussion_r138866762 ?

**Comment by LefterisJP** [comment]
@andrevmatos Which comment do you link to? I don't understand.

That PR added the `GET connection` endpoint but we also have the `PUT connection/token_address` endpoint that will also need renaming. Which is why I did not insists on renaming on that PR.

**Comment by andrevmatos** [comment]
It was this comment:
> Wait no. Disregard this comment, we already use this endpoint to connect, so no renaming.

**Comment by LefterisJP** [comment]
Yep, so as I said in rocketchat, I noticed this problem last week and was about to tell you to rename it but then realized it's more than one endpoint that needs renaming so better leave it for another issue (i.e.: this issue)
