### ISSUE TITLE
smoketest with parity?

### ISSUE THREAD

**Issue by drandreaskrueger** [raiden-network/raiden#1059]
## Problem Definition
While trying to explore my ['timeout when polling for transaction' issue](https://github.com/raiden-network/raiden/issues/1058) I found the `smoketest` command. Is that useful for me as an end-user too, or only for you developers?

raiden smoketest fails with `KeyError: 'RST_GETH_BINARY'` exception. I do not have `geth` but `parity`.

## Solution

Extend 
https://github.com/raiden-network/raiden/blob/7a6531a22bd077367140f036872d5442a57d4cda/raiden/tests/utils/smoketest.py#L64 to not only work with `geth` but also with `parity` ?

### System Description
```
source raiden/env/raidenpython/bin/activate; raiden version; parity --version; solc --version; deactivate

{
  "python_version": "2.7.13", 
  "python_implementation": "CPython", 
  "system": "Linux 64bit_ 4.9.0-3-amd64", 
  "raiden": "0.1.0+git.r72845c7a"
}

Parity
  version Parity/v1.8.0-unstable-684b14271-20170921/x86_64-linux-gnu/rustc1.20.0

solc
Version: 0.4.16-develop.2017.9.25+commit.d7661dd9.Linux.g++
```

**Comment by drandreaskrueger** [comment]
I had misunderstood the role of `geth` in that smoketest.  I do not want to keep two copies of the gigantic Ethereum public chain on my machine, and that is why I am avoiding geth (in favor of parity). But for smoketest I can simply have the geth binary, without downloading the whole chain, of course. Done that now.

Result:

```
raiden smoketest
[1/5] getting smoketest configuration
[2/5] starting ethereum
[3/5] starting raiden
Warning: This is a pre-release compiler version, please do not use it in production.
Warning: This is a pre-release compiler version, please do not use it in production.
Warning: This is a pre-release compiler version, please do not use it in production.
Warning: This is a pre-release compiler version, please do not use it in production.
Warning: This is a pre-release compiler version, please do not use it in production.
[4/5] running smoketests...
[5/5] smoketest successful, report was written to /tmp/tmpPqXJpl.log
```
So that seems to run through fine, no? Would it help you to see anything from that /tmp/tmpPqXJpl.log for my question https://github.com/raiden-network/raiden/issues/1058 ? Thanks.

**Comment by hackaugusto** [comment]
> Is that useful for me as an end-user too, or only for you developers?

That is a sanity check. It executes a private chain and runs a few checks, it's okay to run it and see what happens.

Since the smoketest executed successfully, I'm going to close this issue.
