### ISSUE TITLE
Endpoint registration fails on fast restarts

### ISSUE THREAD

**Issue by drandreaskrueger** [raiden-network/raiden#1061]
I get a new error message now:

    CRITICAL:raiden.raiden_service	
    Endpoint registry failed: JSONRPCClientReplyError
    (u'known transaction: a68a50307bc064a039ec69f333f43a71c40afb8c6d91963e234a4a8d3c8e565d',).  

This is a followup on https://github.com/raiden-network/raiden/issues/1058 so more details are there, but here is a summary:
```
geth --rpc --rpcapi eth,net,web3,debug --testnet --fast --bootnodes "enode://20c9ad97c081d63397d7b685a412227a40e23c8bdc6688c6f37e97cfbc22d2b4d1db1510d8f61e6a8866ad7f0e17c02b14182d37ea7c3c8b9c2683aeb6b733a1@52.169.14.227:30303,enode://6ce05930c72abc632c58e2e4324f7c7ea478cec0ed4fa2528982cf34483094e9cbc9216e7aa349691242576d552a2a56aaeae426c5303ded677ce455ba1acd9d@13.84.180.240:30303"
```
fully synced, until:
```
INFO [09-26|12:25:44] Imported new chain segment               blocks=1 txs=1  mgas=0.115 elapsed=25.985ms mgasps=4.413  number=1749785 hash=44ac59…7c8fce
```
then raiden:
```
source raiden/env/raidenpython/bin/activate
raiden --keystore-path  ~/.ethereum/testnet/keystore --address $ETHADDRESS --password-file $ETHADDRESSPASSWORDFILE
```
and that now results in:

```
Welcome to Raiden, version 0.1.0+git.r72845c7a!
ERROR:raiden.network.upnpsock	could not query your lanaddr reported=
INFO:raiden.network.sockfactory	Network port opened internal=0.0.0.0:40001 method=stun external=my.EXTERNAL.ip.address:40001
Checking if the ethereum node is synchronized
Warning: This is a pre-release compiler version, please do not use it in production.
Warning: This is a pre-release compiler version, please do not use it in production.
Warning: This is a pre-release compiler version, please do not use it in production.
Warning: This is a pre-release compiler version, please do not use it in production.
Warning: This is a pre-release compiler version, please do not use it in production.
Traceback (most recent call last):
  File "/PATH/raiden-network/raiden/env/raidenpython/local/lib/python2.7/site-packages/gevent/greenlet.py", line 534, in run
    result = self._run(*self.args, **self.kwargs)
  File "/PATH/raiden-network/raiden/raiden/network/discovery.py", line 92, in register
    self.discovery_proxy.register_endpoint(node_address, endpoint)
  File "/PATH/raiden-network/raiden/raiden/network/rpc/client.py", line 575, in register_endpoint
    startgas=DISCOVERY_REGISTRATION_GAS
  File "/PATH/raiden-network/raiden/env/raidenpython/local/lib/python2.7/site-packages/pyethapp/rpc_client.py", line 783, in transact
    **kargs
  File "/PATH/raiden-network/raiden/raiden/network/rpc/client.py", line 175, in send_transaction
    data_encoder(rlp.encode(tx)),
  File "/PATH/raiden-network/raiden/env/raidenpython/local/lib/python2.7/site-packages/pyethapp/rpc_client.py", line 413, in call
    raise JSONRPCClientReplyError(jsonrpc_reply.error)
JSONRPCClientReplyError: known transaction: a68a50307bc064a039ec69f333f43a71c40afb8c6d91963e234a4a8d3c8e565d
<Greenlet at 0x7ff3f36d4910: <bound method ContractDiscovery.register of <raiden.network.discovery.ContractDiscovery object at 0x7ff3f2de9090>>('\xc6-\x9fP\x92s\x7f\xa7h\x95y\xe2y\xa3\xa1\xddUC\, 'my.EXTERNAL.ip.address', 40001)> failed with JSONRPCClientReplyError

CRITICAL:raiden.raiden_service	Endpoint registry failed: JSONRPCClientReplyError(u'known transaction: a68a50307bc064a039ec69f333f43a71c40afb8c6d91963e234a4a8d3c8e565d',).  
```
with `my.EXTERNAL.ip.address` = edited out by me.  

The mentioned transaction [a68a50307bc064a039ec69f333f43a71c40afb8c6d91963e234a4a8d3c8e565d](https://ropsten.etherscan.io/tx/0xa68a50307bc064a039ec69f333f43a71c40afb8c6d91963e234a4a8d3c8e565d) was visible on etherscan, but disappeared again after ~30 minutes.

I am happy about the above because this error is actually different from the [previous 'timeout when polling' error message](https://github.com/raiden-network/raiden/issues/1058#issuecomment-332151465) - but what to do now?

**Comment by hackaugusto** [comment]
Hi @drandreaskrueger ,

Do you recall if the raiden node was restarted? That explains the error message.

The first time the node started it tried to register its `ip:port` pair with the smart contact, the node was restarted but the transaction was not mined in time, at the second time the same transaction was sent to the ethereum node resulting in that error.

We can change the rpc client to check if a transaction for registration is in-flight and wait for it to complete instead of trying a new one on top.

**Comment by ChosunOne** [comment]
This is likely related to the ropsten testnet being mined by a miner who has a large amount of the hashpower and is not including transactions into blocks.  I see this error a lot after an attempt to register the endpoint timeouts and I restart the raiden node.

**Comment by hackaugusto** [comment]
@ChosunOne here is a quick fix https://github.com/raiden-network/raiden/issues/1064#issuecomment-332696176 , this will likely fix the problem

**Comment by drandreaskrueger** [comment]
> related to the **ropsten testnet** being mined by a miner 
> who has a large amount of the hashpower and is 
> not including transactions into blocks.

Yes Ropsten seems ... ill. Please consider to deploy raiden also to Kovan/Rinkeby? Thanks.

**Comment by LefterisJP** [comment]
@drandreaskrueger you are free to deploy in other testnets.

**Comment by drandreaskrueger** [comment]
thx ;-)

Being not an expert on this, I thankfully decline the offer \*g\*. To even get here was a surprising challenge, literally each piece of the toolchain created an issue, some even several. So, thanks but no.

For me it would be a lot of trial and error - while you'd know exactly what and how to do. Plus you could make those contracts as official as the ones on Ropsten (I guess those are hardcoded into some settings file of raiden?).

Thanks

**Comment by LefterisJP** [comment]
This won't happen at the moment. We have our testing infrastructure in ropsten and no plans to change it. Ropsten is at the moment, the only universtal testnet that both clients can work on. Plus its the only testnet with metropolis changes activated.

**Comment by drandreaskrueger** [comment]
Alright, understood. Thanks anyways.

**Comment by drandreaskrueger** [comment]
> Do you recall if the raiden node was restarted? 

Yes, and many times. I am fighting with this thing for too much time already. So many hickups.  --> Would not have been my choice to restart, but I had to.

> The first time the node started it tried to register its ip:port pair with the  
> smart contact, the node was restarted but the transaction was not mined in time,  

I suppose even if your system were rather flawless, the crippled network you are trying to run it in ... causes most of the current issues.


>  at the second time the same transaction was sent to the ethereum node resulting in that error.  
> We can change the rpc client to check if a transaction for registration is in-flight 
> and wait for it to complete instead of trying a new one on top.

You seem to exactly understand what is going on here.  Great. So yes, please consider adding that failsafe. Thanks.

**Comment by drandreaskrueger** [comment]
Manually restarting raiden after that error ... now did the trick.

I get tons of warnings, but then it ends like this:
```
NettingChannelLibrary.sol:460:5: Warning: Function is marked pure. Be careful, pureness is not enforced yet.
    function max(uint a, uint b) pure internal returns (uint)
    ^
Spanning multiple lines.
ChannelManagerLibrary.sol:108:5: Warning: Function is marked pure. Be careful, pureness is not enforced yet.
    function partyHash(address address_one, address address_two)
    ^
Spanning multiple lines.
INFO:raiden.network.discovery	endpoint already registered node_address=a0d01b1d host=my.public.ip.address port=40001
INFO:filelock	Lock 139955740362832 acquired on ~/.raiden/0xa0d01b/.lock 
The Raiden API RPC server is now running at http://127.0.0.1:5001/.

See the Raiden documentation for all available endpoints at
http://raiden-network.readthedocs.io/en/stable/rest_api.html
```

**Comment by LefterisJP** [comment]
Since there is no further communication for months in this issue I will assume it is closed. If it persists please open a new one.

**Comment by hackaugusto** [comment]
I believe this is not fixed, when the same transaction is sent to the ethereu node an JSON RPC error is returned, this is verified by the assumption test from PR #1222.

We need to choose a behavior and handle all transactions sites properly.

**Comment by LefterisJP** [comment]
Let's use issue #1223 to further track progress of this problem.
