### ISSUE TITLE
PUT /api/1/tokens/0x... --> Internal Server Error

### ISSUE THREAD

**Issue by drandreaskrueger** [raiden-network/raiden#1064]
I am exploring raiden, and to have some ERC20 token to play with, I sent [testeth to 0x583cbBb8a8443B38aBcC0c956beCe47340ea1367 (BOKKY)](https://www.reddit.com/r/ethereum/comments/6i7twg/is_there_a_easy_and_fast_way_of_getting_some)

Now I am trying to register that token in raiden, but it fails:

```
curl -X PUT http://127.0.0.1:5001/api/1/tokens/0x583cbBb8a8443B38aBcC0c956beCe47340ea1367
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    37    0    37    0     0      0      0 --:--:--  0:03:00 --:--:--     9
{
  "message": "Internal Server Error"
}
```

Is that just because you have chosen a too short timeout of 3 minutes?

### my raiden is initialized indeed:
```
curl -X PUT http://127.0.0.1:5001/api/1/tokens/0x0f114A1E9Db192502E7856309cc899952b3db1ED
{"errors": "Token is already registered"}
```
so that works.

## Solutions

* Simply extend the timeout? 
  * But what is a good time? 
  * Additional api call parameter 600 (for 10 minutes)?
* move to a different testnet, because Ropsten is broken?
* separate (submitting that transaction & querying transaction receipt) into 2 API calls?
  * 1st API call: Submit transaction, answer is transaction hash
  * 2nd API call: with transaction hash given, return status
* what else could be done?

### System Description
```
source env/raidenpython/bin/activate; raiden version; parity --version; solc --version; deactivate
{
  "python_version": "2.7.13", 
  "python_implementation": "CPython", 
  "system": "Linux 64bit_ 4.9.0-3-amd64", 
  "raiden": "0.1.0+git.rcee8f459"
}
Parity
  version Parity/v1.8.0-unstable-684b14271-20170921/x86_64-linux-gnu/rustc1.20.0

solc
Version: 0.4.16-develop.2017.9.25+commit.d7661dd9.Linux.g++
```

**Comment by andrevmatos** [comment]
Hi, @drandreaskrueger 
`500` errors _should_ produce a very informative traceback in the Raiden's stdout/stderr. Can you look for it, and paste it here, please? Thank you.

**Comment by hackaugusto** [comment]
@drandreaskrueger thanks for testing.

> - separate (submitting that transaction & querying transaction receipt) into 2 API calls?
>   - 1st API call: Submit transaction, answer is transaction hash
>   - 2nd API call: with transaction hash given, return status

This was intentionally avoided. Using two calls won't really help since the problem with timeouts will just move from the 1st API call to the 2nd.

> what else could be done?

We can block the HTTP response until the transaction is mined, this has it's on set of problems, since a long running http request may seem broken to a user.

**Comment by hackaugusto** [comment]
Btw @drandreaskrueger , you may want to increase the GAS_PRICE setting to 100Gwei by hand, this is [likely the reason](https://gitter.im/ethereum/ropsten?at=59ca5f6bcfeed2eb6550d688) behind the long time to mine a transaction.

You can change the gas price at in [the setting.py file](https://github.com/raiden-network/raiden/blob/5a359fea3c7ec27f560181027ef77724344f4ba5/raiden/settings.py#L10)

**Comment by drandreaskrueger** [comment]
Nice one, good idea. Thanks.

**Comment by drandreaskrueger** [comment]
> GAS_PRICE setting to 100Gwei by hand

So all I need to do is changing [this line](https://github.com/raiden-network/raiden/blob/5a359fea3c7ec27f560181027ef77724344f4ba5/raiden/settings.py#L10) 
to

    GAS_PRICE = denoms.shannon * 100

?

**Comment by LefterisJP** [comment]
For 100 gwei yeah. But also check https://ropsten.etherscan.io/ for the gas price of the latest succesful transactions to see what gas price people put now. It seems to be up to 300 gwei now.

**Comment by drandreaskrueger** [comment]
About my idea/suggestion/fix (and also for https://github.com/raiden-network/raiden/issues/1079#issuecomment-335873151 ):

> > separate (submitting that transaction & querying transaction receipt) into 2 API calls?  
> > 1st API call: Submit transaction, answer is transaction hash  
> > 2nd API call: with transaction hash given, return status  

> This was intentionally avoided.  
> Using two calls won't really help since the problem with   
> timeouts will just move from the 1st API call to the 2nd.  

Yesbutno.

I imagine the first call to submit the transaction(s), but not wait for anything, so it immediately returns, just giving a (list of) transaction hash(es).

However, the second call could then rather result in 2 different outcomes:

```
{
    "status": "complete",

    "channel_address": "0x2a65aca4d5fc5b5c859090a6c34d164135398226",
    "partner_address": "0x61c808d82a3ac53231750dadc13c777b59310bd9",
    "token_address": "0x9aBa529db3FF2D8409A1da4C9eB148879b046700",
    "balance": 1337,
    "state": "open",
    "settle_timeout": 600
}
```

or 

```
{
    "status": "incomplete"
}
```

which means for me as a user that I sleep a few seconds, and then try the 2nd call again.



   

> @drandreaskrueger thanks for testing.  

@hackaugusto You're welcome. The goal of this project is exciting. It needs more testing - and such feedback like mine, right? Hope all these many issues of mine are helping you somehow? Anyone of you in London, by any chance -  perhaps we could meet one day?

**Comment by hackaugusto** [comment]
> which means for me as a user that I sleep a few seconds, and then try the 2nd call again.

That is what I mean it moves the timeout to the second API call, waiting a few seconds before the next request is just a different form of a timeout. With this approach one needs to choose how often to retry (with backing-off or not) and how many retries prior to considering a failure.

Ideally we should let the user know the software didn't hang, but we cant do that with the HTTP transport. For the moment the goal is to make these APIs blocking and idempotent, allowing the user to choose its timeout and to safely retry.

> The goal of this project is exciting. It needs more testing - and such feedback like mine, right? Hope all these many issues of mine are helping you somehow?

Yes, definitely. Knowing how people are trying to use Raiden and what is broken is the goal now :)

> Anyone of you in London, by any chance - perhaps we could meet one day?

Just to not leave the question hanging. The Raiden team is distributed around the world, this makes meeting a bit hard even for us, I live in south america for instance. There is big part of the team that lives in Europe though, you should try the gitter channel and see :smile:

**Comment by hackaugusto** [comment]
Closing in favor of #1134

@drandreaskrueger thanks again
