### ISSUE TITLE
Discussion: Account ordering

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden#1072]
## Problem Definition

I created two test accounts for testing with raiden. Their order as shown in `geth` is `["0xfb398e621c15e2bc5ae6a508d8d89af1f88c93e8", "0x0d6c3e766cb6a8464ec0f72c04ef54e59337ae64"]`. The first one here was created first, so I guess accounts are ordered by creation time.

When starting raiden I got the following order:

```
The following accounts were found in your machine:

[  0] - 0xfb398e621c15e2bc5ae6a508d8d89af1f88c93e8
[  1] - 0x0d6c3e766cb6a8464ec0f72c04ef54e59337ae64
```

I assumed that the first account in raiden would correspond to the first account as shown in `geth`, so I was surprised when my password didn't work. It urns out that raiden uses the order of `os.listdir(self.keystore_path):` which is probably the inode order of the files.

## Solution

I'd suggest to check account order in other clients and if applicable change the account order in raiden to match the clients.

## Tasklist

- [ ] Check account order in parity and other clients

**Comment by LefterisJP** [comment]
I don't think that the account ordering maters much. You should recognize the hex of your account and press the corresponding number, not choose based on index out of memory without even thinking or checking the account number. That is asking for trouble.

If you really think this is important and presents a usability problem then you can work on it, but I don't see it as something really important.

**Comment by palango** [comment]
Ok, just wanted to get feedback on this.
