### ISSUE TITLE
"errors": "After 10 seconds the deposit was not properly processed."

### ISSUE THREAD

**Issue by drandreaskrueger** [raiden-network/raiden#1079]
Hooray, I am actually *using* raiden now (after ~10 issues related to parity, ropsten, geth, and raiden hickups) - so any issue now is ... *suffering on a happy level* \*g\* ... I am actually pretty excited, to get this working. Thx again to everyone who helped.

Small problem:

```
cat openchannel.json
{
    "partner_address": 	"0x18...",
    "token_address": 	"0x583cbBb8a8443B38aBcC0c956beCe47340ea1367",
    "balance": 		1337,
    "settle_timeout": 	600
}

curl -X PUT http://127.0.0.1:5001/api/1/channels -d @openchannel.json --header 'Content-Type: application/json'

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   256  100    70  100   186      1      2  0:01:33  0:01:09  0:00:24    16

{
  "errors": "After 10 seconds the deposit was not properly processed."
}
```
the raiden log output shows success though:

```
INFO:raiden.network.rpc.client	new_netting_channel called peer1=72b0610c netting_channel=1920b92c peer2=18d4971f
INFO:raiden.event_handler	state_change received state_change=<raiden.transfer.mediated_transfer.state_change.ContractReceiveNewChannel object at 0x7fe4b1485710>
INFO:raiden.network.rpc.client	deposit called amount=1337 contract=1920b92c
INFO:raiden.network.rpc.client	deposit sucessfull amount=1337 contract=1920b92c
```

So ... the `/api/1/channels` is just not patient enough?

---

P.S.: As suggested before, I had raised the gasPrice to 300 Gwei - which made creating the channel pretty expensive - 0.3549267 Ether. Are the attacks over now? What is a good gasPrice right now? Thx.

**Comment by drandreaskrueger** [comment]
Probably the same in the next step?
```
curl -X PATCH http://127.0.0.1:5001/api/1/channels/0x19... -d @depositToChannel.json --header 'Content-Type: application/json'
```
with 
```
cat depositToChannel.json
{
    "balance": 7331
}
```
again I get a 
```
{"message": "Internal Server Error"}
```
and in the log output
```
EthNodeCommunicationError: After 10 seconds the deposit was not properly processed. 

in detail:
...
  File "~/raiden-test/raiden/raiden/api/v1/resources.py", line 60, in patch
    return self.rest_api.patch_channel(**kwargs)
  File "~/raiden-test/raiden/raiden/api/rest.py", line 536, in patch_channel
    balance
  File "~/raiden-test/raiden/raiden/api/python.py", line 281, in deposit
    wait_timeout_secs
EthNodeCommunicationError: After 10 seconds the deposit was not properly processed. 
INFO:raiden.api.rest	127.0.0.1 - - [2017-10-11 17:28:38] "PATCH /api/1/channels/0x19... HTTP/1.1" 500 164 27.173296 
```
BUT ...

... 2 transactions are created (approve, and deposit).

So functionality wise all is good, just the return value not.


Your default waiting time is too short?

Or again, instead of waiting for miners & receipt ... same idea like in another place:   
API endpoint 1 only submits the PATCH transactions, (but does not wait, only) returns transaction hashes - and you'd provide a new 2nd API endpoint: which (when given hashes) analyzes the transaction receipts, once they are mined (or returns "not yet"). Then the end user could poll the 2nd endpoint until success.  
I am thinking along those lines because you seem to try to make an asynchronous backend (Ethereum) into a synchronous middleware (raiden) by waiting for miners - and then when Ethereum takes too long, you need to timeout your waiting, of course.

**Comment by drandreaskrueger** [comment]
Your default waiting time is too short?

Or again, instead of waiting for miners & receipt ... same idea like in another place:   
API endpoint 1 only submits the PATCH transactions, (but does not wait, only) returns transaction hashes - and you'd provide a new 2nd API endpoint: which (when given hashes) analyzes the transaction receipts, once they are mined (or returns "not yet"). Then the end user could poll the 2nd endpoint until success.  
I am thinking along those lines because you seem to try to make an asynchronous backend (Ethereum) into a synchronous middleware (raiden) by waiting for miners - and then when Ethereum takes too long, you need to timeout your waiting, of course.

**Comment by drandreaskrueger** [comment]
but ... actually ... even after patching the channel from the side of the recipient, by sending those 7331 token-Wei ...

```
curl -s http://127.0.0.1:5001/api/1/channels | jq
[
  {
    "partner_address": "0x72...",
    "balance": 0,
    "reveal_timeout": 10,
    "settle_timeout": 600,
    "state": "opened",
    "channel_address": "0x19...",
    "token_address": "0x583cbbb8a8443b38abcc0c956bece47340ea1367"
  }
]
```

... why is the 

```
    "balance": 0,
```
?
I would expect it to now show either 1337 + 7331 = 8668 or at least the patched 7331. No?

**Comment by drandreaskrueger** [comment]
> Or ...

websockets?

**Comment by hackaugusto** [comment]
Closing in favor of #1085 

> Are the attacks over now? What is a good gasPrice right now? Thx.

Keep the gas price high for the time being.

> Your default waiting time is too short?

In some cases, yes, same problem as https://github.com/raiden-network/raiden/issues/1058

> websockets?

That was our initial approach, we moved away from it because of bad support for websockets with gevent library, for the time being this is out of scope.
