### ISSUE TITLE
documentation: /api/1/ or /api/v1/ ?  404 Not Found

### ISSUE THREAD

**Issue by drandreaskrueger** [raiden-network/raiden#1087]
Probably just a typo?

> GET /api/1/address    
> http://raiden-network.readthedocs.io/en/stable/api_walkthrough.html#scenarios

but  

> PUT /api/v1/connection/0xc9d55C7bbd80C0c2AEd865e9CA13D015096ce671    
> http://raiden-network.readthedocs.io/en/stable/api_walkthrough.html#connect

I am asking, because for both `/1/` and `/v1/` I get the same answer:

```
curl -X GET http://127.0.0.1:5001/api/1/connection/0x583cbbb8a8443b38abcc0c956bece47340ea1367 -d '{"funds":2000}' --header 'Content-Type: application/json'
curl -X GET http://127.0.0.1:5001/api/v1/connection/0x583cbbb8a8443b38abcc0c956bece47340ea1367 -d '{"funds":2000}' --header 'Content-Type: application/json'

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>404 Not Found</title>
<h1>Not Found</h1>
<p>The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.</p>
```

Thanks.

### System description
same as [before](https://github.com/raiden-network/raiden/issues/1085)

**Comment by LefterisJP** [comment]
It's a typo which has been fixed in latest master. Unfortunately `readthedocs` documentation updates only when we make a release and so far we have made none after the developer preview.

You can see it here: https://github.com/raiden-network/raiden/blob/master/docs/rest_api.rst#connecting-to-a-token-network

And it's `connections` not `connection`.


Sidenote: Thank you for opening all these issues. At the moment we are also rather busy with the raiden auction so apologies if we are not replying fast enough.

Some of the things you mention could also be solved by a simple chat in gitter: https://gitter.im/raiden-network/raiden instead of opening new issues.

**Comment by drandreaskrueger** [comment]
> typo ... latest master. Unfortunately readthedocs ...

Good to know, thanks.

> Sidenote: Thank you for opening all these issues.   

A pleasure.

> rather busy with the raiden auction  

Good luck with that then. May it go well. Once you have proper funding, you can repair all this ;-)

> so apologies if we are not replying fast enough.  

Don't worry. This type of communication is meant to by asynchronous - whenever anyone finds the time, there is an answer. I understand that. 

I also cannot dedicate more time to this than I do. And when I do, none of you might be awake:

> Some of the things you mention could also  
> be solved by a simple chat in gitter:   
> https://gitter.im/raiden-network/raiden 

Yes, but beforehand no one knows which thing can be solved in a chat, and which cannot.  
Moreover, waiting for someone to arrive in the chat is not nice.  
Plus, there is no good usable archive of the chat, no?  

> instead of opening new issues.

I don't mind opening issues.  And you seem to work well with them too, only closing those which are really solved. I like that.

**Comment by drandreaskrueger** [comment]
> And it's connections not connection.

Thanks. 

    /1/connections

now
```
curl -X PUT http://127.0.0.1:5001/api/1/connections/0x583cbbb8a8443b38abcc0c956bece47340ea1367 -d '{"funds":2000}' --header 'Content-Type: application/json'
```
resulted in the now well-known

```
{"message": "Internal Server Error"}
```

but next time I called it, it returned immediately, with no answer. So I guess something has changed now?
```
curl -s http://127.0.0.1:5001/api/1/channels | jq
[
  {
    "partner_address": "0x18d4971fe30d9d25e450c2a7f0dbfca640aa09a7",
    "balance": 1337,
    "reveal_timeout": 10,
    "settle_timeout": 600,
    "state": "opened",
    "channel_address": "0x321010d493d841941e37ed0071484bfe283b4a5e",
    "token_address": "0x583cbbb8a8443b38abcc0c956bece47340ea1367"
  },
  {
    "partner_address": "0xa286d8e1ad2e82eb01fcdbdedd90a8fdc2d0baab",
    "balance": 0,
    "reveal_timeout": 10,
    "settle_timeout": 90,
    "state": "opened",
    "channel_address": "0x719bccc884140eec7995f6a4b5b66439092928e2",
    "token_address": "0x583cbbb8a8443b38abcc0c956bece47340ea1367"
  },
  {
    "partner_address": "0xfce399a738d8c9ab9817341213c5d411ea92caee",
    "balance": 21993,
    "reveal_timeout": 10,
    "settle_timeout": 600,
    "state": "opened",
    "channel_address": "0x177840481cd3063e9346169a819846600f493fee",
    "token_address": "0x583cbbb8a8443b38abcc0c956bece47340ea1367"
  }
]
```
The middle recipient `0xa286d8e1ad2e82eb01fcdbdedd90a8fdc2d0baab` is not controlled by me, so that must be new channel: `0x719bccc884140eec7995f6a4b5b66439092928e2`

questions:

* your documentation links from channel creation & depositing to transfering tokens (and for a 1-to-1 transfer I would imagine a bidirectionally funded channel is enough?). But as that transfer did not work (see https://github.com/raiden-network/raiden/issues/1086 ) ... I just tried out the `/connections/` call. In short: Is the /connections/ call needed at all?

* to simply send to `0xfce399a738d8c9ab9817341213c5d411ea92caee`  I actually want to use the (already funded) channel `0x177840481cd3063e9346169a819846600f493fee` (channel for the same token).  Why/how can't I do that? Shouldn't 'connections' notice that there is already one connection for that token?

* where are my 2000 tokens now? They don't show up: `    "balance": 0,`

**Comment by drandreaskrueger** [comment]
```
* where are my 2000 tokens now? They don't show up: `    "balance": 0,`
```
Hah.

They are actually there, but it needed this harsh action:

1 kill raiden  
2 start raiden  
3 try again:  

```
curl -s http://127.0.0.1:5001/api/1/channels | jq

[
  {
    ...
    "balance": 1337,
   ...
  },
  {
    "partner_address": "0xa286d8e1ad2e82eb01fcdbdedd90a8fdc2d0baab",
    "balance": 400,
    "reveal_timeout": 10,
    "settle_timeout": 90,
    "state": "opened",
    "channel_address": "0x719bccc884140eec7995f6a4b5b66439092928e2",
    "token_address": "0x583cbbb8a8443b38abcc0c956bece47340ea1367"
  },
  {
    ...
    "balance": 21993,
    ...
  }
]
```

so:

        "balance": 400,

seemingly the 2000 got distributed among ... 5 nodes?


Hmmm ... leaves the other 2 questions up there unanswered, plus the obvious request: Fix this issue that I have to restart raiden, to have complete information about the `/connections/` --> new `/channels/` . 

Reopen?  Thanks.
