### ISSUE TITLE
Define the best polling timeout

### ISSUE THREAD

**Issue by czepluch** [raiden-network/raiden#109]
It seems that if we create a new token, but the block time is too long of the block that the transaction is included in the client times out, and does not register the token, thus making it impossible to open a channel with the token. Unless the token is registered manually.

**Comment by hackaugusto** [comment]
Where does this happen? A unit test or cli usage?

For the cli we should poll until the token is deployed (not merged into master yet):
https://github.com/hackaugusto/raiden/blob/tmux_test_scenario/raiden/console.py#L332-L354

**Comment by utzig** [comment]
I think the issue was happening when creating tokens while running on Morden. Probably the value of `DEFAULT_POLL_TIMEOUT=60` is too low under these circumstance.

**Comment by hackaugusto** [comment]
Closing this since it's under specified, if we need a new polling timeout a new issue can be open with a test and value suggestion.
