### ISSUE TITLE
Initiator should unlock the refunds

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/raiden#1091]
## Problem Definition

The initiator is trying a different route when a refund is received without revealing the lock, this means the amount will stay locked until expiration, reducing liquidity.

## Solution

Reveal the secret when a valid refund is received:

## Tasklist

- [ ] Change refund handling in the initiator state task to reveal the secret if a valid refund is received

**Comment by pirapira** [comment]
The initiator should keep choices. If the initiator chooses to unlock, it loses the mediation fees.  Otherwise, the initiator has to wait till the lock expiration but gets everything back.

**Comment by karlb** [comment]
Irrelevant, since we will remove refund transfers in its current form.
