### ISSUE TITLE
Raiden does not properly start

### ISSUE THREAD

**Issue by diandianxiyu** [raiden-network/raiden#1092]
## Problem Definition
when i start ,then

```
Welcome to Raiden, version 0.1.0!
INFO:raiden.network.sockfactory	trying to find uPnP port mapper... 
ERROR:raiden.network.upnpsock	no upnp providers found 
INFO:raiden.network.sockfactory	uPnP not available, trying STUN for port mapping... 
ERROR:raiden.network.stunsock	STUN failed nat={'ExternalIP': None, 'Resp': False, 'ExternalPort': None, 'ChangedPort': None, 'SourcePort': None, 'SourceIP': None, 'ChangedIP': None}
```

## Solution

eth rpc 

```
./raiden--x86_64.AppImage --keystore-path  ~/.ethereum/testnet/keystore  --rpc --eth-rpc-endpoint "localhost:8545"

```
but ,no use 

## Tasklist

Here provide a checkpoint list of tasks that need to be done in order for this issue to be considered closed.
This will help us evaluate if the issue has been properly addressed.

Example:

- [ x] eth rpc
- [ x] Raiden rpc 
- [ ]  uPnP
- [ ]  STUN
## Only For Bugs

Bother with this section only if you are reporting a bug

### System Description

```
xiaoyu@xiaoyu-Parallels-Virtual-Platform:~/下载$ ./raiden--x86_64.AppImage version
{
  "python_version": "2.7.12", 
  "python_implementation": "CPython", 
  "system": "Linux 64bit_ELF 4.10.0-37-generic", 
  "raiden": "0.1.0"
}
xiaoyu@xiaoyu-Parallels-Virtual-Platform:~/下载$ geth version
Geth
Version: 1.7.2-stable
Git Commit: 1db4ecdc0b9e828ff65777fb466fc7c1d04e0de9
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.9
Operating System: linux
GOPATH=
GOROOT=/usr/lib/go-1.9
xiaoyu@xiaoyu-Parallels-Virtual-Platform:~/下载$ solc --version
未找到 'solc' 命令，您要输入的是否是：
 命令 'solv' 来自于包 'libsolv-tools' (universe)
 命令 'svlc' 来自于包 'vlc' (universe)
 命令 'slc' 来自于包 'heimdal-multidev' (main)
 命令 'solo' 来自于包 'sgt-puzzles' (universe)
 命令 'sol' 来自于包 'aisleriot' (main)
solc：未找到命令
```

**Comment by robertdavid010** [comment]
Have potentially different problem but at same point (Raiden startup)

1. Successfully start raiden as described in docs
2. Multiple network errors (as above). Assumed because I'm not trying to connect to a Raiden network (AFAIK)
3. Recognizes Geth person.account
4. Select account/pubkey
5. Enter password for account/key
6. Get this error:

```
ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8545): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x0000000006f51a28>: Failed to establish a new connection: [Errno 111] Connection refused’,))
```

Running on VM through VitualBox on MacOS host to Ubuntu LTS VM.

Raiden binary install

**Comment by LefterisJP** [comment]
@robertdavid010 Your problem is different. You are not properly connected to your geth instance.

Have you put the `--rpc` flag in your geth command?

**Comment by robertdavid010** [comment]
@LefterisJP thanks. Syncing and awaiting channelManager contract from testnet to be downloaded.

**Comment by robertdavid010** [comment]
FYI the readthedocs docs are missing the `--rpc`

> geth --testnet --fast --bootnodes "enode://20c9ad97c081d63397d7b685a412227a40e23c8bdc6688c6f37e97cfbc22d2b4d1db1510d8f61e6a8866ad7f0e17c02b14182d37ea7c3c8b9c2683aeb6b733a1@52.169.14.227:30303,enode://6ce05930c72abc632c58e2e4324f7c7ea478cec0ed4fa2528982cf34483094e9cbc9216e7aa349691242576d552a2a56aaeae426c5303ded677ce455ba1acd9d@13.84.180.240:30303"

**Comment by LefterisJP** [comment]
The most up to date docs can be found under the [docs](https://github.com/raiden-network/raiden/tree/master/docs) directory. readthedocs.org has not yet been updated.

**Comment by LefterisJP** [comment]
@robertdavid010 readthedocs should now be up to date :)

**Comment by LefterisJP** [comment]
@diandianxiyu Is this still an issue for you?
