### ISSUE TITLE
CLI Configuration

### ISSUE THREAD

**Issue by heikoheiko** [raiden-network/raiden#11]
- [x] create commandline argument parsing for node startup [see **specs**](https://github.com/raiden-network/raiden/issues/11#issuecomment-232079040)
- [x] start interactive repl
- [ ] document usage for manual transfers

**Comment by heikoheiko** [comment]
support for bootstrapping a network of nodes. seed, nodeid based deterministic configuration might be the easiest for now

**Comment by konradkonrad** [comment]
Here is the interface I have in mind:

- start `raiden` command with arguments
 * `eth_rpc_host`
 * `eth_rpc_port`
 * `eth_privkey`
 * `raiden_registry_contract_address`
 * `raiden_discovery_contract_address`
 * `raiden_privkey`
 * `raiden_host=0.0.0.0` 
 * `raiden_port=40001`
 * `raiden_external_host`
 * `raiden_external_port`
- this starts the raiden node and
 * ensures that `*_contract_address` exists
 * registers/updates the `(raiden_external_host, raiden_external_port)` with `ethereum.utils.privtoaddr(raiden_privkey)` at `raiden_discovery_address`
 * enters a REPL with the following `locals`
   * `raiden_cli`
     * property: `blockchain` - the [BlockChainService](https://github.com/raiden-network/raiden/blob/master/raiden/network/rpc/client.py#L49)
      * function: `find_peer_by_endpoint(host, port)` -> `address`
      * function: `find_peer_by_address(address)` -> `(host, port)`

shortcomings:
 - `raiden_external_host` and `raiden_external_port` need to be determined by the user

TODOs:
- `BlockChainService` methods are incomplete: https://github.com/raiden-network/raiden/blob/master/raiden/network/rpc/client.py#L124-L166
- `raiden_discovery_contract` is not implemented yet

**Comment by heikoheiko** [comment]
what about combining endpoints as "host:port" to shorten the argument list. also i'd get rid of all `raiden_*` prefixes. can you support a configuration file too? what are the defaults? 

s/raiden_host/rpc_host/ (or rpc_endpoint if combined)

s/find_peer_by_endpoint/get_address_by_endpoint/ 
s/find_peer_by_address/get_endpoint_by_address/

**Comment by heikoheiko** [comment]
also, why do we need a eth_privkey?

**Comment by konradkonrad** [comment]
sorry, should have noted that the spec is extra verbose to ease understanding.

> why do we need a eth_privkey

My mistake - I thought raiden accounts were different from eth accounts, but ofc they aren't.
Will update the spec accordingly.

**Comment by konradkonrad** [comment]
> can you support a configuration file too?

Yes, my point was to spec out the parameters. How they "enter" is a different issue.

**Comment by konradkonrad** [comment]
> s/raiden_host/rpc_host/ (or rpc_endpoint if combined)

Not sure about the terminology here: `raiden_host` was supposed to be the interface address for the raiden network endpoint (i.e. where to listen for incoming messages). I wouldn't call that RPC, would you?

`raiden_external_host` is the workaround for not doing implicit/automatic NAT punching yet, i.e.

1) raiden service runs internally on the users box on `0.0.0.0` (default) or `127.0.0.1` ==> `raiden_host`
2) users ISP-assigned IP is `23.42.42.23` ==> `raiden_external_host`
same goes for port (or concatinated endpoint tuples)

**Comment by konradkonrad** [comment]
I made some updates

**Comment by konradkonrad** [comment]
This is minimally functional now.

@hackaugusto I could probably use some help to walk through *"the very first manual raiden transfer"* between two local nodes...

**Comment by hackaugusto** [comment]
Given that the `target_address` endpoint is registered and discoverable, and both apps are running and with the socket bound, you just need to:

```python
app.raiden.api.transfer(asset_address, amount, target_address)
```
