### ISSUE TITLE
Define `settleTimeout` minimum block amount

### ISSUE THREAD

**Issue by czepluch** [raiden-network/raiden#110]
30 blocks was just a number I pulled out of the hat. What's an appropriate number for this?

**Comment by heikoheiko** [comment]
depends on the situation. i'd say 6 under the condition that blocks are not full, i.e. disputes can be resolved by according txs (we need an oracle for this).
please note, the timeout should be reset whenever a dispute message is received.

**Comment by hackaugusto** [comment]
Related: #383

**Comment by palango** [comment]
Closed by https://github.com/raiden-network/spec/issues/16
