### ISSUE TITLE
PUT /connections/<token_address> does not answer anything.

### ISSUE THREAD

**Issue by drandreaskrueger** [raiden-network/raiden#1102]
## Problem Definition

`PUT /api/<version>/connections/<token_address>` does not answer anything.

Manual is [there](http://raiden-network.readthedocs.io/en/stable/rest_api.html#connecting-to-a-token-network).

#### reproduce:
start geth, raiden; create channel, deposit, etc., then:  

Step 1: which tokens  
```
curl -s http://127.0.0.1:5001/api/1/tokens | jq
[
  "0x0f114a1e9db192502e7856309cc899952b3db1ed",
  "0x583cbbb8a8443b38abcc0c956bece47340ea1367"
]
```

Step 2: Fund a connection  
```
curl -X PUT http://127.0.0.1:5001/api/1/connections/0x583cbbb8a8443b38abcc0c956bece47340ea1367 -d '{"funds":2000}' --header 'Content-Type: application/json'
```

Result:  

nothing.  

no answer.  

curl just returns control.

The log print shows only that the server notices the query:

```
INFO:raiden.api.rest	127.0.0.1 - - [2017-11-01 16:01:31] "PUT /api/1/connections/0x583cbbb8a8443b38abcc0c956bece47340ea1367 HTTP/1.1" 204 143 0.001128 
```
  

with `-v` switch I see:

```
curl -v -X PUT http://127.0.0.1:5001/api/1/connections/0x583cbbb8a8443b38abcc0c956bece47340ea1367 -d '{"funds":2000}' --header 'Content-Type: application/json'
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 5001 (#0)
> PUT /api/1/connections/0x583cbbb8a8443b38abcc0c956bece47340ea1367 HTTP/1.1
> Host: 127.0.0.1:5001
> User-Agent: curl/7.52.1
> Accept: */*
> Content-Type: application/json
> Content-Length: 14
> 
* upload completely sent off: 14 out of 14 bytes
< HTTP/1.1 204 NO CONTENT
< mimetype: application/json
< Content-Type: application/json
< Content-Length: 0
< Date: Wed, 01 Nov 2017 16:06:26 GMT
< 
* Curl_http_done: called premature == 0
* Connection #0 to host 127.0.0.1 left intact
```

### System Description

```
source env/raidenpython/bin/activate; raiden version; geth version; solc --version; uname -a; deactivate

{
  "python_version": "2.7.13", 
  "python_implementation": "CPython", 
  "system": "Linux 64bit_ 4.9.0-4-amd64", 
  "raiden": "0.2.0+git.r118f9e76"
}

Geth
Version: 1.7.2-stable
Git Commit: 1db4ecdc0b9e828ff65777fb466fc7c1d04e0de9
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.7.3
Operating System: linux
GOPATH=/home/akrueger/Documents/Code/go
GOROOT=/usr/local/go

solc, the solidity compiler commandline interface
Version: 0.4.16-develop.2017.9.25+commit.d7661dd9.Linux.g++

Linux ... 4.9.0-4-amd64 #1 SMP Debian 4.9.51-1 (2017-09-28) x86_64 GNU/Linux

```

---

greetings to [Cancun](https://www.youtube.com/watch?v=Yo9o5nDTAAQ) :-)

**Comment by hackaugusto** [comment]
@drandreaskrueger What is your expected result? This endpoint is used to allow Raiden to manage funds on behalf of the user. Channels are opened asynchronously, we don't have much information to report once the request succeeds.

**Comment by drandreaskrueger** [comment]
>  What is your expected result?

Any answer would do. 

If I do a curl call

    curl -X PUT http://127.0.0.1:5001/api/1/connections/0x583cbbb8a8443b38abcc0c956bece47340ea1367 -d '{"funds":2000}' --header 'Content-Type: application/json'

it is odd to not see *any* reaction to that.

The command is accepted, and I am back in my bash, but I have no feedback about what just happened.

Possible answers I could imagine:

    {"success": true}

or

    {"success": false, error: "not enough funds"}
    {"success": false, error: "token contract does not exist"}

or 

    {"success": true, "TxHash" : "0x04f1e48f170d0704ed1890771882ea984aecfb1e9ed4b9b561de29232090b88e"}


I see your point:

> we don't have much information to report once the request succeeds.

but I guess whatever you do internally after my `PUT .../connections/<token>`  ... you would know whether an exception was thrown, or whether your code went through without problems - right? In the latter case, why not return a `{"success": true}`  ?

**Comment by LefterisJP** [comment]
This issue has been handled. There is no return if all is succesfull as the code is 204 no content. If there are errors either a `402 Payment Required ` or a `408 Timeout` is returned.
