### ISSUE TITLE
ERC20 Recover tokens transferred with transfer instead of transferFrom

### ISSUE THREAD

**Issue by Dexaran** [raiden-network/raiden#1105]
## Problem Definition

Raiden netting channel contract is a special contract that is designed to work with token deposits.

It requires users to send tokens to this contract using [deposit](https://github.com/EthereumCommonwealth/raiden/blob/master/raiden/smart_contracts/NettingChannelLibrary.sol#L67) function which will call the `transferFrom` function of the desired ERC-20 token.

ERC-20 token standard suffers critical security problem: it has two ways to transfer funds (1) [transfer](https://github.com/EthereumCommonwealth/raiden/blob/SafeRaiden/raiden/smart_contracts/Token.sol#L16) function and (2) [approve + transferFrom](https://github.com/EthereumCommonwealth/raiden/blob/SafeRaiden/raiden/smart_contracts/Token.sol#L23,L29) mechanism. The first method is usual method to transfer/deposit tokens for most users and third party services.

If the user deposits the ERC-20 tokens into the netting channel contract using the `transfer` function, the tokens will get stuck inside your contract without any possibility to recover them. **Which means that it will result in loss of money for Raiden users.**

You can read more about ERC20 critical problems [here](https://medium.com/@dexaran820/erc20-token-standard-critical-problems-3c10fd48657b). [Here](https://docs.google.com/document/d/1Feh5sP6oQL1-1NHi-X1dbgT3ch2WdhbXRevDN681Jv4/edit) you can find a small presentation as well.

Each contract that does not allow to extract ERC20 tokens will be a potential token trap. This problem already results in loss of more than $400,000. ([Read this](https://www.reddit.com/r/ethereum/comments/6e8y9o/the_ens_contract_becomes_token_holder_erc20/) or [this](https://www.reddit.com/r/ethereum/comments/6uckdx/reminder_about_problems_of_most_erc20_tokens/) for example).

Again, relying on ERC20 token `transferFrom` deposit mechanism is guaranteed to lead to a loss of money for your users.

## Solution

You **must** reject accidental token `transfer`s by analogy with how the contract rejects accidental Ether transfers. Unfortunately, you can't because of ERC20 token suffers one more critical problem: lack of [event handling](https://en.wikipedia.org/wiki/Event_(computing)) mechanism (transaction is event in this case).

There are two ways to avoid the described problem:

1. Implement a special function that will allow a centralized trusted party to extract any stuck ERC20 token from netting channel by default. In this case, you will likely act as trusted party and you should refund all the users manually. 

https://github.com/EthereumCommonwealth/raiden/blob/SafeRaiden/raiden/smart_contracts/NettingChannelLibrary.sol#L434-L438

2. Do not work with ERC20 tokens at all. Personally I think that relying on mechanism that is guaranteed to result in loss of funds for your users is not a good idea.

**Comment by hackaugusto** [comment]
@Dexaran Thanks for opening the issue.

This is a problem that [we are aware of](https://github.com/EthereumCommonwealth/raiden/blob/ed219895d2bb82c7c4fb8d4fa47dc809e1a39d4e/raiden/smart_contracts/NettingChannelLibrary.sol#L303-L306).

We are not the authors of the tokens used with Raiden, and sadly there are ERC20 tokens in the wild, not supporting these tokens is not an option IMO. That doesn't mean that we won't support ERC223, nor that we require the ERC20.

Regarding your proposed solution 1.:

> Implement a special function that will allow a centralized trusted party to extract any stuck ERC20 token from netting channel by default. In this case, you will likely act as trusted party and you should refund all the users manually.

This is probably the path forwards, with the added constraint on the recovered amount to be at most equal to the superfluous amount.

**Comment by robertdavid010** [comment]
Is ERC223 considered safe?

**Comment by LefterisJP** [comment]
There is nothing actionable for the Raiden client in this issue. Closing.
