### ISSUE TITLE
The channel data and other data are store in only memory or  store in local db?

### ISSUE THREAD

**Issue by SmartMeshFoundation** [raiden-network/raiden#1114]
## Problem Definition

Does the channel data and other data are store in only memory or  store in local db?  if only store in memory, if the raiden node restarted,the channel data or other translate data are losed?

**Comment by hackaugusto** [comment]
It's saved to disk.

ATM it requires a clean shutdown for the data to be properly saved (1), once this issue https://github.com/raiden-network/raiden/issues/507 is done the write-ahead-log will provide durability guarantees for hard failures.

1- For a clean shutdown uses either: `SIGINT` 2 (this is control-c), `SIGQUIT` 3, or `SIGTERM` 15.
