### ISSUE TITLE
Add lock.amount to the SecretRequest message

### ISSUE THREAD

**Issue by pdobacz** [raiden-network/raiden#112]
In a situation where there is a path: A-B-C:

A sends a locked transfer to C and A receives secret request -- does A know what transfer C actually got? For example whether C really got the amount A sent (excluding fees of course)? If so, how?

Heiko:

> hashlock is the transferid but A needs to rely on Cs word, that a certain amount was received or not. in practice it will work by C rejecting payments (CancelTransfer) which do not correspond to an expected amount.

**Comment by hackaugusto** [comment]
> disclosing received amount
Each hop in the chain needs to know the transfered amount to control the balance/locked_amount, I'm afraid we cannot hide this information (but the sender and target could be hidden with onion encryption).

> A sends a locked transfer to C and A receives secret request -- does A know what transfer C actually got?
No, B could change the `lock.amount`  and keep the `lock.hashlock` and A that wouldn't know.

Possible solutions:
- Add lock.amount to the SecretRequest message.
- For some user cases the transfered amount can be agreed before hand and `C` would be able to check the it (eg. decentralized exchanges were the amount are predefined)

**Comment by pdobacz** [comment]
> For some user cases the transfered amount can be agreed before hand and C would be able to check 

I imagine it would require C to be able to "hold off" sending of `SecretRequest` message for a given `hashlock` (or `transfer_id` after #139), until C is able to check it?

> Possible solutions

I think, from my POV both solutions will work. I guess they both have their use cases. Do you think there is an option of supporting both scenarios, i.e. it's up to C's decision, whether C includes `lock.amount` in SR messages or defers sending SR messages until some condition is met?

**Comment by hackaugusto** [comment]
> I imagine it would require C to be able to "hold off" sending of SecretRequest message for a given hashlock (or transfer_id after #139), until C is able to check it?

I'm assuming that A and C agree on the transferred amount before A starts the transfer, through whatever means available, once the MediatedTransfer is received the check should be as trivial as a number comparison, it is up to C to hold off or not the `SecretRequest` (up to the lock expiration).

> Do you think there is an option of supporting both scenarios

Both strategies could be supported, but I have no opnion on it yet.

> it's up to C's decision, whether C includes lock.amount in SR messages or defers sending SR messages until some condition is met?

Either strategy allows C to hold the SecretRequest message (a pre agreement on the amount doesn't eliminate the need for the SecretRequest, and it's under C's control when the message is sent)

**Comment by pdobacz** [comment]
>  it's under C's control when the message is sent

oh I wasn't aware of that, how does C do that with the current API (or is it planned to be added)? I was looking for something like `raiden_api.allow_sending_secret_request(id)`.

**Comment by hackaugusto** [comment]
> oh I wasn't aware of that, how does C do that with the current API (or is it planned to be added)? I was looking for something like raiden_api.allow_sending_secret_request(id).

Ohh, no, we don't have an API for this behavior. I just wanted to say that both strategies for checking the amount allow C to hold the SecretRequest (also, we dont have this feature in a milestone, fell free to open an issue though :) ).

**Comment by pdobacz** [comment]
OK, Thank you very much!

I've opened #142 and renamed this one, to be more specific

**Comment by hackaugusto** [comment]
This was implemented by bbc5413edce41fe90ec3c8dc777f57e5371dd9a0
