### ISSUE TITLE
smart contract about EndpointRegistry.sol 

### ISSUE THREAD

**Issue by SmartMeshFoundation** [raiden-network/raiden#1127]
## Problem Definition
when i read the source code，i found the smart contract “EndpointRegistry.sol”， the contract support  findEndpointByAddress  function，from it we can pass the ethereum wallet address param that return the raiden node ip and port later you can tranlate to it . so when i create the channel ,i need to call the smart contract (EndpointRegistry.sol) to record the ip and port ,if it is sure, may be when i change the computer or change the computer ip , it does not work or i need to recall smart contract (EndpointRegistry.sol) to update the information,but if that it will need ethereum gas to do it once again .  Do I have an exact understanding?

**Comment by LefterisJP** [comment]
This registry contract is only called by raiden at startup to record your node's ipaddress and port combination. Then it it is queried whenever you need to send a message to an address to find its ip/port.

**Comment by andrevmatos** [comment]
Yes, it's correct. #1018 is intended to monitor network/ip/endpoint changes and send a transaction to update your address on the registry.

**Comment by SmartMeshFoundation** [comment]
@andrevmatos   update  address to smart contract “EndpointRegistry.sol”,it need to cost gas,if my node is mobile network and the ip always change, so  even the transaction  don't cost gas, but frequent write to smart contract is cost gas,i think it is no cost！

**Comment by andrevmatos** [comment]
If you're on a mobile network, you probably won't host a full node, this is the perfect case for light clients. Full nodes are expected to run on servers or, at least, computers with good/stable/cheap connection, which won't require updating the registry often. For now, the only way to discover nodes is through this on-chain registry, but we're considering options that may not require it in the future.
