### ISSUE TITLE
Install smart contract filters using from_block equal to the contract creation.

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/raiden#1129]
## Problem Definition

Filters for a smart contract must be installed either from block 0 or when the contract was created.

My assumption is that there is a race condition among deposit transactions and filter installation. E.g. for a netting channel, the deposit transaction could be mined faster than the filter is installed, and the event would be missed.

Here is the code execute when a new channel is created:

- [ContractReceiveNewChannel](https://github.com/raiden-network/raiden/blob/master/raiden/event_handler.py#L207-L208`) is handled, since the channel appears in the channels list
- As part of the new channel event [the channel is registered](https://github.com/raiden-network/raiden/blob/3f8758c85fa84bbf0ae8ca68d2ae8990dde60a5e/raiden/event_handler.py#L245-L248)
- During channel registration [a filter is installed](https://github.com/raiden-network/raiden/blob/3f8758c85fa84bbf0ae8ca68d2ae8990dde60a5e/raiden/raiden_service.py#L794), this was suppose to get the deposit events.

## Solution

Install the filter during channel registration using the `from_block` equal to the creation block:

- [ ] token network registry
- [ ] token network

## Related

#669 On Restart: Query all events from the latest known block 

## Tasklist

- [ ] Install the filter using the `from_block`  equal to the block in which the channel was created

**Comment by hackaugusto** [comment]
This will be more important with https://github.com/raiden-network/raiden-contracts/tree/master/raiden_contracts , because we will rely exclusively on events to restore the on-chain state.

**Comment by czepluch** [comment]
So, apparently, after being quite confused and talking with Augusto it turns out that this issue was more or less solved with https://github.com/raiden-network/raiden/pull/1385. What's left to do is to write a test that makes sure that the `from_block` is optimal. I don't really have a good idea of how to check this. @LefterisJP or @hackaugusto if you have any ideas, please let me know.

**Comment by LefterisJP** [comment]
> What's left to do is to write a test that makes sure that the from_block is optimal

What do you mean by optimal here? @czepluch

**Comment by czepluch** [comment]
The filters can either be installed with `block_number` 0 or when a contract is deployed. We should find out if it's more efficient to do the latter upon recovering the state and replaying events. I would assume so, but I am not entirely sure how to prove it.

**Comment by andrevmatos** [comment]
@czepluch On µRaiden we had issues with it, it was actually way more efficient to cap the `from_block` to some point equal or before contract deployment (we had to hardcode it in config), for geth (parity always performed better on this, did this optimization under the hood). Not sure if geth is still affected after 1.8 wave of optimization, event scan was one of the focuses.

**Comment by LefterisJP** [comment]
It depends on the client's implementation of the filter.

**Comment by hackaugusto** [comment]
There is no JSON RPC interface to find the transaction / block for which a given smart contract was deployed, so we cannot properly install the filters using a `from_block` for the `TokenNework` smart contracts deployed by the `TokenNetworkRegistry`, since on restarts we continue from the block_number of the last run, things should be fine for now.

**Comment by pcppcp** [comment]
the thing we did in uRaiden was a hardcoded deploy block value for different networks, because of the 
same exact reason @hackaugusto mentions. But if the last block is properly cached and used on restart, it's not that much of an issue.

**Comment by LefterisJP** [comment]
Exactly as @pcppcp says. The raiden contract addresses are hard coded anyway in the client. Why not also:

- Hard code deployment block of the deployed registry (can't do the same for each token network, but still it's better than the zero block).
- Add an option to manually input deployment block in case you want to point to non-default token network.

In either case this is more of an optimization and heavily depends on how the underlying client implements event filtering.

**Comment by LefterisJP** [comment]
Should we close this due to no action needed anymore or just implement what I wrote [above](https://github.com/raiden-network/raiden/issues/1129#issuecomment-392733610)

We can add a hard-coded option which is also tweakable by a CLI argument to set [this](https://github.com/raiden-network/raiden/blob/b17fda83e938f57ba7fa23c5149074ad9e79acb5/raiden/raiden_service.py#L250) block number.

**Comment by hackaugusto** [comment]
This should be fairly easy, now the block number is part of the deployment metadata, it's available [here](https://github.com/raiden-network/raiden-contracts/blob/dbc4d03b6818417701afefd00d0fd7148242374f/raiden_contracts/contract_manager.py#L33)

**Comment by hackaugusto** [comment]
This is not an issue anymore:

- ATM new token network registries are not followed, so we don't have to worry about it.
- If the node is starting for the first time:
  - [The block the token network registry](https://github.com/raiden-network/raiden/blob/3e43309c4d65ae8e2f422521f43002b747f8d760/raiden/ui/app.py#L284-L286) was deployed is used.
  - After https://github.com/raiden-network/raiden/pull/4899 , if the fallback is also configured per network. If the smart contract is not deployed by us, the optimal value is not used but we use a hard fork as a base value to trim a significant number of unnecessary blocks from the filter queries.
  - The token networks will be followed as the events are processed, and the new filters are installed  [starting at the block they were created](https://github.com/raiden-network/raiden/blob/3e43309c4d65ae8e2f422521f43002b747f8d760/raiden/blockchain_events_handler.py#L20-L36) 
- If the node is running:
   - New token networks [have the filter installed exactly at the block they were created](https://github.com/raiden-network/raiden/blob/3e43309c4d65ae8e2f422521f43002b747f8d760/raiden/blockchain_events_handler.py#L20-L36)
- If the node is starting:
  - the last confirmed block is used as [a starting point](https://github.com/raiden-network/raiden/blob/3e43309c4d65ae8e2f422521f43002b747f8d760/raiden/raiden_service.py#L373-L376), so no unnecessary blocks are queried.

There are also some checks done on different places of the code base that use filters, these are addressed by #4899
