### ISSUE TITLE
Raise an exception if the NettingContract events were not emmited

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/raiden#113]
Check the calls to the following contract's methods succeded by veryfing that the corresponding event was emmited in the `network.rpc.client`:
- NettingChannelContract
  - [ ] settle
  - [ ] updateTransfer
  - [ ] deposit
  - [ ] unlock
  - [ ] close
- ChannelManagerContract
  - [x] ~~newNettingChannel~~ Checking if the returned address has code
- Registry
  - [x] ~~addAsset~~ Checking if the returned address has code

**Comment by konradkonrad** [comment]
NettingChannelContract is missing the `close` method, no?

**Comment by hackaugusto** [comment]
added

**Comment by sdtsui** [comment]
Hi @hackaugusto @konradkonrad !

I'm interested in learning the codebase. Is this improvement still desired?  If so, I'd like to help.

![https://puu.sh/wUar5/095815509b.png]()
Are there any commits I can reference, for these checked off items, so that I can understand what it means to verify that corresponding events are being emitted in `network.rpc.client`?

Thank you.

**Comment by LefterisJP** [comment]
Hey @sdtsui. The checked off items check for a different thing thanthe non-checked off ones.They check that there is code in the deployed address, while the non-checked off items specify that they should wait for the corresponding event to be emitted and seen.

This would need some changes in the corresponding rpc client functions. For example [here](https://github.com/raiden-network/raiden/blob/459c13e742e84441e7f3a6dab2fe46b4d9d8b6e8/raiden/network/rpc/client.py#L1091) is where the `settle()` function would need to be checked.

You would need to make sure that the blockchain event gets emitted. So you would need to use the proper rpc calls to listen for the correct event and the correct arguments.

**Comment by czepluch** [comment]
See this (https://github.com/raiden-network/raiden/blob/0e5404a2a9beebfb02acb4f9170a1aa4e99b52a2/raiden/network/rpc/client.py#L67) for a way to check if a transaction threw.

**Comment by hackaugusto** [comment]
This if fixed. All transactions have the receipt checked with `check_transaction_threw`, all calls that return empty check if the smart contract called selfdestruct.
