### ISSUE TITLE
Enable macOS tests on travis

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden#1130]
After #1021 is fixed we should enable macOS testing on travis.

**Comment by ulope** [comment]
I'm not sure we should at this point. As long as travis continues to be so badly underequipped with mac workers we would add around an hour of waiting time alone to every test run during peak hours.

**Comment by LefterisJP** [comment]
Perhaps after getting more jobs in Travis we can revisit this issue and run a few tests to see if OSX travis availability has increased? In Rotkehlchen the OSX job is a tad bit slower but does not take longer than the Linux job to start.

**Comment by ulope** [comment]
We haven't encountered any mac specific issues in Raiden itself for a long time. Therefore it seems not worth to spend the money on Circle CI.

If that changes we can re-visit this.
