### ISSUE TITLE
Unreliable health check

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/raiden#1133]
## Problem Definition

Multiple users are reporting problems with the health check (#1020 #1086 also on gitter).

The problem is that even with the nodes online the health check is not changing the state of the nodes to `reachable` and the transfer fails because there is no route available. Some of these users are running all nodes and opening direct channels, so it's known that both nodes are online and there is a route.

This needs further investigation, the expected behavior is:

- On a fresh run (without a database):
  - The node will query the blockchain and get a [list of all channel that it is a participant](https://github.com/raiden-network/raiden/blob/3f8758c85fa84bbf0ae8ca68d2ae8990dde60a5e/raiden/raiden_service.py#L728-L741).
  - For each of its partners a health check will be [started](https://github.com/raiden-network/raiden/blob/3f8758c85fa84bbf0ae8ca68d2ae8990dde60a5e/raiden/raiden_service.py#L297-L304)
- For a running node:
  - The node queries the [blockchain each block for events](https://github.com/raiden-network/raiden/blob/3f8758c85fa84bbf0ae8ca68d2ae8990dde60a5e/raiden/raiden_service.py#L278)
  - When a [new channel is found](https://github.com/raiden-network/raiden/blob/3f8758c85fa84bbf0ae8ca68d2ae8990dde60a5e/raiden/event_handler.py#L207-L208), it's [registered and the healthcheck is started](https://github.com/raiden-network/raiden/blob/3f8758c85fa84bbf0ae8ca68d2ae8990dde60a5e/raiden/event_handler.py#L244-L250)

From the workflows outlined above, participants of the same channel are pinging each other using the public ip / port, that should be sufficient for nat travesal allowing the nodes to communicate.

**Comment by hackaugusto** [comment]
> This appears to happen when the network_state changes from "unknown" to "unreachable". While the network state is "unknown" the transfer will seem to succeed, but the balance is not changed upon checking the channels via the api.

https://github.com/raiden-network/raiden/issues/1086#issuecomment-337443336

@konradkonrad Could it be a problem with our health check retry defaults? What you think about decreasing the default from [10 seconds](https://github.com/raiden-network/raiden/blob/master/raiden/settings.py#L26) to something else?

**Comment by konradkonrad** [comment]
> What you think about decreasing the default from 10 seconds to something else?

Not sure; halving it would not hurt. However, the issues can arise from a range of problems, and inspecting the NAT state is hard.

> From the workflows outlined above, participants of the same channel are pinging each other using the public ip / port, that should be sufficient for nat travesal allowing the nodes to communicate.

That is only the case, if the nodes are behind a non-symmetric NAT, i.e. one with fixed port mappings.

One way forward I could see is being more defensive, as in: instead of starting transfers to/via `unknown` network state partners, we could deny them and always wait for a known network state. Users would need to try again themselves after some time. If channel partners can not find each other, we would know that our NAT traversal attempts failed.

However, this would not help for `target` nodes of `unknown` state, because we cannot make target nodes ping us (for invitation) with the current set of protocol messages. 

Here our current strategy is to start the health check (for invitation purposes) when the transfer is initiated. If the target is behind NAT, it won't respond to our pings until it learned about our transfer and hence starts the health check to us, the initiator, themselves.

**Comment by hackaugusto** [comment]
> Not sure; halving it would not hurt

I asked ramxis on gitter to try this setting, and it didn't work for his case.

I wonder if the problem isn't related to the [invitation timeout](https://github.com/raiden-network/raiden/blob/master/raiden/settings.py#L27) being set to 3 minutes. For instance, on my router according to this [website](http://nattest.net.in.tum.de/individualResult.php?hash=18cc42083a5592cf11438f219979a738) the timeout is 14seconds, assuming that this is also used to clear up the mappings, that means only on 8% of the time I would have the mapping working on my router.

> That is only the case, if the nodes are behind a non-symmetric NAT,

That is the assumption, please check this report: https://gitter.im/raiden-network/raiden?at=5a1b88176b5080350f343315 . It may be a problem with hairpinning

> instead of starting transfers to/via unknown network state partners, we could deny them and always wait for a known network state

This was changed by #1088, the nodes have the state changed from unknown to unreachable, but not to reachable.

**Comment by konradkonrad** [comment]
> according to this website the timeout is 14seconds

nice test page! if `invitation timeout` of 180 seconds means, that we only send a second invitation ping after 3 minutes, we should by all means lower that value. probably to some small value like 10 seconds. we should remember to send users that have connectivity problems to that test page.

**Comment by hackaugusto** [comment]
> if invitation timeout of 180 seconds means, that we only send a second invitation ping after 3 minutes, we should by all means lower that value.

Yes, that is correct, this is the rough outline:

The current implementation starts with [frequent retries](https://github.com/raiden-network/raiden/blob/master/raiden/network/protocol.py#L383-L390), by default it will be only [2 retries](https://github.com/raiden-network/raiden/blob/master/raiden/settings.py#L25) with a [10 second](https://github.com/raiden-network/raiden/blob/master/raiden/settings.py#L26) interval in between, if both these retries fail, then it falls back to the [slower path](https://github.com/raiden-network/raiden/blob/master/raiden/network/protocol.py#L395-L425), which will send the invitation ping every [3 minutes](https://github.com/raiden-network/raiden/blob/master/raiden/settings.py#L27)

I'm considering using the echo node to do a nat punch test when raiden is started.

**Comment by ramxis** [comment]
The main problem is that raiden health check /ping/ack method is being very unreliable. 
It works some times and completely refuses  at other times. I could see ping/ack messages between my two nodes located in the same network, and with a third remote node consistently for 3 days (Raiden nodes were started each night left running and powered down after 1 to 2hrs ) . 
But then for the last 48 hrs i could not see any ping/acks between any of my nodes or with the remote node. Even manually running **health_check_for(node)** command from console was not working. Then tonight when i started raiden nodes they decided to see ping/ack with each other. I have not altered my testing methodology one bit or changed network conditions in any way. I am assuming there is something either in health_check or may be even Nat punching that is not working reliably.

**Comment by nkbai** [comment]
use communication with a node to keep nat punching , it maybe not a good solution.
using stun's own protocol maybe better

**Comment by palango** [comment]
No more UDP transport.
