### ISSUE TITLE
Only open channels with nodes that we can communicate

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/raiden#1142]
## Problem Definition

NAT traversal is a problem big enough that may drive a channel useless, instead of opening a channel to only then finding out that it cannot be used, Raiden should first try to reach a target node and only open the channel if both nodes can communicate.

**Comment by LefterisJP** [comment]
I actually like that idea. At the moment we have this scheme where we ignore the elephant in the room, that is nodes should not go offline. And we happily create channels with anyone even if the other address has never been registered in the endpoint registry or is not online.

I like the idea of introducing a check that the counterparty is online before creating the channel.
@konradkonrad opinions?

**Comment by hackaugusto** [comment]
We would need a TURN / ICE server for this though. Unless we use some sort of onion encryption and existing nodes/paths from the Raiden network to open the NAT (doesn't sound a good idea)

**Comment by LefterisJP** [comment]
I am not working on this so I am unassigning myself.

**Comment by LefterisJP** [comment]
Do we ever plan to implement this? At the moment there is no reachability check at opening a channel.

**Comment by palango** [comment]
https://github.com/raiden-network/raiden/issues/5453 is a subtask of this.

**Comment by hackaugusto** [comment]
implemented by https://github.com/raiden-network/raiden/pull/5633
