### ISSUE TITLE
Upgrade pyethereum to support REVERT

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/raiden#1143]
## Problem Definition

Raiden is currently using a fork of the [upstream pyethereum package](https://github.com/raiden-network/raiden/blob/5c32d29ad2529361e87a55588c460ddbd52ce793/requirements.txt#L4) which doesnt support the REVERT opcode. This breaks tests that go through the failure path

**Comment by palango** [comment]
Is there a special test that failed because of this or tests that we should add?

pyethereum is updated in #1193

**Comment by hackaugusto** [comment]
The existing tests are fine, they were executing the revert as a throw.

This was only problem because we couldn't write tests for the gas usage.
