### ISSUE TITLE
Don't use a timeout in shutdown sequence

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden#1149]
## Problem Definition

Currently a timeout is used in the shutdown sequence if the ethereum node in not reachable.

## Solution

Instead of using a client that tries to reconnect and giving it a timeout we should use a client that doesn't try to reconnect.

**Comment by palango** [comment]
@hackaugusto The original cause of this issue is gone, but there is still a timeout: https://github.com/raiden-network/raiden/blob/d68f002c0b640783d49fe9e42bea17b13dd9915f/raiden/raiden_service.py#L337-L341

**Comment by andrevmatos** [comment]
@palango I should be removing that one in #2208, then the only stop/shutdown timeout left should be the one in `cli`'s `_run_app`

**Comment by palango** [comment]
Nice, then just add this as a fixed issue there.

**Comment by andrevmatos** [comment]
Fixed by #2208
