### ISSUE TITLE
syntax error for deploy.py

### ISSUE THREAD

**Issue by nkbai** [raiden-network/raiden#1166]
## Problem Definition

run tools/deploy.py with python 2.7.3

python deploy.py

  File "deploy.py", line 73
    exec(  # pylint: disable=exec-used
SyntaxError: unqualified exec is not allowed in function 'patch_deploy_solidity_contract' it contains a nested function with free variables

**Comment by LefterisJP** [comment]
@nkbai I can not reproduce your problem with python 2.7.13

Can it be a specific python 2.7.3 problem?

Can you give me more information on:

1. your system and OS
2. how do you run the command exactly? Simply `python deploy.py`  ?

**Comment by nkbai** [comment]
```
bai@ubuntu:~/pyeth/raiden_bak/tools$ python deploy.py 
  File "deploy.py", line 73
    exec(  # pylint: disable=exec-used
SyntaxError: unqualified exec is not allowed in function 'patch_deploy_solidity_contract' it contains a nested function with free variables
bai@ubuntu:~/pyeth/raiden_bak/tools$ md5sum deploy.py
3cfacf9064e9de4cfa6e4c0d720fb651  deploy.py
bai@ubuntu:~/pyeth/raiden_bak/tools$ uname -a
Linux ubuntu 3.16.0-77-generic #99~14.04.1-Ubuntu SMP Tue Jun 28 19:17:10 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
bai@ubuntu:~/pyeth/raiden_bak/tools$ git branch
* master
bai@ubuntu:~/pyeth/raiden_bak/tools$ python -V
Python 2.7.6
```

**Comment by nkbai** [comment]
i'm unfamiliar with python

**Comment by nkbai** [comment]
on my windows ,
it has the similiar error:
```
D:\goethereum\origin\raiden\tools (master)
λ python deploy.py
  File "deploy.py", line 70
    exec(code, JSONRPCClient.deploy_solidity_contract.im_func.__globals__, ctx)
SyntaxError: unqualified exec is not allowed in function 'patch_deploy_solidity_contract' it contains a nested function with free variables

D:\goethereum\origin\raiden\tools (master)
λ python -V
Python 2.7.3
```

**Comment by LefterisJP** [comment]
We do not support windows at the moment, I am sorry.

**Comment by LefterisJP** [comment]
Okay so you need to update to the latest python2 version which is [python 2.7.14](https://www.python.org/downloads/release/python-2714/). We do not support older python version.
