### ISSUE TITLE
Investigate problems with lastlog / lasterr in interactive console

### ISSUE THREAD

**Issue by ulope** [raiden-network/raiden#1168]
## Problem Definition

User `ramix` reported in the Gitter channel that `lastlog()` and `lasterr()` produce no output in the interactive console even though commands that should have produced logs / errors have been performed. 

Screenshots:
![](https://files.gitter.im/raiden-network/raiden/VHpt/Screenshot-from-console-2017-12-01-15-09-14.png)
![](https://files.gitter.im/raiden-network/raiden/Hnt5/Screenshot-from-2017-12-01-15-13-29.png)

Investigate if things broke.

## Solution

Investigate problem.

## Tasklist

- [x] Investigate `lastlog()` / `lasterr()`

**Comment by pcppcp** [comment]
`io.StringIO` requires unicode string and raises an exception if Python's `str` is passed in. Fix will be probably very easy.
