### ISSUE TITLE
Integrate the token network contract

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#1172]
## Problem Definition

Part 2/2 of #1025.

> At the moment whenever we open a channel we create a smart contract per channel. We went with this implementation for simplicity reasons in the beginning but it is not optimal as it increases gas costs for channel opening due to the CREATE operation.

Should be done after https://github.com/raiden-network/raiden/issues/1171

## Tasklist

- [ ] Integrate the [token network](https://github.com/raiden-network/raiden-contracts/blob/7d183081bcd6df06728bdb6b8da581e68c39dbc1/raiden_contracts/contracts/TokenNetwork.sol) into the raiden codebase
- [ ] Remove the old netting channel code

**Comment by loredanacirstea** [comment]
This is currently done. Multiple PRs have been merged since June 1st. We have started using the new contracts from https://github.com/raiden-network/raiden-contracts (including the global `TokenNetwork contract`) since https://github.com/raiden-network/raiden/pull/1684
