### ISSUE TITLE
about test_handle_secretreveal of test_target.py

### ISSUE THREAD

**Issue by nkbai** [raiden-network/raiden#1194]
in function test_handle_secretreveal ,
the fromroute's nodeaddress is initiator, it means that the revealsecret message is send from from_route's nodeaddress, why  the receiver will send this revealsecret message back to initiator?

it's obviously useless.. and why?

**Comment by LefterisJP** [comment]
The `RevealSecret` message is sent from the initiator to the target. The target then sends a secret message back to the initiator as a means of synchronization. This is what this unit test is looking to test for.

You can look up more info on the protocol for mediated transfers [here](http://raiden-network.readthedocs.io/en/latest/spec.html#mediated-transfers).

**Comment by nkbai** [comment]
@LefterisJP this is useful for a mediated transfer ,but useless for a direct transfer.
if there is a channel between A<->B,
but a transfer from A to B is a mediated transfer 
at this condition, Is B really needs send reveal secret to A?
transfer from A to B is a mediated transfer ,which i have tested.

**Comment by LefterisJP** [comment]
oh yes, we no longer have direct transfers in the protocol in order to reduce the complexity of the code and the paths it follows. We just make all transfers behave like mediated transfers.

**Comment by nkbai** [comment]
@LefterisJP  B should send reveal secret to A? when use mediated transfer to simulate direct transfer?

**Comment by LefterisJP** [comment]
The names of the events can be a bit confusing in the code. The protocol is the exact one described in [the link above](http://raiden-network.readthedocs.io/en/latest/spec.html#mediated-transfers) with `initiator` being `A`, `target` being `B` and no mediator. That's how direct transfers work now.

So in the code itself when the `target`, in our case `B`, receives the `RevealSecret` from the `initiator`, in our case `A`, the state machine goes [here](https://github.com/raiden-network/raiden/blob/master/raiden/transfer/mediated_transfer/target.py#L106).

For a succesfull secret then the target will emit a  [`SendRevealSecret`](https://github.com/raiden-network/raiden/blob/master/raiden/transfer/mediated_transfer/events.py#L43) event which will end up in sending a [`RevealSecret`](https://github.com/raiden-network/raiden/blob/master/raiden/event_handler.py#L127) back to the previous hop for synchronization purposes. It basically informs the node of the previous hop that the lock has been released and the token can be withdrawn, either on-chain or off-chain. But in our case the previous hop is actually the `initiator`.

**Comment by nkbai** [comment]
do you mean that:
A needs a revealsecret message from B, so that A can send the new balance proof to B?

so in this condition, B really needs send a revealsecret message to A.

**Comment by LefterisJP** [comment]
Both A and B send SecretReveal to each other as part of the protocol.

**Comment by LefterisJP** [comment]
Closing this as it's a question and not a code issue. For further questions please use the gitter channel: https://gitter.im/raiden-network/raiden
