### ISSUE TITLE
can raiden restore from a broken transaction?

### ISSUE THREAD

**Issue by nkbai** [raiden-network/raiden#1197]
hi,
i'm writing another version of raiden using golang.
the restore_channel  function of raiden_service tries to  restore the channel state,but  i don't know how to retore from a broken transaction.

for example A has a MediatedTransfer with B.
now the state is :
A has send  a revealsecret message to B,  before A  receive B's revealsecret message, A have to stop because of an user request( ctrl +c). but A saved this state.

when A restart ,can A go on this transaction to avoid that B close the channel between A and B?

**Comment by nkbai** [comment]
the  identifier_to_statemanagers  data may save the secret of  this transaction, but A's ChannelEndState is wrong, and A doesn't know the hashlock after restart.

**Comment by hackaugusto** [comment]
Hi @nkbai ,

For the *current* version of the code base, a clean restart is required. I'm currently working on the issue #507 to fix this. So this response will focus on the current code base (as of ca2564bb7043c345ab44325dce5b3a3b0906f51f).

### For the current code base

Given a path A-B, and a mediated transfer from A to B, we have the exchange of the following messages:

```
1. Mediated Transfer from A to B
2. Secret Request from B to A
3. Secret Reveal from A to B
4. Secret Reveal from B to A
5. Secret from A to B
```
If this protocol reached the step 3, B must have received A's `SecretReveal` message and `Ack`ed it, this means the nodes are working on the step 4.

If A restarts with a clean shutdown (ctrl+c and the user waited), all the state for this transfer is saved as part of [initiator state](https://github.com/raiden-network/raiden/blob/master/raiden/transfer/mediated_transfer/state.py#L46-L57).

When the node *A* is restarted the transfer is at the step 4, and *B* is the node that needs to send a SecretReveal to A, B's protocol layer will keep [retring](https://github.com/raiden-network/raiden/blob/master/raiden/network/protocol.py#L149-L152) until either A receives and acknowledged the message, or the channel is closed.

These are the relevant steps:

- [The secret](https://github.com/raiden-network/raiden/blob/master/raiden/transfer/mediated_transfer/initiator.py#L147-L156) is part of the initiator state, set when the route is first used.
- [The transfer state is saved](https://github.com/raiden-network/raiden/blob/master/raiden/raiden_service.py#L134) as part of the clean shutdown.
- [The transfer state is loaded](https://github.com/raiden-network/raiden/blob/master/raiden/raiden_service.py#L394) as part of the initialization.
- While A is restarting B's protocol is [resending the message](https://github.com/raiden-network/raiden/blob/master/raiden/network/protocol.py#L149-L152)
- After A restarts it will receive a message from a retry, and once the message [is fully processed](https://github.com/raiden-network/raiden/blob/master/raiden/network/protocol.py#L850-L853), then A acknowledges the message to B and the protocol continues at step 5.

**Comment by nkbai** [comment]
thank you very much  @hackaugusto 
from code of the master branch.
channelEndState's hashlocks_to_pendinglocks and hashlocks_to_unclaimedlocks don't restore from pickle.
after restart,A's transfer state is right ,but the corresponding channelEndState is wrong.

**Comment by nkbai** [comment]
when restore from snapshot, it tries to retore the protocol's state, 
but it seems useless to retore the protocol's state.
 for example 
A shutdown at step 3, and B doesn't receive the reveal message , B will send secret request again and again.
if B receive the reveal message ,B will try to send revealsecret message repeatly.

if A shutdown at step 1, just let this transfer fail is a better choice.
if A shutdown at any other step, A can restore  as long as B works right.

**Comment by LefterisJP** [comment]
Closing this as it's a question and not a code issue. For further questions please use the gitter channel: https://gitter.im/raiden-network/raiden
