### ISSUE TITLE
maker's lock expiration  when token swap

### ISSUE THREAD

**Issue by nkbai** [raiden-network/raiden#1198]
for example
taker:
{
    "role": "taker",
    "sending_amount": 42,
    "sending_token": "token1",
    "receiving_amount": 76,
    "receiving_token": "token2"
}
maker:
{
    "role": "maker",
    "sending_amount": 76,
    "sending_token": "token2",
    "receiving_amount": 42,
    "receiving_token": "token1"
}

assume that maker and taker have direct channel on both token1 and token2
but token1's channel settle timeout is 600 
token2's channel settle timeout is 6000

In this scenario ,this token swap will fail because of lock expiration. 
but this token swap should be success.

how to rosolve:
1. maker set a short lock expiration :  
```
#lock_expiration = block_number + from_channel.settle_timeout
 lock_expiration = block_number +min(settle_timeout1 ,settle_timeout2)
```
2. taker set a short lock expiration
```
#lock_expiration = maker_paying_transfer.lock.expiration - raiden.config['reveal_timeout']
if "maker_paying_transfer.lock.expiration  is too large" :
     lock_expiration = block_number +min(settle_timeout1 ,settle_timeout2)
```
lines start with "#" are code copied from token_swap.py

**Comment by nkbai** [comment]
of course there are more problems about settle timeout when maker and taker have a long route hop

**Comment by hackaugusto** [comment]
@nkbai Thanks for the issue report.

You're correct, the [code](https://github.com/raiden-network/raiden/blob/ca2564bb7043c345ab44325dce5b3a3b0906f51f/raiden/token_swap.py#L608) is not taking the taker settle timeout.

```python
lock_expiration = maker_paying_transfer.lock.expiration - raiden.config['reveal_timeout']
```

The correct fix however, is to use the minimum of channel used by the *taker* for the second mediated transfer:

```python
max_lock_expiration = taker_paying_channel.settle_timeout + raiden.get_block_number()
expiration_blocks = min(max_lock_expiration, maker_paying_transfer.lock.expiration)
lock_expiration = expiration_blocks - raiden.config['reveal_timeout']
```

There should be no additional problems with longer hops.

**Comment by nkbai** [comment]
@hackaugusto  thanks very much
and another error:
token_swap.py line 770
self.async_result.set(False)

taker doesn't have a async_result member

**Comment by LefterisJP** [comment]
@nkbai thanks for the report will take a look at this and use another issue to track its progress: #1212
