### ISSUE TITLE
Add mypy analysis to CI

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden#1206]
## Problem Definition

Currently we don't use type annotations for type checking

## Solution

Add a mypy check to the CI builds.
Currently `mypy` needs some improvements (e.g. https://github.com/python/mypy/issues/604)

## Tasklist

- [ ] Run `mypy` locally and fix type annotations/bugs
- [ ] Add `mypy` check to CI builds

**Comment by palango** [comment]
Some WIPs: #3034 #3040

**Comment by hackaugusto** [comment]
This is being done gradually, this issue is not really good on its own.
