### ISSUE TITLE
Mediated transfers should work between unknown peers (with available path)

### ISSUE THREAD

**Issue by utzig** [raiden-network/raiden#121]
Mediated transfers should work between unknown peers that have a valid path.

Steps to test:

```
1) Create a token and run 3 raiden nodes: A, B and C
2) Open a channel between node A and B
3) Open a channel between node B and C
4) Send a transfer from A to C
```

This is failing if it's done on the first run.

**Comment by heikoheiko** [comment]
If what is done the first time? 4?
Could you narrow down, what the issue is? Are the channels open as expected? Is the network graph in sync? is there are test for this?

**Comment by utzig** [comment]
Mediated transfers for unknown nodes are blocking here:

https://github.com/raiden-network/raiden/blob/master/raiden/raiden_service.py#L315

This only checks the local graph for edges. A more correct way would be to check if there is any valid channel available which could be used as path. For example:

```
if len(asset_manager.partneraddress_channel) == 0:
    raise NoPathError('No path to address found')
```

This way as long as there is a valid path, we will correctly create the mediated transfers and the transfer will work.

If there's no path some of the `*MediatedTransfer` tasks will throw a `NetworkXNoPath` exception in `channelgraph.get_shortest_paths` which needs to be handed from outside the greenlets.

**Comment by utzig** [comment]
@heikoheiko:

Precondition is: the token did not exist and was just created on this session, and no channels were ever opened between the running nodes.

Opening the channel between A and B enables payments between both in both directions. Same happens for B and C if a channel is opened between them. But transfers between A and C and C and A don't go through.

The graph in node A is not being updated when a channel is opened between B and C but that should not be a problem at first because as long as we send a mediated transfer to B and let B do its work all is good.

There is a mediated transfer test that is passing but I didn't really check the fixtures we're using to know if they are not taking over some of the responsibility of the `transfer` code and always making it work.

**Comment by hackaugusto** [comment]
New channels are registered through events:

https://github.com/raiden-network/raiden/blob/master/raiden/raiden_service.py#L504-L522

The condition for ignoring the channel is incorrect and should add the path to the local graph before returning, eg.:

```python
# add this to the top of the event handler and remove from AssetManager::register_channel
asset_manager.channelgraph.add_path(
    event['participant1'],
    event['participant2'],
)
```

**Comment by utzig** [comment]
@hackaugusto Check if PR #123 is what you had in mind.

This doesn't seem to work very reliably. It seems that sometimes events come in, sometimes not (for some channels).

I created a channel A -> B, received two new channel events on A and one in B. The graph of both looks ok (not sure what the duplicated event for A was). I opened another instance C, and opened a channel between B -> C. B and C now both got events and had the graph updated with all nodes, but A never got this event. So it was possible to transfer from C -> A but not A -> C.

Second time I tried similar problem but this time C never got the events, so A could reach C but C could not reach A.

Would be nice if someone can do some double checking of this.

**Comment by hackaugusto** [comment]
Humm, weird, can you provide the log and a steps to reproduce the problem

**Comment by utzig** [comment]
@hackaugusto Will do it today.

**Comment by czepluch** [comment]
This is also the behavior that I have been experiencing. I can do some concrete testing if you have anything specific you want me to try.

**Comment by utzig** [comment]
What I did was:

1) Put up 3 nodes
2) Create a new token
3) For this token, create a channel between nodes A and B
4) For the same token create a channel between B and C (I always create on node B, could as well try creating on channel C)
5) Sending transfers from A to C and C to A with `master` branch will not work

So, I applied the change suggested by @hackaugusto which is available in PR #123.

After that things got really strange for me because sometimes after doing the previous setup I could send from A to C and sometimes from C to A (at least that's what I remember). But never got it to work 100%. I checked the graphs for each node (can be done with the following commands in the console):

```
a = raiden.managers_by_asset_address[token_address.decode('hex')]
a.channelgraph.graph.edges()
```

and there was no edge created on one of them. I proceeded to add one extra log line to the `channel new` event handler in the `Service` and there was no event being received on one of the nodes (which explains the graph). Have not saved the logs but I can try again later today and attach all logs here.

**Comment by utzig** [comment]
Just updating myself, the place where I logged the event was `RaidenEventHandler::event_channelnew` (not in `Service`).

**Comment by hackaugusto** [comment]
I could not reproduce the error, it worked fine after applying the graph patch. Here is a proper script to test the mediated transfer:

```sh
# run a private cluster on a separate terminal
python tools/startcluster.py
# deploy the registries:
python tools/deploy.py
# The default accounts have the following privatekeys:
#     51c662cae295bdef5b0b895065aaa105089375e6541381dc17ba6d3ea0451052
#     20d8b10d23ec1f00b54d798c9120fae94cff91e8db936affe6ef9d80a74c3535
#     aa3e84aa62daa5186d75663ff09c62500b998fe143bdfbb1b7e29b8e5583970b
# With the addresses from the deploy script, run three nodes:
python raiden/app.py \
  --eth_rpc_endpoint 127.0.0.1:8101                  \
   --listen_address 0.0.0.0:40001                    \
   --privatekey=<privkey>                            \
    --registry_contract_address=<managers registry>  \
    --discovery_contract_address=<endpoint registry> \
    --logging ':DEBUG' --logfile /tmp/node1
```

```python
# on any of the three nodes deploy a token
In [1]: tools.create_token()
Out[1]: '9e35c9fa95fb0de3b28b178d441ade31919086ea'
# distribute asset/token to the other two nodes
In [3]: asset = raiden.chain.asset('9e35c9fa95fb0de3b28b178d441ade31919086ea'.decode('hex'))
In [4]: asset.transfer('01551883681ba1eedf9403f743808776cc9e509a'.decode('hex'), 50000)
In [5]: asset.transfer('397a25e3c9c66c870e2a044379da9429156aa05f'.decode('hex'), 50000)
# at this point asset.balance_of() is not zero
# create a channel from A to B and from B to C in the proper client
In [6]: tools.open_channel_with_funding('9e35c9fa95fb0de3b28b178d441ade31919086ea', '01551883681ba1eedf9403f743808776cc9e509a', 5000)
In [1]: tools.open_channel_with_funding('9e35c9fa95fb0de3b28b178d441ade31919086ea', '397a25e3c9c66c870e2a044379da9429156aa05f', 5000)
# at this point we have the channels registered in the nodes and the graph updated, a transfer from A to C can be done because there is balance
In [10]: raiden.api.transfer('9e35c9fa95fb0de3b28b178d441ade31919086ea', 100, '397a25e3c9c66c870e2a044379da9429156aa05f')
# now that C has some balance it can make a transfer back
```

**Comment by konradkonrad** [comment]
Confirmed your working example @hackaugusto 
```
In [5]: A = '67febce7e8f81e6c6b6624a6cef64b4b717c0194'

In [6]: raiden.api.transfer(token, 100, A)
Out[6]: True

In [7]: raiden.api.transfer(token, 100, A)
Out[7]: False
```
