### ISSUE TITLE
Modify estimate_and_transact() function

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#1216]
## Problem Definition

After Byzantium we [stopped](https://github.com/raiden-network/raiden/blob/41b1fa41a606fb27fe2e3272ab3cba17ded4fcc4/raiden/network/rpc/transactions.py#L33) using the `estimate_and_transact()` function to its full potential as we stopped using estimate gas.

## Solution

Now that estimate gas [works reliably](https://github.com/raiden-network/raiden/pull/1215) again and can even specifically detect a transaction that would throw we need to reconsider using `estimateGas` inside the `estimate_and_transact()` function and also modify the pattern of using `estimate_and_transact()` followed by a `check_if_transaction_threw`.

**Comment by hackaugusto** [comment]
The `check_if_transaction_threw` must be kept in place, this is required for race conditions.

Think of a call to `settle` on the current smart contract, were both nodes race to settle, both calls to `eth_estimateGas` will be sucessfull but only one of `eth_sendRawTransaction` will work.

**Comment by LefterisJP** [comment]
ofcourse! I am not saying we should remove it. But that we should also utilize this new tool, that gives us the ability to see beforehand if a transaction would fail, and avoid doing it. This can save gas and time for our users. 

But still gotta think a bit on how to integrate such a check into the current methodology of transaction execution and checking.

**Comment by LefterisJP** [comment]
This issue is no longer relevant, especially with all the switches to web3.py functionality.
