### ISSUE TITLE
Testing Channel on same Ropsten Node

### ISSUE THREAD

**Issue by EasonWang01** [raiden-network/raiden#1241]
## Problem Definition

>  open a channel with another Raiden node

I try to run two raiden node running on the same Ropsten Node.
When I create other address and pasting it to test1 folder then running
```
raiden --listen-address 127.0.0.1:40012  --keystore-path $HOME/Library/Application\ Support/io.parity.ethereum/keys/test1
```
but it will says something like 
```
 return _socket.socket.sendto(self._sock, *args)
OSError: [Errno 49] Can't assign requested address
```
Or is there an option to using Docker for testing the channel?

Thanks for reply.

**Comment by LefterisJP** [comment]
@EasonWang01 terribly sorry for the late reply.

Listening address should have `0.0.0.0:40012`. Generally for listening host use the `0.0.0.0` address. 

Does this solve your issue?

**Comment by LefterisJP** [comment]
I assume the issue is solved due to lack of reply to my proposed solution.
