### ISSUE TITLE
Release raiden to the Ubuntu store

### ISSUE THREAD

**Issue by elopio** [raiden-network/raiden#1249]
## Problem Definition

A while ago, the metadata required to package raiden as a snap was landed in #1104. However, it hasn't been released to the store yet.
I'm very interested in making this easily available to all ubuntu users, early adopters and our community of testers.
To get started releasing to the edge channel, where more tests can be easily run before making the first stable release, you just have to go to https://build.snapcraft.io

More info in https://snapcraft.io/

**Comment by LefterisJP** [comment]
Hello elopio and thank you. This will make sense once we have a first stable release.

**Comment by elopio** [comment]
Hello @LefterisJP. I think this would make testing your unstable releases a lot easier. But I understand if you have a different preference.

**Comment by ulope** [comment]
@elopio Just as a pointer: We do have standalone binary releases for linux and macOS since the last two or so releases: https://github.com/raiden-network/raiden/releases

**Comment by elopio** [comment]
@ulope yes, but U say that it would be easier because the snap would autoupdate. Your community of testers will always have the most recent code from master ready to use.

**Comment by karlb** [comment]
The standalone binary releases should be sufficient for most cases, so this is low priority.

Feel free to reopen if you volunteer to take over this task.
