### ISSUE TITLE
Raiden on TestRPC

### ISSUE THREAD

**Issue by exSpectrum** [raiden-network/raiden#1260]
Is it possible to run / deploy Raiden on my private Blockchain (like the one generated with Truffle e.g.)?
And if yes, may I trouble you to share some links or info on the topic.
I’d be much obliged.

**Comment by LefterisJP** [comment]
Hello @exSpectrum and really sorry for not seeing this issue earlier.

In principle it should be possible. We don't have any docs on how to achieve this though. 

You will need to deploy all the relevant contracts in that chain and point raiden to them. We have arguments for them:

```
  --discovery-contract-address ADDRESS
                                  hex encoded address of the discovery
                                  contract.  [default:
                                  1e3941d8c05fffa7466216480209240cc26ea577]
  --registry-contract-address ADDRESS
                                  hex encoded address of the registry
                                  contract.  [default:
                                  66eea3159a01d134dd64bfe36fde4be9ed9c1695]
```

**Comment by LefterisJP** [comment]
I assume this issue has been solved since there is no reply yet. If that's not true please feel free to reopen.
