### ISSUE TITLE
Update smart contracts to be solc 0.4.0 compatible

### ISSUE THREAD

**Issue by czepluch** [raiden-network/raiden#130]

**Comment by konradkonrad** [comment]
added the `bug` label, since it breaks our builds on travis-ci

**Comment by konradkonrad** [comment]
could resolve the builds by using an older static `solc` version, see https://github.com/raiden-network/raiden/commit/f5d0819b208f43418d96e62dee0efb58889aa5bd
priority is lower now
@czepluch handing this over to you. although not yet released, I linked the most likely release link for 0.4.0 in `.travis.yml`, see https://github.com/raiden-network/raiden/commit/fedfdced8954b97919eafcc7d876dcfc9db4e2cd

**Comment by czepluch** [comment]
https://github.com/ethereum/solidity/blob/develop/Changelog.md
