### ISSUE TITLE
Error deploying Raiden on Rinkeby testnet

### ISSUE THREAD

**Issue by dopetard** [raiden-network/raiden#1302]
I tried to deploy the raiden contract on Rinkeby 
`python deploy.py --pretty ###privatekey###`

Traceback

`unrecognised option '--add-std'
Traceback (most recent call last):
  File "deploy.py", line 146, in <module>
    main()  # pylint: disable=no-value-for-parameter
  File "/home/exchangeunion6/raidennode1/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/exchangeunion6/raidennode1/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/exchangeunion6/raidennode1/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/exchangeunion6/raidennode1/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "deploy.py", line 141, in main
    deployed = deploy_all(client)
  File "deploy.py", line 112, in deploy_all
    compiled_contracts = allcontracts(RAIDEN_CONTRACT_FILES)
  File "deploy.py", line 90, in allcontracts
    for c in contract_files
  File "deploy.py", line 90, in <dictcomp>
    for c in contract_files
  File "/home/exchangeunion6/raidennode1/lib/python3.6/site-packages/ethereum/tools/_solidity.py", line 322, in compile_contract
    extra_args=extra_args
  File "/home/exchangeunion6/raidennode1/lib/python3.6/site-packages/ethereum/tools/_solidity.py", line 282, in compile_file
    output = subprocess.check_output(args, cwd=workdir)
  File "/usr/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/local/bin/solc', '--combined-json', 'bin,abi', '--add-std', 'NettingChannelLibrary.sol']' returned non-zero exit status 1`

I tried building solc from source and also added it to PATH. 

### System Description

```
Python 3.6.3

Linux instance-2 4.13.0-36-generic #40-Ubuntu SMP Fri Feb 16 20:07:48 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

/usr/local/bin/solc
solc, the solidity compiler commandline interface
Version: 0.4.22-develop.2018.3.10+commit.30443f3a.Linux.g++

/usr/bin/geth
Geth
Version: 1.8.2-stable
Git Commit: b8b9f7f4476a30a0aaf6077daade6ae77f969960
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.9.4
Operating System: linux
GOPATH=
GOROOT=/usr/lib/go-1.9

{
  "raiden": "0.3.0",
  "python_implementation": "CPython",
  "python_version": "3.6.3",
  "system": "Linux 64bit_ELF 4.13.0-36-generic x86_64"
}
[ -d .git ] && git rev-parse HEAD
539e6fde927a5de0316a1136ee702736273713b6

```

**Comment by dopetard** [comment]
Maybe @dcale could look into this since he seem to a have successfully deployed the contracts on rinkeby. Also @andrevmatos This is different error than the pythereum not finding solc one I was getting

**Comment by LefterisJP** [comment]
@dopetard I will look into it, I think I have an idea what's wrong

**Comment by LefterisJP** [comment]
@dopetard 

Okay so the problem is because you have 0.4.21 solidity. Inside solidity's integration in pyethereum the argument `--add-std` is appended in every compilation. At least in 0.4.21 that argument no longer exists. In 0.4.18 it does.

They removed it without putting out any note in the changelog ... so we did not notice it at all.

Your safest bet is to use 0.4.18. I will test all versions in between to see which one removed it and think of a way forward.

Tell me if using 0.4.18 solves your issue.

**Comment by LefterisJP** [comment]
Yep it affected everyone, go-ethereum too. Check the issue here: https://github.com/ethereum/solidity/issues/3695

**Comment by LefterisJP** [comment]
So @dopetard using 0.4.20 should also be fine. Not tested yet, but at least the argument seems to have been removed at 0.4.21.

So for your issue use any solc less than 0.4.21. 

For Raiden we will be able to use solc 0.4.21 once:

1. This PR is merged in pyethereum: https://github.com/ethereum/pyethereum/pull/858
2. A new pyethereum release is made (unless we fork it in a very dirty way again)

**Comment by dopetard** [comment]
Thanks much @LefterisJP Using solc 0.4.18 solves this issue. Gonna test it with other versions as well. Closing this for now.
