### ISSUE TITLE
Make raiden console ipython 5 compatible

### ISSUE THREAD

**Issue by konradkonrad** [raiden-network/raiden#132]
Our current way of event loop integration breaks with ipython version 5:

`UnknownBackend: No event loop integration for 'gevent'.`

Whilst this is no pressing issue, ipython 5's use of `prompt_toolkit` would enhance the raiden console in a nice way.

**Comment by LefterisJP** [comment]
@konradkonrad Is this still an issue? Ipython is now at [release 6.3.1](http://ipython.readthedocs.io/en/stable/) and I guess more stuff would be broken if we try to integrate with that too.

I don't know of anyone else using the `--console` feature and we got practically 0 tests for it. Is it worth the developer time to maintain it?

**Comment by LefterisJP** [comment]
I am closing this. If someone else needs it we can reopen it.
