### ISSUE TITLE
Reintroduce Token Swap with the Recoverable Approach

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#1324]
Essentially revert what what done in https://github.com/raiden-network/raiden/pull/1323. But when reintroducing it, make sure that it uses the recoverable state machine.

**Comment by hackaugusto** [comment]
duplicated https://github.com/raiden-network/raiden/issues/303 ?

**Comment by LefterisJP** [comment]
Sort of. There is no "current implemenation" anymore but yes we can keep one issue only. Just wanna make sure we don't forget about it. There have been 1000 issues made since that issue was first opened.
