### ISSUE TITLE
Raiden does not start, gives syntax error

### ISSUE THREAD

**Issue by atuljoshi1990** [raiden-network/raiden#1326]
I am using Ubuntu 16.04.3 LTS App on Windows. 
I have run the Ethereum client and kept it to sync with Ropsten testnet. Parallely, I am trying to launch Raiden with the default testnet keystore path: 

raiden --keystore-path  ~/.ethereum/testnet/keystore

Since I am using a source install, I have set virtualenv to version 3 of the python interpreter.

python --version
Python 3.6.4

Still, I am getting the same error:
 
Traceback (most recent call last):
  File "/usr/local/bin/raiden", line 11, in <module>
    load_entry_point('raiden', 'console_scripts', 'raiden')()
  File "/home/atulsigma/raiden/raiden/__main__.py", line 7, in main
    from raiden.ui.cli import run
  File "/usr/local/lib/python2.7/dist-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "/home/atulsigma/raiden/raiden/ui/cli.py", line 194
    print(syncing_str.format(local_block, etherscan_block), end='')
![image](https://user-images.githubusercontent.com/35613178/37934945-8a6f2e8e-3115-11e8-8ae8-a134a884db80.png)
Any ideas what am I missing?

**Comment by andrevmatos** [comment]
@atuljoshi1990 May you, please, test with `python /usr/local/bin/raiden --keystore-path ...`, instead of calling `raiden` directly?

**Comment by hackaugusto** [comment]
Your virtualenv is *not* using python3, please recreate it.

You can see the version of the interpreter in the stacktrace `/usr/local/lib/python2.7/dist-packages...`

**Comment by LefterisJP** [comment]
your venv used `python2.7`

**Comment by atuljoshi1990** [comment]
I have tried everything, I have created a new environment, when I run check the python version it given correct version but when I launch the Raiden it for some reason pick up 2.7 version and gives error, I am not able to understand what I am missing. I tried making changes in .bashrc file as well, but that doesn't seem to work either.

**Comment by atuljoshi1990** [comment]
I was successfully able to resolve the environment issue. But now I am getting the following error:
![image](https://user-images.githubusercontent.com/35613178/37961339-9ab4f70c-317d-11e8-8147-43ece925d4aa.png)
raiden --keystore-path  ~/.ethereum/testnet/keystore
Traceback (most recent call last):
  File "/usr/local/bin/raiden", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 3088, in <module>
    @_call_aside
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 3072, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 3101, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 574, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 892, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 778, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'raiden' distribution was not found and is required by the application

**Comment by palango** [comment]
Did you run `python setup.py develop` in the new environment?

Follow this guide: https://raiden-network.readthedocs.io/en/v0.3.0/overview_and_guide.html#installation-from-source

**Comment by atuljoshi1990** [comment]
Thanks for such quick response. While trying to install the dependencies, I am getting following error:

![image](https://user-images.githubusercontent.com/35613178/37964567-91b3f914-3187-11e8-84e9-42603b52032d.png)

pip install --upgrade -r requirements-dev.txt

Installed /usr/local/lib/python3.6/dist-packages/tinyrpc-0.8-py3.6.egg
Searching for psutil==5.4.3
Reading https://pypi.python.org/simple/psutil/
Downloading https://pypi.python.org/packages/e2/e1/600326635f97fee89bf8426fef14c5c29f4849c79f68fd79f433d8c1bd96/psutil-5
.4.3.tar.gz#md5=3b291833dbea631db9d271aa602a169a
Best match: psutil 5.4.3
Processing psutil-5.4.3.tar.gz
Writing /tmp/easy_install-7spb2kzg/psutil-5.4.3/setup.cfg
Running psutil-5.4.3/setup.py -q bdist_egg --dist-dir /tmp/easy_install-7spb2kzg/psutil-5.4.3/egg-dist-tmp-5tq0wpfx
psutil/_psutil_common.c:9:20: fatal error: Python.h: No such file or directory
compilation terminated.
error: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

I have installed python3-dev package, python-all dev package and python2.7-dev package. Still I am getting the error.

**Comment by hackaugusto** [comment]
Both errors messages are for missing header files, for ubuntu `python3-dev` is the correct package. How are you creating the virtual environments?

**Comment by KimdongHak** [comment]
Wow. That's cool. I also read this issue, and I solved it. Thank you so much.
