### ISSUE TITLE
Use different database paths for different blockchains

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/raiden#1328]
Raiden must not assume that the running blockchain client is always connected to the same network. Raiden can handle different networks by:

1. notifying the user about the mismatch and quitting 
2. using different database paths for different networks

The first option is a bit problematic because it makes unecessarily annoying to use different networks, so I propose the use of option 2 with a message on the command line about the current used network.

**Comment by hackaugusto** [comment]
Note: This implies that if a user wants to run raiden on multiple blockchains, than multiple processes need to be run, which IMO it's fine as long as it doesn't want to do token swaps across chains.

**Comment by LefterisJP** [comment]
Yeah option 2 is fine. But how would that work?

You connect to the ethereum client at the specified `eth-rpc-endpoint` and then you get the network id with the `net_version` RPC call and thus you know the network id and the directory for the DB to read/write to.

No extra arguments needed from the user, just keeping separate DB directories.
