### ISSUE TITLE
Add an event to signal that a message was properly processed

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/raiden#1351]
## Problem Definition

Add an event to signal that a message was successfully Processed.

**Comment by LefterisJP** [comment]
As we discussed in Rocketchat perhaps the way to handle this now is to send a `Processed` message once a state change hits the WAL.

**Comment by hackaugusto** [comment]
This was done by a few commits, but most importantly this one: 1e05ebd163934ddecf33303a5ebf3ec3a8ac9a18

we are using two messages, Delivered and Processed, each one with a different goal, the first is to guarantee the recipient has stored the message to disk and the second that the message was processed and was valid.
