### ISSUE TITLE
Network ID may have changed after Eth node reconnect

### ISSUE THREAD

**Issue by ulope** [raiden-network/raiden#1356]
## Problem Definition

In the past we added automatic reconnect to the Eth node in case of a disconnect.
And with #1340 we now also segregate the datadir by `network_id`.

What we currently don't check is if the `network_id` remains the same after a reconnect. It's possible that someone (either by accident or intentionally, maybe forgetting that Raiden is still running) will stop their Eth node and restart it with a different `network_id`. 
If this happens all sorts of things will break.

We need to detect a changing `network_id` and decide how we want to handle this case.
The least complicated solution is probably to just inform the user and shut down cleanly.

**Comment by LefterisJP** [comment]
That's correct. Good point. I've done this recently with both Raiden and Rotkehlchen and things break in beautiful ways.

**Comment by ulope** [comment]
In theory there is an alternative to shitting down. We could throw an exception that gets caught very high up in the stack (e.g. `cli.py:run()`) and then simply re-start raiden.

I don’t think that’s a very good idea but it would be possible ;)

**Comment by andrevmatos** [comment]
I'd vote for just bail out. Network change isn't something we'd expect user to do (I don't think there's a valid use case yet for this), so it's an exceptional situation, which we may expect/require user intervention (restarting raiden) to handle it.

**Comment by ulope** [comment]
I added a simple [`on_reconnect` listener / callback system in the matrix branch](https://github.com/andrevmatos/raiden/commit/9c0cfc2c8182103733ca4f1ca059d35dfc2cf40a) because I initially thought we could "survive" a network id change. 
@hackaugusto Something like this (with some modifications) should be usable for a clean shutdown, shouldn't it?

**Comment by hackaugusto** [comment]
Removing the decorator in favor of a callback system? I doubt it would fix the problem without a large change.

**Comment by LefterisJP** [comment]
@hackaugusto @palango @ulope Is this issue still valid?

At the moment if the ethereum client crashes and an `EthNodeCommunicationError` is raised and this is not caught anywhere for retry any longer, but we seem to just shut down. So there would be no case where a different chain id can pop up.

**Comment by hackaugusto** [comment]
> At the moment if the ethereum client crashes and an EthNodeCommunicationError is raised and this is not caught anywhere for retry any longer, but we seem to just shut down. So there would be no case where a different chain id can pop up.

I'd say it's still possible but more unlikely. E.g. with a process watch and changes to config files, the user changes a config file, which changes the network used by the node, the ethereum node is restarted by the process watch.

**Comment by LefterisJP** [comment]
We don't have config files for raiden's arguments yet so this would not be relevant for Red Eyes and still quite a corner case. I am removing this from the milestone.

**Comment by hackaugusto** [comment]
This is fixed now.

e0a6290609d926c3cf5137fdf15aaf56a86a5e02 introduced one directory per network, so the restart corner case is gone.
