### ISSUE TITLE
Check if solc satisfies version requirements.

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#1365]
Taking [this](https://github.com/raiden-network/raiden/pull/1364) PR a step further we can have a check that invokes `solc --version` and compares the used version of solc with the `MIN_REQUIRED_SOLC` version and fail much earlier and with a more specific message.

**Comment by Arbitrage0** [comment]
Hey, just wanted to say that I tried working on the issue and hope you wouldn't mind having a look at it! First contributor here ^^

**Comment by onyb** [comment]
@LefterisJP What's the best place in the code to perform this check? Alternatively, do you think we should rather install the Solidity compiler as part of a post-install hook in `setup.py`, if the `solc` binary is not found? `py-solc` does provide a helper to install the Solidity compiler, though I'm not sure if this feature is cross-platform.

```py
from solc import install_solc
install_solc(MIN_REQUIRED_SOLC)
```

**Comment by loredanacirstea** [comment]
We do not require `solc` as a `raiden` dependency as of https://github.com/raiden-network/raiden-contracts/pull/295.
The Raiden client should use the precompiled data provided by the `raiden-contracts` package. Compiling on the fly from the source code is not advised.
`raiden-contracts` throws an error when `solc` is missing while doing `make compile_contracts`. `solc` will throw an error if the version is smaller than the `pragma` from the source code - this does not need additional handling.

**Comment by hackaugusto** [comment]
@onyb thanks for the interest, but I'm closing this because it's outdated. Sorry for the confusion.

But we do have other small issues that could have a hand marked as [hacktoberfest](https://github.com/raiden-network/raiden/labels/hacktoberfest)  :)
