### ISSUE TITLE
Proper python file encoding definition

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#137]
All raiden python files seem to be using the [PEP 263](https://www.python.org/dev/peps/pep-0263/) encoding definition for UTF-8.

It's a minor request but the encoding is misspelt in all of the files. `utf8` is not the correct name. The encoding must always contain a dash, unless it's used in systems where dash is not acceptable. The correct name is `utf-8`. (source: [IANA](http://www.iana.org/assignments/character-sets/character-sets.xhtml))

So all 

```python
# -*- coding: utf8 -*-
```

should be replaced with

```python
# -*- coding: utf-8 -*-
```

And since we are at it I would also suggest adding the python shebang on top there.
```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-
```

This is not just to be pedantic. Some editors (e.g.: emacs), don't recognize the requested encoding and need specific tweaks to work with the raiden sourcecode at the moment.

**Comment by hackaugusto** [comment]
Do we need to add the shebang for non-executable files?

**Comment by LefterisJP** [comment]
no it is not really needed. Could be done easily though as a search and replace when the encoding is changed on top of the files if we wanted to.

**Comment by schmir** [comment]
Please don't add the shebang for non executable files. I've configured emacs to chmod +x those files when saving them.

see https://www.masteringemacs.org/article/script-files-executable-automatically

**Comment by LefterisJP** [comment]
All right, that's not a problem at all then. Quite an interesting way to configure your emacs there @schmir :)
