### ISSUE TITLE
Remove the DummyTransport

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/raiden#1372]
The class `DummyTransport` only exists to aid testing, the callbacks are used to save the messages that go through the protocol layer. The current version of the code base has the WAL, which allows for a cleaner way to query all the messages/events that went through the system, so DummyTransport is not necessary anymore.

Doing this will fix https://github.com/raiden-network/raiden/issues/251

**Comment by jomuel** [comment]
I guess so. @hackaugusto what is 'the WAL'?

**Comment by LefterisJP** [comment]
The WAL stands for our write-ahead-log. For more info look in this [directory](https://github.com/raiden-network/raiden/tree/master/raiden/storage).

We use (or [will](https://github.com/raiden-network/raiden/issues/592) use) it to recover from an unexpected crush. Allows us to have all state changes available and ready to re-read when we come back online.

**Comment by jomuel** [comment]
Ok I'll handle this then (Would assign it to me but apparently assigning issues in this repo is disabled for me)

**Comment by LefterisJP** [comment]
@jomuel I think you now can do it.
