### ISSUE TITLE
Support multiple matrix homeservers 

### ISSUE THREAD

**Issue by ulope** [raiden-network/raiden#1379]
## Problem Definition

Once the initial matrix transport implementation (#1378) is merged we need to support multiple homeservers with federation.

Issues to solve:
- [ ] Server discovery - where to get a list of suitable homeservers from (e.g. on-chain registry)
- [ ] Server selection - there should be an automatic selection of the "best" homeserver (e.g. by ping time)
- [ ] User discovery - there needs to be a mechanism by which users can be found across homeservers. Possible solutions: 
  - Global well-known presence channel
  - [Matrix 3pid](https://matrix.org/docs/spec/identity_service/unstable.html)
  - ...

**Comment by ulope** [comment]
@lefteris Correct, it isn’t necessary for a possible intermediate preview release with matrix support though.

**Comment by MorganGR** [comment]
Any testing possible yet? I am looking at a small Matrix server.

**Comment by ulope** [comment]
@MorganGR Code for this specific issue is currently actively being developed.

If you really want to experiment with the bleeding edge you can check out PR #1373, but be warned that this is very much not done yet and most definitely will have bugs.

**Comment by andrevmatos** [comment]
About the 3rd point, currently, a common room is used only to trigger all servers which federate this room to sync/know users within. Then, server-side user directory search is used to search for users. This way, this room isn't suitable for any kind of spam or dos attack (as no user ever listens to it), and server-side search is more performant than always keeping a list of all users in every client.
3pid may make the system more centralized or lock other valid servers out.

**Comment by ulope** [comment]
@andrevmatos Automatic server selection by best ping from the (currently) static list of available homeservers is already implemented in the current PR.
