### ISSUE TITLE
Integrate raiden-libs to avoid duplicating code and effort

### ISSUE THREAD

**Issue by loredanacirstea** [raiden-network/raiden#1381]
## Problem Definition

https://github.com/raiden-network/raiden-libs was created to aggregate common tools used across `raiden-network` repositories.
It should be integrated in `raiden` to avoid duplicating code and effort. E.g. https://github.com/raiden-network/raiden-libs/issues/50

**Comment by ulope** [comment]
Just FYI: This is already starting in #1373 with the gevent matrix client
