### ISSUE TITLE
Add an identifier field for Raiden's transfers

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/raiden#139]
Add an identifier to raiden messages.
- The initiator of a Mediated Transfer cannot reuse a secret when a timeout happend, it needs to discard the current secret/hashlock and make a new transfer, as a consequence the hashlock cannot be used for identifying a transfer.
- Allow multiple channels to be used for a single transfer. When a single channel doesnt have enough funds to complete a transfer but multiple channels aggregate could sum up to desired transfer value, a unique identifier is required as an identifier.

TODO:
- [x] Decide on a identifier size (16/32/64 bits)
- [x] Add the identifier to messages:
  - [x] DirectTransfer
  - [x] MediatedTransfer
  - [x] SecretRequest

  > these changes need to be done in the files `raiden/messages.py`, `raiden/encoding/messages.py`, and the `raiden/smart_contracts/NettingChannelLibrary.sol`

- [x] Add an identifier argument to the end-user-apis that wll be used with the messages
  - [x] raiden/console.py:Tools
  - [x] raiden/raiden_service.py:RaidenAPI

**Comment by LefterisJP** [comment]
This issue should now be complete thanks to #145 and #147
