### ISSUE TITLE
setup.py's read_version_from_git is an ad-hoc, informally-specified, bug-ridden, slow implementation of half of setuptools_scm

### ISSUE THREAD

**Issue by schmir** [raiden-network/raiden#1397]
I'm trying to build a source distribution of raiden with `python setup.py sdist`. The `read_version_from_git` function tries to determine the version by calling into git.

Here's one of the problems the current implemtation has. I'm trying to build a source distribution in order to upload it on a private devpi server.

When building that, it looks like's it's building version 0.3.0+git.r4992c106. This is also the version I see when installing with 'pip -e'.

However, if I install the source distribution, the version is 0.3.0:
```
pip install dist/raiden-0.3.0+git.r4992c106.tar.gz
...
Installing collected packages: raiden
Successfully installed raiden-0.3.0
pip install dist/raiden-0.3.0+git.r4992c106.tar.gz  5.71s user 0.93s system 110% cpu 6.028 total
~/raiden/core (git)-[master] % pip freeze |grep -E '^raiden'                     
raiden==0.3.0
```
That's bound to fail later.

[setuptools_scm](https://github.com/pypa/setuptools_scm) is the pypa blessed way to compute a version based on the git version. 

Please consider moving to setuptools_scm.

**Comment by LefterisJP** [comment]
I would like to take that one. Thanks for reporting this @schmir. I copied this mistake in another project of mine and I should correct the mistake there too.
