### ISSUE TITLE
Profiling Framework

### ISSUE THREAD

**Issue by heikoheiko** [raiden-network/raiden#14]
Add support for easy profiling 
ideally the continuous integration would notify if a commit slows the system down

**Comment by hackaugusto** [comment]
Available dashboards that I know of:

- [catapult dashboard](https://github.com/catapult-project/catapult/blob/master/dashboard/README.md) [[example](https://chromeperf.appspot.com/)]
  - This is an app engine, but we can gather the data from a build and publish to a "local" server
- [perf-o-matic](http://hg.mozilla.org/graphs/) [[example](http://graphs.mozilla.org/graph.html#tests=[[289,132,37],[289,131,37]]&sel=1454981044000,1455153844000), [alerts](http://alertmanager.allizom.org:8080/alerts.html?showAll=1), [ref](http://aosabook.org/en/posa/talos.html)]
  - Confusing project, really
- [codespeed](https://github.com/tobami/codespeed/) [[example](http://speed.pypy.org/)]

I don't know if there is any continuous integration as a service that also has perf dashboards built-in, so we might need to host our own server.

**Comment by hackaugusto** [comment]
c82bc420 adds an experiment to profile greenlets in isolation (preserving the timming per greenlet with the stack trace)

**Comment by heikoheiko** [comment]
@hackaugusto what's the status here? what is missing to close this?

**Comment by hackaugusto** [comment]
@heikoheiko no support in the CI

**Comment by hackaugusto** [comment]
Another dashboard option: http://asv.readthedocs.io/en/latest/

**Comment by hackaugusto** [comment]
closing in favor of https://github.com/raiden-network/raiden/issues/61

**Comment by Dominik1999** [comment]
as discussed yesterday, should we reopen?
