### ISSUE TITLE
Warn about using same private key from other applications and remove nonce management

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#1400]
From [this](https://github.com/raiden-network/raiden/pull/1392#issuecomment-387089813) comment.

>Either we assume that we share the privatekey or not:
>
>- if we don't share it, then the nonce update is useless: The running Raiden node is the only one  sending transactions with that key, therefor the only node changing the nonce, so the local nonce is always valid.
>   - assuming the ethereum node puts transactions in pending *faster* than Raiden restarts.
>- if we do share, then there **will be** races where two nodes send the different transactions with the  same nonce, only updating the nonce without fixing and resending the transactions is not sufficient. At  the best case scenario, the retry logic would also fix the transaction, but then either:
>  - the two nodes deadlock each other and waste ether, because one will try to overwrite the other   transaction and needs to pay more for the gas
>  - the node which sent the rejected transaction accepts that it lost the race and sends a new  transaction with a fresher nonce. This is IMO just too annoying, the effort is not worth and would be better to just /not/ use local signing.

TODOs:

- [ ] Provide a warning message to the user in the start of the raiden node, letting him know that he should not use the private key used for raiden in anything else as long as the raiden node is running.
- [ ] Remove the code updating nonce for a given interval. The nonce must be updated from the chain at the start.

**Comment by hackaugusto** [comment]
> Did I understand correctly that you want to disallow using the same private key in 2 local running raiden nodes?

How would we do that? I can only think about asking the user to not reuse the same account.

> And with that assumption throw away the nonce management?

Yeah, I would just remove it

**Comment by LefterisJP** [comment]
> How would we do that? I can only think about asking the user to not reuse the same accoun

- Each running raiden node should either put a lock file inside `~/.raiden` with the name being the address the private key corresponds to or ... write that to one common file.

- Each running raiden node would first check the above mentioned file/files and if the key requested for unlocking is contained in that lock file then it would exit with a message: `Another raiden node is running in this machine with the account XXX unlocked or a stale lock file exists at PATH.`

**Comment by hackaugusto** [comment]
nonce management was removed by https://github.com/raiden-network/raiden/pull/2064/
account ownership was done by https://github.com/raiden-network/raiden/pull/1838
