### ISSUE TITLE
Get rid of local signing

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#1402]
Related to https://github.com/raiden-network/raiden/issues/1400#issuecomment-387235851

At the moment we always sign transactions locally on Raiden and send it to the ethereum node for transmission. That is introducing some friction on determining the order of transactions and on handling the possibility of other applications using the same private key that Raiden uses.

The alternative would be to simply delegate the transaction signing to the ethereum node and use something like `eth_sendTransaction` in order to send Transactions to the node and let it do the nonce management.

This issue needs discussion.

We need to evaluate the reason we use local signing, compare with letting the ethereum node do the signing and nonce management and then if it makes sense to change the current behaviour to do so.

**Comment by andrevmatos** [comment]
I don't think running unlocked eth node is more insecure than opening the key by ourselves. It may need additional setup step (to block external connections, etc), but I think it may have some advantages:
- we may/should rely on standard interfaces for signing, e.g. `eth_sendTransaction`, `eth_sign` and `eth_signTypedData` (when stable)
- we may rely on the eth node to give wider key support
- related to above, it'd be nice to keep the possibility of using hardware keys. Currently, signing is interactive, but with e.g. Trezor T/Core supporting custom firmwares, it could emerge an option to unlock/authorize once, auto-sign in the future, and would be nice if we support standard signing interfaces, so geth/parity/Metamask could be used to interface with those hardwallets
- if the user wishes, it may allow full interactive signing. It may not be practical for a full node, but the light-clients sharing libs could make good use of it

Obs: `personal_unlockAccount` isn't available in Parity out-of-the-box, but can be activated by enabling `personal` in Parity's interface, or `unlock`ing directly on parity command-line. Anyway, it's a nice interface for recurrent signatures which we should make use of.

**Comment by LefterisJP** [comment]
>  but can be activated by enabling 

Not a problem. For geth it's there I think. We can have specific requirements for using a local ethereum node.

**Comment by pcppcp** [comment]
here are some scenarios where local signatures make sense

- light raiden client that connects to a public geth node
- some sort of DMZ separation - raiden clients on one network, geth node on an isolated network interfacing the chain, allowing only selected clients to access its RPC interface. Because eth node is facing the internet, it shouldn't be trusted.
- company that provides raiden-in-a-cloud. You don't want to run separate geth for each customer, but having single point where the keys for different nodes are unlocked is also out of question.

**Comment by andrevmatos** [comment]
@pcppcp Yes, these are valid use cases. But, if we stick with the eth-node/web3 signature interfaces, couldn't we support them through some kind of middleware, e.g. Metamask or https://github.com/ethereum/web3.py/pull/649 , while still fully supporting node-side signatures?

**Comment by pcppcp** [comment]
@andrevmatos yeah, I like the idea of `web3` middleware, I hope they merge it soon. MS currently uses a rather ugly contract wrapper to sign locally.

**Comment by palango** [comment]
If we think that the middleware is the best way to go forward we should maybe look into finishing the web3 PR ourselves. The majority seems to be done.

**Comment by hackaugusto** [comment]
I think this issue should be closed. Without local signing we cant support infura.io

**Comment by andrevmatos** [comment]
Is there an issue for **adding** remote signing support, instead of gettnig rid of local altogether?

**Comment by hackaugusto** [comment]
@andrevmatos created: https://github.com/raiden-network/raiden/issues/4239
