### ISSUE TITLE
Smoketest fix makes Raiden non-startable w/o geth installed

### ISSUE THREAD

**Issue by ulope** [raiden-network/raiden#1404]
## Problem Definition

The fixes for #1237 (#1353 and #1374) cause Raiden to be non-startable if geth isn't installed on the user's machine.

The reason is that the check for the geth binary is perfomed on module level (i.e. import time) and the `smoketest` module is being imported by the `cli` module. 

IMO the easiest solution would be to only perform the check for geth when actually running the smoketest.

**Comment by LefterisJP** [comment]
Well there is no reason to start if an ethereum client is not present. But I see the problem. Even `raiden --help` or `raiden removedb` don't work.

**Comment by LefterisJP** [comment]
The commit made it only in my fork ... and still somehow closed the issue. Wtf?
