### ISSUE TITLE
Recover sender address in SignedMessage's from_dict methods

### ISSUE THREAD

**Issue by ulope** [raiden-network/raiden#1431]
## Problem Definition

`SignedMessage` and its subclasses have a `decode()` method that is used to decode a packed binary representation of the message (by using the subclasses `unpack` methods). It sets the `sender` field by recovering the address from the message signature.

This doesn't happen when using `from_dict()` as it's used directly and not through a `decode()` like wrapper mechanism.

## Tasks

- [ ] Implement a mechanism for recovering the sender from the message signature when using `from_dict()`
- [ ] Update Matrix transport to use the new mechanism

**Comment by hackaugusto** [comment]
fixed by 7b3b1fc0985ded9d535bbb90f85677066cdcd026
