### ISSUE TITLE
Terminology

### ISSUE THREAD

**Issue by heikoheiko** [raiden-network/raiden#146]
Create a consistent terminology for the components, concepts, methods we are dealing with. Use it consistently throughout the code base and communication.

**Comment by LefterisJP** [comment]
Yes! And as discussed this should be part of a greater document, a "raiden developer's guide" of sorts.

**Comment by hackaugusto** [comment]
asset / token / fungible , which should we prefer?

**Comment by LefterisJP** [comment]
I suppose token.

**Comment by hackaugusto** [comment]
A Balance proof is an expirable structure constructed from the previous messages necessary to proof the current balance to the blockchain.

**Comment by hackaugusto** [comment]
Documentation wise I also think we should define our system model. Suggestion:

> The system model is based on asynchronous network with Byzantine nodes. The network may fail to deliver messages, delay them, duplicate them, modify them, or deliver them out of order.

**Comment by ameensol** [comment]
Conversation about Unlock / UnlockTransfer vs. Secret:

Jabob:```
> How do you guys feel about renaming the “Secret” message to “Unlock”?
I was thinking about it, and it makes sense to rename. My reasoning is:

The secret message is used to perform an action of unlocking the asset locally and withdrawing in the counter party end, in that respect the Secret is just the data used to perform unlock/withdraw.

But I'm not sure if Unlock is the best name.
```

Ameen:```
My reasoning for calling it “Unlock” or “UnlockTransfer” is that in addition to just the secret, for the “Secret” message to be a valid BalanceProof, it needs to update the nonce, locksroot, and transferred_amount

And my implementation plan right now involves creating an “UnlockTransfer” message and registering it on both the sending and receiving sides, much in the same way that a DirectTransfer would be created and mutually registered.

I’m open to keeping it at Secret, but then we have to call the registration method something else so it doesn’t get confused with “register_secret"

My plan so far was to go with “create_unlocktransfer” and “register_unlocktransfer”
```

**Comment by hackaugusto** [comment]
For the restartable tasks I'm using this nomenclature:

```
A -- B -- C -- B -- D

A is the mediated transfer initiator.
D is the mediated transfer target.
B and C are mediators.

Each mediator has someone that will pay the transfer and someone that the mediator is paying to, I'm calling the hop paying `payer` and the receiving `payee`. Each mediator will only forward a mediated transfer if it's given a valid payer transfer, these (payer, payee) are grouped in transfer pairs.

For B:
  The (A, C) transfer pair, A as the payer and C as the payee.
  The (C, D) transfer pair, C as the payer and D as the payee.
For C:
  The (B, B) transfer pair, B is both the payer and the payee.
```

**Comment by konradkonrad** [comment]
@hackaugusto I'm not 100% following this: why is there a `(B, B)` transfer pair? I believe my confusion comes from the `… B -- C -- B …` path you describe, which is a little unexpected to see. Can you enlighten me?
>>> 
```
For C:
  The (B, B) transfer pair, B is both the payer and the payee.
```

**Comment by hackaugusto** [comment]
B sent a mediated transfer to C, in that example C didn't have a route available to forward the transfer to, then it refunded B. C did received a transfer from B and it sent a transfer to B.

**Comment by hackaugusto** [comment]
Atomic Swaps or Asset Exchange?

**Comment by LefterisJP** [comment]
I prefer `atomic swap` myself. But if we use `Exchange` I guess it should be `Token Exchange` to be consistent with the rest of the terminology on tokens.

**Comment by hackaugusto** [comment]
It was agreed to use `TokenSwap`

**Comment by LefterisJP** [comment]
Closing this issue. Reason:

This issue is too generic as of now. Problems with naming of specific terms should be raised in separate issues (one per term) and not in this repo but the spec repo.
