### ISSUE TITLE
Validate all address input for EIP55 compatibility

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#1460]
## Problem Definition

We are now using web3.py which uses [EIP55](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-55.md) checksummed addresses/.

At the moment we sanitize addresses by using `to_checksum_address()` before passing them on to web3.py.

This is missing the point as we basically don't really validate the checksums on the time of input.

## TODO

- Validate all hex address input by the user for EIP55 compliance
    - Validate hex addresses given through the API endpoints [here](https://github.com/raiden-network/raiden/blob/203c77df4e44bac52b5cee8cded2d57c557bbe95/raiden/api/v1/encoding.py#L46)
    - Validate hex addresses given through the cli [here](https://github.com/raiden-network/raiden/blob/203c77df4e44bac52b5cee8cded2d57c557bbe95/raiden/utils/cli.py#L199)
~- Remove all `to_checksum_address` uses. If a hex address somehow gets to web3.py without already being checksummed it means we are not sanitizing some input.~

**Comment by palango** [comment]
> Remove all to_checksum_address uses. If a hex address somehow gets to web3.py without already being checksummed it means we are not sanitizing some input.

`to_checksum_address` cannot be removed for calls of the web3 clients as it expects checksummed addresses and we use a canonical representation (which isn't checksummed) inside raiden everywhere.

**Comment by LefterisJP** [comment]
That's the whole point of EIP55 compliance though. To switch to using checksumed addresses. 

If we don't do that the entire EIP55 thing is pointless. We would just be using `to_checksum_address` to appease web3.py and miss the point completely.

**Comment by palango** [comment]
> If we don't do that the entire EIP55 thing is pointless. We would just be using to_checksum_address to appease web3.py and miss the point completely.

Not as long as you require every input to be checksummed. That's the whole point of the sandwich encoding.

**Comment by LefterisJP** [comment]
Hmm that is true, but I assumed we wanted to completely switch to EIP55 as the canonical representation for addresses. So what you want instead is something like below?

```
              Input1            Input2
                |                 |
 `check_if_checksum()`   `check_if_checksum()`
                |                 |
------------------------------------------------
|                                              |
|  Raiden Core -- only lowercase hex addresses |
|                                              |
------------------------------------------------
           |                      |
  `to_checksum_address()` `to_checksum_address()`
           |                      |
    `web3.eth.getBalance()` `web3.eth.getCode()`
```

as opposed to

```
              Input1            Input2
                |                 |
 `check_if_checksum()`   `check_if_checksum()`
                |                 |
------------------------------------------------
|                                              |
|  Raiden Core -- only checksum hex addresses  |
|                                              |
------------------------------------------------
           |                      |
    `web3.eth.getBalance()` `web3.eth.getCode()`
```


I don't have a strong opinion here. Just doing the first should be super trivial, but I had understood we wanted to switch to checksummed strings also inside the code.

In any case doing the first one now does not bar us from switching to the second one as a second step. Let's also discuss in person.

**Comment by palango** [comment]
I don't have strong opinions either, but from my discussion about that topic before I gt the feeling that option 1 was favored.

Either way, I guess we should start with checking the inputs and change the internal representation later.

**Comment by andrevmatos** [comment]
What's the argument for using binary representation internally? From my point of view, the only reason for that is easing operations with the binary data (e.g. concatenating/composing it with other binary data in a smartcontract call or signing), but it's done so rarely compared to standalone usage (e.g. `pex`/logging, ext-library calls [web3 and friends], rest endpoints), and for these rare first cases, there're plenty of functions to help on this. I think we could at least review this sandwich-architecture decision.

**Comment by LefterisJP** [comment]
> I think we could at least re-discuss this sandwich-architecture decision.

Perhaps, but this is not the time for such a refactoring and this issue is not the place to discuss it :)

**Comment by hackaugusto** [comment]
> What's the argument for using binary representation internally? 

We need to choose /one internal/ representation and *stick to it*. The goal here is to avoid encoding errors, e.g.:

```python
>>> b'\x00' + u'0'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: can't concat str to bytes
```

> From my point of view, the only reason for that is easing operations with the binary data (e.g. concatenating/composing it with other binary data in a smartcontract call or signing), but it's done so rarely compared to standalone usage (e.g. pex/logging, ext-library calls [web3 and friends], rest endpoints), and for these rare first cases, there're plenty of functions to help on this.

There will *always* be a mismatch on the internal and external representations, that is what encoders are for, changing what we use internally will never fix this.

If we change to `str` we still have to agree on a representation, `0x` prefix or not? checksummed or not? And once that is agreed upon the libraries/IO boundaries mismatches will have to be fixed and the data must be re-encoded. This will make web3 compatible and UDP/signing incompatible, effectively it only moved the format mismatch without any benefit.

You may argue on the frequency of such things, but IMO the re-work is not even close to be worth it.

> I think we could at least re-discuss this sandwich-architecture decision.

The point of a decision like this is to make the code less error prone and avoid bike shedding like this, IMO we should not re-discuss this.

**Comment by LefterisJP** [comment]
This should probably be closed. Input both from the CLI and the API are being validated for EIP55. If something is missing open individual issues.
