### ISSUE TITLE
Rework filtering to use the web3 APIs

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden#1466]
## Problem Definition

Currently we use a home grown function to filter events. After switching to the web3.py stack in #1293  we should switch to the filtering stack web3 uses.

- [x] Simplify current code (#1517 )
- [ ] Remove Raidens `Filter` class
- [ ] Remove double decodings of events

**Comment by LefterisJP** [comment]
Looking at their [docs](https://web3py.readthedocs.io/en/stable/filters.html) it should not be that hard.
