### ISSUE TITLE
Use more web3 middlewares

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden#1467]
## Problem Definition

The web3.py project provides useful middlewares for caching, stalechecks as well as gas pricing strategies. We should remove our custom code for these functionalities and switch to the web3 implementations.

Follow up to #1293

**Comment by LefterisJP** [comment]
@palango I think it's better if you open an issue for each one of the middlewares like you already did with https://github.com/raiden-network/raiden/issues/1473. This way we can discuss, evaluate and eventually integrate (or not) each one of them on a case by case basis.

**Comment by palango** [comment]
I agree, let's close this one.
