### ISSUE TITLE
web3: local signing middleware

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden#1475]
## Problem Definition

We currently sign transactions locally in raiden and send them to the ethereum node as a raw transaction. From the discussion in #1402 it seems that we generally want to keep signing transactions ourselves, while allowing people with special needs (e.g. hardware-wallets) to disable this.

https://github.com/raiden-network/raiden/blob/6ae3fc37773d75ddae0d5b22007d0058bcb832fd/raiden/network/rpc/client.py#L435-L475

There's now a web3 middleware (see ethereum/web3.py#493) that signs transactions locally. My proposal is to use that middleware by default. We could later add a switch to disable it for people that want to use hardware wallets.

Another advantage is that we could start using web3 contract proxies which currently isn't possible because they use `sendTransaction` internally for transactions.

A disadvantage I see is that the whole stack gets more intransparent.

Note: this is currently unreleased. However, it should be easy to get the web3 guys to release it if we need it.

**Comment by andrevmatos** [comment]
I'd replace the hardware wallet argument for a more generic "ethereum_client-side signing", which includes the node support for hardwallets. In the case of this usage, we may give limited support for unlocking accounts, and pointing users to node-side specific config, if needed (e.g. parity).

**Comment by hackaugusto** [comment]
https://github.com/raiden-network/raiden/pull/3386 implemented a signer abstraction. We can't use web3's proxies alone because they lack proper error handling
