### ISSUE TITLE
Add chain_id to the BalanceProof

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#1476]
Part of the integration of the new contracts to raiden core. (#1383)

Add the chain_id to the balance proof structure in the raiden code.

**Comment by palango** [comment]
Just to make sure I'm on the right track:

The balance proof structure is both `BalanceProofUnsignedState` and `BalanceProofSignedState`.

So in order to close this we need to:
- Add the chain_id to the classes above
- Fix all invocation to add the chain_id
- Add the chain_id to the messages
