### ISSUE TITLE
Update API documentation for Red Eyes

### ISSUE THREAD

**Issue by czepluch** [raiden-network/raiden#1477]
## Problem Definition
With the new TokenNetwork design there will be changes to the [Raiden API](https://github.com/raiden-network/raiden/blob/master/raiden/api/rest.py). We need to make sure this is kept up to date. This is ideally done, when the code is updated. If it is, then this issue should check that it's correct and if the documentation has not been updated according to the code, this issue must take care of updating the documentation according to the code changes.

This issue is an ongoing issue that is dependent on changes to the API, and should not be considered done until the documentation and code is in sync prior to a release.

The current documentation is available [here](https://github.com/raiden-network/raiden/blob/master/docs/rest_api.rst)

## Tasks
- [x] Check if the documentation is up to date according to code changes

If docs are not up-to-date:
- [x] Update documentation according to code changes

**Comment by jomuel** [comment]
Done (#1685)
