### ISSUE TITLE
Add function to create Network Graph from events

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#1478]
Part of integrating the new smart contracts in the raiden core. (#1383)

Add a free-standing function in the raiden repo that will create the network graph from events of the TokenNetwork.sol contract and replace the old behaviour where it was created from a call to the channel manager contract's `channels_addresses()` function. For the purpose of this issue you can simply add the TokenNetwork.sol contract in the repo and we can have it removed later.

The purpose of this issue is to parallelize work and avoid conflicts (as much as possible)

**Comment by loredanacirstea** [comment]
I understood @hackaugusto 's proposal otherwise: implement this function in the `raiden-contracts` repo, where you can actually test it. Import it or move it in the `raiden` repo when we are ready to integrate.

**Comment by LefterisJP** [comment]
It makes little difference. You can also test here if it's a free standing function. Can even be in raiden-libs for all I care.

**Comment by hackaugusto** [comment]
We don't really need this utility now, since the Raiden node has to watch the token network with filters and handle the events anyway, on the first run it can recover logs starting from block `0`, which will recover the full network.

**Comment by palango** [comment]
Is there any need for a free-standing function then? If the state machine updates the network representation this should be enough.

**Comment by LefterisJP** [comment]
Should not be needed after this is achieved: https://github.com/raiden-network/raiden/issues/1561
