### ISSUE TITLE
Cross asset transfer support

### ISSUE THREAD

**Issue by heikoheiko** [raiden-network/raiden#149]
-  User Alice wants to transfer N of asset X to user Charlie for at most M of asset Y
-   Alice and Charlie both only have an account for on of the assets

Solution New MediatedAXTransfer message which additionally specifies: target_asset, target_amount. Every hop checks the channel graph if there is path with a node which has accounts for both assets. A node with both assets would accept the source_asset and forward the transfer as the target_asset, if it agrees with the source_amount, target_amount ratio. As with the MediatedTransfer, we'll have optimistic routing i.e. as there is no global view on the transfer capacity (deposit/balance) and the exchange rate of the nodes. If a node can not successfully transfer, it reports this back to the calling node which tries the next best path.

**Comment by heikoheiko** [comment]
Next step: Document necessary changes.

**Comment by hackaugusto** [comment]
Why are we going to use the same path for both assets?
