### ISSUE TITLE
Propagate alarm clock task exceptions

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#1490]
All exceptions that happen inside alarm clock tasks are ignored and only their stack trace is printed. This can lead to bugs being missed and should be avoided.

Any exception inside the alarm clock tasks **is a bug**. So we should [propagate](https://github.com/raiden-network/raiden/blob/master/raiden/tasks.py#L101) all exceptions from the alarm tasks to the main task and let the exception be raised and quit the program.

**Comment by pcppcp** [comment]
see how it's done in MS: every greenlet exception is treated as fatal and will terminate the program

https://github.com/raiden-network/raiden-monitoring-service/blob/master/monitoring_service/server.py#L33

**Comment by LefterisJP** [comment]
Yeah I know that this is possible but in this case it's even simpler. We just need to remove the catch-all exception in tasks.py.

The only other place we use greenlets would be the matrix stuff and I don't wanna enforce exception being an error there, at least not yet -- since I did not write it.

**Comment by ulope** [comment]
We should also do this in the `MatrixTransport`, but it will need another pass of checking which exceptions can happen where before we can do that.

**Comment by LefterisJP** [comment]
@ulope yeah thought of doing it there too, but I guess one location at a time.
