### ISSUE TITLE
`test_regression::test_regression_unfiltered_routes`

### ISSUE THREAD

**Issue by pcppcp** [raiden-network/raiden#1502]
When executed on Travis, this test timeouts due to an event (`NewChannel` or `ChannelNewBalance`) not being registered by one of the nodes.

The timeout occurs in `wait_for_channels()` check where one of the node waits for channel deposit being registered indefinitely.

**Comment by hackaugusto** [comment]
Do you have a copy of the stack trace on a gist or a link to the log from a travis build?

**Comment by pcppcp** [comment]
no stack trace unfortunately, only log.

https://travis-ci.org/pcppcp/raiden/jobs/387882435
