### ISSUE TITLE
Meta: Path to a MVP

### ISSUE THREAD

**Issue by heikoheiko** [raiden-network/raiden#153]
Revise the milestones so that they plan for the quickest route to a minimal viable product. I.e. usability, key handling, channel opening, UI might be more important than updating the transport layer or routing algorithm.

**Comment by konradkonrad** [comment]
What is the intended audience for the MVP?

**Comment by konradkonrad** [comment]
What is the account scenario? Local account, unlocked account via rpc, other model?

**Comment by konradkonrad** [comment]
What is the expected maximum setup effort for a user/user application?

**Comment by konradkonrad** [comment]
Will there be a end-user interface?

**Comment by konradkonrad** [comment]
How will routing be solved in the MVP? Global view, or different strategy?

**Comment by konradkonrad** [comment]
How do we handle going offline? Support for 3rd party challenging?

**Comment by konradkonrad** [comment]
Will fees be supported in the MVP?

**Comment by heikoheiko** [comment]
Initial Users: Golem, Gnosis, Omise, IPFS?

**Comment by philtable** [comment]
In the last dev update, you mentioned Raiden MVP's expected release date is around March 2017. I am wondering what's the latest on the progress?

**Comment by scuzzleb** [comment]
can you please set a date when you are going to release mvp. It is nessesery for your community. Appretiate us

**Comment by LefterisJP** [comment]
There is nothing actionable in this issue. Closing.
