### ISSUE TITLE
AttributeError: 'TargetTask' object has no attribute 'token_address'

### ISSUE THREAD

**Issue by pcppcp** [raiden-network/raiden#1532]
greenlet is terminated because of this error in some tests

https://travis-ci.org/pcppcp/raiden/jobs/389686763#979

the exception is raised from here:
https://github.com/raiden-network/raiden/blob/2df06259496fd10cadd29c8e3f4f5f86289f3940/raiden/transfer/node.py#L298

but removing the offending line won't fix the tests: - mediated transfer fails
https://travis-ci.org/pcppcp/raiden/jobs/389706012#L915

**Comment by pcppcp** [comment]
log file for a failed test (`token_address` already removed)
https://gist.github.com/pcppcp/4c1dc34f45bad9572e6482722f0545e5

**Comment by hackaugusto** [comment]
@pcppcp is this still a problem? https://github.com/raiden-network/raiden/blob/90f0d39dd9eb2e686b4a3df0fd253e50abb17ea7/raiden/transfer/node.py#L294-L298 the mentioned line is not there anymore

**Comment by pcppcp** [comment]
@hackaugusto no it's been fixed in `eth-tester` PR. I'll close this issue.
