### ISSUE TITLE
Use balance_hash in balance proof

### ISSUE THREAD

**Issue by loredanacirstea** [raiden-network/raiden#1538]
Use `balance_hash` in the balance proof - http://raiden-network-specification.readthedocs.io/en/latest/messaging.html#balance-proof. 

- Add `locked_amount`, `balance_hash` to all balance proof-related messages & states. These can be set to `0` / `b''` initially or included in duplicated functions.

Some related files:
- `raiden/encoding/messages.py`
- `transfer/balance_proof.py`
- `transfer/state.py` - `BalanceProofSignedState`, `balanceproof_from_envelope`
- `raiden/messages.py` - `EnvelopeMessage`
- `raiden/raiden_event_handler` - `handle_contract_channelclose`, `handle_contract_channelupdate`
- `handle_contract_channelsettle` needs to provide all balance proof data to the smart contract now.

### ToDo
- [x] Add locked_amount to signature #1558
- [ ] Add balance_hash to the balance proof

**Comment by hackaugusto** [comment]
https://github.com/raiden-network/raiden/blob/bb38202c778344ec3795e3301a2f479797469ddb/raiden/messages.py#L294-L312

**Comment by hackaugusto** [comment]
Parent issue: #1383
