### ISSUE TITLE
Create unit tests for new proxies

### ISSUE THREAD

**Issue by pcppcp** [raiden-network/raiden#1541]
Integration of new smart contracts: test basic contracts proxy functionality.

- [x] secret registry
- [x] token network registry
- [x] token
- [ ] token network
  - [x] new_netting_channel
  - [ ] channel_exists
  - [ ] detail_participant
  - [ ] detail_channel
  - [x] deposit
  - [ ] update transfer
  - [x] close
  - [ ] unlock
  - [ ] settle
  - [ ] events filter

**Comment by pcppcp** [comment]
Token and TokenNetwork will be addressed in a separate PR

**Comment by palango** [comment]
Fixed by #1564
