### ISSUE TITLE
Define Transport's public interface via a common base class

### ISSUE THREAD

**Issue by ulope** [raiden-network/raiden#1544]
## Problem Definition

Currently both transports (UDP, Matrix) expose a public interface that is only informally specified.
With every change to either, there is a chance that the interface changes without being updated in the other. Also sometimes tests access private members that may not be available in both implementations.

A common base class will help reduce both problems by making the public interface explicit.

**Comment by hackaugusto** [comment]
Related #3252

**Comment by rakanalh** [comment]
Closing. At the moment, Raiden has one transport as UDP was removed. This could be done as part of integrating a new transport into Raiden.
