### ISSUE TITLE
Create "fake" proxy for channel

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden#1549]
## Problem Definition
With the old contracts a single `NettingChannel` has an identity on the blockchain and we creates a proxy around this. With the new contracts all channels are managed in the `TokenNetwork`.

To make the refactoring to the new contracts easier we create a fake `Channel` proxy that contains the channel identifier as well as a link to the `TokenNetwork` and provides similar API as the `NettingChannel`.

Related to #1383 

- [x] Create inital Proxy
- [ ] Fix `settlement_period` 
- [ ] Fix `get_all_events` filter
- [ ] Write tests

**Comment by hackaugusto** [comment]
why was this closed? https://github.com/raiden-network/raiden/pull/1551/files#diff-d61d2051073a2ebe26853759137f22caR121

The functions signatures are /not/ matching, therefor this is not a replacemento
