### ISSUE TITLE
Update PyInstaller script once switch to raiden-contracts is done

### ISSUE THREAD

**Issue by ulope** [raiden-network/raiden#1550]
## Problem Definition

We're in the process of switching from the previous smart contracts to using those from `raiden-contracts`.
Once this is done the PyInstaller script needs to be updated to include the pre-compiled contract ABI and compiled code from the new locations.

Additionally, now that #1652 is merged, the smoketest needs to be updated to use the compiled code instead of trying to compile anew when running from the bundled version.

**Comment by pcppcp** [comment]
The current location of precompiled contracts is `raiden_contracts/data/contract.json`. They are automatically compiled when building `raiden_contracts` release.
