### ISSUE TITLE
Improve API docs with sphinx addons 

### ISSUE THREAD

**Issue by ulope** [raiden-network/raiden#1554]
## Problem Definition

To further improve our API docs we should start using [sphinxcontrib-httpdomain](https://sphinxcontrib-httpdomain.readthedocs.io/en/stable/) and [sphinxcontrib-httpexample](http://sphinxcontrib-httpexample.readthedocs.io/en/latest/). Both of those will help create docs that make it easier for people new to the project to explore the API while reducing our maintenance effort.

**Comment by jomuel** [comment]
Done (#1685)
