### ISSUE TITLE
Include flake8 check for trailing commas 

### ISSUE THREAD

**Issue by pcppcp** [raiden-network/raiden#1555]
## Problem Definition

No human being should be ever checking if there's a missing trailing comma in the code - we can offload this onto **A L G O R I T H M S**.

- [ ] add `flake8-commas` to `requirements.txt`
- [ ] run `make lint` to see where the commas are missing (*there's a lot of them*)
- [ ] add trailing commas to make `flake8` happy

**Comment by LefterisJP** [comment]
haahah @pcppcp you got pissed didn't you? Didn't know there is a package for this. Great!
