### ISSUE TITLE
fix hardcoded path in `tools/install_synapse.sh`

### ISSUE THREAD

**Issue by pcppcp** [raiden-network/raiden#1570]
In the helper script that installs synapse on Travis, variable `$BASEPATH` is hardcoded to use `raiden-network` (which is a Travis username) as a part of its path. This breaks local Travis builds where the username is different (script fails when copying `synapse-config.yml`)

https://github.com/raiden-network/raiden/blob/master/tools/install_synapse.sh#L21

failed build:
https://travis-ci.org/pcppcp/raiden/jobs/392674122

**Comment by pcppcp** [comment]
`.travis.yml` unfortunately uses this hardcoded username as part of the path passed to the `pytest` as well

**Comment by andrevmatos** [comment]
I already fixed it as part of the #1435 . PR will follow shortly

**Comment by ulope** [comment]
This was fixed in #1572
