### ISSUE TITLE
Fix skipped matrix transfer tests

### ISSUE THREAD

**Issue by jomuel** [raiden-network/raiden#1575]
We are currently skipping the matrix versions of four of the tests in `raiden/tests/intgration/transfer` that are failing. They pass when the `network_wait` parameter is set to very high values (3 seconds and more), so they just seem to be slowed down a lot. This may be related to issue #1573, since the same 401 errors can also be seen in the Synapse log when running these tests.

**Comment by andrevmatos** [comment]
Fixed in 6242a9be6171415353fee8057624467a226457d7

**Comment by andrevmatos** [comment]
Disabled in #1639 and actually fixed in #1636
