### ISSUE TITLE
Take SecretRegistry into account in the state machine

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/raiden#1579]
Register filter for the Secret Registry

- [x] Registry a filter for all secrets registered on-chain
- [x] Create a state change for the learned secrets `ContractReceiveSecretReveal` - added in https://github.com/raiden-network/raiden/pull/1560
- [ ] Handle this state change with the proper transfer tasks
- [ ] add an additional mapping to the `NettingChannelEndState` e.g. `secrethashes_to_onchainunlockedlocks`, that should store the locks with secrets that have been registered on-chain; this mapping will keep the state clear, especially when the "remove expired locks" https://github.com/raiden-network/raiden/issues/193 functionality will be added (easier to differentiate between expired locks with or without on-chain registered secrets)

**Comment by LefterisJP** [comment]
Edited this a bit and added it to Red Eyes as it's required if we are to properly work with a SecretRegistry.

**Comment by loredanacirstea** [comment]
Parent issue: https://github.com/raiden-network/raiden/issues/1496

**Comment by palango** [comment]
> add EventOnchainSecretRevealSuccess, EventOnchainSecretRevealFailed (log an error)

When is an secret reveal considered a success? When it allows us to unlock a lock?

**Comment by loredanacirstea** [comment]
Should be considered a success when the secret was registered on-chain or was found already registered. A failure (secret is not already registered, but transaction fails) should never happen, so we need to log the error. But this is already done in the `secret_registry` proxy.

The question was - do we need to do anything if it fails, do we need to do anything if it succeeds -> if yes, we need these additional events, to trigger the state changes.

The success part should be handled anyway by the blockchain event path. In case of failure, I don't think there is much that we can do, but I am not sure. This would just mean that the node loses those transfer tokens (it should not happen under normal circumstances anyway).

This is why I said `To consider` ..
