### ISSUE TITLE
Test and document websockets API

### ISSUE THREAD

**Issue by konradkonrad** [raiden-network/raiden#158]
https://github.com/raiden-network/raiden/blob/master/raiden/api/wamp_server.py exposes some API-functions via websockets. 

We need tests and documentation and should coordinate the exposed functions with #81 in order to close #10.

**Comment by hackaugusto** [comment]
@konradkonrad @LefterisJP Are going to keep the wamp implementation along side the REST API?

**Comment by LefterisJP** [comment]
Good question. I would say that we shouldn't and would even argue for total removal. Anything that would serve to simplify our code and allows us to support less stuff is good.
