### ISSUE TITLE
Add the SecretRegistry to the App

### ISSUE THREAD

**Issue by loredanacirstea** [raiden-network/raiden#1587]
- [ ] `SecretRegistry` contract should be deployed on Ropsten, address should be added in `constants.py` as a tuple with the `TokenNetworkRegistry`
- [ ] add the contract instance to `App` - `ui/cli.py`

Related: #1579

**Comment by loredanacirstea** [comment]
Parent issue: https://github.com/raiden-network/raiden/issues/1496

**Comment by palango** [comment]
Deployed git `7d18308` to ropsten and verified contract: https://ropsten.etherscan.io/address/0x7862eF1296EeF5Fa55ef056c0cB03FF8D4d49Cf8#code
