### ISSUE TITLE
Add `secret` to the on-chain secret reveal event & handler

### ISSUE THREAD

**Issue by loredanacirstea** [raiden-network/raiden#1588]
Currently the `SecretRegistry` contract emits only the `secrethash` in the `SecretRevealed` event.

@hackaugusto pointed out that there might be reasons to also add `secret` as an event argument in https://github.com/raiden-network/raiden/pull/1560#discussion_r196386434 

Reasons:
- in case we need to register the `secret` again in another `SecretRegistry` contract
- future integration with other layer 2 projects, needing to register the secret again

Related issue in `raiden-contracts`: https://github.com/raiden-network/raiden-contracts/issues/137

**Comment by LefterisJP** [comment]
I would say that is costs us very little to add the Secret to the event and that doing so makes it much easier for other applications to monitor secrets that have been registered with the `SecretRegistry` cotnract.

**Comment by palango** [comment]
Fixed by raiden-network/raiden-contracts#138
