### ISSUE TITLE
Include Synapse as dev requirement once it supports Python3

### ISSUE THREAD

**Issue by ulope** [raiden-network/raiden#1590]
## Problem Definition

At the moment Synapse (the Matrix Homeserver implementation written in Python) doesn't support Python 3 yet. From looking at the GitHub repo it seems they are actively working on getting support ready, however.

Due to that we currently have to [jump](https://github.com/raiden-network/raiden/blob/890f57ea50daf8992c4844e99c5925d61b738de6/raiden/tests/conftest.py#L67-L72) through [some](https://github.com/raiden-network/raiden/blob/e66612b9a15f017ced8f8dc00ea29c8646161d86/tools/install_synapse.sh) annoying [hoops](https://github.com/raiden-network/raiden/blob/890f57ea50daf8992c4844e99c5925d61b738de6/raiden/ui/cli.py#L891-L902)  to get a local synapse server running for the tests as well as the smoketest. 

Once Synapse Python 3 support lands we should add synapse to `requirements-dev.txt` and simplify the test fixtures as well as the smoketest configuration.

**Comment by konradkonrad** [comment]
related #2669
