### ISSUE TITLE
Rethink safe_to_wait in the context of the SecretRegistry

### ISSUE THREAD

**Issue by loredanacirstea** [raiden-network/raiden#1603]
Rethink how much should a node wait before sending the secret reveal on-chain transaction.
With the old approach, we would need to take into account the `closeChannel` transaction + all the `unlock` transactions.
Therefore, the current way should be safe, as it waits more that it needs.

https://github.com/raiden-network/raiden/blob/2aad110c9b71b3de2a3ee87bc8aed8e6081ab29c/raiden/transfer/mediated_transfer/mediator.py#L146

https://github.com/raiden-network/raiden/blob/89786fe60ff2f7bbc11b8e461e3f984604a296ce/raiden/transfer/mediated_transfer/target.py#L33

Parent issue: https://github.com/raiden-network/raiden/issues/1496

**Comment by LefterisJP** [comment]
Since this is an optimization and only client side removed it from the milestone

**Comment by hackaugusto** [comment]
The handling of the lock expiration was changed as part of #2225
