### ISSUE TITLE
Limit the number of pending transfers to max that can be unlocked

### ISSUE THREAD

**Issue by loredanacirstea** [raiden-network/raiden#1604]
After a channel close, pending transfers can be unlocked by sending the batched & packed lock data to the `TokenNetwork` contract.

- [ ] Calculate gas cost for the `unlock` transaction and see what is the maximum number or locks that can be unlocked in the same transaction
- [ ] Add the limit in the Raiden client

Parent issue: https://github.com/raiden-network/raiden/issues/1496

**Comment by hackaugusto** [comment]
this is similar to: https://github.com/raiden-network/raiden/issues/439 . please close one of the issues

**Comment by loredanacirstea** [comment]
https://github.com/raiden-network/raiden/issues/439 is better defined. I am closing the current one and adding the older issue to the Parent issue.
