### ISSUE TITLE
Handle old balance proofs used for settlement by the channel partner

### ISSUE THREAD

**Issue by loredanacirstea** [raiden-network/raiden#1623]
Raiden client keeps the last balance proof data in the channel state.
If the partner uses an older balance proof, there is currently no implemented way to find that data.

As @hackaugusto pointed out, we can either iterate through all the WAL data (bytes encoded) and decode it and check if it is what we are looking for, or change the current storage layout and add an additional table.

The same issue for pending locks from old balance proofs. These are not currently stored in the WAL at all.

The same issue might apply for the participant data, in case the channel is closed with an old balance proof, provided by a 3rd party.

**Comment by hackaugusto** [comment]
duplicated #2214
