### ISSUE TITLE
Move batch unlock data encoding to the proxy

### ISSUE THREAD

**Issue by loredanacirstea** [raiden-network/raiden#1624]
`get_batch_unlock` should return a list of locks. The encoding in the proper format needed for the smart contract transaction should be done inside the proxy.

https://github.com/raiden-network/raiden/blob/cd1bd281dfeaa5b6390e1470e9e7545292f3c338/raiden/transfer/channel.py#L693

**Comment by hackaugusto** [comment]
This was done by 2e3d3f7a43f951cf11c58a76bea158a93f3840cf
