### ISSUE TITLE
Wait for confirmation of the settle channel transaction before sending the batch unlock transaction

### ISSUE THREAD

**Issue by loredanacirstea** [raiden-network/raiden#1625]
Now we send the batch unlock transaction after the `settleChannel` event is emitted.
Consider sending it after we receive the number of confirmations needed by the Raiden client.

https://github.com/raiden-network/raiden/blob/cd1bd281dfeaa5b6390e1470e9e7545292f3c338/raiden/transfer/channel.py#L1555

**Comment by LefterisJP** [comment]
This is trying to protect us in case of a reorg? If yes then this should be a strategy applied to everything and not just settleChannel

**Comment by hackaugusto** [comment]
This was implemented by https://github.com/raiden-network/raiden/pull/2671 . After that PR only confirmed events are dispatched to the state machine, so all the actions are confirmed by definition.
