### ISSUE TITLE
Re-add check_contract_version

### ISSUE THREAD

**Issue by loredanacirstea** [raiden-network/raiden#1656]
`check_contract_version`  must be added to the new `ContractManager` and re-enabled in all proxies. E.g. 

https://github.com/raiden-network/raiden/blob/55973a312be3138a667f649e6e3032bba9e0717f/raiden/network/proxies/secret_registry.py#L53-L57

**Comment by palango** [comment]
@pcppcp Right now we extract the contract version with a regex from the files, but that won't be possible once we use the precompiled contracts. Would it be OK if we just declare a constant inside raiden and compare it with the version of the deployed contract?

**Comment by pcppcp** [comment]
@palango yes that's probably the easiest solution. Maybe we can have a simple script to extract contract version when building `raiden-contracts` and have it available from there.
