### ISSUE TITLE
Deploy new contracts - tetstnet & test fixtures

### ISSUE THREAD

**Issue by loredanacirstea** [raiden-network/raiden#1663]
Add deployment logic for new contracts.

We might need duplicated functions & fixtures. 

Old contracts are deployed using:
https://github.com/raiden-network/raiden/blob/a8a223b20f6e583b06af7314c945a30a4eef36e2/raiden/network/blockchain_service.py#L214

https://github.com/raiden-network/raiden/blob/a8a223b20f6e583b06af7314c945a30a4eef36e2/raiden/network/rpc/client.py#L336

We already have a test fixture for deploying the new contracts:
https://github.com/raiden-network/raiden/blob/a8a223b20f6e583b06af7314c945a30a4eef36e2/raiden/tests/integration/fixtures/blockchain.py#L145

I suggested that the deployment logic from the above fixture might be better placed in the `JSONRPCClient` and `BlockchainService`, so it can be used in the same way as for the old contracts. But this doesn't need to be in the PR that fixes this issue.

**Comment by hackaugusto** [comment]
implemented by: https://github.com/raiden-network/raiden/pull/1684
