### ISSUE TITLE
Internal Server Errors when calling /events/network endpoint

### ISSUE THREAD

**Issue by jomuel** [raiden-network/raiden#1690]
Calling `/api/1/events/network?from_block=30000` results in an Internal Server Error. It happens whenever the `from_block` parameter is specified and the queried block range is nonempty (`to_block` absent or above `from_block`, `from_block` below current block height).

**Comment by LefterisJP** [comment]
@jomuel Let's try this again when we have finalized the new contracts and the event querying mechanism is revised. May be automagically fixed. Depending on which commit you tried at.

**Comment by palango** [comment]
I tested the `http://localhost:5001/api/1/_debug/blockchain_events/network` endpoint now with different `from_block` and  `to_block` values, and I cannot reproduce this issue.

**Comment by LefterisJP** [comment]
Then closing this -- especially since this is now a debug only endpoint
