### ISSUE TITLE
CI: Raspberry PI 2

### ISSUE THREAD

**Issue by heikoheiko** [raiden-network/raiden#17]
Demonstrating IoT + mobile compatibility

Well known and using an ARM CPU
https://en.wikipedia.org/wiki/ARM_architecture#Market_share

**Comment by LefterisJP** [comment]
What's this issue about? Is it to demonstrate a demo of raspberry PIs running raiden in an IoT context?
@heikoheiko @ezdac ?

**Comment by heikoheiko** [comment]
yes, delivered
