### ISSUE TITLE
Make `chain_id` a property of the messages

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#1718]
At [this](https://github.com/raiden-network/raiden/commit/ec18dc60108dcd4fddf0818f475c1740f0b3fec7) commit we (okay okay .. I did it .. sorry) added the `chain_id` in a very very hacky way to make the unit tests pass fast.

All the places where `NETWORKNAME_TO_ID` is added in that commit need to change so that they take the chain_id as a function argument and also the messages themselves must have the chain id as an attribute.

**Comment by andrevmatos** [comment]
For the future: [EIP-155](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-155.md) supports encoding the `chain_id` in the `v` value of the signature, so we could make that a `@property` of the messages and validate upon message handling.

**Comment by hackaugusto** [comment]
@andrevmatos Raiden's messages are not valid Ethereum transactions. Are you proposing to use the same signature scheme in Raiden?

**Comment by andrevmatos** [comment]
Only for the `v` value. EIP712 signatures aren't also valid ethereum transactions, but use the v value as per 155 to replay-protect from the beginning, we could do that on Raiden too, and this change is actually trivial
