### ISSUE TITLE
Support closing the NettingChannel without requiring a transfer

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/raiden#172]
To close the channel a participant is required to make a transfer, there are only two methods available for closing the smart contract, [`closeSingleTransfer`](https://github.com/raiden-network/raiden/blob/a9f79acc1a8e8874badd9e5ebf709c2360844936/raiden/smart_contracts/NettingChannelContract.sol#L58) and [`close`](https://github.com/raiden-network/raiden/blob/a9f79acc1a8e8874badd9e5ebf709c2360844936/raiden/smart_contracts/NettingChannelContract.sol#L63), the first require one transfer from either party and the later a transfer from each.
- [ ] Implement a close function that doesnt required a transfer for either participant.

**Comment by czepluch** [comment]
This seems like a duplicate of https://github.com/raiden-network/raiden/issues/157

**Comment by czepluch** [comment]
Oh, just looked at #24 , guess that one explains the problem indeed.

**Comment by LefterisJP** [comment]
closed by #276
