### ISSUE TITLE
Handle unlocks for old balance proofs

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/raiden#1723]
If a misbehaving node closes the channel with one of its partner's *old* balance proof, the available merkle root wont match, because the channel state only contains the latest merkle tree. In this case Raiden must recompute the corresponding tree from the WAL to call unlock.

Note: No tokens will be lost, the valid merkle tree can always be restored from the WAL.

**Comment by loredanacirstea** [comment]
Same issue is already opened: https://github.com/raiden-network/raiden/issues/1623

**Comment by hackaugusto** [comment]
Thanks @loredanacirstea  , closing this issue as it's a duplicate
