### ISSUE TITLE
Fix timing hack in smoketest

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden#1727]
During the contracts integration I included a hack in the smoketest:

https://github.com/raiden-network/raiden/blob/ef9f18d9657f2c50226cf66ec1947a2a6deb0581/raiden/tests/utils/smoketest.py#L265

This should be done properly by waiting for the contract creation block instead of waiting for a second.

**Comment by CosminNechifor** [comment]
I got this one.

**Comment by palango** [comment]
Fixed by #1748
