### ISSUE TITLE
Fix broken integration tests in master after SC integration branch

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#1733]
After merging the SC integration branch some integration tests have broken in master as we can see [here](https://travis-ci.org/raiden-network/raiden/jobs/400590386).

Tests to fix are:

- [x] `raiden/tests/integration/test_recovery.py::test_recovery_unhappy_case`
- [x] `raiden/tests/integration/test_regression.py::test_regression_unfiltered_routes`
- [x] `raiden/tests/integration/test_settlement.py::test_close_channel_lack_of_balance_proof`
- [x] `raiden/tests/integration/test_settlement.py::test_batch_unlock`

**Comment by hackaugusto** [comment]
fixed by #1800
