### ISSUE TITLE
Exceptions not handled in message handler

### ISSUE THREAD

**Issue by andrevmatos** [raiden-network/raiden#1787]
## Problem Definition

Right now, the transport makes a [very simple and naive](https://github.com/raiden-network/raiden/blob/6444580a4208a32afcebc5415c4c34db671967c2/raiden/network/transport/matrix.py#L432-L448) sanitization of the messages it receives, and, upon decoding, the message is passed to the [message_handler.on_message](https://github.com/raiden-network/raiden/blob/6444580a4208a32afcebc5415c4c34db671967c2/raiden/message_handler.py#L125-L147) function which handles the message and generates the state changes.
This is the entrypoint of all message handling in the node, and literally the whole stack is under it, with lots of assertions and exception cases we couldn't think of in the codepaths of the causes and effects of a message. An exception or assertion hit anywhere will make the node crash.
As this `on_message` function is the network entrypoint, I'd like to propose it's the only place acceptable for a pokemon-exception handler (catch 'em all, `except Exception as e:`), and the right place to protect the node from a possible DoS attack. With high-priority logging, we can get it if something starts going wrong, but not bailing out. Of course, ideally, all exceptions should be handled in the right place, this would be the last safety net.

**Comment by hackaugusto** [comment]
I don't agree with this approach, `assert`s are use to assert on the expected state of the node, if an assertion is being hit either the assumption was too strong, and the assertion should be changed, or a required precondition was broken, and it's a bug. Assuming it's a bug, we must not continue executing the node, otherwise incorrect behavior may happen.

Additionally, catch-all exceptions will catch the exceptions `KeyboardExit` , `GreenletExit`, and `SystemShutindDown`, which will interefere with the exit logic, so at the very least these exceptions must not be handled.

**Comment by pcppcp** [comment]
I'd say let it crash. It's easier to fix a known exception rather than fish for a traceback somewhere in the logs of a flaky test.

**Comment by LefterisJP** [comment]
I agree with @hackaugusto and @pcppcp . In such situations we are going to let the node crash and take the stack trace, analyze the situation and address each problem on a case-by-case basis.

I don't want a pokemon exception handler there.

P.S.: Really awesome name for a catch all handler. First time I see this.

**Comment by andrevmatos** [comment]
> let the node crash and take the stack trace

and explain users why they lost funds because a hand-crafted message crashed his node overnight. Ok ;)

**Comment by LefterisJP** [comment]
> and explain users why they lost funds because a hand-crafted message crashed his node overnight

These users should have had a monitor running. Same thing can happen if their power goes down overnight, run out of memory or whatever.

**Comment by LefterisJP** [comment]
> I agree that a blanket catch all exception handler is not OK, but shipping software with a known remote inducible crash

Yes if there is a way we can crash through a remote message we should definitely handle it. Naturally nobody is arguing against that. A catch-all exception is not the way to do that.
