### ISSUE TITLE
Close the channel if the partner is not updating the current transferred_amount

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/raiden#181]
For a mediated transfer ABC with these messages exchanged:

```
A>B MediatedTransfer
B>C MediatedTransfer
C>A SecretRequest
A>C RevealSecret
C>B RevealSecret
* dont finish the protocol *
```

Charlie learns the secret from Alice but Bob doesnt send a signed message with an updated `transferred_amount` Charlie is forced to close the channel to claim the locked asset as it sees a risk of the lock expiring.

**Comment by konradkonrad** [comment]
@heikoheiko that is the issue you were discussing with @hackaugusto -- could you provide some input?

**Comment by hackaugusto** [comment]
Explanation about the expiration of the lock:

https://github.com/raiden-network/raiden/issues/30#issuecomment-267182073

**Comment by hackaugusto** [comment]
This was implemented as part of the state tasks:

- mediator nodes use the function `is_channel_close_needed` to verify if a close is need (Introduced by: https://github.com/raiden-network/raiden/commit/b4aa21d327f5d037e8dca60e4c059414cd881d40)
- target nodes don't need to take in account the payer/payee pair, so they rely solely on the `is_safe_to_wait` function (Introduced by: d8118cc28e7bcb8e5422dde27aac6eb36644a3c0)
- initiator nodes don't need to close the channel since they are not being paid (losing token)
