### ISSUE TITLE
Notify users about updates

### ISSUE THREAD

**Issue by ulope** [raiden-network/raiden#1810]
## Problem Definition

Raiden should notify users when newer versions are available. This is especially important for security updates where reaching the biggest majority of our users fast is critical.

This can be easily accomplished by querying the GitHub Releases API: `https://api.github.com/repos/raiden-network/raiden/releases/latest`.

This check should be repeated periodically (e.g. every 24h or so) to account for long-running nodes.

**Comment by ulope** [comment]
Fixed with #1837

**Comment by palango** [comment]
On 19 Jul 2018 11:15 PM, Ulrich Petri <notifications@github.com> wrote:Fixed with #1837
