### ISSUE TITLE
Channel state stuck in `waiting_for_settle`

### ISSUE THREAD

**Issue by andrevmatos** [raiden-network/raiden#1818]
## Problem Definition

The channel settle call was performed, and succeeded:

```
raiden_1  | 2018-07-13 13:39:46 [debug    ] STATE CHANGE                   [raiden.raiden_service] node=e0902284 state_change=<Block 3627480>                                                                       
raiden_1  | 2018-07-13 13:39:46 [debug    ] RAIDEN EVENT                   [raiden.raiden_service] node=e0902284 raiden_event=<ContractSendChannelSettle channel:6b44e524 token_network:7692624c>  
raiden_1  | 2018-07-13 13:39:46 [info     ] settle called                  [raiden.network.proxies.token_network] locked_amount=0 locksroot=0x node=e0902284 partner=22222222 partner_locked_amount=0 partner_locksroot=0x partner_transferred_amount=0 token_network=7692624c transferred_amount=0
...
raiden_1  | 2018-07-13 13:46:54 [info     ] settle successful              [raiden.network.proxies.token_network] locked_amount=0 locksroot=0x node=e0902284 partner=22222222 partner_locked_amount=0 partner_locksroot=0x partner_transferred_amount=0 token_network=7692624c transferred_amount=0                                                                                                                                      
web3_1    | 2018-07-13 13:46:54 UTC Transaction mined (hash 0xa4ba16c7adc8f49833cc333c71c66ba25fe6988c6cc79d501940b990165dfcb8)
```
but no state changes to update the channel state showed up in the logs, and even after a restart (which tried to settle the channel again, but failed because it's already settled), the channel is stuck in the `waiting_for_settle` state, and on the channels list.

**Comment by palango** [comment]
Can you try removing the database with `raiden removedb` and check if it works afterwards?

If so this seems to be the same bug as https://github.com/raiden-network/raiden/issues/1822

**Comment by andrevmatos** [comment]
Related to #1807 . Removing the db made the view of the state up-to-date again, although of course it's not a solution.

**Comment by hackaugusto** [comment]
Please don't trim the logs that much, it's really hard to know what happened, did the filter expire? maybe it is not expired but it missed a few events? maybe the node got stuck in a loop and the alarm task is starving?

**Comment by andrevmatos** [comment]
I trimmed it because there was no relevant logs anywhere I could look at. Only new block events in the horizon. I'm not sure, as the request was done in the webUI, but seems like not even the REST API request returned, as the event was not fired and the `async_result` was not set, even if the settle was called and tx mined succesfully.

**Comment by andrevmatos** [comment]
@palango you're right, it seems related to #1822. I've also experienced other block chain events being missed: just saw a deposit tx going through, the block it was mined in was fetched, but the event was **not** fired.
Debugging seems to point that most (probably all) events for a channel that already exists from a previous session to be lost because both `BlockchainEvents`'s [add_token_network_listener](https://github.com/raiden-network/raiden/blob/cbd6d3edc5684b3f637af7ed1d9e34dcf93e4efc/raiden/blockchain/events.py#L391) and [add_payment_channel_listener](https://github.com/raiden-network/raiden/blob/cbd6d3edc5684b3f637af7ed1d9e34dcf93e4efc/raiden/blockchain/events.py#L405) methods to be called **only** during [new token](https://github.com/raiden-network/raiden/blob/cbd6d3edc5684b3f637af7ed1d9e34dcf93e4efc/raiden/blockchain_events_handler.py#L45) and [new channel](https://github.com/raiden-network/raiden/blob/cbd6d3edc5684b3f637af7ed1d9e34dcf93e4efc/raiden/blockchain_events_handler.py#L104) events handling, being completely lost on following sessions, while these listeners should be registered together with [add_token_network_registry_listener](https://github.com/raiden-network/raiden/blob/cbd6d3edc5684b3f637af7ed1d9e34dcf93e4efc/raiden/raiden_service.py#L410), at `install_and_query_payment_network_filters` time. This issue doesn't show up in the tests because in then the token networks and channels are always registered  on every run. CC @hackaugusto

**Comment by hackaugusto** [comment]
@andrevmatos I don't think this is not a problem, all the state changes are replayed ATM, therefor the event handlers that you mentioned, which add the filters, are executed.

**Comment by andrevmatos** [comment]
Well, maybe then something else is preventing the listener to beind added, or the state are not being correctly re-applied, but adding some logs comproved the listeners **were not** registered, at least on my node, on every startup.

**Comment by hackaugusto** [comment]
Do you have the logs? If you run raiden with `--log-config 'raiden.blockchain_events_handler:DEBUG'` and the events `TokenNetworkCreated` and `ChannelOpened` are printed, then the event listeners will be created using the code you linked to.

**Comment by hackaugusto** [comment]
Actually @andrevmatos  you're right, the filters are /not/ being reinstalled.

On a first run the events from the blockchain are processed in the `blockchain_events_handler`, which will do things like convert the event to a state change, install the filters, and start the connection manager. On restart the [state changes are replayed](https://github.com/raiden-network/raiden/blob/master/raiden/storage/wal.py#L24-L25), and the [raiden events are reprocessed](https://github.com/raiden-network/raiden/blob/master/raiden/raiden_service.py#L282-L283), the blockchain events are *not* called again.

We need to revisit the issue #1561 as it was not properly implemented.

**Comment by hackaugusto** [comment]
closing in favor of #1561

**Comment by hackaugusto** [comment]
Looks like the same issue [described here](https://github.com/raiden-network/raiden/issues/2129#issuecomment-412354969)

> The state machine assumes the partner will always successfully call update transfer, and includes both balance proofs in the settlement call, if the update transaction fails then the settle transaction will also fail. To fix this the settle state change should not include the balance proof, but the balance hash, and the balance proof should be recovered from the WAL.

**Comment by andrevmatos** [comment]
@hackaugusto now, my node crash on start with:
```
raiden_1  | 2018-08-17 10:02:40 [debug    ] JSONRPCClient created          [raiden.network.rpc.client] available_nonce=317 sender=e0902284
raiden_1  | Checking if the ethereum node is synchronized
raiden_1  |
raiden_1  | You are connected to the 'ropsten' network and the DB path is: /root/.raiden/netid_3/0xe09022/log.db
raiden_1  | 2018-08-17 10:02:40 [info     ] Lock 139792177286112 acquired on /root/.raiden/netid_3/0xe09022/.lock [filelock]
raiden_1  | 2018-08-17 10:02:40 [debug    ] Restoring from snapshot        [raiden.storage.wal]
raiden_1  | 2018-08-17 10:02:40 [debug    ] Replaying state changes        [raiden.storage.wal] num_state_changes=3646
raiden_1  | 2018-08-17 10:02:55 [debug    ] Restored state from WAL        [raiden.raiden_service] last_restored_block=3849893
raiden_1  | Traceback (most recent call last):
raiden_1  |   File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
raiden_1  |     "__main__", mod_spec)
raiden_1  |   File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
raiden_1  |     exec(code, run_globals)
raiden_1  |   File "/app/raiden/raiden/__main__.py", line 15, in <module>
raiden_1  |     main()
raiden_1  |   File "/app/raiden/raiden/__main__.py", line 11, in main
raiden_1  |     run(auto_envvar_prefix='RAIDEN')  # pylint: disable=no-value-for-parameter
raiden_1  |   File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 722, in __call__
raiden_1  |     return self.main(*args, **kwargs)
raiden_1  |   File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 697, in main
raiden_1  |     rv = self.invoke(ctx)
raiden_1  |   File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1043, in invoke
raiden_1  |     return Command.invoke(self, ctx)
raiden_1  |   File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 895, in invoke
raiden_1  |     return ctx.invoke(self.callback, **ctx.params)
raiden_1  |   File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 535, in invoke
raiden_1  |     return callback(*args, **kwargs)
raiden_1  |   File "/usr/local/lib/python3.6/dist-packages/click/decorators.py", line 17, in new_func
raiden_1  |     return f(get_current_context(), *args, **kwargs)
raiden_1  |   File "/app/raiden/raiden/ui/cli.py", line 1093, in run
raiden_1  |     NodeRunner(kwargs, ctx).run()
raiden_1  |   File "/app/raiden/raiden/ui/cli.py", line 917, in run
raiden_1  |     app = self._run_app()
raiden_1  |   File "/app/raiden/raiden/ui/cli.py", line 935, in _run_app
raiden_1  |     app_ = run_app(**self._options)
raiden_1  |   File "/app/raiden/raiden/ui/cli.py", line 759, in run_app
raiden_1  |     raiden_app.start()
raiden_1  |   File "/app/raiden/raiden/app.py", line 132, in start
raiden_1  |     self.raiden.start()
raiden_1  |   File "/app/raiden/raiden/raiden_service.py", line 310, in start
raiden_1  |     self.start_async().wait()
raiden_1  |   File "/app/raiden/raiden/raiden_service.py", line 262, in start_async
raiden_1  |     last_log_block_number,
raiden_1  |   File "/app/raiden/raiden/raiden_service.py", line 472, in install_all_blockchain_filters
raiden_1  |     channel_state.identifier,
raiden_1  |   File "/app/raiden/raiden/network/blockchain_service.py", line 188, in payment_channel
raiden_1  |     channel_identifier=channel_id,
raiden_1  |   File "/app/raiden/raiden/network/proxies/payment_channel.py", line 40, in __init__
raiden_1  |     raise ValueError('Channel is non-existing.')
raiden_1  | ValueError: Channel is non-existing.
raiden_1  | 2018-08-17 10:02:56 [info     ] Lock 139792177286112 released on /root/.raiden/netid_3/0xe09022/.lock [filelock]
```

**Comment by hackaugusto** [comment]
@andrevmatos That exception is raised if the channel with the given identifier was *never* created.

Can you please report what are the values of the following:

- token network registry address (`app.raiden.default_registry.address` from the ui.cli)
- the token network address (`token_network.address` from the payment channel proxy)
- the channel id (`channel_identifier` from the payment channel proxy)

**Comment by andrevmatos** [comment]
@hackaugusto My last error was caused by an outdated node. Disregard it, please. The one about `settle failed` with channel stuck in `waiting_for_settle` though is still valid to this day

**Comment by LefterisJP** [comment]
Added your log to a gist as opening a file in a text editor is a bit annoying. First wanna read it in the browser: https://gist.github.com/LefterisJP/e416b2642828f8e6f2233034623b5426

**Comment by LefterisJP** [comment]
Also @andrevmatos I think we can close the issue. Looking at Andre's traceback the exception raised is the same I saw when I worked on: https://github.com/raiden-network/raiden/pull/2245 and I fixed it there but also @hackaugusto fixed it at https://github.com/raiden-network/raiden/pull/2244.

It's due to the exception not being logged as a string.

If you agree then please close the issue.
