### ISSUE TITLE
Allow third parties to close the channel

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/raiden#182]
## Problem Definition

A node cannot go offline as long as there are pending locks (vide #181)

## Solution

Allow a third party to call close on behalf of a user, so that the user may request the service from multiple third-parties and go offline knowing that under the risk of a pending lock being claimed that the third-party will act upon.

## Example

Consider a mediated transfer ABC:

```
A>B MediatedTransfer
B>C MediatedTransfer
C>A SecretRequest
A>C RevealSecret
C>B RevealSecret
* B crashes *
```
1. C will call close once the lock is near expiration (as from #181), that will get B's asset.
2. A has no incentive to close the channel, it can just let the lock expire
3. If the third party cannot call close for the AB channel, B loses the asset from the AB transfer

## Tasklist

- [ ] A way to incentivize the third-party to call close. Ideas:
  - Use state channels for the node to pay for the third party for it's services (perhaps with different payment methods, e.g. signatures or pay-per-arbitrage)
  - Escrow some token in the netting channel used as a payment for the third-party (might required changes to the single funded use-case since the partner also needs to put some amount in escrow)
- [ ] Allow third parties to close (through a new function, instead of adding this concern to `close`).
  - [ ] #293 Allow the message to be updated, *only if* it was not closed by the participant (Note: This is not to protect against bad behaving participants, but to protect against bad behaving third-parties)
- [ ] Add unit test

## Related

Allow third parties to update the counterparty transfer #293
[Closed] Close the channel if the partner is not updating the current transferred_amount #181

**Comment by hackaugusto** [comment]
problems:
- what is the incentive for the third party to close the channel?
  - under a dispute the third party is incentivized to dispute by a fee that can be taken from the lier balance, the use of multiple third parties unkown to the other participant is sufficient for preventing cooperation among the third party and the participant.
- what is the incentive for the third party *not* close the channel under normal operation.

**Comment by konradkonrad** [comment]
> a naive implementation would allow the third party to close the channel at any moment, which is not desirable

Well, how about a more involved approach:
- Alice (A) sends regular updates (U) to the third party (T) 
- T is incentivized to close the channel, in case of #181 by a fee enclosed in U
- T is disincentivized to close the channel under normal operation by a mandatory deposit for third party closing (TPC)
- in case of #181 T is supposed to ~ping A before acting
- A can dispute the TPC during a short time period

Open attack vectors:
- A can pretend to be silent in order to grab the TPC deposit
  - now A would lose reputation and not be served again by T

Not sure if this is enough though.

**Comment by hackaugusto** [comment]
We decided to go against the monitoring close.

This issue was create to allow a monitoring service close a channel at any time, this was required to unlock a lock that is nearing expiration. The problem is solved by using the secret registry, where the channel doesn't need to be closed for a lock to be unlocked.

This doesn't mean that a delegate close will not be implemented (a function call may done on behalf of a user if authorization is given)
