### ISSUE TITLE
Missed events by Raiden node

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden#1822]
## Problem Definition

While running the Raiden client we're missing events

I created a couple of channels with other people. The requests timed out as #1820 . 
The channels still got created on chain, but never got shown in the client (neither REST API nor WebUI).

After running `raiden removedb` however the state got resynced and the channels showed up properly.

The same happened for Rakan and Cosmin.

Logs from the resync after removing the db: https://gist.github.com/palango/f3ae12b7adf705ead2cb3dd26ba5d05c

**Comment by hackaugusto** [comment]
closing in favor of #1561
