### ISSUE TITLE
Write debug logs to file for testnet release

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden#1844]
When people find bugs during the testnet release it helps a lot when they provide debugs logs for us. However, a lot of the people probably won't turn on debug logging.

It might be useful to save debug log output to files and update the bug reporting guidelines to include these logs. For this we have to make sure that no private data is included in the logs.

**Comment by hackaugusto** [comment]
This can be done with a [default `--log-file`](https://github.com/raiden-network/raiden/blob/master/raiden/ui/cli.py#L465-L471) [rotated after a few MBs](https://docs.python.org/3/library/logging.handlers.html#rotatingfilehandler)

**Comment by ulope** [comment]
Would be nice though to have that in addition to the stderr logging. Should be easy enough to just attach another handler in `configure_logging()`
