### ISSUE TITLE
Produce nightly releases

### ISSUE THREAD

**Issue by ulope** [raiden-network/raiden#1894]
## Problem Definition

As noticed during the last release our automated release process isn't tested often enough.
After that is fixed in #1893 we want to produce automated nightly releases.

Open questions:
- Where to store the binaries (e.g. S3 or similar)

**Comment by LefterisJP** [comment]
Scoping out of Red Eyes

**Comment by LefterisJP** [comment]
Scoping it back in and making it priority

**Comment by ulope** [comment]
I just saw that digitalocean supports S3 compatible storage with directory listing, thats perfect for our needs.
