### ISSUE TITLE
Remove `--bootnodes` from the "System Requirements and Installation Guide"

### ISSUE THREAD

**Issue by rakanalh** [raiden-network/raiden#1901]
Generally, it is recommended not to use `--bootnodes` as geth will try to discover sync nodes on it's own.

**Comment by LefterisJP** [comment]
You need the bootnodes for the testnet. Geth won't sync otherwise. Mainnet is another story.

**Comment by palango** [comment]
Should we just link to https://gist.githubusercontent.com/rfikki/c895641b6405c082f68bcf139cf2f7ae/raw/4bcaff7eb486babb59f95dd9305c88818508cc02/ropsten-peers-latest.txt for up to date ropsten peers?

**Comment by rakanalh** [comment]
@LefterisJP i am not sure if that's the case because i always run geth without predefined bootnodes for testnet and it goes fine. My concern is that the nodes we have in the documentation might become out-of-date or go offline ... etc which will lead people for long times thinking that geth is syncing when it actually isn't.

**Comment by LefterisJP** [comment]
These bootnodes are only temporary for the testnet release. will be removed from the docs for the mainnet.

They come from here: https://github.com/ethereum/ropsten

@palango Yes we should but I am not sure if we can link to the same gist as sometimes that guy deletes and makes a new one instead of updating it.

**Comment by LefterisJP** [comment]
So I was just talking with @kelsos. He seems to have synced without the `--bootnodes` argument, just by adding the peers by rfiiki and he ended up on a wrong chain and his sync is now stuck. I can't say with certainty if the lack of the bootnoodes is the reason he ended up in the wrong chain but if you don't specify the bootnodes and you get an initial peer that is stuck in the wrong ropsten chain then this will happen. It seems there are many active peers in the wrong chain. This is not the first time this happens.

So I don't want us to remove the bootnodes from the command for as long as we are on the testnet.
