### ISSUE TITLE
Remove the field secret from DirectTransfer encoding

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/raiden#192]
Issue #188 explains why the field is not used anymore.
- [ ] Remove the field from the `raiden/encoding/messages.py`
- [ ] Fix the decoder in `raiden/smart_contracts/NettingContactLibrary.sol`

**Comment by hrishikeshio** [comment]
#486 is merged. Please close.

**Comment by LefterisJP** [comment]
Closing. As a future reference @hrishikeshio check the [verbs](https://help.github.com/articles/closing-issues-via-commit-messages/#keywords-for-closing-issues) that you can use in the PR to put right after the issue name and indicate which issue they are supposed to close.

Once used and the PR is merged they will automatically also close the issue.

**Comment by hrishikeshio** [comment]
@LefterisJP Thanks
