### ISSUE TITLE
Raiden Status Website

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#1927]
We want to have the Raiden Status Website @anmolshl and Caroline built up for the mainnet release. 

### Backend
- [x] Implement https://github.com/raiden-network/raiden-libs/issues/105 so we can only show the networks from the official token network registry.
- [x] Update the channel identifier in the PFS codebase https://github.com/raiden-network/raiden-pathfinding-service/pull/69
- [x] Cleanup and check the code
- [x] Investigate caching and/or writing the results to a static json file for performance reasons.

### Frontend
- Tracked in https://github.com/raiden-network/status-page/issues 

### Deployment
- [x] Create domain and setup server
- [ ] Write docker compose files for the service and deploy. tracked in https://github.com/raiden-network/status-page/issues/34

**Comment by palango** [comment]
This is now tracked in https://github.com/raiden-network/status-page/
