### ISSUE TITLE
Remove expired locks

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/raiden#193]
A raiden payment channel is comprised of two ends, one for each participant, each participant is responsible to control the state changes for its own end, this is done to ensure the messages sent are valid.
- [ ] Add a updating message from the sender to the partner.
- [ ] Add a watcher to remove expired locks based on `tasks.py:AlarmTask`, used by sender.
  - [ ] Clear the node's internal state for the expired lock and send the message to the partner

Note: This is only for expired locks, locks that were claimed are either updated by a ~Secret~ Unlock message #189 or result in the channel being closed #181

**Comment by konradkonrad** [comment]
Clarification:
> Add a updating message from the sender to the partner

Does this mean, you want a `"UpdatedMyEnd"` message, that keeps the other party up to date about the current state on the sender's side, or is it meant the other way around, i.e.: a `PleaseUpdateYourEnd` message? Or something else?

> Add a watcher to remove expired blocks...

You mean ~~b~~locks (without the 'b'), right?

**Comment by hackaugusto** [comment]
> Does this mean, you want a "UpdatedMyEnd" message, that keeps the other party up to date about the current state on the sender's side, or is it meant the other way around, i.e.: a PleaseUpdateYourEnd message? Or something else?

A message `RemoveLock` used by the sender to inform the receiver to clear this lock.

> You mean blocks (without the 'b'), right?

Yes :) (edited the issue)

**Comment by LefterisJP** [comment]
A sum up of our discussion on rocketchat on the problem.

We need to have a way to clean up expired locks from the lock state of channels. Let us assume a unidirectional channel between `A` and `B` where `A` is the payer/sender and `B` is the receiver.

If at some point the lock expires we need to be able to come to a unanimous agreement that the lock has expired between the two nodes. If the block at which the lock has expired is first seen by the sender `A` then he does nothing and waits until the block is also seen by `B`.

When `B` sees the lock expiry block he 

1. Notifies `A` that he saw the expiry block either by a `B` -> `A` `RequestLockRemove` message or a message with an included block height, like an Ack
2. `A` -> `B` will then `Ack(RequestLockRemove)` or if the block height is sent with the ACK `A` will do nothing.
3. Finally in `A`->`B`, `A` sends a `ConfirmLockRemove` message. Alice can change the chanel lock state when both agree on the block expiry. And so can BoB on his view of Alice's channel as soon as he gets the message.

This method has the **advantage** that in between `1` and `3` the channel is not stalled but `A` and `B` can still transact based on the old lock state.

Once `3` is done we need to do two things:
1. Clear the lock state by removing the lock from the merkle root and adjusting it.
2. Clear the locked amount of the lock.

**Comment by hackaugusto** [comment]
Notes:
- `locked amount` is updated *together* with the `merkle tree`, we could update the locked amount without changing the tree, but then the tree would have unbounded size.
- The lock removal is controlled *only by the sender of the unidirectional channel*, the message from B to A is not required nor trusted, it's just a hint to A informing that a lock may be removed, and B won't stall the channel waiting for a block confirmation.

Different designs:
- It's viable to use only the `RemoveLock` message, without the message from B informing that a lock may be removed. Stalls can be avoided by A by delaying the message a block or two.
- The hint from B to A may be the block number instead of the lockhash.

**Comment by LefterisJP** [comment]
Removing this from the Developer Preview as it did not make the milestone.

**Comment by LefterisJP** [comment]
Moving this out of Red Eyes
