### ISSUE TITLE
Hide settled channels 

### ISSUE THREAD

**Issue by rakanalh** [raiden-network/raiden#1938]
## Problem Definition

Opening and closing channels would mean that the UI will show all channels the user created. This issue is to suggest we add some UI utility which would enable me to toggle (show/hide) settled channels.

**Comment by andrevmatos** [comment]
Actually, settled channels should be removed from the node state, and shouldn't show up at all
@hackaugusto ?

**Comment by hackaugusto** [comment]
@andrevmatos Channels are removed once their state is no longer required, and the APIs always report the latest state, so yes, the channels will eventually be removed.

A channel state being no longer required means:
- The channel was settled and there is not unlocks to be done
- The channel had all the unlocks done

**Comment by hackaugusto** [comment]
@kelsos is this still a problem?

**Comment by kelsos** [comment]
On my side settled channels are no longer listed on the webui so I would say no it is not still a problem.
