### ISSUE TITLE
Maintain multiple netting channel states per channel identifier

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#1941]
With [raiden contracts 193](https://github.com/raiden-network/raiden-contracts/issues/193) getting implemented we will now need to maintain multiple [netting channel state](https://github.com/raiden-network/raiden/blob/master/raiden/transfer/state.py#L862) objects per channel identifier.

That is going to enable [calling](https://github.com/raiden-network/raiden/blob/master/raiden/transfer/channel.py#L1725) batch unlock for older channels with a participant with whom we have already closed/settled when we already have a new channel with the same participant and will also make it easier to maintain the separate state needed per channel for its lifecycle.

Changes needed:

- Make sure that the [views that access channel state](https://github.com/raiden-network/raiden/blob/master/raiden/transfer/views.py#L245-L297) use the correct identifier and allow for differentiation depending on different netting channel states, depending on the newly changed channel identifier.
- Make sure that the mapping of `token_network_state.channelidentifiers_to_channels` gets properly [populated](https://github.com/raiden-network/raiden/blob/master/raiden/transfer/token_network.py#L77) whenever a new channel is opened with a participant even if an older participant channel was open before.
- Follow the logic of where [`token_network_state.partneraddresses_to_channels`](token_network_state.partneraddresses_to_channels) is called from and make sure that this only refers to the current channel, and if at any point it's required make sure the channel identifier is taken into account
- If any old netting channel state has had the unlock done for our side of the channel then the channel state can be cleared, ([probably here](https://github.com/raiden-network/raiden/blob/master/raiden/transfer/channel.py#L1725)).
- Maybe some more misc changes (?)

**Comment by hackaugusto** [comment]
BTW, the solution for the issue https://github.com/raiden-network/raiden/issues/1623 , would probably also apply to this one (since we need to cover all old BPs, handling the newest one is similar)
