### ISSUE TITLE
Check if the channel_identifier that requested it is old before making an on-chain transaction

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#1942]
This is not in a direct connection with [raiden contracts 193](https://github.com/raiden-network/raiden-contracts/issues/193) but stemmed out of the conversation from it as the easiest solution for #1907.

Essentially everytime we are about to make an on-chain call, check if the channel we are about to make the call for is the current channel and if not, do not perform the transaction.

For example in the case of #1907 it was due to checking the events since last restart and seeing there is a need to call `updateNonClosingBalanceProof()` since the counterparty closed while we were offline. But in the meantime the counterparty had reopened the channel and as such the `updateNonClosingBalanceProof()` is for a previous channel and will always fail.

To avoid that we need to add a check before [here](https://github.com/raiden-network/raiden/blob/master/raiden/network/proxies/token_network.py#L586) for the `updateNonClosingBalanceProof()` case and make a call to the `TokenNetwork` proxy for the current channel identifier. If it's the same as the one that lead us to go down the path of making the on-chain transaction we will proceed. If not, we will just do nothing. Perhaps add a debug log saying the channel is outdated so we do nothing.

Do the same as above for all the blockchain transactions in [token_network.py](https://github.com/raiden-network/raiden/blob/master/raiden/network/proxies/token_network.py)

**Comment by hackaugusto** [comment]
A more detailed solution for this is to implement the transaction queue (https://github.com/raiden-network/raiden/issues/1950), stop reprocessing the events at restart (https://github.com/raiden-network/raiden/issues/1951), and have separate exceptions for the possible scenarios (https://github.com/raiden-network/raiden/issues/1966), some of which should be handled.
