### ISSUE TITLE
Unclean Matrix shutdown due to long polling sync request

### ISSUE THREAD

**Issue by ulope** [raiden-network/raiden#1947]
## Problem Definition

Matrix uses HTTP long polling (with a default poll timeout of `30s`).
During Raiden shutdown the Matrix transport waits a total of `10s` for all greenlets to terminate.
Depending on the time in the request cycle and the activity the client sees it's possible that the long polling sync request will block longer than `10s` leading to: 
https://github.com/raiden-network/raiden-libs/blob/7ac0d335b76e17c6ca47cd73ba548fe4a9b15d10/raiden_libs/network/matrix/client.py#L200

Solution: keep track of greenlets performing the sync long polling requests and `.kill()` them before calling `.join_all()` on the remaining ones.

**Comment by CosminNechifor** [comment]
@ulope Can you reproduce it? It's not happening anymore on c027f80b28839e5848558411250f078ce2b7970c

**Comment by ulope** [comment]
It's still happening as of 0.4.1
