### ISSUE TITLE
Forbid on-chain actions which can race with a reorg

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/raiden#1965]
This is a pessimistic approach for sending transactions. The downside of this approach is that the latency or some changes will increase (e.g. partner depositing after a channel is opened)

### Problem definition

Given the following execution order, as seen by two Raiden nodes:

On block x, P1 calls settle
On block x+1, P2 calls open channel
On block x+2, P1 calls deposit

With a chain reorg these transactions could be execute in the wrong order, either in the same or different blocks: 

Block x, P2 calls open channel
Block x, P1 calls settle

Or:

Block x, P1 calls deposit
Block x+1, P2 calls open channel

### Tasklist

The only sane strategy to fix this is to send state dependent transaction after the confirmations blocks have elapsed.

- [ ] Register token allowed after the token registry deployment is confirmed
- [ ] Register secret allowed after the token registry deployment is confirmed
- [ ] Open channel allowed after the register token is confirmed
- [ ] Deposit allowed after open is confirmed
- [ ] Withdraw allowed after open is confirmed
- [ ] Close allowed after open is confirmed
- [ ] Settle allowed after the settlement window "is confirmed", IOW after block `close_block + settle_timeout + confirmation_blocks` (Issue: #1625)
- [ ] Unlock allowed after settlement is confirmed

### Related issue

Take chain reorg into account #1121

**Comment by pirapira** [comment]
A potential alternative is not to wait for the confirmation, but to use the new Constantinople BLOCKHASH opcode. Smart contracts can see recent block hashes so they can see which fork they are on.  So, whenever you sign a balance proof or a deposit transaction, you can include the recent blockhash.  Then the smart contract would reject the transaction after a reorg.

**Comment by hackaugusto** [comment]
@pirapira  I don't think that is a good idea because `BLOCKHASH` has only some of the values available, if a node creates a balance proof and goes offline for a long period of time, the opcode will not find the hash and the balance proof will be invalidated. This adds two problems:

- It can be used as an attack vector
- It introduces problems with data validity that will required rewrite of all balance proofs in the message queue

Additionally that would only tackle the problem of `close` and `updateTransfer`. There are other operations that don't have a balance proof that are also susceptible to reorgs.

So, I'm marking closing this issue, the current approach is definitely sufficient; ATM a Raiden node only updates its local state [with confirmed data](https://github.com/raiden-network/raiden/blob/bfc15c97f03a2f580a1ca0c3bcdef61afb60af73/raiden/raiden_service.py#L772-L785), and on top of that all operations are validated against this confirmed state.

The validation is done both by the proxies and the APIs, this was introduced as part of the work on the pruned blocks handling https://github.com/raiden-network/raiden/issues/3566 and it's being double checked on issue https://github.com/raiden-network/raiden/issues/4763
