### ISSUE TITLE
Test `integration/contracts` in standard (PR) CI run

### ISSUE THREAD

**Issue by pcppcp** [raiden-network/raiden#1974]
Let's discuss whether we should add contract proxies test to the default run.

pros: 
- it takes only ~45s with tester backend on my machine
- it tests important past of the core functionality

cons:
- tell me some

**Comment by LefterisJP** [comment]
I tested locally and for me tester is even faster for the contract integration tests.

- geth: 3 mins 10 secs
- tester: 37 secs
> tell me some

But ... I really dislike the tester backend as it has manytimes in the past had errors which made us lose a lot of time only to find that the tester backend was to blame. Also it does not really test the way a normal ethereum client backend would be as it's just a testing backend.

Regardless, having a few more tests in the non-full integration PR runs won't hurt and may even help us catch bugs. So I will approve this under the following condition:

- If the tester backend contracts start failing again and we realize they pass with geth and that it's some arcane problem with tester again we remove it. I don't want to waste any more developer time in debugging tester backend specific problems.
