### ISSUE TITLE
Remove the removedb feature

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#1976]
The removedb command should not be userfacing.

 Removing the local state in the mainnet would mean losing money so the user should never have access

**Comment by ulope** [comment]
How about keeping it but only allowing it to remove the db for non-mainnet network ids?

**Comment by LefterisJP** [comment]
@ulope no sorry. It's easy enough to remove the database manually for developers and that feature being there is a liability and sends the wrong message.

**Comment by ulope** [comment]
> It's easy enough to remove the database manually for developers

Yes, which might lead to people running `rm -rf ~/.raiden` without thinking about that they also have a mainnet db in there.

**Comment by LefterisJP** [comment]
@ulope No. With the same way of thinking you may run `rm -rf ~/.ethereum` without thinking the keystore is there. 

The point of this issue is simple. Don't make it easy for people to remove the local state. And also put warnings to never remove it unless they know what they are doing.

**Comment by pcppcp** [comment]
> The point of this issue is simple. Don't make it easy for people to remove the local state. And also put warnings to never remove it unless they know what they are doing.

which is much easier if you provide such command and print out big fat warning before executing it ;)

**Comment by LefterisJP** [comment]
> which is much easier if you provide such command and print out big fat warning before executing it 

Hmm .. ? No.

Providing the command in any form makes it easier to make a mistake than not providing the command at all. 

Let's agree to disagree and close the issue by merging #1980
