### ISSUE TITLE
Matrix test setup is flaky

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/raiden#1977]
#### Problem definition

Fixture setup sometimes fails to communicate with the matrix server, this is the raised exception:

> raiden.exceptions.TransportError: Unexpected error while communicating with Matrix homeserver: Something went wrong in GET requesting http://localhost:8008/_matrix/client/r0/sync: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

This is the [full log from the failed build](https://gist.github.com/hackaugusto/53984f6507dbe459795270fe74598874#file-gistfile1-txt-L3081)

Additional examples:
https://travis-ci.org/raiden-network/raiden/jobs/408896758#L2965
https://gist.github.com/hackaugusto/79f1aaf47819b17c6f01895f7b0126f0

#### Proposed solution

~~Wait for the matrix server to run before continuing with the fixtures setup~~ Already done by the miraku library

**Comment by ulope** [comment]
This already happens automatically through the `mirakuru` `HTTPExecutor`, butmaybe the URL it's trying to connect to to verify up-state needs to be adjusted.

**Comment by andrevmatos** [comment]
Example run of the issue: https://travis-ci.org/raiden-network/raiden/jobs/409855617#L1532
