### ISSUE TITLE
Investigate number of parallel matrix connections effect on performance

### ISSUE THREAD

**Issue by andrevmatos** [raiden-network/raiden#2012]
## Problem Definition

In https://github.com/raiden-network/raiden-libs/pull/115 and #2008, to circumvent an error where synapse starts refusing long-lived (keep-alive) connections when on heavy per-user load (as matrix requests are rate-limited, and in our tests, it gets pretty heavy), we reduced the number of matrix parallel connections to 4. As most of the data should go through `/sync` calls, and the rest are one-shot, short requests (like asking for a user' displayname or sending a message), it should not block the requests for long.
We need to benchmark raiden throughput with different parameters both for matrix clients connections, as well as different server parameters for rate limitations (DDoS prevention), document the impact of them on the throughtput and, if it's the bottleneck, find better working parameters.
Related: #61

**Comment by hackaugusto** [comment]
@andrevmatos @ulope is this still relevant?

**Comment by andrevmatos** [comment]
Yes, this is a backlog related to #2385 and #3199 , not required for now but should eventually be measured and dealt with, if needed.

**Comment by ulope** [comment]
Yes, it’s still relevant not at all a priority though.

**Comment by ulope** [comment]
Check once #4292 is implemented

**Comment by hackaugusto** [comment]
https://github.com/raiden-network/raiden/pull/5920 has introduce tools to stress test the synapse servers, the number of connections weren't a problem
