### ISSUE TITLE
Fix contracts deployment guide

### ISSUE THREAD

**Issue by czepluch** [raiden-network/raiden#2014]
## Problem Definition
According to a chat I had with Ulo the [Smart contract deployment guide](https://raiden-network.readthedocs.io/en/latest/smart_contracts.html) is currently not up to date. 

## Tasks
- [ ] Get list from @ulope describing how he deployed the contracts
- [ ] Adjust the guide to reflect above steps

**Comment by hackaugusto** [comment]
@loredanacirstea @czepluch  is this still relevant?

**Comment by LefterisJP** [comment]
@hackaugusto I am closing this since all contract deployment should be on the contracts repo and the linked doc does not even exist.
