### ISSUE TITLE
Include partner network status/presence in channels endpoints

### ISSUE THREAD

**Issue by andrevmatos** [raiden-network/raiden#2016]
## Proposal

As we already have neighbors (nodes with which we have a channel with) availability/reachability in our state (through `ActionChangeNodeNetworkState` state changes), we should include it in the channel's API responses, so the client (e.g. webUI) can display a nice indicator when the partner of a channel is online or not.

Example:
```
http http://localhost:5001/api/1/channels
[
    {
        "balance": 100,
        "channel_identifier": "0x6b44e524596ada26184cbc177ca8b4b3fdc31fed8f75bc7faa65cec09e36784d",
        "partner_address": "0xE0902284c85A9A03dAA3B5ab032e238cc05CFF9a",
        "partner_status": "reachable",
        "reveal_timeout": 10,
        "settle_timeout": 500,
        "state": "open",
        "token_address": "0x0f114A1E9Db192502E7856309cc899952b3db1ED",
        "token_network_identifier": "0x7692624c0C43285D51c0DdDfb2A6388f5002762E"
    }
]
```

For the `unreachable` status, we may also include the _last seen_ information on it, which is simply the time of the last `NODE_NETWORK_REACHABLE` event for that partner:
```
        "partner_status": "unreachable since 1533045701",
```

**Comment by christianbrb** [comment]
@hackaugusto Makes a lot of sense to have this functionality for the WebUI 👍

**Comment by karlb** [comment]
The client does not know about the partner's status, so this should be done by the UI (by talking to the PFS). See https://github.com/raiden-network/webui/issues/202.
