### ISSUE TITLE
Improve validation of contract bytecode

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#2017]
## Problem Definition

During https://github.com/raiden-network/raiden/pull/1997 there was a discussion [here](https://github.com/raiden-network/raiden/pull/1997#discussion_r206211092) about how we can improve the validation of the deployed contract bytecode.

This issue is to document the suggested method and track its implementation.

## Task

In the constructors of the proxies right where the `AddressWrongContract` is added in #1997, add another check:

1. If the network_id is not ropsten (or in the future mainnet) do nothing
2. If it is, somehow compare the bytecode. It is a bit more complicated due to the metadata hash which  also includes the filename so the comparison here is brittle. Check [here](https://solidity.readthedocs.io/en/develop/metadata.html#encoding-of-the-metadata-hash-in-the-bytecode) to see where the metadata are located and how we can compare without the metadata.
3. We should have the hash of the compiled bytecode (without the metadata) in constants.py for easy comparison

**Comment by hackaugusto** [comment]
Related #344

**Comment by LefterisJP** [comment]
Scoping this out of Red Eyes.

**Comment by hackaugusto** [comment]
The data published with the raiden-contracts packaged should be enough, I guess the addresses from that package can be trusted, everything else not.

**Comment by hackaugusto** [comment]
related: #2117 https://github.com/raiden-network/raiden-contracts/issues/359

**Comment by LefterisJP** [comment]
I am not working on this so I am unassigning myself.

**Comment by hackaugusto** [comment]
My bad this is the same issue as #3744 , I did not remember about it. Because I have updated the other issues to point to #3744 I'm closing this one.
