### ISSUE TITLE
Use `get_proof` instead of `merkleroot` with `proof` parameter

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/raiden#202]
The following pattern

```
proof = [for]
merkleroot(elements, proof)
```

Obscures the usage of the function to actually get the proof, the function `raiden/mtree.py:get_proof` is explicit about this intent.

**Comment by schmir** [comment]
My changes have been merged. Strictly speaking this issue is fixed. But I do think the comment from d4309ca51d4ed3ed32a36c102e1e86f83b46d1e7 should still be addressed:
```
    raiden.channel.BalanceProof.get_known_unlocks should probably create a
    mtree.Merkletree object and pass that to compute_proof_for_lock as it
    creates multiple proofs with the same merkletree.
```

@hackaugusto I've assigned you to this issue. Feel free to open a new one for the above or start tracking it here.
