### ISSUE TITLE
Raiden Client not compatible with Infura

### ISSUE THREAD

**Issue by BCsRock** [raiden-network/raiden#2027]
## Problem Definition
I am considering the possiblity of using a 3rd-party hosted Ethereum Full Node and decided to go with [Infura](https://infura.io/). This allows a small IoT Device to run the Raiden Client and interact with 3rd-party node. 

Reason is: not everybody has infrastructure to host an own full node, ensure it's 24/7 uptime, maintaining security updates and so on. 

The infura documentation regarding the available API Endpoints is shown [here](https://infura.io/docs/api/get/symbolFull). 

It covers a variety of methods of rpcapis: `eth_*, net_*, web3_*`

The problem is: when calling raiden with `--eth-rpc-endpoint https://ropsten.infura.io/<myToken>:<myPort>` it produces the error message:

```
Could not contact the ethereum node through JSON-RPC.
Please make sure that JSON-RPC is enabled for these interfaces:

    eth_*, net_*, web3_*

geth: https://github.com/ethereum/go-ethereum/wiki/Management-APIs
```

It would now be interesting to identify if there are actually necessary methods which are not provided by Infura's API endpoints.

### System Description

Ubuntu 16.04 LTS
Raiden-0.4.1-linux
Geth on Infura: Geth/v1.8.3-stable/linux-amd64/go1.10

**Comment by BCsRock** [comment]
Guys, you are awesome! Tested with version 0.5.0 today in our VM on our cloud server. It works like a charm. Using Infura Account as RPC interface, I was able to´establish a channel between two accounts, send tokens off-chain, close the channel. Everything without any failure. 

I really appreciate your development strength and I am sure this feature will make a lot of users happy in the future too (^_^)b

**Comment by palango** [comment]
@czepluch Should we mention this more prominently in the docs? I think this might be nice to know for people who just want to test raiden.

**Comment by czepluch** [comment]
That's a good idea.

**Comment by err508** [comment]
A description of the how to use Raiden with the Infura endpoint has been added to the docs [here](https://raiden-network.readthedocs.io/en/latest/overview_and_guide.html#using-eth-rpc-endpoint-infura).
