### ISSUE TITLE
Implement health check

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/raiden#203]
Periodic health check for all the open channels.
- [ ] For each address that has a queue in the protocol add a `last_received_time` variable.
- [ ] Update this variable each time a new message is received (for any sort of message)
- [ ] Add a Task that will send a Ping after the timer drift for a configurable `ping_timeout` amount of time
  - [ ] If no message is received for a configurable `unhealthy_timeout` set the node as unhealthy in the routing
- [ ] When the health check fails, remove the node from the graph.

**Comment by LefterisJP** [comment]
I will take this task. Will help me see yet another part of the codebase from up close.

Any further pointers/tips please write here in the issue.

**Comment by hackaugusto** [comment]
Notes:
- I proposed the use of `last_received_time` because if we are actively exchanging transfers I don't see the *need* for a Ping message.
  - so, while we are running this [loop](https://github.com/raiden-network/raiden/blob/f6745762d8a35e1e4f98c1704e1aae689ae52339/raiden/raiden_protocol.py#L94) or [not queue.empty()](http://www.gevent.org/gevent.queue.html#gevent.queue.Queue.empty) we don't need pings. Note: like `Ack` I don't think `Ping` needs to be in the queue because there are no ordering constraints.
- We don't actually need a `Task` for waiting, using `peek(timeout=ping_timeout)` for each message queue and checking for `None` should be suficient [1](http://www.gevent.org/gevent.queue.html#gevent.queue.Queue.peek).
