### ISSUE TITLE
Revise Raiden Glossary

### ISSUE THREAD

**Issue by czepluch** [raiden-network/raiden#2030]
## Problem Definition
We need to make sure that the Raiden glossary is kept up to date according to the specs and as the code base evolves.

## Solution
Go over https://github.com/raiden-network/raiden/blob/master/docs/glossary.rst and revise if the wording is up-to-date. Furher more it would be nice to get a better formation of the documents to make it easier to read and navigate.

## Tasks
- [ ] Go through the terms and make sure they are valid and relevant still
- [ ] Improve the formatting of the document to make it easier to read and navigate

**Comment by palango** [comment]
For #2084 we should at least add the term payment to it. I could only find the definition in the spec.

**Comment by LefterisJP** [comment]
Fixed by https://github.com/raiden-network/raiden/pull/2323
