### ISSUE TITLE
Remove dependencies from channel.py

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/raiden#204]
Keep the `channel.py` independent of the encoding and tasks layers.
- [ ] Move the message instantiation out of the `Channel` class
  - [ ] `create_directtransfer`
  - [ ] `create_lockedtransfer`
  - [ ] `create_mediatedtransfer`
  - [x] ~`create_refundtransfer_for`~
  - [x] ~`create_timeouttransfer_for`~
- [x] Move the alarm callback `blockalarm_for_settle` into another module

**Comment by LefterisJP** [comment]
@hackaugusto How about this issue? Do you consider it solved? Or is it something you also work on in your branch atm?

**Comment by hackaugusto** [comment]
Ah, lets close this issue, it doesnt have a good description and it will be done with the restartable channel.
