### ISSUE TITLE
Use authenticated GitHub API calls in linux bundle creating dockerfile

### ISSUE THREAD

**Issue by ulope** [raiden-network/raiden#2059]
## Problem Definition

The automatic bundling for linux often fails with the following error on Travis:
```
Step 11/21 : ADD https://api.github.com/repos/${REPO}/commits/${RAIDENVERSION} /dev/null
ADD failed: failed to GET https://api.github.com/repos/raiden-network/raiden/commits/v0.4.2 with status 403 Forbidden: {"message":"API rate limit exceeded for 35.202.145.110. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://developer.github.com/v3/#rate-limiting"}
make: *** [bundle-docker] Error 1
```

The reason appears to be that too many unauthenticated requests to the github API are performed form Travis' IP addresses.
To prevent this we should be using authenticated requests.

**Comment by LefterisJP** [comment]
This is not needed for Red Eyes. Scoping it out.

**Comment by ulope** [comment]
This causes random build failures (esp. now that we're working on nightly builds) so I'd argue that we do indeed need it.
