### ISSUE TITLE
Matrix connection refused

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/raiden#2069]
Fixture setup failed because matrix rejected new connections, log:

https://gist.github.com/hackaugusto/7d8f0ba77510b16aedd6ce3b94fe84f0
https://gist.github.com/hackaugusto/6e0e2da1bf5486ebaea4e3721e9e931d
https://gist.github.com/hackaugusto/0ba437055fb12f1db57c1c10ed490b0c

**Comment by andrevmatos** [comment]
#2062 should fix this.
