### ISSUE TITLE
WebUI: Channel Events view misses events

### ISSUE THREAD

**Issue by ulope** [raiden-network/raiden#2076]
## Problem Definition

The Channel events view in the WebUI often doesn't update with new events.

Steps to reproduce:
- Open a channel 
- Open 'Channel Events' view 
- Initiate a transfer from outside the WebUI (preferably to a partner that will send some tokens back, e.g. the echo node)
- Notice that most of the time the transfer events don't show up

The reason seems to be that the frontend uses a too strict block limit of only the current block when querying for the events. This leads to under-sampling of events if the call isn't performed at exactly the moment before a new block appears (which is unlikely to say the least).

Proposed solution: Use `from_block=<current - 1>` when querying for updates to the event list.

**Comment by hackaugusto** [comment]
The REST APIs Raiden is exposing ATM are really bad for pagination. The issue https://github.com/raiden-network/raiden/issues/2043 has a better proposal were the client app doesn't need to query the blockchain before getting Raiden's events.

**Comment by ulope** [comment]
Ah, yes that's a better solution. I'll close this one then.

**Comment by andrevmatos** [comment]
Just a headsup: this webui-side paging/walking was done to workaround that bugs that made geth events fetching veerrry slow in the past. Just fetching all events as seen by raiden and replacing the list, if it's quick enough, should be a better approach.

**Comment by LefterisJP** [comment]
>  fetching all events as seen by raiden and replacing the list, if it's quick enough,

That is not good. The more events (the more in the past you query the ethereum node) the more it will wait.
