### ISSUE TITLE
Add logging to Rest API methods

### ISSUE THREAD

**Issue by ulope** [raiden-network/raiden#2078]
## Problem Definition

Currently the Rest API layer contains no logging calls at all. That is sub-optimal, especially for longer running and chain interacting requests such as channel opening, deposit, close etc. since there is no indication in the log that anything is happening until chain events start coming back which can take quite a while depending on block time, chain congestion etc.

Solution: Add logging calls at least to the Rest API layer for at least long-running operations.

**Comment by LefterisJP** [comment]
So you mean something like "Requesting `X` endpoint with `A`, `B`, `C`.. arguments before each call to the underlying python API?

**Comment by andrevmatos** [comment]
Notice `flask` already do some logging for every request. We may want to get that suppressed if we plan to add our own, more informative logging to these calls.

**Comment by ulope** [comment]
@LefterisJP Yeah basically. Maybe with the messages more oriented on the business logic though (e.g. `Create channel request partner=0x... token=0x... deposit=...`

@andrevmatos The flask logging is fine but only happens *after* the request is completed which won't help with long running ones.
