### ISSUE TITLE
Replace Delivered messages in matrix with read receipts

### ISSUE THREAD

**Issue by andrevmatos** [raiden-network/raiden#2081]
## Problem Definition

Matrix protocol have read receipts events built-in. These events may be used to inform the peer in a p2p room that we've received and are handling a message, getting rid of the additional `Delivered` message round-trip, and, together with fetching of room history (events and messages that were sent while we were offline or still hadn't joined the room), improve matrix reliability on message delivering as well as reduce the number of messages needed, decreasing latency and required bandwidth either from the peers as well as the servers.

Only drawback is that read-receipt events are in a _up-to_ basis, so we may have to wait for a read-receipt for a message before sending the next, which IMO is also an improvement, to prevent spamming the rooms while the peer is offline or waiting for something to happen.

Everything here affects matrix transport only, and no changes on core/inner layers should be required.

Related: #1951 
Long-standing  TODO in code: https://github.com/raiden-network/raiden/blob/784c50d5d88bb02fd6fe1558e137aa78cf33087d/raiden/network/transport/matrix.py#L542-L546

**Comment by ulope** [comment]
That would be very useful to improve round-trip time since it will significantly cut the number of messages being sent.

We do need to keep the caveat I mentioned in the TODO comment Andre linked above in mind though.

**Comment by LefterisJP** [comment]
@andrevmatos Is this **really**, **really** required for Red Eyes? It seems like just an enhancement? Can we scope it out of Red Eyes?

**Comment by andrevmatos** [comment]
@LefterisJP no, it's not **really, really** required. #2268 should improve a bit the current behavior, so we can put this one on backlog

**Comment by LefterisJP** [comment]
Thank you Andre. We already got enough work for this milestone as it is. We can implement this soon after the mainnet release.

**Comment by ulope** [comment]
We also discussed this with Matthew from Matrix. 

He also agreed that due to the unpredictable message order in federated contexts the read receipts aren't suitable for our purposes. 

However, since matrix is a reliable protocol we may want to simply drop the `Delivered` messages alltogether. Separate proposal issue will follow.

**Comment by ulope** [comment]
Replaced with: #2383
