### ISSUE TITLE
Make sure that the UI is still functional after the event API changes and the transfer->payment rename

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#2090]
After https://github.com/raiden-network/raiden/issues/1949, https://github.com/raiden-network/raiden/issues/1898 and https://github.com/raiden-network/raiden/issues/2084 are solved, the API will have some considerable changes which may break the UI.

Check what changes are required in the UI to adjust it to the aforementioned API adjustments and then implement them. The end result is that the UI should be fullly functional as it was before the API changes.

**Comment by LefterisJP** [comment]
@czepluch Also make sure the docs are updated for all these changes.

**Comment by palango** [comment]
@kelsos #2085 has been merged, should be a simple change of the endpoint when sending payments.

**Comment by andrevmatos** [comment]
Maybe also renaming `Transfer` to `Pay`, to keep compliant with our Glossary

**Comment by kelsos** [comment]
@andrevmatos I proceeded with the changes, however I would like to verify with you just to be sure. Does it make sense to change transfer to Pay/Payment everywhere in the webui, or is there perchance a specific dialog or page where it should remain transfer?

**Comment by andrevmatos** [comment]
Can't see a place where it would make sense to keep `Transfer`, maybe only possibly in some event that may come (no need to search/replace strings there, etc). UI-wise, if I understood correctly the discussions, `Payment` it the term to be used where we refered to `Transfer`s. @palango may correct me if I'm wrong

**Comment by palango** [comment]
Yes, payment should be the user visible term.

We also discussed if the **Payment** menu item still makes sense on a per channel basis, but we have to discuss that a bit more.

**Comment by LefterisJP** [comment]
@kelsos yes please change all transfers to payments. We want to have consistent terminology. Remember `transfer` is what happens inside a channel, only between 2 participants .. but what the user cares about is payments .. sending tokens to others through multiple channels.

**Comment by kelsos** [comment]
Ok thanks :+1:

**Comment by kelsos** [comment]
@LefterisJP I am closing this since this should be at least partially fixed by #2146
