### ISSUE TITLE
When nodes become unreachable update the status in the graph

### ISSUE THREAD

**Issue by utzig** [raiden-network/raiden#210]
Nodes may become unreachable. There is treatment for messages failing to be delivered but the graph still has information about those nodes which means when running something like `get_best_routes` it may return invalid paths. When finding nodes that are unreachable the graph should be updated to signal the condition and not try those paths.

**Comment by konradkonrad** [comment]
See also #203

**Comment by konradkonrad** [comment]
duplicate of #203
