### ISSUE TITLE
define connection manager behavior

### ISSUE THREAD

**Issue by pcppcp** [raiden-network/raiden#2100]
## Problem Definition

Connection manager (CM) is used to automatically join the token network using a certain amount of funds. It will automatically create payment channels with random peers and will distribute the funds equally across the channels.

There're several problems with the implementation
- the peers to create the channels with are chosen randomly, regardless of their state. Online nodes should be preferred instead.
- current implementation could use some refactoring in regard to parallel `connect()` calls. Now it just serializes parallel operations with a lock, which can sometime lead to confusing results.
- the REST api allows multiple calls to `connect()` method, even when the network channel join/deposit cycle is in progress. In such case it would be appropriate to return E409 if the network join is in progress. A GET request to `/api/1/connections/<token_address>` should return status of connection manager as well

To play devils advocate, I think that connection manager is an ideal candidate to remove from Raiden core - anything it does could be done in a couple of REST calls, either sent by a cli tool or a webUI.

**Comment by andrevmatos** [comment]
Some thoughts:
About 1. #1142 #1945 , also I have some ideas on using non-binding messages to query if possible new partners would be willing to counter-deposit in the channels we'd be about to open, and prefer those, to have a better connected network, but I doubt that'd be given enough priority any time soon (as most of my wished improvements)
About 2. as this call should be idempotent (i.e. same results with same parameters) this is not a big concern IMHO
About 3. yes, that'd be good and easy to do with the lock in place (by trying to non-blocking lock and handling the exception)

**Comment by hackaugusto** [comment]
duplicated https://github.com/raiden-network/raiden/issues/576
