### ISSUE TITLE
Handle the ContractReceiveUpdateTransfer state change

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/raiden#2109]
Is not being dispatched and handled at the moment ContractReceiveUpdateTransfer

**Comment by LefterisJP** [comment]
@hackaugusto Hmmm you are right. Should be easy to do. Was just looking at that code. But what should the action on the channel be if updateTransfer() was called?

**Comment by hackaugusto** [comment]
> Was just looking at that code. But what should the action on the channel be if updateTransfer() was called?

The state of the channel should be transition from "need to call update" to "dont need to call update" iff the state change contains the latest balance proof hash. And the contract send update should not be sent if the current state is "dont need to call update"
