### ISSUE TITLE
Signed releases

### ISSUE THREAD

**Issue by ulope** [raiden-network/raiden#2117]
## Problem Definition

Once we move to the mainnet we need to sign our releases.

We should define a fixed set of release managers whose gpg key IDs are listed in a file hosted on https://raiden.network. This is important to ensure that the list is not simply changeable via the Raiden github repo at it would if the list were contained in the documentation (since that is built automatically from the source). We should still link from the documentation to this list though.

The release managers should include:
- One key that is exclusively used by the automated deployment system running on Travis CI.
- At least two Raiden team members.

Suggested process for making a release:
- The version tag from which the binaries are built must be signed by one of the release managers (which means we need to change our process slightly again)
- Alongside the binaries the Github releases page must include `<release-file>.asc` signature files that have been created by running `gpg --local-user <release-mgr-key-id> --armor --detach-sign <release-file>` by one of the release managers' keys.
- The automated deployment must verify that the tag has been signed by an authorized key before producing and signing release binaries

**Comment by LefterisJP** [comment]
Agreed. This is an important procedure to have. Can you handle it with the support of someone else? And who would you need support from @ulope ?

**Comment by hackaugusto** [comment]
I will hijack this issue and ask, what about signed commits? I'm currently doing it, but Github rewrites the commits when it does a rebase, even if it's not needed, so having signed commits would change our workflow.

**Comment by pcppcp** [comment]
@hackaugusto are you talking about having signed commits as a requirement?

**Comment by hackaugusto** [comment]
> are you talking about having signed commits as a requirement?

For the core developers, yes. I'm not suggesting we should do it *right now*, but it would be interesting to see other's opinions.

**Comment by pcppcp** [comment]
I think it's an overkill. Even Bitcoin or geth repos don't require them, why should Raiden?

**Comment by hackaugusto** [comment]
> I think it's an overkill. Even Bitcoin or geth repos don't require them, why should Raiden?

Thinking it's overkill is okay, but because other projects don't do it doesn't mean much.

**Comment by LefterisJP** [comment]
I would not start by saying it should be a requirement but encouraging it would be nice.

**Comment by hackaugusto** [comment]
> I would not start by saying it should be a requirement but encouraging it would be nice.

The downside is that we would have to merge PRs from the command line and push to github, instead of using the rebase button from git's interface.

**Comment by ulope** [comment]
Not necessarily. Github signs commits made from the UI with it's own key.

**Comment by LefterisJP** [comment]
@ulope The problem we got with the UI is that whenever we press "Rebase and merge" there are new hashes to the commits since they are rebased and they can't be signed. Rebasing locally re-signs the commits.

Any way around this you are aware of?

**Comment by christianbrb** [comment]
Set up a meeting to decide how we execute it. Define the process.

**Comment by err508** [comment]
@ulope and me discussed three approaches to sign releases on github:

1. Sign mainnet releases manually with (hardware-) keys 
2. Sign mainnet releases automatically via CircleCI 
3. Integrate a more concise solution to the problem like [TUF](https://theupdateframework.github.io/) to also have signed PyPI releases, be ready for automated (signed) Raiden updates, etc.

Implementation effort of 1, 2 is low and can be extended to 3 once done. 1 is arguably more secure than 2 but introduces some overhead when making a release, please provide input if you prefer automated signing or are comfortable with manual signing/key management @LefterisJP @rakanalh @pirapira .

**Comment by pirapira** [comment]
I'm willing to keep some key storing hardware.

**Comment by LefterisJP** [comment]
I am comfortable with manually signing releases through hardware. As long as, this is not for nightlies and we have a common understanding we want to extend this to (3) and remove all manual steps from releases in the near future.
