### ISSUE TITLE
Revisit the gevent patch for exception handling

### ISSUE THREAD

**Issue by jomuel** [raiden-network/raiden#2123]
Cf issue #1829. The last changes to the patch (#2122) were done hastily after the previous solution (#2041) was merged in a faulty state and broke master. Revisit this issue and:

- Check if the newly introduced `rawlink_safe` functions really make sense - can it even happen that callables linked to an `Event` or `AsyncResult` must handle an exception from these?
- Check if they are actually called (the patched error handler in `gevent_utils.py` only checks if the current _greenlet_ is safe-linked.)
- Make sure the new solution is reasonably complete
- Update tests and docs accordingly.

(Edit: removed the task list as it has changed, see comment below)

**Comment by andrevmatos** [comment]
Some comments: AsyncResult and other events classes aren't C extensions, and can have its methods monkey-patched. Also, I'd call for mirroring the name and shadowing the method names in a children class, to implement the new behavior, so it can keep compatibility with the interface and be drop-in replaced. `configure_gevent` may need to be called before other modules import gevent though.

**Comment by jomuel** [comment]
Thanks for these suggestions @andrevmatos.

- You are right, the `link`, `link_exception` and `rawlink` methods can be overriden instead of defining new `link_safe` etc methods. As long as we know our methods have been called to link and the callables are wrapped, exception handling stays safe.
- `AsyncResult` and `Event` can then be monkeypatched instead of derived, but it is probably not necessary to modify them at all (I'm writing a unit test to verify that).

**Comment by jomuel** [comment]
As turned out in discussing issue #2179, gevent does what we need out-of-the-box - its default behavior regarding unhandled exceptions in greenlets is to bubble them up to the parent greenlet. The only problems that remain are a faulty usage of `Greenlet.link_exception` and cases where flask catches unknown exceptions and turns them into non-fatal `500`s. The new plan for this issue is thus

- [ ] revert all gevent patching that has been done
- [ ] add a test to ensure exception handling works as expected
- [ ] check the uses of `link_exception` in the code.

The flask-related instances will be taken care of in issue #2179.

**Comment by jomuel** [comment]
Replaced by #2201
