### ISSUE TITLE
Version the database to make breaking testnet upgrades easier

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/raiden#2134]
Instead of asking users to remove the database when a breaking change is introduced, we should make a new database and leave the old one behind, in case there are still actions that need to be executed, e.g. leave the token networks.

### Tasklist

- [x] Add a constant to define the current version of the database.
- [x] Use the database version as part of the database path (either the path or in the sqllite .db name)

**Comment by palango** [comment]
Fixed by #2200
