### ISSUE TITLE
MatrixRequestError: 404: {"errcode":"M_UNKNOWN","error":"No row found"}

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#2137]
At #2035's latest build there are 3 failing matrix tests with the errror:

`matrix_client.errors.MatrixRequestError: 404: {"errcode":"M_UNKNOWN","error":"No row found"}`

Travis Build: https://travis-ci.org/raiden-network/raiden/jobs/414283939
Raw Travis Log in a Gist: https://gist.github.com/LefterisJP/57b0488d443c96e8e09b3e0f8bdf4adf

**Comment by andrevmatos** [comment]
Seems like some other form of those setup/teardown bugs on synapse firing. I'm looking into it.
