### ISSUE TITLE
Separate development requirements from the application requirement

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/raiden#214]
Development dependencies:

```
pytest
pytest-timeout
tox
sphinx
u-msgpack-python
```

These can be moved to a `requirements-dev.txt` file:

```
-r requirements.txt

pytest
pytest-timeout
tox
sphinx
u-msgpack-python
```

Or we can remove the magic from the `setup.py` and leave `requirements.txt` as is [python-guide](http://docs.python-guide.org/en/latest/writing/structure/?highlight=requirements#requirements-file).

**Comment by hackaugusto** [comment]
I actually favor the second option, python's packaging is by itself so I would like to remove any magic from `setup.py`. Yes we will have some duplication, but it will be just a few lines of dependencies. Thoughts?

**Comment by LefterisJP** [comment]
I am all for separating development from production requirements.

I just noticed the magic in `setup.py`.

Is this what you refer to?

```python
install_requires = list(set(
    install_requires_replacements.get(requirement.strip(), requirement.strip())
    for requirement in open('requirements.txt')
))
```

I don't really understand your second suggestion though. What is wrong with just having a `requirements-dev.txt`?

**Comment by hackaugusto** [comment]
> Is this what you refer to?

Yes.

> I don't really understand your second suggestion though. What is wrong with just having a requirements-dev.txt?

The `requirements-dev.txt` per se, nothing, it's fine, but if we keep the application depencendies in the `setup.py`, instead of reading the contents of `requirements.txt`, it makes no sense to have two files.

**Comment by LefterisJP** [comment]
Aha, so you mean keep it one file, `requirements.txt` and then filter for production only requirements in `setup.py`?

**Comment by utzig** [comment]
I would prefer to just have the two requirements files (very standard practice) and remove that install section from `setup.py`.

**Comment by hackaugusto** [comment]
> I would prefer to just have the two requirements files (very standard practice)

Both strategies are pretty common, could you elaborate on why requirements file are better?

> and remove that install section from setup.py.

You mean, preserve the `open("requirements.txt")` as it's today? Removing the install section cannot be done, we need the `install_requires` is used for dependency resolution, without it our users wont have the appropriate depedencies installed.

To better express my opnion:

`install_requires` and a `requirements.txt` file are not the same thing, the former is a [list of package names with an optinal version specifier](https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-dependencies), the later is a list of arguments accepted by the `pip` tool, so the [requirements.txt can have directives](https://pip.pypa.io/en/stable/reference/pip_install/#requirements-file-format) like `--index-url`, `-r` and so on.

Also, ideally the `install_requires` represents the minimum set of [abstract requirements](https://caremad.io/posts/2013/07/setup-vs-requirement/) for the application to execute, while the `requirements.txt` should have the concrete requirements.

**Comment by LefterisJP** [comment]
@hackaugusto Since I just added yet another package in the `requirements.txt` which should go to `dev_requirements.txt` instead can we just settle on something here? I find having 2 separate requirements files very simple and straightforward. Can we just go with it for now and then improve it if indeed required?

**Comment by hackaugusto** [comment]
Sure :)
