### ISSUE TITLE
Create tests for RaidenService

### ISSUE THREAD

**Issue by rakanalh** [raiden-network/raiden#2156]
## Problem Definition

At the moment, RaidenService is not covered by tests. This issue is created to have tests created for the service so that changes are tested.

**Comment by hackaugusto** [comment]
@rakanalh is this still relevant? could you list the tests you have in mind?

**Comment by LefterisJP** [comment]
I guess it's implicitly tested through all of our end to end and API tests

**Comment by hackaugusto** [comment]
I agree with @LefterisJP

**Comment by rakanalh** [comment]
The problem i see with implicitly testing the service is that not all code paths are properly visited. However, given the needed setup for the tests, i think it's going to be somewhat hard to test this in isolation.

Closing issue.
