### ISSUE TITLE
WAL tests should be done with Raiden States

### ISSUE THREAD

**Issue by rakanalh** [raiden-network/raiden#2157]
## Problem Definition

The current unit tests for WAL make sure that storing and restoring dummy states works. However, we need to make sure that we use Raiden-specific states are used to simulate real-world scenarios.

**Comment by hackaugusto** [comment]
@rakanalh is this still valid? If you think we still need the tests, I would argue it should be limited to the serializers and do the same thing we have for messages:

https://github.com/raiden-network/raiden/blob/9d8feb2f71e45174b86294df822efacdf26020c0/raiden/tests/unit/test_binary_encoding.py#L85-L96

**Comment by rakanalh** [comment]
I think this was implemented at some point in `test_sqlite.py`. Closing issue.
