### ISSUE TITLE
investigate: identifier_to_results can actually not contain an identifier

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#2159]
## Problem Definition

On 10/08 on a chat with @hackaugusto we determined that `identifier_to_events` must always contain the [handled payment identifier](https://github.com/raiden-network/raiden/blob/master/raiden/raiden_event_handler.py#L137) and that we should not test for existence of identifier inside the dict as that would hide a bug. [Tests](https://travis-ci.org/raiden-network/raiden/jobs/414583281) showed that either this was wrong or we already have a bug: https://github.com/raiden-network/raiden/pull/2158

## Task

Investigate what is happening and fix the codebase accordingly

**Comment by pcppcp** [comment]
After extensive testing, I couldn't reproduce this bug, using both Travis and local tests.

Reading the affected parts of the code didn't help either. I suggest closing this issue, we can reopen it again if the bug occurs again.

**Comment by hackaugusto** [comment]
> I suggest closing this issue, we can reopen it again if the bug occurs again.

The bug won't happen again with the current code base, to avoid errors with users we have two conditionals:

[1](https://github.com/raiden-network/raiden/pull/2158/files#diff-7ad95324bffb7475f8c35bef86abdb6aR137), [2](https://github.com/raiden-network/raiden/pull/2158/files#diff-7ad95324bffb7475f8c35bef86abdb6aR150) which are hiding the bug

So closing the issue would put this in the limbo

**Comment by LefterisJP** [comment]
Fixed by #2311
