### ISSUE TITLE
Make Raiden messages forward and backward compatible -- message versioning

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#2161]
## Problem Definition

Raiden messages must be versioned and be forwards and backwards compatible.

## Specification

- The first version of the messages is going to be the Red Eyes mainnet release, defined as version 0.
- We are going to be forwards and backwards compatible, meaning that nodes can send to and receive messages from both newer and older versions. We are going to keep this compatibility as long as we can but we reserve the right to break it as some future major release.
- In order to achieve this backwards and forwards compatibility we:
    - We never remove fields from messages
    - Even if in a newer version an old field is no longer used we will have to populate it with the proper value so that it's understandable by older version nodes.
- Add a handshake mechanism, composed of a new off-chain message which would negotiate the features supported by each node and also the version of its messages.
- Depending on the version of our partner that we learn from the handshake we send him the proper message format.

**Comment by hackaugusto** [comment]
What could be done as ground work has been done, now we need to make sure that changes to the message format maintain compatibility.

**Comment by hackaugusto** [comment]
I see, I was under the impression it was about groundwork because of the other items in the list. So we can just supersede this with #3283

**Comment by LefterisJP** [comment]
Fine by me
