### ISSUE TITLE
Remove expired transactions from the queue

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/raiden#2169]
## Problem Definition

Currently the queue clearing logic is not taking into consideration the fact that a transaction can expire, specifically the secret registration and update transfer transactions are time dependent, and it doesnt make sense to send these transactions after a given block number.

## TODO

- [ ] Implement logic to remove expire transaction.

**Comment by palango** [comment]
Is this completed with #2172 ?

**Comment by hackaugusto** [comment]
@palango yes :)
