### ISSUE TITLE
Exposing total_deposit on channels in the rest API

### ISSUE THREAD

**Issue by kelsos** [raiden-network/raiden#2176]
## Problem Definition

The webui uses the user's `balance` to calculate the new deposit when updating the `total_deposit`. The webui requires a user to insert then number of tokens to add to the deposit, then adds this number to the channel's balance and updates the channel's total deposit.

If the current balance is 10 and the user want's to increase the deposit by 10, the webui will send a `total_deposit` of 20, however if I have a channel with a `total_deposit` of 20 and the send a payment of 10 tokens to someone my balance in the channel will be 10. 

Essentially this means that if I try to increase the `total_deposit` by 5 the webui will send a `total_deposit` of 15 where it should send a 25.

**Comment by LefterisJP** [comment]
Okay so this is indeed an issue.

Two things needs to be done.

1. Add the`total_deposit` to the ChannelSchema returned by the Rest API and edit the docs. I will do this today.
2. Edit the WebUI to make sure that the total deposit is used when depositing to a channel and not the balance. @kelsos you should handle this.
