### ISSUE TITLE
Exposing more information about the channel on the rest API

### ISSUE THREAD

**Issue by kelsos** [raiden-network/raiden#2177]
## Problem Definition

![image](https://user-images.githubusercontent.com/2269732/44078427-b88a82f0-9fa6-11e8-9b49-c8c61b38eb10.png)

In the mockups there is a progress bar in the channel balance depiction showing a current/available balance, however it is unclear what available is supposed to represent. Is it supposed to be the total_deposit or maybe the total channel capacity?

Would it make sense showing a bar like this, and what data should be depicted. In a small discussion @palango also suggested that it would be nice to show any locked amounts.

What do you think would make sense to visualize from a user's perspective, and how easy it would be to expose such information on the REST API?

**Comment by hackaugusto** [comment]
> What do you think would make sense to visualize from a user's perspective, and how easy it would be to expose such information on the REST API?

I don't think a bar is of any use if it shows the on-chain values (like `total_deposit` or `channel_capacity`), I would show the *current* node's available balance. (Note: We may be using different names for the same thing here, is the channel capacity the off-chain capacity of a participant?)

**Comment by kelsos** [comment]
@andrevmatos That would be nice to have.

**Comment by palango** [comment]
@kelsos Is this fixed by https://github.com/raiden-network/raiden/pull/2241 ?

**Comment by kelsos** [comment]
@palango This is more of a discussion about what more information we can expose to the webui for each channel so I am guessing it is not really done yet. `total_deposit` was a different issue. This is more about how we could visualize the channel balance state on the webui.

**Comment by LefterisJP** [comment]
@kelsos Can we close this issue from here? Have you gotten all the feedback you require? Especially considering the webui is in its own repo right now.

**Comment by kelsos** [comment]
@LefterisJP yes I will go ahead and close the issue. If we have any specific requests for specific APIs and information we can open new issues for them with @manuelwedler
