### ISSUE TITLE
Show a notification on webUI when a transfer is received and new channel is opened with us

### ISSUE THREAD

**Issue by andrevmatos** [raiden-network/raiden#2192]
## Problem Definition

As when a outgoing transfer succeed, we should show a success notification when receiving a transfer on any of the open channels, or a new channel is opened with us. Maybe also add some _highlight_ animation to the channel and balance too, if currently on the channels screen.
Related: #2188

**Comment by kelsos** [comment]
@andrevmatos let's keep the highlight idea somewhere for future improvements. 
The notifications are now implemented as part of #2188
