### ISSUE TITLE
Handle transaction specific failures

### ISSUE THREAD

**Issue by rakanalh** [raiden-network/raiden#2194]
A follow up to #1966:

## General transactions failures which are unrecoverable
- [ ] Transaction removed from the pool:
  - [ ] The nonce was invalid (too-low). Considered a bug when local signing is used.
  - [ ] The gas was invalid (lower than the minimum)
  - [ ] Another transaction overwrote it (same nonce, higher gas). Considered a bug if we are not trying to increase the probability of the transaction being mined (which is the case as of https://github.com/raiden-network/raiden/commit/d329583e492798e558f84ac1d839f345384d231d).
- [x] The transaction had data and the `to` address never had bytecode
- [x] The transaction failed because the `start_gas` was too low [OOG]
- [x] A transaction which hit an assert

The above cases should raise `RaidenUnrecoverableError` which is handled by `on_raiden_event`.

## General transactions failures which are recoverable

- [x] The transaction start gas was higher than the block gas limit
- [ ] A transaction to a smart contract address which has selfdestructed
- [x] A transaction which hit a revert

The above cases should raise `RaidenRecoverableError` which is handled by `on_raiden_event`.

**Comment by hackaugusto** [comment]
>  The transaction failed because the start_gas was too low [OOG]

This cannot be verified by the JSONRPCClient because it cannot differentiate an OOG error from an assert. This is currently being done in the proxies.

**Comment by hackaugusto** [comment]
>  A transaction which hit an assert

The JSONRPCClient can check that this is the case, however it cannot provide a good error message. This is currently done in the proxies.

**Comment by hackaugusto** [comment]
>  The nonce was invalid (too-low, too-high). Considered a bug when local signing is used.

A high nonce is not ignored if it is a local transaction.
