### ISSUE TITLE
Detect and handle proxy calls with invalid balance proofs

### ISSUE THREAD

**Issue by rakanalh** [raiden-network/raiden#2195]
A follow up to #1966:

The following cases should be detected and `RaidenUnrecoverableError` should be raised:
- [ ] close with an invalid balance proof hash
- [ ] updateTransfer with an invalid balance proof hash
- [ ] settle with invalid balance proof data

**Comment by hackaugusto** [comment]
For close and update we only need to verify the signature, if it's invalid throw.
For the settle we can compute the balance hash in the proxy, and if it doesn't match throw.

**Comment by hackaugusto** [comment]
Done by:

- close https://github.com/raiden-network/raiden/pull/3961
- update https://github.com/raiden-network/raiden/pull/3897
- settle https://github.com/raiden-network/raiden/pull/4276
