### ISSUE TITLE
WebUI must handle token decimals

### ISSUE THREAD

**Issue by andrevmatos** [raiden-network/raiden#2197]
## Problem Definition

Right now, webUI shows tokens as Raiden sees it: only token `wei`s, as integers. The webUI/client is responsible for managing token decimals, and should handle it gracefully. Each token contract have a `decimals()` method which returns an integer for the amount of decimals this token is configured with. UI `input type="number"`s should convert from decimal number to integer before sending the values to the REST API (`raiden_amount = int(input_amount * 10**decimals)`) and prevent user from entering more decimals than token supports, and places where any amount/deposit/balance is displayed should take it into account (`ui_amount = raiden_amount / 10**decimals`). `BigNumber` may be required. `RaidenService` may do it before handling data to the rest of the components.

**Comment by kelsos** [comment]
@LefterisJP I decided to deploy a test token and I just replaced `uint8 public decimals = 18;` with     `uint8 public decimals`; This returns a 0, but zero can be a valid value for a non divisible token. Is that what you meant by missing or did I misunderstood something?

**Comment by LefterisJP** [comment]
No you misunderstand. Of course it would be 0 if the variable is not initialized. Missing means the contract not having the `decimals` attribute at all.

**Comment by kelsos** [comment]
@LefterisJP Thanks for clarifying I will look into it. I just remembered we already discussed this in person along with the approach to solve it. I am almost sure that the current webui will not be able to handle the missing value.
