### ISSUE TITLE
Web UI is not working with 0.5.0 binary release

### ISSUE THREAD

**Issue by czepluch** [raiden-network/raiden#2198]
## Problem Definition

When trying to access the webui when running the recent release as a binary all I get is `{"errors": ["invalid endpoint"]}`. @kelsos confirms that he gets the same. 

### System Description

I start Raiden with: 
```
./raiden-0.5.0-linux --eth-rpc-endpoint http://geth.ropsten.ethnodes.brainbot.com:8545 --keystore-path ~/.ethereum/testnet/keystore
```

**Comment by andrevmatos** [comment]
@ulope looks like this is in the last released binary. Any chance `compile_webui` may have failed unnoticeably and left the webui files out of the release?

**Comment by ulope** [comment]
Yeah that'd be my guess as well. I wasn't here last friday. Do any of you remember if the linux build (that's what @andrevmatos and @czepluch have been using I guess) was built manually or on travis?

**Comment by czepluch** [comment]
I actually think it was also a problem in the release before 0.5.0. At least now I remember that I saw the same message when trying to open the UI, but didn't think about it because I didn't actually need it at that point in time. So might have been introduced earlier than 0.5.0.
