### ISSUE TITLE
Re-enable automatic PyPI release uploads

### ISSUE THREAD

**Issue by ulope** [raiden-network/raiden#2205]
## Problem Definition

We had to disable automatic PyPI release uploads in #2204 due to the fact that our auto deployment user `raiden_pypi_automated` is currently unusable since it has no associated email address. And we have no access until @konradkonrad comes back.

**Comment by LefterisJP** [comment]
In the last release's build the automatic PyPI uploading failed: https://travis-ci.org/raiden-network/raiden/jobs/437840495#L4404

It needs to be fixed.

**Comment by LefterisJP** [comment]
closing this in favour of #2701
