### ISSUE TITLE
Unable to obtain token list

### ISSUE THREAD

**Issue by pciccioni** [raiden-network/raiden#2218]
## Problem Definition

I've installed from scratch a raiden node, i can start parity client correctly and raiden (0.5.0 first and the upgraded to 0.5.1) but after raiden started i cannot obtain token list , i run `curl -i http://localhost:5001/api/1/tokens` but i receive the following:

HTTP/1.1 200 OK
mimetype: application/json
Content-Type: application/json
Content-Length: 2
Date: Mon, 20 Aug 2018 16:15:08 GMT

[raiden-debug.log](https://github.com/raiden-network/raiden/files/2303132/raiden-debug.log)

Raiden also logs debug information to the `raiden-debug.log` file. Please attach it to the
issue as it may help us find the source of the issue faster.

### System Description

Here add a detailed description of your system, e.g. output of the following script:

```

uname -a : Linux Raiden 4.15.0-32-generic #35-Ubuntu SMP Fri Aug 10 17:58:07 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

command -v solc && solc --version: nothing
command -v geth && geth version: nothing
command -v parity && parity --version: /usr/bin/parity
Parity
  version Parity/v1.11.8-stable-c754a02-20180725/x86_64-linux-gnu/rustc1.27.2
Copyright 2015, 2016, 2017, 2018 Parity Technologies (UK) Ltd
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

By Wood/Paronyan/Kotewicz/Drwięga/Volf
   Habermeier/Czaban/Greeff/Gotchac/Redmann

 command -v ./raiden-0.5.1-linux && ./raiden-0.5.1-linux version:  
./raiden-0.5.1-linux
{
  "raiden": "0.5.1",
  "python_implementation": "CPython",
  "python_version": "3.6.3",
  "system": "Linux 64bit_ELF 4.15.0-32-generic x86_64",
  "distribution": "bundled"
}

[ -d .git ] && git rev-parse HEAD: nothing
```
Thats'all

**Comment by czepluch** [comment]
Can you also provide the commands you use to start parity and raiden?

**Comment by pciccioni** [comment]
to start the parity client:
/usr/local/src$ more run-parity.sh
/usr/bin/parity --chain=ropsten  --keys-path=/usr/local/.ethereum/keys --db-path=/usr/local/.ethereum/ --bootnodes
 "enode://20c9ad97c081d63397d7b685a412227a40e23c8bdc6688c6f37e97cfbc22d2b4d1db1510d8f61e6a8866ad7f0e17c02b14182d37
ea7c3c8b9c2683aeb6b733a1@52.169.14.227:30303,enode://6ce05930c72abc632c58e2e4324f7c7ea478cec0ed4fa2528982cf3448309
4e9cbc9216e7aa349691242576d552a2a56aaeae426c5303ded677ce455ba1acd9d@13.84.180.240:30303" --no-warp --jsonrpc-cors=
* --unsafe-expose

to start raiden:
./raiden-0.5.1-linux --keystore-path /usr/local/.ethereum/keystore

**Comment by czepluch** [comment]
Alright. I have now recreated the issue by using Parity. I usually use geth, but I get an empty token list using Parity.

**Comment by andrevmatos** [comment]
I also saw this issue in the past, it's not related to Raiden node itself, but Parity sometimes losing historical db and needing a full resync to recover itself (and then Raiden not fetching the events it needs to populate the tokens list and everything else).

To check it's a Parity issue, do the following:
1. Open a browser with Metamask on Ropsten network
2. Create a filter in the default token network registry, for the TokenNetwork event:
```
filter = web3.eth.filter({fromBlock: 0, toBlock: 'latest', address: '0x445d79052522ec94078dfccf96d9302775ca5b4e', topics: ['0xf11a7558a113d9627989c5edf26cbd19143b7375248e621c8e30ac9e0847dc3f']})
```
3. Fetch the logs: `filter.watch(console.log)`
4. Repeat from 1., but now pointing Metamask to the `localhost:8545` or your local parity node

Here, on first case, the `filter.watch` outputed the 6 currently registered token events, while on second case, nothing. After a full parity resync, the second case also got me the tokens.

**Comment by CosminNechifor** [comment]
@pciccioni can you delete your database and try again with the latest master?

**Comment by cmenzani** [comment]
@CosminNechifor Sorry! What's the latest master?

**Comment by pciccioni** [comment]
@CosminNechifor : what database do you mean? Raiden DB o Parity DB?

**Comment by CosminNechifor** [comment]
@pciccioni Raiden DB, you can find it inside the ``raiden`` directory
@cmenzani the latest master is the name of the default branch. You can get it by cloning the repository using ( `` git clone https://github.com/raiden-network/raiden `` ) or if you already done that, just pull from it. Anyway "Trying the latest master" means that you would have to create a virtualenv for python, install the dependencies and then start Raiden. You can find more information [here](https://raiden-network.readthedocs.io/en/stable/overview_and_guide.html)

**Comment by czepluch** [comment]
@pciccioni Did this solve the issue for you?

**Comment by pciccioni** [comment]
Hi Jacob, i've do a lot of things from when i've the problem:
- I've installed raiden 6.0
- i've delete .raiden directory 
- After that i was able to see only two tokens (despite parity was synched)
- I've switched to GETH and now i'm waiting to have a synched chain to check  token list yet

**Comment by CosminNechifor** [comment]
@pciccioni Are you still experiencing the same problem?

**Comment by pciccioni** [comment]
Hi, the problem now i resolved. (in meantime we have installed raiden 7.0 ).

Thank You
