### ISSUE TITLE
Raiden node gets stuck and is unable to process payments anymore 

### ISSUE THREAD

**Issue by CosminNechifor** [raiden-network/raiden#2227]
## Problem Definition

When testing the Raiden client with @czepluch we tried sending each other 10 transfers at the same time, after that my Raiden node was stuck. After we both restarted our clients I was able to perform payments again. 

After some time my node is getting into a state where it can no longer do payments with anyone in my list. One more weird thing is that I can mediate payments but not do my own payments. 

After querying the payment_events endpoint we got different outputs: 
@czepluch -> [output](https://gist.github.com/czepluch/f31289b741f972524af270c546479e1d)
My output -> [output](https://gist.github.com/CosminNechifor/ad5d1db887053e4e1c8a18b4b4854dce)

Logs: 
[raiden-debug.log](https://github.com/raiden-network/raiden/files/2311094/raiden-debug.log)
[raiden-debug1.log](https://github.com/raiden-network/raiden/files/2311096/raiden-debug1.log)
[raiden-debug2.log](https://github.com/raiden-network/raiden/files/2311097/raiden-debug2.log)

### System Description
```
Linux cosmin-Lenovo-ideapad-100-15IBD 4.15.0-32-generic #35-Ubuntu SMP Fri Aug 10 17:58:07 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
/usr/bin/solc
solc, the solidity compiler commandline interface
Version: 0.4.24+commit.e67f0147.Linux.g++
/usr/bin/geth
Geth
Version: 1.8.12-stable
Git Commit: 37685930d953bcbe023f9bc65b135a8d8b8f1488
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.10.1
Operating System: linux
GOPATH=
GOROOT=/usr/lib/go-1.10
c18c896c7b070f4ecbbd09597623836f8a606787
```

**Comment by LefterisJP** [comment]
Can you please be adding the debug logs as gists so that they are easy to read?

**Comment by CosminNechifor** [comment]
https://gist.github.com/CosminNechifor/55293f30fb72d1177378810b96540dd8

**Comment by LefterisJP** [comment]
There are 3 logs in the above gist. Can you say which one is doing what? You mentioned it was you and Jacob, so I expect 2 logs.

**Comment by CosminNechifor** [comment]
The 3 logs above are only mine. If I remember correctly @czepluch  gave me a gist with his log, and I think is this one [here](https://gist.github.com/czepluch/95de2dd8ea5ceb19c50b7dff0919c29d).

**Comment by CosminNechifor** [comment]
@LefterisJP I will try to reproduce this. On a clean install with a new account.

**Comment by CosminNechifor** [comment]
Me and @czepluch were able to perform payments in the beginning, because bought of us were using the release version. But after a while I changed the version to the current master of that time. That's when the problem started to happen. We were using the same geth account as before but different versions of the raiden client, which means that we were trying to make payments using the same matrix room. His client was not able to understand my messages, since we don't have forward compatibility, but mine was (and that was why I could still do mediated transfers). 

@LefterisJP I think this issue can be closed.

**Comment by LefterisJP** [comment]
Okay I see. Please keep testing but with the release version and not latest master. Master is accepting breaking changes at the moment.
