### ISSUE TITLE
Remove partner argument from setTotalWithdraw.

### ISSUE THREAD

**Issue by err508** [raiden-network/raiden#2240]
# Problem Definition

The `partner` argument for `setTotalWithdraw` was [removed](https://github.com/raiden-network/raiden-contracts/pull/251), this needs to be done in the client as well.

**Comment by LefterisJP** [comment]
Contract breaking changes are moved to Testnet 7

**Comment by LefterisJP** [comment]
Moved even further to Testnet 8
