### ISSUE TITLE
Add to the webui the ability to view payment history with partner on token network.

### ISSUE THREAD

**Issue by kelsos** [raiden-network/raiden#2252]
The rest API already provides endpoints for the payment history. This should be included on the webui so that the user can see the payment history with a partner on a token network.

**Comment by palango** [comment]
https://raiden-network.readthedocs.io/en/stable/rest_api.html#get--api-1-payments-(token_address)-(target_address) is not bound to a particular channel. So we need to find a proper place for it.

**Comment by kelsos** [comment]
@palango so there is no way currently to filter for a specific channel?

**Comment by palango** [comment]
No, because payments are not bound to channels, only to the token and the target.

**Comment by kelsos** [comment]
Since the wording doesn't make any sense I changed it.
So it would not make sense making the payment history expand out of a specific channel, instead it would be better to open an entirely new page with the payment history for a token network/partner
