### ISSUE TITLE
Include timestamp in internal events

### ISSUE THREAD

**Issue by andrevmatos** [raiden-network/raiden#2287]
## Problem Definition

Right now, the internal raiden events only includes an increasing ID, which is enough for ordering, but not very useful for clients, specially the webUI events views. The ID is also enough for clients which keeps polling for the data, but doesn't help clients processing historical events (for any reason). Blockchain events have the block numbers, which have an associated timestamp, but internal events don't.
We should include the UTC `timestamp` on each event, set on the moment it was processed by the WAL, and expose it in all events APIs. The UI can then use it to show a human-readable time.

PS: this could be done in a non-breaking way, by letting the current data as null, or doing a db upgrade function to interleave the block events, but we can avoid doing that by queuing it for merge on the next breaking change release.

**Comment by LefterisJP** [comment]
Fixed by https://github.com/raiden-network/raiden/pull/2381
