### ISSUE TITLE
Use Enums in the transfers module

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden#2298]
## Problem Definition

We should use enums when building sum types. 
https://github.com/raiden-network/raiden/blob/b883acd1ab28187c3bba04e7161b62fa1b83ca87/raiden/transfer/state.py#L20-L25

https://github.com/raiden-network/raiden/blob/b883acd1ab28187c3bba04e7161b62fa1b83ca87/raiden/transfer/state.py#L47-L49

**Comment by LefterisJP** [comment]
What's a bit annoying is that we already have numeric enums for these in [raiden-contracts](https://github.com/raiden-network/raiden-contracts/blob/a2e3f0fb437818b85ea07f64244302dea219ce6f/raiden_contracts/constants.py#L42) and we use them already in the code.

So we would end up having another enum, a string one this time, for the same thing.

But I guess the states we have in the client are event more as we have the `waiting_` type of states.
