### ISSUE TITLE
raiden asks for address if non-existent address is specified

### ISSUE THREAD

**Issue by schmir** [raiden-network/raiden#230]
When running raiden with the --address parameter and a non-existent address is specified, raiden asks to choose from an address it found on the local machine.

```
(local) ~/raiden (git)-[master] % python -m raiden.app --address no-such-address
The following accounts were found in your machine:


Select one of them by index to continue: : 
```

I think the right thing to do in that case is to log an error message (possibly with printing addresses it found on the local machine) and stop the program.

**Comment by LefterisJP** [comment]
Hmmm I would say that yes an error should be logged/printed to the user, but why not drop back to choosing from the existing accounts?

**Comment by schmir** [comment]
Well, I'm thinking about non-interactive use here, i.e. calling raiden from a script and passing --address option. In that case you most probably don't want to be asked for a address.

Another argument is, that raiden also won't ask you to fix other arguments you pass on the command line.  Why should it do that for the address? What's special about it?

**Comment by adrianbrink** [comment]
I agree with @schmir that it should probably stop raiden as well as log an error, like @LefterisJP suggested. 

@LefterisJP What do you think? If you agree I'll get on implementing this.

**Comment by LefterisJP** [comment]
@adrianbrink Sure Adrian, please go ahead.

**Comment by adrianbrink** [comment]
Could you tag me :-) and assign it ```work_in_progress```.
