### ISSUE TITLE
Nodes are unable to process payments

### ISSUE THREAD

**Issue by CosminNechifor** [raiden-network/raiden#2303]
## Problem Definition

I have tried to send payments between two nodes at the same time. I started the first script which was sending payments from N1 to N2. This seem to work perfectly, then after that I started the script which would send transfers from N2 to N1, so now both nodes were sending and receiving transfers from each other.

It worked for a while, but after some time, the nodes got stuck. 

One more thing I would like to mention is that. After restarting the nodes, they were still stuck. And could not perform payments between them.

Logs: https://gist.github.com/CosminNechifor/c34e0c77e84017f756f150db81a0edde 

I have a video of the entire thing, but I will not put it here, since it contains some private information. If someone really wants to see it, talk with me in private.  

### System Description

```
Linux cosmin-Lenovo-ideapad-100-15IBD 4.15.0-33-generic #36-Ubuntu SMP Wed Aug 15 16:00:05 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
/usr/bin/solc
solc, the solidity compiler commandline interface
Version: 0.4.24+commit.e67f0147.Linux.g++
/usr/bin/geth
Geth
Version: 1.8.12-stable
Git Commit: 37685930d953bcbe023f9bc65b135a8d8b8f1488
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.10.1
Operating System: linux
GOPATH=
GOROOT=/usr/lib/go-1.10
/home/cosmin/.virtualenvs/raiden/bin/raiden
{
  "raiden": "0.6.1.dev11+ged08f720.d20180827",
  "python_implementation": "CPython",
  "python_version": "3.6.5",
  "system": "Linux 64bit_ELF 4.15.0-33-generic x86_64",
  "distribution": "source"
}
b2e2d35d8dde0c10b7359b6eb92be874741f1d64
```

**Comment by LefterisJP** [comment]
So you got 2 logs in the gist. One is called "after restart", and the other is called "most important log". Can you be giving the name of the node for which the log is? So for 2 nodes and 1 restart each I would expect to see 4 logs.

**Comment by CosminNechifor** [comment]
@LefterisJP Those are the logs of only one of the nodes. I am sorry but I don't have the other one's log. And I can no longer provide it. But if you consider it a must have. I will go through the process again.

**Comment by LefterisJP** [comment]
I will close this in favour of the stress test: https://github.com/raiden-network/raiden/pull/2309
