### ISSUE TITLE
Provide the route together with the mediate transfer message

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/raiden#2304]
## Problem Definition

With a naive implementation, each hop in a transfer would be required to request a route from the PFS to find the next hop, adding costs and latency to the transfer.

#### Solution

Add a new message type, which wraps a mediated transfer and provide the recommended route. This route will not be enforced, as it's only additional metadata around the mediate transfer.

**Comment by ulope** [comment]
This is called [source routing](https://en.wikipedia.org/wiki/Source_routing#Internet_Protocol) and has been abandoned in the IP protocol because of security concerns. We need to make sure that we don't introduce vulnerabilities with this.

**Comment by rakanalh** [comment]
For now, we decided that the PFS will request the route at each hop.
