### ISSUE TITLE
Fix and unskip test_mediated_transfer_messages_out_of_order

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#2316]
## Problem Definition

In [this](https://github.com/raiden-network/raiden/pull/2301/files#diff-37fe2abad51b2e528ba8f148669f29eaR127) PR `test_mediated_transfer_messages_out_of_order` was [skipped](https://github.com/raiden-network/raiden/blob/master/raiden/tests/integration/transfer/test_mediatedtransfer.py#L125) because it's failing on Travis.

Find out why that happens, fix the test and unskip it.

**Comment by palango** [comment]
I talked to Andre about this: they are already working on a fix: https://github.com/raiden-network/raiden/pull/2313

**Comment by LefterisJP** [comment]
That's good. Point of making an issue stands.

**Comment by LefterisJP** [comment]
Won't make it this week.

**Comment by LefterisJP** [comment]
Moving this out of scope for Red Eyes.

**Comment by jomuel** [comment]
Closing this issue for now. As mentioned in #2313, the test will not be unskipped and fixed until the planned Matrix optimizations are done, which may fix the problem already.

**Comment by hackaugusto** [comment]
@jomuel in which issue should the progress for this be tracked?

**Comment by LefterisJP** [comment]
I am reopening this issue @jomuel. We **will not** have a skipped test without an issue tracking it. @andrevmatos which planned matrix optimizations are we talking about? Can such stuff be documented here please?
