### ISSUE TITLE
Proposal: Add optional gasprice parameter to on-chain REST-API methods

### ISSUE THREAD

**Issue by ulope** [raiden-network/raiden#2322]
## Problem Definition

It could be useful to (optionally) give the user control over the gasprice used for on-chain actions via the REST-API.

This is especially the case on Ropsten where the gas-price is usually difficult to predict but could also be useful for mainnet and possibly private chains.

**Comment by LefterisJP** [comment]
There [is](https://github.com/raiden-network/raiden/blob/02a554e3c22d7b94f5952c6959b089b2b7667cce/raiden/ui/cli.py#L397) already a cli argument for it which controls the price for all the calls your node would make.

Adding it to the API would allow the user granularity per call I suppose.

**Comment by ulope** [comment]
Also it would allow to react to changing gas price conditions without having to re-start raiden.

**Comment by hackaugusto** [comment]
After #1473 Raiden is using web3's strategies, @ulope is that enough?

**Comment by ulope** [comment]
Seems to be good enough, yes.
