### ISSUE TITLE
Initiator manager must not discard the initiator task when the transfer is cancelled

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/raiden#2329]
## Problem Definition

The function `handle_cancelroute` discard the current initiator task, because the payment cannot be successfully completed:

https://github.com/raiden-network/raiden/blob/32c7c1f2e520626b9bb1ed3bdca84ada736e8e0a/raiden/transfer/mediated_transfer/initiator_manager.py#L137-L140

This, however, will discard the task and make it impossible for the initiator to remove the expire lock. To fix this the tasks must be kept and only be cleaned once the lock has complete successfully or not.

Related: #1091 
## Task

1. Add a list of initiator_transfers to the `InitiatorPaymentState`
2. Subdispatch relevant state changes to all such initiator transfers of an `InitiatorPaymentState`
3. When we need to reveal a secret make sure it happens only for one of these transfers or else we will end up making multiple transfers.

Also since canceling functionality is missing from the code at the moment we need to:
1. Remove `ActionCancelRoute` (it's not used at the moment) and instead add logic in the state machine in order to properly retry a transfer through a different route.
2. Add a configuration for the number of retries
3. Add a configuration for the frequency of retries
4. The first transfer that succeeds will be the one for which the secret will be revealed and all others will be canceled.

**Comment by LefterisJP** [comment]
I am pushing this to the next milestone. There is functionality missing from the state machine that needs to be re-evaluated and that means that the work is much more than initially expected.

**Comment by LefterisJP** [comment]
I am still working on this, but as we discussed in the planning, this is not really a hard requirement for red eyes so I am moving it out of the milestone and into the high priority shortlist. When it's finished, we include it into the next release.
