### ISSUE TITLE
Performance issues on LogListenerTask

### ISSUE THREAD

**Issue by utzig** [raiden-network/raiden#233]
LogListenerTask should be improved to minimize the number of RPC calls done.

Inside Raiden there are 5 ou 6 tasks created using a LogListenerTask, each for a different event (e.g new channel, channel settled, etc). Each of these tasks poll `eth_getFilterChanges` every 0.5s (by default). This amounts to a lot of RPC calls and the events that are polled for happen very sparsely.

An initial suggestion would be to add one single `FilterPollerTask` that polls for all topics that log listeners want to monitor and delivers the events to the appropriate `LogListenerTask`. This should already reduce any number of event pollers to a single RPC call.

Later some form of caching should probably be employed.

**Comment by hackaugusto** [comment]
Closing the issue since the PR #286 removed the LogListenerTask.
