### ISSUE TITLE
Raiden Error: new BigNumber() not a base 16 number

### ISSUE THREAD

**Issue by czepluch** [raiden-network/raiden#2336]
## Problem Definition

With version 0.7.0 of Raiden I get this message when trying to see the wallet view in the web ui.

![2018-09-03-112218_3840x2160_scrot](https://user-images.githubusercontent.com/1026799/44978937-219bfd80-af6c-11e8-9acf-a760edb0b0bc.png)

**Comment by LefterisJP** [comment]
That sounds like a javascript problem. Can you show the console and what errors appear there? @kelsos I think you should pick this up.

**Comment by czepluch** [comment]
Yeah, it looks like a js error. I already shared the issue with Kelsos.

**Comment by kelsos** [comment]
@LefterisJP it is thrown by web3 from a contract that is missing symbol. From what I understand symbol is not required, and neither is name? I will have to fix the handling to not fail in such cases.
