### ISSUE TITLE
Add argument to bypass the experimental disclaimer prompt

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#2340]
## Problem Definition

After https://github.com/raiden-network/raiden/issues/2285 we introduced an acknowledgement of the experimental software disclaimer.

Many people will want to run raiden inside automated scripts or have it managed by an external process. Having a non-bypassable prompt like we do now may make it impossible for them to do it.

## Task

- [ ] Evaluate if adding an argument to bypass the disclaimer is okay
- [ ] If that is fine, add an `--accept-disclaimer` argument which would skip the `[y/N]` prompt.

**Comment by stefante** [comment]
From my point of view an explicit "accept disclaimer" is sufficient. 
@christianbrb would suggest to also include this in the document for Jim to review.
