### ISSUE TITLE
Raiden crashes on restart

### ISSUE THREAD

**Issue by czepluch** [raiden-network/raiden#2351]
## Problem Definition

On latest master Raiden crashes with the error in the gist after restarting. 

https://gist.github.com/czepluch/5fd608d9313b7b7eee666fd8d66a04f8

Note: I tried starting Raiden again after this error occurred, and every thing seems to work fine.

**Comment by andrevmatos** [comment]
@czepluch do you have the logs from before the traceback? If that message handling is in response to a message sent by your node (maybe queued from a previous session), that shouldn't trigger an assertion, and in any case, we need to replace this assertion with a noop, as that could be a message crafted to crash the node

**Comment by LefterisJP** [comment]
@czepluch can you try latest master now and tell me if this is stil an issue for you?

**Comment by czepluch** [comment]
Yes. I am just waiting for a channel to settle before I update to latest master.

**Comment by czepluch** [comment]
This seems to have been fixed. Haven't experienced it more than that one time.
