### ISSUE TITLE
Raiden DB doesn't takes into account contracts address, and gets messed up on new deploys

### ISSUE THREAD

**Issue by andrevmatos** [raiden-network/raiden#2356]
## Problem Definition

After latest contracts deployment and merge of changes on `master`, nodes which didn't `removedb` get lost because it can't find onchain the channels it had registered, nor detect/react on new ones, as it doesn't know about the new contracts.

It's caused by the db name having only the `chain_id` and `version` on it. It should also include the `token_network_registry` address, to reset on new deployments.

### System Description

Current master 7fff72a57ee411af55d2234132d9370102c3f6fd

**Comment by LefterisJP** [comment]
Yep we noticed. @hackaugusto is fixing it right now

**Comment by andrevmatos** [comment]
Fixed by #2359
