### ISSUE TITLE
Nodes crash when trying to join a token network 

### ISSUE THREAD

**Issue by CosminNechifor** [raiden-network/raiden#2361]
## Problem Definition

This happened when I tried to join a token network with both my nodes. It resulted in both of them crashing. 

Log: https://gist.github.com/CosminNechifor/44f96fa89ef61c8442366c117c8d9076

commit: 9267352071da1e1892efaf62f88d26ca8c1fe851

**Comment by LefterisJP** [comment]
@CosminNechifor can you try again with latest master and if this does not occur, close the issue?

**Comment by CosminNechifor** [comment]
I could not reproduce this.
