### ISSUE TITLE
Speedup --blockchain-type=geth tests in the CI

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#237]
The `--blockchain-type=geth` matrix build in Travis takes too much time to complete. It is [temporarily disabled](https://github.com/raiden-network/raiden/blob/061cbac24f95abc8f19bd1a1d86e5435a59e1a83/.travis.yml#L22) until a solution is found.

Speed comparison justifying disabling:

![2016-11-08-112658_885x248_scrot](https://cloud.githubusercontent.com/assets/1658405/20097336/294605cc-a5ae-11e6-8945-0630d90087da.png)

**Comment by hackaugusto** [comment]
#246

**Comment by hackaugusto** [comment]
PR #246 was merged, closing this
