### ISSUE TITLE
Profile Matrix performance

### ISSUE THREAD

**Issue by ulope** [raiden-network/raiden#2385]
## Problem Definition

We've had multiple reports that mediated transfers using the Matrix transport are slow.
Investigate why this is the case.

**Comment by BCsRock** [comment]
My findings are that from version 0.4.0, where Matrix was introduced, the time to send a simple payment from client 1 to client 2 (direct payment channel) has increased from roughly 1 second to 7 seconds :-/

please see my measurement results:

Results from August using v.0-4-0 or v.0-4-1

![image](https://user-images.githubusercontent.com/40204055/45555004-eb962d80-b837-11e8-97cc-b2fa1bade1b7.png)

Results from yesterday using v.0-8-0

![image](https://user-images.githubusercontent.com/40204055/45554943-c5708d80-b837-11e8-8286-cc1ba530de88.png)

**Comment by hackaugusto** [comment]
@BCsRock thanks for the report :)

Could you give a bit more detail regarding the location of the clients? I assume you are using Azure, but which zone is it?

**Comment by BCsRock** [comment]
Actually I tried a mixed setup, with clients only on Cloud (Azure) and Clients only running from within our office in Cologne, Germany, and mixed scenarios Cloud-Office. The performance is the same, in the order of 6-7 seconds :-( 

For Cloud azure: I can only see `West Europe` as Server location.

Apart from ping, what info could be interesting to monitor?

How about:
- size of messages - could this be reduced to a bare minimum?
- number of messages - In the Raiden Client I can observe the ping-pong of shared and revealed secrets. Maybe some step can avoided or integrated in another one?
- Is there a way to breakdown and measure the time for each of the steps: 
From Raiden Client 1 to Matrix -> from Matrix to Matrix -> from Matrix to Raiden Client 2 and back?
(To better idenditfy a bottle neck)

**Comment by BCsRock** [comment]
Wow, using v-0.9.0 it was back to almost initial performance.

Any idea what could have caused this optimization?

![image](https://user-images.githubusercontent.com/40204055/45617457-b295cd00-ba72-11e8-947b-18c1b7c8df5d.png)

Next I consider to measure performance when hopping over 4 nodes.

**Comment by ulope** [comment]
@BCsRock There was some misconfiguration on our testing matrix servers that will probably have caused excessive rate limiting. 

But independent of that we'll be looking into improving performance in the future.

**Comment by Dominik1999** [comment]
@Dominik1999 asks @ulope whats about that issue

**Comment by ulope** [comment]
Closing this. We have improved general Raiden performance a lot in the past months. 

Tracking transfer performance will be done with #5956 and Matrix specifically will improve a lot once we get to implement WebRTC.
