### ISSUE TITLE
Merge Registry and Endpoint Discovery

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/raiden#239]
Currently the asset [Registry](https://github.com/raiden-network/raiden/blob/master/raiden/smart_contracts/Registry.sol) and [EndpointRegistry](https://github.com/raiden-network/raiden/blob/master/raiden/smart_contracts/EndpointRegistry.sol) are two separate contracts.

It doesnt make much sense to have a Registry without endpoint discovery, nor multiple Endpoint contracts for a single registry, so merging these into a single contract makes sense.

**Comment by konradkonrad** [comment]
I disagree: the EndpointRegistry in my view is a temporary workaround for the physical discovery issue of network locations -- the asset Registry on the other hand provides protocol specific information, that would even hold value after we apply a different solution to the physical network complex.

**Comment by hackaugusto** [comment]
Okay, so we should move to a p2p endpoint discoverability instead of merging the smart contracts. Agreed.

If noone has anything to add until the end of the week I will close the issue as invalid

**Comment by konradkonrad** [comment]
invalid
