### ISSUE TITLE
Disable token registration for the Red Eyes mainnet release

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#2393]
## Intro

As per our requirements for the Red Eyes release we need to disable token registration.

## Tasks

- [ ] Gray out all token registration functionality in the WebUI.
- [ ] The `register_token` API endpoint should always return a "Not implemented" error

## Notes

This should only be merged in master for the red eyes mainnet release.

**Comment by kelsos** [comment]
I had a discussion with @andrevmatos in regards to this, and he suggested to introduce the concept of mainnet in the configuration that is generated on raiden: https://github.com/raiden-network/raiden/blob/2d2c5cbb082f42d171f3305c2ea6f1a284de3a49/raiden/api/rest.py#L389-L395 And then is passed to the webui. 

This way the webui doesn't need to know about anything during compile and it will be able to dynamically adjust to the configuration provided by raiden.

**Comment by LefterisJP** [comment]
Information on whether we are on a main or test network mode is currently passed to the webui [here](https://github.com/raiden-network/raiden/pull/2530/files#diff-8a975e5d87b5ba8673403e4786aae22dR399) and will be in master soon as #2530 is merged.

**Comment by LefterisJP** [comment]
Part of this was done by https://github.com/raiden-network/raiden/pull/2530
UI part soon by #2541

**Comment by LefterisJP** [comment]
Should be done.
