### ISSUE TITLE
Setting --rpccorsdomain "http://localhost:5001" does not work

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#2396]
## Problem Definition

In the documentation we state that setting `--rpccorsdomain "http://localhost:5001"` as an argument to the ethereum client (parity or geth) should work and allow the WebUI to work.

In the ETHBerlin Hackathon we noticed that both for parity and for geth this does not work. The only option that works is `--rpccorsdomain "*"`

## Task

- [x] Investigate why this is happening
- [x] Either fix it so that the original suggestion works, or edit the documentation.

**Comment by err508** [comment]
This can be fixed `--rpccorsdomain "http://127:0.0.1:5001`. This is the default domain the Raiden API RPC server will run on and therefore needs to be authorized make cors requests. Another option is to set raidens `--api-address` to `localhost:5001`, i.e. this cors authorization has to be consistent.
