### ISSUE TITLE
debug API endpoint doesn't work anymore

### ISSUE THREAD

**Issue by eorituz** [raiden-network/raiden#2421]
## Problem Definition

I tried to querry `/api/(version)/_debug/raiden_events/tokens/(token_address)` and got an invalid API endpoint response.
Is it supposed to be like that? If so --> remove the endpoint from the docu

### System Description
Used the latest *.tar [binary release](https://github.com/raiden-network/raiden/releases/download/v0.8.0/raiden-v0.8.0-linux.tar.gz)(v0.8.0) 
Python3.6, Ubuntu 18.04

**Comment by LefterisJP** [comment]
All the debugging endpoints are temporary and may be changed without any notice. They are only there for easier debugging of the client. That said, the docs had it wrong. The endpoint is just `/api/(version)/_debug/raiden_events/`.

To see all the endpoints look here: https://github.com/raiden-network/raiden/blob/6659160eda5010d0ef4ab6ebb7294cb4558f1285/raiden/api/rest.py#L99
