### ISSUE TITLE
Fix automatic homebrew formula updating

### ISSUE THREAD

**Issue by ulope** [raiden-network/raiden#2426]
## Problem Definition

Follow up to #1893: The automatic homebrew formula update hangs because of an SSH known hosts prompt.

Travis run: https://travis-ci.org/raiden-network/raiden/jobs/425900673

**Comment by LefterisJP** [comment]
The last nightly passed successfully: https://travis-ci.org/raiden-network/raiden/jobs/428003030

Is that considered fixed then?

**Comment by ulope** [comment]
The nightlies don't update homebrew. The linked PR should fix it though.

**Comment by LefterisJP** [comment]
"Should fix it". -- Famous last words.

I think we still have this problem. The v0.9.0 release failed to update homebrew: https://travis-ci.org/raiden-network/raiden/jobs/428788532

**Comment by ulope** [comment]
This is turning into a groundhog day issue...

Latest failure: https://travis-ci.org/raiden-network/raiden/jobs/434678475

**Comment by LefterisJP** [comment]
Nope. It's still winter.

Here is the log of the latest failure: https://travis-ci.org/raiden-network/raiden/jobs/437840496#L1973

And a screenshot in case the travis log dissapears or gets trimmed.
![2018-10-06-010030_919x526_scrot](https://user-images.githubusercontent.com/1658405/46563828-f8241800-c903-11e8-8b59-b5d1f3166384.png)
