### ISSUE TITLE
Missing field crashes the node

### ISSUE THREAD

**Issue by CosminNechifor** [raiden-network/raiden#2427]
## Problem Definition

As you can see in the following stacktrace [ContractReceiveChannelBatchUnlock](https://github.com/raiden-network/raiden/blob/master/raiden/transfer/state_change.py#L759) does not have a transaction_from field, and also it does not [inherit](https://github.com/raiden-network/raiden/blob/master/raiden/transfer/architecture.py#L151) it from anywhere. which will cause the node to crash with an [AttributeError](https://github.com/raiden-network/raiden/blob/master/raiden/transfer/node.py#L998).

```
File "/home/cosmin/Documents/WORK/GITHUB/raiden/raiden/transfer/node.py", line 1088, in is_transaction_pending
    is_transaction_effect_satisfied(chain_state, transaction, state_change) or
  File "/home/cosmin/Documents/WORK/GITHUB/raiden/raiden/transfer/node.py", line 998, in is_transaction_effect_satisfied
    state_change.transaction_from == our_address and
AttributeError: 'ContractReceiveChannelBatchUnlock' object has no attribute 'transaction_from'
```
Full log: https://gist.github.com/CosminNechifor/06c04687b31dc4776a4cdceb21cda693

**Comment by LefterisJP** [comment]
I will look into this Cosmin. Thank you.
