### ISSUE TITLE
Use a proper gas value per transaction

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/raiden#244]
## Problem Definition

The contract proxies are using the [Morden gaslimit](https://github.com/raiden-network/raiden/blob/d79e8c32b7c26f4fd57ca3b6efa8686815b5c5a4/raiden/network/rpc/client.py#L34) for each transaction, this should be replaced by an [estimated gas](https://github.com/ethereum/wiki/wiki/JavaScript-API#web3ethestimategas).

### Why it happened

The current JSON-RPC implementation used by raiden is from `pyethapp.rpc_client`, this implementation uses [`eth_gaslimit`](https://github.com/ethereum/pyethapp/blob/afc8f66b8e47d6b21ea780e754c300a52b32411d/pyethapp/rpc_client.py#L412-L413) if the user does not specify the transaction gas, [`eth_gaslimit`](https://github.com/ethereum/pyethapp/blob/develop/pyethapp/jsonrpc.py#L1008-L1011) is a pyethapp extension that returns the latest block gas_limit, this can result in transactions failling because of improper gas setting.

As a workaround the Morden gaslimit was used.

## Solution

Use `eth_estimateGas`

## Tasklist

- [ ] Replace all occurrences of `startgas` in the `network.rpc.client` module with the estimated gas from the proxy `MethodProxy.estimate_gas`, e.g.:

From:
```python
        transaction_hash = self.proxy.approve.transact(
            contract_address,
            allowance,
            startgas=self.startgas,
            gasprice=self.gasprice,
        )
```
To:
```python
        estimated_gas = self.proxy.approve.estimate_gas(
            contract_address,
            allowance,
            startgas=estimated_gas,
            gasprice=self.gasprice,
        )
        transaction_hash = self.proxy.approve.transact(
            contract_address,
            allowance,
            startgas=estimated_gas,
            gasprice=self.gasprice,
        )
```

**Comment by LefterisJP** [comment]
Should be handled by: https://github.com/raiden-network/raiden/pull/481
