### ISSUE TITLE
Receiver doesn't see EventPaymentReceivedSuccess

### ISSUE THREAD

**Issue by eorituz** [raiden-network/raiden#2461]
## Problem Definition

When sending a sucessfull Tx between two locally running nodes (I ran the nodes in debug mode and saw the EventPaymentSentSuccess in the senders and the receivers Raiden client) the receiver doesn't store the event correctly.

Meaning that querying the payment history between S and R after the Tx:
The S response will be the expected EventPaymentSentSuccess. 
While the R node does return an empty list.

### System Description
Ubuntu 18.04, python3.6, Raiden version 0.8.1.dev78+g9373c616 (latest master on Tuesday 13.09)

**Comment by LefterisJP** [comment]
Can you go into a bit more details about what you are doing?

- What are the exact API endpoints that each node queries and with what parameters
- What is the response?
- What is your expected response
- Attach logs if possible

**Comment by eorituz** [comment]
Sure:

## Raiden Client Log files:
[Sender](https://gist.github.com/eorituz/80e5ff7ed35721d0885338f9bd21eade) (on Port 5009)
[Receiver](https://gist.github.com/eorituz/ec8b120840ddc327ff2226816a01f5f5) (on Port 5001)

Sender_address = `0x00F3fF781d1eCf923aFa54611CE6C3c9E679D1E3`
Receiver_address = `0x002857f3a3BEa9DC0301D6DCf573692720f88B5a`

## The Payment was initialized by the API call:
`echo '{                                                                                "amount": 1,                            
  "identifier": 2
}' | http POST http://localhost:5009/api/1/payments/0x0f114A1E9Db192502E7856309cc899952b3db1ED/0x002857f3a3BEa9DC0301D6DCf573692720f88B5a Content-Type:application/json
`
Using Httpie.

## The Response was
```
HTTP/1.1 200 OK
Content-Length: 224
Content-Type: application/json
Date: Thu, 13 Sep 2018 11:52:39 GMT
mimetype: application/json

{
    "amount": 1,
    "identifier": 2,
    "initiator_address": "0x00F3fF781d1eCf923aFa54611CE6C3c9E679D1E3",
    "target_address": "0x002857f3a3BEa9DC0301D6DCf573692720f88B5a",
    "token_address": "0x0f114A1E9Db192502E7856309cc899952b3db1ED"
}

```
## Payment API requests
## Receivers payment history request:
```
http http://localhost:5001/api/1/payments/0x0f114A1E9Db192502E7856309cc899952b3db1ED/0x00F3fF781d1eCf923aFa54611CE6C3c9E679D1E3
```
Response:
```
HTTP/1.1 200 OK
Content-Length: 2
Content-Type: application/json
Date: Thu, 13 Sep 2018 13:30:18 GMT
mimetype: application/json

[]

```

## Senders payment history request
```
http http://localhost:5009/api/1/payments/0x0f114A1E9Db192502E7856309cc899952b3db1ED/0x002857f3a3BEa9DC0301D6DCf573692720f88B5a
```
Response:
```
HTTP/1.1 200 OK
Content-Length: 124
Content-Type: application/json
Date: Thu, 13 Sep 2018 13:30:30 GMT
mimetype: application/json

[
    {
        "amount": 1,
        "event": "EventPaymentSentSuccess",
        "identifier": 2,
        "target": "0x002857f3a3BEa9DC0301D6DCf573692720f88B5a"
    }
]

```

**Comment by czepluch** [comment]
I can verify that this is a problem. I thought we fixed it with https://github.com/raiden-network/raiden/pull/2382/files

**Comment by czepluch** [comment]
And it's very weird that the `EventPaymentReceivedSuccessful` doesn't show, since we have a test for it (https://github.com/raiden-network/raiden/pull/2395/files)

**Comment by czepluch** [comment]
Related to https://github.com/raiden-network/raiden/issues/2373 that should have been fixed already

**Comment by LefterisJP** [comment]
I will have a look further then if you also think it's still a problem @czepluch

**Comment by czepluch** [comment]
@LefterisJP Yes, I can confirm that it's still a problem. I just now tried with latest master again and it is indeed a problem.

**Comment by LefterisJP** [comment]
Ah damn I think I see the problem.
