### ISSUE TITLE
Payment Identifier gets overwritten

### ISSUE THREAD

**Issue by eorituz** [raiden-network/raiden#2462]
## Problem Definition

When doing a Tx between to locally running nodes with a defined identifier
`echo '{                                                                                "amount": 1,
  "identifer": 2
}' | http POST http://localhost:5009/api/1/payments/0x0f114A1E9Db192502E7856309cc899952b3db1ED/0x002857f3a3BEa9DC0301D6DCf573692720f88B5a Content-Type:application/json`

The identifier gets overwritten by the senders raiden client,  because return of the Raiden client is:

```
HTTP/1.1 200 OK
Content-Length: 242
Content-Type: application/json
Date: Thu, 13 Sep 2018 10:41:40 GMT
mimetype: application/json

{
    "amount": 1,
    "identifier": 7085303223089080205,
    "initiator_address": "0x00F3fF781d1eCf923aFa54611CE6C3c9E679D1E3",
    "target_address": "0x002857f3a3BEa9DC0301D6DCf573692720f88B5a",
    "token_address": "0x0f114A1E9Db192502E7856309cc899952b3db1ED"
}
```

### System Description

Ubuntu 18.04, python3.6, Raiden version 0.8.1.dev78+g9373c616 (latest master on Tuesday 13.09)

**Comment by LefterisJP** [comment]
Hey oliver. Thanks for the report. Will look into this. Can you also post the debug logs?

**Comment by czepluch** [comment]
Works for me with manually specifying an identifier on latest master.

**Comment by czepluch** [comment]
In your example above, you spell "identifier" wrong @eorituz . This is probably why

**Comment by LefterisJP** [comment]
yes that's definitely why. And extra arguments are ignored.

**Comment by eorituz** [comment]
... You're right that solved it.
Is there any particular reason why additional arguments are ignored?
Maybe we could catch the case of an illiterate human :D
