### ISSUE TITLE
Inconsistent view of the payment network

### ISSUE THREAD

**Issue by CosminNechifor** [raiden-network/raiden#2466]
## Problem Definition

At this moment in time, we have the functionality of the cooperative settle implemented in the [TokenNetwork](https://github.com/raiden-network/raiden-contracts/blob/master/raiden_contracts/contracts/TokenNetwork.sol#L830-L911) smart contract, and if two users decide to call it manually they will make the other users view of the payment network inconsistent. For example if we have the following payment network: 

```
A <-> B <-> C <-> D <-> E
```

And if for some reason C and D decide to remove their channel by calling ``cooperativeSettle`` . The nodes ``A`` , ``B``, ``E`` will have an inconsistent view of the payment network, since the part of the code that removes a channel from their representation of the payment network is only triggered by a ``ChannelClosed`` event.

**Comment by palango** [comment]
Closing this for #2467
