### ISSUE TITLE
Address Healthcheck Synchronization

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#247]
## Problem Definition

The health check task and the greenlet responsible for a node message queue are not synchronized.

## Solution

Instead of using a Health Check task for all nodes, we could add the ping logic in the `_send_queued_message`.

Example pseudo-code:

```
Send ping to check if partner is online:
    - if ping unconfirmed
        - node is unavailable
        - wait for partner to come online (if any message is received from partner)
loop:
    - message := queue.peek with time-out after send-ping-time
    - if message is None
        - message := Ping
        - wait for confirmation or max_unresponsive_time
        - if message unconfirmed
            - node is unavailable
            - wait for partner to come back online
    - while queue not empty
        - message := queue.pop, retries_left := max_retries
        - while message unconfirmed
            - send message
            - retries_left := retries_left -1
            - wait for confirmation or timeout
            - if retries_left == 0 node is unavailable # the message worked as the Ping
                - wait for partner to come back online
                - retries_left := max_retries
```

This would make one task per channel, eliminate synchronizations issues for messages that have max_retries, and we can start these queues in a randomization loop as suggested by @konradkonrad

**Comment by hackaugusto** [comment]
Implemented by https://github.com/raiden-network/raiden/pull/615

The algorithm in the issue body didn't work that well because a node may have multiple channels, so instead of merging the health check with the channel task a new health check that exposed healthy/unhealthy events was added, the queue tasks will hold stop when the node is not healthy and wait until it is back alive.
