### ISSUE TITLE
Introduce concept of 'test' and 'main' Ethereum networks

### ISSUE THREAD

**Issue by ulope** [raiden-network/raiden#2470]
## Abstract

We keep a list of well-known Ethereum networks, their IDs and the deployed contract addresses in the Raiden client. 
We should add a flag to each network that indicates whether the network is a 'test' or 'main' one.

## Motivation

This came out of our discussion about security issues.

We need this flag to be able to en-/disable certain features that are desirable for debugging but have an impact on security or performance.
Those features currently are:
- [Matrix] `is_public` flag on Rooms
- [Matrix] e2e encryption  (only after red eyes)
- [WebUI / Core] Allow registering new tokens
- [WebUI / Core] Deposit / channel limits

## Specification

Tasks:
- [x] Add a `type` parameter (values `test` and `main`)  (suggestions for better names welcome) to the list of well-known Ethereum networks 
- [x] Add a CLI option `--network-type` to allow unknown networks to be marked as test networks. **This option _must not_ be able to override a network marked as `main` in the well-known list with `test`.** The other way around (i.e. setting a `test` network to `main`) is fine and useful for testing. 
- [x] Switch the features described under [Motivation](#motivation) depending on the value (only those that are currently implemented
- [x] Switch the Unrecoverable Errors to logging instead of crashing the node if we are on the mainnet
- [x] Add changelog entry

**Comment by LefterisJP** [comment]
We should also conditionally add these to the features enabled on testnets:

- Testnet Faucet: https://github.com/raiden-network/raiden/issues/2465
- Testnet Token minting: https://github.com/raiden-network/raiden/issues/2471
