### ISSUE TITLE
Get rid of Delivered messages in matrix

### ISSUE THREAD

**Issue by andrevmatos** [raiden-network/raiden#2505]
## Proposal

`Delivered` messages were inherited from the UDP transport because it doesn't have persistency. Matrix transport does, so we should get rid of these messages, and rely on the rooms persistency and assume the messages were delivered once the HTTP request for putting the message event succeeds.
This is trivial for most messages.
The only exception is `SecretRequest`, which currently get cleaned on `Delivered`, but should only upon receiving the respective `SecretReveal` (or a `Processed`).
This will get rid of ~50% of the currently exchanged messages between peers, and could significantly improve matrix communication times without losing any feature, security or guarantee.
Related: #2502

**Comment by andrevmatos** [comment]
Complementing: this doesn't mean getting rid of `ReceiveDelivered` events. For the state machine/core/outside matrix transport, nothing changes. But internally, instead of waiting for a couple of roundtrips + unnecessary data transfer to get a partner's `Delivered` message to emit this event, as the message which is expecting it is sent only if the user is online and Matrix is reliable, once the message was delivered to the server the partner will get it anyway, so we can assume it was delivered and emit the event. If something went wrong with fetching/processing the message on the receiver is another issue (but there's ways to get rid of the `Processed` messages too, we may look into it in the future).

**Comment by andrevmatos** [comment]
Related: #2383

**Comment by ulope** [comment]
Superseeded by: #3254

**Comment by hackaugusto** [comment]
@ulope shouldn't this be closed because of the same reason as https://github.com/raiden-network/raiden/issues/2383#issuecomment-454736011? (and also, this is superseded)

**Comment by ulope** [comment]
We agreed to keep it open until there is a decision on #3254

**Comment by hackaugusto** [comment]
It was decided to remove the delivered altogether, it is not a useful optimization. [ref](https://github.com/raiden-network/raiden/issues/3254#issuecomment-502704167)

This issue is superseded by #3254
