### ISSUE TITLE
Invert webui event ordering default to descending by block

### ISSUE THREAD

**Issue by err508** [raiden-network/raiden#2512]
## Problem Definition

The webui currently displays events arranged in ascending order by default, where the user is usually more interested in the most current events for a given token/channel.

**Comment by andrevmatos** [comment]
I think we should instead change the order in which the API returns events and stop [reversing](https://github.com/raiden-network/raiden/blob/master/raiden/api/python.py#L753) [them](https://github.com/raiden-network/raiden/blob/master/raiden/api/python.py#L788) [there](https://github.com/raiden-network/raiden/blob/master/raiden/api/python.py#L822). AFAIR, that was done to return most recent events first, thinking in a streaming context, but we don't support streams (every request returns all results at once), so I think it makes more sense to return the ordered data there.

**Comment by err508** [comment]
I'd leave the API response order as it is, as ascending by block is the design primitive we use for a channel life cycle (i.e. total deposit is ascending by block). This makes  API response verification generic and if a user is only interested in the most current event and skips verification (like in the UI), this requires an explicit step.

**Comment by kelsos** [comment]
It shouldn't be hard to put a descending by block order as the default option.
