### ISSUE TITLE
Remove reveal_timeout can not be larger or equal to settlement_timout message 

### ISSUE THREAD

**Issue by err508** [raiden-network/raiden#2515]
## Problem Definition

When opening a channel a user is given the option to choose the settle timeout. The UI denotes:  `The smallest allowed value is 1` and displays `reveal_timeout can not be larger or equal to settlement_timeout` if a to small settlement timeout is chosen. 
I'd suggest to remove the error message here and display the minimum `Settle Timeout` as constrained by the `reveal_timeout`  in the channel opening view.

**Comment by kelsos** [comment]
@err508  `the smallest allowed value is 1` is the hint message displayed on the field above, which is the balance field. Each error message appears on the bottom of an input field and has a red colored text.

**Comment by err508** [comment]
@kelsos The Settle Timeout must also be larger than the `reveal_timeout` of a particular token as required [here](https://github.com/raiden-network/raiden-contracts/blob/master/raiden_contracts/contracts/TokenNetwork.sol#L236). This token specific information is available already in the client.

**Comment by kelsos** [comment]
@err508 Thanks, I will add an extra validation to the field.

**Comment by kelsos** [comment]
@err508 I am having trouble finding where `reveal_timeout` is actually exposed in the REST api.
The `/tokens` returns an array of token contract addresses. Any meaningful information (balance, name etc) is then queried directly from the ERC20 token via web3.js. The `/connections` api doesn't seem to contain any information about `reveal_timeout` either. 

The message `reveal_timeout can not be larger or equal to settlement_timeout` seems to originate from the REST api.

The only place I could find `reveal_timeout` information was in the list of channels.

**Comment by andrevmatos** [comment]
@kelsos `reveal_timeout` is channel-specific, not token-specific (afaict), and [comes in channels endpoints](https://github.com/raiden-network/raiden/blob/master/docs/rest_api.rst#channel-object)

**Comment by err508** [comment]
If the reveal timeout is tweakable, we only have a lower bound for the `settle_timeout` input given by the token's `Settle_Timeout` no? As of [here](https://github.com/raiden-network/raiden/issues/2225) the initiator of a mediated transfer chooses the `reveal_timeout` and the client only has to check that it is smaller than the `Settle timeout` for its mediating channel. 
We could display some hand wavy explanation at this point, that a larger `settlement timeout` is correlated to a higher degree of security (in case of offline time) and a larger amount of mediated transfers/mediation fees, but in turn the tokens are locked for a prolonged time if the user might want to move them away from a channel.

**Comment by andrevmatos** [comment]
Yes, `reveal_timeout` is a lower bound to `settle_timeout`, and both are tweakables, although not exposed in the webUI nor the docs. I'm working on a PR to expose the default values in `config.json`, and the webui will be able to use this lower bounday.

**Comment by andrevmatos** [comment]
Ok, there's a problem. The `reveal_timeout` is actually exposed through the API (both rest and python) but isn't taken into account when opening the channel (#2529). I did PR #2531 to expose the values of these variables through webUI's `config.json`.
@kelsos , please, make a follow up PR over it to use these values throughout the webui:
- Default `settle_timeout` in the open dialog populated from the config
- Minimum `settle_timeout` value is `reveal_timeout * 2`
https://github.com/raiden-network/raiden/blob/d989738e5f8840748cdd8a02aafa6df4a4ab1409/raiden/app.py#L94
