### ISSUE TITLE
Display UI messages longer 

### ISSUE THREAD

**Issue by err508** [raiden-network/raiden#2517]
## Problem Definition

When an error is displayed in the UI it is not possible to cp + pst. the message atm because it disappears to fast. IMO UI messages (at least errors and warnings) should only disappear if acknowledged.

**Comment by kelsos** [comment]
@err508 The default timeout of the notifications is currently 3 seconds, would 10 seconds make sense?

**Comment by err508** [comment]
10 secs seems imo a little long for a confirmation. I had an Issue copying an error messages, so I'd make them acknowledgeable - same for warnings.

**Comment by andrevmatos** [comment]
Not sure if it's easy, but I think it'd be nice e.g. 5s messages, which stays open while you hover over it

**Comment by kelsos** [comment]
Ok I will check if this can be done somehow, using the existing notification library api.
