### ISSUE TITLE
Take the block number in which secret was registered on chain into consideration

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#2535]
Follow up issue after merging https://github.com/raiden-network/raiden/pull/2441.

We should make sure that [register_onchain_secret](https://github.com/raiden-network/raiden/blob/a680108b777c19fa8d9fa3379d5cfc32d7db99a1/raiden/transfer/channel.py#L1509) takes the block number at which the secret was registered into account.

**Comment by rakanalh** [comment]
The idea is mostly about this function:
https://github.com/raiden-network/raiden/blob/a680108b777c19fa8d9fa3379d5cfc32d7db99a1/raiden/transfer/channel.py#L1465-L1489

If pending_lock has already expired by the time we're handing on-chain secret registration. 

The execution path reaches to this point if the secret was already learned on-chain or by receiving a secret reveal message from the initiator. If we find that the pending lock has expired before the secret was registered.
- What is the course of action in this case? 
- Should the pending lock be deleted without registering it to `secrethashes_to_unlockedlocks`?

**Comment by hackaugusto** [comment]
> What is the course of action in this case?

The lock has expired and it should go through the remove expired lock code path.

> Should the pending lock be deleted without registering it to secrethashes_to_onchain_unlockedlocks?

No. Otherwise the channels will be out-of-synch and `RemoveExpiredLock` won't work
