### ISSUE TITLE
Locations in the code to change when going back to non-limited contracts

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#2556]
## Introduction

This is a list of locations that need to be changed for the raiden client to be compatible with the non-limit contracts again.

## Locations

- Remove the extra argument for the deprecator from raiden/tests/integration/contracts/fixtures/contracts.py:82
- Uncomment the tests involving `withdraw()` raiden/tests/integration/contracts/test_token_network.py
- Change the default network_type back to test in raiden/tests/fixtures/variables.py:320
- Revert where needed the `number_of_tokens` variable to anything other than 1 and uncomment code that was testing behaviour for multiple tokens in raiden/tests/integration/api/test_restapi.py
- Unskip two integration tests that use multiple tokens in raiden/tests/integration/test_pythonapi.py

## Commits

This is the list of commits that introduced the changes to make raiden comply with the red eyes limits contracts. To make raiden compatible with non-limited contracts they should be selectively (may need to investigate which parts should stay as is) reverted in the develop branch.

- https://github.com/raiden-network/raiden/commit/ad286b7c5bdbe15f91edfc1e2b97ad6d13e5a5f0 Check contract's channel limit before deposit if on mainnet
- https://github.com/raiden-network/raiden/commit/b93add4fe6b152c8b6490b8e0f51b49ba3acde95 Specify address for deprecator in `token_network_proxy` fixture
- https://github.com/raiden-network/raiden/commit/c40bfafbb8cfd00c39b947fc363f5d737e43bfb5 comment out withdraw checks in the tests
- https://github.com/raiden-network/raiden/commit/35eebf5c8a5ef08ef98db2ff1f0307472c169a17 Adjustment to the rest api tests to work with a single token, limited deposits and without registrations
- https://github.com/raiden-network/raiden/commit/a7c08b30876d1db045aff7da23bf9dc1048afa35 Adjustment to the integration tests to work with only a single token

**Comment by pirapira** [comment]
Now, if somebody wants an unlimited version, they can deploy the contracts with `UINT256_MAX` as the limit.  No code is supposed to change for that special case.
