### ISSUE TITLE
rtt_token.mint not working

### ISSUE THREAD

**Issue by alemhnan** [raiden-network/raiden#2557]
Hello,

I'm trying to mint some rtt token. I successfully invoke the method from my local geth account, as stated [here](rtt_token.mint). I see the transactions (e.g. [here](https://ropsten.etherscan.io/tx/0x8c9da7b06a38f79fba3b687d9081e5d6b45b2827d11dadb17bef65245ca41155) in etherscan but I do not get any token back in my account.

Is still working the rtt token?

**Comment by ulope** [comment]
Hi @alemhnan,

Etherscan doesn't know about all tokens esp. on Ropsten.

To check whether you own any RTT tokens you can check the contract's `balanceOf` function. Easiest way to do that is via Etherscan's [`Read Contract` function on the RTT contract](https://ropsten.etherscan.io/address/0x0f114a1e9db192502e7856309cc899952b3db1ed#readContract)].

Hope this helps :)

**Comment by alemhnan** [comment]
Got that. 

I was thrown off by another mistake. I do indeed have tokens.
The actual problem was that I was mistakenly launching raiden with a different account that the one that I was minting.

Thanks for the help!
