### ISSUE TITLE
Uncrecoverable error

### ISSUE THREAD

**Issue by err508** [raiden-network/raiden#2572]
## Problem Definition

Three nodes` (A->B->C)` running for scenario player; After closing some channels which were opened for scenarios, all nodes crashed and are now unrestartable
 [ log A](https://gist.github.com/err508/7de7526060bd8ae9a0dc36e6b228fa9e)
 [ log B](https://gist.github.com/err508/73f516f872622e2b29709a9e74003dc0)
 [ log C](https://gist.github.com/err508/f4dc24fd5e4825fa45706408e62ec91a)

### System Description

Here add a detailed description of your system, e.g. output of the following script:

```
uname -a
Linux box 4.15.0-34-generic #37~16.04.1-Ubuntu SMP Tue Aug 28 10:44:06 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

-v solc && solc --version
/usr/bin/solc
solc, the solidity compiler commandline interface
Version: 0.4.23+commit.124ca40d.Linux.g++

-v geth && geth version

... using infura endpoint

-v raiden && raiden version
{
  "raiden": "0.9.1.dev31+g2020466.d20180924",
  "python_implementation": "CPython",
  "python_version": "3.7.0",
  "system": "Linux 64bit_ELF 4.15.0-34-generic x86_64",
  "distribution": "source"
}
[ -d .git ] && git rev-parse HEAD
202046675742df38814f48754310fa757704d600

```

**Comment by LefterisJP** [comment]
@err508 you seem to be using an older version of Raiden. This raiden error should be handled from 0.10.0 and afterwards.
