### ISSUE TITLE
Use updated matrix servers list

### ISSUE THREAD

**Issue by andrevmatos** [raiden-network/raiden#2604]
## Problem Definition

Currently, the list of available matrix servers is hardcoded in the configurations:
https://github.com/raiden-network/raiden/blob/2bdaf306178834a61d05cd0b2c1212b1dc931833/raiden/app.py#L48-L52
Other servers may still be passed by hand with `--matrix-server` CLI option, but if the default of `auto` is used, one of these hardcoded servers will be selected based on response times from user's location.

We need to ensure this list is updated when new servers are added. Currently, the curated list is kept in `raiden-transport` repository. We should fetch the list dynamic list from https://github.com/raiden-network/raiden-transport/blob/master/known_servers.yaml, and use it on raiden' startup. In the future, an on-chain repository of available servers (as well as other 3rd party service providers as PFS and MS) may be used instead.

**Comment by LefterisJP** [comment]
TODO: Add testnet switch for usign our own servers for testnet cc @ulope
