### ISSUE TITLE
In-depth search for unhandled exceptions in transport messages handling

### ISSUE THREAD

**Issue by andrevmatos** [raiden-network/raiden#2605]
## Problem Definition

We have tests for ill-formed messages arriving the transport [here](https://github.com/raiden-network/raiden/blob/master/raiden/tests/integration/test_matrix_transport.py), but the tranport only does basic validation of the message before forwarding it to the core of raiden, the state machine, through [message_handler.py::on_message](https://github.com/raiden-network/raiden/blob/2bdaf306178834a61d05cd0b2c1212b1dc931833/raiden/message_handler.py#L135). After that, there's a tone of places where asserts, keyerrors and other exceptions caused by a _well-formed but not expected by the current state_ messages, either by desynched state partners or hand-crafted by malicious attackers, could cause exceptions which, unhandled, will crash the node, causing a DoS and potentially funds loss for the user.

#1787 was an attempt to mitigate this issue, but of course, not the right one.

As was done for the REST API by @CosminNechifor in https://github.com/raiden-network/raiden/issues/1944#issuecomment-418382971 , we need to walk through all possible handling codepaths and make sure to list possible exceptions, and identify the right place to handle it. No message, by accident or malicious, should be able to crash the node.

**Comment by LefterisJP** [comment]
I would suggest we implement scenarios or tests to cause these invalid messages and when we fix them have tests for regression.

**Comment by LefterisJP** [comment]
As discussed in the planning meeting the proper way to handle this would be to:

- perform fuzzy testing of the message handler and of the state machine to find places in the code which can fail with assertions or raise unhandled exceptions. Such fuzzy testing would create:
    - messages with random data (most probably invalid)
    - valid messages of each different types (`SecretRequest`, `SecretReveal`, e.t.c.) with some specific data field off.
   - valid messages missing required arguments
   - more?

Current issues that track fuzzy testing (they call it property testing):

- [Initiator property testing](https://github.com/raiden-network/raiden/issues/1155)
- [Mediator property testing](https://github.com/raiden-network/raiden/issues/1156)
- [Target property testing](https://github.com/raiden-network/raiden/issues/1157)

---

I will create fuzzy testing meta issue for what should be done and we can decide on more details there.

**Comment by LefterisJP** [comment]
As for the manually looking through the code idea, I believe this is not actionable. It essentially is asking for an audit of the entire codebase, looking at each line of code. The message handler branched out to the entire raiden codebase.

As mentioned above the proper way to handle this is with fuzzy testing.

Closing this issue as non-actionable, no certain way to act on it or no certain way to consider it finished.
