### ISSUE TITLE
Matrix: Flakyness on test setup

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/raiden#2613]
Relevant log: https://travis-ci.org/raiden-network/raiden/jobs/433552881#L1238

**Comment by ulope** [comment]
Will probably be obsolete once #3172 is merged.

**Comment by ulope** [comment]
@hackaugusto Have you seen this in the last week or so?

**Comment by hackaugusto** [comment]
Nope, I haven't seen this particular error in quite some time

**Comment by ulope** [comment]
Ok, then I'll close it for now.
