### ISSUE TITLE
Fuzz Testing

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#2649]
## Motivation

Stemming from the discussion of [this](https://github.com/raiden-network/raiden/issues/2605) issue we should introduce fuzzy testing in Raiden.

## Tasks

- perform fuzzy testing of the message handler and of the state machine to find places in the code which can fail with assertions or raise unhandled exceptions. Such fuzzy testing would create:
    - messages with random data (most probably invalid)
    - valid messages of each different types (`SecretRequest`, `SecretReveal`, e.t.c.) with some specific data field off.
   - valid messages missing required arguments
   - more?

Current issues that track fuzzy testing (they call it property testing):

- [Initiator property testing](https://github.com/raiden-network/raiden/issues/1155)
- [Mediator property testing](https://github.com/raiden-network/raiden/issues/1156)
- [Target property testing](https://github.com/raiden-network/raiden/issues/1157)

## Other thoughts

Let's use this issue to discuss how to approach fuzzy testing and to generally track this task. At this point it is still not yet well defined.

**Comment by LefterisJP** [comment]
So far we have used the [hypothesis framework](https://hypothesis.works/). And from the [options](https://wiki.python.org/moin/PythonTestingToolsTaxonomy#Fuzz_Testing_Tools) out there for python, it seems like the best solution.

From here and on we will need to work on defining property tests for each different section of the state machine and adding them to our test runs.

**Comment by jomuel** [comment]
Closing this as we have settled for an approach to fuzz testing now and started implementing it. Current issues tracking fuzz testing (split into the different parts of the state machine) are #1155, #1156, #1157 and #3246.
