### ISSUE TITLE
Poorly handled exception when opening a channel

### ISSUE THREAD

**Issue by CosminNechifor** [raiden-network/raiden#2661]
## Problem Definition

When we open the channel from the webui calls ``open`` from the [rest.py](https://github.com/raiden-network/raiden/blob/master/raiden/api/rest.py#L538), then [channel_open](https://github.com/raiden-network/raiden/blob/master/raiden/api/rest.py#L554), in the end we end up calling the ``new_netting_channel`` [here](https://github.com/raiden-network/raiden/blob/master/raiden/network/proxies/token_network.py#L168). 

If for example the transaction fails in the [_new_netting_channel](https://github.com/raiden-network/raiden/blob/master/raiden/network/proxies/token_network.py#L190), the exception is propagated to the [new_netting_channel](https://github.com/raiden-network/raiden/blob/master/raiden/network/proxies/token_network.py#L166) and it's raised again.

In short the problem is that we don't provide any message to the user (webui), and we don't explain what might be the cause for this. The application keeps running like nothing happened except for the critical message that is shown in the terminal.

```
2018-10-03 10:48:47 [debug    ] new_netting_channel called     [raiden.network.proxies.token_network] peer1=27fad1fc peer2=ed3eb092                   
2018-10-03 10:48:48 [critical ] new_netting_channel failed     [raiden.network.proxies.token_network] peer1=27fad1fc peer2=ed3eb092
2018-10-03 10:48:48 [info     ] partner opened channel first   [raiden.api.python]
```

Problems that have to be solved:

- [ ] We should provide better error handling (Maybe change this part in order to propagate the exception till it reaches rest.py and then handle it there, and also give the proper response code)
- [ ] We should give the user a message saying what happened and why his channel is not opening

**Comment by LefterisJP** [comment]
I am not sure I understand what's wrong @CosminNechifor?

The rest api call will succeed, no? The channel will be opened. It's just not you that opened it but your partner. What is wrong with that?

**Comment by CosminNechifor** [comment]
@LefterisJP I didn't receive any notification, saying that the channel was already opened.

**Comment by hackaugusto** [comment]
> The application keeps running like nothing happened except for the critical message that is shown in the terminal

That is correct behavior in this case, the node lost a race to open the channel as shown by the last line of your logs.
