### ISSUE TITLE
Initial_channel_target and joinable_funds_target is automatically set to default when given 0

### ISSUE THREAD

**Issue by Dominik1999** [raiden-network/raiden#2675]
## Problem Definition

In the tests, when joining a network with `initial_channel_target = 0` or `joinable_funds_target = 0` the client responds with 204 and joins a network but with default values, i.e. `initial_channel_target = 3` or `joinable_funds_target = 0.4` respectively. 

It should either tell the user that it changed the values or not joining the network at all.

**Comment by LefterisJP** [comment]
Hey @Dominik1999 I don't see how this can happen. Can you provide the entire debug log of your test run and what API calls you made?

**Comment by Dominik1999** [comment]
@LefterisJP here is the logfile for `initial_channel_target` = 0 https://gist.github.com/Dominik1999/44db2487a52d23373e03c93aca377e78

**Comment by LefterisJP** [comment]
I want to see the logs of the raiden client. This seems like only a scenario player log.

**Comment by Dominik1999** [comment]
there you go, here the output of the respective Raiden node: https://gist.github.com/Dominik1999/30817a1fb7a90b2d0ff406f0e9b7df88

**Comment by LefterisJP** [comment]
I am sorry but this is not a debug log. Please find the raiden-debug.log in the appropriate directory as ulo said.

**Comment by Dominik1999** [comment]
Ok it took me some time, but I hope, now we are happy. 
https://gist.github.com/Dominik1999/82ca3a1f965e76d25a7e52a7b9e9bdcb

This is node 4, which joins a network with `initial_channel_target` set to `0`. So we would expect 0 channels to e opened or an error message. But we see 3 open channels. 

`=================================================================================================== TASKS ===================================================================================================
- [✔] Serial [1039 s]
  - [✔] Parallel [489 s] - Setting up a network
    - [✔] OpenChannel [489 s]: {'from': 0, 'to': 1, 'total_deposit': 10, 'expected_http_status': 201}
    - [✔] OpenChannel [349 s]: {'from': 0, 'to': 2, 'total_deposit': 10, 'expected_http_status': 201}
    - [✔] OpenChannel [348 s]: {'from': 1, 'to': 2, 'total_deposit': 10, 'expected_http_status': 201}
  - [✔] Serial [  0 s] - Checking the network
    - [✔] Assert [  0 s]: {'from': 0, 'to': 1, 'total_deposit': 10, 'balance': 10, 'state': 'opened'}
    - [✔] Assert [  0 s]: {'from': 0, 'to': 2, 'total_deposit': 10, 'balance': 10, 'state': 'opened'}
    - [✔] Assert [  0 s]: {'from': 1, 'to': 2, 'total_deposit': 10, 'balance': 10, 'state': 'opened'}
  - [✔] Serial [550 s] - Node Nr. 4 joins with initial_channel_target set to 0
    - [✔] JoinTokenNetwork [550 s]: {'from': 3, 'funds': 100, 'initial_channel_target': 0, 'expected_http_status': 204}
    - [✔] Assert [  0 s]: {'from': 3, 'to': 0, 'total_deposit': 20, 'balance': 20, 'state': 'opened'}
    - [✔] Assert [  0 s]: {'from': 3, 'to': 1, 'total_deposit': 20, 'balance': 20, 'state': 'opened'}
    - [✔] Assert [  0 s]: {'from': 3, 'to': 2, 'total_deposit': 20, 'balance': 20, 'state': 'opened'}
`

**Comment by LefterisJP** [comment]
@Dominik1999 this can't be the entire log. It starts `2018-10-07 10:45:03 ` and ends `2018-10-07 10:45:37`. That's only 34 seconds and does not contain anything api related. It's mostly riddled with calls to the infura ethereum node.

**Comment by Dominik1999** [comment]
@LefterisJP Sorry didn't see that. The whole file is 45Mb. How could I send it to you?

**Comment by LefterisJP** [comment]
@Dominik1999 As far as I can see from the logs you are joining the  token_network with an `initial_channel_target` of `3`.

> 2018-10-07 11:05:30 [debug    ] Connecting to token network    [raiden.api.rest] funds=100 initial_channel_target=3 joinable_funds_target=Decimal('0.4') registry_address=0xf2a175A52Bd3c815eD7500c765bA19652AB89B30 token_address=0xDF7dEF5f01e924b1D5092DB6A54ee1cab9896801

**Comment by Dominik1999** [comment]
Hmm this is not what 
- is written in the scenario https://gist.github.com/Dominik1999/d76c7cf509dfaffbe5ade08d33753bea 
- or what the scenario player tells me 

================== TASKS ==================
- [✔] Serial [1039 s]
  - [✔] Parallel [489 s] - Setting up a network
    - [✔] OpenChannel [489 s]: {'from': 0, 'to': 1, 'total_deposit': 10, 'expected_http_status': 201}
    - [✔] OpenChannel [349 s]: {'from': 0, 'to': 2, 'total_deposit': 10, 'expected_http_status': 201}
    - [✔] OpenChannel [348 s]: {'from': 1, 'to': 2, 'total_deposit': 10, 'expected_http_status': 201}
  - [✔] Serial [  0 s] - Checking the network
    - [✔] Assert [  0 s]: {'from': 0, 'to': 1, 'total_deposit': 10, 'balance': 10, 'state': 'opened'}
    - [✔] Assert [  0 s]: {'from': 0, 'to': 2, 'total_deposit': 10, 'balance': 10, 'state': 'opened'}
    - [✔] Assert [  0 s]: {'from': 1, 'to': 2, 'total_deposit': 10, 'balance': 10, 'state': 'opened'}
  - [✔] Serial [550 s] - Node Nr. 4 joins with initial_channel_target set to 0
    - [✔] JoinTokenNetwork [550 s]: {'from': 3, 'funds': 100, 'initial_channel_target': 0, 'expected_http_status': 204}
    - [✔] Assert [  0 s]: {'from': 3, 'to': 0, 'total_deposit': 20, 'balance': 20, 'state': 'opened'}
    - [✔] Assert [  0 s]: {'from': 3, 'to': 1, 'total_deposit': 20, 'balance': 20, 'state': 'opened'}
    - [✔] Assert [  0 s]: {'from': 3, 'to': 2, 'total_deposit': 20, 'balance': 20, 'state': 'opened'}

Does maybe the scenario player changes this value automatically?

**Comment by LefterisJP** [comment]
Perhaps this is a scenario player bug or you are making some kind of mistake. Unless you can give me a different log I can't say what's wrong. According to the logs the raiden node got the value of `3` for `initial_channel_target`.

**Comment by LefterisJP** [comment]
@ulope can you check if this is a bug with the scenario player?

**Comment by Dominik1999** [comment]
So for me it still looks like a bug. Tried it again manually, with the following response:
```
(.raiden2) dominik@dominik-ThinkPad-T450s:~/PycharmProjects/Raiden2$ curl -i -X PUT http://localhost:5004/api/1/connections/0xd0A1E359811322d97991E03f863a0C30C2cF029C -H 'Content-Type: application/json' --data-raw '{"funds": 1000000000000000, "initial_channel_target": 0}'
HTTP/1.1 204 NO CONTENT
mimetype: application/json
Content-Type: application/json
Content-Length: 0
Date: Thu, 25 Oct 2018 09:42:25 GMT
```
No content seems to be the response code for successfully joining the network. 

> 204 No Content – For a successful connection creation.

However, in the WebUI it shows me that I did not join the network yet neither do I see any open channels. 

Please tell me if this is something worth investigating and what logs do you need to see.

**Comment by palango** [comment]
@Dominik1999 

> However, in the WebUI it shows me that I did not join the network yet neither do I see any open channels.

Isn't that what we would expect if we want no channels to be created?

**Comment by palango** [comment]
regarding the issue in the scenario player, looks like this could be the issue:
```py
        initial_channel_target = self._config.get('initial_channel_target')
        if initial_channel_target:
            params['initial_channel_target'] = initial_channel_target
```
If `initial_channel_target` is 0, then is evaluated as falsy and the value won't be set. @ulope

**Comment by palango** [comment]
My proposal to fix this is requiring that `initial_channel_target >= 1`. @LefterisJP

**Comment by palango** [comment]
I wanted to wait for some answer from Dominik, but I guess he can reopen if necessary.

**Comment by Dominik1999** [comment]
sorry I was for 2 days not on my laptop. Looks like you have found the source of the error
