### ISSUE TITLE
Join a network - no error message when joinable_funds_target > 1

### ISSUE THREAD

**Issue by Dominik1999** [raiden-network/raiden#2676]
## Problem Definition

When joining a network the optional argument `joinable_funds_target` can be set with a value on (0,1). However, when `joinable_funds_target` is set >1, the client joins the network (204 response) and creates channels with deposit and balance 0.

I would expect the function to throw.

**Comment by LefterisJP** [comment]
This is indeed a bug. Let me fix that. We don't do sanity checks on `joinable_funds_target` and if you give something bigger than `1` you end up with a negative number inside the connection manager. 

Ouch.
