### ISSUE TITLE
Join a network - initial_channel_target > network participants doesn't throw an error

### ISSUE THREAD

**Issue by Dominik1999** [raiden-network/raiden#2677]
## Problem Definition

When joining a network the variable `initial_channel_target ` can be set. It defines with how many token network participants channels are opened. When `initial_channel_target ` is set to some value bigger than the number of participants in the network, the Raiden client responses with 204, joins the network, opens channels with all participants but allocates the `funds` as if there were as many channels like in  `initial_channel_target ` set. 

Example:  `initial_channel_target `= 4, 3 participants in the network -> 3 open channels with 0 deposit and 0 balance each.

I would expect the function to throw or to allocate the `funds` over the actual amount of participants.

**Comment by hackaugusto** [comment]
This is the intended behavior, do you think it should be changed or better documented?

The REST API call only configures the channel manager, and once the channel manager is configured it will run and manage the channels for you, if you request for 4 channels but that is not possible to open at the moment, the manager will wait until a new address is available and connect to it.

**Comment by Dominik1999** [comment]
Thanks @hackaugusto , sounds good to me. Maybe we can add this info into the Raiden documentation @czepluch ?

**Comment by LefterisJP** [comment]
@Dominik1999 Please don't assign labels or people without consulting with me first :)

> I would expect the function to throw or to allocate the funds over the actual amount of participants.

Why is that? The way it currently is now the client will not do someting you don't expect. You still have 1/4th of your funds to allocate for another channel when another participant joins the network.

But perhaps we should add this edge case to the documentation.
