### ISSUE TITLE
Improve debug log naming

### ISSUE THREAD

**Issue by ulope** [raiden-network/raiden#2690]
## Abstract

Raiden automatically writes a debug log file on each run. Currently this file is called `raiden-debug.log` with an optional numeric suffix for log rotation.

## Motivation

Having this simplistic name becomes problematic when running multiple nodes at once or multiple times in quick succession.

Therefore it would be helpful to include more details in the filename to avoid conflicts and make them easier to identify.

## Specification

Change the debug file name to follow this template (slightly pseudo code):
`f'raiden-debug-node_{pex(node_addr)}-net_{net_id}-{datetime.now().isoformat()}.log'`

## Backwards Compatibility

This is a debug only feature, so backwards compatibility is not relevant.
We will need to update the issue template text asking users to submit those files slightly though.

**Comment by hackaugusto** [comment]
@ulope what about using the database folder?

**Comment by dergoegge** [comment]
I would like to take this one!
Am i correct that this should be done in the [here](https://github.com/raiden-network/raiden/blob/94d33b9e69143fd679e42d5fa375a3d78a7b4d6c/raiden/log_config.py#L130)?

Also since i have never worked with raiden before where do i get the node address and network id from?

**Comment by LefterisJP** [comment]
Yes it can be done there. As you can see the argument curently has a default value which is what we got.

As for `node_address` and `net_id` you can get them if you move the `configure_logging()` call from [here](https://github.com/raiden-network/raiden/blob/94d33b9e69143fd679e42d5fa375a3d78a7b4d6c/raiden/ui/cli.py#L1002) to [here](https://github.com/raiden-network/raiden/blob/94d33b9e69143fd679e42d5fa375a3d78a7b4d6c/raiden/ui/cli.py#L629).

@ulope Would moving the `configure_logging()` call have some bad side effects?

**Comment by andrevmatos** [comment]
@dergoegge Thank you for wanting to pick this up.
That function has a `debug_log_file_name` parameter you may prefer to set one level above, where it's called, i.e. in [cli.py](https://github.com/raiden-network/raiden/blob/94d33b9e69143fd679e42d5fa375a3d78a7b4d6c/raiden/ui/cli.py#L1002-L1007). IMO, the only difficulty is that some of these information may currently only be available at `_run_app` time, a little below (as `configure_logging` is done quite early during startup). The option then would be to possibly move the call to `_run_app` where you get those infos, possibly redirecting initial log calls to some random file and then moving it in-place on the final log setup.

**Comment by dergoegge** [comment]
@LefterisJP @andrevmatos thanks guys! you both pretty much described the same thing so i'm gonna do that!

**Comment by LefterisJP** [comment]
But hmm @dergoegge on second thought I think we need @ulope to answer [this](https://github.com/raiden-network/raiden/issues/2690#issuecomment-427373285) comment by @hackaugusto 

The idea of using the DB folder to save the debug log in is much better imo, as we get all that info he wants to put in the filename already.

**Comment by LefterisJP** [comment]
yes. Should be even easier.

**Comment by ulope** [comment]
In theory using the database path would be great. The problem is that it's being constructed very late in startup. The place where the directory is actually created, if it doesn't exist, is even later all the way in `RaidenService.__init__()`.

That is much too late to catch startup logging and would require annoying workarounds such as logging to a temporary file and later renaming it (as Andre suggested). That seems too complicated for a simple debugging feature.

Instead I'd suggest to place the file in `tempfile.gettempdir()` (which usually points to `/tmp` on POSIX like systems). All the information required for naming is available at the place of the current `configure_logging` call in the `self._options` dict.

**Comment by hackaugusto** [comment]
> In theory using the database path would be great. The problem is that it's being constructed very late in startup.

The only requirement is the account selection. Network id and token network registry are provided as part of the configuration and have defaults, database version is a constant.

So the startup could be:

- Display warning and wait for the confirmation
- Ask the user for the account (only thing thing that is new prior to the logging configuration)
- configure logging with database path

Is this too late?

**Comment by ulope** [comment]
No, that should be fine. We only need to switch from using logging to prints (or rather `click.secho` calls) in the `AccountManager`. Shouldn't be a big issue since it only has two logging calls IIRC.
