### ISSUE TITLE
Fix PyPI uploading

### ISSUE THREAD

**Issue by ulope** [raiden-network/raiden#2701]
## Problem Definition

The newly re-enabled PyPI uploading failed due to the presence of the `dist/archive` folder: 
https://travis-ci.org/raiden-network/raiden/jobs/437840495#L4391

Possibly the binary release files will also cause problems, check before fixing.

We can't use `skip_cleanup: false` since otherwise the compiled webui would be deleted as well.

## Solution

- Move PyPI deployment to the end
- Add a script deployment directly before it that deletes the `archive` folder from `dist` after the binary deployment steps are done is done.

**Comment by LefterisJP** [comment]
Isn't this a duplicate of: https://github.com/raiden-network/raiden/issues/2205 ?

**Comment by ulope** [comment]
#2205 is solved. This is a new issue that is the result of it IMO.

**Comment by LefterisJP** [comment]
All right. Fine by me.

**Comment by ulope** [comment]
Should be fixed by #2705
