### ISSUE TITLE
Be consistent with response codes in the docs

### ISSUE THREAD

**Issue by czepluch** [raiden-network/raiden#2710]
## Problem Definition
As a result of https://github.com/raiden-network/raiden/issues/2706 it is clear that some places in the docs are inconsistent with the actual responses provided by the API.

We need to go through the docs and make sure it is consistent all the way through according to the following rules:
- If there is an error in the URL return 404
- If there is malformed request data return 400
- If there are other errors in the values of the request then we just have 409 as a catch all.

## Tasks
- [ ] Go through the API doc and make sure it's consistent with the API code.
- [ ] If the API code is inconsistent somewhere fix the code

**Comment by palango** [comment]
In danger of start bikeshedding here:
It doesn't feel consistent to me to return 404 when an address in a URL is non-checksummed, but returning 400 when the non-checksummed address is in the json body.

I'd rather return a 400 everywhere when an address has the wrong format. @czepluch @LefterisJP

**Comment by LefterisJP** [comment]
no please stick to what was discussed. 404 for urls being wrong and 400 for json body.
