### ISSUE TITLE
Only poll for events from confirmed blocks

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/raiden#2711]
## Abstract

Reorgs may change the order transactions are executed, the new order may make a previously successful transaction fail, or change the order of events. To avoid races we need to wait for the blocks to be confirmed.

## Motivation

This has introduce a few bugs #2449 #2658 #2664 

## Specification

The event filter should just lag behind by confirmations blocks.

## Backwards Compatibility

This will not introduce backwards compatibility issues, but it will add a bit of latency for the secret registration, which is not a problem with the current version of the smart contracts because of the secret registry.

## Related

Take chain reorg into account #1121

**Comment by palango** [comment]
Fixed by #2671
