### ISSUE TITLE
Wrong arguments in API function call

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden#2723]
## Problem Definition

In the python API we call the function `list_channelstate_for_tokennetwork` twice with different parameters, where the third parameter should be the `token_address`.
https://github.com/raiden-network/raiden/blob/819dffa74ec813cc5bcd29b04a557814810b0e74/raiden/api/python.py#L559-L571

**Comment by LefterisJP** [comment]
I am looking at this.
