### ISSUE TITLE
Document how to get/create W-ETH

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden#2740]
For Red Eyes we require the use of W-ETH. We should add a guide that explains how to convert Ether to W-ETH to lower the barrier to use Red Eyes.

**Comment by LefterisJP** [comment]
This should be part of our onboarding guide. @czepluch can you handle this?

**Comment by czepluch** [comment]
Sure.

**Comment by christianbrb** [comment]
Also adding a link in the blog post

**Comment by palango** [comment]
Added this in the Red Eyes tutorial, can be tracked with #1486
