### ISSUE TITLE
Flag `--network-type` and its options' names are confusing

### ISSUE THREAD

**Issue by konradkonrad** [raiden-network/raiden#2752]
## Problem Definition

`--network-type` currently supports two options: `main` and `test`. They are easily confused with the `--network-id` parameter for the Ethereum chain, i.e. `mainnet`.
From what I gathered, not even the name "network type" is very descriptive.

I'm putting this issue up for discussion, but here are some proposals:
- `--protocol-configuration release|dev`
- `--environment release|dev`

As for the option names, I could also think of
- `live|sandbox`

Other suggestions welcome!

**Comment by andrevmatos** [comment]
How about `prod|dev` or `production|development`, as in angular/js builds?

**Comment by LefterisJP** [comment]
Plus one for `production|development`

**Comment by konradkonrad** [comment]
Can we also get some eyes on the option name?

**Comment by andrevmatos** [comment]
In JS realm, it's called `--environment`, or `--env`, not sure if it applies here

**Comment by junaidev** [comment]
I am using https://github.com/raiden-network/raiden/releases/tag/v0.14.0 build and connected with a private eth net. When registering new token I am getting {"errors": "Registering a new token is currently disabled in the Ethereum mainnet"} while using ./raiden-v0.14.0-linux --config-file config.toml --environment-type development cli
