### ISSUE TITLE
Channel lifecycle scenario

### ISSUE THREAD

**Issue by CosminNechifor** [raiden-network/raiden#2756]
## Scenario player 

We need a scenario that tests for more then just one specific case. That's why I would like to introduce a scenario that would test for the following cases: 

| **Cases** |
|---|
| Try to open a channel  | 
| Try to open a channel, but the channel already exists  | 
| Try to open a channel with 0 deposit  |
| Try to deposit less then the amount already deposited  | 
| Try to deposit to a channel that does not exist |
| Deposit more then the total_deposit |
| Try to open a channel with more tokens than the RedEyes limit |
| Selecting available routes |
| Performs multi hop payments |
| Performs one hop payments |
| Closing channels |
| Making deposit to a channel that is being closed |
| Selecting routes with enough capacity, or channels that are still open |
| Try to close channels that are already being closed |
| Leave token network while some channels are already being closed |
| Trying to make a payment to a through a channel that was closed |

## Scenario steps:
| Number | Action | 
|----|--------------------------------------------------------------------------------------------------|
| 1  | Start 5 Raiden nodes                                                                             |
| 2  | Create the following channels: A - B, B - C, C - D with 0 deposit                                |
| 3  | A B C D make a deposit of 100 to their channels                                                  |
| 4  | E tries to make a deposit to a channel that does not exist (fail channel with D  does not exist) |
| 5  | B makes a deposit of 50 tokens on both of his channels (fail)                                    |
| 6  | B tries to open a channel with A, but it already has a channel (fail)                            |
| 7  | C opens a channel with E (0 tokens)                                                              |
| 8  | C makes a deposit of 100 tokens                                                                  |
| 9  | C tries to deposit 30 tokens  (fail)                                                             |
| 10 | C deposits 150 tokens to the channel (C - E)                                                     |
| 11 | A tries to open a channel with an initial deposit that is bigger then the Red Eyes Limit (fail)  |
| 12 | A opens a channel with E (initial deposit of 10)                                                 |
| 13 | E deposits 25 tokens to A<->E channel                                                            |
| 14 | A performs a payment to E of 50 tokens (path A<->B<->C<->E)                                      |
| 15 | C sends all of its tokens to B (one transfer)                                                    |
| 16 | C tries to send another > 25 tokens payment to B (fail no route with enough capacity)            |
| 17 | C sends 10 payments of 1 token to B by using the C <->  E <-> A <-> B route                      |
| 18 | B shuts down                                                                                     |
| 19 | A sends 10 tokens to C (using the A<-> E <-> C route)                                            |
| 20 | A tries to open a channel with B (fail - it already has a channel with B)                        |
| 21 | A tries to make a payment to B (Node is offline - fails)                                         |
| 22 | B is back online                                                                                 |
| 23 | D sends all 100 tokens to C on payments of 1 token/each.                             |
| 24 | A deposits 160 tokens on his channel with B                                          |
| 25 | Assert that route A->B->C->D has enough capacity to send 200 tokens from A to D      |
| 26 | Perform 200 payments From A to D                                                     |
| 27 | Assert                                                                               |
| 28 | E closes his channel with C                                                          |
| 29 | C tries to make a deposit in the channel that is being closed (fail 409)             |
| 30 | C sends 10 tokens to B                                                               |
| 31 | B sends 10 tokens to A                                                               |
| 32 | E sends 10 tokens to C (A -> B-> C)                                                  |
| 33 | E Closes his channel with A                                                          |
| 34 | All nodes try to make a payment to E which should fail                               |
| 35 | A and B leave the token network                                                      |
| 36 | Assert that the only channel that is still opened is C(0 capacity) <-> D(200 tokens) |
| 37 | C tries to close the channel that is already being closed with  B                    |
| 38 | C and D leave the token network                                                      |
| 39 | Assert for the closed channels                                                       |

**Comment by palango** [comment]
Just going through the issues, @czepluch you've probably taken care of this already in your spreadsheet!?

**Comment by czepluch** [comment]
Yeah, PR has been closed.
