### ISSUE TITLE
ActionInitChain using wrong value

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/raiden#2784]
## Problem

- During start up we use the latest block number (as seen by the node's Ethereum node) to initialize the node's state [here](https://github.com/raiden-network/raiden/blob/ab9aaa2a11c2351dae033f767490f29ac4b7b9d5/raiden/raiden_service.py#L291), this is dispatched and make recoverable by the WAL [here](https://github.com/raiden-network/raiden/blob/ab9aaa2a11c2351dae033f767490f29ac4b7b9d5/raiden/raiden_service.py#L309)
- Then [here](https://github.com/raiden-network/raiden/blob/ab9aaa2a11c2351dae033f767490f29ac4b7b9d5/raiden/raiden_service.py#L370) Raiden polls all events from the smart contracts, updating the node's view of the blockchain
- If during the poll the node is crashes, it will be left with a partial update
- On restart, the node will use the latest block number set in the NodeState, [here](https://github.com/raiden-network/raiden/blob/ab9aaa2a11c2351dae033f767490f29ac4b7b9d5/raiden/raiden_service.py#L319). Which is up to the latest block number
- That block is then used [here](https://github.com/raiden-network/raiden/blob/ab9aaa2a11c2351dae033f767490f29ac4b7b9d5/raiden/raiden_service.py#L350) to poll the events from the blockchain

## Fix

Instead of using the latest block number, ActionInitChain must use the block height at which the token network registry was deployed.

**Comment by palango** [comment]
Fixed by #2787
