### ISSUE TITLE
Routing problem 

### ISSUE THREAD

**Issue by CosminNechifor** [raiden-network/raiden#2798]
## Problem Definition

The initiator of the transfer can't perform the payment, because it believes there is no route to the target, the target is offline or it has not enough balance to perform the payment. All of those three cases are invalid. The target is actually online, there exists a path to the target, and also it has enough balance to perform the payment.  

I've ended up to this problem while testing with the scenario from #2763 , in this scenario there is a section which checks for the direct channel balances between the two nodes. 
More exactly here: 

https://github.com/CosminNechifor/raiden/blob/a78dbf5c8ac4c86d9f7800c71cfce1b0080351a0/raiden/tests/scenarios/long-running.yaml#L191-L195

And after that I tried to perform 100 payment from node ``3`` to ``2``. 

https://github.com/CosminNechifor/raiden/blob/a78dbf5c8ac4c86d9f7800c71cfce1b0080351a0/raiden/tests/scenarios/long-running.yaml#L196-L201

99 of the transfer worked, The last payment failed, because instead of returning a 200 it returned a 409 conflict message code.

Full log of node 3 (initiator): 
[node_3_run-32.log](https://github.com/raiden-network/raiden/files/2482338/node_3_run-32.log)

Full log of node 2 (target):
[node2_run-32.log](https://github.com/raiden-network/raiden/files/2482343/node2_run-32.log)

There is no way this could have failed because of ``node3`` not having enough tokens: 

If we query the ``/api/1/channels`` for both accounts we can see this: 

![node2](https://user-images.githubusercontent.com/22676160/47008451-0a435900-d143-11e8-94ca-8ab8b6a47793.png)

![node3](https://user-images.githubusercontent.com/22676160/47008462-10393a00-d143-11e8-9ed9-c8cb5e99f88c.png)

Scenario player output: https://gist.github.com/CosminNechifor/ae19bccb4452f2ab31531d8429702e87 
 
### System Description

Here add a detailed description of your system, e.g. output of the following script:

```
Linux noname 4.15.0-36-generic #39-Ubuntu SMP Mon Sep 24 16:19:09 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux                                             
/usr/bin/solc                                                                                                                                         
solc, the solidity compiler commandline interface                                                                                                     
Version: 0.4.25+commit.59dbf8f1.Linux.g++                                                                                                             
/usr/bin/geth                                                                                                                                         
Geth                                                                                                                                                  
Version: 1.8.15-stable                                                                                                                                
Git Commit: 89451f7c382ad2185987ee369f16416f89c28a7d                                                                                                  
Architecture: amd64                                                                                                                                   
Protocol Versions: [63 62]                                                                                                                            
Network Id: 1                                                                                                                                         
Go Version: go1.10.1                                                                                                                                  
Operating System: linux                                                                                                                               
GOPATH=                                                                                                                                               
GOROOT=/usr/lib/go-1.10                                                                                                                               
/home/cosmin/.virtualenvs/raiden/bin/raiden                                                                                                           
{                                                                                                                                                     
  "raiden": "0.13.2.dev5+g28333184",                                                                                                                  
  "python_implementation": "CPython",                                                                                                                 
  "python_version": "3.6.5",                                                                                                                          
  "system": "Linux 64bit_ELF 4.15.0-36-generic x86_64",                                                                                               
  "distribution": "source"                                                                                                                            
}                                                                                                                                                     
a78dbf5c8ac4c86d9f7800c71cfce1b0080351a0
```

**Comment by LefterisJP** [comment]
Hm that's interesting. In the logs of the initiator you get:

> 2018-10-16 07:36:51 [info     ] channel doesnt have enough funds, ignoring [raiden.routing] amount=1 distributable=0 from_address=9fdbb73e partner_address=cb7cccc9.

So it sees the remaining distributable as `0` [here](https://github.com/raiden-network/raiden/blob/6a08d32f17ec82f1c96d8f87e7dc6a56df52ebd0/raiden/routing.py#L80).

Could be some for of off-by one error either in the client or in the scenario player side.

**Comment by LefterisJP** [comment]
It's not a bug. You have 1 token locked in that channel, so there is no off-by-one error.

> <SendBalanceProof msgid:7121098729253290257 paymentid:6842831693131323992 token:f0a2fa30 secrethash:2a939a2f recipient:cb7cccc9 balance_proof:<BalanceProofUnsignedState nonce:199 transferred_amount:99 locked_amount:1 locksroot:ee0f5859 token_network:d238b1d3 channel_identifier:1 chain_id: 4>>
