### ISSUE TITLE
Cannot deposit or transfer tokens to raiden node which has not joined a token network.

### ISSUE THREAD

**Issue by agatsoh** [raiden-network/raiden#2808]
## Problem Definition

A raiden node **A** (66aa)is started  , it does not join a token network, it does not open any channels, it does not have  tokens from the token networks that have already been created. 
Another raiden node **B** opens a channel to it. Both can see the channel through the UI, **B** can deposit to the channel, but can not make direct transfers to **A**. Instead, **B** (8645) unsuccessfully tries to route the transfer via a bystanding node **C** (67b2) it has also an open channel with.
[node-8645-debug.log](https://github.com/raiden-network/raiden/files/2486766/raiden-node-8645-debug.log)
[bystander-node-debug.log](https://github.com/raiden-network/raiden/files/2486845/raiden-bystander-node-debug.log)

node **A**(66aa) debug log  
[raiden-debug.log](https://github.com/raiden-network/raiden/files/2487466/raiden-debug.log)

node **A**(Ee36) debug log 2nd run
[node-Ee36.log](https://github.com/raiden-network/raiden/files/2488780/node-Ee36.log)

Was tested via UI (no reaction) and via api (no response, hanging)

### System Description

Here add a detailed description of your system, e.g. output of the following script:

```
Nodes B (8645) and C (67b2) were running on kovan via infura. 

uname -a
Darwin MacBook-Pro.fritz.box 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64

command -v solc && solc --version
Version: 0.4.24+commit.e67f0147.Darwin.appleclang

command -v raiden && raiden version

{
  "raiden": "0.13.2.dev7+gf2ab2edb.d20181016",
  "python_implementation": "CPython",
  "python_version": "3.6.0",
  "system": "macOS 10.13.6 64bit",
  "distribution": "source"
}

[ -d .git ] && git rev-parse HEAD
f2ab2edb84c7caba6242c289d949ecdb6ddda466
```
```
Details of node A
uname -a
Linux krishna-pc 4.18.12-arch1-1-ARCH #1 SMP PREEMPT Thu Oct 4 01:01:27 UTC 2018 x86_64 GNU/Linux
command -v solc && solc --version
/usr/bin/solc
solc, the solidity compiler commandline interface
Version: 0.4.25+commit.59dbf8f1.Linux.g++
sudo parity --version
Parity
  version Parity-Ethereum/v2.0.6-stable-549e202-20180919/x86_64-linux-gnu/rustc1.29.0
Copyright 2015, 2016, 2017, 2018 Parity Technologies (UK) Ltd
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

By Wood/Paronyan/Kotewicz/Drwięga/Volf
   Habermeier/Czaban/Greeff/Gotchac/Redmann
command -v raiden && raiden version
/home/krishna/Envs/raiden_env/bin/raiden
{
  "raiden": "0.13.2.dev13+g777f6760",
  "python_implementation": "CPython",
  "python_version": "3.7.0",
  "system": "Linux 64bit_ 4.18.12-arch1-1-ARCH x86_64",
  "distribution": "source"
}

 [ -d .git ] && git rev-parse HEAD
777f676085452cf040d666e0178141a6012a5f03

**Comment by czepluch** [comment]
This should work afaik. I have previously tried this where it works. Only think I can imagine is that the pathfinding maybe is a bit confused. Now that I think of it I might only have had a direct path when I did it and no potential mediator to confuse the pathfinding.

**Comment by err508** [comment]
This problem does not persist with:

```
Node B
{
  "raiden": "0.14.1.dev34+gf543900",
  "python_implementation": "CPython",
  "python_version": "3.7.0",
  "system": "Linux 64bit_ELF 4.15.0-36-generic x86_64",
  "distribution": "source"
}
```

and 

```
Node A
{
  "raiden 0.14.1.dev37+g97820b6b",
  "python_implementation": "CPython",
  "python_version": "3.6.6",
  "system": "Linux 64bit_ELF 4.15.0-36-generic x86_64",
  "distribution": "source"
}

```
The same setup has been retested with several fresh nodes.
