### ISSUE TITLE
Node crashes on quick restart after being killed

### ISSUE THREAD

**Issue by ulope** [raiden-network/raiden#2838]
## Problem Definition

(This may be parity related, haven't tested with Geth yet.)

Steps to reproduce:
- Kill a node (with SIGKILL, -9) right after a new block was received
- Restart node within a few seconds

The node crashes with a ValueError from within web3:
```
ValueError: {'code': -32000, 'message': 'One of the blocks specified in filter (fromBlock, toBlock or blockHash) cannot be found', 'data': '0x8b2045'}
```
[Full logs](https://gist.github.com/ulope/230c9a9551d179a5306afcf1f3be3386)
As you can see the `data` attribute in the error is increasing and seems to be a block number.
- `0x8b2045` -> `9.117.765`
- `0x8b2047` -> `9.117.767`
- `0x8b2048` -> `9.117.768`

This error persists for a while but disappears after a few minutes.

**Comment by hackaugusto** [comment]
Maybe this was fixed by https://github.com/raiden-network/raiden/pull/2671

**Comment by ulope** [comment]
@hackaugusto Unfortunately not, this was with latest master as of yesterday evening (e0f3e6f)

**Comment by hackaugusto** [comment]
Ahhh, I think I know what is the problem:

- A node learns about a new block, [updates its state](https://github.com/raiden-network/raiden/blob/97820b6bf431522c02eb99cd59a2cf9da25f62d6/raiden/raiden_service.py#L552-L557), then crashes
- On restart, the block number is [recovered](https://github.com/raiden-network/raiden/blob/97820b6bf431522c02eb99cd59a2cf9da25f62d6/raiden/raiden_service.py#L321), and the filters are ["installed" with the latest known block](https://github.com/raiden-network/raiden/blob/97820b6bf431522c02eb99cd59a2cf9da25f62d6/raiden/raiden_service.py#L347-L353), this will eventually be a [stateless filter](https://github.com/raiden-network/raiden/blob/97820b6bf431522c02eb99cd59a2cf9da25f62d6/raiden/network/rpc/client.py#L477-L485) instance
- The race: The node finishes the above *before* a new block is mined
- The bug: The [filter is polled](https://github.com/raiden-network/raiden/blob/97820b6bf431522c02eb99cd59a2cf9da25f62d6/raiden/raiden_service.py#L364) on first run, which [always executes the callbacks](https://github.com/raiden-network/raiden/blob/97820b6bf431522c02eb99cd59a2cf9da25f62d6/raiden/tasks.py#L179), and eventually poll the filter for a block in the future:

https://github.com/raiden-network/raiden/blob/97820b6bf431522c02eb99cd59a2cf9da25f62d6/raiden/utils/filters.py#L111

**Comment by LefterisJP** [comment]
As discussed in Rocketchat this should no longer be happening after https://github.com/raiden-network/raiden/pull/2895 which now updates the block state only with confirmed blocks.
