### ISSUE TITLE
--environment-type = "development" has no effect when registering new token on private eth net

### ISSUE THREAD

**Issue by junaidev** [raiden-network/raiden#2857]
## Problem Definition

When running Raiden in development env mode by specifying environment via command line argument or by using config.toml there is no effect. The bug is caught when Raiden is connected with a private eth net and new token was tried to registered. The new token registration always returned "errors": "Registering a new token is currently disabled in the Ethereum mainnet"}

### System Description

Here add a detailed description of your system, e.g. output of the following script:

```
uname -a
Linux Sharkstobalaba 4.15.0-36-generic #39-Ubuntu SMP Mon Sep 24 16:19:09 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

command -v solc && solc --version
/usr/bin/solc
solc, the solidity compiler commandline interface
Version: 0.4.25+commit.59dbf8f1.Linux.g++

parity --version
Parity Ethereum version Parity-Ethereum/v2.1.3-beta-18ddd7c-20181015/x86_64-linux-gnu/rustc1.29.0

aiden version
raiden-v0.14.0-linux
```

**Comment by junaidev** [comment]
Fixed bug in my local code, file: /raiden/raiden/ui/app.py 
changed :
    if environment_type == Environment.PRODUCTION:
        # Safe configuration: restrictions for mainnet apply and matrix rooms have to be private
        config['environment_type'] = Environment.PRODUCTION
        config['transport']['matrix']['private_rooms'] = True
    else:
        config['environment_type'] = Environment.DEVELOPMENT

to:
    if environment_type == Environment.PRODUCTION:
        # Safe configuration: restrictions for mainnet apply and matrix rooms have to be private
        config['environment_type'] = Environment.PRODUCTION
        config['transport']['matrix']['private_rooms'] = True
    else:
        config['environment_type'] = Environment.DEVEOPMENT

built raiden and tested with local private eth client, now its allowing me to register new token.

**Comment by LefterisJP** [comment]
@junaidev the change you are proposing seems correct @junaidev. It's indeed a bug. Would you like to open a PR for this?

**Comment by LefterisJP** [comment]
@junaidev please do a PR soon because we need this solved by EOD today.
