### ISSUE TITLE
Ensure the node works on a consistent view of the blockchain

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/raiden#2885]
## Problem Definition

The version `v0.14.0` of the source code is relying on the web3 library, which exposes smart contracts as proxies objects. Interactions with the smart contracts are done using these proxies and the [call](https://web3py.readthedocs.io/en/stable/contracts.html#web3.contract.ContractFunction.call) function, which under the hood uses the [`eth_call`](https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_call) RPC call, which happens to have a default value of `latest`.

This means that two consecutive calls can get data from different blocks, and if the new block happened to execute a transaction which changes the smart contract's state, it is possible to observe inconsistent data.

This is specially sensitive for the version `0.4.0` of the smart contracts, which exposes only a partial view of a channel, requiring the client to do multiple requests to recover the channel's state:

https://github.com/raiden-network/raiden/blob/eb03cc85ef1ca4d773e7c265e12b4fe0a5cf9ea3/raiden/network/proxies/token_network.py#L330-L338

### Solution

The fix for this problem is to use an explicit `block_identifier` (which must be the blockhash and not the block number, because of reorgs), to expose a consistent view of the data.

That means:

- [x] Add a blockhash argument to most proxy calls. This will allow us to query the blockchain for any block we need to.
- [ ] All state changes/events that deal with the proxies have to contain the blockhash of the block that triggered them so that there is a consistent view of what caused an event to be sent and the data we query during its processing.

**Comment by LefterisJP** [comment]
So block identifier argument was put in all of the proxies after https://github.com/raiden-network/raiden/pull/3391

**Comment by LefterisJP** [comment]
Next task in order to probably go in smaller steps would be a PR to:

- Add blockhash to all `ContractReceiveStateChange` state changes ... and perhaps other state changes/events that need it.
- Make a DB migration for the above

**Comment by LefterisJP** [comment]
This should be done after

https://github.com/raiden-network/raiden/pull/3515
https://github.com/raiden-network/raiden/pull/3505
https://github.com/raiden-network/raiden/pull/3550
