### ISSUE TITLE
Invalid LockedTransfer message keeps appearing

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden#2893]
## Problem Definition

For a payment I sent I keep getting this message in the logs every minute:
```
2018-10-25 13:52:52 [debug    ] Raiden event                   [raiden.raiden_service] node=28898a6b raiden_event={"identifier": 1540475471961, "secrethash": "0xa70607ac71de211c10bca1daab2d5e0f2ab5a321d24d77e11d518df293b4646b", "reason": "Invalid LockedTransfer message. Nonce did not change sequentially, expected: 5 got: 3.", "_type": "raiden.transfer.mediated_transfer.events.EventUnlockClaimFailed", "_version": 0}
```

The transfer with the id 1540475471961 completed successfully before:
```
    {
        "amount": 1000000000000000,
        "event": "EventPaymentReceivedSuccess",
        "identifier": 1540475471961,
        "initiator": "0xf2fBCC167cc3f24a620798E27b4BB084dD275253",
        "log_time": "2018-10-25T13:51:18.343"
    },
```

After a restart the message doesn't appear any more. That's why @hackaugusto thinks it might be some leftover-greenlet

### System Description

Here add a detailed description of your system, e.g. output of the following script:

```
Darwin yoda 18.0.0 Darwin Kernel Version 18.0.0: Wed Aug 22 20:13:40 PDT 2018; root:xnu-4903.201.2~1/RELEASE_X86_64 x86_64
/Users/paul/.bin/solc
solc, the solidity compiler commandline interface
Version: 0.4.23+commit.124ca40d.Darwin.appleclang
/usr/local/bin/geth
Geth
Version: 1.8.17-stable
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.11.1
Operating System: darwin
GOPATH=
GOROOT=/usr/local/opt/go/libexec
/usr/local/bin/parity
Parity
  version Parity-Ethereum/v2.0.8-stable-ef8f95e-20181015/x86_64-macos/rustc1.29.0
Copyright 2015, 2016, 2017, 2018 Parity Technologies (UK) Ltd
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

By Wood/Paronyan/Kotewicz/Drwięga/Volf
   Habermeier/Czaban/Greeff/Gotchac/Redmann

/Users/paul/Work/venv-raiden/bin/raiden
{
  "raiden": "0.14.1.dev26+gdb914d1a",
  "python_implementation": "CPython",
  "python_version": "3.6.5",
  "system": "macOS 10.14 64bit",
  "distribution": "source"
}
2c0d3525291c966b8ef6f66d670715fa6e945890
```

**Comment by hackaugusto** [comment]
As far as I know the matrix transport is starting a new greenlet for each message. IMO this should be changed to a queue, where new messages are pushed to and a single greenlet consumes from that queue.

Using a queue reduces the number of invalid messages processed by a node (because only valid messages are sent), makes it easier to send messages in batch (since you can peek the queue and push all messages at once), and is closer to what I understand as the expected behavior (not the best argument, but this is my opinion).

**Comment by kelsos** [comment]
It seems that I am getting this in `raiden-v0.15.1.dev6+g14cba904-linux` while testing but up to this point it doesn't seem to affect the expected outcome for the transfers.

**Comment by andrevmatos** [comment]
I agree with @hackaugusto . From Paul's logs, I can see the `Processed` for the message that generated these warnings was sent only once, and even without the respective `Delivered`, was not retried. I can't find in the logs nor in the code the reason for a message which was still in the queue not be retried by transport, but a per-queue loop implementation for the message retry logic, as Augusto suggested, will definitely ensure the message will be delivered and stopped only once cleaned.
