### ISSUE TITLE
Allow third parties to update the counterparty transfer

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#293]
## Problem Definition

To support offline nodes without closing the netting channels a monitoring third party is required, the third party will be responsible to call `updateTransfer` (or a equivalent function) on behalf of the offline counter party.

## Solution

Allow nodes that are not participants to call a function that has a similar behavior to `updateTransfer`.

## Tasklist

- [ ] A new message format for a node to inform third parties about it's known latest balance proofs.
- [x] A new netting channel function for a third party to update the transfer on behalf of the participant.
  - [x] ~Forbid the third-party from overwriting a participant provided transfer. (Note: This is not to protect against bad behaving participants, but to protect against bad behaving third-parties)~
- [ ] unit tests for this.

## Details

The concept of dispute and penalization were removed because:

- only the participants were allowed to update the netting channel by providing the *counter-party* message, this meant messages are always pristine.
- messages are monotonically increasing in value, this gives a strong interest for the participant to provide the latest know message from the counter-party.

With the introduction of third-parties we lose the property of always having pristine messages, but as long there is one well-behaved and up-to-date third party everything is okay. At the same hand we cannot add penalization to third-parties that provide an out-of-date message because the node could intentionally not update the service.

## Related

~Monitor Channels & Dispute #82~
~Allow third parties to close the channel #182~

**Comment by hackaugusto** [comment]
After issue #365 I think it is best to not reuse the `updateTransfer` function, but it's best to add a `thridpartyUpdate` of some kind, rationale:

- close may only be called by one of the participants once
- we need to allow multiple update calls from third parties, the one with the highest transferred_amount wins
  - this function may be used as long as the counter party doesnt call `updateTransfer`
- `updateTransfer` may only be called by the counter party once

**Comment by hackaugusto** [comment]
Update: #417 removed the courtesy transfer and prohibited calls to `updateTransfer` from any address but the counter party.

Now for this issue the netting channel library needs to be updated and the third party service coded.

**Comment by hackaugusto** [comment]
Update: The smart contract function was spec out here: [smart_contract](https://github.com/raiden-network/spec/blob/9ac529000fa9a9e9d4aea728b8230addf4d1907b/smart_contracts.rst), under the `Update transfer state` header, and the smart contract implementation is [here](https://github.com/raiden-network/raiden-contracts/commit/921c006a8fac5e556e238808667b48016b4c2bab#diff-1bdf2ff343918b98864fc26df16cc1ebR322)

There is a follow up issue to blind the balance proof from the monitoring service here https://github.com/raiden-network/raiden-contracts/issues/27

**Comment by hackaugusto** [comment]
> Forbid the third-party from overwriting a participant provided transfer. (Note: This is not to protect against bad behaving participants, but to protect against bad behaving third-parties)

This is fixed by the balance proof's sequential nonce and the requirement of the two signatures. If a good participant called updateTransfer, it will use the latest balance proof with the highest nonce, since the monitoring service cannot provide a valid balance proof with a higher nonce it cannot overwrite the data provided by the participant.

**Comment by hackaugusto** [comment]
This was fixed by: https://github.com/raiden-network/raiden-contracts/commit/09ed693f2afa08a7ae46fc3469cfb57e8761598a#diff-2f6fb78ac7aaf29aaec1ed8ab59468f8

Follow up issue for the python client: #1432
