### ISSUE TITLE
Unable to start Raiden Network with a user-defined network id

### ISSUE THREAD

**Issue by Lyric15** [raiden-network/raiden#2935]
## Problem Definition

I was trying to deploy Raiden on a private Ethereum network. It failed to start with a user-defined network id. 

The command I used was: raiden --keystore-path  ~/.ethereum/keystore --network-id 303

Then I selected an account to deploy raiden and then I received the following error message:

Traceback (most recent call last):
  File "/usr/local/bin/raiden", line 9, in <module>
    load_entry_point('raiden', 'console_scripts', 'raiden')()
  File "/home/ubuntu/raiden/raiden/__main__.py", line 11, in main
    run(auto_envvar_prefix='RAIDEN')  # pylint: disable=no-value-for-parameter
  File "/home/ubuntu/.local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/click/core.py", line 1043, in invoke
    return Command.invoke(self, ctx)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/ubuntu/raiden/raiden/ui/cli.py", line 397, in run
    app = runner.run()
  File "/home/ubuntu/raiden/raiden/ui/runners.py", line 243, in run
    return self._start_services()
  File "/home/ubuntu/raiden/raiden/ui/runners.py", line 97, in _start_services
    app_ = run_app(**self._options)
  File "/home/ubuntu/raiden/raiden/ui/app.py", line 274, in run_app
    if node_network_id in ID_TO_NETWORK_CONFIG:
UnboundLocalError: local variable 'node_network_id' referenced before assignment

### Issue checklist
Read through [Requirements for safe usage](https://raiden-network.readthedocs.io/en/stable/overview_and_guide.html#requirements-for-safe-usage) mentioned in our documentation and make sure your usage follows the requirements.

1. Is your Ethereum node syncing and up to date with the blockchain? **Yes**
2. Are you using the same Ethereum account with anything other than the Raiden node? Or are you running multiple Raiden nodes with the same Ethereum account? **No**
3. Does your Ethereum account used by Raiden have sufficient ETH? **Yes**
4. Did you alter or delete the local DB that exists by default at ~/.raiden? **Probably, I can't find it now. How to solve this?**
4. Did you stop / restart your raiden node while having open channels and/or pending transfers? if so, please provide further information. **No**
5. Did you stop / restart your Ethereum node while Raiden was running? **No**
6. Did you switch from one Ethereum node to another? example: switching from a local Ethereum node to an Infura one. **No**
7. Is Raiden REST API protected from public access? **Yes**

### System Description

Here add a detailed description of your system, e.g. output of the following script:

```
Linux miner2 4.4.0-137-generic #163-Ubuntu SMP Mon Sep 24 13:14:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
/usr/bin/solc
solc, the solidity compiler commandline interface
Version: 0.4.25+commit.59dbf8f1.Linux.g++
/usr/bin/geth
WARN [10-29|06:15:32.449] Sanitizing cache to Go's GC limits       provided=1024 updated=666
Geth
Version: 1.8.16-stable
Git Commit: 477eb0933b9529f7deeccc233cc815fe34a8ea56
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.11
Operating System: linux
GOPATH=
GOROOT=/home/travis/.gimme/versions/go1.11.linux.amd64
/usr/local/bin/raiden
{
  "raiden": "0.12.1.dev60+g5432b6f",
  "python_implementation": "CPython",
  "python_version": "3.6.5",
  "system": "Linux 64bit_ELF 4.4.0-137-generic x86_64",
  "distribution": "source"
}
```

**Comment by junaidev** [comment]
You are using "raiden": "0.12.1.dev60+g5432b6f" that's older version, can you try raiden 0.15 https://github.com/raiden-network/raiden/releases/tag/v0.15.0  ?

**Comment by LefterisJP** [comment]
i will close this issue unless you can reproduce this with the latest version. If you can please reopen.

**Comment by Lyric15** [comment]
Ok. I will try.
