### ISSUE TITLE
Direct Transfers/HappyCasePayments 

### ISSUE THREAD

**Issue by err508** [raiden-network/raiden#2957]
## Abstract

Currently we use the mediated transfer code path for all transfers. However, Raiden's Happy Path/minimal MVP could be reduced  to making use of contract's cooperative settle (_implemented/tested in the contracts, but deactivated_) and the direct transfer message (_partially implemented/untested_). 

## Motivation

The security assumptions for direct transfers and coop settle are relaxed); therefore implementing and testing the code path should **temporarily** remove **a lot** of complexity and overhead until the red eyes release is shipped (_for implementation but especially in app execution_). 

Removed complexity:
```
-> secret_request/secret_reveal sending/handling
-> Unlock handling
-> Pathfinding
```

## Specification

t.b.d

## Backwards Compatibility

Backwards compatible.

**Comment by LefterisJP** [comment]
We made a decision some time ago to remove direct transfers in favour of mediated transfers to have a consistent code path for all transfers and to not have to think of or debug special cases. I don't see that changing.

As for the coop settle, this will be implemented after Red Eyes.

**Comment by hackaugusto** [comment]
direct transfers were removed from the code base
