### ISSUE TITLE
Join Network in Tokens section of WebUI, scrolling is unintuitive 

### ISSUE THREAD

**Issue by mat7ias** [raiden-network/raiden#2963]
## Abstract

When attempting to join a Token Network via WebUI with 18 decimals the user (if they are using Chrome, I haven't checked other browsers) gets a window where it's unintuitive that they need to scroll down to show the entire message compared to less decimals 
![image](https://user-images.githubusercontent.com/35585644/48066077-b1864e00-e220-11e8-8dbc-4acb0409f579.png)) 
![image](https://user-images.githubusercontent.com/35585644/48066116-d5499400-e220-11e8-95e6-ee8b607141f4.png)

## Motivation

Suggestion would be to make anything up to 18 decimal places not require any type of scrolling for it to be visible.

**Comment by kelsos** [comment]
Hey @mat7ias thanks for reporting. The scrollbar is the default overflow behavior for the hint in the input, since the hint is directly bellow the input and can't expand more it would make sense to increase the width of the dialog.
