### ISSUE TITLE
Release 15.01 uncompatible with Infura endpoint

### ISSUE THREAD

**Issue by llxxee** [raiden-network/raiden#2973]
## Release 15.01 uncompatible with Infura endpoint

Using Raiden with an rpc-endpoint provided by an Infura Ethereum node results in Client 405 error:
`requests.exceptions.HTTPError: 405 Client Error: Method Not Allowed for url: https://ropsten.infura.io/v3/<token>`

### System Description
Raiden version:

```
{
  "raiden": "0.15.1",
  "python_implementation": "CPython",
  "python_version": "3.6.7",
  "system": "Linux 64bit_ELF 4.15.0-36-generic x86_64",
  "distribution": "bundled"
}
```

output of `./raiden --keystore-path  ~/.ethereum/testnet/keystore --eth-rpc-endpoint "https://ropsten.infura.io/v3/<my_token>"`:
```
... (Python Traceback)
requests.exceptions.HTTPError: 405 Client Error: Method Not Allowed for url: https://ropsten.infura.io/v3/<my_token>
```

Release 13.01 works well:
```
{
  "raiden": "0.13.1",
  "python_implementation": "CPython",
  "python_version": "3.6.6",
  "system": "Linux 64bit_ELF 4.15.0-36-generic x86_64",
  "distribution": "bundled"
}
```

**Comment by mat7ias** [comment]
Same issue as #2951 
Lefteris explained why this is happening [here](https://github.com/raiden-network/raiden/issues/2947#issuecomment-436785966). You can fix it by running a Geth or Parity node or otherwise, the next Raiden release should allow users to use Raiden with Infura again (usually comes out on Fridays). Running your own node is much more reliable compared to using Infura in general though so I'd probably recommend that.

**Comment by LefterisJP** [comment]
Until then you can use the latest nightly: https://raiden-nightlies.ams3.digitaloceanspaces.com/raiden-nightly-2018-11-08T06-37-50-v0.15.2.dev55%2Bga7698758-linux.tar.gz which should also include the fix.

**Comment by mat7ias** [comment]
@LefterisJP I still get the same error using the latest nightly with Infura. It works fine when I run my own node though.

**Comment by LefterisJP** [comment]
Hmm let me test it

**Comment by LefterisJP** [comment]
It's indeed still an issue. Possibly due to the checks introduced by https://github.com/raiden-network/raiden/pull/2969. I will work on this now.
