### ISSUE TITLE
Writing into a WAL

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/raiden#298]
Save and restart the node at the latest known valid state (#205)

- Save each state transition into the log prior to applying it.
  - Each transition must have a serial identifier.
  - This includes:
    - current mediated transfers states
    - all channels known balance proof (latest message, locks, and secrets)
- Save a snapshot of resulting state after the state transition is applied.
  - The snapshot must have an accompanying identifier for the latest transition applied
- Recover the state of the node from the log files.

**Comment by hackaugusto** [comment]
Related: #1

**Comment by LefterisJP** [comment]
I guess this should have been part of the MVP milestone. Adding it.

**Comment by hackaugusto** [comment]
Note: For Expose internal raiden events in the REST API #466 it would be nice to have a seekable log format
