### ISSUE TITLE
Raiden startup is slow

### ISSUE THREAD

**Issue by ulope** [raiden-network/raiden#2989]
## Problem Definition

It currently takes a long time to start Raiden (esp. first run).
This is most notable on Kovan where 150+ token networks are registered.

Needs investigation and evaluation for possible optimization.

**Comment by palango** [comment]
#2687 is related.

**Comment by ulope** [comment]
First datapoint: every `TokenNetwork` contract proxy instantiation takes about ~120ms. At 150 token networks that’s almost 20s startup time alone. A big portion of that 120ms seems to be spent on the has code check (esp. with a remote node).

**Comment by LefterisJP** [comment]
Yeah RPC calls cost a lot. An idea would be to have a utility contract that could batch all these checks for us in 1-N calls (depending on the gas limit). People are already doing this for token balance checks.

**Comment by hackaugusto** [comment]
https://github.com/raiden-network/raiden/issues/2793 is also related

**Comment by czepluch** [comment]
This was also discussed in the recent retreat and a couple of suggestions as to how to decrease the start-up time was created.

The two suggestions are:

1. To parallelize or batch the RPC calls that take place during start up
2. To make it possible to filter for token networks and only process events for the desired token networks.

We decided that this is not an immediate priority, but something we can do after the next main net release.

**Comment by palango** [comment]
Point 2 sounds similar to https://github.com/raiden-network/raiden/issues/2687

**Comment by rakanalh** [comment]
> People are [already doing](https://medium.com/@wbobeirne/get-all-eth-token-balances-for-multiple-addresses-in-a-single-node-call-4d0bcd1e5625) this for token balance checks.

The batch RPC call that was mentioned is as interesting as using a contract. It's probably a bit slower since it wasn't good for them but doesn't suffer the gas limit issue.

**Comment by hackaugusto** [comment]
I'm closing this issue because I believe the following issues cover this problem and are more detailed:

 Make token networks opt-in #2687 
 Parallelize transactions on restart #2793 
 Batch JSON RPC event polling #2818 
 Make PaymentChannel open event validation optional #3958
