### ISSUE TITLE
`TransactionChannelNewBalance.__lt__` broken

### ISSUE THREAD

**Issue by schmir** [raiden-network/raiden#2998]
`state.TransactionChannelNewBalance ` uses the functools.total_ordering decorator.

It's `__lt__` method looks like:
 
```
    def __lt__(self, other):
        if not isinstance(other, TransactionChannelNewBalance):
            return NotImplemented
        return (
            self.participant_address < other.participant_address and
            self.contract_balance < other.contract_balance and
            self.deposit_block_number < other.deposit_block_number
        )
```

Let's say we have two instances `a`, `b` of this class with 
`a.participant_address < b.participant_address` and `a.contract_balance < b.contract_balance` and
`a.deposit_block_number == b.deposit_block_number`.

Then none of the following conditions hold: `a<b`, `b<a`, `a==b`

i.e. there is no total ordering. The same seems to be true for `TransactionOrder`.

The solution is to compare tuples, look at the `functools.total_order` documentation for an example.

**Comment by LefterisJP** [comment]
Hah nice catch! You are indeed right. Let me fix that right up and add a test.
Does not seem to affect too much -- only seems to affect the deposit transaction order. The heap invariant must not have been respected since the ordering of `TransactionOrder` was not correct.
