### ISSUE TITLE
Add expiration handling into the raiden service

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/raiden#30]
- ~~DirectTransfer might need a expiration field~~
- Take into consideration the MediatedTransfer and CancelTransfer expiration in the netting contract

**Comment by hackaugusto** [comment]
Expiration is part of the lock and not of the transfers messages, the use of the expiration is to guarantee that a given secret will be released either through the network or the blockchain before a given channel can be settled, so it only needs to be considered for locks in the settlement and there is no need to add a expiration into the DirectTransfer.

**Comment by czepluch** [comment]
Expirations on locks should be compared to closing block instead of current block in order to determine if they're valid or not.

**Comment by czepluch** [comment]
After discussions with @hackaugusto, we agree that this is not a problem, and that the current behaviour is correct.

**Comment by hackaugusto** [comment]
To document our discussion:

> Take into consideration the MediatedTransfer and CancelTransfer expiration in the netting contract

Is done and it is using the current block number. The current block number is the correct approach, the alternative of the closing block is wrong, here is why:

For a transaction using the nodes ABC, where Alice is the initiator, Bob is the only mediator and Charlie is the target, Bob needs the guarantee that if Charlie claims the lock form the BC channel then he will also be able to claim from the AB channel.

To achieve that each node has a reveal timeout configuration used as `expire(BC.lock) <= expire(AB.lock) - reveal_timeout`, the reveal timeout needs to be sufficient for Bob to learn the secret, call close, and then unlock. If we did use the *closing block* instead of the *current block* this doesnt hold.

```
Let's assume that all three nodes are using the defaults and these are:

settle_timeout = 15
reaveal_timeout = 5

then

expire(AB.lock) == 10
expire(BC.lock) == 5

if the *close block number* is used to check expiration, then:

An attacker that controls A and C:

- Calls BC.close at block 5
- Waits for block 11 and do not close I-M
- AB.unlock(lock) will work in this *example* since the closing block is used to validate the lock
- BC.unlock(lock) will not work in this *example* since the channel is not closed and the lock becomes expired
```

ie. if we did use the close block number we expand the lifetime of the lock up to settle_timeout blocks, and that is would not be correct.
