### ISSUE TITLE
Retrying to initiate a transfer plus receiving an invalid secret request for it seems to confuse the client

### ISSUE THREAD

**Issue by jomuel** [raiden-network/raiden#3000]
Calling `raiden.transfer.node.state_transition` with the following sequence of actions results in a failing assertion (`"lock is already registered"`):
- `ActionInitInitiator`
- an invalid `ReceiveSecretRequest` for the initiated transfer, e. g. one in which the `amount` is wrong
- the same `ActionInitInitiator` again

This is the first issue we found by fuzz testing, so we are not certain it is an actual bug. To reproduce, run `test_failing_path_2` in the wip pull request #2887.

**Comment by hackaugusto** [comment]
This is the same problem as https://github.com/raiden-network/raiden/issues/3001 , but instead of receiving a new secret request the transfer is "restarted". So, I'm going to close this as a duplicate.
