### ISSUE TITLE
Debug log file is always created

### ISSUE THREAD

**Issue by ulope** [raiden-network/raiden#3003]
## Problem Definition

The debug log file is always created upon Raiden start even if the `--disable-debug-logfile` option is set.

The reason is that the `debug-info` handler [is unconditionally configured](https://github.com/raiden-network/raiden/blob/f141d2e7c1203b8889762c24192f1c4894719bd0/raiden/log_config.py#L238-L245) (which already causes the file to be created) even if it isn't enabled depending on the flag.

## Solution

Only define the `debug-info` handler if the debug log is enabled.

**Comment by palango** [comment]
Fixed by #3018
