### ISSUE TITLE
Annotate assertions or convert to UnrecoverableErrors

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden#3004]
## Abstract

We have a couple of assertions without messages which leads to hard to debug errors (see #2947).
We should either add error messages to each assertions or throw some exception.

## Motivation

See above

## Specification

We need to add messages to all assertions or find another solution for this problem.
@ulope has a small pipeline for finding raw asserts (https://github.com/raiden-network/raiden/issues/2947#issuecomment-436231611):
```bash
ggrep -r --include '*.py' --exclude-dir tests --exclude-dir node_modules -P '^\s*assert [^,]+$' . | wc -l
      57
```

## Backwards Compatibility

No problems

**Comment by hackaugusto** [comment]
I would additionally add a pylint linter to enforce this rule

**Comment by hackaugusto** [comment]
https://github.com/raiden-network/raiden/pull/5564
