### ISSUE TITLE
Save the version in the sqlite database

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/raiden#3006]
## Abstract

Add a new table named `runs` to the local database, insert in it the timestamp and version of the software.

## Motivation

To debug problems with upgrades, it's important to know the version of the software which was running at a given point in time.

## Specification

I guess the best place to save this data is just before `AlarmTask.first_run` in `Raiden.start`, my rationale is that logging too early may spam the table if a supervisor is used with useless information, and if it's too late (after the transport is started) then we may miss important debugging information, **prior** the alarm task `first_run` is a good point because we don't do state changes until then.

## Backwards Compatibility

This is completely backwards compatible

**Comment by hackaugusto** [comment]
> The client may crash during recovery attempts, and especially in such cases it would be very beneficial to be able to pin-point the moment in state that lead to the crash.

Like during restoring the latest snapshot and replaying state change? This sounds fine, it is a lot of data per entry anyways.

**Comment by karlb** [comment]
What would be the right place to put a test for this? `test_wal.py` is the only test file using SQLiteStorage, but this feature is not wal related. Add it nevertheless, create a new file or skip it because a test is overkill for this simple feature?

**Comment by LefterisJP** [comment]
@karlb you can make a new file where all non-wal specifi sqlite tests will go.
