### ISSUE TITLE
Encode all integers before saving to the sqlite database

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/raiden#3013]
## Problem Definition

SQLite support up to [8 bytes integers](https://www.sqlite.org/datatype3.html), but Raiden uses values up to 32 bytes. If a query is built with a value larger than `2 ** 8 -1` the following exception is thrown:

> OverflowError: Python int too large to convert to SQLite INTEGER

This means we cannot represent integers in SQLite directly, and the value must be encoded with another representation.

## Specification

- Choose an alternative representation, preferably a representation which respects the total order of integers
- Implement this new representation in the serializers/deserializers of all state_changes / events / state objects which contain integers
- Fix the SQLite queries which rely on integers to also encode the values as appropriate:
  - Mainly done in `raiden_event_handler.py`

## Backwards Compatibility

This will break database compatibility, since the representation of integers will change.

**Comment by andrevmatos** [comment]
I think SQLite supports the `NUMERIC` datatypes, e.g. `Decimal(30, 0)`, which supports arbitrarily large values (stored as text/blob if can't fit on standard int sizes). Lib/driver is then responsible for converting them upon reading, even casting it to python's `Decimal` type. Wouldn't it fit more transparently this usecase?
