### ISSUE TITLE
Enable coverage report generation on a nightly basis

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#3020]
## Problem Definition

In the past we used to run coverage with coveralls on every PR. We stopped that for two reasons:

1. Running tests with coverage slows them down considerably
2. Due to the flakiness of some tests and the fact that we also can skip particular tests with commit labels like `[no ci-integration]`, the coverage report was erratic and was changing after every commit.

Right now to get coverage reports (e.g. for the unit tests) we need to run tests locally with:

```
coverage run -m pytest raiden/tests/unit
coverage html
```

And then look inside the generated `htmlcov` directory.

## Task

The above is manual and not something we can easily point to externals to showcase the coverage of the test suite. 

So to reintroduce a coverage report and have it updated on a dailys basis we would need to have it run on a nightly job with all tests being run, generate the report with [coveralls](https://pypi.org/project/python-coveralls/) in Travis and display it in html in the coveralls website.

**Comment by palango** [comment]
If we only want coverage on the unit tests (which might make sense at least for the state machine) we could also enable coverage only for that job.

**Comment by LefterisJP** [comment]
@palango We want of the entire test suite. Only unit tests is not that useful. Plus it's super easy and fast to get the report locally. The entire test suite though is another matter.

**Comment by ulope** [comment]
There was a discussion during the retreat that we should look into using codecov.io instead of coveralls since it seems much nicer from a reporting perspective and is also used by trustlines.

**Comment by LefterisJP** [comment]
@ulope Good point. I think that @konradkonrad made it still with coveralls which is fair game at the moment. Perhaps make another issue to document a switch to codecov.io?
