### ISSUE TITLE
when i run raiden from source when i go to 127.0.0.1:5001 i get {"errors": ["invalid endpoint"]}

### ISSUE THREAD

**Issue by Giulio2002** [raiden-network/raiden#3021]
when i run raiden from source when i go to 127.0.0.1:5001 i get {"errors": ["invalid endpoint"]}.
i downloaded the source code to run it from source and it seems that raiden can't start the user interface.
i also used the ```sh --web-ui```  flag, but it's not working either.

**Comment by LefterisJP** [comment]
Hello @Giulio2002. Thank you for your report.

There is an issue template when you try to open a new issue. It asks you for a lot of information that is helpful to us. Can you please use it?

I need to know what version of raiden you were using (commit hash if it's source) and what exactly you were trying to do. How did you run raiden? Where do you get the error?

**Comment by Giulio2002** [comment]
commit hash: dc9406351589f5b4ec2192db3a7a16c4ccf93008
command: python3 raiden/__main__.py --web-ui --datadir ~/.raiden/data --keystore-path ~/.raiden/keys --eth-rpc-endpoint https://ropsten.infura.io/  --network-id ropsten

**Comment by LefterisJP** [comment]
@Giulio2002 And where do you see the error? What do you do to get the invalid endpoint? 

The command looks wrong. How did you install it from source? Have you read the [developer](https://raiden-network.readthedocs.io/en/latest/overview_and_guide.html#for-developers) guide?

**Comment by Giulio2002** [comment]
When i try to use the web i get this error. I have ran with python3 the __main__.py script in raiden folder

**Comment by kelsos** [comment]
Hi @Giulio2002, did you also follow the [webui tutorial](https://raiden-network.readthedocs.io/en/latest/webui_tutorial.html)? The webui needs to be build before being usable when using raiden from source.

**Comment by LefterisJP** [comment]
@Giulio2002 so does it work for you now? If yes then we will close this issue.
