### ISSUE TITLE
Make writing unit tests easier

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/raiden#3025]
## Abstract

The current unit tests can be verbose to write because of the amount of data that we need to pass around to instantiate value objects. To make unit tests easier to write we should provide factories that are easy to use.

## Motivation

Goals:
- Work at the WAL level (not the RaidenService or above)
- Make it easier to write tests:
  - Reduce the number of variables a test needs to manage by introducing hidden state
  - Automate duplicated tasks:
    - Creating topologies
  - Easy to control the messages sent/received:
    - Simulate concurrency by interleaving state changes for different transfers
    - Simulate networks problems by delaying/replaying/dropping state changes
    - Simulate attacks by producing invalid state changes (with or without valid signatures)
  - Easy to test multiple nodes:
    - To test both ends of a channel and simulate a network
  - Easy to assert on valid states:
    - Needs to take into account difference of views of both nodes:
      - assertions that are valid globally
      - assertions that are valid locally
      - assertions that are valid after a given state change

## Backwards Compatibility

This is just about testing, compatibility is not an issue.

**Comment by LefterisJP** [comment]
We definitely need some more factories for creating common topologies at the unit test level. I find myself copying pasting from other tests and adjusting as I go -- so most of these can be abstracted to nice factories.

**Comment by pirapira** [comment]
@hackaugusto showed me https://github.com/hackaugusto/raiden/commit/8cdbe87bb8317091baef1e5dcdda1b4347bdbd5f and told me I can explore other approaches as well.

**Comment by pirapira** [comment]
I'll try a simpler approach using `functools.partial()` and show how the tests look (probably on a pull-req).

**Comment by pirapira** [comment]
@jomuel are you also working on this?

**Comment by pirapira** [comment]
After an offline discussion, I'm passing this one to @jomuel .

**Comment by LefterisJP** [comment]
There has been some progress on the additional factories side by @jomuel 

https://github.com/raiden-network/raiden/pull/3143
https://github.com/raiden-network/raiden/pull/3108

**Comment by LefterisJP** [comment]
I will remove it from the milestone though as this is not a blocker right now and jochen is on vacation.

**Comment by jomuel** [comment]
Follow-up issue: #3335
