### ISSUE TITLE
Implement the Atomic token swap within the raiden architecture

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/raiden#303]
## Problem Definition

Current implementation relies on greenlet tasks that are not restartable

## Solution

Write the atomic token swap within the restartable Raiden architecture (this might need new state changes and events)

## Tasklist

- [ ] Code the maker
  - [ ] state function
  - [ ] tests
- [ ] Code the taker
  - [ ] state function
  - [ ] tests
- [ ] Remove `Raiden::handle_secret`, this method should not be required after the exchange tasks are done.

**Comment by LefterisJP** [comment]
@hackaugusto can you confirm this is finished and if yes close the issue?

**Comment by hackaugusto** [comment]
It's not implemented, token swaps are using greenlets

**Comment by LefterisJP** [comment]
This is going out of Red Eyes

**Comment by LefterisJP** [comment]
@Dominik1999 @rakanalh I think we can close this issue. As far as I understand we don't plan to implement this, but instead will rely on xud.
