### ISSUE TITLE
Raiden node unable to find registered tokens 

### ISSUE THREAD

**Issue by err508** [raiden-network/raiden#3030]
## Problem Definition

When running some raiden nodes (~4/15), the WETH token network is not displayed, neither via UI (displays _No tokens found!_) nor API (returns empty list). 
-  happened with infura and vpn eth-endpoint. 
- `v12.db` only

 
### System Description

Here add a detailed description of your system, e.g. output of the following script:

```
{
  "raiden": "0.16.1.dev26+g13590b0",
  "python_implementation": "CPython",
  "python_version": "3.7.0",
  "system": "Linux 64bit_ELF 4.15.0-36-generic x86_64",
  "distribution": "source"
}
[ -d .git ] && git rev-parse HEAD
13590b074bad7f853b8214177dd1f2f46d887b4e
```

**Comment by junaidev** [comment]
I am too facing same issue

**Comment by err508** [comment]
@junaidev Pls set up a new account and see if the error persists. We're currently investigating that issue.

**Comment by LefterisJP** [comment]
Guys can we get some more information? Logs? Which network is this on?

**Comment by junaidev** [comment]
I used new accounts on both ends of raiden and now I am able to list registered tokens. 
I was running raiden in development mode with tobalaba.

**Comment by LefterisJP** [comment]
This issue has not been able to be reproduced and no logs were provided. Seems that when both @err508 and @junaidev tried with a new account it did not surface again.

I will close this as "Could not reproduce". If we get more info (logs e.t.c.) and a reproducible way to see the error then we can revisit or open another issue.
