### ISSUE TITLE
Add types and run typecheck on target.py

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#3040]
## Problem Definition

This is part of work to make the state machine type-checkable to have one additional tool that will help us find bugs. 

## Task

Add types to `target.py` and then run mypy on the file: `mypy raiden/transfer/mediated_transfer/target.py --ignore-missing-imports` and fix any problems that may be found.  No need to go in other files, we will do the mypification file-by file.

**Comment by pirapira** [comment]
```
mypy raiden/transfer/mediated_transfer/target.py --ignore-missing-imports | cut -f 3- -d " " | sort
```
shows similar errors together.

**Comment by pirapira** [comment]
I'm dropping this while I take over the smart contracts.

**Comment by palango** [comment]
Fixed with https://github.com/raiden-network/raiden/pull/3983
