### ISSUE TITLE
Decrease minimun settle_timeout for testnet

### ISSUE THREAD

**Issue by Giulio2002** [raiden-network/raiden#3056]
## Decrease minimun settle_timeout for testnet

Using raiden, i noticed that 500 are too much block in ropsten. Additionally having a limit for settle_timeout in testnet can be really annoying for developers. For example if i want to quickly settle a channel to test a new channels related feature or if i want to just to quickly try out raiden, i have to wait (in ropsten) almost 2-3 hours.

## Motivation

Every block on ropsten takes a long time before it get mined.(sometimes in ropsten a new block get mined after 1 minute)
in mainnet, blocks don't need so much time (13 seconds average)

## Specification

i think it would be a good idea to decrease the reveal_timeout in config if the ``--network-id`` is different from mainent

**Comment by LefterisJP** [comment]
@Giulio2002  We are testing with the same defaults we are going to be using on mainnet.

You can edit the [DEFAULT_SETTLE_TIMEOUT](https://github.com/raiden-network/raiden/blob/9790bfd76de3f63a8c2e8e2a99eeabdbcd6df867/raiden/settings.py#L30) and [DEFAULT_REVEAL_TIMEOUT](https://github.com/raiden-network/raiden/blob/9790bfd76de3f63a8c2e8e2a99eeabdbcd6df867/raiden/settings.py#L29) values to suit your needs in your tests for the channels you open.
