### ISSUE TITLE
Add documentation on testing to Contributing.md

### ISSUE THREAD

**Issue by konradkonrad** [raiden-network/raiden#3069]
## Abstract

We should document for developers _when_ and _how_ to write unit tests over integration tests. This documentation should be added to `Contributing.md`.

## Motivation

Issue #3025 aims to make writing unit tests easier and we want to encourage testing from the inside out. One problem we discovered in the past is that new developers tend to write integration tests ("I make sure my thing is somehow covered by some test") rather than unit tests and may sometimes have no good understanding when to apply which testing strategy.

## Specification

Write a documentation paragraph in `Contributing.md` that answers
- [ ] What testing strategies do we have available
- [ ] What testing strategy should I chose in which situation
- [ ] How do I get started with either testing strategy

**Comment by jomuel** [comment]
I wanted to add some information about fuzz testing anyway, so I will take this issue.
