### ISSUE TITLE
Comparing message handling of Python clients against that of smart contracts

### ISSUE THREAD

**Issue by pirapira** [raiden-network/raiden#3070]
Purpose
-----------

The purpose of this plan is to prevent some unhappy scenarios where users feel like they’ve lost their funds because Python and smart contracts behave differently on messages.

The unhappy scenarios looks like this:
1. The Raiden client receives a message, says the message is fine.
2. The user tries to use the message to interact with smart contracts.
3. The smart contracts say the message is not good.

One such case has been found already: https://github.com/raiden-network/raiden/issues/3054

Targets
------

The Python client should be stricter than (or equivalent to) smart contracts about:
* Crypto primitives
* Each message
    * Message format checks
        * Length check
        * Value checks
* Validity of operations

Methods
------

### Code Review

Comparing the relevant Solidity code and the Python code.

### Fuzzing

Extending the Python fuzzing (#2649 ) with the following two steps:
* convert the Message into a call into smart contracts
* perform the call in EVM.
If the Python client validates a message but the smart contract fails, we might have found a problem.

Progress
----

| aspect  |  code review  | fuzzing  | outcome   |
|---|---|---|---|
|  ECDSA signature validation | [ ] |  not planned yet  | found #3054   |
| BalanceProof (in `Secret` messages) | spent 30 mins.  |  not planned yet  |   |
| LockedTransfer | n/a | not planned yet | basically a BalanceProof |
| RevealSecret | [ ] | not planned yet | found #3091 |
| unlock() evidences |  |  | found https://github.com/raiden-network/raiden/pull/3238  |
|  [more to be filled] |   |  not planned yet |   |

**Comment by pirapira** [comment]
I'll pick this up when I can afford to.

**Comment by karlb** [comment]
The most likely case of this problem happening is mismatching signatures. We now use signatures generated from the contracts repo which are tested against the contracts, there.
