### ISSUE TITLE
Use a sliding window for UDP transport

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/raiden#308]
Each node must order it's own messages before sending to the partner, this is currently implemented with a queue of messages and a new message is only sent when the current in flight message is acknowledged. This naive implementation compromises throughtput.

The protocol should support a kind of sliding window implementation, like [go-back-n](https://en.wikipedia.org/wiki/Go-Back-N_ARQ), to improve througput.

**Comment by hackaugusto** [comment]
Do we want to do this for the UDP transport?

**Comment by LefterisJP** [comment]
I don't think it makes sense now with the work being done on the matrix transport layer, no?

**Comment by hackaugusto** [comment]
if we replace UDP with matrix, definitely no need for it

**Comment by rakanalh** [comment]
UDP Transport was removed. Closing
