### ISSUE TITLE
EventUnlockClaimFailed constantly emitted

### ISSUE THREAD

**Issue by rakanalh** [raiden-network/raiden#3086]
The mediator's current logic for `handle_block` currently updates the payer_state twice when the lock has already expired. 

https://github.com/raiden-network/raiden/blob/9790bfd76de3f63a8c2e8e2a99eeabdbcd6df867/raiden/transfer/mediated_transfer/mediator.py#L1108-L1147

The first is the call to `events_for_onchain_secretreveal_if_dangerzone` which updates the payer_state of the pair to `payer_waiting_secret_reveal`.

https://github.com/raiden-network/raiden/blob/9790bfd76de3f63a8c2e8e2a99eeabdbcd6df867/raiden/transfer/mediated_transfer/mediator.py#L811-L812

While the call to `events_for_expired_pairs` will check if the lock has expired and if the payer state has NOT `payer_expired` then it will emit the `EventUnlockClaimFailed`. 

The problem here is that the condition for the pair in `events_for_expired_pairs` will always be True because the previous call to the `events_for_onchain_secretreveal_if_dangerzone` has overrided the value of `payer_expired` with `payer_waiting_secret_reveal` which will trigger emitting the `EventUnlockClaimFailed` every time.

**Comment by LefterisJP** [comment]
@rakanalh Spent some more time playing also with Receiving a `LockExpired` message from the payer channel to see how this could lead to the proper code path where you problem surfaced. But did not get anywhere yet. 

At this point it would really help if you could give me a minimal reproducible scenario and a set of minimum steps which lead to the behaviour you observed.

**Comment by LefterisJP** [comment]
Found another occurence of this but for the target. PR incoming.
