### ISSUE TITLE
Consider which v values to use with ecdsa_recoverable() for Ithaka and later

### ISSUE THREAD

**Issue by pirapira** [raiden-network/raiden#3089]
When I reported https://github.com/raiden-network/raiden/issues/3054, @loredanacirstea told me to keep an issue open for considering `v` values for future releases after Red Eyes.  We could say only {0,1} are valid, or something else.

**Comment by LefterisJP** [comment]
@pirapira Do the smart contracts plan to change their behavior for this in Ithaca? If yes we should keep this issue open and adjust the client behavior too. If not then I would say we should close this issue. What do you think?

**Comment by pirapira** [comment]
Now I believe, the easiest way is to keep the current behaviors.

**Comment by rakanalh** [comment]
If that's the case, i will remove it from the Ithaca milestone.

**Comment by LefterisJP** [comment]
And I will close it. If we need to revisit this then let's open another issue with a better definition.
