### ISSUE TITLE
Collapse multiple messages within a single UDP packet

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/raiden#309]
Raiden messages are ordered using a per target queue, this allows to collapse multiple raiden messages into a single transport packet.

**Comment by hackaugusto** [comment]
Note: Direct transfer may be a problem for packing, since these transfers are irrevocable, it's unclear what to do if a packet contains two direct transfers and neither are acknowledged.

**Comment by rakanalh** [comment]
UDP Transport was removed. Closing
