### ISSUE TITLE
Using 0x0000...00 as a secret works in the client but not in the smart contracts

### ISSUE THREAD

**Issue by pirapira** [raiden-network/raiden#3091]
Currently, the SecretRegistry contract [refuses 0x00...00 as the secret](https://github.com/raiden-network/raiden-contracts/blob/master/raiden_contracts/contracts/SecretRegistry.sol#L22).  If I create a hash lock with keccack(0x0000..00), send the secret, but never send a balance proof, what happens?

If the recipient believes it has received an offchain payment, but cannot really claim the payment online, the experience is unpleasant.

* [ ] See if Python client accepts keccack(0x0000..00) as a secrethash when it receives LockedTransfer message
* [ ] See if Python client accepts 0x0000..00 as a secret when it receives RevealSecret message
* [ ] See if Python client accepts a 31-byte or 33-byte secret when it receives RevealSecret message (this is @konradkonrad 's idea).

(How I found it: I started reading Solidy code with https://github.com/raiden-network/raiden/issues/3070 in mind.)

Ping: @loredanacirstea

**Comment by pirapira** [comment]
>  if Python client accepts 0x0000..00 as a secret when it receives RevealSecret message

Seems like yes.  I followed till [mediator.py: def handle_offchain_secretreveal()](https://github.com/raiden-network/raiden/blob/27b4c34a8eef067ab6a2fc3928fa775a643f3c59/raiden/transfer/mediated_transfer/mediator.py#L1209), but I haven't seen a check against `0x0000...00`.

**Comment by pirapira** [comment]
> if Python client accepts a 31-byte or 33-byte secret

Seems like no.  On the messages, they are always 32 bytes.  https://github.com/raiden-network/raiden/blob/27b4c34a8eef067ab6a2fc3928fa775a643f3c59/raiden/encoding/messages.py#L51
> secret = make_field('secret', 32, '32s')

**Comment by pirapira** [comment]
@LefterisJP does this look like a critical bug?

**Comment by loredanacirstea** [comment]
My reasoning for not allowing registration for a secret of the form `bytes32(0)` in the `SecretRegistry` contract was that it could imply an error in the way the `secret` is computed. 
E.g.: the `secret` is somehow not set and it is considered `0x00..0` -> if this happens, then multiple transfers could potentially "reuse" the `bytes32(0)` secret without knowing.

Indeed, I should have checked the client implementation more closely.

**Comment by pirapira** [comment]
Perhaps do all of them.  Just 1. is not enough.  Do 2. and 3.

**Comment by LefterisJP** [comment]
@pirapira yeah that's what I meant. Edited comment for clarity.
