### ISSUE TITLE
Payments hang forever -- even after the lock expires

### ISSUE THREAD

**Issue by junaidev** [raiden-network/raiden#3094]
## Problem Definition

Raiden restful post call for token transfer timeouts if there is timeout set at restful consumer end. If there is no time out the post call hangs forever. It is random occurring issue. Along with this failed token transfer restful call other get calls (like querying channels ..etc ) are successful simultaneously. 

POST /api/1/payments/0x0f114A1E9Db192502E7856309cc899952b3db1E/0x61C808D82A3Ac53231750daDc13c777b59310bD9 HTTP/1.1
Host: localhost:5001
Content-Type: application/json

{
    "amount": 42
}

### System Description

System description: 

```
command -v solc && solc --version
/usr/bin/solc
solc, the solidity compiler commandline interface
Version: 0.4.23+commit.124ca40d.Linux.g++

command -v solc && solc --version
/usr/bin/solc
solc, the solidity compiler commandline interface
Version: 0.4.23+commit.124ca40d.Linux.g++

command -v geth && geth version
/usr/bin/geth
Geth
Version: 1.8.13-stable
Git Commit: 225171a4bfcc16bd12a1906b1e0d43d0b18c353b
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.10.3
Operating System: linux
GOPATH=
GOROOT=/home/travis/.gimme/versions/go1.10.3.linux.amd64

command -v raiden && raiden version
/usr/local/bin/raiden
{
  "raiden": "0.17.1.dev49+g27b4c34a.d20181129",
  "python_implementation": "CPython",
  "python_version": "3.6.7",
  "system": "Linux 64bit_ 4.15.0-39-generic x86_64",
  "distribution": "source"
}


/raiden# [ -d .git ] && git rev-parse HEAD
27b4c34a8eef067ab6a2fc3928fa775a643f3c59
```

**Comment by junaidev** [comment]
No that is not happening,

**Comment by LefterisJP** [comment]
Hmm okay let me have a look then.

**Comment by junaidev** [comment]
I reproduced it again today, after continuous 525 token transfers in a 1 to 1 channel, Raiden node is not responding any more transfer call on that channel ...

**Comment by LefterisJP** [comment]
@junaidev The not responding part is probably due to this issue which we are currently looking at: https://github.com/raiden-network/raiden/issues/2779

But the transfer getting stuck forever and not returning after the lock timeout is indeed a problem! I introduced a fix here: https://github.com/raiden-network/raiden/pull/3111
