### ISSUE TITLE
Remove DirectTransfer message from the implementation

### ISSUE THREAD

**Issue by pirapira** [raiden-network/raiden#3097]
@LefterisJP [says](https://github.com/raiden-network/spec/pull/137#issuecomment-442826348) DirectTransfer messages are never used, so they should be removed.  He also has a git branch somewhere that does this.

**Comment by pirapira** [comment]
I love your branch.  Pure removal of hundreds of lines.

**Comment by LefterisJP** [comment]
And it's not even finished ^_^. I should pick it up in the weekend.
