### ISSUE TITLE
geth is being reused during integration tests

### ISSUE THREAD

**Issue by luehrsFred** [raiden-network/raiden#3098]
## Intro

Geth client is being reused due to bug in finding free port. This causes some test failures afterwards. 

## Problem Definition

After rejoining all integration tests in one job in circle ci I found out that a started geth client is being reused throughout the tests. Although the blockchain provider is session scoped the problem lies in the `setup_testchain_and_raiden` finding a free port. `get_free_port` always delivers 28754 which then does not start a new geth node instead it uses the current one which is already running. This means that former tests does not stop geth properly, which should be done also to avoid reuses like this IMO.

**Comment by hackaugusto** [comment]
Fixed by: https://github.com/raiden-network/raiden/pull/3991
