### ISSUE TITLE
Add filter polling

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/raiden#31]
Consider what is a proper bloom filter for the secret revealed events (or if it is required at all)

**Comment by konradkonrad** [comment]
related #54

**Comment by hackaugusto** [comment]
A new task was created to do poll filter changes every half-second.

Commit 276b2f18bcbac4adc4f5ad36353f12b8b03cb8fa , d598d2cbb1256b12c3afc42fe4770606b47b76a7 , and e83f19a03842e94066ed9f3864e425ae1eaf67d6 added the `LogListenerTask`
