### ISSUE TITLE
Geth is not properly closed after session closed

### ISSUE THREAD

**Issue by luehrsFred** [raiden-network/raiden#3101]
## Intro
I discovered that after starting geth via the function `setup_testchain_and_raiden` in smoketest.py geth is never been closed afterwards. Even when pytest finishes geth continues to run.

I assume that this causes some flakiness problems we encountered in the past. Also in the same moment `get_free_port` always return 28754 which points to the still running geth from before. Nevertheless it accepted the current running one.

The free port problem is going to be fixed by #3099 

## Reproduction

For test purposes run some tests which use `setup_testchain_and_raiden`

`
pytest   -vvvvvv   --log-config='raiden:DEBUG'   --random   --blockchain-type=geth --transport=udp raiden/tests/integration/cli
`
after pytest finishes run 

`
netstat -tulpe | grep geth
`
to see if geth is still running and which port it uses

### System Description

Here add a detailed description of your system, e.g. output of the following script:

```


Linux think-fred 4.13.0-46-generic #51-Ubuntu SMP Tue Jun 12 12:36:29 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
Version: 0.4.25-develop.2018.6.21+commit.32f2db78.Linux.g++
Geth
Version: 1.8.12-stable
Git Commit: 37685930d953bcbe023f9bc65b135a8d8b8f1488
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.10
Operating System: linux
GOPATH=
GOROOT=/usr/lib/go-1.10
{
  "raiden": "0.17.1.dev51+g5fe0df70",
  "python_implementation": "CPython",
  "python_version": "3.6.3",
  "system": "Linux 64bit_ELF 4.13.0-46-generic x86_64",
  "distribution": "source"
}

```

**Comment by hackaugusto** [comment]
This should have been fixed by https://github.com/raiden-network/raiden/pull/3809
