### ISSUE TITLE
Matrix: Initial sync must be done w/o sync token to get room / invite state

### ISSUE THREAD

**Issue by ulope** [raiden-network/raiden#3113]
## Problem Definition

With #3090 we introduced keeping the matrix sync token across restarts. This is a nice optimisation for message syncing but creates a problem with room membership and invite state.

Both room membership and invites are handled as events that get returned in the sync call as well. When using a previously stored sync token any events that happened before the "timestamp" the sync token represents will not be returned.

Since we keep no local state in the matrix transport across restarts we rely on the initial sync of room membership and invites to restore our state. 
Thanks to @andrevmatos for reminding me of this.

## Task List

- [ ] Perform initial sync w/o sync token but with a message length filter of 0 to only get membership and other 'meta' events
- [ ] Use stored sync token for subsequent sync calls

**Comment by hackaugusto** [comment]
Question: Would it be useful to store the rooms information and go back to use the token?

**Comment by andrevmatos** [comment]
@hackaugusto that's what matrix-js-sdk does, and they're in way better shape about this. It'd need some refactoring of [G]MatrixClient though, to be able to fully serialize matrix state, and ensure correct build up of state changes/deltas over syncs, then we can go back to store and reuse sync token.
