### ISSUE TITLE
Remove all mypy errors around Address type

### ISSUE THREAD

**Issue by pirapira** [raiden-network/raiden#3120]
When I apply #3051 on the current codebase, I get hundreds of test failures due to missing `Address(...)` casts.  This issue keeps track of removing mypy errors around `Address` type first on the whole codebase.

**Comment by pirapira** [comment]
When I try to cover any more files under mypy, I see lots of mypy errors around unit test factories.  I think it's better to wait for https://github.com/raiden-network/raiden/issues/3025 .  (Easier unit tests are far more important.)

**Comment by LefterisJP** [comment]
You can also apply mypy only on the source directory and omit tests for now.

**Comment by pirapira** [comment]
When I add `raiden/ui` as an argument to mypy, mypy starts checking the unit tests.

**Comment by LefterisJP** [comment]
> When I add raiden/ui as an argument to mypy, mypy starts checking the unit tests.

Hmm that's strange ... no idea why they get pulled in if you add the `ui` directory

**Comment by pirapira** [comment]
@jomuel are you still making changes in the unit test fixtures?  Or can I start modifying the type annotations in there?

**Comment by LefterisJP** [comment]
He still has a pending PR afaik

**Comment by pirapira** [comment]
Has he?

**Comment by LefterisJP** [comment]
Yes. By pending I mean "yet to be opened". Check the standup report of the last 2 days in Rocketchat.

**Comment by pirapira** [comment]
I'm dropping this while I'm taking over the smart contracts.

**Comment by palango** [comment]
Fixed with https://github.com/raiden-network/raiden/pull/3983
