### ISSUE TITLE
Increase test coverage of MatrixTransport

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#3124]
## Problem Definition

Even though the [`MatrixTransport` has a test coverage of > 70%](https://codecov.io/gh/raiden-network/raiden/src/master/raiden/network/transport/matrix.py) most of that is incidental through the integration tests. 

We assumed that the integration tests would be enough to thoroughly test the transport, but it turns out that this assumption was mistaken.

We need specific tests that exercise esp. the unhappy and edge cases.

Some groundwork in that direction has already been laid with #3172 (and the [accompanying tests](https://github.com/raiden-network/raiden/blob/ab4784b975cb8a93daeccc4266e7a3aabc587f07/raiden/tests/integration/test_matrix_transport.py#L392-L490))

## Tests to write

- Hanging transfers (#3123)
  - [x] Test the invite works on the happy path (both users online):
  - [x] Test the invite works on the unhappy paths:
    - [x] Both nodes open an invite at the same time
    - [x] The node which is being invited is offline at the time of the invite
    - [x] The node which does the invite goes offline and the invited node comes back online

- User roaming
  - [x] Write test that ensures users switching servers are handled correctly
    - [x] User A uses server X and performs a transfer with User B.
    - [x] User A uses server Y and performs a transfer with User B.
    - [x] User A comes back to server X  and performs a transfer with User B.
    - [ ] Repeat for both users roaming across servers

- Account data update (#2779)
  - [ ] Test that a *single* update to account data are stored in the matrix server
  - [ ] Test the *single* update is recovered on restarts
  - [ ] Test that concurrent updates don't race, and that the latest one will be respected and loaded on the following restart (we need a definition of order here, @andrevmatos @ulope ?)

- Misbehaving servers
  - [ ] Test that the transport can cope with misbehaving servers (e.g. HTTP codes 4xx, 5xx). The client should either catch such errors and retry the operation or crash with descriptive error

- Retries
  - [ ] Write tests that ensure retries work correctly even after re-starting and also with roaming users (see above)

**Comment by hackaugusto** [comment]
We need tests for the invitation system to avoid problems like https://github.com/raiden-network/raiden/pull/3123:

- [ ] Test the invite works on the happy path (both users online):
- [ ] Test the invite works on the unhappy paths:
  - [ ] Both nodes open an invite at the same time
  - [ ] The node which is being invited is offline at the time of the invite
  - [ ] The node which does the invite goes offline and the invited node comes back online

@ulope would the above catch the problem from #3123 ?

**Comment by hackaugusto** [comment]
We also need tests for hanging transfers, issue #2779 . From what I gathered the tests is for concurrent updates to account data

- [ ] Test that a *single* update to account data are stored in the matrix server
- [ ] Test the *single* update is recovered on restarts
- [ ] Test that concurrent updates don't race, and that the latest one will be respected and loaded on the following restart (we need a definition of order here, @andrevmatos @ulope ?)

**Comment by ulope** [comment]
@hackaugusto I pulled your suggested tests into the issue description

**Comment by palango** [comment]
@ulope I think you worked a lot on testing more. Can this be closed or should it be left open?

**Comment by LefterisJP** [comment]
Let's just close it, since this has been open a long time and has no specific coverage target.

@ulope what you think?
