### ISSUE TITLE
Rename Secret message into Unlock to agree with the spec

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#3132]
## Problem Definition

In the spec we call the message that is sent to our payer partner [Unlock](https://github.com/raiden-network/spec/blob/379dbe6f2c2ac8495e0ba41bc917fe1834bc73d7/messaging.rst#unlock). In the code we call it [Secret](https://github.com/raiden-network/raiden/blob/38971b372dafb3205cbd3df8cfc3306922a55eac/raiden/messages.py#L557).

This inconsistency causes headaches to all new hires or people who look into the code. We should get rid of it.

## Task

- [ ] Rename the Secret class in the code and everywhere else the "Secret" is used to mean the "Unlock" message of the spec into "Unlock".

**Comment by pirapira** [comment]
This breaks the backward compatibility of Matrix messages https://github.com/raiden-network/raiden/pull/3145#issuecomment-451108904 .  So I'm not working on this now.

**Comment by hackaugusto** [comment]
Just a note, the name used in the [`type` for the Secret message](https://github.com/raiden-network/raiden/blob/1466689bd21bf7a4e285784bc502b3620fdc44ba/raiden/messages.py#L674) can be a hard coded string, the class and it's usage in the code base can be renamed.
