### ISSUE TITLE
Specify the state machines

### ISSUE THREAD

**Issue by pirapira** [raiden-network/raiden#3160]
This issue keeps track of writing a specification of the state machines in the client implementation.  The spec will be useful for writing unit tests and keeping track of the test coverage.  The spec will live in `raiden` repository rather than `spec` repository because it is about this particulr implementation (I discussed this with @LefterisJP ).

The first task is to write a sample specification for one state change on one state.  After getting some feedback on that, the spec can be extended to cover one state machine.

**Comment by christianbrb** [comment]
Closed via #4711
