### ISSUE TITLE
UDP transport does not seem to retry messages until processed

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#3185]
While working on the [refund transfer test](https://github.com/raiden-network/raiden/blob/621963ec483cb6ef29d501b3bce8515da254c280/raiden/tests/integration/transfer/test_refundtransfer.py#L110) I [mocked](https://github.com/raiden-network/raiden/blob/621963ec483cb6ef29d501b3bce8515da254c280/raiden/tests/integration/transfer/test_refundtransfer.py#L221) the non-processing of a LockedExpired message.

This worked fine with the matrix transport but I noticed problems with UDP. It is my understanding that all messages that include a Balance Proof, including `LockExpired`, have to be retried until a `Processed` message for that message is received. This is how the process is also [documented](https://raiden-network.readthedocs.io/en/latest/onboarding.html#messages-acknowledgment-and-processing) in our development guide.

The above works as expected with Matrix. They [use](https://github.com/raiden-network/raiden/blob/621963ec483cb6ef29d501b3bce8515da254c280/raiden/network/transport/matrix.py#L217) the `_queueids_to_queues` structure to get the different types of queues and check if the message is still in the queue before retrying. Whenever we received a `Delivered`, if the message we received it for belongs in the global queue (iow, is not a BP message) we remove it from the queue:

https://github.com/raiden-network/raiden/blob/621963ec483cb6ef29d501b3bce8515da254c280/raiden/transfer/node.py#L534-L538

And for processed if the message we received the Processed for was in the queue we delete it.

https://github.com/raiden-network/raiden/blob/621963ec483cb6ef29d501b3bce8515da254c280/raiden/transfer/node.py#L711-L720

So far so good.

But UDP won't do any of this. Its retry mechanism only waits for `Delivered`:

https://github.com/raiden-network/raiden/blob/621963ec483cb6ef29d501b3bce8515da254c280/raiden/network/transport/udp/udp_utils.py#L72-L121

The `AsyncResult` we wait for is stored in `messageids_to_asyncresults` and whenever udp receives a `Delivered` the corresponding `AsyncResult` is set to true:

https://github.com/raiden-network/raiden/blob/621963ec483cb6ef29d501b3bce8515da254c280/raiden/network/transport/udp/udp_transport.py#L552-L573

---

So the problem is that we have inconsistent behaviour in the retry mechanism between Matrix and UDP.

**Comment by hackaugusto** [comment]
Anything else for this issue? [retries are literally](https://github.com/raiden-network/raiden/blob/621963ec483cb6ef29d501b3bce8515da254c280/raiden/network/transport/udp/udp_transport.py#L130-L139) the only way UDP sends messages (however this does not mean there are no bugs)

**Comment by LefterisJP** [comment]
@hackaugusto yes. I updated the description to give proper context.

**Comment by andrevmatos** [comment]
4th point of #3252 proposes a specific interface for that, with an interface equivalent to `send_async(queue, message)`: `stop_retry(queue, message)`. It should be synchronous, and called when the message is removed from the queue (so core should know when to give up retrying any message)

**Comment by rakanalh** [comment]
UDP transport was removed. Closing
