### ISSUE TITLE
Raiden is slow on slow hardware

### ISSUE THREAD

**Issue by eorituz** [raiden-network/raiden#3199]
## Abstract
Raiden tx from a [raspberry pi zero ](https://de.wikipedia.org/wiki/Raspberry_Pi#Hardware) to an [udoo x86](https://shop.udoo.org/x86/udoo-x86-ultra.html) takes extremly long.
If the Udoo runs 6 Raiden nodes and the Pi zero 1 it takes 45-75s to complete a Tx (almost independent of the number of hops.

# Plot
I tested a transaction from the pi zero (pi@raspberrypi) to the udoo (train@demo) with only one raiden node running on each machine (it was ofc a direct transfer). It took ~40s to complete the transfer. Checkout the video to see what I did in particular.

## Specification
Used Raiden version 0.18.1 
Raspian on the RPi
Ubuntu 18.04 on the Udoo

# Logs
(Tx started at ~13:51 GMT)
[raspberry_sender.log](https://github.com/raiden-network/raiden/files/2703007/raspberry_sender.log)
[udoo_receiver.log](https://github.com/raiden-network/raiden/files/2703008/udoo_receiver.log)

# Video
A short video of what I did, including memory usage of Pi 
https://drive.google.com/file/d/1K1l0oIx8IGBM0Tp45IFCkKj-lLIBEg_B/view?usp=sharing

**Comment by hackaugusto** [comment]
Related: https://github.com/raiden-network/raiden/issues/61

**Comment by christianbrb** [comment]
Available in ReadTheDocs: https://raiden-network.readthedocs.io/en/latest/overview_and_guide.html#raspberry-pi

Closing...

**Comment by eorituz** [comment]
Ulo and I suspect, that the long transaction time is caused by the EC recover function, which needs to be done for every received message.

**Comment by palango** [comment]
> Ulo and I suspect, that the long transaction time is caused by the EC recover function, which needs to be done for every received message.

Is there something we can do in that case? The crypto-code should already be native code. @ulope

**Comment by karlb** [comment]
I assume the performance on the pi is much better today. @ezdac since you do some testing on this, please reopen if this is not the case.
