### ISSUE TITLE
AppImage unavailable from GitHub Releases

### ISSUE THREAD

**Issue by probonopd** [raiden-network/raiden#3209]
The documentation says there is an [AppImage](https://appimage.org/), yet this is unavailable from GitHub Releases:
https://github.com/raiden-network/raiden/releases/

Please do provide an AppImage for download. Thanks.

**Comment by ulope** [comment]
Hi @probonopd,

We no longer offer AppImage bundles. Instead we now distribute self contained binaries (created with PyInstaller) for Linux and macOS (which you can find on the releases page).

AFAIK we removed mention of AppImage from the docs. Please link to where you found it so we can fix that.

**Comment by probonopd** [comment]
Why are you preferring self contained binaries (created with PyInstaller) for Linux?

Providing an [AppImage](http://appimage.org/) would have, among others, these advantages:
- Applications packaged as an AppImage can run on many distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
- One app = one file = super simple for users: just download one AppImage file, [make it executable](http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80), and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Works out of the box, no installation of runtimes needed
- Optional desktop integration with `appimaged`
- Optional binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can optionally GPG2-sign your AppImages (inside the file)
- Works on Live ISOs
- Can use the same AppImages when dual-booting multiple distributions
- Can be listed in the [AppImageHub](https://appimage.github.io/apps) central directory of available AppImages
- Can double as a self-extracting compressed archive with the `--appimage-extract` parameter
- No repositories needed. Suitable/optimized for air-gapped (offline) machines

**Comment by ulope** [comment]
Almost all of these should be true for the binaries we have as well (minus the AppImage specific ones, like the catalog, obviously).

The binaries are intended to be runnable on any “modern” distribution without any further dependencies (except an ethereum node of course). If that isn’t the case please open a separate issue.

We prefer PyInstaller mainly because:
- identical process for Linux and Mac (and windows possibly in the future)
- bundle download size is about a quarter of the AppImage one

**Comment by probonopd** [comment]
> bundle download size is about a quarter of the AppImage one

Well, then you are bundling different things. Think of an AppImage like a self-mounting filesystem image. You can put inside what you decide to. Just like with a self-extracting binary. You could probably even put the exact same binaries inside that you are distributing now, hence, combining the advantages of your current process with the advantages of AppImage.
