### ISSUE TITLE
invalid command 'compile_webui'

### ISSUE THREAD

**Issue by MysticRyuujin** [raiden-network/raiden#3210]
I'm following along with the [official instructions](https://raiden-network.readthedocs.io/en/stable/webui_tutorial.html) for installation and setup and I'm getting the error `invalid command 'compile_webui'` when trying to setup the WebUI?

```
root@geth01:/raiden# uname -a
Linux geth01 4.15.0-43-generic #46-Ubuntu SMP Thu Dec 6 14:45:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

root@geth01:/raiden# git pull
Already up to date.

root@geth01:/raiden# npm -v
6.5.0

root@geth01:/raiden# node -v
v8.10.0

root@geth01:/raiden# python -V
Python 3.6.7

root@geth01:/raiden# ls -al setup.py
-rwxr-xr-x 1 root root 1967 Dec 31 18:30 setup.py

root@geth01:/raiden# python setup.py compile_webui
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: invalid command 'compile_webui'
```

I pretty much just followed the instructions [here too](https://raiden-network.readthedocs.io/en/latest/overview_and_guide.html) including dependencies

```
apt-get install solc
apt-get install build-essential automake pkg-config libtool libffi-dev libgmp-dev
cd /
git clone https://github.com/raiden-network/raiden.git
cd raiden
pip install -c constraints.txt --upgrade -r requirements-dev.txt
python setup.py develop
```

**Comment by LefterisJP** [comment]
@kelsos the webui tutorial should be updated. Can you handle it?

@MysticRyuujin I think that you can just download the latest binary and use that as is. Don't try unstable versions (like latest master). The binary should include the webui.

**Comment by MysticRyuujin** [comment]
@LefterisJP as in I can download, extract, and run the binary from the release page and it automatically runs the WebUI?

**Comment by LefterisJP** [comment]
yep! The guide you are following is for development and it's horribly outdated. The webui is no longer part of the client but an external dependency that is pulled.
