### ISSUE TITLE
Client will crash if coming online right after partner closes channel

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#3216]
## Problem Definition

I discovered this issue while working on finalizing [this](https://github.com/raiden-network/raiden/blob/8ead49a8ee688691c98828a879d93f822f60ae53/raiden/tests/integration/transfer/test_refundtransfer.py#L287) test.

Let's say we have 2 nodes `A` and `B`, and `A` goes offline. Then `B` closes the channel. Once that is done `A` comes back online.

During the node's startup process it will perform the first run of the alarm task:

https://github.com/raiden-network/raiden/blob/8ead49a8ee688691c98828a879d93f822f60ae53/raiden/raiden_service.py#L361-L362

In there it will poll all missed blockchain events, see the ChannelClosed:

https://github.com/raiden-network/raiden/blob/8ead49a8ee688691c98828a879d93f822f60ae53/raiden/blockchain_events_handler.py#L188-L198

process it and emit a `ContractSendChannelUpdateTransfer` event which will eventually end up making and polling a transaction to call `UpdateNonClosingBalanceProof()` in the contract.

So far all is good.

The problem comes right after getting out of the alarm task first run when we initialize the transaction queues.

https://github.com/raiden-network/raiden/blob/8ead49a8ee688691c98828a879d93f822f60ae53/raiden/raiden_service.py#L366-L367

Inside the `pending transactions` there is a `ContractSendChannelUpdateTransfer` which will cause us to resend the transaction to `updateNonClosingBalanceProof` and crash with a `TransactionThrew`.

https://github.com/raiden-network/raiden/blob/8ead49a8ee688691c98828a879d93f822f60ae53/raiden/raiden_service.py#L585-L610

This happens because at the end of every state change we got the `update_queues()` function seen below.

https://github.com/raiden-network/raiden/blob/8ead49a8ee688691c98828a879d93f822f60ae53/raiden/transfer/node.py#L1106-L1123

After any `ContractSendEvent` we add it to the pending transactions. Normally this gets cleared up in the next block/s if we get a `ContractReceiveStateChange` that invalidates the pending transaction. 
But in the case of the client startup there is no time between `self.alarm.first_run(last_log_block_number)` and `self._initialize_transactions_queues(chain_state)` to do so. Thus the transaction is sent two times and leads to a crash.

This is **not** a critical issue because in the next (or one of the next) restart/s after the crash we will see the `ContractReceiveUpdateTransfer` state change which will invalidate the pending transaction and allow us to proceed without crashing again.

## Task

- [ ] Somehow clear the pending transactions between `self.alarm.first_run(last_log_block_number)` and `self._initialize_transactions_queues(chain_state)`
- [ ] Test will be covered by the currently skipped test that prompted the finding of this issue.

**Comment by hackaugusto** [comment]
> But in the case of the client startup there is no time between self.alarm.first_run(last_log_block_number) and self._initialize_transactions_queues(chain_state) to do so. Thus the transaction is sent two times and leads to a crash.

This does not make sense to me, `first_run` is blocking exactly to make sure it will have polled all events from the blockchain before proceeding:

https://github.com/raiden-network/raiden/blob/8f1767797d63e894429bb6f398483c5925cccf7f/raiden/tasks.py#L160-L161

The added code:

https://github.com/raiden-network/raiden/blob/8f1767797d63e894429bb6f398483c5925cccf7f/raiden/tasks.py#L179-L184

Will either use the same block or one higher, using the same block must be a noop (otherwise we have another bug lingering in there), and using a higher block will just poll events from this new block (an expected race condition).

Without the logs it's hard to say, but couldn't it be the first transaction was sent on the first run?

**Comment by LefterisJP** [comment]
> This does not make sense to me, first_run is blocking exactly to make sure it will have polled all events from the blockchain before proceeding:

It's very easy to reproduce this error with the test there.

Apply the following diff which essentially removes the change that fixes this PR and add a pdb breakpoint in the case where we detect a repeating `updateNonClosingBalanceProof()` call. Since this issue I made the change to not even try to send the `updateNonClosingBalanceProof` transaction if the onchain nonce is already updated.

```diff
diff --git a/raiden/network/proxies/token_network.py b/raiden/network/proxies/token_network.py
index 7cd25dde..8261a76e 100644
--- a/raiden/network/proxies/token_network.py
+++ b/raiden/network/proxies/token_network.py
@@ -1230,6 +1230,8 @@ class TokenNetwork:
             partner=self.node_address,
         )
         if closer_details.nonce == update_nonce:
+            import pdb
+            pdb.set_trace()
             msg = (
                 'updateNonClosingBalanceProof transaction has already '
                 'been mined and updated the channel succesfully.'
diff --git a/raiden/tasks.py b/raiden/tasks.py
index afdca2ca..4ef6f230 100644
--- a/raiden/tasks.py
+++ b/raiden/tasks.py
@@ -180,8 +180,8 @@ class AlarmTask(Runnable):
         # clear pending transactions after the chain syncing during
         # the first run of the alarm task.
         # https://github.com/raiden-network/raiden/issues/3216
-        latest_block = self.chain.get_block(block_identifier='latest')
-        self._maybe_run_callbacks(latest_block)
+        # latest_block = self.chain.get_block(block_identifier='latest')
+        # self._maybe_run_callbacks(latest_block)
 
     def _maybe_run_callbacks(self, latest_block):
         """ Run the callbacks if there is at least one new block.
```

The pdb breakpoint will hit.

This happens since the last blockchain event that the first run of the alarm task will get would have been the `ChannelClosed` as I explained in the initial [post](https://github.com/raiden-network/raiden/issues/3216#issue-395232862).

It willl process it and generate the `ContractSendChannelUpdateTransfer` event which will be processed by the event handler and send the `updateNonClosingBalanceProofTransaction`.

The problem is in the that inside the pending transactions there is a `ContractSendChannelUpdateTransfer` which will cause us to resend the transaction to `updateNonClosingBalanceProof`. That would have normally been cleaned by an `update_queues()` calls as explained in the first post and which is why I added another poll of the latest block.

**Comment by hackaugusto** [comment]
Hummm, I see, the events produced from the alarm task are being processed. That was supposed to be prevented by this (introduced by d6d36e91230ab430c7c779f07e2291aa38ecc339 through https://github.com/raiden-network/raiden/pull/2099):

https://github.com/raiden-network/raiden/blob/9800e629e0dc451b2ddbe2e04816aa2f9ddca197/raiden/raiden_service.py#L487-L488

However it looks like the code never worked. Your fix is not sufficient, it worked for your test because the second call happened to see a new block with the transaction mined, but this can easily break:

- the block in which the channel was closed could have been polled in the second call, then the second transaction would be sent anyways
- the transaction sent from either poll could take longer to be mined, and the second transaction would be sent anyways

**Comment by LefterisJP** [comment]
> it worked because the second call raised a recoverable error:

No that's not it. The second call was initially raising a `TransactionRaised` error when I wrote the test and reproduced this behaviour. Only after this commit [here](https://github.com/raiden-network/raiden/pull/3218/commits/ffbfd7c6165cfe52445ac389f68f4494309a1932) did it start raising a `RecoverableError`. The fix worked even before it. You can reproduce by removing the `RecoverableErrror`.

But looking at the code again there is probably still some timing problems that can happen there. Because the second block callback that I added as a fix could still poll new blockchain events, that may trigger the same behaviour just later (e.g. if the transaction is mined later). I think this is also what your second bullet point says above.

> Hummm, I see, the events produced from the alarm task are being processed. That was supposed to be prevented by this (introduced by d6d36e9 through #2099):

This is very valuable input! So the original intention was to **not** process events from state changes at the alarm tasks's first run? This makes sense and explains the existence of `dispatch_events_lock` better.
