### ISSUE TITLE
An `updateNonClosingBalanceProof` is sent even if channel is already updated.

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#3217]
## Problem Definition

This is related to https://github.com/raiden-network/raiden/issues/3216

As seen in #3216 we may end up resending the `updateNonClosingBalanceProof` transaction while the channel has already been updated to the latest nonce. Or even better when we have monitoring services perhaps the monitoring service already acted and we don't need to do anything.

If that happens the transaction will throw and we will get in this part of the code:

https://github.com/raiden-network/raiden/blob/8ead49a8ee688691c98828a879d93f822f60ae53/raiden/network/proxies/token_network.py#L827-L850

which will just tell us that the transaction threw without any more information and crash the client.

We can do better.

## Task

- [ ] Query the contract for the closing participant's latest nonce. If that nonce is the same as the one we got in our partner's state and the one we are about to send to the contract then don't send the transaction.
- [ ] If the `updateNonClosingBalanceProof()` fails then make the same check and if the nonce is already properly set then that means that someone else updated the closer's state while our transaction was in flight.

**Comment by hackaugusto** [comment]
I wonder if this only happened because we processed the send unlock twice (once for the `alarm.first_run` and another from `_initialize_transactions_queues`), or if we *also* have a problem with the clearing of the queue.
