### ISSUE TITLE
Test the initiator state machine

### ISSUE THREAD

**Issue by czepluch** [raiden-network/raiden#322]
**Estimate for sprint 2:** 5

**Comment by konradkonrad** [comment]
Implemented through the following commits (part of #266):
c4e1c2e27a0a5268d6af3d2a1c5d74aa6ac28a79
c0f8864d267b6840d7440cf067cd82a4096cb226
7153e2c413d40e15e223bb1c3b6d1f6348871fc1
885372e6855002e266e594bf894c6f0128d2c772
2a4565ff3a763e8725ab5e1813816aac6ae812d9
7f12184af92c87e8e885afbb759a6af4a75e54de
38d7b994fe563d1edd609d58ef661196f627a8d7
5bc8b300ad91682b897a927381353f157e76a926
047c63ffe5d9b3fa657e5b5d18bd9a21b64dff5c
d1f60105d41dd84aa6548a0a9781f5c5372abd8b

**Comment by LefterisJP** [comment]
If this is implemented can we close this issue?

**Comment by konradkonrad** [comment]
I'll close this, it is part of #266
