### ISSUE TITLE
Token networks & channels are not shown for Kovan, production (limits enabled)

### ISSUE THREAD

**Issue by loredanacirstea** [raiden-network/raiden#3234]
Opened this in the webui repo initially: https://github.com/raiden-network/webui/issues/42, but it seems a Raiden client API issue.

The production version (limits enabled) webui & Raiden API don't not show any token networks or channels for the Kovan network.
Even after I created a channel & deposited tokens in it by using the Raiden API directly, the channel did not show up in the webui nor APi route.

For Mainnet & Ropsten it works correctly.

- `/api/v1/channels` response is `[]`, even though I have a channel opened: https://kovan.etherscan.io/tx/0x797d9b0e104c59f8cd0c4b168688124836fa4793dec9d0b571fa9ab5375a28b4 . My Raiden node address is `0xbC682A384c48D3bBF6e25Cb10F448F73601B6259`
- `/api/v1/tokens` response is `[]`

**Comment by LefterisJP** [comment]
I tried to reproduce this by:

1. Opening the vpn to our parity kovan node
2. Connecting to it by running raiden with: `python -m raiden --keystore-path /path/to/keystore --log-config "raiden:DEBUG" --network-id kovan --eth-rpc-endpoint http://ourparitynodeurl.com --accept-disclaimer --environment-type production --rpc`
3. Querying the tokens via the Rest API:
```
$ http http://localhost:5001/api/v1/tokens                                                                                                                                                                                       

HTTP/1.1 200 OK
Content-Length: 46
Content-Type: application/json
Date: Tue, 08 Jan 2019 08:16:52 GMT
mimetype: application/json

[
    "0xd0A1E359811322d97991E03f863a0C30C2cF029C"
]
```

But as you can see it works as expected. We are missing something so I will need the following information:


1. The exact version of raiden you are running?
2. The command with which you started raiden?
3. The eth node version and type (parity/geth)
4. Debug logs

**Comment by Dominik1999** [comment]
Do we need to solve this issue now?

**Comment by LefterisJP** [comment]
We need someone else to try and reproduce it. If it 's not reproducible we can close.
