### ISSUE TITLE
MS needs a public Matrix room to receive balance proofs / monitoring requests

### ISSUE THREAD

**Issue by Dominik1999** [raiden-network/raiden#3243]
As discussed in the call 08.01.19:
# Summary
- Monitoring services need a public matrix room. The initial implementation should use the same mechanism that is used for the Raiden client discovery room.
- Goal is for Raiden Nodes to publish their blinded balance proofs together with a proposed monitoring fee (monitor request) into that room
- Monitoring services can pick up these messages and on that basis monitor specific channels
- Room joining / creation algorithm should work analogous to the Raiden client discovery matrix room 
- Format of the published monitor requests will be JSON
- Raiden client Nodes should only post into that room and not listen

# To Dos:

- [ ] Refactor server selection and federated room setup code out of `MatrixTransport` into a reusable utility: #3291 
- [ ] Set up call KW 3 to explain the matrix client in more detail @Dominik1999

**Comment by ulope** [comment]
@Dominik1999 I moved this issue here since the `raiden-transport` repo is used for the Synapse server configuration setup we provide to the community.

**Comment by ulope** [comment]
This is solved for now via #3291.
