### ISSUE TITLE
Monorepo config for CircleCI

### ISSUE THREAD

**Issue by karlb** [raiden-network/raiden#3260]
After the discussion in https://github.com/raiden-network/team/issues/227, I tried to move towards to monorepo approach in https://github.com/raiden-network/raiden/pull/3255. For a monorepo to be realistic we need an appropriate CI configuration which does not execute all jobs/workflows on every commit but instead checks which projects are affected by the change.

CircleCI has no official support for monorepos yet, but it's the most popular planned feature (https://circleci.com/ideas/?idea=CCI-I-208). A good workaround would be to check in each workflow if the project is affected and skip the workflow if it is not. Unfortunately, this is also not supported (see https://circleci.com/ideas/?idea=CCI-I-208).

Other approaches are
* checking in every single job and then skipping the job if intended (but still executing all followup jobs and checking there, again)
* checking for changes in the default job and triggering the matching jobs via the HTTP API (https://medium.com/@reuvenharrison/using-circleci-with-monorepos-c04b03f9f39c), which only works with jobs, not workflows AFAICS

Both of these seem unattractive. Better suggestions wanted!

**Comment by jomuel** [comment]
Another idea that came up in the discussion was to use commit tags like `[ci contracts]`, `[ci pathfinding]` etc. to mark which part of the monorepo build should be triggered. However, since CircleCI does not support these tags well, so we would probably end up manually parsing commit messages and then again skipping single jobs.

On top of that, the tag approach would be errorprone. If we avoid auto-detecting changes we will have to check manually in each pr review that all relevant parts of the monorepo build were executed. 

So far it looks like starting every job and then conditionally skipping it is the best workaround.

**Comment by karlb** [comment]
I asked the support for suggestions on this issue to make sure that we're not missing anything. Here's the response:

> At this moment there is no first class support for monorepos. However, this is a heavily requested feature and is now planned for development and release: https://ideas.circleci.com/ideas/CCI-I-208 (However I see that you have already seen this).
>
> This will most likely make use of a newly improved Workflows GraphQL API for Workflows that is currently in soft launch. Mono repo support should be following soon after.
> 
> For the current moment, the "hacks" mentioned are the best solution. I am also in favor of triggering workflows based on git commit message as was suggested in that GitHub issues page. I have heard this once or twice before, and it seems we have a request for this as well: https://ideas.circleci.com/ideas/CCI-I-763

**Comment by ulope** [comment]
There is an ORB that helps with running monorepos on Circle: https://circleci.com/orbs/registry/orb/dnephin/multirepo

It's still kind of a workaround but might be good enough.

**Comment by ulope** [comment]
CircleCI now has support for generating dynamic configurations at runtime: 
https://circleci.com/blog/introducing-dynamic-config-via-setup-workflows/

This would allow us to go ahead with the monorepo concept.

Simple experiment: https://github.com/ulope/circle-setup-wf-test

**Comment by karlb** [comment]
We got used to the current situation and are unlikely to change this. Please reopen if you disagree.
