### ISSUE TITLE
Matrix transport must leave unused rooms

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/raiden#3262]
The logic to leave rooms was disabled as part of a bug fix and needs to be re-enabled. [reference](https://github.com/raiden-network/raiden/pull/3123/files#r239117232)

**Comment by ulope** [comment]
This can only be fixed after we increase test coverage on the transport and have a reliable test that can tell us if we re-introduce hanging transfers.

**Comment by hackaugusto** [comment]
should we have another issue for the test?

**Comment by LefterisJP** [comment]
There is a meta one. Perhaps it can be added there: https://github.com/raiden-network/raiden/issues/3124

**Comment by ulope** [comment]
Will be addressed by #5572

**Comment by karlb** [comment]
We don't use any rooms anymore.
