### ISSUE TITLE
Monitor Requests (blinded balance proofs) must be published into a global matrix room

### ISSUE THREAD

**Issue by Dominik1999** [raiden-network/raiden#3273]
## Monitor Requests must be published to be picked up by Monitoring services

As described in the [Raiden Spec](https://raiden-network-specification.readthedocs.io/en/latest/monitoring_service.html) Monitor Requests will be published into a global Matrix room, see [here](https://github.com/raiden-network/raiden/issues/3243) for Monitoring services to be picked up. Therefore, the Raiden client needs to publish every balance update of its channels in case they should be monitored. 

## Every new balance update will be published as a Monitor Request

Monitor Requests are defined in the [Raiden Spec](https://raiden-network-specification.readthedocs.io/en/latest/monitoring_service.html). These messages will be published and picked up by the Monitoring Services. 

## Specification

For every balance update of a channel the user wants to be monitored, a Monitor Request needs to be published. 

General issue, see [#28](https://github.com/raiden-network/raiden-monitoring-service/issues/28)

Detailed Specification tbd 

## Backwards Compatibility tbd

It is probably backwards compatible.

## Timeline to be met in order to make MS / PFS team happy
- 01.02.2019 (then there will be beer/some surprise for the client team, if we reach that goal)

**Comment by Dominik1999** [comment]
@palango anything to add?

**Comment by rakanalh** [comment]
Tagging @ulope for the transport team to plan accordingly.

**Comment by hackaugusto** [comment]
related https://github.com/raiden-network/raiden/issues/1432

**Comment by Dominik1999** [comment]
Additionally, for that issue to be finished, we would need the client to join the matrix room for Monitor Requests. We will be able to create the room next week, when #3291 is finished. Does that make sense to you?

**Comment by palango** [comment]
With #3374 and #3393 in review let's plan the next steps (client side) here. From my understanding the following steps are necessary.

- Create/Join the monitoring broadcast room as the client. This seems to be as easy as adding it [here](https://github.com/raiden-network/raiden/pull/3393/files#diff-a4a44a402c47ecdb34a60c44d6c065c0R56). We should probably make this conditional on a command line flag like `--enable-ms-broadcasting`.
- Broadcast the BP (with the reward set to 0) every time a new BP from the other participant arrives. A first step might be to subclass the `RaidenEventHandler` and overwrite the handling of `EventPaymentReceivedSuccess` there.

@rakanalh @LefterisJP @konradkonrad @andrevmatos Does this make sense and did I forget anything?

**Comment by andrevmatos** [comment]
@palango I think that should be mostly it. I'd suggest adding a simple `send_global` method to the `MatrixTransport` as a send-and-forget, to send a `Message` to one of the global rooms (received as the suffix string), and then call it from the event handler.

**Comment by palango** [comment]
> I'd suggest adding a simple `send_global` method to the `MatrixTransport` as a send-and-forget

@andrevmatos Can you take care of that?

**Comment by andrevmatos** [comment]
@palango Yes, I'll add the method and make a PR, and you can take from there to finish the PR with the handler bits

**Comment by andrevmatos** [comment]
Matrix functions and methods ready and merged. You can now use `transport.send_global('monitoring', message)` (or whatever name given in `app.config['matrix']['global_rooms']` list) to send messages to this room.

**Comment by rakanalh** [comment]
Closing issue as #3452 was done. Follow up issues will be created if needed.
