### ISSUE TITLE
Discussion of DB migrations solutions

### ISSUE THREAD

**Issue by rakanalh** [raiden-network/raiden#3275]
## Abstract

Having released Red Eyes, users who run Raiden will have a database setup for them in the current version which is 16. This database contains:
1. Snapshots of the chain state
2. state changes
3. events

Some bug fixes / features that are planned to be fixed / implemented might need to do one of 2 things:
1. Change the structure of the database (new columns, rename a column, create a table .. etc)... this is out of scope of this discussion.
2. Change the structure of the data stored inside the database (3 types mentioned above).

For point (2), and in case this happens, we need to implement an upgrade machanism into Raiden that will transform the data from an old structure into the new structure to mirror the code change that happened in either one of states, state changes or events. 

This issue is to kick off a discussion about the problem and potential solutions.

## Potantial Solutions

Following the discussion that took place on PR: #3227, the proposed solutions are as follows. Notice that i break down the solutions into multiple sections as each describes a specific problem that the section should resolve

### Loading migrations

Options are:
1. Declare a list of hard coded migrations, such that:
```
migrations = [
   upgrade_v1,
   upgrade_v2,
   upgrade_v3,
]
```
Where an upgrade manager would have to check the current version and run the migrations starting from the current version and above. An example would be: if a user runs node with version 2, and then upgrades to Raiden version 3,  `upgrade_v3` and above need to be executed.

**Pros**:
- Simple implementation

**Cons**:
- Needs manual modification everytime a migration is introduced.

2. Automatic loading based on convention:

Introduce an upgrade manager which takes the old version and current version, constructs a module path such as: `migrate_v1_to_v2.py` to be loaded and executed. The module has to implement an interface where a function called `upgrade` has to exist in that module.

This is implemented in #3227 PR.

**Pros**:
- When upgrading, the upgrade manager knows if there are any migrations to be executed and executes them.

**Cons**:
- The implementation is slightly more complicated than the previous solution.

### Applying migrations

In case changes happen to the structure of the data classes (events, states and/or state changes):

1. The get methods from the storage would always apply the migrations. So, [get_snapshot_closest_to_state_change](https://github.com/raiden-network/raiden/blob/a468fedc433fa7ffbd4b12c5e63dda3626c19cc0/raiden/storage/sqlite.py#L171) and [get_statechanges_by_identifier](https://github.com/raiden-network/raiden/blob/a468fedc433fa7ffbd4b12c5e63dda3626c19cc0/raiden/storage/sqlite.py#L295) would load the data from the database **and** apply the migrations, once we do the [replay](https://github.com/raiden-network/raiden/blob/a468fedc433fa7ffbd4b12c5e63dda3626c19cc0/raiden/storage/wal.py#L45-L47) all the objects would have the latest version and the state machine doesn't have to worry about it.

**Pros**:
- Fast, as transforming individual items could be instant. 
- They happen once upon restoring data from the database.

**Cons**:
- Assumes that the restore/transform cycle needs to happen once because at some point snapshots will be taken and we'd never have to look at the transformed items again.
- Upgrade checking / execution need to happen every time a call to these functions are made.
- Could leave us with non-transformed data in the database which would prevent us from being able to restore the state from the database without a snapshot.

2. Before Raiden Service is started, upgrade all state changes / events and states but transforming the data and persist them into the database again (update in-place).
For:
a. State changes / events: load  the items using a query into the database and filter by `_type` field, go through each of those items and update their structure accordingly and perform an `UPDATE` statement.
b. for states (chain_state to be specific), load the raw JSON, decode it into a map, transform and store back.

**Pros**:
- Will only run once before anything else.
- Will upgrade the complete database which means that even using the latest version, one will be able to restore the state without relying on the presence of snapshots.

**Cons**:
- Could be time consuming depending on the size of the database.

## Backwards Compatibility

Code changes in states, state changes and event are backward-incompatible unless one of the aforementioned upgrade solutions is implemented.

**Comment by konradkonrad** [comment]
I don't see an option for an explicit `raiden updatedb` command, which I think would be preferable over any automatic migration process on start. So basically:

- implement `updatedb` that migrates the complete db (through either of the proposed upgrade manager schemes), and _after_ successful migration replaces the old db (or rollback in case of an error).
- check the db version in the client code during at the first db connection in the client. In case of a db mismatch exit the client and inform the user of the missing migration.

Pros:
- keeps migration and replay/snapshot logic completely separate.

Cons:
- needs user interaction

For "Loading Migrations", option 1) seems straight forward.

For "Applying Migrations", option 2) is pretty close to my separate command proposal, and if we really want to do it on-line, I would opt for that, as it leads to a complete and consistent (in case migration is sane) db.

**Comment by hackaugusto** [comment]
@konradkonrad If we have a separate command, to upgrade these steps would have to be done in order:

- upgrade software
- stop raiden
- run migration
- start with the new version

If the step is not done then the new version needs to crash (otherwise weird errors would pop-up). Is that what you are proposing?

**Comment by LefterisJP** [comment]
@rakanalh 

For "Loading migrations":

> Pros
> When upgrading, the upgrade manager knows if there are any migrations to be executed and executes them.

Hey @rakanalh I don't understand this as a PRO of the 2nd solution (upgrade manager) for loading migrations. Can you maybe explain? To me the first solution sounds a lot simpler and I don't see any cons for it.

For applying migrations:

I think option 2 would be the way to go. The bigger the DB gets, the more upgrades we do, the more work the getters would have to do it and it may end up being a considerable slowdown. Better go through the pain once and have a consistent DB.


As for @konradkonrad 's suggestion of having a manual upgrade process:

I don't see the benefit. Why require user interaction?  They already interact once by upgrading to latest raiden. Why require user action again? And picture the scenario where the user says, no I won't update. What then? Only case is to crash and tell him to downgrade.

I would opt instead for a very clear message for each new version that upgrades the DB, that if they download and run it, their DB will be upgraded. This is standard practise. Both parity and geth have had DB upgrades like this.

We could have a prompt when raiden starts, warning them a DB upgrade is gonna take place, and if they want it to happen or not and if they don't then crash ..  but I still don't see the point.

**Comment by rakanalh** [comment]
@LefterisJP 
Autoloading for the migrations is explained:
>Introduce an upgrade manager which takes the old version and current version, constructs a module path such as: migrate_v1_to_v2.py to be loaded and executed. The module has to implement an interface where a function called upgrade has to exist in that module.

So basically, the hardcoded list would be an explicit way to say: here is the migration function you need to run between v1 and v2. But with finding and autoloading the migration would be implicit. Creating the migration script file is the only explicit action you need to take for the manager to know if a migration exists for a certain version or not.

> I think option 2 would be the way to go. The bigger the DB gets, the more upgrades we do, the more work the getters would have to do it and it may end up being a considerable slowdown. Better go through the pain once and have a consistent DB.

We agree on this part. Running the migration for X seconds/minutes once rather than running it multiple times during the function calls (which could add up) is what we should implement.

So i guess it's 1 vote (option 2) vs 1 (option 1, voted on by @hackaugusto in #3227).

**Comment by LefterisJP** [comment]
> So basically, the hardcoded list would be an explicit way to say: here is the migration function you need to run between v1 and v2. But with finding and autoloading the migration would be implicit. Creating the migration script file is the only explicit action you need to take for the manager to know if a migration exists for a certain version or not.

I think I get it. So the question is between one big function with `if elif else` and a list of files each containing a single version update script which would be attempted? So end result is pretty much the same, just the list is more well organized. So we want the same thing.

**Comment by konradkonrad** [comment]
@LefterisJP 
> I don't see the benefit. Why require user interaction? They already interact once by upgrading to latest raiden. Why require user action again?

In the PR discussion, the terms "replay" and "on-demand" were thrown around, and with my proposal I want to clearly firewall (the development of) migrations and client startup procedure.
e.g. https://github.com/raiden-network/raiden/pull/3227#discussion_r247558417

Nothing against trying to auto run the `upgradedb` command in case of a `DBVersionMismatchException` during client start up.

**Comment by ulope** [comment]
We should take a few queues from other db migration implementations. 

Basically every tool I've used in the past has had the following properties:

1. **Files are auto-discovered / imported from a well known location**
1. **One file := one version**
1. **Each module exposes functions with well known names (e.g. `upgrade`, `downgrade`).**
1. The database interfacing functionality is either:
    1. Exposed as a single import
    1. **Passed into the migration function as an argument**
1. Which file represents which version is either:
    1. Inferred from the filename (which in this case has to follow a fixed format)
    1. **Given as a module level attribute** (following a well defined naming convention is still a good idea though)
1. Ordering of versions:
    1. **Implicitly, monotonically increasing**
    1. Via a 'parent' or similar attribute
1. Directionality, either:
    1. **Only upgrade**
    1. Up- and downgrade

(I've highlighted the options I'd recommend we take in bold.)

Regarding the 'migrate everything on startup' or performing it ad-hoc while in use I also prefer the on startup method. I don't think however, we should bother the user with manual upgrades.

The following algorithm provides a safe upgrade mechanism without data loss potential:
- Check for partial migration (see below) and abort if found
- Notice we need to migrate
- Copy the previous database to a new file for the current version with a pre- or suffix that marks it as 'in progress'
- Perform the migration on the new file
- Rename new database to final version name

One final question for @rakanalh: You mentioned in the top message that structural changes are out of scope for this issue. Why do you want to exclude them?

**Comment by rakanalh** [comment]
> We should take a few queues from other db migration implementations.
> 
> Basically every tool I've used in the past has had the following properties:
> 
> 1. **Files are auto-discovered / imported from a well known location**
> 2. **One file := one version**
> 3. **Each migration file exposes the same functions with well known names (e.g. `upgrade`, `downgrade`).**
> 4. The database interfacing functionality is either:
>    
>    1. Exposed as a single import
>    2. **Passed into the migration function as an argument**
> 5. Which file represents which version is either:
>    
>    1. Inferred from the filename (which in this case has to follow a fixed format)
>    2. **Given as a module level attribute** (following a well defined naming convention is still a good idea though)
> 6. Ordering of versions:
>    
>    1. **Implicitly, monotonically increasing**
>    2. Via a 'parent' or similar attribute
> 7. Directionality, either:
>    
>    1. **Only upgrade**
>    2. Up- and downgrade
> 
> (I've highlighted the options I'd recommend we take in bold.)
> 

Exactly what's implemented in #3227.

> The following algorithm provides a safe upgrade mechanism without data loss potential:
> 
> * Check for partial migration (see below) and abort if found
> * Notice we need to migrate
> * Copy the previous database to a new file for the current version with a pre- or suffix that marks it as 'in progress'
> * Perform the migration on the new file
> * Rename new database to final version name
> 

The upgrade manager also takes care of this. The backup file is created and restored in case of an upgrade failure.

> One final question for @rakanalh: You mentioned in the top message that structural changes are out of scope for this issue. Why do you want to exclude them?

They could still be done through this migration mechanism through manually writing an `ALTER TABLE` statement... i excluded them because alembic was brought up at some point in time when discussing this but i agree that we can and should use this if we all agree on how it's implemented.

**Comment by rakanalh** [comment]
> So end result is pretty much the same, just the list is more well organized

I disagree... both the "list of migration files" and the list of functions approaches are ways to organize thie migrations. The list approach will make us run ALL migrations regardless of which version you're currently running, by doing this each migration should check if it's upgrading the correct version in that case which is out of it's scope (the caller of the migration should only call the migration when it's needed).

**Comment by rakanalh** [comment]
> For "Loading Migrations", option 1) seems straight forward.

See my comment above. It's easier to implement the list but the added complexity somewhere else is also something to consider.

**Comment by LefterisJP** [comment]
> I disagree... both the "list of migration files" and the list of functions approaches are ways to organize thie migrations. The list approach will make us run ALL migrations regardless of which version you're currently running, by doing this each migration should check if it's upgrading the correct version in that case which is out of it's scope (the caller of the migration should only call the migration when it's needed).

Hmm I may not understand correctly then. Can you perhaps quickly show the different with pseudocode? I think in this case it would be much easier to understand.

**Comment by rakanalh** [comment]
Example of list migrations would be:
```
def migrate_to_2(current_version, old_version):
    if old_version != 1 or current_version != 2:
        return
    # Perform migration here

migrations = [
    upgrade_to_2,
    upgrade_to_3,
    upgrade_to_4,
]

for migration in migrations:
    migration(current_version, old_version)
```

Example of a migration taken from #3227 which implements the single-file-per-migration approach:

https://github.com/raiden-network/raiden/blob/e2727a58b4862ba21aa5d33a57c204e8e79814ab/raiden/utils/migrations/v16_to_v17.py

The upgrade manager:
https://github.com/raiden-network/raiden/blob/e2727a58b4862ba21aa5d33a57c204e8e79814ab/raiden/utils/upgrades.py

**Comment by hackaugusto** [comment]
> The list approach will make us run ALL migrations regardless of which version you're currently running,

I don't understand why this argument is brought up, if you want to compare:

list of functions:
- call each function

list of files:
- needs to call the OS
- glob to pattern match against the filenames
- dynamic load the modules

either way, *both are negligible*

**Comment by rakanalh** [comment]
> I don't understand why this argument is brought up

:smile: you're right... maybe i am biased.

**Comment by hackaugusto** [comment]
> The bigger the DB gets, the more upgrades we do, the more work the getters would have to do it and it may end up being a considerable slowdown. Better go through the pain once and have a consistent DB.

This is also true to applying the migration to all elements, it will be proportional to the number of entries.

**Comment by rakanalh** [comment]
Alright... let's just vote:

#### Autoloading 
:one:: List approach
:two: Dynamic approach

#### Applying migrations:
:three: In getters
:four: During startup

@hackaugusto @konradkonrad @LefterisJP @ulope

**Comment by rakanalh** [comment]
Decision:

1. Create a list of migrations that need to be executed. Each migration should check if the passed versions match the ones this migration is upgrading. If that's the case, the migration becomes a no-op.
2. Run migrations on startup.
