### ISSUE TITLE
Add raiden's fees

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/raiden#33]
- For the initiators
  - [x] Reveal or not the secret, depending on the transfer amount reported by the target.
- For the mediators:
  - [x] Decrease the `lock.amount` equal to it's fee amount
- For the target
  - [x] Inform the initiator how much token the receive transfer (Done with the secret request message)

### Timeline
The PFS team relies on this implementation before it can incorporate fees into its routing algorithms. A basic implementation until mid-March 2019 would be good.

**Comment by LefterisJP** [comment]
I am removing "needs discussion" label @hackaugusto. Since the time this was added we have more or less cleared out how they would work. See loredana's comment above.
