### ISSUE TITLE
CircleCI builds fail at long-running test_secret_revealed test

### ISSUE THREAD

**Issue by jomuel** [raiden-network/raiden#3301]
CircleCI builds are flaky at the moment as one of the tests:

`raiden/tests/integration/long_running/test_integration_events.py::test_secret_revealed[matrix-False-channels_per_node0-3]`

tends to fail with `Too long with no output (exceeded 10m0s)`. The test is not particularly slow when run locally so there seems to be a specific problem (deadlock or something) occurring in CircleCI builds.

Until this is fixed, the test will be skipped (see #3140)

**Comment by LefterisJP** [comment]
Note: This issue is for fixing the test and not just skipping it, I suppose?
