### ISSUE TITLE
Only ask PFS if necessary

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden#3303]
## Abstract

With #3236 Raiden will ask the PFS for a path if the PFS is set. However, this is not necessary for transfers to direct channel partners. In this case the Raiden client shouldn't ask the PFS:

## Motivation

Not doing the request to the PFS will lower costs and increase latency of payments to direct partners.

## Specification

Before asking the PFS the client should check if:
- there is a direct channel to the target
- if this channel is open
- if the channel has enough capacity

If all checks are successful the payment can be sent using this channel.

## Backwards Compatibility

Backwards compatible.

**Comment by BOR4** [comment]
is it possible that due to low capacity in direct channel a payment gets routed via mediated transfer? If yes, is that wanted behaviour?
