### ISSUE TITLE
raiden echonode stopping right away after start

### ISSUE THREAD

**Issue by narcis2007** [raiden-network/raiden#3315]
I try to start the raiden echonode like this and it stops after 2-3 seconds
➜  Raiden ./raiden echonode --token-address 0x7B1Fc0BAA785aBE33e5e601AE2121955C4A6843e
2019-01-23 20:16:34.440333 [info     ] Starting Raiden                [raiden.ui.runners] distribution=bundled python_implementation=CPython python_version=3.6.7 raiden=0.100.1 system=Linux 64bit_ELF 4.15.0-43-generic x86_64
➜  Raiden 

It's the same story if I run ./raiden --keystore-path  ~/.ethereum/keystore --network-id rinkeby --environment-type development --eth-rpc-endpoint https://rinkeby.infura.io/v3/370ca9dbb4db4eb1a2ebcd54ac76023b echonode --token-address 0x7B1Fc0BAA785aBE33e5e601AE2121955C4A6843e

Am I doing something wrong? I'm trying to test a payment in a channel and from the documentation I can only do it in a nice way using the echonode it seems

**Comment by narcis2007** [comment]
https://raiden-network.readthedocs.io/en/stable/api_walkthrough.html#interacting-with-the-raiden-echo-node

"For easy testing of Raiden, there is a specialized Raiden node running, the “Raiden Echo Node”. The Echo Node responds to received payments by sending a payment back to the initiator."

**Comment by narcis2007** [comment]
@LefterisJP Can you tell me how can I test a payment in a channel then?

**Comment by czepluch** [comment]
Hi @narcis2007!

You can run two nodes yourself and open a channel between them. You can start a second node, by simply giving it a flag that point to another api address `--api-address "http://localhost:5002"` and then open a channel with that node. When you start Raiden you should not provide the "echonode" argument.

**Comment by narcis2007** [comment]
That worked to start the second node
I have one more question: will we be able to submit transactions through some sort of light client in the future? (not needing to run a node?)
