### ISSUE TITLE
Move tests outside the application directory

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#3342]
## Problem Definition

[Suggested](https://github.com/raiden-network/raiden/tree/test-review/ob-review#test-layout) to us during our test review. This is probably a nitpick so I also put the "needs discussion" label.

Suggestion is to:

- Move the tests code outside the application directory.
- Organize fixtures as internal plugins rather than a colletion of modules inside the test packages. That would also make it unnecessary to have the test folders as packages
- Use the `/src` (see [article](https://hynek.me/articles/testing-packaging/)) layout.

**Comment by hackaugusto** [comment]
> That would also make it unnecessary to have the test folders as packages

I believe that we have them as a package because of the utils, I don't think the plugin will fix that, and some of these don't really need to live in the raiden code base (e.g. factories)

**Comment by ulope** [comment]
> Move the tests code outside the application directory.

We already went through that cycle once (well almost) ;)

#692 removed the `tests` module from the sdist.
#718 re-introduced it

Here is the only part of chat about this I could find: https://chat.brainbot.com/channel/dev-raiden?msg=Q3dk8Y4eGjAFgx8cX

IIRC schmir's argument was that you might want to run the tests after having installed the package with pip.

If we move the tests outside of the source tree we can't distribute them with the sdist and wheel packages anymore.

**Comment by LefterisJP** [comment]
I don't think this is anything we need to spend time on right now. And in the interest of consolidating our testing plan I would say this should be closed.
