### ISSUE TITLE
Speed up the complete mypy integration

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#3343]
## Problem Definition

[Suggested](https://github.com/raiden-network/raiden/tree/test-review/ob-review#mypy) to us during our test review. 

Suggestion is to:

- Prioritize introduction of types to the entire codebase and enforce it in the CI. (@LefterisJP agrees 100% -- we have recently seen at least 1 [instance](https://github.com/raiden-network/raiden/pull/3331#discussion_r251049195) where mypy would have caught a bug.)
- Perhaps use [pyannotate](https://github.com/dropbox/pyannotate) to do this faster.
- Enforce the same typing standard in the test code. We seem to not use types in the tests.

**Comment by hackaugusto** [comment]
We are not 100% there, but a good chunk of the code base is type annotated. I don't think we need an issue for the remaining since it can be done gradually.
