### ISSUE TITLE
Use fixture's name argument to communicate what fixtures inject into the tests

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#3346]
## Problem Definition

[Suggested](https://github.com/raiden-network/raiden/tree/test-review/ob-review#suggestion-naming-things) to us during our test review. I (@LefterisJP ) am not sure if this would really be useful so I am adding a needs discussion label.

Suggestion is to:

- Utilize the `pytest.fixture()` name argument (check [source](https://docs.pytest.org/en/latest/_modules/_pytest/fixtures.html#fixture)) in order to make what the fixture returns more explicit. Example:
```python
@pytest.fixture(name="db_connection", scope="session")
def create_postgres_db():
    ...
```

**Comment by LefterisJP** [comment]
>  maybe we should just do it for one or two fixtures and see what changes in the reports?

Sure :)

**Comment by hackaugusto** [comment]
okay, one thing that I really think this will help with is this pattern we have:

```python
@pytest.fixture
def f(): pass

def f2(f): pass
```

And pylint complains that `f2`'s first argument is overwriting `f` (rule `redefined-outer-name`), which is quite annoying to me, because that hinder real errors/warnings from the same file.

**Comment by LefterisJP** [comment]
This has been done for some fixtures. It personally did not help me much and I would not push for enforcing this further. To help in consolidating our testing plan I would close this issue.

**Comment by karlb** [comment]
I usually prefer the old way, since it introduces less different names for the same thing. We can still do this in cases where there is a clear benefit, but we don't need to make a coordinated effort. So we don't need this ticket.
