### ISSUE TITLE
Approach for introducing more inside-out tests

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#3349]
## Problem Definition

[Suggested](https://github.com/raiden-network/raiden/tree/test-review/ob-review#how-to-introduce-more-inside-out-tests) to us during our test review. This is a bit tricky as it's good advice but it's hard to separate into concrete action items.

## Suggestion

If an integration test fails, ask yourself what could have been tested on a lower level to catch that problem earlier and write that test(s). Over time there will be a greater coverage of lower levels.

If and when integration tests might be superfluous is a harder question to answer. I prefer to err on the side of testing too much than testing too little for a critical system (or critical part of a system).

Splitting up the system into clear subsystems with clear interfaces makes testing in isolation and direct interaction between them easier and more lightweight.

**Comment by hackaugusto** [comment]
I don't see the point of this issue. What is the task here?

**Comment by LefterisJP** [comment]
@hackaugusto I made the issues as reminders for each of the things that the reviewer comments about.

If something is not directly actionable and is simply good advice, we can see if we want to dedicate time to go through the code and apply it.

If not then perhaps to just add it to the Contributing.MD as general advice for writting tests. I think this issue falls more on this category.

The end result would be to document good practices and good advice somewhere.

**Comment by LefterisJP** [comment]
I thought of adding something to Contributing.MD for this. But then looking at the file we mention the same advice [here](https://github.com/raiden-network/raiden/blob/master/CONTRIBUTING.md#workflow). So I think we can close this issue.
