### ISSUE TITLE
Measure code complexity in functions and perhaps enforce a value in the CI

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#3355]
## Problem Definition

[Suggested](https://github.com/raiden-network/raiden/tree/test-review/ob-review#pylint--flake8) to us during our test review. Added needs discussion as this may be a nitpick and we would need to also discuss the acceptable complexity value.

Suggestion is to:

- Measure the cyclomatic function complexity via `flake8 raiden/ --max-complexity 10` and enforce a particular value. Lower cyclomatic complexity makes for more readable code.

**Comment by LefterisJP** [comment]
I would put this up for discussion in the team. My one remark is that whatever rule we set we should make sure that it's CI and linting enforceable.

**Comment by karlb** [comment]
Results on the current code base don't seem helpful to me. If anyone is interested in this, feel free to reopen.
