### ISSUE TITLE
Use vulture to detect dead code and then remove it

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#3356]
## Problem Definition

[Suggested](https://github.com/raiden-network/raiden/tree/test-review/ob-review#dead-code) to us during our test review. 

Suggestion is to:

- Use the [vulture](https://github.com/jendrikseipp/vulture) tool to detect dead code in the project and remove it.

**Comment by hackaugusto** [comment]
I don't think we need an issue for that. Myself and @pirapira  (https://github.com/raiden-network/raiden/pull/3223) have executed the tool a few times. It's useful but full of false positives.

**Comment by LefterisJP** [comment]
Agreed. I also have used it in the past but found false positives to be a bit annoying. I simply made an issue for everything and then we can decide to close anything not relevant to us.

So the bottom line is we can just use vulture from time to time to see if we can find something but nothing actionable to do at the moment so the issue can be closed.

**Comment by pirapira** [comment]
Let's start building a whitelist?  I know these false positives >> then add them to the white list!

https://pypi.org/project/vulture/
> Handling false positives
> You can add used code that is reported as unused to a Python module and add it to the list of scanned paths. To obtain such a whitelist automatically, pass --make-whitelist to Vulture.
> $ vulture mydir --make-whitelist > whitelist.py
> $ vulture mydir whitelist.py

**Comment by hackaugusto** [comment]
@pirapira I was unaware of this feature, yeah, should be nice :)
