### ISSUE TITLE
Client publishes balance updates to path finding service 

### ISSUE THREAD

**Issue by Dominik1999** [raiden-network/raiden#3364]
## Abstract

The path finding service need to know actual channel balances incl. the transferred amounts. Therefore, clients need to publish current balance proofs with any state change into a global matrix room. Similar to the monitor request provided in #3273 we need a new message provided by the client.

## Specification

Every new state of a channel need to be published into a global matrix room. We can use the [Off-Chain Balance Proof](https://raiden-network-specification.readthedocs.io/en/latest/messaging.html) and publish it into the room. Additionally, we need the current reveal_timeout of that channel to be included in that message (motivation, see [here](https://github.com/raiden-network/raiden-services/issues/5)). 

| Field Name                    | Field Type |  Description                                                                                     |
| -------------------------------  | ------------- | -------------------------------------------------------------------------------------- |
|  nonce                            | uint256     | Monotonically increasing number of balance proofs                       |
|  transferred_amount       | uint256     | Total transferred amount in the history of the channel                   |
|  locked_amount              | uint256     | Current locked amount                                                                   |
|  locksroot                        | bytes32     | Root of the merkle tree of lock hashes (see below)                      |
| token_network_identifier | address   | Address of the TokenNetwork contract                                           |
|  channel_identifier           | uint256    | Channel identifier inside the TokenNetwork contract                      |
|  message_hash               | bytes32   | Hash of the message                                                                      |
|  signature                         | bytes       | Elliptic Curve 256k1 signature on the above data                          |
|  chain_id                          | uint256    | Chain identifier as defined in EIP155                                             |
|  reveal_timeout                | uint256    | Time to wait for a payment to conclude before going on chain      |

## Backwards Compatibility

It is backwards compatible.

**Comment by rakanalh** [comment]
@Dominik1999 is this different than: https://github.com/raiden-network/raiden/issues/3273 or is it a duplicate?

**Comment by palango** [comment]
@rakanalh This are the BP updates for the PFS, which are not blinded

**Comment by Dominik1999** [comment]
@rakanalh this is different. 

- #3273 provides the Monitor Request (incl. a fee) for the Monitoring Service
- This requests is about balance updates (incl. reveal_timeout) for the path finding service

The implementation should be pretty similar from what I understand

**Comment by konradkonrad** [comment]
talked to @rakanalh, he suggested
- this needs to only send "copies" of the balance proofs that we **send** to our partner -- @palango can you confirm?
- we can intercept the to-be-send balance proof in the event handler on `Send*` events

**Comment by err508** [comment]
@konradkonrad Please have a look [here](https://github.com/raiden-network/team/issues/326), especially second case, there's a call scheduled for Monday to evaluate this with RSB team.

**Comment by konradkonrad** [comment]
closed by #3477
