### ISSUE TITLE
Increased CPU usage when the node is idle.

### ISSUE THREAD

**Issue by kelsos** [raiden-network/raiden#3369]
## Problem Definition

As idle state I consider the state where the node is not actively sending, receiving or mediating transfers. At this state I mostly receives blocks. 

![image](https://user-images.githubusercontent.com/2269732/52046144-537ab580-2546-11e9-91b8-f49c849df5e4.png)

At this state the CPU usage is constantly at 70-80% of a single core. 
If the same node is started on v0.100.1 instead of master, then the CPU usage at this state usually around 1-3%.

On the latest master the flamegraph of the client on this state looks like this:
![image](https://user-images.githubusercontent.com/2269732/52046783-dc462100-2547-11e9-9267-ed7091b29644.png)

This behavior appears to started somewhere after the v0.100.1 tag and before the v0.100.2-rc1.

I will continue investigating to see if I can provide more information that could be of help.

### System Description

Here add a detailed description of your system, e.g. output of the following script:

```
Linux forseti 4.20.5-arch1-1-ARCH #1 SMP PREEMPT Sat Jan 26 12:59:18 UTC 2019 x86_64 GNU/Linux
/usr/bin/solc
solc, the solidity compiler commandline interface
Version: 0.5.2+commit.1df8f40c.Linux.g++
/usr/bin/geth
Geth
Version: 1.8.21-stable
Git Commit: 9dc5d1a915ac0e0bd8429d6ac41df50eec91de5f
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.11.4
Operating System: linux
GOPATH=
GOROOT=/usr/lib/go
/usr/bin/parity
Parity Ethereum
  version Parity-Ethereum/v2.2.7-stable-b00a21f39a-20190115/x86_64-linux-gnu/rustc1.31.1
Copyright 2015-2018 Parity Technologies (UK) Ltd.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

By Wood/Paronyan/Kotewicz/Drwięga/Volf
   Habermeier/Czaban/Greeff/Gotchac/Redmann

d21098203f7ffecb286ee231e76b07d6101717a4

```

**Comment by LefterisJP** [comment]
When we discussed together in the morning @kelsos said he bisected and provided the following.

> 990a20c0c9fa9b4def07428162ddbe90be5b8bfd bad
> 5eddbe43d93001bfbad01dc5e38808f8cdd9be0b good

So I looked at the commits in between with 
```
git rev-list 5eddbe43d93001bfbad01dc5e38808f8cdd9be0b..990a20c0c9fa9b4def07428162ddbe90be5b8bfd

990a20c0c9fa9b4def07428162ddbe90be5b8bfd
fb2f1c979fbccd3ec5f33f9a3ae6d5a181fa9ceb
567e7818aad2f2cf2e712d10b24b4c70360cf74f
cc7585001360f5070a7f172d54dfc1bf49432a4f
63777fecb8e93c00535d3f9416e660b3d05c8aec
7e6dd0fd11aca00871556e1cdfa926fb2de415fa
ffbfd7c6165cfe52445ac389f68f4494309a1932
59c2ae665542e836ce06c8319be2334d62a43d3c
```


990a20c0c9fa9b4def07428162ddbe90be5b8bfd
fb2f1c979fbccd3ec5f33f9a3ae6d5a181fa9ceb
567e7818aad2f2cf2e712d10b24b4c70360cf74f
cc7585001360f5070a7f172d54dfc1bf49432a4f
63777fecb8e93c00535d3f9416e660b3d05c8aec
7e6dd0fd11aca00871556e1cdfa926fb2de415fa
ffbfd7c6165cfe52445ac389f68f4494309a1932
59c2ae665542e836ce06c8319be2334d62a43d3c


From those commits, one thing that could affect performance is the [extra alarm](https://github.com/raiden-network/raiden/pull/3218/files#diff-47f574997fd6a3b54c548636aa8df63bR179) call. But this is already removed in latest master so I don't think it's related.

I will keep looking.

**Comment by LefterisJP** [comment]
And for me in latest master when the node is idle and is running with the following command:

> python -m raiden --keystore-path ~/.ethereum/testnet/keystore --log-config "raiden:DEBUG" --network-id kovan --eth-rpc-endpoint http://parity.kovan.ethnodes.brainbot.com:8545 --accept-disclaimer --environment-type development --rpc

I get a steady 15-17% CPU usage. @kelsos How do you run the client?

**Comment by kelsos** [comment]
So I am doing some different tests now to get more information.
Apparently on kovan the CPU usage jumps from 2-3% (v0.100.1) on idle to 16-20% on latest master.

What seems to make matters really bad is the combination of the CPU increase with a private chain setup (the block time doesn't seem to really matter I tried both 5seconds and 15seconds there was no change).

I start the client like this. 

```
/home/kelsos/.virtualenvs/raiden/bin/python /home/kelsos/.virtualenvs/raiden/bin/raiden --keystore-path /home/kelsos/.ethereum/testnet/keystore --log-config raiden:DEBUG --api-address localhost:5503 --eth-rpc-endpoint http://localhost:8545 --accept-disclaimer --network-id 17 --environment-type production --address 0x60FFe4daDE358246C49C4A16bB5b430d333B5Ce9 --password-file /home/kelsos/development/utils//credentials/0x60FFe4daDE358246C49C4A16bB5b430d333B5Ce9 --no-sync-check --tokennetwork-registry-contract-address=0xA4e13D328308194c0AB4E10bB1f2B2e8d624d240 --secret-registry-contract-address=0x1450306327242B8db9B9179906C24e5c35D4053b --endpoint-registry-contract-address=0xa427f6e3686A0BE8dE550cC5450B7FaD1B770956
```
