### ISSUE TITLE
Improve feedback when accounts doesnt have ETH on chain

### ISSUE THREAD

**Issue by marcosmartinez7** [raiden-network/raiden#3375]
When interacting with the REST api with accounts withouth ETHER in the chain (geth, parity, for example) the REST api did not respond anything, even a timeout. 

Restarting the REST api but with ether into the Raiden account works ok.

## Issue checklist

To help us more easily debug your issue please check the boxes for which requirements for safe usage or Raiden were followed:

- [x] The Ethereum node was always up to date with the chain tip and never stopped running.
- [x] No Ethereum transaction was sent for the account that Raiden manages by another app.
- [ ] The Ethereum account used by Raiden always had sufficient ETH.
- [x] The Raiden DB that exists by default at ~/.raiden was never altered or deleted.
- [ ] The Raiden node was never restarted. If yes please provide more info.
- [x] The ethereum node was not switched while Raiden was running.
- [x] The Raiden REST API is protected from public access.

## Problem Definition

Reproducible scenario:

- Run 2 raiden nodes, create a payment channel, make some payments and close them. 
- Run a third one, try to invoke /connect

Without ether: nothing happens, requests blocked forever
With ether: works ok

### System Description

Here add a detailed description of your system, e.g. output of the following script:

```
Ubuntu 

/usr/bin/solc
solc, the solidity compiler commandline interface
Version: 0.5.3+commit.10d17f24.Linux.g++

/usr/bin/geth
Geth
Version: 1.8.21-stable
Git Commit: 9dc5d1a915ac0e0bd8429d6ac41df50eec91de5f
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.10.4
Operating System: linux
GOPATH=
GOROOT=/usr/lib/go-1.10

{
  "raiden": "0.100.2rc4.dev7+g032bdcf2",
  "python_implementation": "CPython",
  "python_version": "3.6.7",
  "system": "Linux 64bit_ELF 4.15.0-43-generic x86_64",
  "distribution": "source"
}

```

**Comment by LefterisJP** [comment]
Hmm no I just tried the same in latest master and without enough Ether this is the error I am getting:

```
http PUT http://localhost:5001/api/v1/connections/0xc49597882BCAd4B8a623E5e5703D3928636023C5 funds=1
HTTP/1.1 402 PAYMENT REQUIRED
Content-Length: 178
Content-Type: application/json
Date: Thu, 31 Jan 2019 21:56:15 GMT
mimetype: application/json

{
    "errors": "The account balance is below the estimated amount necessary to finish the lifecycles of all active channels. A balance of at least 5704389593358572 wei is required."                                                                                            
}
```

Can you provide logs of this attempt which made connect hang for you?

**Comment by marcosmartinez7** [comment]
I have done this using the v100.2-rc2

I will test it using master
