### ISSUE TITLE
Investigate Matrix 1.0 / Synapse 0.99, 1.0 changes

### ISSUE THREAD

**Issue by ulope** [raiden-network/raiden#3387]
## Problem Definition

As announced during FOSDEM 2019, Matrix has released v1.0 of their spec and also v0.99 of the Synapse homeserver (v1.0 planned for March).

Most notable changes:

- No more self-signed certificates for S-S federation traffic, everything is Letsencrypt now
- Rooms "version 3", room ids will change to a base64 encoded content hash

We need to investigate what impact (if any) those changes will have on our use of Matrix:

- Certificates for local federation used for tests
- Possible changes in room discovery due to room ID change
- ???
- Once the switch has been made the `psycopg2` pinning in `requirements/requirements-dev.in` should be removed.

**Comment by konradkonrad** [comment]
I have a couple flaky tests in an unrelated PR since after the upgrade to `0.99`:
- https://circleci.com/gh/raiden-network/raiden/46534#tests/containers/11
- https://circleci.com/gh/raiden-network/raiden/46535#tests/containers/5
