### ISSUE TITLE
Address shortcomings of existing migration management / execution

### ISSUE THREAD

**Issue by rakanalh** [raiden-network/raiden#3405]
## Introduction

Provided the discussion in #3275, we've implemented the upgrade manager to have a list of migration functions which are executed in order to migrate the database from one version to another.

Given that i already wrote 1 migration and currently writing another, i have began seeing shortcomings that we need to address.

## What are the shortcomings?

Snippet 1:
https://github.com/raiden-network/raiden/blob/d50045c7aec544d225dcddc4fb2ee81f35e1949e/raiden/utils/upgrades.py#L14-L18

Snippet 2:
https://github.com/raiden-network/raiden/blob/d50045c7aec544d225dcddc4fb2ee81f35e1949e/raiden/utils/upgrades.py#L125-L135

Snippet 3:
https://github.com/raiden-network/raiden/blob/d50045c7aec544d225dcddc4fb2ee81f35e1949e/raiden/utils/migrations/v16_to_v17.py#L5-L9

Snippet 4:
https://github.com/raiden-network/raiden/blob/d50045c7aec544d225dcddc4fb2ee81f35e1949e/raiden/utils/migrations/v16_to_v17.py#L63-L64

Looking at the above code, we have the following problems:

1. Migration imports
2. Version is not updated between migrations
3. Difficulty in determining if a migration is a no-op
4. Code duplication

I will go through each point to elaborate on them:

### Migration imports

This is a minor issue. But the more migrations we have, the bigger the list of imports will be. To solve this we have 2 solutions:
1. Keep the migrations in the same file (this could grow significantly)
2. Auto-load migrations so that we don't have to import (previously implemented and rejected for the list approach to which i am now presenting an observed future issue).

### Version is not updated between migrations

Let's say the user was running v16 (redeyes). When v17 is out, the user downloads and runs the new version. So the upgrade manager will run the all existing upgrades in the list. However, each migration checks for the version it is upgrading. Which means that that the check will be as follows:
```
if old_version == 16 and current_version > 16:
    # upgrade
```
This works until it doesn't. If the user misses a release and upgrades the one after (v18 in this case), each of the migrations will check the version it is upgrading. Which means the above if-statement will work for the 1st migration (which upgrades v16 to v17), but if the second migration checks for v17 as the old version:
```
if old_version == 17 and current_version > 17:
    # upgrade
```
The migration won't be executed because the above test won't pass. This is because we're upgrading v16 -> v18 in one pass.

Solutions:
1. Update the version after each migration (inside the loop) so that subsequent migrations get the proper "old_version" they're upgrading.
2. Instead of looping over a list of functions, `for i in (old_version, current_version + 1): #inclusive for current version`. And run a module that upgrades the `i`th version so that migrations don't have to check for the version itself, the manager will just guarantee which migrations it should run.

### Difficulty in determining if a migration is a no-op

Same problem described above because of version checks.

### Code duplication
 
The problem here can be seen in snippet 3 where a migration needed to get the list of snapshots in the database. Another migration i recently added in PR (#2832) required the same thing so i had to duplicate some code. One would argue that we can place these functions inside the storage (SQliteStorage). However, the problem with that is that the migrations don't want the "deserialized" version of the snapshots but rather the raw json string. The need for a manually fetching the snapshots from the database not through the storage was because the storage uses the serializer by default.

We can:
1. Pass `raw=True|False` to functions in the storage so that the storage methods decide whether to deserialize data or not.
2. OR, we can create a proxy class on top of the storage which provides the Serialization/Deserialization integration with the storage. 

In #2, we can create utility functions in the "raw" storage so that we can get raw data from the DB in migrations without needing to duplicate any code or create additional "utils.py" kind of modules.

**Thoughts?**

**Comment by LefterisJP** [comment]
> Migration imports

So the problem here is what? That it is not nice to (eventuallly) have a huge list of imports?

> Version is not updated between migrations

What's wrong with the logic of just running migrations for all old versions all the time and if a migration is a no-op that's fine? I believe this is the usual approach to DB migration (i.e. django does).

I think this is what you are saying here also:

>     2\. Instead of looping over a list of functions, `for i in (old_version, current_version + 1): #inclusive for current version`. And run a module that upgrades the `i`th version so that migrations don't have to check for the version itself, the manager will just guarantee which migrations it should run.

Essentially just run all previous version migrations and if something is to be done for an upgrade it will be, if it's a no-op it's fine.

> Code duplication

I need to study the code closer to see the duplication problem.

But on the way to doing that I don't understand your comment or the linked issue here:

> In #2, we can create utility functions in the "raw" storage so that we can get raw data from the DB in migrations without needing to duplicate any code or create additional "utils.py" kind of modules.

Can you maybe explain it a bit more?

**Comment by hackaugusto** [comment]
> Migration imports

I don't see a problem at all. In fact I prefer this, since we will know at least the code is syntactically valid (Ideally we will have a test for each migration, but who knows).

> Version is not updated between migrations

Yeah, the version upgrade should be done as part of the migration itself inside the open transaction. Perhaps this can be made into a `UpgradeTransaction` context manager.

> Difficulty in determining if a migration is a no-op

Why is this a problem?

> Code duplication

I think 2. is a good option, I don't like that we decode/encode in JSON from the migrations, the format should not be a problem to the migrations (well ... maybe it should, if we do change the format, then where this migration would go?).

**Comment by LefterisJP** [comment]
Note:

> In #2, we can create utility functions in the "raw" storage so that we can get raw data from the DB in migrations without needing to duplicate any code or create additional "utils.py" kind of modules.

I got this explained by @rakanalh in a call and I now understand his suggestion. I also think it's a good option.

Btw @rakanalh you actually linked to the issue #2 in this repo so I was further confused :)

**Comment by rakanalh** [comment]
Ahh, sorry i should stop using `#` to refer to bullet points

**Comment by rakanalh** [comment]
I'll close this since some PRs were merged that improve things a bit.
