### ISSUE TITLE
Decide on the type annotation for non return functions

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/raiden#3411]
The definitions bellow are equivalent:

```python
def a() -> None:
    pass


def b():
    pass
```

We need to pick one to keep the style consistent.

**Comment by hackaugusto** [comment]
vote
```
def a() -> None:
    pass
```

**Comment by hackaugusto** [comment]
vote
```
def b():
    pass
```

**Comment by palango** [comment]
I think I was partly wrong in saying that `-> None` is inferred. Especially when running mypy with the `--disallow-untyped-defs` it complains when functions do not have that annotation.

**Comment by LefterisJP** [comment]
> `--disallow-untyped-defs` it complains when functions do not have that annotation.

Well this argument explicitly asks **all** function defs to be typed ;)

**Comment by palango** [comment]
Yes, but I always assumed that no return type annotation implies `-> None`.

**Comment by ulope** [comment]
No, no annotation implies `-> Any`. 
The only exception are `__init__` methods **with parameters** that are annotated, those automatically default to `-> None` ([long issue discussion about that 'feature'](https://github.com/python/mypy/issues/604))
