### ISSUE TITLE
Publish Monitoring Requests on Recovery

### ISSUE THREAD

**Issue by konradkonrad** [raiden-network/raiden#3454]
After  #3273 the client is able to publish monitoring requests during regular operation, but, if a client is configured with monitoring, it should also publish the latest balance proofs after recovery.

After recovery, the client should publish the latest received balance proof of all (configured, #3462) channels to the monitoring service.

**Comment by hackaugusto** [comment]
@konradkonrad can you clarify what is the difference from the normal operation and recovery code paths?

**Comment by konradkonrad** [comment]
> @konradkonrad can you clarify what is the difference from the normal operation and recovery code paths?

The difference will depend on what comes out of #3452 -- the way I imagine it:
- normal operation: if a state change leads to a _new_ received balance proof (and meets policy #3462) ==> publish to MS
- recovery: during replay: don't publish to MS, after replay: collect _latest_ balance proofs for all channels and (if the respective channel-monitoring-policy #3462 matches) ==> publish to MS

**Comment by rakanalh** [comment]
Closing issue as it was implemented in #3514
