### ISSUE TITLE
Notify user about insufficient RDN funds

### ISSUE THREAD

**Issue by rakanalh** [raiden-network/raiden#3464]
## Requirements

- [x] Introduce a `MIN_RDN_THRESHOLD` 
- [x] Log an error message when the user is running out of RDN tokens to pay for the services.

## Open Questions
- What would insufficient be? < 1 RDN or < 10?

Expected: End of Feb, 2019.

**Comment by LefterisJP** [comment]
### Comments

>     * Introduce a `MIN_RDN_THRESHOLD`

I would also add that this should be **only** enabled if the user uses a PFS or MS.

>     * Log an error message when the user is running out of RDN tokens to pay for the services.

We can use the same check as the `gas_reserve` [here](https://github.com/raiden-network/raiden/blob/8ab370536b59b474049dab23d2683d29364dd797/raiden/tasks.py#L71) for this warning.

The only problem with this is the same as the gas reserve. A warning in the console is very very easy to miss. In normal operations people don't stare at their screen.

>     * What would insufficient be? < 1 RDN or < 10?

That depends on the average amount of RDN that will be needed for PFS requests as I guess this is what is going to be the most frequent expense (MS payments should be rare enough to not care about them in this calculation). Let's call this value `PFS_REQUEST_RDN` 
@palango we don't know this value yet, do we? 

When we do know, then we should also define some average expected PFS requests per channel per hour. That's going to most probably be a guestimate. Let's call it `PFS_REQUESTS_PER_HOUR`.

Then the user should configure how many hours of operation he wants to be warned before. Let's call that `WARN_HOURS_BEFORE_OOF`.

So the amount of RDN at which we should warn should be:

```
PFS_REQUEST_RDN * PFS_REQUESTS_PER_HOUR * WARN_HOURS_BEFORE_OOF * NUMBER_OF_OPEN_CHANNELS
```


### Additional thoughts (can be other issue)

For both the low `RDN` and the low `ETH` check we will need some sort of action to be taken. Perhaps a user defined action? Like for example a callback using which someone can implement their own actions. For example program a mail server to send out warning emails. Or even a script to refill their account with ETH/RDN.

**Comment by palango** [comment]
In general we don't know the price of a PFS request yet, and it should be dynamic in the future.

Also for the UDC deposits the services will probably require some margin on the user side, because double spending is possible in theory.
