### ISSUE TITLE
Client should have a default payment for requesting a route 

### ISSUE THREAD

**Issue by rakanalh** [raiden-network/raiden#3466]
@palango needs to define how this will work.

The idea is to include IOU information of the payment. 

If the user doesn't have enough funds to pay the PFS, either:
1. Fallback to basic routing
2. inform the user to deposit more in UDC

Expected: End of Feb, 2019.

**Comment by LefterisJP** [comment]
The arguments that need to be included with each PFS request are in the [spec](https://raiden-network-specification.readthedocs.io/en/latest/pathfinding_service.html#arguments).

Relevant PFS [issue](https://github.com/raiden-network/raiden-services/issues/38). Important section: "Communication between client and PFS"

**Comment by rakanalh** [comment]
Closing this one in favor of #3461 and #3464
