### ISSUE TITLE
add getter methods to the RaidenAPI

### ISSUE THREAD

**Issue by ezdac** [raiden-network/raiden#347]
this is a split-up from #10, as stated in #325 

This are mainly getter methods for a Client to retrieve the initial state of the node on the first connect. Ideally, every following state-update will be retrieved through events in a long-polling fashion, in order to keep the polling count low.

For now, the methods should only return internal Objects like e.g. a `raiden.channel.Channel`.
But in the end, we want the same Interface for external api-users (via TCP) and internal api-users (in-process). Therefore, the API-methods should return Objects that function as simple data-containers for all the relevant information in their decoded (binary) form.
Internal users of the API will simply process this objects, without worrying about encoding,
while external users will retrieve the JSON-encoded version of this objects.

**add following methods to the `raiden-service.RaidenAPI`**:

- `get_channel_list(asset_address=None, partner_address=None)`:
This is a universal method for retrieving a collection of channels.
When neither of the keyword-arguments is provided, it should return all channel-objects that the node participates in. The keyword-arguments serve as a simple filter, so that the client can retrieve channels filtered by a certain asset- / partner address.
e.g. RESTful: `/api/assets/<asset_address>/channels GET`
Returns a list of channels

- `get_channel(channel_address)`:
Returns only one channel-object, retrieved by the netting-channel-address.
This is not neccessarily needed, since we can retrieve all channels with `get_channel_list`,
but is a convienience method if the client is only interested in one channel, or needs to poll for state changes

- `query_endpoint(raiden_address)`:
Querys raiden's discovery to get the value of the `address - > endpoint` mapping.
Returns an endpoint-object (with fields: `address`, `port`)
This will serve for light-clients to establish a connection to a node without having to know the discovery.

**Comment by LefterisJP** [comment]
Same as with https://github.com/raiden-network/raiden/issues/356, I think this is not needed for the Raiden API as we defined it for the MVP.
