### ISSUE TITLE
Timeouts with multiple synapse servers

### ISSUE THREAD

**Issue by err508** [raiden-network/raiden#3472]
## Problem Definition

Found during #3385. 

There are some problems when different clients use different synapse servers.
- UserPresence updates when a client goes offline are propagated slowly and if the client was sending messages before that, the greenlet handling the UserPresence update caused by the client going offline might be processed before the UserPresence update caused by the message, leading to inconsistent UserPresence state. 
- Creating a room and inviting a user on multiple servers takes longer (especially for private rooms) than joining the room for the invitees, which leads to timeouts on their side. 
- Local synapse servers are considerably slower on Linux when compared to OSX, which leads to flakiness with our Linux CI 
- As a result, testing with multiple synapse servers is considerably slower, is yet needed due the issues described above but leads to bloating the build.

## Possible solutions

- transport-tests CI tag ?
- See if Synapse 1.0 solves some of these issues #3387

**Comment by ulope** [comment]
We haven't seen timeouts in that area of the integration tests for a while now.
Closing.
