### ISSUE TITLE
Improper use of async_result in rest api payments

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#3475]
## Problem Definition

This was found by @offerm in https://github.com/raiden-network/raiden/pull/3473.

The code was not checking the async result object properly to get its result so it would never get into the "Payment could not be completed error".

**Comment by rakanalh** [comment]
Should this be closed? The PR fixing this was merged, no? unless you're referring to a different issue?

**Comment by offerm** [comment]
Yes, can be closed. Thanks.
