### ISSUE TITLE
Handle channels from different registries and same token

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/raiden#348]
#### Problem

The current implementation "dispatches" messages solely on the token address without considering the current registry, this means that channels from two different registries but same token will be mixed up.

#### TODO

- Implement #292 
- Either:
  - Add the network into the messages
  - Use the signature to "match" the registry address
- Change Raiden to use a AssetManager per registry

**Comment by hackaugusto** [comment]
Update: #1278 added the state objects required to represent multiple registries.

The messages need to be updated to include the registry address for proper dispatch, currently the default registry is assumed.

**Comment by carllin** [comment]
Implementing the changes
