### ISSUE TITLE
Improve Error Message when a user starts multiple transports

### ISSUE THREAD

**Issue by err508** [raiden-network/raiden#3488]
When a client starts two transports on different home servers, this raises 

```
2019-02-15 11:34:14.362367 [error    ] A MatrixHttpLibError occured during sync. [raiden.network.transport.matrix.client] 
 Traceback (most recent call last):
[...]
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response
```
This exception could be more explicit

**Comment by ulope** [comment]
> When a client starts two transports on different home servers

How can that happen?

**Comment by err508** [comment]
Bad user behaviour, when a user starts nodes with the same address on different home servers. 
You can close this if you think its unreasonable though, just found it during testing and agree its not very likely/not the worst part that will break than.

**Comment by ulope** [comment]
Ah! Ok, the wording was just confusing to me (maybe change the description to `... when a user user ...`, `client` is what confused me).

No I think it's fine to at least have an issue about this even if we decide not to do anything about it in the short time.

**Comment by err508** [comment]
Aight, will do!
