### ISSUE TITLE
Resolve unclarity about identifiers

### ISSUE THREAD

**Issue by konradkonrad** [raiden-network/raiden#3493]
## What is wrong?
We currently have a pretty mixed bag of ways to identify a channel:
- `channel_identifier`: the channels `(participant1, participant2)` "nonce" for a token network (increased with every new channel opened between the two per token network). Unfortunately this "identifier" is not unique, so we add some other fields for unique identification:
- `chain_id`: the chain identifier
- `registry_address`: the address of the payment network contract
- `token_network_address`: the address of a token network contract
- `token_network_identifier`: the `token_network_address` **note: it is the same thing as the `token_network_address`**

Especially the last two tend to get mixed up. ~~Moreover, some messages are _overspecified_, as they may define `chain_id, channel_id, token_network_identifier`, which spells out to `chain_id, channel_id, chain_id, token_network_address`.~~ (nevermind this!)

## What's the goal?
In scope of off- and on-chain messages, we need to uniquely identify the payment channel, so that a signed message for one channel can **not be replayed** onto any other channel.
@hackaugusto proposed a `canonical_identifier` for this. The definition is:
- `canonical_identifier`: `(chain_id, token_network_address, channel_identifier)`

## What's to do?
I propose, that we 
- introduce the `canonical_identifier` to all off-chain messages
- in turn get rid of `token_network_identifier` entirely

**Comment by hackaugusto** [comment]
> introduce the `canonical_identifier` to all off-chain messages

IMO this is useful through out the whole code base, to have a single way of referencing channels.

> in turn get rid of `token_network_identifier` entirely

One of the reasons to have this types is to reduce the number of arguments we have to pass around. The views make for a good example:

https://github.com/raiden-network/raiden/blob/eb62016ec8415dd0538f9781eb76a1ab1dd9c877/raiden/transfer/views.py#L61-L65

Another is to have a canonical way of identifying these objects internally (think of the sandwich encoding, where we have internally everything as bytes and don't have to worry about bytes/str compatibility). The RaidenAPI make a good case for this:

https://github.com/raiden-network/raiden/blob/f57cbf35d5313101fb27d227ff329b64c2cc7fb0/raiden/api/python.py#L162-L167

**Comment by andrevmatos** [comment]
Previosus try to get it done, it became bigger than expected and is frozen for now, may be base for implementation or at least give some hints: #2537
