### ISSUE TITLE
Do in need to maintain multiple raiden nodes each time to connect a new account

### ISSUE THREAD

**Issue by imhari213** [raiden-network/raiden#3506]
i setup-ed two raiden nodes and i can able to create channels .transfer token from that channels but i can able to do it between the two accounts only.
what if i want to create a state channel to another from existing account do i need to setup another raiden node or is there any other way.

**Comment by czepluch** [comment]
Hi @imhari213 .
If you've opened channels with other nodes in a token network you should be able to transfer to all other nodes that you have a path to with enough capacity. For instance, you can take a look at the graph on the [Raiden Explorer](https://explorer.raiden.network/tokens/0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2) page. This will give you an idea of how the network looks like, and then if you open a channel to a node already in the network you can interact with other nodes.

**Comment by imhari213** [comment]
> that means to open a channel with some Account like : 0x48A966441a948c19bAfB15c4e1518BAEa575e1Cb
> do i need to maintain a node attached to this 0x48A966441a948c19bAfB15c4e1518BAEa575e1Cb [Account]

**If it is like that for every Account i need to maintain individual node**

**Comment by czepluch** [comment]
Sorry, I am no sure what you mean.

As [per the documentation](https://raiden-network.readthedocs.io/en/stable/overview_and_guide.html#requirements-for-safe-usage), at the moment your node(s) need to be always online.

**Comment by agatsoh** [comment]
@imhari213 At this stage you need to maintain one node for each account(each ethereum address). All the nodes need to be online if you want to send and receive payments. If any node by some reason gets offline due any problem like network issues, the nodes are quite fault tolerant that if you bring them online immediately  the transfer will still get completed. If you have any more doubts I have already sent you a personal message on gitter. I can solve any more doubts that you may have there.

**Comment by imhari213** [comment]
Thanks for your help @czepluch @agatsoh  :)

**Comment by hackaugusto** [comment]
It looks like the question was answered, so I'm closing this for now. @imhari213 if you have more question feel free to reopen or create a new issue.
