### ISSUE TITLE
[SP] Add assertion to check blockchain events

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden#3509]
Add an assertion to the scenario player that makes it possible to check for events on the blockchain.
At the beginning events from the core contracts should be enough, later an extension for the service contracts might be helpful.

**Comment by hackaugusto** [comment]
@palango could you clarify a bit? Do you mean an additional directive for the yaml file?

**Comment by palango** [comment]
Sure: the problem we're trying to solve is to test the happy path of the monitoring service. For this to be possible (and as the MS doesn't have a public interface right now) we need to be able to check that certain events were emitted (in this case the `UpdatedNonClosingBalanceProof`).

So there should be an assertion usable in the yaml scenario definition that allows to check that certain events appeared on the blockchain.
