### ISSUE TITLE
Recoverable and Unrecoverable errors

### ISSUE THREAD

**Issue by marcosmartinez7** [raiden-network/raiden#3516]
There are some situations that i think that the Raiden node must be recoverable and the API should not crash. 

Those are, for example, when openning a channel: 

- The transferFrom function of the ERC20 token has some access modifier and the transaction fails. For this situation, raiden fails with this message:

> FATAL: setTotalDeposit call failed. The tokens were not transferred

```python
 def _check_why_deposit_failed(
            self,
            channel_identifier: ChannelID,
            partner: Address,
            token: Token,
            amount_to_deposit: TokenAmount,
            total_deposit: TokenAmount,
            transaction_executed: bool,
            block_identifier: BlockSpecification,
    ) -> Tuple[
        Union[RaidenRecoverableError, RaidenUnrecoverableError],
        str,
    ]:
        error_type = RaidenUnrecoverableError
        msg = ''
        latest_deposit = self.detail_participant(
            channel_identifier=channel_identifier,
            participant=self.node_address,
            partner=partner,
            block_identifier=block_identifier,
        ).deposit

        allowance = token.allowance(
            owner=self.node_address,
            spender=Address(self.address),
            block_identifier=block_identifier,
        )
        if allowance < amount_to_deposit:
            msg = (
                'The allowance is insufficient. Check concurrent deposits '
                'for the same token network but different proxies.'
            )
        elif token.balance_of(self.node_address, block_identifier) < amount_to_deposit:
            msg = 'The address doesnt have enough tokens'
        elif transaction_executed and latest_deposit < total_deposit:
            msg = 'The tokens were not transferred. Please check that the transferFrom function is accessible'
        else:
            participant_details = self.detail_participants(
                participant1=self.node_address,
                participant2=partner,
                block_identifier=block_identifier,
                channel_identifier=channel_identifier,
            )
            channel_state = self._get_channel_state(
                participant1=self.node_address,
                participant2=partner,
                block_identifier=block_identifier,
                channel_identifier=channel_identifier,
            )
            # Check if deposit is being made on a nonexistent channel
            if channel_state in (ChannelState.NONEXISTENT, ChannelState.REMOVED):
                msg = (
                    f'Channel between participant {self.node_address} '
                    f'and {partner} does not exist',
                )
            # Deposit was prohibited because the channel is settled
            elif channel_state == ChannelState.SETTLED:
                msg = 'Deposit is not possible due to channel being settled'
            # Deposit was prohibited because the channel is closed
            elif channel_state == ChannelState.CLOSED:
                error_type = RaidenRecoverableError
                msg = 'Channel is already closed'
            elif participant_details.our_details.deposit < total_deposit:
                msg = 'Deposit amount did not increase after deposit transaction'

        return error_type, msg
```

Is there any reason of why the API should take those errors as unrecoverable and shut down the node? 

It is terrible for situations like, you have a node that its connected to 10 networks (10 differents ERC20 tokens), and seems one transaction fails into one ERC20 token then the node will crash, affecting the rest of the networks. 

For example, this is the allowance error

```python
if allowance < amount_to_deposit:
            msg = (
                'The allowance is insufficient. Check concurrent deposits '
                'for the same token network but different proxies.'
            )
```

Obviously if we have concurrent deposits the allowance may be lower than the amount_to_deposit, but is this unrecoverable? Why dont just return that the operation fails? 

I think the same applies for when the node doesnt have the enough balance on chain (invoking balanceOf)

I am missing something? Why we cannot treat them as RaidenRecoverableError and return them as a message to the UI?

**Comment by hackaugusto** [comment]
Hi @marcosmartinez7 , I think the best definition for the recoverable/unrecoverable errors is on the issue https://github.com/raiden-network/raiden/issues/2719 . In short, it's unrecoverable if Raiden has a programming error in *its code*, meaning something unexpected happened and as a consequence the node's state is unknown.

> Is there any reason of why the API should take those errors as unrecoverable and shut down the node?

I assume that by API you are talking about the REST API.

It's the REST API responsibility to reject impossible calls to deposit, these are:

- Deposit for a channel that was never opened
- Deposit for a channel which has been settled/removed

It's the responsibility of the token proxy to report the above errors. So, for these cases if the node is crashing we have a bug in the REST API.

> The transferFrom function of the ERC20 token has some access modifier and the transaction fails. For this situation, raiden fails with this message:

For this case, the ERC20 token is not our code, but a third party code that we interact with. Unrecoverable errors don't apply because we will never really be 100% sure of its behavior, and we therefore cannot detect errors. If the proxy is raising an unrecoverable error exception here, we have a bug in the proxy.

The code you linked is indeed a bit too restrictive on the ERC20 verification, thanks for reporting.

**Comment by marcosmartinez7** [comment]
I think is too restrictive too, as i said, the entire node going down because 1 of the N ERC20 Tokens that is joined retrieves an error with

- allowance
- balanceOf
- transferFrom access modifiers

I mean, those situations can be handled just as an exception but i think it must not affect the rest of the networks that the node is part. 

Thanks for the response !
