### ISSUE TITLE
2 payments from the same payer to to same payee fails 

### ISSUE THREAD

**Issue by offerm** [raiden-network/raiden#3518]
I'm trying to use payment API to make 2 payments one after the other to the same payee.

The second payment fails. 

There is an warning `Message already in queue - ignoring` 

I created a PR with a test that IMHO should pass #3517 

Let me know if I missed anything

**Comment by LefterisJP** [comment]
I commented in the PR explaining why the test is wrong. Comment is [here](https://github.com/raiden-network/raiden/pull/3517#issuecomment-465329130)

**Comment by offerm** [comment]
Many thanks. Closing
