### ISSUE TITLE
Splitting transactions / payments to allow for retail use cases

### ISSUE THREAD

**Issue by Dominik1999** [raiden-network/raiden#3520]
## Abstract

Channels in the Raiden Network tend to be imbalanced in almost any retail use case (where somebody buys something). This is because money tends to flow uni-directionally from a payer to a payee but never into the other direction. Money is then allocated at the payee (the business entity) and spent in large single transactions to buy many units of that good for a cheaper price. As long as we can not split up transactions, Raiden might not be used as a system to buy goods and services. 

I made a small comic: 
![raiden feature request - transaction splitting](https://user-images.githubusercontent.com/35031754/53112355-519d8400-353f-11e9-952d-d11fcfff32d6.jpg)
![raiden feature request - transaction splitting 1](https://user-images.githubusercontent.com/35031754/53112384-5cf0af80-353f-11e9-8c7a-22848da4a6ff.jpg)
![raiden feature request - transaction splitting 6](https://user-images.githubusercontent.com/35031754/53112525-b3f68480-353f-11e9-8bfb-419dbd140b32.jpg)
![raiden feature request - transaction splitting 2](https://user-images.githubusercontent.com/35031754/53112396-624dfa00-353f-11e9-88e6-75e5d7f585f4.jpg)
![raiden feature request - transaction splitting 3](https://user-images.githubusercontent.com/35031754/53112406-667a1780-353f-11e9-92af-3a7b253ebf86.jpg)
![raiden feature request - transaction splitting 4](https://user-images.githubusercontent.com/35031754/53112413-6a0d9e80-353f-11e9-943d-d3f01b856990.jpg)
![raiden feature request - transaction splitting 7](https://user-images.githubusercontent.com/35031754/53112762-48f97d80-3540-11e9-9a72-7f1dd0df5c16.jpg)

... had a long train ride today :)

**Comment by hackaugusto** [comment]
I really liked the stick figures :).

Yeah, this is a feature that we need to re-introduce, this is why we have the concepts `transfer` and `payment` in the protocol. A payment can be made out of multiple transfers, all using the same secrethash, allowing channels of smaller capacity to be used for larger payments.

**Comment by LefterisJP** [comment]
@hackaugusto We don't have an issue for this do we? So perhaps we can use this one with the awesome stick figures?

We had discussed in the past that we should at some point introduce this, as it's the same as Lightning does with their [AMPs](https://lists.linuxfoundation.org/pipermail/lightning-dev/2018-February/000993.html) (Atomic Multi-path Payments) but can't find traces of that discussion in Github.
