### ISSUE TITLE
One-click-installer

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/raiden#3525]
## Abstract

Installing Raiden is already quite easy, but we would like to simplify the installation of the full stack needed to run Raiden even further for MacOS and Linux (including ETH client, RPC or Infura)

## Motivation

There are still users who have got difficulties or which do not have time to set up and configure Raiden and the Ethereum client.

## Current Solutions and Descriptions
1. Normal Install ([Documentation ](https://raiden-network.readthedocs.io/en/stable/overview_and_guide.html#installation)and [Video](https://www.youtube.com/watch?v=fy2ctCQHfD4))
2. [Raiden Workshop](https://github.com/raiden-network/workshop)
3. [Dockerhub](https://hub.docker.com/r/raidennetwork/raiden)
4. [PyPI](https://pypi.org/project/raiden/)

### Preface
This is not a full-fledged specification going into every detail. Whenever possible, I am trying to give priorities, that it can be implemented in an agile manner.

MVP could look like: Linux -> Testnet -> Infura -> Existing Account -> 

Please correct, if you have got better ideas or something doesn't make sense.

### Environment
Priority
1. Linux
2. MacOS
3. Windows

### Example

Akasha has created a nice [installer](https://github.com/AkashaProject/Community/releases), which still has [got some issues](https://steemit.com/utopian-io/@ervin-lemark/akasha-project-closed-beta-first-look-install-and-setup), but it shows (mainly at the start) how we are envisioning the set-up.

### Usability
It should be a guided set-up with a graphical interface if an installer framework can be used. A guided script would also be good enough at the start

### Steps
If the order does not make sense, please change the steps.

Make the installer restartable
- Checking, if steps have been already executed
- Branching into another option (eg. for testnet it has been already configured - on the second configure it for mainnet)

Make it possible, that the installer is running updates

#### 1. Network
Priority
1. Testnet (the easist/best one)
2. Mainnet
3. Other testnets
4. Private Chain (just a vision - this [set-up might be used](https://github.com/kelsos/test-environment-scripts))

#### 1.1 Accept Requirements for safe use
1. Testnet: Link to the documentation
2. Mainnet: Just move on, if the user has accepted, that he has been reading the requiremnts for safe use (like in the Raiden client)

#### 2. Ethereum Client
Priority
1. Connect to Infura
2. Connect to an existing Ethereum Client (locally or via RPC)
3. Connect to an existing Raiden client (locally or via VPN, etc.) and launch the WebUI
4. Install an Ethereum Client and synchronize
5. Install a private chain, deploy the Raiden contracts  and connect (just a vision)

#### 3. User Account
1. Use an existing account
2. Create a new account (maybe [this workshop script](https://github.com/raiden-network/workshop#on-boarding) can be used)

#### 4. Fill account with ETH
Priority
1. Testnet: Request Testnet ETH (maybe [this workshop script](https://github.com/raiden-network/workshop#on-boarding) can be used)
2. Mainnet: Guide how to do it
3. Mainnet: Ideas?

#### 5. Get tokens
This functionality will need additional thoughts. Some ideas how to implement it are
- Within the workshop repo
- As two issues within the webui repo (https://github.com/raiden-network/webui/issues/11 and https://github.com/raiden-network/webui/issues/15)

Priority
1. Testnet: Select a token and give instructions on how to get it from a faucet (or how to mint it, if it has got this function exposed)
2. Testnet: Select a token and start minting or request it from a faucet
3. Mainnet: Point to guide how to wrap ETH
4. Mainnet: Provide a function to wrap ETH

#### 6. Create a link / script / icon to start Raiden
1. Create a script to start Raiden and show the script name eg. `raiden_mainnet`
2. Create a button and place it on the Desktop, etc. (depends on OS)

#### 6. Connect to token network and start Raiden
1. Start Raiden and launch WebUI (provide a hint how token network can be selected)
2. Start Raiden, connect to selected token network and start WebUI

## Backwards Compatibility

Does not apply

**Comment by stefante** [comment]
Under 5: for the test net I would use faucets only not the mining process....

**Comment by LefterisJP** [comment]
@christianbrb Let me see if I understand this issue correctly. You don't want an one-click installer for Raiden as it's already one-click. The raiden executable is just a binary anyone can run with one click.

But what you want is a bundle of raiden + ethereum client + onboarding of an account with ETH/Tokens?

**Comment by christianbrb** [comment]
Development has started here: https://github.com/raiden-network/raiden-installer
