### ISSUE TITLE
review FIFO-Queue for Event emission (from API to client)

### ISSUE THREAD

**Issue by ezdac** [raiden-network/raiden#353]
**Note**: this is partially implemented in [PR #280](https://github.com/ezdac/raiden/blob/ea1941af7c866a8fd61fcb2a897482f0ab6d026f/raiden/raiden_service.py), but needs improvement. Here is an explanaition of the code:

The API will pass a flat list of Events to the client via the `get_new_events()` [method](https://github.com/ezdac/raiden/blob/ea1941af7c866a8fd61fcb2a897482f0ab6d026f/raiden/raiden_service.py#L463-L480), which can be polling or long-polling (for long polling see link above).

The Events include all the [blockchain-events](https://github.com/ezdac/raiden/blob/ea1941af7c866a8fd61fcb2a897482f0ab6d026f/raiden/raiden_service.py#L79-L84) for the channel, as well as a [TransferReceived](https://github.com/ezdac/raiden/blob/ea1941af7c866a8fd61fcb2a897482f0ab6d026f/raiden/raiden_service.py#L88) event for incoming messages that represent some kind of transfer.

Blockchain events will be constructed in the [same place](https://github.com/ezdac/raiden/blob/ea1941af7c866a8fd61fcb2a897482f0ab6d026f/raiden/raiden_service.py#L859-L864) where they get passed to raiden's internals for processing via a callback.
(We cannot just simply pass blockchain events, because the emitting contract address should be included in raiden's events.)

The TransferReceived event get's constructed via the [on_withdrawable](https://github.com/ezdac/raiden/blob/ea1941af7c866a8fd61fcb2a897482f0ab6d026f/raiden/raiden_service.py#L106-L108) callbacks.

Once the callbacks are registered in those places, the events will be [automatically put](https://github.com/ezdac/raiden/blob/ea1941af7c866a8fd61fcb2a897482f0ab6d026f/raiden/raiden_service.py#L117) in the Event-Queue.

**To Do**:

- Please review the above concept and provide some input.
- The Queue needs some limitation (max-size), otherwise it will get filled indefinitely when no client polls events
- the callback registration/ filling of the Queue should depend on some kind of `raiden --api --events=True` flag
- provide a simple polling option for the  `get_new_events` method  (trivial)

**Assumptions / Consequences of above concept**:

- the client needs to poll for an initial state on connect (events will only serve as state-updates during the connect)
- Events will only be saved until the queue is full and as long as the node is running

**Comment by LefterisJP** [comment]
@ezdac There are some things I do not understand. I believe we said we would not use callbacks at all for the API. This issue seems to rely on them.

Additionally it seems to be based on https://github.com/raiden-network/raiden/pull/280, which is not merged at the moment and seems to also contain callbacks.

**Comment by LefterisJP** [comment]
Closing this one since, we are rethinking the kind of API we want for the MVP. That is, as simple as possible.
