### ISSUE TITLE
Pluto release linux binary reports different version number

### ISSUE THREAD

**Issue by mat7ias** [raiden-network/raiden#3531]
## Problem Definition
I downloaded raiden-v0.100.2-linux-x86_64 from the nightlies. When I run it instead of saying it's version 0.100.2 it says 0.100.3.dev0+g32c1f504.d20190221 ![picture](https://user-images.githubusercontent.com/35585644/53233760-40d94380-36e2-11e9-993a-67f66382fddd.jpg)

**Comment by LefterisJP** [comment]
Hmmm thanks @mat7ias. This applies to the binary from the release page too. We will have a look.

**Comment by ulope** [comment]
This version number style means there were some untracked (by git) files in the working tree. Probably something left over from one of the previous steps.

I’ll take a look.
