### ISSUE TITLE
Description of Raiden image on docker hub is broken

### ISSUE THREAD

**Issue by BOR4** [raiden-network/raiden#3535]
Description looks like this:

.. image:: https://img.shields.io/pypi/pyversions/raiden.svg :target: https://raiden-network.readthedocs.io/en/stable/) :alt: Python 3.7 .. image:: https://badges.gitter.im/Join%20Chat.svg :target: https://gitter.im/raiden-network/raiden?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge :alt: Chat on Gitter

Raiden Network documentation_

.. _Raiden Network documentation: https://raiden-network.readthedocs.io/

I don't think this is intentional

**Comment by ulope** [comment]
By default docker hub pulls the project’s readme but is apparently not able to render ReST.

We should add a docker specific description there.

**Comment by konradkonrad** [comment]
@BOR4 is this still an issue for you? from here https://hub.docker.com/r/raidennetwork/raiden looks alright

**Comment by konradkonrad** [comment]
@BOR4 feel free to re-open, if this issue still exists!

**Comment by BOR4** [comment]
no need now it looks great!
