### ISSUE TITLE
Remove monkey patch hotfix for tinyrpc session IF upstream PR gets merged

### ISSUE THREAD

**Issue by konradkonrad** [raiden-network/raiden#354]
Due to https://github.com/mbr/tinyrpc/issues/26 our rpc client (`pyethapp.rpc_client.JSONRPCClient`) was [prone to exhausting client ports](https://github.com/raiden-network/raiden/issues/253).

I have created a [PR against the upstream (tinyrpc)](https://github.com/mbr/tinyrpc/pull/31) in order to address this. For the meantime, I have created a monkey patch (https://github.com/raiden-network/raiden/pull/350) to work around this.

Once the upstream PR is merged, or a similar patch is applied to `pyethapp`'s `JSONRPCClient`, we should get rid of the monkey patching.

**Comment by LefterisJP** [comment]
This issue is closed by commit: https://github.com/raiden-network/raiden/commit/b771fc06a9bcdaae531e3d3ef88dc63b9f9b42e9
