### ISSUE TITLE
Token registration endpoints return before token network exists in internal state

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden#3544]
The endpoint to register a new token return really fast, and before the state changes have been done to the internal raiden state.

In #3543 this leads to the testing code requiring a long wait (https://github.com/raiden-network/raiden/pull/3543/files#diff-00c4c05ef0fac830fbdcfcb586861a27R1374)  before the raiden node itself knows about the new token network.

The endpoint should only return after the changes to the internal state have been done.

**Comment by ulope** [comment]
Somewhat related: #2523

**Comment by christianbrb** [comment]
Scenario Player was running into this: https://github.com/raiden-network/scenario-player/issues/125

CC @nlsdfnbch @agatsoh
