### ISSUE TITLE
define RESTful endpoint specs for API

### ISSUE THREAD

**Issue by ezdac** [raiden-network/raiden#355]
Related to #10 

For filtering, should we only work with query strings on simple collection resources, or should we allow layering of resources :

for getting a specific channel:
- `GET /api/channels?partner=...&asset=...` or `GET /api/channels/<channel_address>`
- **vs.** `GET /api/partners/<partner_address>/assets/<asset_address>/channels`

for getting all channels with an specific asset:
- `GET /api/channels?asset=...`
- **vs.** `GET /api/assets/<asset_address>/channels`

for getting all channels:
- `GET /api/channels`

Should intersections of both approaches be allowed?:

 - `GET /api/partners?asset=.../<partner_address>/`

For putting data, should we stick to simple json-objects/form data attached to simple collection resource urls?:
e.g. `http PUT /api/channels partner=... asset=... settle_timeout=...` opens a channel with an additionally provided settle timeout.

One way to extend this even further would be to just use the encoded objects (e.g. channel)
to imply a client's request for state-update inside the node by changing the appropriate field to a new value.
The endpoint would always be `UPDATE /api/channels` and you could send an json-object
```
{
    'channel_address': '...'
    'partner_address': '...'
    'asset_address': '...'
    'balance': '...'
    'status': 'closed'
}
```
To request the closing of the channel.

### To Do:
- **please discuss:**

>  How RESTful does our API actually need to be, and how many duplicate endpoints do we need to provide for usability?

> How should posting to 'setting'  or 'state-updating' methods be handled?

**Comment by LefterisJP** [comment]
Personally I like consistency above everything else. I think that the layering approach may be more common and we should follow it too.

`GET /api/partners/<partner_address>/assets/<asset_address>/channels`
`GET /api/assets/<asset_address>/channels`

> Should intersections of both approaches be allowed?:
I believe not, this would hurt consistency.

> How should posting to 'setting' or 'state-updating' methods be handled?

I think just put`PUT` and `UPDATE` with simple json-objects would be the way to go.

**Comment by hackaugusto** [comment]
> For filtering, should we only work with query strings on simple collection resources, or should we allow layering of resources

IMO it's fine to "layer resources" as long as it fits with the document paradigm, e.g. I don't think a channel contains the asset, but the other way around, so `assets/<asset_address>/channels/<channel_address>` makes sense, where as the opposite `channels/<c>/assets/<a>` doesn't. That doesn't prohibit the existence of multiple URLs for the same document.

> Should intersections of both approaches be allowed?

I don't think so, it's going to make things to complicated on the backend and breaks the document paradigm.

> For putting data, should we stick to simple json-objects/form data attached to simple collection resource urls?:

Definitely not, the document content needs to go in the body of the `PUT` request, not in the query_string.

> One way to extend this even further would be to just use the encoded objects (e.g. channel)
to imply a client's request for state-update inside the node by changing the appropriate field to a new value

This is the correct approach, let's stick to the [RFC for HTTP Semantics and Content](https://tools.ietf.org/html/rfc7231#section-4.3.4):

> The PUT method requests that the state of the target resource be created or replaced with the state defined by the representation enclosed in the request message payload.

**Comment by konradkonrad** [comment]
>> Should intersections of both approaches be allowed?:

> I believe not, this would hurt consistency.

+1

> How should posting to 'setting' or 'state-updating' methods be handled?

> Definitely not, the document content needs to go in the body of the PUT request, not in the query_string.

>>    One way to extend this even further would be to just use the encoded objects (e.g. channel)
    to imply a client's request for state-update inside the node by changing the appropriate field to a new value

> This is the correct approach, let's stick to the RFC for HTTP Semantics and Content:

>>    The PUT method requests that the state of the target resource be created or replaced with the state defined by the representation enclosed in the request message payload.

> The endpoint would always be `UPDATE /api/channels` and you could send an json-object
```
{
    'channel_address': '...'
    'partner_address': '...'
    'asset_address': '...'
    'balance': '...'
    'status': 'closed'
}
```

For modifying lifecycle states of a channel, a format like the above seems pretty weird to me. I'm all in to sticking to RFC's, but having an endpoint like

```
POST/UPDATE /api/channels/<channel_address>/_close
```

seems more intuitive to me (nb: I'm probably spoiled by the Elasticsearch API).

**Comment by konradkonrad** [comment]
Let's play an example:
for creating a channel:
```
PUT /api/version/channels
{
  "channel_address": ???????,
  "partner_address": ...,
  "asset_address": ...,
  "deposit": 50
}
```
?

**Comment by LefterisJP** [comment]
So from our discussion we all seem to agree that intersections of both approaches should not be allowed.

We have a disagreement as to how to update the channel and other similar status changing operations. The options are:

1. Totally comply with the RFC for what restful is and always provide a full new object even if we want to perform a simple state change from `open` to `close`.

2. Just like @konradkonrad suggested have some *special* endpoints which would perform certain changes to the channel

**Comment by ezdac** [comment]
What I find a little weird with the single object manipulation is the redundancy of some of the fields depending on the state of the  channel and on the endpoint (like @konradkonrad stated). So the `asset_address, partner_address` and `channel_address` are mutually exclusive when the channel is existing.
`deposit` is only relevant when you either create the channel or the channel is in it's `opened` state.
`settle` and `close`-actions are only defined by the `status` and `channel_address` fields.

Say we have a `channel_state` and a read-only `channel` object (like @konradkonrad suggested):
We would have to think about how to handle the redundancy in the `channel_state`. 
I'd say we have to force that either `asset_address, partner_address` or `channel_address` is provided. And since we cannot use `channel_address` for the creation of a channel, it should be excluded from the object completely.

With the approach of multiple endpoints, there is also the intersection of 'arguments' (as object fields) and endpoint-arguments that I was talking about earlier. If we take precedence of the endpoint-arguments, then the relevant object-fields change again depending on the endpoint.

So since the fields are completely dynamic depending on state and endpoint, it would introduce a lot of confusing logic in creating and checking the requests.
The only way I see the RFC-approach would be to **exclusively** allow a `PUT /api/<version>/channels`
endpoint and exclude the `channel_address` from the `channel_state`-object to get rid of the mutually exclusive fields.

Otherwise I think we should go completely endpoint-defined, and don't use object's for state updates at all, which sounds a little hacky. But then again for transfers, objects would be handy because they have a uniform interface and don't depend on external state.

I cannot really decide which way is best, but I get the feeling that the object-approach is very uniform, but harder to explain to the end-user? Still, I think I like it better.

What I was wondering:

- Do we make the assumption, that the client always polls the full list of `channel`s on connect and then listens on the events permanently? Then it would be easy for him to construct the desired state-transition objects for a given channel. 
The only scenario where you would try to do a state-change without knowing the previous state would be to try to `close` a channel as an emergency measure?

- What do we actually gain from layered/multiple endpoints? I mean for 'browsing' for information it makes sense. But maybe we overestimate the gain of a RESTful API, since we don't really browse a database but rather do a lot of state updates, which would be best defined by the arguments of the function/method itself?

**Comment by hackaugusto** [comment]
I believe this issue can be closed, @LefterisJP what do you think?

**Comment by LefterisJP** [comment]
Yeah, wanted to close it at the end of last sprint. Slipped my mind! :)
