### ISSUE TITLE
define the structure of JSON-encoded objects (for the API)

### ISSUE THREAD

**Issue by ezdac** [raiden-network/raiden#357]
Related to #10 

*The structure of the JSON-encoding of objects has implications on how a client has to deserialise them again. Therefore a logical structure has to be thought of.*

**The current proposal**:

see PR [280](https://github.com/ezdac/raiden/blob/websocket_server/raiden/api/encoding.py#L51)

every object will be enveloped with information on what type of object the JSON-string represents and how to decode it (in terms of an API-version specifier):

For example an ChannelSettled - Event will look like this:

```python
 {
            'type': 'Event',
            'classifier': 'channel_settled',
            'version': '0.9b',
            'data': {
                'netting_channel_address': '0x624c4a42215d63282b5e3f754d7b3d5e542c3842',
                'block_number': '1'
            },
 }
```
- the `type` specifies the Base-class of the Object `Event`, `Channel`, ...
- the `classifier` specifies the Sub-Class of the Object `channel_settled`, `channel_new`, `null`
- the `version` specifies the API-version that encoded the object
- `data` will contain the nested, encoded Object itself

There will also be a `List` type, that represents some flat list of objects, whose base-class (former: `type`) is specified in the `classifier`

```python
 {
            'type': 'List',
            'classifier': 'channel',
            'version': '0.9b',
            'data': [{
                    'netting_channel_address': '0x624c4a42215d63282b5e3f754d7b3d5e542c3842',
                    'partner_address': '0x524c4a42215d63282b5e3f754d7b3d5e542c3842',
                    'asset_address': '0x424c4a42215d63282b5e3f754d7b3d5e542c3842',
                    'balance': 42,
                    'block_number': '1',
                    'status': 'closed'
                },
                {
                    'netting_channel_address': '0x324c4a42215d63282b5e3f754d7b3d5e542c3842',
                    'partner_address': '0x724c4a42215d63282b5e3f754d7b3d5e542c3842',
                    'asset_address': '0x425c4a42215d63282b5e3f754d7b3d5e542c3842',
                    'balance': 42,
                    'block_number': '4',
                    'status': 'open'
                }
            ]
 }
```

Especially for events, this List has to support polymorphic fields, since there will be differently structured Events appended. Here, following the proposed schema, we would also have to envelope every Event in the list.

The proposed implementation of encoding uses for the most part the `webargs` [module](https://github.com/sloria/webargs),
which heavily wraps around the `marshmallow` [module](https://marshmallow.readthedocs.io/en/latest/)

### To Do:
- please give some feedback on the encoding schema
- especially think about how objects should be enveloped in regard to flat lists that represent arbitrary collections of objects

### To Do *implementation wise*:
- construct a custom `marshmallow.field.Field` for polymorphic fields or use the `marshmallow-polyfield` [extension](https://github.com/Bachmann1234/marshmallow-polyfield)

**Comment by LefterisJP** [comment]
I think that the proposed structure for JSON-encoded objects looks fine. Flat lists also look okay and make sense. Would be what a `get_channels()` kind of function would return.

One question. In your description of the `classifier` field you also mention `null` as a value. When would the `classifier` field be `null`?

Regarding `marshmallow` I don't know much about it but it looks like a good thing to use for our case. Will need to read about it further.

**Comment by konradkonrad** [comment]
Why would `block_number` be a string?

**Comment by LefterisJP** [comment]
good point. It shouldn't be.

**Comment by hackaugusto** [comment]
I don't think in our case the version number is part of the document, it's part of the api and it's best placed in the url. As for the lists, JSON has a built-in list representation, I don't see why do we need to wrap it into yet another structure.

More important, for both cases, if we do add the api version number or use a list wrapper, the documents used for PUT and GET methods won't match.

**Comment by konradkonrad** [comment]
For a RESTful API #355 we don't need the envelope

**Comment by LefterisJP** [comment]
After our call and discussion of the issues we concluded that we do not need the envelope since the API is restful.

Essentially we would only need the `data` part of your proposal since the properties of what these data are would be defined by the URI of the endpoint.

Also the version would be part of the endpoint and is not needed here.

@mmax do you have any comments on this?

**Comment by ezdac** [comment]
Thanks for your input!

> I'm not yet sure what the upside of a (seemingly arbitrary) two-fold type discrimination (type + class) is?

The two-fold type-specifier was initially introduced for easier class inheritance in `marshmallow`, and should represent Baseclass and Childclass. but It shows that it doesn't make things easier by a lot and also creates unneccessary confusion.

I agree on most of your comments. URLs/Endpoints define the type and version and the envelope isn't neccessarily needed. BUT:

> Essentially we would only need the data part of your proposal since the properties of what these data are would be defined by the URI of the endpoint.

This holds true for everything but the Events, and that's the main reason I introduced the envelope with type-specifier.

_Note: The getter-method for events will pop an Event-Queue of recent events empty and return it as a list._

The list contains different types of Events where most have different fields - so the encoding would require support for polymorphism. In order to decode the events on the client-side, it needs to have a type specifier, if we don't have a special endpoint for every type of events.

The initial choice for implementing this was an envelop, which was also included in every other object (like a channel) for consistency.

We could do 2 things:

- poll uniform lists of a specific type from separate endpoints (like `/api/version/events/channel_closed/ GET` )  

- stay with the mixed type list approach but just include the type in the former `data`-dict, and do this only for events:
```python
             {
                "event_type": "channel_settled",
                "netting_channel_address": "0x624c4a42215d63282b5e3f754d7b3d5e542c3842",
                "block_number": 1
             }
```

I'm more in favor of version 2, because version 1 would require some 'server'-side filtering logic and multiple long-polling endpoints.

**Comment by ezdac** [comment]
sorry, wrong button ;)

**Comment by hackaugusto** [comment]
+1 for the `event_type` as part of the event representation.

**Comment by LefterisJP** [comment]
Yes I also think `event_type` as part of the representation is the way to go. Multiple endpoints per event would be an overkill and would require client-side changes if new events are added.

**Comment by mmax** [comment]
hi everyone. 

I'm pretty sure you added me to this thread accidentally. 
Just thought I'd let you know you have a guest. :)

Cheers

Max

______________________________
http://www.marcoll.de
http://www.stock11.de

**Comment by LefterisJP** [comment]
@mmax Hahaha. Hey my bad. @ezdac's handle is same as yours in our internal chat. Nice to meet you :)

**Comment by LefterisJP** [comment]
This is done.
