### ISSUE TITLE
macOS dev installation docs still mention Python 3.6

### ISSUE THREAD

**Issue by ulope** [raiden-network/raiden#3575]
## Problem Definition

The [macOS development setup instructions](https://raiden-network.readthedocs.io/en/stable/macos_install_guide.html#macos-development-setup) sill instruct users to use Python 3.6

**Comment by czepluch** [comment]
Are you fixing this? Otherwise I can do it, I am editing some of the docs right now anyway.

**Comment by palango** [comment]
That is already fixed in master, just not updated on readthedocs yet.

**Comment by LefterisJP** [comment]
Closing this as it's already fixed: https://raiden-network.readthedocs.io/en/latest/macos_install_guide.html#macos-development-setup
