### ISSUE TITLE
send_async / _handle_invite race

### ISSUE THREAD

**Issue by err508** [raiden-network/raiden#3588]
## Problem Definition

 There is a race condition with `send_async / _handle_invite`. Triggered if:
- Client A invites
- The invite triggers _handle_invite in Client B's transport
- Client A starts sending messages to Client B
- Messages are lost, as the invite was not processed yet

Appeared during #3124 as seen [here](https://github.com/raiden-network/raiden/pull/3385/files#diff-620b4fcbc4c15ae714616d075ea0b133R1186), related #2779, #3123.

**Comment by andrevmatos** [comment]
This is expected. Retry logic should handle this. How this was not the case?

**Comment by err508** [comment]
`_handle_invite` is (timewise) expensive for private rooms, the `send_async` retries go through before `_handle_invite` is completed.
