### ISSUE TITLE
Create tests for the CLI interface of Raiden

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#360]
Once the interface with raiden is defined we also need to have tests for it. At the moment all functionality under the [UI](https://github.com/raiden-network/raiden/tree/master/raiden/ui) directory is untested.

We need at least tests for:

- initalization of raiden at `app()` and `run()` in https://github.com/raiden-network/raiden/blob/master/raiden/ui/cli.py#L107

- all functions exposed in [console.py](https://github.com/raiden-network/raiden/blob/master/raiden/ui/console.py)

**Comment by hackaugusto** [comment]
closing in favor of https://github.com/raiden-network/raiden/issues/1408
