### ISSUE TITLE
Stable documentation is pointing to v0.100.1

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/raiden#3601]
The stable documentation (https://raiden-network.readthedocs.io/en/stable/) seems to point to v0.100.1 instead of v0.100.2 (at least it looks like this). v0.100.2 does not open when clicking on the link (https://readthedocs.org/projects/raiden-network/). Only when I click on https://raiden-network.readthedocs.io/en/latest/ it shows v0.100.2

**Comment by LefterisJP** [comment]
That's funny!

Hey @ulope I remember you mentioned something about not detecting that it's an actual release for v0.100.2. Could the check if nightly have problems for this release?

https://github.com/raiden-network/raiden/blob/15d636061df4852df5d0e77700a1eec6513db50d/docs/conf.py#L32-L51

**Comment by christianbrb** [comment]
After the v0.100.3 release, the [stable documentation](https://raiden-network.readthedocs.io/en/stable/) is still pointing to v0.100.1

**Comment by palango** [comment]
@christianbrb It works for me, have you tried resetting your browsers cache?

**Comment by christianbrb** [comment]
@palango Did the job, thanks :-)
