### ISSUE TITLE
Add docs for PFS / MS

### ISSUE THREAD

**Issue by rakanalh** [raiden-network/raiden#3607]
## Introduction

Current documentation provides a step by step tutorial on how to run Raiden on mainnet. However, with the upcoming integration with PFS / MS, the documentation should also describe how to run/activate those services so that a Raiden could make use of those services.

**Comment by palango** [comment]
Documentation for the services is tracked here: https://github.com/raiden-network/raiden-services/issues/193

**Comment by czepluch** [comment]
@palango Can you link the docs just created for the MS/PFS to the raiden read the docs?

**Comment by czepluch** [comment]
Maybe we shouldn't do it yet though.

**Comment by palango** [comment]
Yesah, I guess it's not ready for prime time. But foir reference: the docs can be found here: https://raiden-services.readthedocs.io/en/latest/
