### ISSUE TITLE
Check dict serialization of messages

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden#3614]
While working on #3612 @konradkonrad found some fields (token amounts in this case) that were serialized as integers but should have been strings for accuracy reasons (see https://github.com/raiden-network/raiden/pull/3612/commits/acbb896ee20481cebfb6e4a0eb14a5ee67d94b4b)

I fixed on other occurrence of this issue (where only one conversion was done) but all messages should be checked for this. 

A awesome thing to do would be to write a linter to check this and/or have a json serializer that automatically converts all `ints`/`bytes` to proper strings.

**Comment by rakanalh** [comment]
@palango is this issue still valid?

**Comment by palango** [comment]
If nobody did this then yes.

**Comment by andrevmatos** [comment]
Just FYI, related: https://github.com/raiden-network/light-client/pull/194#discussion_r298202190
In the LightClient, current implementation uses `io-ts` schemas which declare the BigNumber types and support decoding them both from JSON numbers or strings.

**Comment by palango** [comment]
Fixed in 8ae95a6c6cc8282f8578e8f6ccc1298d77dd83ad
