### ISSUE TITLE
Clarify UnrecoverableErrors

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/raiden#3645]
## Abstract

During discussions for https://github.com/raiden-network/raiden/issues/3268 , https://github.com/raiden-network/raiden/issues/2885 , and https://github.com/raiden-network/raiden/issues/3516 it became clear there are two overlapping concepts at play:

- Programming errors that should be detected and crash our test system, but not necessarily the client (currently done with the `--environment-type` flag).
- Unrecoverable errors, were we can't fix a broken expectation (usually special cases DB exceptions).

These two cases should be handled differently.

## Motivation

ATM one exception is used to represent both cases, and that can lead to confusion and invalid code.

## Specification

- Introduce a new exception `BrokenPrecondition` which should be raised like an assert but for external systems. This should be used in the circumstances describe [here](https://github.com/raiden-network/raiden/issues/3268#issuecomment-465644351).
- Keep the `UnrecoverableError` but use it in more constrained circumstances, e.g. when the database is corrupted, or the Blockchain client changes chain_id.

## Backwards Compatibility

This is completely backwards compatible.

**Comment by rakanalh** [comment]
`BrokenPreconditionError` was introduced.
