### ISSUE TITLE
initiator_init and mediator_init not passing privkey param

### ISSUE THREAD

**Issue by rakanalh** [raiden-network/raiden#3660]
## Problem

The functions `initiator_init` and `mediator_init` are not passing `routing.get_best_routes` the required private key. Which means that in case PFS was enabled, these two functions will always fall back to internal routing and skipping PFS altogether.

## Proposed Solutions
Either:
1. Pass privkey from the `initiator_init` and `mediator_init` to the routing module call.
2. Or, move the call to `get_best_routes` outside of the `*_init` functions.

**Comment by karlb** [comment]
Related to this, I would like to ask why this has not been caught by a test. Generally not contacting the PFS should be a rather obvious failure mode.
