### ISSUE TITLE
Break app/ui.py into smaller unit testable components

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#3677]
## Problem Definition

A lot of bugs are seen in the startup of Raiden with different arguments combinations. Smoke tests can't cover all the cases.

## Task

Break the startup of Raiden into different unit testable components and make unit tests for them.

**Comment by LefterisJP** [comment]
Things that can be found when we properly break the module up: https://github.com/raiden-network/raiden/pull/3688

**Comment by LefterisJP** [comment]
As a first step I simply opted for breaking parts of the startup into smaller function and unit testing them, since that code is simply not covered at all.

That alone uncovered numerous problems: https://github.com/raiden-network/raiden/pull/3732

**Comment by LefterisJP** [comment]
I did what I was planning to do for this issue in https://github.com/raiden-network/raiden/pull/3732

I will not work on it any further. 

@hackaugusto we can either keep it open for someone to implement your suggestions or move them to a new issue and close this one.

**Comment by rakanalh** [comment]
Closing issue as this has been improved. We can create further more detailed issues if needed.
