### ISSUE TITLE
Create a guide for deployment on private networks

### ISSUE THREAD

**Issue by pirapira** [raiden-network/raiden#3682]
## Abstract

This issue keeps track of creating a guide for using Raiden on a private network.

## Motivation

Some people are trying to use Raiden on private networks but reporting problems and crashes.

For them to prepare pull-requests, the guide should work with the `master` branch of `raiden`.

**Comment by pirapira** [comment]
Resources:

* https://github.com/kelsos/test-environment-scripts
* https://github.com/raiden-network/raiden/issues/3244#issuecomment-462803015

**Comment by pirapira** [comment]
I'm trying to follow Kelsos's script. Currently on https://github.com/kelsos/test-environment-scripts/issues/4 .

**Comment by pirapira** [comment]
I'm trying to follow https://github.com/raiden-network/raiden/issues/3244#issuecomment-462803015.  Currently on https://github.com/raiden-network/raiden-contracts/issues/777 .  The problem seems to be raiden-contracts is too old.

**Comment by pirapira** [comment]
raiden-contracts package is old because raiden 0.100.2 specifies so.

> raiden 0.100.2 has requirement raiden-contracts==0.8.0, but you'll have raiden-contracts 0.15.0 which is incompatible.
> raiden-libs 0.1.16 has requirement raiden-contracts==0.8.0, but you'll have raiden-contracts 0.15.0 which is incompatible.

**Comment by pirapira** [comment]
So I should not have said `pip install raiden` but I had to install `raiden` from `master`.

**Comment by pirapira** [comment]
I hit https://github.com/raiden-network/raiden-contracts/issues/784 right now.

**Comment by pirapira** [comment]
This means `raiden` should also use `click-7.0`.

**Comment by pirapira** [comment]
I'm also seeing a "No such file or directory".  Perhaps I should install `raiden-contracts` from under `xud-eth`.
```
Deployment info from /home/yoichi/src/raiden-contracts/raiden_contracts/data_0.3._/deployment_private_net.json has been verifiedand it is CORRECT.
{
    "EndpointRegistry": "0x48bE1Dfb0B34EB4B9b908b32b9f9501Adaa6dD56",
    "SecretRegistry": "0x4176e8fafA92381aaD43941BBC0467b114A94704",
    "TokenNetworkRegistry": "0x31304157623A394Cb8517B588cff993e8C327B6B"
}
getting tokennetworkregistry address
cat: raiden_contracts/data_0.3._//deployment_private_net.json: No such file or directory
```

**Comment by pirapira** [comment]
Now I hit https://github.com/raiden-network/raiden-contracts/issues/787 .  I think this fix should be worth a new release.

**Comment by pirapira** [comment]
At least I can start the Raiden client on a private network.  I should turn this into a guide already.

**Comment by pirapira** [comment]
Now I hit https://github.com/raiden-network/raiden/issues/3745

**Comment by pirapira** [comment]
I asked if I can use `genesis.json` by @offerm.  https://gitter.im/raiden-network/raiden?at=5cac703e93fb4a7dc2fc87ba

**Comment by pirapira** [comment]
I should already open a work-in-progress PR.

**Comment by pirapira** [comment]
Now I hit https://github.com/raiden-network/raiden-contracts/issues/852

**Comment by pirapira** [comment]
Now I hit https://github.com/raiden-network/raiden/issues/3244

**Comment by pirapira** [comment]
The guide is available here: https://github.com/pirapira/raiden/blob/private-chain/docs/private_net_tutorial.rst

It works when #3810 is merged.

**Comment by pirapira** [comment]
@christianbrb @konradkonrad who needs to see the private chain deployment guide?

**Comment by christianbrb** [comment]
@pirapira Cool :-) @agatsoh could test it

**Comment by pirapira** [comment]
@agatsoh please try https://github.com/pirapira/raiden/blob/private-chain/docs/private_net_tutorial.rst

**Comment by karlb** [comment]
See https://raiden-network.readthedocs.io/en/latest/custom-setups/private_net_tutorial.html
