### ISSUE TITLE
Create channel on private network  - zero balance

### ISSUE THREAD

**Issue by offerm** [raiden-network/raiden#3685]
Using `master`, private eth network, contracts 0.10.1:

Created with a balance of 5500:
```
[]+ curl -i -X PUT http://localhost:5001/api/v1/channels -H 'Content-Type: application/json' --data-raw '{"partner_address": "0x133499f529A8D7cF00D8C5f7E73841DDB62b9Ca3", "settle_timeout": 500, "token_address": "0x352E04105F25898C9e1dd8Ee5f277208b4df003B", "balance": 5500}'
HTTP/1.1 201 CREATED
mimetype: application/json
Content-Type: application/json
Content-Length: 325
Date: Tue, 26 Mar 2019 15:09:27 GMT

{"reveal_timeout": 50, "state": "opened", "partner_address": "0x133499f529A8D7cF00D8C5f7E73841DDB62b9Ca3", "token_address": "0x352E04105F25898C9e1dd8Ee5f277208b4df003B", "settle_timeout": 500, "balance": 0, "token_network_identifier": "0x0dB304Ac3cE08259F1f7453D5d2cE12551EdA20A", "channel_identifier": 1, "total_deposit": 0}
```

checking with `channels` also shows a balance of zero

```
(raiden) admins-MacBook-Pro-2:xud-eth admin$ curl -i http://localhost:5002/api/v1/channels
HTTP/1.1 200 OK
mimetype: application/json
Content-Type: application/json
Content-Length: 327
Date: Tue, 26 Mar 2019 15:12:28 GMT

[{"partner_address": "0x4F6799E2341379eA52213919622B9bEc80a1b655", "token_network_identifier": "0x0dB304Ac3cE08259F1f7453D5d2cE12551EdA20A", "settle_timeout": 500, "reveal_timeout": 50, "state": "opened", "balance": 0, "total_deposit": 0, "channel_identifier": 1, "token_address": "0x352E04105F25898C9e1dd8Ee5f277208b4df003B"}]
```

**Comment by rakanalh** [comment]
Hello @offerm,

Thanks for reporting this issue.

Could you please provide more information:
1. How to reproduce this issue
2. Were you using a private chain / a testnet or mainnet?
3. In case of 2 being a testnet or mainnet... were you using our already-deployed contracts? or did you deploy your own?

**Comment by offerm** [comment]
Ho @rakanalh 

1.  See above in the issue description. I reproduced it by using curl or create a channel with a balance  of 5500. Yet, the response (201) shows a balance of 0.
2. I'm using a private chain (geth).
3. N/R

I reproduced this problem with contracts version 0.4.0 (production) too.

I can give you access to private chain if you like (and some ether to play with).

**Comment by LefterisJP** [comment]
@offerm do you by any chance have the logs of the node where this happened? We can see a lot from the logs.

**Comment by LefterisJP** [comment]
@offerm Scratch the above.

You have a mistake in the API call.

The required argument for balance is called `total_deposit`. See the API docs [here](https://raiden-network.readthedocs.io/en/latest/rest_api.html?highlight=API#put--api-(version)-channels)

Does that satisfy the question/problem? If yes please close the issue.

**Comment by rakanalh** [comment]
Ahh yea i also didn't spot that. Closing this issue in favor of #3861

**Comment by offerm** [comment]
thanks @rakanalh  and @LefterisJP .

Am I using the wrong doc? I took the API from here https://raiden-network.readthedocs.io/en/stable/api_walkthrough.html#opening-a-channel

**Comment by rakanalh** [comment]
@offerm you're looking at the stable docs where we had that mistake in the documentation. This was fixed and looking at the "latest" version of the documentation, the curl call is defined properly:
https://raiden-network.readthedocs.io/en/latest/api_walkthrough.html#opening-a-channel
