### ISSUE TITLE
With solidity v >= 0.5.5  rpc gas estimation fails

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#3693]
While working on making raiden properly work with parity (https://github.com/raiden-network/raiden/issues/3565) I noticed that locally one of the assumptions tests was failing [here](https://github.com/raiden-network/raiden/blob/master/raiden/tests/integration/rpc/test_assumptions.py#L137) also with geth.

I then tried it out with master and it also fails there. The failures seem to happen with `solc >= 0.5.5`, which is why CircleCI does not see this as we are using v0.5.4 there.

Something must have changed in the way ABI is generated since our test contract's test function looks like this:

```solidity
    function ret() pure public returns (uint) {
        return 1;
    }
```

and should never cause a gas estimation failure.

**Comment by rakanalh** [comment]
Is this still the case? @pirapira could you please advise here?

**Comment by pirapira** [comment]
0.5.9 didn't work https://github.com/raiden-network/raiden-contracts/issues/1155#issuecomment-520518080  I don't know why.
