### ISSUE TITLE
Check the to be registered token contract has totalSupply() function implemented

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#3697]
## Problem Definition

As seen [here](https://github.com/raiden-network/raiden/issues/3630#issuecomment-477558306) the way Raiden fails at token registration if the token does not follow the ERC20 token standard leaves a lot to be desired.

We can definitely provide a better error if the token does not follow the ERC20 interface.

## Task

The way that the contracts check that a "to-be-registered" token follows the ERC20 interface is by checking that they got the `totalSupply()` function implemented as seen [here](https://github.com/raiden-network/raiden-contracts/blob/401544cef31326d155f89d1de1c1519079a912df/raiden_contracts/data_0.11.0/source/raiden/TokenNetwork.sol#L251).

We should perform the same check in the client and fail early with a proper error (not an unrecoverable one if that happens

**Comment by hackaugusto** [comment]
Related: Validate the ABI for non-official deployments of the Raiden contracts #3744
