### ISSUE TITLE
Write a test for the netting capabilities

### ISSUE THREAD

**Issue by konradkonrad** [raiden-network/raiden#370]
One nice property of raiden is, that the channel between Alice and Bob forms a *netting* channel. That means that Alice can send payments to Bob exceeding her initial deposit:

`A.sent > A.deposit`

the condition for this to work is that Bob has also sent payments to Alice in the meantime, so that

`B.sent >= (A.sent - A.deposit)`.

I.e.:
```
A.deposit = 10
B.deposit = 10
A.send(10)  # at this point Alice's deposit is exhausted
A.send(5) --> fail
B.send(5)  # this replenishes the available tokens for Alice
A.send(5)  # is now possible
```

At settlement, Alice and Bob will receive their respective *netted balances*.

We should have a **simple** test case that exemplifies and ensure's this behavior (I couldn't find one on first glance through https://github.com/raiden-network/raiden/blob/master/raiden/tests).

**Comment by adrianbrink** [comment]
This issue should be closed.

**Comment by czepluch** [comment]
Thanks for point that out. @agatsoh Do you agree that this can be closed?

**Comment by LefterisJP** [comment]
Yes, there is a PR that solves the issue. @agatsoh Next time please remember to also close the issue after solving it :)
