### ISSUE TITLE
Master does not compile

### ISSUE THREAD

**Issue by offerm** [raiden-network/raiden#3705]
master does not compile as of 
```
commit ff8b01c81ffe774eadabcf8563d75122b1d3999b (HEAD -> master, raiden-network/master, origin/master, origin/HEAD)
Author: Lefteris Karapetsas <lefteris@refu.co>
Date:   Tue Mar 26 18:08:11 2019 +0100

    Use the service contracts provided via the CLI if they are given
```

looks like 

    services_contracts = dict()

is missing at line 298 of ui/app.py

@LefterisJP

**Comment by LefterisJP** [comment]
Argh that does it. Can't be touching this code without it being covered by proper tests.
Moved https://github.com/raiden-network/raiden/issues/3677 to top priority and will pick it up myself.

 I opened a PR for a fix for this for now: https://github.com/raiden-network/raiden/pull/3706

**Comment by offerm** [comment]
Just for my curiosity, why didn't merged your  PR workon_3678? It was OK
there.

**Comment by LefterisJP** [comment]
I don't know which PR you are referring to.
