### ISSUE TITLE
Return error when channel creation fails due to already existing channel

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#371]
If [`new_netting_channel()`](https://github.com/raiden-network/raiden/blob/bc4669b3dc58aa5947a0cf22792eb16a123090c3/raiden/network/rpc/client.py#L607) is called to create an already existing channel we should return some form of error.

TODO:

- [ ] Implement a check for existing channel with specific partner/asset combo and/or transaction failure and return failure in `new_netting_channel()`.
- [ ] Make a test for it. Possibly best place to put it would be as an extra assert [here](https://github.com/raiden-network/raiden/blob/bc4669b3dc58aa5947a0cf22792eb16a123090c3/raiden/tests/integration/test_blockchainservice.py#L78)

**Comment by adrianbrink** [comment]
Could we add a label ```work_in_progress```?

**Comment by palango** [comment]
This was fixed by #764
