### ISSUE TITLE
How does Raiden client check success/failure of an Ethereum transaction?

### ISSUE THREAD

**Issue by pirapira** [raiden-network/raiden#3717]
Sometimes, `transact()` does not throw any exceptions even when the transaction fails (for example for failing `require()`).  Can there be a piece of code in Raiden that sends a transaction but misses failures of transactions?

(A possible answer is: we always check events so we're fine.)

**Comment by andrevmatos** [comment]
IIRC, transactions have a `status` field which is `0` if transaction failed and `1` otherwise, which is checked while we're waiting for the tx to be mined, it should throw there if a `require` failed

**Comment by pirapira** [comment]
I see.

This came to my mind when a `transact()` didn't fire an exception in a test https://github.com/raiden-network/raiden-contracts/pull/794, suddenly when we specified `gas`.

**Comment by LefterisJP** [comment]
> IIRC, transactions have a status field which is 0 if transaction failed and 1 otherwise, which is checked while we're waiting for the tx to be mined, it should throw there if a require failed

Pretty much this. This is done here: https://github.com/raiden-network/raiden/blob/c690de8cc4d73e4b18525c2e61b63e635ca06aa3/raiden/network/rpc/transactions.py#L4
