### ISSUE TITLE
v.100-3-rc1 crashes in production mode

### ISSUE THREAD

**Issue by eorituz** [raiden-network/raiden#3723]
## Problem Definition

Node crashes on startup (I missed setting the environment to development):
`raiden-v0.100.3-rc1-linux-x86_64 --eth-rpc-endpoint X/X/X:8545 --keystore-path /X/X/X --network-id 42`
But nontheless I expect a propper error message

 
```
Raiden is running in production mode
Traceback (most recent call last):
  File "site-packages/raiden_contracts/contract_manager.py", line 207, in get_contracts_deployment_info
  File "pathlib.py", line 1176, in open
  File "pathlib.py", line 1030, in _opener
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/_MEIJibama/data_0.4.0/deployment_services_kovan.json'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "raiden-script.py", line 2, in <module>
  File "site-packages/raiden/__main__.py", line 11, in main
  File "site-packages/click/core.py", line 764, in __call__
  File "site-packages/click/core.py", line 717, in main
  File "site-packages/click/core.py", line 1114, in invoke
  File "site-packages/click/core.py", line 956, in invoke
  File "site-packages/click/core.py", line 555, in invoke
  File "site-packages/click/decorators.py", line 17, in new_func
  File "site-packages/raiden/ui/cli.py", line 494, in run
  File "site-packages/raiden/ui/runners.py", line 276, in run
  File "site-packages/raiden/ui/runners.py", line 95, in _start_services
  File "site-packages/raiden/ui/app.py", line 310, in run_app
  File "site-packages/raiden_contracts/contract_manager.py", line 213, in get_contracts_deployment_info
ValueError: Cannot load deployment data file: [Errno 2] No such file or directory: '/tmp/_MEIJibama/data_0.4.0/deployment_services_kovan.json'
[7600] Failed to execute script raiden-script
```

As soon as I set the development environment everything works fine:
`raiden-v0.100.3-rc1-linux-x86_64 --eth-rpc-endpoint X/X/X:8545 --keystore-path /X/X/X --network-id 42 --environment-type development`

### System Description

I used the latest binary: raiden-v0.100.3-rc1-linux-aarch64
and the bb-internal kovan node

**Comment by ulope** [comment]
The reason is that there were no services contracts for contracts version 0.4.0.
This should probably be handled in `get_contracts_deployment_info()`.

Ping @pirapira

**Comment by LefterisJP** [comment]
@pirapira This is not about an error message. There must be no error in that function. It should simply not return the services contracts. 0.4.0 is the red eyes version. At the moment master is broken for red eyes / production.

**Comment by pirapira** [comment]
@LefterisJP I don't know.  "If you ask for a non-existent thing, you get an error."  "No, I just asked for everything that there is."  "Well, you asked for both RAIDEN and SERVICES."  "No, ALL doesn't mean RAIDEN+SERVICES, ALL means everything that there are".  "ALL does mean RAIDEN+SERVICES, and you asked for SERVICES as well".

**Comment by pirapira** [comment]
@LefterisJP I think it's difficult because a single function `get_contracts_deployment_info()` does many different kinds of things.  It's simpler when `get_raiden_contracts_deployment_info()` and `get_service_contracts_deployment_info()` are two separate functions.

**Comment by ulope** [comment]
Is maybe that why there was the `services` parameter previously?

**Comment by pirapira** [comment]
@ulope yes, that approach gets messier when there are more than three modules.

**Comment by LefterisJP** [comment]
So the function has the following signature:

```
def get_contracts_deployment_info(
        chain_id: int,
        version: Optional[str] = None,
        module: DeploymentModule = DeploymentModule.ALL,
) -> Dict:
```

To me `ALL` means simply ALL modules you can find info about. And then the consumer of the function can check the returned dictionary to see what was found and act accordingly. This is exactly what I said in [this](https://github.com/raiden-network/raiden-contracts/issues/774#issuecomment-476547617) issue too.

> It's simpler when get_raiden_contracts_deployment_info() and get_service_contracts_deployment_info() are two separate functions.

No this is not gonna be simpler, as we would have to have a lot more conditionals and you move the logic out to the consumer of the function.

**Comment by pirapira** [comment]
> No this is not gonna be simpler, as we would have to have a lot more conditionals and you move the logic out to the consumer of the function.

Right.  I was thinking about "It is more important for the implementation to be simple than the interface" https://en.wikipedia.org/wiki/Worse_is_better but meh.   `ALL` will mean whatever there are.

**Comment by pirapira** [comment]
A fix is coming: https://github.com/raiden-network/raiden-contracts/pull/809  and then a `raiden-contracts` release.
