### ISSUE TITLE
Upgrade DEVELOPMENT_CONTRACT_VERSION to 0.11.0

### ISSUE THREAD

**Issue by pirapira** [raiden-network/raiden#3730]
where `setTotalWithdraw()` is available.

Also I saw a [test failure](https://circleci.com/gh/raiden-network/raiden/36188#tests/containers/10) when I did update to `0.11.0`. The cause of the failure should be investigated.

**Comment by LefterisJP** [comment]
This should only happen when we actually support withdraw in the client.

**Comment by pirapira** [comment]
I'll ask @rakanalh when he wants it, then.

**Comment by pirapira** [comment]
@LefterisJP but 0.11.0 is not deployed on the mainnet, so we'll find only interesting problems, not devastating problems.

**Comment by pirapira** [comment]
The mainnet-sync will be kept track in https://github.com/raiden-network/team/issues/377.

**Comment by LefterisJP** [comment]
Yes sure I am only talking about "interesting" problems. We got our hands full with problems at the moment and they kind of slow down the integration testing (every time we break the services guys have to wait) so I would like to keep the problem search space small.

**Comment by pirapira** [comment]
I see.  If you have many problems, fix them without changing anything.
