### ISSUE TITLE
Adjust routing-mode argument to specify if client publishes PFS updates when not using PFS

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#3735]
## Problem Definition

We discussed this in person an in a private issue and we came up with the following suggestion for a not so confusing argument that with a proper help text will allow people to set their client properly to publish updates to the PFS or not. thanks @konradkonrad

## Specification

`--routing-mode pfs|local|private` where

- `pfs` simply uses the PFS [**default**]
- `local` uses local pathfinding but does update PFS
- `private` uses local pathfinding and does not update PFS

As a user, I want to have an easy way to be used as a mediator, without requiring me to pay money to the PFS. Therefore I choose `local`.
As another user, I want to have an easy way to stay private and not publish my updates to the PFS and therefore I choose `private`

**Comment by konradkonrad** [comment]
Thanks for promoting this to a feature issue @LefterisJP :)
From my point of view, a benefit of this approach is, that it allows for meaningful startup configuration checks and helpful error messages. I.e:
- `--routing-mode=pfs` triggers the checks that all other PFS related configuration constraints are fulfilled, and outputs corresponding error messages
- `--routing-mode=local` would error if `--transport=udp` was set
- `--routing-mode=private` would trigger warnings/errors if any other PFS related flags were given

**Comment by ulope** [comment]
When implementing this please act on the comments in 343146445ad4f9e0c653a7991aa4a4fe5e2c5845
