### ISSUE TITLE
Utilize black tool for styling issues

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#3738]
## Problem Definition

As discussed in person and in the private Technical Debt issues, we should strive for automation of anything that can be automated and also for consistency across repositories in the tooling that we use.

Using black will handle the styling part of the consistency.

**Important**: Prioritization of this task should happen at a point when not too many big PRs are open to reduce conflicts. Also all contributors should be notified so that they can adjust their editor settings and/or precommit hooks.

## Task

- Adjust the minimal configuration of black to match our current style. (99 column size ... anything else adjustable?). Make sure we are consist with the [services black configuration](https://github.com/raiden-network/raiden-services/blob/master/Makefile#L3)
- Use black on the codebase and save the result
- Adjust CI and other linting to use black.
- If flake8 is not useful anymore after that remove it (or use the [flake8-black](https://pypi.org/project/flake8-black/) plugin). Essentially flake8 is a wrapper around `pycodestyle`, `pyflakes` and the [MCCabe](https://github.com/PyCQA/mccabe) script, so we should carefully see what we use/need from there.

**Comment by karlb** [comment]
In the services repo, we had to disable the `bad-continuation` pylint check because pylint and black had different opinions about how continuations are supposed to look. That should be OK, since formatting can't be bad after running black, anyway.
