### ISSUE TITLE
Add a TTL for the UDP messages

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/raiden#374]
### Problem

An initiator can try new routes at will, a new route is tried if the SecretRequest message is not received under a configurable timeout, when this happens the secret is discarded and makes the previous hashlock unusable.

Currently there is no way to inform the mediators that a given hashlock transfer was discarded by the initiator and that further tries to reach the target wont succeed.

### Solution

Add a time-to-live similar to TCP's TTL for the message to reach it's target.

Under a non byzantine operation:
1. For a direct transfer the TTL may be ignored, since the message is not mediated.
2. For a mediated transfer the TTL may be set to different values:
   1. If the initiator discards the secret after a timeout happens the TTL must be equal to this value.
   2. If the initiator does not discards the secret and tries more than one route simultaneously, then the TTL should be an approximation of the lock's expiration block.

Under byzantine behavior:
- The TTL might be set to a low value, which doesn't have negative effects
- The TTL is set to a value higher then the lock's expiration, this is the same as not using the TTL and doesn't have negative effects (if the lock has expired the TTL must be ignored).

### Considerations

The TTL is useful for the scenario `2.i` above.

The value of TTL does not interfere with the expiration time of a lock, meaning that if the TTL was not reached but the lock has expired the TTL is useless.

The TTL is only defined for the protocol messages, it has no implications for the Raiden signed messages, the only usage of this field is to improve the network efficiency, a mediator hop should not try to forward the payment because the initiator has discarded the secret and is trying a different route.

**Comment by rakanalh** [comment]
UDP Transport was removed. Closing
