### ISSUE TITLE
pip install -r requirments.txt -e . fails on a fresh clone

### ISSUE THREAD

**Issue by pirapira** [raiden-network/raiden#3745]
On a fresh virtualenv (Python 3.7), when I try `pip install -r requirements.txt -e .` it fails.

```
 $ mkdir priv_chain
 $ cd priv_chain
 $ virtualenv -p python3.7 env
 $ source env/bin/activate
 (env) $ git clone https://github.com/raiden-network/raiden
 (env) $ cd raiden
 (env) $ pip install -r requirements.txt -e .
```

```
Collecting pyyaml>=3.11 (from matrix-synapse==0.33.9->raiden==0.100.3rc2.dev55+g3eb936e4)
Collecting psycopg2>=2.6 (from matrix-synapse==0.33.9->raiden==0.100.3rc2.dev55+g3eb936e4)
  Using cached https://files.pythonhosted.org/packages/c7/ca/75236b17f1b951950ffc55d657c5aa408d3d0327a1b6c4c0f7cb16ef7e7b/psycopg2-2.8.tar.gz
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/psycopg2.egg-info
    writing pip-egg-info/psycopg2.egg-info/PKG-INFO
    writing dependency_links to pip-egg-info/psycopg2.egg-info/dependency_links.txt
    writing top-level names to pip-egg-info/psycopg2.egg-info/top_level.txt
    writing manifest file 'pip-egg-info/psycopg2.egg-info/SOURCES.txt'
    
    Error: pg_config executable not found.
    
    pg_config is required to build psycopg2 from source.  Please add the directory
    containing pg_config to the $PATH or specify the full executable path with the
    option:
    
        python setup.py build_ext --pg-config /path/to/pg_config build ...
    
    or with the pg_config option in 'setup.cfg'.
    
    If you prefer to avoid building psycopg2 from source, please install the PyPI
    'psycopg2-binary' package instead.
    
    For further information please check the 'doc/src/install.rst' file (also at
    <http://initd.org/psycopg/docs/install.html>).
    
    
    ----------------------------------------
```

**Comment by hackaugusto** [comment]
It looks like you're missing a dependency, postgresql. Also please add `-c constraints.txt` to your command line `pip install -r requirements.txt -c constraints.txt -e .`

**Comment by ulope** [comment]
That looks related to the synapse requirements.

I remember that psycopg2 had some plans to change the way they distribute binary packages. 

I’ll take a look at this.

**Comment by pirapira** [comment]
I started from scratch and added `-c constraints.txt` but I still see the same error.

**Comment by ulope** [comment]
Ok, this has a pretty nice chain of causes leading to the problem:
- We include `synapse` as a test dependency
  - Before `0.99` (we still use `0.33.9`, see #3387) it unconditionally depended on `psycopg2>=2.6`
    - Yesterday [psycopg2 `2.8` was released](http://initd.org/psycopg/articles/2019/04/04/psycopg-28-released/)
    - psycopg2 `2.8` no longer includes precompiled wheels [because](https://github.com/psycopg/psycopg2/issues/674) of [reasons](https://www.postgresql.org/message-id/CA%2Bmi_8bd6kJHLTGkuyHSnqcgDrJ1uHgQWvXCKQFD3tPQBUa2Bw%40mail.gmail.com)
      - They way they chose to solve this with a separate `psycopg2-binary` package really isn't optimal (because of the problem we're seeing here with 3rd party libraries requiring the base package)
- Our `constraints.txt` doesn't include the pinned test dependencies (at least it shouldn't, somehow a few managed to slip in) since we use it to build the `install_requires` list in `setup.py`

The solution is to fix our dev dependency pinning (and also upgrade to `synapse>=0.99`).

Luckily pip constraints files also support chaining / include (similar to how requirements can require others). That will allow us to add a constraints file that pins the dev dependencies and includes the regular one.

I'll prepare a PR for this.

**Comment by pirapira** [comment]
@ulope that's a wonderful diagnosis.  Thank you.
