### ISSUE TITLE
`QueueIdentifier` is underspecified and allows for potential collisions

### ISSUE THREAD

**Issue by konradkonrad** [raiden-network/raiden#3748]
### Problem
Currently a `QueueIdentifier` is specified by only
```python
def __init__(self, recipient: Address, channel_identifier: ChannelID)...
```
If a node has channels with the same `participant` in several token networks (i.e. for token `A` and token `B`, that happen to have the same `channel_identifier` (i.e. channel counter per partner per token network), this can lead to collisions in the queue identifier.

Since messages are ordered per queue, this can lead to unwanted interactions, i.e. 

- if the channel for token network `A` is stuck, messages for the channel in token network `B` will be stuck as well.

- closing the channel in `A` _could_ clear the queue in `B` as well (not verified, but possible)

### Proposed solution

Following the effort from #3493 the QueueIdentifier should also make use of the `CanonicalIdentifier`.

**Comment by andrevmatos** [comment]
First point doens't happen, matrix has a very loose concept of queues, as all the queued (and available after exponential timeout) are sent on every retry loop, and as well processed by the receiver (in order, but despite processing failures), so one channel stuck shouldn't affect any other message in the same queue.
Second point though can be very real: https://github.com/raiden-network/raiden/blob/3eb936e4ad8a744c7d54643e01860e2bf0652207/raiden/transfer/node.py#L594-L599
