### ISSUE TITLE
[ARM] Provided address 0x... for token network registry contract does not contain expected code.

### ISSUE THREAD

**Issue by calinchiper** [raiden-network/raiden#3756]
I'm using a private network that was initially bootstrapped on my laptop[Ubuntu].  I've deployed Raiden contracts using Raiden deployer. On my laptop it works fine. 

I've also connected a Raiden Rasperry PI node but when I start Raiden it shows me the next error:
`Error: Provided address 0x9bb81a9dDeF8bCFA7b19A256c4F04A11C5556E46 for token network registry contract does not contain expected code.`

Also if I connect PI's raiden node to laptop eth-rpc-endpoint it works fine

On my Rasperry I've started a geth using: 
`geth --datadir . --rpc --rpcapi eth,net,web3,txpool --networkid 4224 --rpccorsdomain "*" --syncmode fast--nodiscover --port 30304`

Raiden version: v0.100.2 - Pluto
Raiden contracts version: 0.4.0 (also tried with 0.3.0)

`

**Comment by LefterisJP** [comment]
Hello @calinchiper. How are you running Raiden?

**Comment by calinchiper** [comment]
@LefterisJP 
I'm using a shell file:

`./raiden --keystore-path $KEY_STORE_PATH --network-id 4224 --accept-disclaimer --rpc --api-address $API_ADDRESS --web-ui --environment-type development --console --no-sync-check --tokennetwork-registry-contract-address $TokenNetworkRegistry --secret-registry-contract-address $SecretRegistry --endpoint-registry-contract-address $EndpointRegistry --gas-price 10000000000 --transport udp
`

where `./raiden` is the ARM build from Releases Page

**Comment by LefterisJP** [comment]
So some questions:

- Why are you using the udp transport?
- Why are you providing the `--console` argument?
- You are also providing the `--no-sync-check`. Are you sure that the contracts are deployed at the ehtereum addresses you are giving as arguments and that the ethereum client you are connecting to locally is synced? The reason I am asking is that the error you are getting is pretty much saying there is nothing deployed at the token network registry address.

**Comment by calinchiper** [comment]
@LefterisJP 
`Why are you using the udp transport?` 


> So some questions:
> 
> * Why are you using the udp transport?
> * Why are you providing the `--console` argument?
> * You are also providing the `--no-sync-check`. Are you sure that the contracts are deployed at the ehtereum addresses you are giving as arguments and that the ethereum client you are connecting to locally is synced? The reason I am asking is that the error you are getting is pretty much saying there is nothing deployed at the token network registry address.

**Comment by LefterisJP** [comment]
>  Do you you think that in my context a matrix transport protocol could be ok ?

Yes running a local matrix server or even using one of the predefined ones should be fine.

> I'm using the udp transport because I saw that matrix transport protocol is considered experimental

Can you point me to where you saw this? If we still have it somewhere in the docs then that means it's probably outdated.

> Using a private network without --no-sync-check it gives me an error(says that I should pass this argument)

Aha I see, so yes I had not know this is a private network. Then you need this argument.


> The Rasperry PI Geth node is in sync with my laptop's geth node. eth.syncing returns false

Okay I see. So let's make a check then. Can you open the raspberry PI's geth node with the `console` command to get an interactive prompt? Then write: `eth.getCode("0x9bb81a9dDeF8bCFA7b19A256c4F04A11C5556E46")`. What does this return? If it returns nothing then it means one of the following is happening:

1. your raspberry PI geth node is not synced
2.  It is synced to a different network
3. The contract has not actually been deployed to that address

**Comment by calinchiper** [comment]
> Can you point me to where you saw this? If we still have it somewhere in the docs then that means it's probably outdated.

When you access the help section from Raiden by `raiden --help` you'll see:
`--transport [udp|matrix]                     Transport system yo use. Matrix is experimental.   [default: matrix]`

> Okay I see. So let's make a check then. Can you open the raspberry PI's geth node with the console command to get an interactive prompt? Then write: eth.getCode("0x9bb81a9dDeF8bCFA7b19A256c4F04A11C5556E46"). What does this return? If it returns nothing then it means one of the following is happening:

It prints all the a bunch of hex numbers. I think it's the hex encode of the compiled code.

I'll try also with parity.

**Comment by LefterisJP** [comment]
> It prints all the a bunch of hex numbers. I think it's the hex encode of the compiled code.

Okay so that means that there is a contract in that code but that it does not match the ABI (does not contain the `contract_version` attribute.

How have you deployed the contracts? And which version of the contracts did you deploy?

**Comment by calinchiper** [comment]
"0.3._"

**Comment by LefterisJP** [comment]
@calinchiper yes but how did you do it? What steps did you follow And why 0.3._? The production version is 0.4.0.

**Comment by calinchiper** [comment]
I followed the guide:

**Comment by calinchiper** [comment]
@LefterisJP Can I close it due the fact is more related to `geth` than `raiden`?

**Comment by LefterisJP** [comment]
Ofcourse you can close it but I really am not sure why you would see this behaviour with geth. I am not aware of any bug that can cause this.
