### ISSUE TITLE
Backward-cancellation of a locked transfer

### ISSUE THREAD

**Issue by pirapira** [raiden-network/raiden#3772]
Why don't we cancel a LockedTransfer and send another RefundTransfer?  We get funds locked both ways, instead of no funds locked.

**Proposal**

Let's say A has sent B a locked transfer with secret hash H.

1. B sends A "(GiveUp H)_B" signed
2. A sends B "(CancelTransfer H (GiveUp H)_B)_A" signed

Then, the channel from A to B does not contain the lock H anymore.

Is there any problems?

**Comment by pirapira** [comment]
@hackaugusto needs to tell me the zen of the thing.

**Comment by pirapira** [comment]
But then, if the two parties can unlock the amount, the locked amounts cannot be relied for a mediated transfer.

**Comment by pirapira** [comment]
That's OK though.  In a mediated payment A-->B-->C-->D, if B and C agree and cancel B-->C only, it's C who get's the pain, so the protocol can allow that.

**Comment by pirapira** [comment]
For my protocol, TokenNetwork needs to implement a challenge-response phase on locks.

**Comment by hackaugusto** [comment]
This is an alternative approach to refund transfers

**Comment by hackaugusto** [comment]
Related `Proposal for a new type of refund/cancellation` https://github.com/raiden-network/raiden-contracts/issues/1216
