### ISSUE TITLE
Use specific types to represent blockchain events

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/raiden#3773]
## Abstract

Currently the Raiden code base has a generic `Event` type:

https://github.com/raiden-network/raiden/blob/3fdd02a15a845c3958de3fd2d0fd5b2af1f62ff2/raiden/blockchain/events.py#L197-L206

This does not have any information about the fields and their types. To improve this we should use the same approach as from the raiden-services project, and have a namedtuple for each event:

https://github.com/raiden-network/raiden-services/blob/2cb63cda6cc0a4542466adad083db7c1a5221aff/src/raiden_libs/events.py

## Motivation

Improve type checking and linting.

## Specification

Reuse the code from Raiden services. Ideally when these events are introduced they would be already versioned, since changes to the smart contracts may also change the events.

## Backwards Compatibility

This is just a internal change, completely backwards compatible.

**Comment by rakanalh** [comment]
Related #3869

**Comment by karlb** [comment]
We use dataclasses and have plenty of specific Event subclasses, now.
