### ISSUE TITLE
Improve token swap interface

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/raiden#379]
## Problem Definition

The atomic swap has a confusing api:

    def exchange(self, from_asset, from_amount, to_asset, to_amount, target_address):
    def expect_exchange(self, identifier, from_asset, from_amount, to_asset, to_amount, target_address):

The arguments in `expect_exchange` are the same as the arguments from `exchange` meaning that the node calling `expect_exchange` has the arguments swapped.

## Solution

Write better documentation.

## Tasklist

- [ ] Doc strings for both functions following (related: issue #465  )

**Comment by hackaugusto** [comment]
This is a suggestion for the API:

    atomic_swap.receive(token1, amount1).in_exchange_for(token2, amount2).expect()
    atomic_swap.receive(token2, amount2).in_exchange_for(token1, amount1).start()

**Comment by berndbohmeier** [comment]
slightly different from what Max suggested, another option would be 
def exchange(self, our_token, our_amount, their_token, their_amount, target_address):
def expect_exchange(self, identifier, our_token, our_amount, their_token, their_amount, target_address):

**Comment by tomaaron** [comment]
@hackaugusto what type is atomic_swap in your suggestion?

**Comment by hackaugusto** [comment]
`atomic_swap` may be an instance of `RaidenAPI`, the method `RaidenAPI.receive` would return a partially initialized class to implement the method chaining with the `in_exchange_for`, `expect`, and `start` methods.

**Comment by tomaaron** [comment]
@hackaugusto Thank you for clarifying. I tried to implement your suggestion but it remains unclear for me how to init the `StartExchangeTask` or `Exchange`. As in the current implementation it leads to errors. How would you get `target_address` in your approach? And what is the `identifier`?

**Comment by tomaaron** [comment]
As I already mentioned before I started to implement the suggestion by @hackaugusto but as @LefterisJP pointed out in gitter I should take care of another issue because now it's not clear how to init `StartExchangeTask` and `Exchange`. I just want to leave my implementation here and maybe continue if it is clear how to init `StartExchangeTask` and `Exchange`. Here is the link:
[Implementation](https://github.com/tomaaron/raiden/commit/8bc14e67d24c77ff3271475b8142b23cf14aa35a)

**Comment by hackaugusto** [comment]
closing since this was worked on.
