### ISSUE TITLE
Make mypy happy with the raiden client codebase

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#3798]
## Problem definition

Running mypy on the client code base yields a gazillion errors. Having typed code is really useful and mypy can find a lot of bugs. We need to type the entire code base to prevent bugs.

## Task

- Piece by piece fix all mypy errors on the code base.
- Enable complete mypy check in the CI.

**Comment by LefterisJP** [comment]
Due to my imminent long vacation I am unassigning myself off this issue. A lot of work has been done and not (too) much remain. Only 362 line complaints remain in the entire project

```
mypy --ignore-missing-imports raiden/ | wc -l 
362
```

**Comment by konradkonrad** [comment]
As of now:
- there are only 301 mypy errors left, and those are only below `raiden/tests`.
- we will run mypy on `make lint` over the complete codebase (excluding everything below `raiden/tests`)

**Comment by konradkonrad** [comment]
Some stats @rakanalh 
Prior to work started on this issue (i.e. before 2f02549dcac131d109d2d51b16ea17ecf99d15b4)
```
mypy --ignore-missing-imports raiden|grep -v raiden.tests|grep error|wc -l
549  # without tests
mypy --ignore-missing-imports raiden|grep error|wc -l 
844  # with tests
```
Now, after #3983 was merged it should be `0` without tests, and `301` with tests (see output from `make lint`)
