### ISSUE TITLE
Design changes for cross-TokenNetwork mediated transfers

### ISSUE THREAD

**Issue by pirapira** [raiden-network/raiden#3814]
## Abstract

When TokenNetwork contract upgrades, if Raiden clients can talk to multiple versions of TokenNetwork, the payment network can be kept in whole.

## Motivation

When TokenNetwork contract upgrades, naively, the Raiden payment network will be split into the channels on the old version and the channels on the new version. One way to solve that problem is to make the Raiden client speak with both the old version and the new version of TokenNetwork.

## Specification

This issue keeps track of designing the changes in Raiden client, in order to make the Raiden client speak with multiple instances of TokenNetworks, and opening the GitHub issues for implementing the changes.

**Comment by karlb** [comment]
Closed in favor of https://github.com/raiden-network/raiden/issues/6506 and its sub issues.
