### ISSUE TITLE
Handle blocking estimate gas on parity

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/raiden#3835]
## Abstract

Parity `eth_estimageGas` RPC gas blocks indefinitely. Using the following test code:

```solidity
pragma solidity ^0.5.4;

contract RpcWithStorageTest {
    uint256[] data;
    function waste_storage(uint256 iterations) public {
        uint256 i;
        for (i=0; i<iterations; i++) {
            data[data.length++] = i;
        }
    }
}
```

And doing `contract_proxy.estimate_gas(block_identifier, 'waste_storage', number_iterations)` with a large enough `number_iterations` will block for a long time. On a simple test where `number_iteartions` was approximately `9902771802`, the gas estimation blocked for more than 8 minutes before I killed it.

## Motivation

This can easily be a sort of thread starvation.

## Specification

This should at least be handled with a `gevent.Timeout`, however I do not know what is the impact on cpu usage for the queried ethereum node.

## Backwards Compatibility

this should be backwards compatible

**Comment by hackaugusto** [comment]
this is the relevant stack trace for the above: https://gist.github.com/hackaugusto/94746b62261e953941fff9e93f082c20

**Comment by hackaugusto** [comment]
I don't understand why parity blocks. I did a tiny test where I gradually increase the number of iterations to figure out when the estimation blocks.

These are the successful tests:
```
2019-04-16 14:49:03.546815 number_iterations=24732 startgas=639221403 current_gas_limit=9893101128
2019-04-16 14:49:11.771052 number_iterations=32977 startgas=852313428 current_gas_limit=9893101128
2019-04-16 14:49:20.288655 number_iterations=35332 startgas=913178403 current_gas_limit=9893101128
2019-04-16 14:49:29.591835 number_iterations=38050 startgas=983425113 current_gas_limit=9893101128
2019-04-16 14:49:59.528823 number_iterations=41221 startgas=1065379608 current_gas_limit=9893101128
```
The estimation is for `44967` iterations blocks. There should be no problems to fit a transaction for this many iterations (according to gas_limit), and the number of opcodes is not considerably higher than the test for `41221` iterations.

**Comment by palango** [comment]
Is this something we should report upstream?
