### ISSUE TITLE
Raiden node gets an error on starting rc4 release

### ISSUE THREAD

**Issue by agatsoh** [raiden-network/raiden#3856]
I am running raiden with an old account on kovan. I have been asked to delete any files starting with `v21` if i encounter any errors while starting raiden. Hence i start the raiden node like this 
```
./raiden-v0.100.3-rc4-linux-x86_64 --eth-rpc-endpoint http://10.104.6.6:8545 --api-address "http://localhost:5001" --keystore-path ~/.ethereum/keystore/ --address 0xEe36AEF6C98a992569e34CbCb46dBca49b494483 --network-id kovan --environment-type production --log-file node-Ee36AE-kovan.17Apr2019.log --log-config "raiden:debug"
```

I encounter this error https://gist.github.com/agatsoh/ce8ba69d7d8e33be5f753cfab1cb56dc
I delete all the db files starting with `v21` and again start raiden but encounter the error again. 
Raiden node has again recreated the new db files. I delete them again and restart but its the same error again. I am attaching the log files as follows.

[node-Ee36AE-kovan.17Apr2019.log](https://github.com/raiden-network/raiden/files/3090737/node-Ee36AE-kovan.17Apr2019.log)

The raiden debug logs
[raiden-debug_2019_04_17.zip](https://github.com/raiden-network/raiden/files/3090757/raiden-debug_2019_04_17.zip)

Some findings from the debug logs

```
{"event": "Connection pool is full, discarding connection: 10.104.6.6", "logger": "urllib3.connectionpool", "level": "warning", "timestamp": "2019-04-17 15:04:44.288998"}
```

The current db files as they stand on my machine right now. This is the zip file of the `.raiden/node_ee36aef6` folder.
[node_ee36aef6.zip](https://github.com/raiden-network/raiden/files/3090764/node_ee36aef6.zip)

```
uname -a
Linux krishna-pc 5.0.7-arch1-1-ARCH #1 SMP PREEMPT Mon Apr 8 10:37:08 UTC 2019 x86_64 GNU/Linux

command -v solc && solc --version
/usr/bin/solc
solc, the solidity compiler commandline interface
Version: 0.5.7+commit.6da8b019.Linux.g++

```

**Comment by LefterisJP** [comment]
The connection pool warnings are unrelated.

The error is due to querying pruned blocks that is not guarded by the `self.client.can_query_state_for_block(block_identifier)` check at `detail_participants()`.

There are two choices:

1. Short temporary solution is to add the check also in the calls to `detail_participants` and handle that particular case.
2. The proper solution for this and any other such problems is https://github.com/raiden-network/raiden/issues/3778
