### ISSUE TITLE
password file is not properly read from file

### ISSUE THREAD

**Issue by offerm** [raiden-network/raiden#3857]
Latest master.

I'm using --password-file passwd_file

the file has this:
```
123123123
```

created with 'vi'

`wc passwd-file` shows:
```
admins-MacBook-Pro-2:keystore admin$ wc ../../passwd_file 
       1       1      10 ../../passwd_file
```

There is an extra \n at the end of the line.

This was working fine until 09cc57b48619c629ef7ee275283bf46ab62e77f7 @hackaugusto  

password.strip() takes care of it.

**Comment by andrevmatos** [comment]
I think @hackaugusto may have missed my reply [here](https://github.com/raiden-network/raiden/commit/d2e9d340da80412d57abe74dc05ca7fac57956d0#r33166992)

**Comment by LefterisJP** [comment]
yeah this seems like it. I will create a test and fix.
