### ISSUE TITLE
Permissive source routing

### ISSUE THREAD

**Issue by Dominik1999** [raiden-network/raiden#3863]
## Abstract

We need a specification for permissive source routing every important stakeholder agrees on. Please update the Raiden spec.

Due date: End of Iteration "Spring Cleaning" (03.05.2019)

## Motivation

Lower the cost of mediation by reusing the path from the initiator.

## Specification

- Drop support to the UDP transport (it does not support variable length messages, ATM) #3894
- Implemented Payment metadata #1202
- Add the path as metadata from the initiator
- Initially mediator should fail if matching proposed routes can not be used
  - This should be improved, the mediator can query the PFS again if the route can't be used.
- Mediators should query the PFS if the message does not contain any routing metadata
- The hops should not trim the paths

## Backwards Compatibility

This change is backwards compatible, any compatibility problems are introduced/handled by #1202

**Comment by palango** [comment]
Some questions for clarification

> The hops should not trim the paths

This means that the metadata should not be touched by the mediators, right? Should we send a checksum for the metadata so that the receiver can check this?

Attacks:
We found some ways to misuse this to lock large amounts of channel capacity. Will this include some simple ways of mitigating these (like a max. path length)?

**Comment by lullis** [comment]
From the spec:
> Implemented Payment metadata #1202 

Done in #4165 

> Add the path as metadata from the initiator

Done in #4165 
> Initially mediator should fail if matching proposed routes can not be used

Done in #4165. Sends refund transfer

> The hops should not trim the paths. 

Done in #4165. The current implementation only manipulates the one route that is being traversed, leaving the others intact.)

**Comment by konradkonrad** [comment]
> The hops should not trim the paths. 

~~Done in #4165. The current implementation only manipulates the one route that is being traversed, leaving the others intact.)~~ Actually #4165 currently
- trims the paths
- only forwards routes which contain the next hop

**Comment by lullis** [comment]
@palango, fixed https://github.com/raiden-network/raiden/pull/4165#discussion_r292820475 with latest commit
