### ISSUE TITLE
Mypy: get consistent styles with services

### ISSUE THREAD

**Issue by Dominik1999** [raiden-network/raiden#3866]
## Abstract

Get stricter mypy setting and aligned with the services team

Due date: End of Iteration "Spring Cleaning" (03.05.2019)

**Comment by LefterisJP** [comment]
Hmm what exactly do you mean by mypy style here?

**Comment by Dominik1999** [comment]
This (and the other issues I created on Thursday) are dummy issues. @rakanalh will work them out and describe that technically correct

**Comment by palango** [comment]
Created more concreate #4032 and #4033
