### ISSUE TITLE
Mypy: enable whole tool everywhere

### ISSUE THREAD

**Issue by Dominik1999** [raiden-network/raiden#3867]
## Abstract
Enable mypy everywhere in the client, relates to #3866 

Due date: End of Iteration "Spring Cleaning" (03.05.2019)

**Comment by LefterisJP** [comment]
Hmmm @Dominik1999 please search the repo before opening duplicate issues: https://github.com/raiden-network/raiden/issues/3798

Add the deadline in the linked issue.
