### ISSUE TITLE
Address the way geth v >= 1.9 handles unlocking for our tests

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#3892]
## Problem Definition

I noticed this while running our smoke tests with geth v1.9. I got the following error:
`Fatal: Account unlock with HTTP access is forbidden! `

Apparently Geth v>= 1.9 does not allows us to unlock an account via the personal RPC API in the following conditions according to the [PR](https://github.com/ethereum/go-ethereum/pull/17037#issuecomment-477950848) that implemented this.

 
>  -  If you call unlock via CLI, it fails the unlock if ws or rpc is enabled,
>  - If you call personal.unlock via rpc, it fails it if ws or http-rpc is enanbled

This can be be bypassed by using the following argument `allow-insecure-unlock` but they don't recommend it.

Instead they suggest to use [Clef](https://geth.ethereum.org/clef/Overview) which is I guess the account management moved out of the client.

## Task

Since we don't really use `personal.unlockAccount` apart from [here](https://github.com/raiden-network/raiden/blob/8d2dc8d0803d2fe1e6feed09c79cdecadd385b0d/raiden/tests/utils/smoketest.py#L176) in the smoketests to deploy the contracts we can safely add the `--allow-insecure-unlock` argument to geth in our tests when we decided to switch to 1.9

**Comment by palango** [comment]
@LefterisJP This was fixed by https://github.com/raiden-network/raiden/pull/4410 , right?

**Comment by LefterisJP** [comment]
yeah! How the heck do I have an issue for geth v1.9 dated back from April? I thought they released it more recently.
