### ISSUE TITLE
Harden messages against replay attacks

### ISSUE THREAD

**Issue by konradkonrad** [raiden-network/raiden#39]
Depending on the value of `self.asset`, messages could be re-applicable between two instances of the same state channel `(between=[Alice, Bob], asset=BBCoin)`. Given that:
- Alice and Bob opened+settled channel for BBCoin yesterday AND
- Alice and Bob open a new channel for BBCoin

If `self.asset` resolves to the same value, there seems to be no value unique to the current instance, i.e. yesterdays messages could be valid in today's channel.

So: either the asset-address needs to be unique, or we should include the state-channel address in signed transfer messages.

See:
https://github.com/brainbot-com/raiden/blob/master/raiden/messages.py#L291 
https://github.com/brainbot-com/raiden/blob/master/raiden/messages.py#L394

**Comment by czepluch** [comment]
This should be taken care of with https://github.com/raiden-network/raiden/issues/93 that will introduce nonce ranges.

**Comment by czepluch** [comment]
This can be closed with #287 that add nonce ranges and #211 that makes sure that the same lock cannot be unlocked twice.
