### ISSUE TITLE
Increase test coverage on raiden/api/objects.py

### ISSUE THREAD

**Issue by jomuel** [raiden-network/raiden#3905]
`raiden/api/objects.py` currently has 75% test coverage. Increase it to 90%.

Coverage report: https://codecov.io/gh/raiden-network/raiden/tree/master/raiden

**Comment by LefterisJP** [comment]
This is not needed. Looking at https://codecov.io/gh/raiden-network/raiden/src/develop/raiden/api/objects.py it's just some marshmallow setup code
