### ISSUE TITLE
Routing problem 

### ISSUE THREAD

**Issue by offerm** [raiden-network/raiden#3915]
Using the latest master.

I have the following setup

A<1000,0>B - a channel between A and B. A balance is 1000 and B balance is 0.
A<1000,0>C
A<499,501>D
B<500,500>D
C<1000,0>D

I try to send 501 from A to D with 
```
curl -i -X POST http://localhost:$Aport/api/v1/payments/$token/$D -H 'Content-Type: application/json' --data-raw '{"amount": 501, "identifier":6666666}'
```

The route A<>B<>D can't be used, but the route A<>C<>D should be able to do the work.

Still, the operation hangs. 

I see that sends a LockedTransfer to B but it stops there. I also see the PFS is used by B where I'm not using PFS at all. Not sure if this is for update only or if B is trying to find a route to D.

Log attached.

[raiden-debug_2019-04-25T13:28:08.322353.log](https://github.com/raiden-network/raiden/files/3117104/raiden-debug_2019-04-25T13.28.08.322353.log)

**Comment by rakanalh** [comment]
Hello @offerm,

At some point we used to filter channels by capacity and availability but we removed that in favor of having the transfer being sent and the next node would wait until the next hop's capacity is updated or becomes available. This is because the state of a route could change while the transfer is in-flight. 

The problem here is that we do not order the routes by the "more likely to succeed" order which is a solution to this problem that we can implement.

The other solution is to use our Path finding service that is under heavy development at the moment.

Is this a scenario which you need for your simulation? otherwise, i would change the setup of the nodes balances for now until PFS is more ready to be used (it'll be able to provide better routes eventually)

**Comment by offerm** [comment]
Hi @rakanalh 

Not sure I undertsnad your answer.

The routes selected by A are good (based on what A knows).
When B gets the `LockedTransfer`, B should find that he has no usable route to D and should send to A a ` Refund Transfer`  that should cause A to try getting to D via C (a good route).

The problem is that B does not send the ` Refund Transfer` to A.

**Comment by rakanalh** [comment]
Not really.

So A has 1000 and B has 0.

When B receives the transfer from A, it's a locked amount and cannot be used yet. Therefore, B until that point doesn't have capacity to refund. So the only solution for B is to keep the transfer around until it either expires or the next hop becomes available.

The point i was trying to make in my previous answer is that Raiden knows about 2 possible routes for your transfer, the 1st one being a valid route but "temporarily" unusable. The reason you get this is because it was the shortest path (this is how internal routing is implemented).
What Raiden could have done in this case is to go through the routes and sort them by "usability" (usable routes first, unusuable routes follow)... However, this is something that we might consider implementing or our internal routing module could be replaced completely by PFS (which is more likely).

**Comment by offerm** [comment]
@rakanalh I understand that raiden is currently using a naive shortest path mechanism.  I understand that PFS may be smarter. 

I changed the setup so it should work (B can send Refund back to A):

A<500,500>B - a channel between A and B. A balance is 500 and B balance is 500.
A<1000,0>C
A<100,900>D
B<100,900>D
C<1000,0>D

I'm trying to send 101 from A to D.
The route A<>D can't be used as A has 100 only.
From A's point of view A<>B<>D and A<>C<>D are two valid routes with the same distance.

The command that I'm using 
```
curl -i -X POST http://localhost:$Aport/api/v1/payments/$token/$D -H 'Content-Type: application/json' --data-raw '{"amount": 101, "identifier":6666666}'
```
The command blocks.

I see in the log of `D`:
`LockedTransfer` arrived for `C` (as it should be)
`SecretRequest` sent to `A` (msgid: 9791825257236144642)

I see in 'A' log:
`SecretRequest` received from 'D' (msgid: 9791825257236144642)
**No `SecretReveal` message back to 'D'**

```
{
  "current_user": "@0x4f6799e2341379ea52213919622b9bec80a1b655:raidentransport.ki-decentralized.com",
  "node": "4f6799e2",
  "message": "<SecretRequest [msgid:9791825257236144642 paymentid:6666666 secrethash:e824626d amount:101 expiration:4752 hash:91a01650]>",
  "sender": "89504d7a",
  "event": "Message received",
  "logger": "raiden.network.transport.matrix.transport",
  "level": "debug",
  "greenlet_name": "GMatrixClient._sync user_id:@0x4f6799e2341379ea52213919622b9bec80a1b655:raidentransport.ki-decentralized.com sync_token:s6018633_1383197_0_1_2080_1_1_23775_1",
  "timestamp": "2019-04-25 21:14:34.134608"
}
{
  "node": "4f6799e2",
  "state_change": "{\"payment_identifier\": \"6666666\", \"amount\": \"101\", \"expiration\": \"4752\", \"secrethash\": \"0xe824626db9e16dbdc904719fb45639b5b55f56fba883bd9ef4e99f9633c23561\", \"sender\": \"0x89504d7a60af628fE0710ff1fDeDFE5cEBbAFc3E\", \"revealsecret\": null, \"_type\": \"raiden.transfer.mediated_transfer.state_change.ReceiveSecretRequest\", \"_version\": 0}",
  "event": "State change",
  "logger": "raiden.raiden_service",
  "level": "debug",
  "greenlet_name": "GMatrixClient._sync user_id:@0x4f6799e2341379ea52213919622b9bec80a1b655:raidentransport.ki-decentralized.com sync_token:s6018633_1383197_0_1_2080_1_1_23775_1",
  "timestamp": "2019-04-25 21:14:34.140837"
}
{
  "node": "4f6799e2",
  "raiden_events": [],
  "event": "Raiden events",
  "logger": "raiden.raiden_service",
  "level": "debug",
  "greenlet_name": "GMatrixClient._sync user_id:@0x4f6799e2341379ea52213919622b9bec80a1b655:raidentransport.ki-decentralized.com sync_token:s6018633_1383197_0_1_2080_1_1_23775_1",
  "timestamp": "2019-04-25 21:14:34.161375"
}
```

Any explanation for this?



I also see this on A's log after receiving the `RefundTransfer` from B - **EventUnlockFailed**:
```
{
  "node": "4f6799e2",
  "raiden_events": [
    "{\"recipient\": \"0x133499f529A8D7cF00D8C5f7E73841DDB62b9Ca3\", \"channel_identifier\": \"0\", \"message_identifier\": \"13490318029531603562\", \"_type\": \"raiden.transfer.events.SendProcessed\", \"_version\": 0}",
    "{\"identifier\": \"6666666\", \"secrethash\": \"0xdfcf9bbc0a1cc905b672b292f1220b1d5058375f5ef62e8ee57b3aab6e056962\", \"reason\": \"route was canceled\", \"_type\": \"raiden.transfer.mediated_transfer.events.EventUnlockFailed\", \"_version\": 0}",
    "{\"recipient\": \"0x405364161FD8E38938488969DAb4Bb082DC2E492\", \"channel_identifier\": \"7\", \"message_identifier\": \"10912833126645123354\", \"transfer\": {\"payment_identifier\": \"6666666\", \"token\": \"0x387d35a432Ee58a03034db5976c8412f573C387b\", \"balance_proof\": {\"nonce\": 1, \"transferred_amount\": \"0\", \"locked_amount\": \"101\", \"locksroot\": \"0xe70ab6c600d6b848e2a132cdb03434306a296d67cfffe3a6c75ce9dec32bad56\", \"token_network_identifier\": \"0x2fc458816C5a62B32540269FC73a73dCd7301CFE\", \"channel_identifier\": \"7\", \"chain_id\": 4321, \"balance_hash\": \"0xfcd2562fd2a28c8211e7b774749bcc536914b8466e0c4526a4e6eb754c805f23\", \"_type\": \"raiden.transfer.state.BalanceProofUnsignedState\", \"_version\": 0}, \"lock\": {\"amount\": 101, \"expiration\": 4752, \"secrethash\": \"0xe824626db9e16dbdc904719fb45639b5b55f56fba883bd9ef4e99f9633c23561\", \"_type\": \"raiden.transfer.state.HashTimeLockState\", \"_version\": 0}, \"initiator\": \"0x4F6799E2341379eA52213919622B9bEc80a1b655\", \"target\": \"0x89504d7a60af628fE0710ff1fDeDFE5cEBbAFc3E\", \"_type\": \"raiden.transfer.mediated_transfer.state.LockedTransferUnsignedState\", \"_version\": 0}, \"balance_proof\": {\"nonce\": 1, \"transferred_amount\": \"0\", \"locked_amount\": \"101\", \"locksroot\": \"0xe70ab6c600d6b848e2a132cdb03434306a296d67cfffe3a6c75ce9dec32bad56\", \"token_network_identifier\": \"0x2fc458816C5a62B32540269FC73a73dCd7301CFE\", \"channel_identifier\": \"7\", \"chain_id\": 4321, \"balance_hash\": \"0xfcd2562fd2a28c8211e7b774749bcc536914b8466e0c4526a4e6eb754c805f23\", \"_type\": \"raiden.transfer.state.BalanceProofUnsignedState\", \"_version\": 0}, \"_type\": \"raiden.transfer.mediated_transfer.events.SendLockedTransfer\", \"_version\": 0}"
  ],
  "event": "Raiden events",
  "logger": "raiden.raiden_service",
  "level": "debug",
  "greenlet_name": "GMatrixClient._sync user_id:@0x4f6799e2341379ea52213919622b9bec80a1b655:raidentransport.ki-decentralized.com sync_token:s6018621_1383197_0_1_2080_1_1_23775_1",
  "timestamp": "2019-04-25 21:14:32.654468"
}
```

**Comment by offerm** [comment]
@rakanalh I debuged it a bit and found that `sub_task` is None in this code:
```
def subdispatch_to_paymenttask(
        chain_state: ChainState,
        state_change: StateChange,
        secrethash: SecretHash,
) -> TransitionResult[ChainState]:
    block_number = chain_state.block_number
    block_hash = chain_state.block_hash
    sub_task = chain_state.payment_mapping.secrethashes_to_task.get(secrethash)
    events: List[Event] = list()

    if sub_task:
```
As a results there will be no follow-up events.

The reason why it is None is that `chain_state.payment_mapping.secrethashes_to_task ` does not include the secrethash of the secret created after the first route failed.

**Comment by hackaugusto** [comment]
@offerm that indeed looks like a bug, the action `ReceiveTransferRefundCancelRoute` is creating a new initiator task but it is not updating the task mapping. Thanks for finding it out.

**Comment by offerm** [comment]
Happy to help. 

Anyway, this is not blocking me any more since I managed to get the `RefundTransfer` back to the `initiator`.

**Comment by rakanalh** [comment]
Refunds will be disabled in Raiden repo after having introduced source routing.
