### ISSUE TITLE
Increase test coverage on raiden/utils/runnable.py

### ISSUE THREAD

**Issue by jomuel** [raiden-network/raiden#3924]
`raiden/utils/runnable.py` currently has 85% test coverage. Increase it to 90%.

Coverage report: https://codecov.io/gh/raiden-network/raiden/tree/master/raiden

**Comment by LefterisJP** [comment]
This is already at 91% as of today: https://codecov.io/gh/raiden-network/raiden/src/develop/raiden/utils/runnable.py
