### ISSUE TITLE
Ensure callbacks for on-chain lifecycle changes of a NettingContract are only issued once

### ISSUE THREAD

**Issue by konradkonrad** [raiden-network/raiden#393]
see [this commit](https://github.com/konradkonrad/raiden/commit/afd6b08e14eed28de9f0c14b089d9763f9463b3b) and/or the TODOs in `raiden/channel.py::set_opened/set_closed`

**Comment by hackaugusto** [comment]
Callbacks were removed with f266327f4f2af5a9f667a577103808652c910089
