### ISSUE TITLE
Increase test coverage on raiden/network/proxies/proxy_manager.py

### ISSUE THREAD

**Issue by jomuel** [raiden-network/raiden#3935]
`raiden/network/blockchain_service.py` currently has 76% test coverage. Increase it to 90%.

Coverage report: https://codecov.io/gh/raiden-network/raiden/tree/master/raiden

**Comment by LefterisJP** [comment]
The class has been moved around and is now the `ProxyManager`: https://codecov.io/gh/raiden-network/raiden/src/develop/raiden/network/proxies/proxy_manager.py

With https://github.com/raiden-network/raiden/pull/5289 I am removing dead code so the coverage will increase.

Looking at the remaining lines that are not covered they seem to be edge cases of invalid input and invalid usage which I don't think are needed to be tested ... except perhaps the initialization of the block `interval` in the case of having > 256 blocks:

https://github.com/raiden-network/raiden/blob/dca2128d6f8dca116bd4987cc9d71c6b875dff52/raiden/network/proxies/proxy_manager.py#L108-L112
