### ISSUE TITLE
Increase test coverage on raiden/network/rpc/middleware.py

### ISSUE THREAD

**Issue by jomuel** [raiden-network/raiden#3937]
`raiden/network/rpc/middleware.py` currently has 65% test coverage. Increase it to 90%.

Coverage report: https://codecov.io/gh/raiden-network/raiden/tree/master/raiden

**Comment by LefterisJP** [comment]
This is already at 100%: https://codecov.io/gh/raiden-network/raiden/src/develop/raiden/network/rpc/middleware.py
