### ISSUE TITLE
Increase test coverage on raiden/network/rpc/smartcontract_proxy.py

### ISSUE THREAD

**Issue by jomuel** [raiden-network/raiden#3938]
`raiden/network/rpc/smartcontract_proxy.py` currently has 80% test coverage. Increase it to 90%.

Coverage report: https://codecov.io/gh/raiden-network/raiden/tree/master/raiden

**Comment by LefterisJP** [comment]
I don't think this is needed and I would close this issue. Looking at the module's coverage: https://codecov.io/gh/raiden-network/raiden/src/master/raiden/network/rpc/smartcontract_proxy.py

one function is unused: https://github.com/raiden-network/raiden/pull/5288

The rest are edge cases that are not really needed to test and would be results of incorrect usage of the initialization of the class.
