### ISSUE TITLE
Ensure value-not-set returns 0 for all NettingChannel proxy block values

### ISSUE THREAD

**Issue by konradkonrad** [raiden-network/raiden#394]
During #391 I encountered a case where the `settled_block` value of (at least) the `tester` implementation returned `None` instead of `0`. The stopgap implementation for the PR was to fix the range in the `channel.py` implementation [`ChannelExternalState.query_settled`](https://github.com/konradkonrad/raiden/blob/99ba6e5066694af9f6bd0a025c778a1b86626106/raiden/channel.py#L443-L445), but it should rather be fixed on the lower level.

**Comment by LefterisJP** [comment]
@konradkonrad I will try to reproduce it but do you have a ready-made case where this occurs with `tester`? Which test is it?

**Comment by konradkonrad** [comment]
> I will try to reproduce it but do you have a ready-made case where this occurs with `tester`? 

see #398 

> Which test is it?

It occurs in `test_settlement.py::test_settlement` but you need to have the fixes of #391 applied (without [this line](https://github.com/raiden-network/raiden/pull/391/commits/644d8922ad6938008d32de9898ba5e82cd6886ed#diff-08685f521533606c5888755314d415efR445) )

**Comment by LefterisJP** [comment]
gotcha! Thank you. Am on it.

**Comment by LefterisJP** [comment]
The lower level here would be the tester itself in pyethapp and I don't think this is feasible at this point. We can always do fixes to ensure consistency inside `raiden/tests/utils/tester_client.py`.

I am closing this issue.
