### ISSUE TITLE
Route failure handling when initiator does not have the Secret) 

### ISSUE THREAD

**Issue by offerm** [raiden-network/raiden#3948]
Today, when the initiator does not have the secret, in case of failure of the first route (initiator) the transfer is stopped while a valid route may still exists.

Once  https://github.com/raiden-network/raiden/issues/3945 is done - enhance the code to allow usage of all possible routes

**Comment by rakanalh** [comment]
I can see that you are referring to:

https://github.com/raiden-network/raiden/blob/cdcb7ff44be6a48dea43e61e6139dbb61092ceb9/raiden/message_handler.py#L188-L189

When you said that the transfer is stopped. What can be done in this case is as you suggested which is to use a different route without generating a new secret for the new forward transfer.

**Comment by lullis** [comment]
This has been solved incidentally by #3915 . If an initiator receives a transfer refund but it still knows of any other possible route, a re-route is issued.
