### ISSUE TITLE
Implement a padding helper for hashlock secret encoding

### ISSUE THREAD

**Issue by konradkonrad** [raiden-network/raiden#395]
One of the problems addressed in #391 was that the secret in the test [(`'secret'`) didn't match the (32 byte) padded secret in the smart contract](https://github.com/raiden-network/raiden/pull/391/files#diff-9161c3328a41e5b779ebb4d7966b8abcR53). This lead to a `throw` which naturally is hard to debug. To avoid similar problems in the future, we should introduce a helper function `utils.create_hashlock(secret)` that applies the specified padding. Then we should rigorously remove all usage of plain `sha3(secret)` in tests (and elsewhere).

**Comment by konradkonrad** [comment]
postponing any work on this until we have sorted out related questions, e.g. from #399

**Comment by hackaugusto** [comment]
I don't think padding is a good idea as that will reduce the number of random bits in the secret, perhaps we could just add checks for the `channel.py` register_secret methods and the Secret message constructor to avoid this error in tests again?
