### ISSUE TITLE
Make PaymentChannel open event validation optional

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/raiden#3958]
## Abstract

The check bellow:

https://github.com/raiden-network/raiden/blob/0e8fa93a275deb2a5d33eaa8a377273fc5049559/raiden/network/proxies/payment_channel.py#L37-L42

Is quite expensive for light clients, to improve this check two things should be done:

- Use a better `from_block`. Instead of the genesis block the block at which the token network was created should be used, this is useful to either full or light ethereum clients.
- Make the check optional, so that light client user can disable it.

## Motivation

Performance

## Specification

Add a namedtuple to configure proxies behavior, this should be passed to the proxies by the blockchain service.

## Backwards Compatibility

This only changes the proxies, it is completely backwards compatible.

**Comment by offerm** [comment]
@hackaugusto @LefterisJP What is the status of this one?

This can be a potential blocker for mainnet. the get_logs call may timeout when used with `from_block` = GENESIS.

I have seen it when trying to deposit to a channel. The class `PaymentChannel` is using it to read the participants. 

Note that `curl  http://localhost:5001/api/v1/channels` provides the same information without going to the provider.

**Comment by hackaugusto** [comment]
@offerm I opened with a first improvement for this: https://github.com/raiden-network/raiden/pull/4899

If you can run against Alderaan let me know if it helps with your problem. The PR has a few comments on how to further improve things.

**Comment by offerm** [comment]
@hackaugusto too complicate to check in my environment. I need at least 2 other PRs to be merged first.

**Comment by hackaugusto** [comment]
closing as requested by @rakanalh
