### ISSUE TITLE
Add tooling and documentation for browsersolidity debugging

### ISSUE THREAD

**Issue by konradkonrad** [raiden-network/raiden#396]
It is possible (but cumbersome) to connect [ethereum/browser-solidity](https://github.com/ethereum/browser-solidity) to a running geth-pytest instance. Since this seems the best tool available for debugging failing transactions, we should have a documented and easy way for doing it.

What we need:
- [ ] add a `py.test` flag that enables the `debug` `--rpcapi` on `geth` and sets the `rpccorsdomain`
- [ ] document how to reason about block numbers and contract addresses from the `geth` test log
- [ ] document (or automate) running a local browser-solidity instance
- [ ] document (or automate) connecting to the private testing chain
- [ ] document (or automate) adding the raiden smart contracts to browser-solidity
- [ ] document (or automate) connecting contracts to the deployed instances

**Comment by karlb** [comment]
Since we worked without this all the time and the working revert error messages got added since creating this ticket, there are not plans to do this anymore.
