### ISSUE TITLE
UnboundLocalError: local variable 'service_registry' referenced before assignment

### ISSUE THREAD

**Issue by agatsoh** [raiden-network/raiden#3986]
## Intro

I follow Yoichi's [guide](https://github.com/pirapira/raiden/blob/private-chain/docs/private_net_tutorial.rst) for setting up environment to test raiden in a private network on raiden latest master. But I get the `UnboundLocalError`.

## Problem Definition

Here are the logs and steps that i follow exactly from the Yoichi's guide to get the issue along with the stack trace of the issue at the end of the gist.
https://gist.github.com/agatsoh/a4de50d159c19fc27cf7289da2f5820d

I guess this issue happens before it can even get to making the db. I am attaching the log files here.
[raiden-debug_2019-05-03T07:32:53.001548.log](https://github.com/raiden-network/raiden/files/3141491/raiden-debug_2019-05-03T07.32.53.001548.log)
[raiden-debug_2019-05-03T10:07:05.824939.log](https://github.com/raiden-network/raiden/files/3141492/raiden-debug_2019-05-03T10.07.05.824939.log)
[raiden-debug_2019-05-03T10:16:36.557316.log](https://github.com/raiden-network/raiden/files/3141493/raiden-debug_2019-05-03T10.16.36.557316.log)

### System Description

Here add a detailed description of your system, e.g. output of the following script:

```
uname -a
Linux krishna-pc 5.0.10-arch1-1-ARCH #1 SMP PREEMPT Sat Apr 27 20:06:45 UTC 2019 x86_64 GNU/Linux

command -v solc && solc --version
/usr/bin/solc
solc, the solidity compiler commandline interface
Version: 0.5.8+commit.23d335f2.Linux.g++

command -v geth && geth version
/usr/local/bin/geth
Geth
Version: 1.8.23-stable
Git Commit: c942700427557e3ff6de3aaf6b916e2f056c1ec2
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.11.5
Operating System: linux
GOPATH=
GOROOT=/home/travis/.gimme/versions/go1.11.5.linux.amd64

command -v raiden && raiden version
/home/krishna/Envs/raiden_env/bin/raiden
{
  "raiden": "0.100.3rc5.dev246+g742ad4f4",
  "python_implementation": "CPython",
  "python_version": "3.7.3",
  "system": "Linux 64bit_ELF 5.0.10-arch1-1-ARCH",
  "architecture": "x86_64",
  "distribution": "source"
}

[ -d .git ] && git rev-parse HEAD
```

**Comment by palango** [comment]
Should be fixed by https://github.com/raiden-network/raiden/pull/3985
