### ISSUE TITLE
Ensure interoperability with Lightning etc.

### ISSUE THREAD

**Issue by justmoon** [raiden-network/raiden#399]
## Problem Definition

Different trustline / state channel / payment channel based networks use different hashlocks, which makes trustless payments across them impossible.

* Lightning: SHA-256d¹ (two iterations of SHA-256), 32-byte preimage
* Interledger: SHA-256, 32-byte preimage
* Raiden: Ethereum-SHA-3, 32-byte preimage

In terms of the underlying blockchains, our choices are:

* Bitcoin: SHA-256d¹, <=520 byte preimage
* Ethereum: Any hash algorithm (smart contracts), no preimage size restriction, though 32 bytes (uint256) is convenient
* Ripple ([PayChan](https://ripple.com/build/amendments/#paychan)): [Crypto-conditions](https://tools.ietf.org/html/draft-thomas-crypto-conditions-02) (SHA-256, Ed25519, RSA, Compound Conditions), no preimage size restriction

¹ Note that SHA-256d(x) = SHA-256(SHA-256(x)), so I can trivially prove that a SHA-256 condition C is fulfilled by the same secret as a given SHA-256d condition C' by showing C' = SHA-256(C). This has the effect that networks that use SHA-256 and SHA-256d are mutually interoperable with the security level of SHA-256.

## Solution

Raiden should support SHA-256 (instead of or in addition² to SHA-3) or an alternative to Raiden with SHA-256 support should be created for inter-chain/inter-ledger capability.

² We don't need all networks' condition types to be exactly the same, we just need some lowest common denominator that is shared between all of them.

## Tasklist

- [ ] Decide whether SHA-256 should be added as (a) an alternative to SHA-3 in Raiden, (b) a replacement to SHA-3 in Raiden or (c) a fork of Raiden
- [ ] Define a data format for the new SHA-256 lock
- [ ] Implement and test the SHA-256 lock

**Comment by LefterisJP** [comment]
@justmoon Thank you for bringing this up and for the consice arguments you are presenting. We will discuss this with the team and come back to this issue soon.

**Comment by pirapira** [comment]
This has been implemented in `raiden:develop`.
