### ISSUE TITLE
Enforce flake8 check in Travis

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#401]
## Problem Definition

Not all of us are properly following the styling rules of flake8. Flake8 is also a linter and can spot bugs like unused/uninitialized variables.

## Solution

Enforce flake8 in travis. But omit the long line rule, only in Travis, since some times this rule can and should be ignored. If a PR fails the flake8 test it sould be marked as "Failed" and the creator shoud fix it.

## Tasklist

- [ ] Ensure that no file on the codebase fails the above mentioned flake8 check
- [ ] Enable the flake8 check in travis and configure it as mandatory. i.e.: If it fails the build fails.

**Comment by hackaugusto** [comment]
Additional style guide lines:

When a function signature needs spans multiple lines the following formatting must be used:

```python
def function_with_a_lot_of_parameters(
         param1,
         param2,
         ...,
         paramn):
    pass
```

Strings must use single quotes by default, and fallback to double quotes if the contained text contains a single quote (to avoid escaping)

**Comment by LefterisJP** [comment]
Totally agree. For the non-flake8 style rules I will add them in the coding style guide.

**Comment by LefterisJP** [comment]
Added: https://github.com/raiden-network/raiden/pull/426
