### ISSUE TITLE
Fuzz a pair of state machines, look for nonce mismatch

### ISSUE THREAD

**Issue by pirapira** [raiden-network/raiden#4013]
Some of the last bugs before a release are nonce mismatches.

> hackaugusto 17:03 @jochen started to work on that, we have a few tests here: https://github.com/raiden-network/raiden/tree/master/raiden/tests/fuzz
> IMO the most annoying problem is that currently the state machine checks the signatures
> here: https://github.com/raiden-network/raiden/blob/13d90cabd0eaecc561cf5bf8eedc8ba6a536d406/raiden/transfer/channel.py#L273-L316
> so that means the fuzz either needs to randomly generate valid signatures
> or we need a smartish model of the application

> yoichi 17:04 I see.

> hackaugusto 17:04 this should be improved with this PR: https://github.com/raiden-network/raiden/pull/3860

> so the idea is that all value objects are validated at the boundaries, and that the boundary code is trusted
> to we can just remove the signature verification from the state machine and assume that our own code is correct, and only uses correctness by construction
> after that we have two approaches, either extend the existing asserts
> e.g.: https://github.com/raiden-network/raiden/blob/13d90cabd0eaecc561cf5bf8eedc8ba6a536d406/raiden/transfer/mediated_transfer/mediator.py#L270-L331
> and run the state machine with purely random data
> or build a model of the thing and use AFL or hypothesis
> (AFL would be awesome and I found recently it supports python through a nice little package)

> yoichi 17:07 How can I catch nonse mismatch?
> Maybe I need to couple two state machines, and feed the messages from one into the other?

> hackaugusto 17:12 yes that can work

> just keep in mind that not all nonce mismatches are bugs, so you need synchronous and reliable network model

> IOW, a state change goes into one state machine, events come out, and goes directly to the next state machine

> you will have to do a bit of work to map event to state changes though

> actually, no, an ordered queue is sufficient

> as longs as the events are processed in order things should be fine (by processed I meant that Send events are converted to Receive events for the partner state machine)

**Comment by jomuel** [comment]
In the current fuzz test (`raiden.tests.fuzz.test_state_changes`), we use a single state machine instance and hand-craft messages/events for it. Using multiple state machine instances is a better approach, it will make the test both more realistic and easier to write. Let's rewrite the fuzz test accordingly before adding the remaining rules and use this issue to track it.

Issues for remaining rules: #1155, #1156, #1157, #3246
