### ISSUE TITLE
Initiator should check the state of the partner nodes

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/raiden#4036]
## Abstract

As the mediator, the initiator should prefer routes to nodes which are online. This not currently done

**Comment by LefterisJP** [comment]
Is this also related to https://github.com/raiden-network/raiden/issues/1142 ?

**Comment by rakanalh** [comment]
The logic in the internal routing to check for the node's availability was restored in a PR by @palango and @Dominik1999. I think this issue is done.

**Comment by palango** [comment]
I don't remember that we did this. 😱

**Comment by rakanalh** [comment]
Paul is right, the check for capacity was restored only if the transfer is a direct one:
https://github.com/raiden-network/raiden/blame/develop/raiden/routing.py#L60
