### ISSUE TITLE
Make use of PEP563 for type annotations

### ISSUE THREAD

**Issue by nlsdfnbch** [raiden-network/raiden#4044]
Since [PEP563](https://www.python.org/dev/peps/pep-0563/) is live in Python 3.7, I think it’d be a good idea to separate the import required for typing annotations from the ones actually used in code of a module:

```python
# imports of objects used in logic
import a
from b import c
# Type hint imports
from typing import TYPE_CHECKING
if TYPE_CHECKING:
    # imports for type hints
    from d import F

def foo(bar: F):
    return bar.hello()
```
I see two advantages to this:
 1. You moved all imports for type hints to a visually separate block.
 2. The code is future-proofed against any possible cyclic imports (as long as type hint imports stay in that block and are always only added to that block).

**Note**: PEP563 improves on the previous pattern involving the `typing.TYPE_CHECKING` arg, which required types to be declared as strings:

```python
def foo(bar: 'F'):
    reutrn bar.hello()
```

Starting with Python 3.7 **this is no longer required!**

**Comment by palango** [comment]
Does `isort` support this?

**Comment by nlsdfnbch** [comment]
After briefly checking I did not find anything stating support for this PEP in the `isort` repo. in the worst-case, it'd be required to add `# isort:skip`
On the other hand, I'm not entirely sure `isort` picks up indented imports to begin with :thinking:
