### ISSUE TITLE
Consistent naming for participant state functions across raiden and smart contracts

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/raiden#4055]
# Abstract

Some of the smart contract functions have the same name for arguments, but they are used differently, e.g.:

[unlock](https://github.com/raiden-network/raiden-contracts/blob/dc4d8103c07b15c59261dc3ff9d47e39ec32f161/raiden_contracts/data_0.12.0/source/raiden/TokenNetwork.sol#L834) uses `partner` then `participant`
```solidity
# store
unlock_key = getUnlockIdentifier(channel_identifier, partner, participant);
```
[getChannelPartcipantInfo](https://github.com/raiden-network/raiden-contracts/blob/dc4d8103c07b15c59261dc3ff9d47e39ec32f161/raiden_contracts/data_0.12.0/source/raiden/TokenNetwork.sol#L1074), does it the other way around

```solidity
unlock_key = getUnlockIdentifier(channel_identifier, participant, partner);
```

## Motivation

Having to swap around the parameters is a bit surprising and can lead to subtle bugs.

## Specification

TBD: @pirapira we need to set on a default argument scheme to avoid these incoherencies.

## Backwards Compatibility

This will change the smart contracts functions, therefore it will break compatibility.

**Comment by pirapira** [comment]
`unlock` and `getUnlockIdentifier` will receive `address locker, address unlocker`.

**Comment by pirapira** [comment]
`getChannelParticipantInfo()`'s signature and the body won't change.

**Comment by hackaugusto** [comment]
@pirapira just hold on a bit for the changes, otherwise it will break the client or we have to drop backwards compatibility.

**Comment by pirapira** [comment]
I know.  This will be for `raiden:develop`.

**Comment by pirapira** [comment]
I think this has been fixed by now.  Closing.
