### ISSUE TITLE
Coverage per test type

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden#4073]
With https://github.com/raiden-network/raiden/pull/4022 we created coverage reports for each test type. However, codecov is to slow right now and cannot display the UI, so is was reverted in #4072 .

Once https://community.codecov.io/t/big-slowness-during-opening-pr-changes/58/6 is fixed we can do this again.

**Comment by christianbrb** [comment]
@palango now works on this, right? :-)

**Comment by LefterisJP** [comment]
@palango and @jomuel can figure it out on Monday if Jochen comes back. If not then Paul will finish it.

**Comment by christianbrb** [comment]
Is this the related PR? https://github.com/raiden-network/raiden/pull/4547

**Comment by LefterisJP** [comment]
yes

**Comment by christianbrb** [comment]
Created issue https://github.com/raiden-network/raiden/issues/4664 to cover the implementation of #4547

**Comment by jomuel** [comment]
Closing this now, I have no idea why it has been reopened. A coverage configuration to measure unit tests has been added, and the remaining problem (adding it to CodeCov too, despite their problem with the flag feature) is tracked in #4664.
