### ISSUE TITLE
Adding stability to RDN Tokens

### ISSUE THREAD

**Issue by ayumihamsaki** [raiden-network/raiden#4087]
## Abstract

I read that the Raiden Network have created a trust for their money! See here: https://medium.com/raiden-network/raiden-pulse-5-news-from-march-and-april-56e781aea7c

Yet the team seems to not care about their RDN Tokens! This seems complete madness due to this project being part of a so-called blockchain, which is being designed as digital money extension for the Ethereum Network.

## Motivation

Right now the RDN Tokens are listed on several rubbish exchanges! The only good exchanges are Binance and Huobi. Yet Huobi have issued repeated warnings to the Raiden Team and even labelled RDN with the `ST` see here: https://huobiglobal.zendesk.com/hc/en-us/articles/360000208382-Announcement-on-the-list-of-ST-tokens-of-Huobi-Global

If RDN gets de-listed from Huobi that only leaves Binance as a good exchange for RDN. If both Binance and Huobi de-list RDN, then your token is completely worthless and just another sh@t coin.

The Raiden Network team seriously need to have some people working as developers on the project and also working to push RDN Tokens on to NEW Exchanges! Also to have a marketing team actively pushing RDN Token usage into other new projects and create alliances.

If the price of the RDN Tokens went up, then there would be more funds available to the Raiden Team to develop their projects further!

## With Regards to this github

Just picture in the near future the RDN Tokens were not listed on any good exchanges, the Tokens would quickly become worthless in a matter of hours and your source of funds would reduce very quickly!

This is a good project, but the Raiden Team seriously needs to understand they are a blockchain project with a Token and not just another normal github repo working on some software! 

50% should be spent on coding your software and 50% on increasing RDN Token adoption!

**Comment by franzihei** [comment]
Hi @ayumihamsaki,

Thank you for sharing your concerns and thoughts. We are committed towards developing the Raiden Network to enable near-instant, low-fee and scalable off-chain token transfers. This Github repo is solely dedicated to development issues related to Raiden. If you want to discuss non-development related issues, please feel free to visit the [Subreddit](https://www.reddit.com/r/raidennetwork/), [Raiden's inofficial Telegram community](https://t.me/RaidenNetworkCommunity) or [Twitter](https://twitter.com/raiden_network).

> I read that the Raiden Network have created a trust for their money!

I'm not sure what you mean exactly. In the token sale 16% have been allocated to an external development fund (you can see an overview of the token allocation [here](https://raiden.network/token.html)). The Raiden Trust will fund and support projects and parties that help build and grow the Raiden Network ecosystem. More information about it can be found in the [Raiden Trust Launch Announcement](https://medium.com/raiden-network/introducing-the-raiden-trust-cd47db60146). 

Hope this helps to clarify. Have a great day!
