### ISSUE TITLE
Smart contract functions

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/raiden#41]
Add missing functions:

*channelManagerContract*
- [x] A function that return a list of all existing channels `[(addr1, addr2), (addr3, addr4), ...]`
  - https://github.com/brainbot-com/raiden/blob/master/raiden/network/rpc/client.py#L165

*nettingChannelContract*
- [x] A function to get the participants deposits and addresses
  - https://github.com/brainbot-com/raiden/blob/master/raiden/network/rpc/client.py#L188

**Comment by czepluch** [comment]
until there is a convenient way to create arrays of tuples, we will have to do with an array of addresses where every two elements represents a pair

**Comment by czepluch** [comment]
Latest commit adds the functionality of both desired functions. Still needs testing though.

**Comment by czepluch** [comment]
Closed with commit above
