### ISSUE TITLE
Re-Request PFS info endpoint for price info, when iou-payment fails 

### ISSUE THREAD

**Issue by Dominik1999** [raiden-network/raiden#4100]
## Handle `PFSError.INSUFFICIENT_SERVICE_PAYMENT` better

The Raiden client only requests the PFS price info at startup and stores that value in `service_config["pathfinding_fee"]`. 

In `pathfinding.py` `def query_paths` the client must handle the situation where the payment to the pfs is insufficient. 

We need to handle two situations here. The pfs needs to be re-requested to ask the price again:
- if the pfs price is higher than the maximum payment the client is willing to pay, either internal routing should be used or another pfs chosen
- if the pfs price changed to something that is lower than the maximum payment the client is willing to pay, the value in `service_config["pathfinding_fee"]` should be changed

**Comment by karlb** [comment]
> if the pfs price is higher than the maximum payment the client is willing to pay, either internal routing should be used or another pfs chosen

I would throw an exception for now, as
* internal routing is deprecated
* we have no infrastructure to switch PFSs at the moment
