### ISSUE TITLE
Display sync progress

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden#4102]
## Abstract

When starting Raiden without an existing database there is not progress shown for the initial sync, which can take quite some time.

## Motivation

The user should know that the client is doing work and not shut it down to early.

## Specification

Some progress indicator, like the number of blocks left to sync and the number of blocks that get synced per time interval, should be shown during sync at client startup.

**Comment by LefterisJP** [comment]
We should already have a syncing progress indicator: https://github.com/raiden-network/raiden/blob/358409dc757ac7467962324d5b9f34e6bd5e0cd2/raiden/ui/sync.py#L30

**Comment by palango** [comment]
Oh, maybe the description was unclear. I'm not talking about the eth client, but the blockchain event syncing of the raiden node.

**Comment by LefterisJP** [comment]
Ah I see. That makes sense now and totally agree this also needs to be shown to the user.

**Comment by ulope** [comment]
It would also be nice to show this in the Web-UI.

**Comment by czepluch** [comment]
@rakanalh can we prioritize this? It should not take long, but should add value to the UX.
