### ISSUE TITLE
Evaluate Matrix Olm e2e encryption 

### ISSUE THREAD

**Issue by err508** [raiden-network/raiden#4105]
## Motivation
We need transport e2e encryption, see #473 

## Specification

We will use Matrix's e2e encryption. To be answered:

- [ ] Current status of implementation/maintenance in the python client
- [ ] Performance 
- [ ] Cross Server compatibility 
- [ ] Onion Routing/Source Routing compatibility 
- [ ] Key Management in raiden client/transport
- [ ] Key Generation, Synapse Key distribution, Key recovery
- [ ] Raiden Light Client compatibility

**Comment by ulope** [comment]
Using olm depends on #4292

**Comment by hackaugusto** [comment]
duplicated #3893
