### ISSUE TITLE
Synchronize API calls that use non-constant smart contract functions

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#419]
## Problem Definition

The current API functions that call non-constant smart contract functions need synchronization, this is required to avoid sending transactions for the same effect.

A user interacting with the REST API might make two or more HTTP requests for opening channels with the same token and partner, since only the first transaction can succeed the additional ones will only burn gas.

## Solution

Add synchronization for the following functions:

- get_new_events
- open
- deposit
- close
- settle
- transfer / transfer_and_wait / transfer_async

## TODO

semantics for the concurrency control

-  linearize the calls:
    - synchronized for the same cursor
        - get_new_events
- prohibit concurrent calls
    - channel manager with the same partner address
        - open
    - on the channel
        - deposit, close, and settle

**Comment by hackaugusto** [comment]
```
- linearize the calls:
  - synchronized for the same cursor
    - get_new_events
```
This was effectively done by https://github.com/raiden-network/raiden/pull/1339 . That PR is serializing calls to all filters, which is really coarse, and the logic is not part of the Blockchain proxies, so we may still get races if the proxies are used directly.

Ideally we should lock calls to methods of `Filter` instances, additionally the lock needs to cover the processing of the events. One solution is to wrap the `changes()` function in a context manager, that acquires the locks and return the events, while the events are being processed the lock is held, once the context manager exists the events are cleared. (If this is done then `RaidenService.poll_blockchain.events` must become private, and the lock introduced by #1339 must go)

**Comment by LefterisJP** [comment]
@carllin Thank you. Please ask any questions you have here. Also write here if you stop looking at this issue.
