### ISSUE TITLE
Flaky tests

### ISSUE THREAD

**Issue by karlb** [raiden-network/raiden#4193]
Many tests do not reliably succeed. I've compile the following list by installing pytest-repeat and running all tests five times in random order with
```
pytest -Wignore raiden/tests/ -n 20 --count 5 --random --show-capture=no
```
I marked all failed tests as flaky using https://github.com/box/flaky and retried until I got that command to run without a single (non-retried) error.

Since the number of flaky tests is quite high, I assume that there are some root causes that cause many tests to be flaky. Please split subsets flaky tests into separate issues whenever you identify a common root cause. Some tests might have failed due to increased load, but this is still something that should be fixed since the load was not overly high.

See also https://github.com/raiden-network/raiden/pull/4208.

- [ ] integration/rpc/test_client.py: test_geth_discover_next_available_nonce
- [ ] integration/test_recovery.py: test_recovery_unhappy_case
- [ ] integration/test_recovery.py: test_recovery_blockchain_events
- [ ] integration/rpc/assumptions/test_rpc_transaction_assumptions.py: test_transact_throws_opcode
- [ ] integration/test_blockchainservice.py: test_channel_with_self
- [ ] integration/test_blockchainservice.py: run_test_channel_with_self
- [ ] integration/rpc/assumptions/test_rpc_gas_estimation_assumptions.py: test_estimate_gas_fail
- [ ] integration/rpc/assumptions/test_rpc_gas_estimation_assumptions.py: test_estimate_gas_fails_if_startgas_is_higher_than_blockgaslimit
- [ ] integration/test_send_queued_messages.py: test_send_queued_messages
- [ ] integration/test_raidenservice.py: test_regression_filters_must_be_installed_from_confirmed_block
- [ ] integration/test_pythonapi.py: test_token_registered_race
- [ ] integration/test_pythonapi.py: test_payment_timing_out_if_partner_does_not_respond
- [ ] integration/test_pythonapi.py: test_set_deposit_limit_crash
- [ ] integration/test_pythonapi.py: test_create_monitoring_request
- [ ] integration/test_pythonapi.py: run_test_create_monitoring_request
- [ ] integration/network/proxies/test_token_network.py: test_token_network_deposit_race
- [ ] integration/network/proxies/test_token_network.py: test_query_pruned_state
- [ ] integration/network/transport/test_matrix_transport.py: test_matrix_tx_error_handling
- [ ] integration/network/transport/test_matrix_transport.py: test_matrix_invite_private_room_happy_case
- [ ] integration/network/transport/test_matrix_transport.py: test_matrix_invite_private_room_unhappy_case1
- [ ] integration/network/transport/test_matrix_transport.py: test_matrix_invite_private_room_unhappy_case_2 (VERY FLAKY)
- [ ] integration/network/transport/test_matrix_transport.py: test_matrix_invite_private_room_unhappy_case_3
- [ ] integration/network/transport/test_matrix_transport.py: test_matrix_user_roaming
- [ ] integration/network/proxies/test_secret_registry.py: test_register_secret_batch_with_pruned_block
- [ ] integration/network/proxies/test_secret_registry.py: test_concurrent_secret_registration
- [ ] integration/network/proxies/test_service_registry.py: test_configure_pfs
- [ ] integration/test_regression.py: test_regression_unfiltered_routes
- [ ] integration/test_regression.py: test_regression_payment_complete_after_refund_to_the_initiator
- [ ] integration/test_balance_proof_check.py: test_node_can_settle_if_close_didnt_use_any_balance_proof
- [ ] integration/test_balance_proof_check.py: test_node_can_settle_if_partner_does_not_call_update_transfer
- [ ] integration/transfer/test_mediatedtransfer.py: test_mediated_transfer_with_entire_deposit
- [ ] integration/transfer/test_mediatedtransfer.py: test_mediated_transfer_messages_out_of_order
- [ ] integration/transfer/test_mediatedtransfer.py: test_mediated_transfer_with_allocated_fee
- [ ] integration/transfer/test_mediatedtransfer_invalid.py: test_receive_lockedtransfer_invalidnonce
- [ ] integration/transfer/test_refundtransfer.py: test_different_view_of_last_bp_during_unlock
- [ ] integration/long_running/test_token_networks.py: test_participant_selection
- [ ] integration/long_running/test_settlement.py: test_settle_is_automatically_called
- [ ] integration/long_running/test_settlement.py: run_test_settle_is_automatically_called
- [ ] integration/long_running/test_settlement.py: test_batch_unlock
- [ ] integration/long_running/test_settlement.py: test_settled_lock
- [ ] integration/long_running/test_settlement.py: run_test_settled_lock
- [ ] integration/long_running/test_settlement.py: test_automatic_secret_registration
- [ ] integration/long_running/test_settlement.py: run_test_automatic_secret_registration
- [ ] integration/long_running/test_settlement.py: test_automatic_dispute
- [ ] integration/long_running/test_settlement.py: run_test_automatic_dispute
- [ ] integration/long_running/test_settlement.py: test_batch_unlock_after_restart
- [ ] integration/long_running/test_settlement.py: run_test_batch_unlock_after_restart
- [ ] integration/long_running/test_stress.py: test_stress
- [ ] integration/long_running/test_integration_events.py: test_channel_new
- [ ] integration/long_running/test_integration_events.py: run_test_channel_new
- [ ] integration/long_running/test_integration_events.py: test_channel_deposit
- [ ] integration/long_running/test_integration_events.py: run_test_channel_deposit
- [ ] integration/long_running/test_integration_events.py: test_query_events
- [ ] integration/long_running/test_integration_events.py: test_secret_revealed_on_chain
- [ ] integration/api/test_pythonapi.py: test_raidenapi_channel_lifecycle
- [ ] integration/api/test_pythonapi.py: run_test_raidenapi_channel_lifecycle
- [ ] integration/api/test_restapi.py: test_payload_with_address_not_eip55
- [ ] integration/api/test_restapi.py: test_api_channel_status_channel_nonexistant
- [ ] integration/api/test_restapi.py: test_api_open_close_and_settle_channel
- [ ] integration/api/test_restapi.py: test_api_payments_with_hash_no_secret
- [ ] integration/api/test_restapi.py: test_api_payments_with_secret_and_hash
- [ ] integration/api/test_restapi.py: test_register_token_mainnet
- [ ] integration/api/test_restapi.py: test_network_events
- [ ] integration/api/test_restapi.py: test_channel_events
- [ ] integration/api/test_restapi.py: test_payment_events_endpoints
- [ ] integration/api/test_restapi.py: test_pending_transfers_endpoint
- [ ] unit/blockchain/test_events.py: test_blockchain_events (VERY FLAKY)
- [ ] unit/test_logging.py: test_basic_logging
- [ ] unit/test_cli.py: test_cli_version

**Comment by LefterisJP** [comment]
Hehe this issue is a deja vu: https://github.com/raiden-network/raiden/issues/389
Some tests got flaky again it seems as they were also in that issue and are also here, like the settlement tests.

Also related:

- Skipped flaky echo node tests: https://github.com/raiden-network/raiden/issues/3750
- Flaky test_regression_transport_global_queues_are_initialized_on_restart_for_services: https://github.com/raiden-network/raiden/issues/3714

**Comment by hackaugusto** [comment]
Note: I believe most of these tests are not necessarily flaky when run in isolation. It seems a problem with executing the suite in parallel, which is not necessarily a good idea because of gevent.

**Comment by karlb** [comment]
Yes, there are different reasons for the observed flakiness, so far I observed:

* test is generally flaky
* test fails or gets flaky when run multiple times in the same process
* test is flaky when run in parallel with other tests

I'll burn some CPU time for tests while working on other stuff so that I'll hopefully be able to assign specific reasons to specific tests. I do not believe that tests can't be run in parallel reliably at all due to using gevent.
