### ISSUE TITLE
Fix eth-types mismatch

### ISSUE THREAD

**Issue by ulope** [raiden-network/raiden#4194]
## Problem Definition

We currently use `eth-utils==1.4.1`. 
Upgrading to the latest `1.6.0` causes mypy to suddenly realize that `to_checksum_address`, `to_normailzed_address` etc. have return types that don't match our internally defined ones. (e.g. `raiden.utils.typing.Address` vs. `eth_typing.evm.Address`)

## Possible solutions

1. Remove our types and rely on eth-typing
1. Alias the types
1. Cast all arguments / return values

Only 1. and 2. seem workable.

**Comment by palango** [comment]
We ran into the same problems in the services. Before `eth-utils` 1.6 the typing information is not properly declared, so mypy cannot use it.

In my opinion we should use as many of the `eth-typing` types as possible, as this will interoperability with the various `eth-*` projects easier.

**Comment by hackaugusto** [comment]
We are at [`eth-utils==1.6.4`](https://github.com/raiden-network/raiden/blob/34fe7c14655107afdb0a0f38f4b07428fa71540e/requirements/requirements.txt#L26) already.
