### ISSUE TITLE
Atomic handling of Block state changes

### ISSUE THREAD

**Issue by rakanalh** [raiden-network/raiden#4220]
## Abstract

https://github.com/raiden-network/raiden/blob/cdcb7ff44be6a48dea43e61e6139dbb61092ceb9/raiden/raiden_service.py#L691-L720

In the above snippet, the Raiden service `callback_new_block` is called by the `AlarmTask` when we have a newly-confirmed block. The raiden service in turn, fetches all the blockchain events for this specific block and passes them to the `BlockchainEventHandler` where these blockchain events are converted to state changes and passed down to the state machines.
Once all events have been processed, the `Block` state change is then dispatched.

The problem with this approach is that it leads to conditions where a Raiden would react to a certain blockchain event by sending a transaction or a message to the channel partner. In this case, Raiden's view of the currently confirmed block number at which we're handling the event is off by one.

Example:

Block 4999:
<- Raiden ContractSendChannelNew
Block 5000
-> BC Event: New Channel
-> Raiden: We have a channel, let's deposit (*)
-> Raiden: Store the new block to the latest state

The problem is where `(*)` is. At this point, if we query Raiden's state machine about the current block number, 4999 would be returned because the state change for block 5000 wasn't dispatched, even though we're handling a blockchain event that was triggered by block 5000.

## Motivation

This issue was observed leading to issues in certain scenarios such as the one described above. The proposed solution is to atomicly dispatch all state changes and then react to all events produced by applying those state changes.

## Specification

- [ ] Change the raiden service to dispatch all state changes in a single batch
- [ ] Wait until all state changes are processed and collect resulting events
- [ ] Dispatch events to their respective event handlers.

https://github.com/raiden-network/raiden/blob/cdcb7ff44be6a48dea43e61e6139dbb61092ceb9/raiden/raiden_service.py#L558-L565

Note that the current implementation dispatches each state change in a greenlet that would also process the resulting events. This was done to prevent blocking event processing while waiting for a blockchain transaction to be mined. This should be taken into consideration.

## Backwards Compatibility

Not a protocol change so it should be fully backwards compatible.

**Comment by hackaugusto** [comment]
this was finalized by #4306
