### ISSUE TITLE
Raiden should provide an API endpoint to query important settings

### ISSUE THREAD

**Issue by konradkonrad** [raiden-network/raiden#4224]
## Abstract

Provide an API endpoint to query Raiden `settings` and `constants`.

## Motivation

When discussing https://github.com/raiden-network/webui/issues/96 we figured out, that an application interacting with Raiden should not have to hardcode magic numbers (such as the block confirmation interval). Therefore we should provide an rpc endpoint that allows app developers to query settings on demand.

## Specification

- [ ] Inquire developers for settings that need to be available to a consumer application
- [ ] Specify API endpoint and query format
- [ ] Implement Endpoint
- [ ] Add tests

**Comment by rakanalh** [comment]
Closing in favor of #5011
