### ISSUE TITLE
Fix withdraw race condition

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/raiden#4233]
## Abstract

    A requests withdraw from B with total_withdraw=10
    B confirms withdraw for A with total_withdraw=10
    A sends withdraw to the chain
    A requests withdraw from B with total_withdraw=20
    The transaction for the first withdraw is confirmed, this will overwrite the total_withdraw
    B confirms the total_withdraw=20, A will wrongly reject

https://github.com/raiden-network/raiden/pull/4130#discussion_r294267626

**Comment by rakanalh** [comment]
This was fixed in #4258
