### ISSUE TITLE
Initiator: Split Refund transfer handling

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/raiden#4257]
## Abstract

When a node receives a refund transfer there are a few options:

##### For token swaps

- The secret is *not* controlled by Raiden (The secret is controlled by an external resolver, or the node is starting the second leg of a swap with a simple HTL):
  - The node may give up on the current token swap, and just wait for the pending transfer to expire.
     - This can be informed to the external resolver, which may then reveal the secret to unlock the failed route, and it may start a new transfer with a *new* secret.
  - The node may want to retry the swap using a new forward channel and the *same* secrethash.

##### For token swaps and mediated transfers

- The secret *is* controlled by Raiden (The node is starting first leg of a swap or a mediated transfer using a HTL):
  - The node may give up on the transfer.
    - It can then wait for the pending transfer to expire or release the secret, either way the unlock was unsuccessful.
  - The node may want retry the transfer using a new forward channel and a *new* secret.

## Motivation

The above behavior should be policy driven #216 and as such cannot be controlled inside the state machine. Therefore the possibilities above have to be split into different state changes, where a policy can control their behavior.

## Specification

Add three new state changes:

- ActionTryNewRouteWithSameSecretHash
- ActionTryNewRouteWithNewSecretHash
- ActionReleaseSecretRefundedTransfer

## Backwards Compatibility

For the database format, rhe above is not backwards compatible, which is okay since database downgrades are not supported.
This does not change the REST API or the Protocol, so it's compatible with these.

**Comment by rakanalh** [comment]
Refund transfers will be disabled in the codebase for now. Putting this task on hold so that we close this or resume working depending on what we decide regarding refunds.

**Comment by hackaugusto** [comment]
duplicate: Allow reuse of secret/secretHash after RefundTransfer(initiator) #3945
