### ISSUE TITLE
Disable refund transfer in preparation for phase-out.

### ISSUE THREAD

**Issue by lullis** [raiden-network/raiden#4288]
We plan to phase out the refund transfer mechanism and remove in case we don't find any case that requires such functionality.
For the moment, we need to remove all calls to refund-related functionality and disable/rewrite all test cases that touch this part of the system

- [x] Comment out function calls related to refund transfers
- [x] Check that state machine does not handle any refund-related message
- [x] Mark into tests related to refunds as skippable/xfailed

**Comment by rakanalh** [comment]
@lullis The decision was to "disable" refunds for now which is by removing / commenting out the parts of that trigger a refund transfer:

https://github.com/raiden-network/raiden/blob/cb9e6975b8d2e32570dc41e8b0027a69f48d33fc/raiden/transfer/mediated_transfer/mediator.py#L461-L471

That's the immediate solution we're going for. The longer term approach depends so i think it's early to "prepare" for phasing it out.

**Comment by karlb** [comment]
After more discussion, the result is that we want to
* still disable refunds (no refunds executed for normal users of the Raiden client)
* keep all refund related tests running

If necessary, a flag to toggle refunds can be introduced that enables refunds inside the refund tests and turns them off in all other cases.

**Comment by LefterisJP** [comment]
From what I understand this issue is no longer relevant as refund transfers will not, after all, be disabled.

**Comment by karlb** [comment]
If I'm correctly informed, the decision was to not only make the refund free, but also refund the fees incurred during the refunded transfer. This makes it attractive to the initiator to actually reveal the secret for the refunded transfers, which he otherwise probably won't do.
This is not urgent, since our implementation will reveal the secret even if it's not optimal from a game theoretical point of view. But if we keep the refunds in the long run, we will need that at some point.

**Comment by LefterisJP** [comment]
@karlb I was not here when the back and forth on phasing refund or not happened. Whoever was, please make issue/issues describing what was decided or link to any issues made.

**Comment by karlb** [comment]
The new ticket is https://github.com/raiden-network/raiden/issues/4533.

**Comment by LefterisJP** [comment]
@karlb Thanks a lot man!
