### ISSUE TITLE
Write MVP User Stories

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#429]
## Requirements
- [ ] A relatively new computer < 5 years old
- [ ] The computer must be connected to the Internet
- [ ] The computer must have Linux or Mac OSX as an operating system
- [ ] A geth node installed and synced
- [ ] An ethereum account with funds available

## Installation
- [ ] A user must be able to access the Raiden website.
- [ ] On the Raiden website the user must be able to navigate to the `Download` section.
- [ ] Under the download section the user must be able to select which Raiden client to download or installation instructions
- [ ] It must be possible to download clients for Linux and read Mac OSX install instructions
- [ ] The website must contain a simple installation guide
- [ ] When the download is done, the user must be able to install the Raiden client with one click/command

## Starting Raiden
- [ ] It must be possible for a user to start the Raiden client with one command
- [ ] The user must be able to access a minimal GUI for interacting with Raiden, once Raiden is started
- [ ] The GUI must present the user with relevant information about the user's raiden channels
- [ ] It must show the current open channels of the user and the status hereof
- [ ] It must show the token networks the user currently participates in
- [ ] If the user does not have any open channels, he/she should be made aware hereof and a button for starting token networks or participating in a token network should be presented
- [ ] The user must be presented to failure modes if geth is not available or no funds are present etc.
- [ ] The user must be presented to a message with instructions for the RPC endpoint/UI

## Adding a token
- [ ] The GUI must allow the user to join a network for an already existing token 
- [ ] It should be possible to create a network for an already existing token using the GUI
- [ ] Tokens held by the account should be highlighted in a token overview
- [ ] There must be a dummy ERC20 token contract that mints new tokens on interaction from the user
- [ ] There must be an echo node for users to interact with
- [ ] The user should not experience a difference between adding a new token network or joining an already existing one

## Opening channels
- [ ] Upon joining a token network the user must specify an amount of tokens to use and he/she should automatically be connected to existing participants of that token network
- [ ] It should be possible to open a direct channel with some specified token and account address 
- [ ] The UI should communicate prior to connecting what the user's capacities in the channels will be (for automatic provisioning)

## Depositing
- [ ] The user must be able to deposit more tokens to a channel than initially deposited (just a documented rpc call)

## Inspecting channels
- [ ] The user must be able to inspect the state of a specific channel
- [ ] the user must be able to see the state of all open channels

## Transfer of a specific token
- [ ] The user must be able to specify the receiving address and the amount he/she wants to transfer

## Closing channels
- [ ] The user should be able to close an open channel
- [ ] The interface must provide a method to shutdown the client and block until it is safe to leave

## Re-entering a raiden network
- [ ] It must be possible for a user to enter a token network after having left it

**Comment by czepluch** [comment]
Also, where should this reside?

**Comment by czepluch** [comment]
Closing. User stories now reside in the wiki https://github.com/raiden-network/raiden/wiki/MVP-User-Stories
