### ISSUE TITLE
RuntimeError: The database connection was not closed.

### ISSUE THREAD

**Issue by agatsoh** [raiden-network/raiden#4291]
While running the latest raiden development branch I get [this](https://gist.github.com/agatsoh/9fdb620219a446e35ed52019c108c63c)  error.
version 0.100.4.dev670+gcb9e6975b

[node-1Bc966-goerli.17May2019.log](https://github.com/raiden-network/raiden/files/3330061/node-1Bc966-goerli.17May2019.log)
[raiden-debug_2019-06-26T11:45:03.481800.log](https://github.com/raiden-network/raiden/files/3330062/raiden-debug_2019-06-26T11.45.03.481800.log)
[network_edd4d279.zip](https://github.com/raiden-network/raiden/files/3330068/network_edd4d279.zip)

**Comment by palango** [comment]
Was this on a new database?

**Comment by agatsoh** [comment]
@palango The db is this one 
`/home/krishna/.raiden/node_1bc9667e/netid_5/network_edd4d279/v23_log.db`

**Comment by palango** [comment]
> @palango The db is this one
> `/home/krishna/.raiden/node_1bc9667e/netid_5/network_edd4d279/v23_log.db`

Yes, but was do you also see this when you remove (as in put to another place) the db and start from scratch?

**Comment by agatsoh** [comment]
Actually I dont face the db problem anymore in the `monitoring-service` because I changed the testnet to goerli and the service does not complain anymore. It was in the same testnet if i used one account earlier and then change it to another account does the `monitoring-service` complain.(Earlier I used kovan)

**Comment by agatsoh** [comment]
Command that I use to start raiden 
`raiden --eth-rpc-endpoint https://rpc.slock.it/goerli --api-address "http://localhost:5011" --keystore-path ~/.ethereum/keystore/ --address 0x1Bc9667EDCb58197f4A5431FBf0c2289dDc235f3 --network-id goerli --environment-type production --log-file node-1Bc966-goerli.26June2019.log --log-config "raiden:debug" --enable-monitoring`

**Comment by agatsoh** [comment]
Was a database upgrade issue between updates hence closing.
