### ISSUE TITLE
FATAL: The channel was not opened at the provided block

### ISSUE THREAD

**Issue by czepluch** [raiden-network/raiden#4299]
When running a scenario locally I got the following error. Raiden version is develop from 26-06-2019 0.100.4.dev670+gcb9e6975.

Traceback:
https://gist.github.com/czepluch/0064c393bdb9416c0b9e13713fb98346

Log:
https://gist.github.com/czepluch/a607ff89befeef37b392880e8f23191f

Let me know if additional info is required.

**Comment by hackaugusto** [comment]
duplicate #4132
