### ISSUE TITLE
Bad Jump Destination when creating token address

### ISSUE THREAD

**Issue by xiaoyao1991** [raiden-network/raiden#432]
When raiden is setup and console started, I tried following the tutorials and create a token address by running:
`token_address = tools.create_token(initial_alloc=10000, name="ytoken1", symbol="MT", decimals=2)`

but the transaction didn't go through and throws `Bad Jump Destination` error:
https://testnet.etherscan.io/tx/0x180ea8206258347e11f1a5c042781f95bb679182918aa533409a3374e714c925

Any ideas?

**Comment by LefterisJP** [comment]
@xiaoyao1991 please use the latest master and the [Rest API](http://raiden-network.readthedocs.io/en/latest/rest_api.html).

If you encounter any problems with that open an issue.
