### ISSUE TITLE
Scenario(s) for mediation fees

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden#4347]
We need to create a scenario that tests mediation fees and the client/PFS interaction.

Ref #4343

**Comment by Dominik1999** [comment]
we decided not to test mediation fees in the scenario player, right? Can we close that issue?

**Comment by czepluch** [comment]
At least we decided not to do it right now and then potentially implement debug endpoints in the future to be able to assert that mediation fees are being paid.

**Comment by palango** [comment]
We agreed that we want to only check that the mediation fees are properly received by the PFS.

**Comment by palango** [comment]
Closing for https://github.com/raiden-network/raiden/issues/4748
