### ISSUE TITLE
Don't serialize private field of `FeeScheduleState`

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden#4367]
When a `FeeScheduleState` is serialized, it includes the `_penalty_func`, which is private and shouldn't be serialized.

```
'fee_schedule': {'flat': 0, 'proportional': 0, 'imbalance_penalty': None, '_penalty_func': None}
```

**Comment by rakanalh** [comment]
@palango did overriding the "FeeScheduleState" type in `raiden/storage/serialization/types.py` help?

**Comment by palango** [comment]
Didn't try that yet, and created the issue instead.

**Comment by karlb** [comment]
I can't reproduce this, anymore. It seems to be solved by `marshmallow_dataclass` in this commit:
https://github.com/lovasoa/marshmallow_dataclass/commit/750bb1a873a04e6d4b12dd137e58e7db3726badb#diff-be67bc8d0a9f634f273c1261669f88caL188
where it now says

> Copy all public members of the dataclass to the schema

and treats underscore prefixed members as private.

Regression test is at https://github.com/raiden-network/raiden/pull/4530.
