### ISSUE TITLE
Remove gevent.sleep from all tests

### ISSUE THREAD

**Issue by rakanalh** [raiden-network/raiden#4368]
## Abstract

`gevent.sleep` is currently used in some tests to wait for a certain event / state change to be sent / received. The amount of sleep in some cases might not be sufficient and therefore causing flakiness in tests that use sleep instead of waiting for the actual event / state change.

## Specification

- [ ] For each test that uses `gevent.sleep`, figure out why sleep is required.
- [ ] Remove all usage of `gevent.sleep` in tests.
- [ ] Replace waiting with `gevent.sleep` with a wait for a specific message / event / state change.

**Comment by LefterisJP** [comment]
Amen!
