### ISSUE TITLE
Fail test on unlock failures

### ISSUE THREAD

**Issue by rakanalh** [raiden-network/raiden#4369]
## Abstract

Some flakiness in the tests is caused by the fact that happy-case scenarios are being tested and it is assumed that any given transfer is going to be recieved by both participant nodes in the test. However, in some cases this assumption fails and the test failure stacktrace shows a timeout which is vauge.

## Specification

- [ ] the test for a successful transfer should assert for the absence of `EventUnlockClaimFailed` and `EventUnlockFailed`

**Comment by LefterisJP** [comment]
@jomuel @rakanalh which test does this issue refer to?

**Comment by hackaugusto** [comment]
> @jomuel @rakanalh which test does this issue refer to?

@LefterisJP every test that does a transfer. The point is that a timeout exception is not very informative about the actual error.

**Comment by hackaugusto** [comment]
Not all tests were covered. Example: https://circleci.com/gh/raiden-network/raiden/82547#artifacts/containers/2

**Comment by christianbrb** [comment]
Is this related to #5178 ?

**Comment by jomuel** [comment]
> Is this related to #5178 ?

No, it is not related. If I understand #5178 correctly, it is about verifying an onchain unlock happens in a certain situation. This issue is about making integration tests more predictable by asserting no _unexpected_ unlock failures happen.

**Comment by jomuel** [comment]
I made a follow-up PR that should cover all remaining integration tests.

Tests that were left out are:
- several tests in `test_blockchainservice.py`, `long_running/test_settlement.py`, `transfer/test_mediatedtransfer_invalid.py`, `transfer/test_refundtransfer_invalid.py`, in which the transfers are set up to not take the happy path,
- `test_integration_events.py::test_clear_close_queue`, which starts a transfer but does not care about its success.

All other tests either do not involve a transfer, or already use utils that include the no-failed-unlock assertion, like `raiden.tests.utils.transfer.transfer()`
