### ISSUE TITLE
Define the maximum gas that may be used by a smart contract call.

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/raiden#438]
## Problem Definition

Some smart contract functions need to iterate over arrays (e.g. netting channel's unlock), the size of these inputs need to be limited by the available block's gas limit. Raiden must not assume the full block's gas limit is available so a different value must be used.

## Solution

I'm suggesting 40% of the total gas limit.

## Related:

Support batch unlocking #455
Develop a gas slot based settlement_timeout definition #383

**Comment by adrianbrink** [comment]
Why 40%?

**Comment by hackaugusto** [comment]
Arbitrary value that was brought up in a conversation with @heikoheiko , suggestions are welcome :)

**Comment by hackaugusto** [comment]
Starting with #1990 the max is 40% of pi thousand.
