### ISSUE TITLE
Define the maximum number of pending transfers

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/raiden#439]
## Problem Definition

Define the upper limit for the merkle tree size, since the proof is iterate in the `unlock` function.

## Solution

Find what is the maximum length of the merkle proof (thus also the merkle tree height) that can be unlocked with the available gas limit (#438).

## Tasklist

- [x] Write a utility to find the largest tree height, i.e. increase the merkle tree height by one until unlock fails.
- [x] Define this value as a `MAXIMUM_PENDING_TRANSFERS` constant (pending transfers is easier to reason about and to explain to the user in respect to the proof length or tree height).
- [x] Use this maximum height to reject new mediated transfers.
- [x] Write a test that checks the maximum height is enforced.
- [x] Write a test to verify the constant has a sane value.

**Comment by LefterisJP** [comment]
@jomuel Is this issue finished? If yes can you close it?

**Comment by hackaugusto** [comment]
@LefterisJP https://github.com/raiden-network/raiden/pull/1990
