### ISSUE TITLE
Geth 1.9.0 not working

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/raiden#4412]
## Problem Definition

The stress test is failing ATM with Geth 1.9.0, both locally and in the CI. It seems the transaction to deploy the smart contract is not being mined.

https://github.com/raiden-network/raiden/pull/4410

**Comment by palango** [comment]
Adding this to the Ithaca milestone. We should at least test that raiden is working fine with 1.9.

**Comment by LefterisJP** [comment]
Taking a look at this issue to see how hard it is to solve it. Will also take up @hackaugusto 's PR if I find a solution.

**Comment by LefterisJP** [comment]
Fixed by #4410
