### ISSUE TITLE
Remove module from message serialization

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden#4427]
Currently the serialization of messages contains the module path of the message class https://github.com/raiden-network/raiden/blob/develop/raiden/storage/serialization/cache.py#L18

This shouldn't be included in a publicly visible message data, as it is implementation specific.

**Comment by hackaugusto** [comment]
Please, do not use the internal serialization class for external object. Just replace it with simplejson or something similar.

**Comment by palango** [comment]
> Please, do not use the internal serialization class for external object. Just replace it with simplejson or something similar.

But then we have (possibly) some duplication for serialization. @ulope Have you thought about this before in the matrix team?

**Comment by ulope** [comment]
@palango No, but since we're only de-/serializing the message classes in the transport we haven't run into this problem.

@hackaugusto I don't understand what you mean with 'external objects'. Non-message objects?

**Comment by palango** [comment]
I think what Augusto means is that internal infos (such as the module of the message classes) should not leak to the outside, such as in messages.

**Comment by rakanalh** [comment]
This approach was generally created to be able to serialize class X and store the serialized blob into the DB. Once this blob is fetched from the database we need to figure out a way to be able to know what marshmallow schema to use to be able to deserialize this.

This applies to messages, states, state changes and events. If we wanted to remove it overall, we would need to create a map that hardcodes certain class name to a certain class/module. Doing it only for messages is the same approach but with a smaller list.

**Comment by karlb** [comment]
Planned approach:
* Remove module path after serialization before sending the message
* When receiving a message, look up the class from a message_name -> message_class dictionary
