### ISSUE TITLE
FATAL: Call to createERC20TokenNetwork failed

### ISSUE THREAD

**Issue by Dominik1999** [raiden-network/raiden#4434]
## Node tries to register new token but failed

Potentially this is a bug. 
Some scenarios (seen at MS2 and PFS5) failed with the below error message, see 
- [MS2](http://scenario-player.ci.raiden.network/Scenario_player_Logs-ms2_simple_monitoring-1-latest-2019-07-22.tar.gz)
- [PFS5](http://scenario-player.ci.raiden.network/Scenario_player_Logs-pfs5_too_low_capacity-1-latest-2019-07-22.tar.gz)
```
{"event": "Waiting for nodes to finish starting", "logger": "scenario_player.runner", "level": "debug", "timestamp": "2019-07-22 15:21:09.092021"}
{"url": "http://127.0.0.1:50345/api/v1/tokens/0x5F3dac7aEdc43113e3BD8c457225e0d956562533", "event": "Registering token with network", "logger": "scenario_player.runner", "level": "info", "timestamp": "2019-07-22 15:21:09.108240"}
{"url": "http://127.0.0.1:50345/api/v1/tokens/0x5F3dac7aEdc43113e3BD8c457225e0d956562533", "event": "Registering token with network", "logger": "scenario_player.runner", "level": "info", "timestamp": "2019-07-22 15:22:42.833473"}
{"url": "http://127.0.0.1:50345/api/v1/tokens/0x5F3dac7aEdc43113e3BD8c457225e0d956562533", "event": "Registering token with network", "logger": "scenario_player.runner", "level": "info", "timestamp": "2019-07-22 15:22:43.836216"}
{"url": "http://127.0.0.1:50345/api/v1/tokens/0x5F3dac7aEdc43113e3BD8c457225e0d956562533", "event": "Registering token with network", "logger": "scenario_player.runner", "level": "info", "timestamp": "2019-07-22 15:22:44.838918"}
{"url": "http://127.0.0.1:50345/api/v1/tokens/0x5F3dac7aEdc43113e3BD8c457225e0d956562533", "event": "Registering token with network", "logger": "scenario_player.runner", "level": "info", "timestamp": "2019-07-22 15:22:45.841278"}
{"code": -1, "message": "HTTPConnectionPool(host='127.0.0.1', port=50345): Max retries exceeded with url: /api/v1/tokens/0x5F3dac7aEdc43113e3BD8c457225e0d956562533 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d3c488e10>: Failed to establish a new connection: [Errno 111] Connection refused'))", "event": "Couldn't register token with network", "logger": "scenario_player.runner", "level": "error", "timestamp": "2019-07-22 15:22:46.843399"}
```

whereas `node 0` logged:

`FATAL: Call to createERC20TokenNetwork failed`

It seems to be a problem with gas estimation, since the log comes from: 

```
            gas_limit = self.proxy.estimate_gas(
                checking_block, "createERC20TokenNetwork", **kwarguments
            )

            if gas_limit:
                error_prefix = "Call to createERC20TokenNetwork failed"
                gas_limit = safe_gas_limit(
                    gas_limit,
                    self.gas_measurements["TokenNetworkRegistry createERC20TokenNetwork"],
                )
```
in [here](https://github.com/raiden-network/raiden/blob/07380d8bb5af8159c7ef439615003dc21c9e3278/raiden/network/proxies/token_network_registry.py#L154)

The logs of the nodes are in the above links.

**Comment by christianbrb** [comment]
@Dominik1999 Which scenario did you run?

**Comment by Dominik1999** [comment]
MS2 and PFS5. I have linked that above now

**Comment by christianbrb** [comment]
Closing this as it is not reproducible at the moment

Error raised here: https://github.com/raiden-network/raiden/blob/144e01e4fd3faf4d0fd19c0f32f7a6d6c71115a8/raiden/network/proxies/token_network_registry.py#L129

**Comment by Dominik1999** [comment]
duplicate of https://github.com/raiden-network/scenario-player/issues/97

**Comment by christianbrb** [comment]
happened again, here are the logs
http://scenario-player.ci.raiden.network/Scenario_player_Logs-pfs1_get_a_simple_path-1-latest-2019-07-26.tar.gz

**Comment by hackaugusto** [comment]
how can someone tell which node received the request to do the token registration?

**Comment by ulope** [comment]
In the SP it's always the first node to receive the request.

**Comment by Dominik1999** [comment]
> In the SP it's always the first node to receive the request.

according to @nlsdfnbch it is always the last node

**Comment by nlsdfnbch** [comment]
There was a misunderstanding about this (thanks zoom):

The registration request is always send to *the first node*, the discovery check is (for now) always performed on *the last node*.

Sorry for the confusion.

@hackaugusto , @Dominik1999

**Comment by Dominik1999** [comment]
happend two times today 
- http://scenario-player.ci.raiden.network/Scenario_player_Logs-pfs3_multiple_paths-1-latest-2019-07-31.tar.gz
- http://scenario-player.ci.raiden.network/Scenario_player_Logs-pfs2_simple_no_path-1-latest-2019-07-31.tar.gz

**Comment by Dominik1999** [comment]
Ok this is what I found out.

This bug seems to be flaky. It could be a race condition since 
- the SP deploy a new token with initial supply `0`, see 
[`constructor_parameters=(0, decimals, name, symbol),
`](https://github.com/raiden-network/scenario-player/blob/179394fccb97b2ae3b0fce6fd644fd75a2f36cee/scenario_player/utils/legacy.py#L245)
- the TokenNetworkRegistry calls TokenNetwork to create a new TokenNetwork, see [here](https://github.com/raiden-network/raiden-contracts/blob/d97b8f66132e0da58076637719f2d035e7fe6b99/raiden_contracts/data/source/raiden/TokenNetworkRegistry.sol#L87), but requires [`require(token.totalSupply() > 0);`](https://github.com/raiden-network/raiden-contracts/blob/d97b8f66132e0da58076637719f2d035e7fe6b99/raiden_contracts/data/source/raiden/TokenNetwork.sol#L248)
- so sometimes it happens that the nodes did not mint tokens before the TokenNetworkRegistry was called. That could explain why that bug happened on different scenarios and only rarely

See long explanation:

So the transaction for token registration failed today for the above two scenarios, see here 

https://goerli.etherscan.io/address/0xd207142dcefd4217d7471a6d3c971029f4d819dd

- transaction for pfs2: https://goerli.etherscan.io/tx/0x04e572d0be203c9d2eaa4b2031dbfda28191531bfda9dd888abb195fd8f5b340
- corresponding token address `0xfdc041ceff07c84dc2fa31c0d52ad352bc385db6`

- transaction for pfs3: https://goerli.etherscan.io/tx/0x76a6cdd0bc1bc3aa9a1c88e29d4b763f4e44b2651f3038244e619eda6f7ff78b
- corresponding token address `0x43bbd4c07fe0cfde5ac11f5ff23da9d105c41d45`

Somehow the transactions got "Reverted" by trying to execute 

(line 1938 in the TokenNetworkRegistry)

```
    /// @notice Deploy a new TokenNetwork contract for the Token deployed at
    /// `_token_address`.
    /// @param _token_address Ethereum address of an already deployed token, to
    /// be used in the new TokenNetwork contract.
    function createERC20TokenNetwork(
        address _token_address,
        uint256 _channel_participant_deposit_limit,
        uint256 _token_network_deposit_limit
    )
        external
        canCreateTokenNetwork
        returns (address token_network_address)
    {
        require(token_to_token_networks[_token_address] == address(0x0));

        // We limit the number of token networks to 1 for the Bug Bounty release
        token_network_created = token_network_created + 1;

        TokenNetwork token_network;

        // Token contract checks are in the corresponding TokenNetwork contract
        token_network = new TokenNetwork(
            _token_address,
            secret_registry_address,
            chain_id,
            settlement_timeout_min,
            settlement_timeout_max,
            deprecation_executor,
            _channel_participant_deposit_limit,
            _token_network_deposit_limit
        );

        token_network_address = address(token_network);

        token_to_token_networks[_token_address] = token_network_address;
        emit TokenNetworkCreated(_token_address, token_network_address);

        return token_network_address;
    }
}
```

whereas 

1. `require(token_to_token_networks[_token_address] == address(0x0))` is true for both addresses and 
2. `canCreateTokenNetwork` is also true 

the transaction fails by calling ` token_network = new TokenNetwork(` which also checks for different preconditions: 

```
        // Make sure the contract is indeed a token contract
        require(token.totalSupply() > 0);
```

**Comment by Dominik1999** [comment]
happened saturday again with 
- ms1: http://scenario-player.ci.raiden.network/Scenario_player_Logs-ms1_simple_monitoring-1-latest-2019-08-04.tar.gz
- ms3: http://scenario-player.ci.raiden.network/Scenario_player_Logs-ms3_simple_monitoring-1-latest-2019-08-04.tar.gz
- pfs4: http://scenario-player.ci.raiden.network/Scenario_player_Logs-pfs4_use_best_path-1-latest-2019-08-04.tar.gz
- pfs5: http://scenario-player.ci.raiden.network/Scenario_player_Logs-pfs5_too_low_capacity-1-latest-2019-08-04.tar.gz

**Comment by Dominik1999** [comment]
ok this time all transactions were successful. So this might be another bug. 

- https://goerli.etherscan.io/tx/0x1f0da7a02bef858ef5312e2e84b3c1465fc8a199e4bfa3d58fa0b24e84fab174
- https://goerli.etherscan.io/tx/0x3d2923f4c62678be3435460cb190186eafd3ee38c070478d110dd8997cd4d25d
- https://goerli.etherscan.io/tx/0x9c3c09b3dceb8dea648bb97b086803fbb445f034b24c99dfd2197a1694f7fc13
-  https://goerli.etherscan.io/tx/0x6a66d14decbd4affcfd01970f53838cf732a8f5040149b9a96b390309e4b7f9c

There traceback this time of all nodes is:
```
Traceback (most recent call last): File "/usr/local/lib/python3.7/site-packages/raiden/network/proxies/utils.py", line 121, in log_transaction yield File "/usr/local/lib/python3.7/site-packages/raiden/network/proxies/token_network_registry.py", line 165, in _add_token receipt = self.client.poll(transaction_hash) File "/usr/local/lib/python3.7/site-packages/raiden/network/rpc/client.py", line 675, in poll raise Exception("invalid transaction, check gas price") Exception: invalid transaction, check gas price
```

so it is a different bug this time. 
`raise Exception("invalid transaction, check gas price") Exception: invalid transaction, check gas price `  
see XXX

It is another bug,
