### ISSUE TITLE
mypy: enable warn_unreachable 

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden#4443]
Since mypy 0.720 (see #4442) it can report unreachable code. We should enable that flag.

**Comment by LefterisJP** [comment]
I have enabled it in rotkehlchen. It's nice but can also have some false positives at the moment.

**Comment by palango** [comment]
This found the problem fixed in 083f98c0b04140426c5bc7fddeed78dc7a826363

We should enable it, even though there are some false positives.
