### ISSUE TITLE
Add a HTTP end point for atomic swaps

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/raiden#445]
## Problem Definition

Raiden needs to expose an atomic swap interface.

## Solution

For the atomic swap execution one node will initiate the swap, the other node will preset the expected rate and verify once the swap message is received, the alternative approach is to not preset the rate but to inquire (through a callback mechanism) if the received swap is valid, this second approach has the down sides of increasing latency of the mediated transfer and would force the REST API to have an additional end point for emitting events to do the inquiry.

Note: For atomic swaps both nodes need to agree on an exchange rate, the process through which the exchanges are agreed upon is not defined by Raiden.

## Tasklist

- [ ] Add an endpoint for presetting the expected rate `api/1/atomic_swap/expect_exchange/:receiving_token/:receiving_amount/:sending_token/:sending_amount`
  - This end point blocks until the swap is completed or a timeout happens, the lock expiration is not defined at the moment of the call so a different value needs to be used.
- [ ] Add an endpoint for starting the swap: `api/1/atomic_swap/transfer/:receiving_token/:receiving_amount/:sending_token/:sending_amount`
  - This end point blocks until the swap is completed or a timeout happens, the endpoint doesn't need to block until the lock expiration since this is the node controlling the secret.

The arguments `:receiving_token`, `:receiving_amount`, `:sending_token`, and `:sending_amount` are in respect to each node, e.g. (Note the parameters are the opposed for each node.):

1. Alice will send 10 A to Bob, Bob will send 15 B in return.
1.1 Bob will configure it's Raiden node to expect the swap where he receives 10 A and sends 15 B.
1.1 Alice will start the swap by sending 10 A and receiving the 15 B.

**Comment by LefterisJP** [comment]
Closed in favour of: https://github.com/raiden-network/raiden/issues/465
