### ISSUE TITLE
Node should request info from PFS more often than once

### ISSUE THREAD

**Issue by Dominik1999** [raiden-network/raiden#4454]
## Abstract

At the moment the Raiden Client requests the PFS one time at startup and in case there is no answer, the Raiden Client stops. We should request three times before stopping the client. 

See https://github.com/raiden-network/raiden/blob/7388dede1b023778feca548e873078919a11fe3e/raiden/network/pathfinding.py#L142

## Motivation

We have seen the case, where the PFS is online but the request failed for some reason (maybe bed connection). 

## Specification

Here is a method that potentially can be used, see https://www.peterbe.com/plog/best-practice-with-retries-with-requests

**Comment by karlb** [comment]
Is this only for the case that the PFS is explicitly given? When it's not given, I would prefer to try a different PFS from the service registry immediately.

**Comment by Dominik1999** [comment]
makes totally sense!

**Comment by hackaugusto** [comment]
This was fixed by https://github.com/raiden-network/raiden/pull/4468/ , it will try every PFS available from the registry.
