### ISSUE TITLE
Ship TokenNetwork contract state snapshot with the client

### ISSUE THREAD

**Issue by pirapira** [raiden-network/raiden#4455]
## Abstract

This issue proposes shipping TokenNetwork snapshots together with the client software.  Then, the node can launch faster.

Currently, whenever a node starts from an empty database, the user needs to wait a lot while the node follows the whole history of the TokenNetwork contracts.  If the client software contains the state of the TokenNetwork contracts, the ndoes need to follow only the most recent history after the snapshots.

## Specification

[tbd]

## Backwards Compatibility

There must be an option for a suspecting user to sync the node in the old-fashioned way (following all events from the deployment time).

**Comment by hackaugusto** [comment]
Note: The speed of the first sync was drastically improved by https://github.com/raiden-network/raiden/pull/5003

**Comment by palango** [comment]
https://github.com/raiden-network/raiden/issues/6497 should fix this.
