### ISSUE TITLE
Remove block numbers from the smart contract events

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/raiden#450]
## Problem Definition

[NettingChannel](https://github.com/raiden-network/raiden/blob/b70cd3d5074ed4605b3a643834b74dc5c5604ed7/raiden/smart_contracts/NettingChannelContract.sol#L9-L12) expose a few events with the block number, that value is duplicated since it's available through the [eth_getFilterChanges](https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_getfilterchanges)

> blockNumber: QUANTITY - the block number where this log was in. null when its pending. null when its pending log.

## Solution

Remove the `block_number` fields from all smart contract event and use the result from the JSON RPC call.

## Tasklist

- [x] remove the block_number
  - [x] ChannelNewBalance
  - [x] ChannelClosed
  - [x] TransferUpdated
  - [x] ChannelSettled
- [x] Expose the `blockNumber` from the log to the [filter changes](https://github.com/raiden-network/raiden/blob/b70cd3d5074ed4605b3a643834b74dc5c5604ed7/raiden/network/rpc/client.py#L332-L357)
- [x] Fix the code that needs the block number.

**Comment by hrishikeshio** [comment]
I have done the changes. But can you explain "Fix the code that needs the block number"?

**Comment by LefterisJP** [comment]
@hrishikeshio 
There are places in the events handling where the block number is used by reading the event argument.
Instead we can use the JSON RPC call for that. That is what 

> Fix the code that needs the block number.

means.

**Comment by andrevmatos** [comment]
I'm planning to work on that, but a quick search showed `block_number` instance attribute of diverse events being heavily used on the code. As it may be unnecessary to retrieve the block_number from the API every time it is required, maybe we could keep the attribute, but standardize it's use, maybe with a superclass for all events, and it's fetching, from `eth_getFilterChanges` (as I started this work in #836).

**Comment by andrevmatos** [comment]
Instead of removing the `block_number` and adapting every code that used it to re-fetch the event block number, we standardized populating it for every event that had this attribute, getting it directly from events handling/polling. Through #902 and #836 , I'd consider it as solved.

**Comment by LefterisJP** [comment]
Sure, it can be considered closed.

**Comment by hackaugusto** [comment]
How is this solved? The event's block_number was not removed.

**Comment by andrevmatos** [comment]
@hackaugusto look at my last comment above: instead of removing it, we standardized it's fetching from the logs ( `eth_getLogs|FilterChanges`), and with that, avoided the need to provide it in the constructor, while keeping the attribute, used in numerous places.

**Comment by hackaugusto** [comment]
That is the point of the issue, use the block number from the eth_getLogs and then remove the attribute

**Comment by andrevmatos** [comment]
@hackaugusto Just to clarify, are you talking about the block number attribute from the on-chain event, the event objects in Raiden, or both?

**Comment by hackaugusto** [comment]
The on-chain events that are listed on the task list, it doesn't make sense to remove the block number from the Raiden events.

**Comment by andrevmatos** [comment]
Hmm, right.. I confused it on the description with the Python objects that represented the events, as they too had the blocknumber passed in constructor (which was already fixed), but yes, the on-chain events are not properly fixed yet. Re-opening until I can look at the contracts.

**Comment by andrevmatos** [comment]
For the records: this issue was solved by:
#836 : first patch to populate event's `block_number` through blockNumber in which the event was mined
#902 : improvements on above PR, to fetch events with a single RPC call
#945 : finally removed the `block_number` events attribute, also fetching the block_number on `eth_getFilterChanges` calls (events polling).
