### ISSUE TITLE
Diagnostics for failure for RPC-API consumer

### ISSUE THREAD

**Issue by konradkonrad** [raiden-network/raiden#451]
## Problem Definition
For consumer of the RPC-API it is not easily possible to introspect the internal state of Raiden through python in case of an error. We need to ensure that it remains possible to find the cause of a failure. Errors under consideration here are:

- failing transfers: what was the state transition that failed
- ~crashes mid transfer: raiden dies during a pending transfer leads to an unknown result of the transfer~ fixed by the wal #205 the transfer will expire.
- failing transport/discovery: problems to contact a peer (i.e. wrong discovery information, transport timeout

## Solution

For [failing transfers](https://github.com/raiden-network/raiden/issues/440): HTTP status code signals failure. Reasons could be:
- [ ] Lock Expiry/User Cancel Transfer: ends up in the WAL and should be part of the transfer result object.
- [ ] Insufficient Balance: must be part of the transfer result object.

For mid transfer crashes:
- [ ] an initiator does know about the identifier of the transfer; we could add a "query transfer by identifier" endpoint.
- [ ] for mediators and targets: we could add a "get pending transfers" endpoint. But it is possible to trace the state from the write ahead event log.
 
For failing transport/discovery:
We don't expose these internals through RPC, instead we must ensure that:
- [ ] discovery lookup operations end up in the (DEBUG-) application log with sufficient information (lookup address, resolved endpoint).
- [ ] other socket related errors should be encoded into the application log.

**Comment by LefterisJP** [comment]
@hackaugusto Could we considered the debug endpoints for raiden internal event sufficient and close this issue?

Also the failed transfers have a reason string atm.

**Comment by konradkonrad** [comment]
I believe this can be closed!
