### ISSUE TITLE
Figure out why geth and parity do not follow spec for getTransaction()

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#4513]
## Problem Definition

Follow up from: #4497. This is just an issue to track the figuring out of why geth and parity do not follow the RPC spec as defined [here](https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_gettransactionbyhash) and why sometimes `eth_getTransactionByHash` can return a transaction that has a non-null `blockNumber` but in reality the transaction has not yet been mined.

## External links

- Issue in geth. - TODO
- Issue in parity. - TODO

**Comment by hackaugusto** [comment]
They just don't agree. The behavior is documented in Parity and we have assumption test that covers it:

https://github.com/raiden-network/raiden/blob/34fe7c14655107afdb0a0f38f4b07428fa71540e/raiden/tests/integration/rpc/assumptions/test_rpc_gas_price_assumptions.py#L150-L155

**Comment by LefterisJP** [comment]
Sure but that (and all the other points of disagreement between them) should be bugs in either of the clients.

Ethereum implementations should follow a common spec. Nothing actionable for us to do though so yeah closing the issue if we have assumption tests is fine.
