### ISSUE TITLE
Avoid timeout flakiness

### ISSUE THREAD

**Issue by jomuel** [raiden-network/raiden#4524]
Several integration tests use `gevent.Timeout` to wait for a transfer to complete, which means we risk test failure if any part of the system is slow for some reason. A cleaner solution would be to wait for a block at which the transfer is supposed to be completed with `BlockTimeout`.

- [x] introduce a convenience function to replace the repeated wait-until-timeout blocks in the tests

- [ ] replace `gevent.Timeout` with `BlockTimeout`

**Comment by LefterisJP** [comment]
Hey @jomuel I do not understand the point of this issue. Can you maybe explain in a bit more detail?

Why would raiden transfers have to wait for blocks?

**Comment by jomuel** [comment]
If I recall correctly, the point was to set the transfer's expiration as timeout, so the test would not fail because of a transfer taking longer.

**Comment by LefterisJP** [comment]
Aha all right that makes sense.
