### ISSUE TITLE
Return mediation fees during refund

### ISSUE THREAD

**Issue by karlb** [raiden-network/raiden#4533]
When doing a refund, the refund will incur no mediation fees. Additionally, the fees that have been incurred during the refunded transfer should be returned to the node that paid them. This makes it attractive to the initiator to actually reveal the secret for the refunded transfers, which he otherwise probably won't do.
This is not urgent, since our implementation will reveal the secret even  if it's not optimal from a game theoretical point of view. But if we  keep the refunds in the long run, this is the most sensible choice we could come up with.

**Comment by Dominik1999** [comment]
see https://github.com/raiden-network/team/issues/498#issuecomment-512160320 for the decision

**Comment by Dominik1999** [comment]
this might also lead to a bug in the current behaviour as @palango pointed out.

A refund transfer looks like 

`A -> B -> C -> B -> A `

With the current Raiden behaviour, `B` and `C` would get mediation fees for this transfer. `A` would reveal the secret anyway. 

That allows for the following possible attack from `B`

`B` could simply refund every transfer immediately (send it back to `A`) but keep the fee.

**Comment by karlb** [comment]
Irrelevant, since we will remove refund transfers in its current form.
