### ISSUE TITLE
[Restartable Tasks] Dispatch new routes if existing at newChannel

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#456]
Whenever a new channel is opened, check the graph and see if a new route is available towards any of your node's targets. If it does then take the route and add it to the state.

**Comment by hackaugusto** [comment]
This was done on a series of PRs: 

#1272 Adds NettingChannelState, NettingChannelEndState
#1278 Adds TokenNetworkGraphState, TokenNetworkState, objects required to represent the network graph, and the actions to modify it
#1279 Adds the logic to handle ChannelState objects (logic required filter routes based on available capacity)
#1292 #1291 #1290 Changed the mediator role tasks to use the TokenNetworkState graph
#1325 integrated the changes from the previous PRs
