### ISSUE TITLE
log_time format is different between documentation and respone

### ISSUE THREAD

**Issue by kelsos** [raiden-network/raiden#4560]
## Problem Definition

I am calling the payment REST API:
`http://localhost:5001/api/v1/payments/0x95B2d84De40a0121061b105E6B54016a49621B44/0x82641569b2062B545431cF6D7F0A418582865ba7`

According to the documentation:
```
raiden_events contain a timestamp field, log_time, indicating when they were written to the write-ahead log. The format of log_time is ISO8601 with milliseconds.
```
Verifying with v0.100.1 this seems to be true for that version but it is not for the latest develop version.

What the API returns now is the following: `"log_time": "2019-08-06 14:52:02"`. This format is also what is stored in the database for the timestamps.

```json
[
    {
        "event": "EventPaymentReceivedSuccess",
        "log_time": "2019-08-06 14:52:02",
        "identifier": 1565103119921,
        "amount": 1,
        "initiator": "0x82641569b2062B545431cF6D7F0A418582865ba7"
    }
]
```

### System Description

Here add a detailed description of your system, e.g. output of the following script:

```
Linux forseti 5.2.6-arch1-1-ARCH #1 SMP PREEMPT Sun Aug 4 14:58:49 UTC 2019 x86_64 GNU/Linux
/usr/bin/solc
solc, the solidity compiler commandline interface
Version: 0.5.10+commit.5a6ea5b1.Linux.g++
/usr/bin/geth
INFO [08-09|13:31:41.596] Bumping default cache on mainnet         provided=1024 updated=4096
Geth
Version: 1.9.1-stable
Git Commit: b7b2f60f866d92e75db5bfe5be51b48eadeb3150
Git Commit Date: 20190724
Architecture: amd64
Protocol Versions: [63]
Network Id: 1
Go Version: go1.12.7
Operating System: linux
GOPATH=
GOROOT=/usr/lib/go
/usr/bin/parity
Parity Ethereum
  version Parity-Ethereum/v2.5.5-stable-3ebc769757-20190708/x86_64-linux-gnu/rustc1.35.0
Copyright 2015-2019 Parity Technologies (UK) Ltd.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

By Wood/Paronyan/Kotewicz/Drwięga/Volf
   Habermeier/Czaban/Greeff/Gotchac/Redmann

/home/kelsos/.virtualenvs/raiden-develop/bin/raiden
{
  "raiden": "0.100.5.dev288+ga2270259b",
  "raiden_db_version": 23,
  "python_implementation": "CPython",
  "python_version": "3.7.4",
  "system": "Linux 64bit_ELF 5.2.6-arch1-1-ARCH",
  "architecture": "x86_64",
  "distribution": "source"
}

```

**Comment by ulope** [comment]
The reason for the missing milliseconds seems to be that the timestamp columns in the Raiden DB have their default value set to `CURRENT_TIMESTAMP` which according to the [sqlite docs](https://www.sqlite.org/lang_createtable.html) expands to `YYYY-MM-DD HH:MM:SS`.

According to [this SO answer](https://stackoverflow.com/a/17575175/107946) the solution would be to use a default of `DEFAULT(STRFTIME('%Y-%m-%d %H:%M:%f', 'NOW'))` instead.
