### ISSUE TITLE
limit and offset on payment api don't seem to work as expected

### ISSUE THREAD

**Issue by kelsos** [raiden-network/raiden#4561]
## Problem Definition
The limit and offset query parameters when calling the payment event API, don't work as expected.

`http://localhost:5001/api/v1/payments/0x95B2d84De40a0121061b105E6B54016a49621B44/0x82641569b2062B545431cF6D7F0A418582865ba7`

I have 4 payments in the data.
 
If I use `limit=1` I get an empty array. I would expect to get 1 result since the offset is 0,
If I use `offset=1` or 2 or 3, I still get 4 results back. I would expect to get fewer results. since the offset changes, but it doesn't seem to affect the results returned in a way I would expect.

If on the other hand, I do an 11 offset I will actually get 3 results back. Is there a chance that limit and offset actually work on a different data set and then that is filtered?

I also verified with v0.100.1 and the same behavior is consistent with that version too.

### System Description

Here add a detailed description of your system, e.g. output of the following script:

```
Linux forseti 5.2.6-arch1-1-ARCH #1 SMP PREEMPT Sun Aug 4 14:58:49 UTC 2019 x86_64 GNU/Linux
/usr/bin/solc
solc, the solidity compiler commandline interface
Version: 0.5.10+commit.5a6ea5b1.Linux.g++
/usr/bin/geth
Geth
Version: 1.9.1-stable
Git Commit: b7b2f60f866d92e75db5bfe5be51b48eadeb3150
Git Commit Date: 20190724
Architecture: amd64
Protocol Versions: [63]
Network Id: 1
Go Version: go1.12.7
Operating System: linux
GOPATH=
GOROOT=/usr/lib/go
/usr/bin/parity
Parity Ethereum
  version Parity-Ethereum/v2.5.5-stable-3ebc769757-20190708/x86_64-linux-gnu/rustc1.35.0
Copyright 2015-2019 Parity Technologies (UK) Ltd.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

By Wood/Paronyan/Kotewicz/Drwięga/Volf
   Habermeier/Czaban/Greeff/Gotchac/Redmann

/home/kelsos/.virtualenvs/raiden-develop/bin/raiden
{
  "raiden": "0.100.5.dev288+ga2270259b",
  "raiden_db_version": 23,
  "python_implementation": "CPython",
  "python_version": "3.7.4",
  "system": "Linux 64bit_ELF 5.2.6-arch1-1-ARCH",
  "architecture": "x86_64",
  "distribution": "source"
}

```

**Comment by LefterisJP** [comment]
I will have a first look to see what happens.

**Comment by LefterisJP** [comment]
Okay found the reason behind this. It's rather simple but will require some rewriting.

## Problem 

The only way the `limit` and `offset` are currently used is for the final DB query. But the final DB query, queries for all types of data, not only payment events.

https://github.com/raiden-network/raiden/blob/96aaee0539587bd24d08b3a518855335570d377a/raiden/storage/sqlite.py#L582-L594

So this just gets `limit` events from the DB. But those events get filtered up later in the DB to be only payment events ... and that's where things break.

https://github.com/raiden-network/raiden/blob/96aaee0539587bd24d08b3a518855335570d377a/raiden/api/python.py#L995-L1008

## Proposed Solution

We need to move the filtering functionality of `event_filter_for_payments` into the DB query itself.

https://github.com/raiden-network/raiden/blob/96aaee0539587bd24d08b3a518855335570d377a/raiden/api/python.py#L84
