### ISSUE TITLE
Token

### ISSUE THREAD

**Issue by bitcoinmeetups** [raiden-network/raiden#457]
Hello,
How are you?
Can I make my own token and release it on Raiden?
BM

**Comment by LefterisJP** [comment]
You can make your own token in Ethereum [using](https://www.ethereum.org/token) a smart contract.
And using Raiden you can create payment channels for that token. 

Does that answer your question?

**Comment by hackaugusto** [comment]
Closing the issue since 7 days passed. Feel free to reopen or talk with us at: https://gitter.im/raiden-network/raiden
