### ISSUE TITLE
Upgrade raiden-contracts to 0.29.1

### ISSUE THREAD

**Issue by pirapira** [raiden-network/raiden#4583]
`raiden-contracts 0.29.1` upgrades `web3` and `eth-utils`. https://github.com/raiden-network/raiden-contracts/blob/v0.29.1/CHANGELOG.md#0291---2019-08-13  The Alderaan release will be after 0.29.1.

This issue keeps track of using `raiden-contracts 0.29.1` from `raiden:develop`.  Doing so probably involves adding more mypy annotations.

**Comment by LefterisJP** [comment]
I guess we are skipping v0.29.1
