### ISSUE TITLE
[WIP] Remove echo_node from Raiden client code

### ISSUE THREAD

**Issue by Dominik1999** [raiden-network/raiden#4588]
We have a Raiden echo_node in the raiden repo, see https://github.com/raiden-network/raiden/blob/develop/raiden/utils/echo_node.py

This should be removed from the client code and tests since it is not a client related feature. This way we can keep the code cleaner. 

However, the echo node should be usable and working. So we need to outsource the code from the Raiden repo. 

@christianbrb

**Comment by christianbrb** [comment]
@eorituz Can you check how frequently the echo node is getting used?

**Comment by eorituz** [comment]
So I have 2 Echonodes permanently running, using our Raiden Docker image.

**Comment by Dominik1999** [comment]
cool! But can we somehow outsource that code from the raiden client?

**Comment by palango** [comment]
> So I have 2 Echonodes permanently running, using our Raiden Docker image.

Does anybody ever use them?

**Comment by eorituz** [comment]
> > So I have 2 Echonodes permanently running, using our Raiden Docker image.
> 
> Does anybody ever use them?

Everyone who uses the wizard or https://try.raiden.network can/should interact with the echo nodes.
So I guess outsourcing is fine but we shouldn't "delete" it completely

**Comment by jomuel** [comment]
The clean (and not too costly) way to do this would be to write a python script that

- starts raiden as a subprocess and
- uses the REST API for everything the current echo node does with `RaidenAPI` .

**Comment by eorituz** [comment]
Standalone Echo Node software can be found here: https://github.com/raiden-network/raiden-echo-node
