### ISSUE TITLE
PFS payment scenarios

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/raiden#4591]
### Description
A detailed issue split from https://github.com/raiden-network/scenario-player/issues/216

PFS to be tested:
- **Payments**: 
    - payments (single) ~PFS7 scenario
    - payments (multiples)

### Tasks
- [x] Define scenarios to create or to adjust (two sentences)
- [ ] Implement

**Comment by czepluch** [comment]
I think for single payments PFS7 (soon to be PFS6) covers it fine. I can create another scenario that does ~100 payments and checks for correct capacity updates and request count though. Is that what you had in mind for this @Dominik1999 / @palango ?

**Comment by Dominik1999** [comment]
yes that would be perfect!
