### ISSUE TITLE
PFS Routing contraints scenarios

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/raiden#4592]
### Description
A detailed issue split from https://github.com/raiden-network/scenario-player/issues/216

- **Routing Constraints**:  
    - presence check: node goes offline during test
    - capacity updates (fixed topology, first pfs returns route, then capacity changes, then fewer routes are returned, no route) (1) withdraw (2) transfers -> test with mediating nodes

### Tasks
- [ ] Define scenarios to create or to adjust (two sentences)
- [ ] Implement

**Comment by czepluch** [comment]
So for this I would say that a scenario where payments are made through one path and then the mediating node goes offline, and hence another path should be used would be interesting. This would assure that the PFS correctly updates the presence state of a node.

And a second scenario could be created that checks that the PFS correctly reacts to a partial withdraw. 

What do you think @Dominik1999? Is this what you had in mind? Anything more you'd like?
