### ISSUE TITLE
MS scenarios

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/raiden#4593]
### Description
A detailed issue split from https://github.com/raiden-network/scenario-player/issues/216

MS to be tested:
- UDC Deposit is too low, then the MS should not intervene (Feature from Nils)
- Withdraw node sends MR then withdraws and then MS should get 2 MR 

### Tasks
- [ ] Define scenarios to create or to adjust (two sentences)
- [ ] Implement

**Comment by christianbrb** [comment]
> UDC Deposit is too low, then the MS should not intervene (Feature from Nils)

@palango @Dominik1999 Which feature do we need?

**Comment by czepluch** [comment]
@Dominik1999 Can you explain this to me `Withdraw node sends MR then withdraws and then MS should get 2 MR`? I don't understand what is meant.

**Comment by czepluch** [comment]
First scenario implemented with #4740

**Comment by Dominik1999** [comment]
> @Dominik1999 Can you explain this to me `Withdraw node sends MR then withdraws and then MS should get 2 MR`? I don't understand what is meant.

there should be a MonitorRequest (MR) with every state change in the channel. So when we look at a withdraw event, there must be one MR before and one after withdraw. Does that make sense?

**Comment by czepluch** [comment]
After discussions with @Dominik1999 it turns out that there are no new request for monitoring after a withdraw has been made. It's only relevant for the PFS to know about that. So the second scenario in this issue will not be implemented.

**Comment by czepluch** [comment]
Closed with  #4740
