### ISSUE TITLE
Scenario Routing preferences

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/raiden#4594]
### Description
A detailed issue split from https://github.com/raiden-network/scenario-player/issues/216

- **Routing preferences** (probably new feature):
-- fees to be tested (this needs a new feature request). investigate if already possible 
-- routing preferences: (1) cheapest route (2) shortest route. requires fee setting in SP

### Tasks
~~- [ ] Check, if https://github.com/raiden-network/scenario-player/issues/227 is needed~~
- [ ] Define scenarios to create or to adjust (two sentences)
- [ ] Implement

**Comment by christianbrb** [comment]
This is not configurable at the moment in the Raiden client, just exposed in the Pathfinding Service: https://raiden-network-specification.readthedocs.io/en/latest/pathfinding_service.html#arguments

CC @palango @Dominik1999

**Comment by karlb** [comment]
These are tested in the services repo and again in some SP scenarios.
