### ISSUE TITLE
Enhance control flow in startup checks (*_or_exit functions)

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden#4615]
## Abstract

Currently the checks that run during startup call `sys.exit` in error cases and also print user visible warnings which obscures the control flow and causes problems with tools like `mypy`.

## Motivation

Make the startup code easier to understand and reason about.

## Specification

Avoid calling `sys.exit` in `*_or_exit` functions. Instead throw an exception and handle that in one location.

## Backwards Compatibility

Yes, the state machine is not touched.

**Comment by ulope** [comment]
Related: #4618

**Comment by hackaugusto** [comment]
implemented by https://github.com/raiden-network/raiden/pull/5584
