### ISSUE TITLE
API: pending channels

### ISSUE THREAD

**Issue by kilrau** [raiden-network/raiden#4620]
## Abstract

For our use case, an API call to query pending channels is missing.

## Motivation

We'd like to show the user that the channel is pending and roughly takes x minutes to be ready to be used.

## Specification

N/A

## Backwards Compatibility

N/A

**Comment by LefterisJP** [comment]
Hey @kilrau wouldn't this issue be satisfied if what is requested in https://github.com/raiden-network/raiden/issues/4621 is implemented?

**Comment by kilrau** [comment]
Yes, my bad. Closing.
