### ISSUE TITLE
API: show channel's partner state (active, inactive)

### ISSUE THREAD

**Issue by kilrau** [raiden-network/raiden#4621]
## Abstract

For our use case we'd need to know the detailed channel's partner state as follows:
- active: partner is online
- inactive: partner is offline

## Motivation

For [xud](https://github.com/ExchangeUnion/xud) to know when to use a channel.

## Specification

N/A

## Backwards Compatibility

N/A

**Comment by kilrau** [comment]
As per https://github.com/raiden-network/raiden/issues/4620, it would be nice to take the state as argument and list all channel identifiers with that state.

**Comment by kilrau** [comment]
It would be great if pending channels came with a `tx_id`.

**Comment by rakanalh** [comment]
@kilrau I took the liberty to update the issue and separate the context into this one and #4620

**Comment by karlb** [comment]
User presence can be queries from the PFS via API.
