### ISSUE TITLE
API: allow using full units on endpoints

### ISSUE THREAD

**Issue by kilrau** [raiden-network/raiden#4623]
## Abstract

Allow using full units, like `1.4` weth on endpoints.

## Motivation

18 digits are a nightmare, especially when using endpoints manually due to [lack of a CLI](https://github.com/raiden-network/raiden/issues/4622).

## Specification

Raiden is aware of decimals for each TokenNetwork and can do conversion internally.

## Backwards Compatibility

N/A

**Comment by LefterisJP** [comment]
Are you talking about the REST API endpoints? I don't think this is a good idea for the API. The API is supposed to be used programmatically, and should be simple. Adding conversions in all API endpoints will only make it more complicated.

On the other hand the WebUI, which is a user facing interface, already should have something like that.

**Comment by kilrau** [comment]
If the WebUI features all endpoint functionality and allows full units, then that is indeed sufficient.

**Comment by LefterisJP** [comment]
@kelsos It does, right?

**Comment by kelsos** [comment]
@LefterisJP  Yes the default option in the WebUI is full units (decimal format) and it takes care of the conversion to the API format.

**Comment by kilrau** [comment]
Ok, thx. We'll use the WebUI from now on and report back if we encounter issues there. Closing here.
