### ISSUE TITLE
Raiden Client Blocked

### ISSUE THREAD

**Issue by kilrau** [raiden-network/raiden#4624]
## Intro

Don't block the client. When calls like open channel are running, all calls should still be functioning normally. E.g. we used `/api/v1/channels` as raiden heartbeat. This one is blocked when a channel is being opened (this is quite serious). We switched to, `/api/v1/address` for the heartbeat, but in general no calls should be blocked.

We'll continue adding specific blocking scenarios as comments below.

## Problem Definition

Above.

### System Description

N/A

**Comment by hackaugusto** [comment]
Hummm, @kilrau could you provide the logs of one run that this happened? A `GET` to `/api/v1/channels` should not block, and from a quick look at the code I'm assuming the web server was starving.

**Comment by hackaugusto** [comment]
closing the issue since the critical section for the gas reserve was drastically reduce (which may have been the source of the problem). An alternative is to use the `/address` endpoint for health check.
