### ISSUE TITLE
Preimage stays the same throughout multiple routing attempts

### ISSUE THREAD

**Issue by kilrau** [raiden-network/raiden#4627]
## Abstract

Currently the preimage is being changed by the raiden client when a route fails and a new route is attempted. We need it to stay the same.

## Motivation

Because our atomic swap relies on this preimage. If it changes, the swap fails. This currently limits us to direct channels to make sure the first routing attempt succeeds.

## Specification

Original Reason for differing preimage: because a failed route needs to send refund payment and "use" the preimage it cannot be used again on a second route since it was revealed on the first. 

Similar feedback to what I mentioned in https://github.com/raiden-network/raiden/issues/4626:
* consider moving away from refund payments in the long run. They might bring even more problems, e.g. not enough balance on the way back due to another payment that happened in-between.

Alternative, faster option to solve this: don't redeem refund payments of failed routes immediately, try other routes with same preimage and once a working one is found, reveal preimage to all routes = get all refund payments and send successful payment at once, with the same preimage. **But** increases above mentioned risk.

## Backwards Compatibility

N/A

**Comment by hackaugusto** [comment]
duplicate: Allow reuse of secret/secretHash after RefundTransfer(initiator) #3945
