### ISSUE TITLE
ADR: refund transfers

### ISSUE THREAD

**Issue by pirapira** [raiden-network/raiden#4633]
# what should initiator do for refund transfers

* Status: drafted `needs discussion`

## Context and Problem Statement

- Should `RefundTransfer`s pay fees?
- What should an `initiator` do once it receives a refund?

There are two thoughts regarding the `RefundTransfer` and fees:

- Yes, the refund should incur fees, since the tokens for the mediation have been locked for some time.
- No, since the transfer failed the fees should be reimbursed.

If the mediators do take fees for refunds then there is a question regarding if an initiator should or should not reveal the secret. If the initiator does revel the secret it will pay fees for *a failed* transfer, if the initiator does not then the network liquidity will suffer. The logical decision here would be to *not* reveal the secret.

## Decision Drivers 

* **[3rd-party integration]** For teams trying to integrate Raiden into their own usage, which option is easier?
* **[capacity]** Which option keeps more capacity locked?
* **[fee]** Which one incurs mediation fee costs to the initiator, even for failed payments?
* **[runtime-messages]** Which one reduces the number of messages coming and going?
* **[types-messages]** Which ones remove the type of messages, and shrink the codebase?
* **[success-ratio]** Which strategy has the bigger payment success ratio?
* **[malicious]** Which strategy benefits malicious actors?

## Considered Options

* (a) stop doing refund transfers
* (b) stop doing refund transfers and introduce [Lightning-style "routing failure" hashlock removal](https://github.com/raiden-network/raiden-contracts/issues/1216)
* (c) refunded initiator gives up, revealing the secret
* (d) refunded initiator gives up, not revealing the secret
* (e) refunded initiator retries with the same secret
* (f) refunded initiator retries with a new secret, and reveals the old secret
* (g) refunded initiator retries with a new secret, without revealing the old secret

**Comment by karlb** [comment]
Decision: (a) stop doing refund transfers
