### ISSUE TITLE
test_cli_missing_password_file_enter_password is flaky

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/raiden#4638]
https://circleci.com/gh/raiden-network/raiden/72631#tests/containers/23 This is the relevant part of the logs:

```
You are connected to the 'smoketest' network and the DB path is: /tmp/tmpbrlul4b8/add4d310/keystore/node_67a5e21e/netid_627/network_899d487d/v23_log.db

2019-08-19 10:36:23.597662 [info     ] Using Matrix server            [raiden.network.transport.matrix.utils] average_rtt=0.093629 server_ident=Synapse/0.33.7 server_url=https://raidentransport.exchangeunion.com

FAILED [ 85%]
```

The test was waiting for the REST API to be available:

https://github.com/raiden-network/raiden/blob/0f6ddc4bfa81911b43d04ea81c9c966d681d7e89/raiden/tests/integration/cli/test_cli_production.py#L43-L51

It seems the test didn't make any progress after instantiating the transport and before finishing the service `start`. (The test timeout is 120s, the setup phase took roughly 29.8s, and the logs of the starting app were only 3s apart).

**Comment by LefterisJP** [comment]
The test has not failed since and is not skipped. You already theorized it may be due to #4642. Can we maybe close this issue since it seems to overlap with #4642?

**Comment by ulope** [comment]
Yes, it seems likely that temporary networking issues while connecting to the matrix servers could be the reason for the flakiness.

**Comment by hackaugusto** [comment]
closing as a duplicate of #4642
