### ISSUE TITLE
CLI integration tests should use local matrix servers

### ISSUE THREAD

**Issue by ulope** [raiden-network/raiden#4642]
## Problem Definition

The [cli integration tests](https://github.com/raiden-network/raiden/blob/6f11888397e27ed093dee32465aeab09b683daf0/raiden/tests/integration/cli/test_cli_production.py) currently implicitly use the hosted development matrix servers (transport0[123].raiden.network). 

That is not optimal since it introduces external dependencies for the test runs.

### Proposed Solution

The `raiden_testchain` fixture should start a local matrix server (e.g. by reusing the `matrix_server_starter` utility) and pass that in the generated cli args.

**Comment by hackaugusto** [comment]
This may be the reason for the flakiness of https://github.com/raiden-network/raiden/issues/4638
