### ISSUE TITLE
Raiden process failed to start: client process terminated while waiting for web ui

### ISSUE THREAD

**Issue by Susilmohanty11** [raiden-network/raiden#4647]
## Problem Definition
While Re-lunching raiden (raiden_wizard.linux-gnu.run web UI),  I am getting the bellow error.

There is an error with the pathfinding service with address https://pfs-goerli-with-fee.services-dev.raiden.network. Raiden will shut down.
[I 190820 11:28:51 app:68] Raiden process failed to start: client process terminated while waiting for web ui

How can I fix this issue?

Thanks 
Susil

### System Description

Here add a detailed description of your system, e.g. output of the following script:

```
uname -a
command -v solc && solc --version
command -v geth && geth version
command -v parity && parity --version
command -v raiden && raiden version
[ -d .git ] && git rev-parse HEAD
```

**Comment by LefterisJP** [comment]
Thanks for opening an issue @Susilmohanty11!

That is a known issue and we have seen it happen before.

@palango is this https://github.com/raiden-network/raiden-services/issues/520 where you track this for the services?

**Comment by palango** [comment]
Yes, from the logs looks like this is the problem. I restarted the server for now and started working on a fix.

**Comment by palango** [comment]
Fixed with https://github.com/raiden-network/raiden-services/issues/520
