### ISSUE TITLE
Add option to skip the check for the highest compatible version

### ISSUE THREAD

**Issue by kilrau** [raiden-network/raiden#4662]
## Intro

Probably a feature, but might lead to serious problems down the road when one has to wait for the raiden client to bump the hardcoded geth/parity version. Also, as of now, upgrading raiden to the latest version [is not straightforward in certain environments](https://github.com/raiden-network/raiden/issues/4629).

## Problem Definition

As per https://github.com/raiden-network/raiden/blob/develop/raiden/constants.py#L127, the raiden client currently features a `HIGHEST_SUPPORTED_GETH_VERSION` & `HIGHEST_SUPPORTED_PARITY_VERSION` to ensure compatibility. This is fine and we would definitely want a warning when the used geth/parity version is out of these bounds. BUT we would want raiden to start, even though we are running a higher version. In a [recent example](https://github.com/ExchangeUnion/xud-docker/pull/109) we had to downgrade geth from `1.9.2` to `1.9.1` even though there were no breaking changes between these versions.

An idea is to have a command line argument to skip the check for the highest compatible version is needed (so that it can be scripted).

Another idea is to have a
`HIGHEST_TESTED_X_VERSION` to throw a warning if the used version is higher
`HIGHEST_SUPPORTED_X_VERSION` that is empty on default and only has an entry if there is a known incompatibility with this version

### System Description

N/A

**Comment by palango** [comment]
We ran into the same problem. This was temporarily fixed with https://github.com/raiden-network/raiden/pull/4604 and then properly with https://github.com/raiden-network/raiden/pull/4612 and  https://github.com/raiden-network/raiden/pull/4651.

**Comment by kilrau** [comment]
Thanks, that greatly improves the situation!

A CLI arg to skip the version checks altogether could still be a good idea, though. Let it be for testing only...

**Comment by palango** [comment]
Ok, I change the title and reopen.

**Comment by karlb** [comment]
This should not be a problem anymore since https://github.com/raiden-network/raiden/pull/6447.
