### ISSUE TITLE
Document supported python versions for MacOS

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/raiden#4679]
Currently the binaries available from python.org are not compatible with our code because the monotonic raw clock is not supported. The installation process and the supported version should be documented.

**Comment by err508** [comment]
Stacktrace:

==================================== ERRORS ====================================
__________ ERROR collecting raiden/tests/unit/storage/test_storage.py __________
ImportError while importing test module '/Users/err508/raiden/raiden/tests/unit/storage/test_storage.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
.raiden3.7/lib/python3.7/site-packages/_pytest/python.py:507: in _importtestmodule
    mod = self.fspath.pyimport(ensuresyspath=importmode)
.raiden3.7/lib/python3.7/site-packages/py/_path/local.py:701: in pyimport
    __import__(modname)
.raiden3.7/lib/python3.7/site-packages/_pytest/assertion/rewrite.py:304: in load_module
    exec(co, mod.__dict__)
raiden/tests/unit/storage/test_storage.py:7: in <module>
    from raiden.storage.sqlite import RAIDEN_DB_VERSION, MatrixStorage, SQLiteStorage
raiden/storage/sqlite.py:13: in <module>
    from raiden.storage.ulid import ULID, ULIDMonotonicFactory
raiden/storage/ulid.py:3: in <module>
    from time import CLOCK_MONOTONIC_RAW, clock_getres, clock_gettime_ns, time_ns
E   ImportError: cannot import name 'CLOCK_MONOTONIC_RAW' from 'time' (unknown location)
!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!
=========================== 1 error in 0.45 seconds ============================

Process finished with exit code 2

**Comment by ulope** [comment]
Relevant Python issue: https://bugs.python.org/issue35716

The problem is that the precompiled Python versions for download on python.org are built on a too old macOS version which makes `CLOCK_MONOTONIC_RAW` not be available there.

Solutions are: 
- Use Python from another source, e.g.:
  - Homebrew
  - pyenv
  - pythonz
- Use the Raiden binary bundle since that ships with a working Python interpreter.
