### ISSUE TITLE
[Restartable Tasks] Remove old routes when channel closes or node goes offline

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#468]
This issue is related to: https://github.com/raiden-network/raiden/issues/456

It's the other side of the coin for the same issue. Only this issue tracks the scenario where either a channel is closed or a node goes offline and thus reaches the unreachable state.

In this case and if it is part of a mediated transfer route in our node's route state we should remove it.

**Comment by hackaugusto** [comment]
This was solved by the same PRs metioned on https://github.com/raiden-network/raiden/issues/456#issuecomment-377076626
