### ISSUE TITLE
Add progress information when starting Raiden

### ISSUE THREAD

**Issue by czepluch** [raiden-network/raiden#4681]
## Abstract

Currently we have a problem when users start Raiden for the first time that it takes quite long. It seems as if Raiden is hanging when it is in fact processing events in order to build the correct state. This can be changed by adding some kind of progress information.

In the long run, efforts should be put into decreasing the start up time of Raiden, but for now, this fix will at least give users an impression of what it going on.

## Motivation

According to a face to face discussion we have had, it is proposed to make the webui available as soon as possible and show information there that Raiden is "starting up". Also the CLI should show that events are being processed during start up.

## Specification

I don't believe it's necessary to further specify what this feature entails.

**Comment by czepluch** [comment]
@kelsos will you create the webui part issue? I can also just create one and link to this one for you?

**Comment by palango** [comment]
https://github.com/raiden-network/raiden/issues/4102 sounds similar

**Comment by czepluch** [comment]
@palango yes, it's definitely the same. Had it as an action item from the retreat, but didn't find this when searching.

**Comment by czepluch** [comment]
Dublicate of #4102
