### ISSUE TITLE
Fix coverage report - unit/integration flags work

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/raiden#4703]
#### 2.1 Description

Would build on top of [Add unittest coverage report to CircleCI #4547](https://github.com/raiden-network/raiden/pull/4547)

And is a follow-up of #4664 

#### 2.2 Fullfills the additional requirements

- Percentage for #integration and #unit is correct 
- Target for #unit codecov configuration works (75%)

**Comment by hackaugusto** [comment]
we disabled the coverage because it doesn't work
