### ISSUE TITLE
Transport new user invite needs retries

### ISSUE THREAD

**Issue by ulope** [raiden-network/raiden#4715]
## Problem Definition

In the Matrix Transport we monitor presence events for users of an address that we already know / monitor coming online. Once that happens we spawn a greenlet that invites this user into any existing communication rooms we might have with other users of that address.

However this invite is one-shot only and is not retried.

The reason why retry may be necessary is that the target node might not accept the invite in case the inviter hasn't been whitelisted yet from its perspective.

## Proposed Solution

`MatrixTransport._maybe_invite_user()` needs to implement a retry logic similar to `_get_room_for_address()`. One difference is that the retry should continue until either the user has joined the room or is no longer online.

**Comment by ulope** [comment]
Check if this is still relevant. I assume not.

**Comment by hackaugusto** [comment]
invites are automatically accepted to avoid this race condition.
