### ISSUE TITLE
Also use `production` mode in scenarios

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden#4719]
We should test the use of both `development`  and `production` modes in the scenario player. Ideally we test both with each scenario.

**Comment by rakanalh** [comment]
There's no difference between both really other than the fact that in production mode, raiden crashes on `RaidenUnrecoverableError` if `unrecoverable_error_should_crash` setting is using the default value of `True`.

I am biased towards not spending time on this right now.

**Comment by LefterisJP** [comment]
It is also using different matrix rooms type (https://github.com/raiden-network/team/issues/540#issuecomment-526627464)

**Comment by rakanalh** [comment]
`production` mode is used by default:

https://github.com/raiden-network/raiden/blob/2f6703e154438bd44ad2bfd6fb734d58ce6df856/raiden/ui/cli.py#L197

We should re-word this issue to run with `development` configuration.

**Comment by Dominik1999** [comment]
True, but we set in every scenario the environment type to 
``` 
  default_options:
    gas-price: fast
    environment-type: development
```

**Comment by rakanalh** [comment]
Ok makes sense in this case to also run them in production

**Comment by rakanalh** [comment]
Alright another question:

Should we run all scenarios? this would considerably increase the nightly build time and probably additional server resources. Or, should we select a few scenarios (1 MS, 1 PFS and 1 BF) which can be cloned and set to run with production configs?

**Comment by palango** [comment]
> Ok makes sense in this case to also run them in production

That also means we need to have services running on production. At the moment we don't have those running.

**Comment by Dominik1999** [comment]
I would run all the scenarios, With the decreased settle timeout it only takes 3 hours or so

**Comment by Dominik1999** [comment]
The testplan for Alderaan defines to run all the scenarios in production, see https://docs.google.com/spreadsheets/d/1p63N8a_k-uPIXGpD1UnZzN94a8GAs04kPRwSEjhmDx4/edit#gid=0
