### ISSUE TITLE
pytest tmp path is still too long on macOS

### ISSUE THREAD

**Issue by ulope** [raiden-network/raiden#4727]
## Problem Definition

This is basically a repeat of #1021. Reported again in #4722.
The implemented fix is not sufficient since longer usernames (> 5 chars AFAICS) still lead to an overflow on the IPC path length limit.

## Proposed solution

On macOS we should move pytest's basetemp path to `/tmp` to prevent future occurrences of this. 

Since the contents of the pytest tempdir aren't sensitive there is also no downside to using the 'global' tempdir.

**Comment by palango** [comment]
Fixed in 914883264
