### ISSUE TITLE
Deserialization error on SendWithdrawRequest

### ISSUE THREAD

**Issue by andrevmatos** [raiden-network/raiden#4738]
## Problem Definition

Testing withdraw with the Light Client, on a node with just the channel with the LC, after trying a withdraw which failed due to some issues on the LC side I'm fixing, the `WithdrawRequest` message seems to have been persisted on the state, but on restarting the node, I got the following fatal error on terminal:

```
Traceback (most recent call last):
  File "/opt/venv/lib/python3.7/site-packages/raiden/storage/serialization/serializer.py", line 78, in deserialize
    return schema.load(deepcopy(data))
  File "/opt/venv/lib/python3.7/site-packages/marshmallow/schema.py", line 732, in load
    data, many=many, partial=partial, unknown=unknown, postprocess=True
  File "/opt/venv/lib/python3.7/site-packages/marshmallow/schema.py", line 894, in _do_load
    raise exc
marshmallow.exceptions.ValidationError: {'queueids_to_queues': defaultdict(<class 'dict'>, {'0xE0902284c85A9A03dAA3B5ab032e238cc05CFF9a-42|0x23E1f3B00e09B60044b223Bacee81eADf8F530ff|1': {'value': {0: ["Unable to use schema. Error: Invalid deserializer type\nEnsure there is a deserialization_schema_selector and then it returns a field or a schema when the function is passed in {'nonce': '1', 'expiration': '13264307', 'participant': '0xAAAAAA219100005A77eF9dEf76b24dfB2cD6B35e', 'total_withdraw': '100', 'canonical_identifier': {'chain_identifier': '42', 'token_network_address': '0x23E1f3B00e09B60044b223Bacee81eADf8F530ff', 'channel_identifier': '1'}, 'recipient': '0xE0902284c85A9A03dAA3B5ab032e238cc05CFF9a', 'message_identifier': '14576050161986063955', '_type': 'raiden.transfer.events.SendWithdrawRequest'}. This is the class I got. Make sure it is a field or a schema: None"]}}})}
```

There's some more traceback output in the full output: https://pastebin.com/Zyjqj3P5
It doesn't seem to be on the log though: [raiden-debug_2019-09-04T03:38:29.996420.log](https://github.com/raiden-network/raiden/files/3572620/raiden-debug_2019-09-04T03.38.29.996420.log)

### System Description

docker nightly image from today, with custom `docker-compose.yml`

**Comment by rakanalh** [comment]
@andrevmatos Do you have the database for this node? i'd like to see how the the message was persisted. 

Are you sure you used one version to test this? or did you somehow use a newer version after restart?

**Comment by rakanalh** [comment]
First observation: Taking the mapping of the event and trying to manually deserialize it using:

```
from raiden.storage.serialization import DictSerializer

a = {'nonce': '1', 'expiration': '13264307', 'participant': '0xAAAAAA219100005A77eF9dEf76b24dfB2cD6B35e', 'total_withdraw': '100', 'canonical_identifier': {'chain_identifier': '42', 'token_network_address': '0x23E1f3B00e09B60044b223Bacee81eADf8F530ff', 'channel_identifier': '1'}, 'recipient': '0xE0902284c85A9A03dAA3B5ab032e238cc05CFF9a', 'message_identifier': '14576050161986063955', '_type': 'raiden.transfer.events.SendWithdrawRequest'}

print(DictSerializer.deserialize(a))
```

Produces the correct result.

**Comment by rakanalh** [comment]
I could not reproduce the issue. I was able to write a test which serializes the message and then is able to deserialize it back again.
