### ISSUE TITLE
Scenario bf1_basic_functionality using different matrix servers

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/raiden#4739]
### Problem
In the past, we had issues with Raiden Nodes using different Matrix Servers. As far as I know currently the nodes spawn up by the scenario player all use the same Matrix Server and therefor bugs concerning the use of different Matrix Servers cannot be found.

### Solution
Use different matrix servers within the [bf1_basic_functionality scenario](https://github.com/raiden-network/raiden/blob/develop/raiden/tests/scenarios/bf1_basic_functionality.yaml) for different nodes:

This can be configured via node options: https://github.com/raiden-network/scenario-player/blob/master/examples/scenario-example-v2.yaml#L71-L75

**Comment by czepluch** [comment]
Do you mean that we specify which matrix server to use or that they by accident use the same ones? Afaik, there is an option to specify which matrix server to use per node. In which case, if I understand this issue correctly, it's already solved. But we should probably have another issue to actually use different ones.

**Comment by christianbrb** [comment]
> But we should probably have another issue to actually use different ones.

That's this issue ;-)

**Comment by czepluch** [comment]
Sorry, Misread the issue then. Thanks!

**Comment by christianbrb** [comment]
Updated the issue description as discussed in the daily

**Comment by agatsoh** [comment]
I was testing on the scenario player for this particular case so I basically created a scenario which is a replica of `bf1_basic_functionality` except that now i specify a matrix server for each of the of the nodes.
My scenario is like [this](https://gist.github.com/agatsoh/8d6a3925ce9ee14cd6a60fd239c67190) and I get and [error](https://gist.github.com/agatsoh/ccd1cdd46796d1b6f039ce7aecf33f9e) in the following tasks:

`2019-09-26 14:24:51.474995 [error    ] Task errored                   [scenario_player.tasks.base] task=<TransferTask: {'from': 3, 'to': 0, 'amount': 1}>`

And starting from here all the parent tasks error.

I am running this test once more to check if the tests are flaky.

**Comment by agatsoh** [comment]
Today I run the scenario once more and i get [this](https://gist.github.com/agatsoh/b586ea7ed81e8c0d3aadc677700b3621) exception.
[scenario-player-run_bf1_diff_matrix_node_2019-09-27T10:24:01.log](https://github.com/raiden-network/raiden/files/3661637/scenario-player-run_bf1_diff_matrix_node_2019-09-27T10.24.01.log)
```
run
    f"Expected number of events ({self.num_events}) did not match the number "
scenario_player.exceptions.legacy.ScenarioAssertionError: Expected number of events (1) did not match the number of events found (0)
```
Though this error might be specifically related to Scenario Player and not to raiden.

[bf1_diff_matrix_nodes_individual_logs.zip](https://github.com/raiden-network/raiden/files/3661644/bf1_diff_matrix_nodes_individual_logs.zip)
