### ISSUE TITLE
Test that PFSCapacityUpdate is triggered after deposit/withdraw

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden#4743]
We have tests that `PFSCapacityUpdate`s and `PFSFeeUpdate`s are triggered when the balance proof changes, but we need to add tests that this also happens after deposits and withdraws.

**Comment by Dominik1999** [comment]
This should also be tested in the scenario player. I think in one of the PFS scenarios. @christianbrb could you check?

**Comment by czepluch** [comment]
Yes, there is indeed a scenario that tests that.

**Comment by Dominik1999** [comment]
@palango so we need to check whether this is tested in the Raiden Client, right?

**Comment by palango** [comment]
As far as I know it's not tested in the client and we should add a test.

**Comment by Dominik1999** [comment]
ok I will write a test
