### ISSUE TITLE
Update `MIN_REI_THRESHOLD`

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden#4745]
We have a task that checks that at least `MIN_REI_THRESHOLD` are in the UDC.

Besides the name being wrong (it checks for RDN, not REI), we need to set the default.

**Comment by Dominik1999** [comment]
thanks for creating this issue!
As far as I can see, it checks for REI, right?

```
    while True:
        rei_balance = user_deposit_proxy.effective_balance(raiden.address, "latest")
        rdn_balance = to_rdn(rei_balance)
        if rei_balance < MIN_REI_THRESHOLD:
```

**Comment by palango** [comment]
Ah right, I missed that `rdn_balance` is just used in the message.
