### ISSUE TITLE
Rename unlock to withdraw 

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/raiden#476]
## Problem Definition

The python code and the smart contract code are not synchronized terminology wise in regard to the `unlock` function.

The python code was updated to use unlock only for the sender and withdraw for the receiver, while kept the original name `unlock`.

## Solution

Rename the smart contract function from `unlock` to `withdraw` and update the proxies.

## Tasklist

- [ ] rename `unlock` to `withdraw` in the following smart contracts:
  - [ ] NettingChannelLibrary
  - [ ] NettingChannelContract
- [ ] Update the proxies
  - [ ] Update the JSON-RPC proxy
  - [ ] Update the tester proxy
  - [ ] Update the mock proxy

**Comment by hrishikeshio** [comment]
#549 is merged. Can we close this?

**Comment by LefterisJP** [comment]
yep.
