### ISSUE TITLE
Make sure that proxies have checks for all `assert()` and `require()` in the Solidity sources

### ISSUE THREAD

**Issue by pirapira** [raiden-network/raiden#4763]
This issue keeps track of making sure that the proxies contain checks for all `assert()`s and `require()`s in the Solidity sources.

* the target version of the Raiden client is `raiden:develop`.
* the target version of the Raiden contract is the version that `raiden:develop` uses

**steps**

* list all `assert()`s and `require()`s in the Solidity sources
* for each one, make sure that
    * the `assert()` or `require()` has corresponding checks in all related proxies, or
    * the `assert()` or `require()` can never be reached from any of the proxies

**Comment by pirapira** [comment]
@karlb does the service codebase have something similar to contract proxies in the client?

**Comment by karlb** [comment]
No, there are less contract interactions and things have been comparatively simple, so that pulling out the contract calls and detecting every possible error case was not necessary, so far.

**Comment by pirapira** [comment]
That's good to know.  Thanks.

**Comment by rakanalh** [comment]
Augusto is currently looking at the proxies & contracts to make sure they we in sync.

**Comment by pirapira** [comment]
The contracts to cover:
* TokenNetworkRegistry
* TokenNetwork
* SecretRegistry
* HumanStandardToken

**Comment by pirapira** [comment]
Suspended till I understand the norm https://github.com/raiden-network/raiden/issues/4828

**Comment by pirapira** [comment]
Also stuck on https://github.com/raiden-network/raiden/issues/4829

**Comment by pirapira** [comment]
Also stuck on https://github.com/raiden-network/raiden/issues/4830

**Comment by pirapira** [comment]
I unassigned myself because I have some bottleneck work in the smart contracts.

**Comment by rakanalh** [comment]
I will close the issue for now and consider this done. If any additional requires / asserts need to be checked in the proxies, we can create specific issues for them as we see them.
