### ISSUE TITLE
Remove deadcode in token_network_registry.py

### ISSUE THREAD

**Issue by pirapira** [raiden-network/raiden#4794]
Since `raiden:develop` no longer supports RedEyes, there should be no use for

> def add_token_without_limits(self, token_address: TokenAddress) -> Address:

in `raiden/network/proxies/token_network_registry.py`.

This function should be removed together with any calls to it.

**Comment by palango** [comment]
Fixed with cb293d67ee9a980582c0d1f0860bff7cc3921715
