### ISSUE TITLE
give us some clear info about the project and how to get in touch with the devs

### ISSUE THREAD

**Issue by furiousOyster** [raiden-network/raiden#48]
Hey guys - have you got a chat channel or some info pages or something we can take a look at ?
We're looking at using and contributing to Raiden for an internal payments network we've been tasked with building - please let me know how to get in touch.

**Comment by ezdac** [comment]
We're currently in the making of a public slack channel. If you're looking for documentation, that's currently not on the top of our priority list. 
Contact me at max@brainbot.com and i can invite you to the slack channel, but it's not yet crowded for now.

**Comment by heikoheiko** [comment]
Hi, take a look at this public channel: https://gitter.im/brainbot-com/raiden
