### ISSUE TITLE
mediated_transfer_messages_out_of_order seems flaky

### ISSUE THREAD

**Issue by pirapira** [raiden-network/raiden#4804]
`test_mediated_transfer_messages_out_of_order[matrix-False-3-channels_per_node0]` failed when I made an unrelated change.

https://circleci.com/gh/raiden-network/raiden/76964#queue-placeholder/containers/23

**Comment by LefterisJP** [comment]
duplicate of: https://github.com/raiden-network/raiden/issues/4694
