### ISSUE TITLE
Scenario PFS9 wrong expected PFS route count

### ISSUE THREAD

**Issue by ulope** [raiden-network/raiden#4817]
## Problem Definition

The first `assert_pfs_history` check in the `PFS9` scenario only expects one route:
https://github.com/raiden-network/raiden/blob/2e7dd81f1f2ab22aeddc3f9eb2e45617f4b04aca/raiden/tests/scenarios/pfs9_partial_withdraw.yaml#L81-L87

AFAICS this can never be true, since there are two paths with capacity available:
- `0 -> 1 -> 2 -> 3`
- `0 -> 4 -> 3`

**Comment by czepluch** [comment]
Good point. We could set the `pathfinding-max-paths` to `1`. That would assure that the first time only the shortest path is returned. And the second time they're both returned, because they've both been used.

**Comment by Dominik1999** [comment]
do you fix that Jacob and open a PR?

**Comment by czepluch** [comment]
Affirm.
