### ISSUE TITLE
Use current block gas limit as transaction gas upper bound

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#482]
## Problem Definition

At the moment in raiden we use the [Morden Gas Limit](https://github.com/raiden-network/raiden/blob/master/raiden/settings.py#L13) as the gas upper bound of all transactions. That is suboptimal as the gas limit can be changed by the miners and in the mainnet is already at the time of writting quite difference. What's worse if for some reason the block gas limit goes below that no transactions will even work.

## Solution

Make sure that all transactions are provided with the actual block gas limit as the upper bound and the result of estimate Gas as the lower bound.

## Tasklist

- [ ] Use the current block's gas limit as the upper bound of a transaction's gas.

**Comment by hrishikeshio** [comment]
Where should this code be added? in settings.py or in raiden.rpc.client.py?

**Comment by LefterisJP** [comment]
It should replace the usage of [morden gas limit](https://github.com/raiden-network/raiden/blob/8b7d968475519c5c6df885bc1e47a21c10b39121/raiden/settings.py#L13) from settings.py in as many places inside `rpc/client.py` as it makes sense.

For example in [here](https://github.com/raiden-network/raiden/blob/8b7d968475519c5c6df885bc1e47a21c10b39121/raiden/network/rpc/client.py#L210).

I suppose you need to have a function in the rpc client that would be querying the current block gas limit and use it instead of `GAS_LIMIT` inside `rpc/client.py`

**Comment by LefterisJP** [comment]
Closed by: https://github.com/raiden-network/raiden/pull/1234
