### ISSUE TITLE
TokenNetworkRegistry's proxy does not raise `BrokenPrecondition` when the token is already registered

### ISSUE THREAD

**Issue by pirapira** [raiden-network/raiden#4828]
TokenNetworkRegistry proxy's [_add_token()](https://github.com/raiden-network/raiden/blob/db54b197f8f225bc3936bc4c6052e1c4a041c28a/raiden/network/proxies/token_network_registry.py#L123) does not check for the precondition that the token is not yet registered (so it never raises `BrokenPrecondition`).

Instead, the gas estimation fails and eventually `RaidenRecoverableError("Call to createERC20TokenNetwork will fail. Token already registered")` is [raised](https://github.com/raiden-network/raiden/blob/db54b197f8f225bc3936bc4c6052e1c4a041c28a/raiden/network/proxies/token_network_registry.py#L187).

I believe when the proxy finds the precondition broken already before sending the transaction, the proxy should raise `BrokenPrecondition`.  Shall the code be fixed, or am I mistaken about when to raise `BrokenPrecondition`?

**Comment by pirapira** [comment]
@rakanalh says

```
in this case, BrokenPrecondition will crash the client (intended) so we should not even reach the proxy if we know that the require will fail

So in python.py, we should also check for this with a call to a proxy getter that can figure if adding more tokens is possible or not.
```

@pirapira says

```
@rakan Doesn’t that cause another race condition? After python.py checks the precondition, python.py calls the proxy. Then the proxy checks the same condition again on a newer block and the client crashes. Is the acceptable?
```

**Comment by pirapira** [comment]
Also stuck on https://github.com/raiden-network/raiden/issues/4829

**Comment by pirapira** [comment]
Also stuck on https://github.com/raiden-network/raiden/issues/4830

**Comment by hackaugusto** [comment]
> @rakan Doesn’t that cause another race condition? After python.py checks the precondition, python.py calls the proxy. Then the proxy checks the same condition again on a newer block and the client crashes. Is the acceptable?

Preconditions must be check against a specific block and it must handle pruned blocks. We must only rely on the gas estimation to be against the latest block.

**Comment by pirapira** [comment]
This was fixed in https://github.com/raiden-network/raiden/pull/4865.
