### ISSUE TITLE
Ensure user has enough ether left in the account to safely interact with the netting channel

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/raiden#483]
## Problem Definition

If a uniformed user creates a netting channel with all it's ether then she will not be able to close/updateTransfer/settle it to recover it's asset.

## Solution

This is a hard problem and would required monitoring of the account's balance, an initial solution should ensure during the netting channel creation that the account's balance is sufficient to complete the close/updateTransfer + settle operations.

## Tasklist

Preliminary list of tasks (split into multiple issues)

- [ ] Add a configuration variable for the minimum number of pending transfer
- [ ] Ensure the account will has enough balance to call close/updateTransfer + the minimum pending transfer unlocks + settle

**Comment by LefterisJP** [comment]
Closing in favour of #1815 and #1861.
