### ISSUE TITLE
Should TokenNetworkRegistry.add_token() take a block identifier? Yes, do it!

### ISSUE THREAD

**Issue by pirapira** [raiden-network/raiden#4830]
Currently, [TokenNetwork.add_token_with_limits()](https://github.com/raiden-network/raiden/blob/db54b197f8f225bc3936bc4c6052e1c4a041c28a/raiden/network/proxies/token_network_registry.py#L96) does not take a block identifier as an argument.  As a result, the proxy and the caller can perform precondition checks on different blocks.  Should this function take a block identifier?

**Comment by pirapira** [comment]
@LefterisJP asked "Aren’t proxy calls made for specific block identifiers?"  So he might have opinions here.

**Comment by hackaugusto** [comment]
All the methods of the proxies must receive a triggering block, the ones that don't should be updated because they don't comply to the current pattern of interacting with the blockchain.

**Comment by LefterisJP** [comment]
> @LefterisJP asked "Aren’t proxy calls made for specific block identifiers?" So he might have opinions here.

It's basically what @hackaugusto mentioned in the above comment https://github.com/raiden-network/raiden/issues/4830#issuecomment-530384231
