### ISSUE TITLE
MS4 scenario is broken

### ISSUE THREAD

**Issue by czepluch** [raiden-network/raiden#4831]
The MS4 scenario is currently broken. There are several syntax errors that results in the scenario not running.

- [x] Fix the syntax
- [ ] Make sure the scenario passes

**Comment by czepluch** [comment]
Syntax has been fixed, but now the scenario fails with:
```
Traceback (most recent call last):                                                                                                                                                          
  File "/home/jacob/dev/venvs/sp_venv/lib/python3.7/site-packages/scenario_player/main.py", line 230, in run                                                                                
    runner.run_scenario()                                                                                                                                                                   
  File "/home/jacob/dev/venvs/sp_venv/lib/python3.7/site-packages/scenario_player/runner.py", line 224, in run_scenario                                                                     
    wait_for_txs(self.client, fund_tx | ud_token_tx | mint_tx)                                                                                                                              
  File "/home/jacob/dev/venvs/sp_venv/lib/python3.7/site-packages/scenario_player/utils/legacy.py", line 214, in wait_for_txs                                                               
    raise ScenarioTxError(f"Transaction {txhash} failed.")                                                                                                                                  
scenario_player.exceptions.legacy.ScenarioTxError: Transaction 0x4f26e8b4d9cbeb06fe339ff85f6f4140a8e63be4d76475975f9bd3e104cb1915 failed. 
```
It happens in the `deposit()` function. Link to goerli etherscan: https://goerli.etherscan.io/tx/0x4f26e8b4d9cbeb06fe339ff85f6f4140a8e63be4d76475975f9bd3e104cb1915

**Comment by czepluch** [comment]
With this version of the scenario file: https://github.com/raiden-network/raiden/pull/4832

**Comment by czepluch** [comment]
Full logs of the run: 
[scenario-player-run_ms4_udc_too_low_2019-09-11T15:38:06.log](https://github.com/raiden-network/raiden/files/3601256/scenario-player-run_ms4_udc_too_low_2019-09-11T15.38.06.log) (might be other tx hash, but same error)

**Comment by rakanalh** [comment]
AFAIK, deposit failed because:
1. You don't have enough balance for the token used by UDC:
    - i checked here and address `0x10c5a0A2fe626D4615e3Bb561bDb34398b36238e` has 0 balance https://goerli.etherscan.io/address/0x18a0a29cd1122cbe89dcd1da14d2f5f487adaa54#readContract
2. Because the balance was zero, no amount was "approved" for the UDC to perform "transferFrom".

**Comment by rakanalh** [comment]
In the logs, i noticed this:

```
{"tx_hash": "0x2aea9de77541f019db2ac1c28de0d256a999915d179f6527466efe0458f73ec5", "event": "'mint' call succeeded", "logger": "scenario_player.utils.token", "level": "info", "timestamp": "2019-09-11 13:40:32.707112"}
{"target_address": "0x10c5a0A2fe626D4615e3Bb561bDb34398b36238e", "required_balance": 5000, "actual_balance": 0, "event": "Checking necessity of deposit request", "logger": "scenario_player.utils.token", "level": "debug", "timestamp": "2019-09-11 13:40:32.797946"}
{"target_address": "0x10c5a0A2fe626D4615e3Bb561bDb34398b36238e", "event": "deposit call required - insufficient funds", "logger": "scenario_player.utils.token", "level": "debug", "timestamp": "2019-09-11 13:40:32.799181"}
```

So the mint succeeded but it seems like the account didn't have the balance required for the deposit.

**Comment by rakanalh** [comment]
@hackaugusto will take over from here.

**Comment by czepluch** [comment]
I think I fixed it. It was a problem in the scenario that meant that the nodes weren't correctly funded with tokens. Running it locally now and didn't get the error. @hackaugusto please don't spend time on this right now.
