### ISSUE TITLE
[discussion] Migrate to marshmallow-dataclass 6.1.0

### ISSUE THREAD

**Issue by lovasoa** [raiden-network/raiden#4833]
Hello,
  I am the author of the [marshmallow-dataclass](https://github.com/lovasoa/marshmallow_dataclass) library that you use. I just published a new pre-release, version 6.1.0rc1, which adds the ability to [define custom types](https://github.com/lovasoa/marshmallow_dataclass#custom-newtype-declarations) while associating a custom marshmallow field to them. I am looking for user feedback before I release the final version and I thought you could help.
  The feature should allow you to remove some boilerplate, and to avoid [using the private `marshmallow_dataclass._native_to_marshmallow` dictionary](https://github.com/raiden-network/raiden/blob/develop/raiden/storage/serialization/types.py#L188).

**Comment by rakanalh** [comment]
Thanks alot @lovasoa... Funny how i came to the issues page to create an issue about this exact thing. 

I am not sure we're going to be able to prioritize this for the next couple of weeks. However, i'll try to squeeze it in as soon as we can.

**Comment by lovasoa** [comment]
The new version of marshmallow-dataclass is now released, and supports the definition of custom types that you may find useful. Feel free to close this issue if you want.

**Comment by karlb** [comment]
We're now on the latest version and remove the hacky usage of `marshmallow_dataclass._native_to_marshmallow` as suggested. Thanks @lovasoa!
