### ISSUE TITLE
Ensure consistent json encoding in the Rest API

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#484]
## Problem Definition

At the moment in the Restful API most functions seem to be doubly encoding the resulting JSON.
To solve that we are forced to do [double decoding](https://github.com/raiden-network/raiden/blob/6b9364171b1663a93ca019d178e72813e038bc62/raiden/tests/utils/apitestcontext.py#L30) during the tests. 

Some of the [newer functions](https://github.com/LefterisJP/raiden/blob/63aa5f35c053c2366ca5061d06b471ae043b531a/raiden/api/rest.py#L183) do not require this and properly return the json as expected.

It's probably related to the way marshmallow/flash does things under the hood.

## Solution

Find a way to make the behaviour of the result of all Restful API calls consistent in the way the JSON is decoded across all API functions. Stop the need for double decoding.

## Tasklist

- [x] Make all Restful API result json encoding consistent

**Comment by czepluch** [comment]
fixed with #624 thanks @hackaugusto
