### ISSUE TITLE
PFS fails with "Expected route [0, 4, 3] not found. Actual routes: [[0, 1, 2, 3]]"

### ISSUE THREAD

**Issue by czepluch** [raiden-network/raiden#4866]
PFS5 fails with "Expected route [0, 4, 3] not found. Actual routes: [[0, 1, 2, 3]]" in the nightly run on 13/09/2019.

Logs: 
[scenario-player-run_pfs5_too_low_capacity_2019-09-13T02:48:03.log](https://github.com/raiden-network/raiden/files/3609138/scenario-player-run_pfs5_too_low_capacity_2019-09-13T02.48.03.log)

**Comment by czepluch** [comment]
Closing since it's duplicate of https://github.com/raiden-network/scenario-player/issues/331

**Comment by czepluch** [comment]
Reopening since it doesn't seem to be the exact same problem. The problem @agatsoh is seeing is a payment that doesn't go through. The problem that the nightly shows is a payment that used an unexpected path.

**Comment by czepluch** [comment]
Passed all the runs during the weekend. Might have experienced a spike in the matrix on Friday, which is why it failed. (pun intended)

**Comment by rakanalh** [comment]
Is assistance investigating this further required? or can we close the issue?

**Comment by czepluch** [comment]
@rakanalh I'd say we can close this for now, and reopen if it happens again.

**Comment by czepluch** [comment]
I am experiencing this locally again now. Reopening. Might be related to https://github.com/raiden-network/raiden/issues/4927

**Comment by christianbrb** [comment]
@ulope What is the severity of this issue?

**Comment by ulope** [comment]
This is a symptom of #4972 as @czepluch suspected.

I guess we can close it as a duplicate.

**Comment by Dominik1999** [comment]
closed as duplicate
