### ISSUE TITLE
Make alarm sleep time configurable

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#4877]
## Problem Definition

At the moment we query the ethereum client two times a second for a new block. That's a lot, considering that the average block time at the moment is 13.3 seconds for the ethereum mainnet.

There is a long standing TODO in the alarm task for this:

https://github.com/raiden-network/raiden/blob/f8f14d62f4a2ae9308b85aa4ae100bea0a3fffec/raiden/tasks.py#L151-L154

Related: https://github.com/raiden-network/raiden/issues/4872

## Task

Make the alarm time configurable depending on the network. For example ethereum mainnet has 13.3 seconds block time, our integration tests have 1 second and so on and so forth.

**Comment by ulope** [comment]
One thing to keep in mind is that the integration tests have a block time of 1s.

**Comment by LefterisJP** [comment]
> One thing to keep in mind is that the integration tests have a block time of 1s.

Good point, we can be patching this value in the tests. Or perhaps even better make it a configurable argument?

This should heavily depend on the blocktime of the blockchain you are on and this can vary!
