### ISSUE TITLE
Document that proxies should not raise specific exceptions `AlreadyRegisteredTokenAddress` etc.

### ISSUE THREAD

**Issue by pirapira** [raiden-network/raiden#4878]
I thought something like below, but there is a reason not to do that according to @rakanalh and @hackaugusto.  This issue keeps track of documenting the reason why proxies are not supposed to raise specific exceptions such as `AlreadyRegisteredTokenAddress`.

------

In Python, programmers can define new exceptions.  So at the cause of the exception, the programmer can raise a specific exception that describes the situation. Currently in Raiden, [sometimes](https://github.com/raiden-network/raiden/blob/2d8674b46b5b2ed98752346d2339e0c214d4f416/raiden/api/python.py#L243) the API function catches a generic `RaidenRecoverableError` and converts that to more specific `AlreadyRegisteredTokenAddress` and so on.

This issue keeps track of stopping that, by
* raising specific exceptions from the proxies, and
* classifying these specific exceptions as `RaidenRecoverableError` (not `RaidenError`).

**Comment by rakanalh** [comment]
Raising specific exceptions from the proxies is **not** something we want to do (that was decided when @hackaugusto and I introduced `BrokenPreconditionError`). The line you're referring to is an oversight that should be fixed by just re-raising the `RaidenRecoverableError`.

**Comment by pirapira** [comment]
@rakanalh I'll document that decision in the proxy guide in the documentation.

Do you have the log for the decision?

**Comment by hackaugusto** [comment]
> Document that proxies should not raise specific exceptions

@pirapira There are currently `229` raise statements in the proxies `grep raise *.py | wc -l`. Each of this exceptions is covering a distinct scenario. Having a single exception for each possibility would simple be too much.

With the above said, even if we did use a separate exception type for each error, `AlreadyRegisteredTokenAddress` would not be the correct exception. Currently the exception `AlreadyRegisteredTokenAddress` is used for input validation, in the modules `raiden.api.rest` and `raiden.api.python` these errors are not unrecoverable, they are just validation issues that must return a human readable message, and not crash the client.

**Comment by pirapira** [comment]
Of course `AlreadyRegisteredTokenAddress` is recoverable.  So I'm doing `class AlreadyRegisteredTokenAddress(RaidenRecoverableError)`.  https://github.com/raiden-network/raiden/pull/4879/files#diff-c48bfeb29bf18bd2ec0add25841f1ce8R155

**Comment by hackaugusto** [comment]
This should be a `ValidationError` https://github.com/raiden-network/raiden/blob/1a690cf8683797567e25fc63cc1391693d17f276/raiden/exceptions.py#L44-L49, I would still keep these hierarchies disjoint, they are not used for the same thing.

**Comment by pirapira** [comment]
The user provided a valid address.  It's not the problem with the value.  It's the problem with the chain that has registered the address already.

**Comment by pirapira** [comment]
Then I'll first update the docstring for `RaidenValidationError`.

**Comment by pirapira** [comment]
https://github.com/raiden-network/raiden/pull/4952 I extended the docstring a bit.

**Comment by pirapira** [comment]
Whether or not proxies raise AlreadyRegisteredTokenAddress, this exception already exists in the codebase because `raiden/api/python.py` raises it.  So I don't see a reason why a proxy should not raise it.

**Comment by pirapira** [comment]
I've updated the documentation and it talks about when proxies can raise specific exceptions.  https://github.com/raiden-network/raiden/blob/bdc6aada475224b041d05e5268ced8d72a3e56f5/docs/proxies.rst#a-guide-for-implementing-proxies

> Instead of RaidenValidationError, you can also raise a special exception that you derive from RaidenError, but make sure you catch it. The typical use case is to provide a nice HTTP status number.
