### ISSUE TITLE
test_mediated_transfer_with_fees is flaky

### ISSUE THREAD

**Issue by pirapira** [raiden-network/raiden#4881]
`test_mediated_transfer_with_fees[matrix-False-4-channels_per_node0-4]` is flaky. For example, https://circleci.com/gh/raiden-network/raiden/78531#tests/containers/5

**Comment by LefterisJP** [comment]
This should change completely once we finish all the related work with making integration tests work properly with fees:

https://github.com/raiden-network/raiden/pull/4869
https://github.com/raiden-network/raiden/pull/4802

**Comment by rakanalh** [comment]
Added this to the milestone so that it is closed when #4802 is merged.

**Comment by LefterisJP** [comment]
After #4802 this should hopefully not be flaky. If it is we can reopen the issue.
