### ISSUE TITLE
TokenNetworkRegistry's add_token() should check if secret_registry_address is zero

### ISSUE THREAD

**Issue by pirapira** [raiden-network/raiden#4882]
If the given secret_registry_address is zero, the transaction will fail, so the proxy should raise BrokenPreconditionError.

This is a part of https://github.com/raiden-network/raiden/issues/4792

**Comment by rakanalh** [comment]
According to the contracts:

https://github.com/raiden-network/raiden-contracts/blob/94f1428d2fad4719efffb26be3d7731d7bb3f3da/raiden_contracts/data/source/raiden/TokenNetworkRegistry.sol#L70-L105

There is no require/assert for the secret registry address **when** `createERC20TokenNetwork` is called.

The assert exists in the constructor of the contract which means that if that fails there would be no usable instance of the contracts.

**Comment by pirapira** [comment]
@rakanalh `createERC20TokenNetwork()` calls the constructor of `TokenNetwork`.  The constructor of `TokenNetwork` contains a `require(secret_registry_address != 0);`.

**Comment by pirapira** [comment]
I assigned myself because @rakanalh has not understood why the change has to be made.

**Comment by rakanalh** [comment]
@pirapira my PR will handle this one as well.

**Comment by pirapira** [comment]
Yes, and @rakanalh also knows the motivation of the change.

yoichi 11:32> I want to tell you something about createERC20TokenNetwork().

When it executes new TokenNetwork(), the constructor of TokenNetwork is executed.

And that contains a bunch of require()s https://github.com/raiden-network/raiden-contracts/blob/94f1428d2fad4719efffb26be3d7731d7bb3f3da/raiden_contracts/data/source/raiden/TokenNetwork.sol#L228

When any of these require’s fail, createERC20TokenNetwork() fails.


rakan 11:34> I know
yoichi 11:34> Oh.
