### ISSUE TITLE
TokenNetworkRegistry should check the deprecation executor address before/after sending a tx

### ISSUE THREAD

**Issue by pirapira** [raiden-network/raiden#4884]
This issue keeps track of making sure that the TokenNetworkRegistry's proxy checks the deprecation executor address before sending `createERC20TokenNetwork()` transaction.  Also check the same condition after gas estimation or the tx in a block fails.

These checks are necessary because the function fails when the deprecation executor address is zero.

**Comment by pirapira** [comment]
This is a part of https://github.com/raiden-network/raiden/issues/4792.

**Comment by rakanalh** [comment]
https://github.com/raiden-network/raiden-contracts/blob/94f1428d2fad4719efffb26be3d7731d7bb3f3da/raiden_contracts/data/source/raiden/TokenNetworkRegistry.sol#L70-L105

The contract seems to set the `deprecation_executor` to `msg.sender` but the value isn't used in a modifier to disable adding new token networks. Should this be done in the contracts first?

**Comment by pirapira** [comment]
> The contract seems to set the deprecation_executor to msg.sender but the value isn't used in a modifier to disable adding new token networks. Should this be done in the contracts first?

I think that's a good idea.

**Comment by pirapira** [comment]
Here is the issue to authenticate the deprecation executor in `createERC20TokenNetwork()` https://github.com/raiden-network/raiden-contracts/issues/1232
