### ISSUE TITLE
TokenNetworkRegistry should check chain_id before calling createERC20TokenNetwork()

### ISSUE THREAD

**Issue by pirapira** [raiden-network/raiden#4886]
TokenNetworkRegistry class's `add_token()` calls `createERC20TokenNetwork()` function of the TokenNetworkRegistry smart contract.  This call fails when `chain_id` stored in the smart contract is zero.

This issue keeps track of adding
* a precondition check against zero chain_id
* a post-failure check against zero chain_id

**Comment by pirapira** [comment]
This is a part of #4792.

**Comment by rakanalh** [comment]
Replied in other issues, but any constructor-(require|assert) in the contract doesn't need to be checked in the proxy methods.
