### ISSUE TITLE
TokenNetworkRegistry proxy should check settlement_timeout_min is not zero

### ISSUE THREAD

**Issue by pirapira** [raiden-network/raiden#4888]
Smart contract proxies should try to avoid sending transactions that are going to fail.  Currently, TokenNetworkRegistry's proxy sends `createERC20TokenNetwork()` transactions without checking the value of `settlement_timeout_min`.  If `settlement_timeout_min` is zero, the transaction fails because `TokenNetwork`'s constructor fails.

Also, when a transaction fails in a block or when gas estimation fails, a similar check helps to diagnose the problem.

This issue keeps track of adding these checks in TokenNetworkRegistry's proxy.

**Comment by pirapira** [comment]
This is a part of https://github.com/raiden-network/raiden/issues/4792

**Comment by rakanalh** [comment]
As i wrote in one of the issues you created, `settlement_timeout_min` and `settlement_timeout_max` are checked in the contract's constructor. No "precondition" check should take place in the proxy methods for require/asserts that are executed in the contract's constructor.
