### ISSUE TITLE
TokenNetworkRegistry proxy should check settlement_timeout_max is bigger than settlement_timeout_min

### ISSUE THREAD

**Issue by pirapira** [raiden-network/raiden#4889]
Smart contract proxies should try to avoid sending transactions that are going to fail.  Currently TokenNetworkRegistry does not check the values of `settlement_timeout_min` and `settlement_timeout_max` before sending `createERC20TokenNetwork()` transactions.  However, `createERC20TokenNetwork()` fails when `settlement_timeout_min` is not smaller than `settlement_timeout_max`.  This is because the TokenNetwork's constructor requires that the max is bigger than the min.

This issue keeps track of
* adding a precondition check that `settlement_timeout_min` is smaller than `settlement_timeout_max`
* and adding a similar post-failure check after a transaction fails in a block or gas estimation fail.

This is a part of #4792.

**Comment by rakanalh** [comment]
As i wrote in one of the issues you created, `settlement_timeout_min` and `settlement_timeout_max` are checked in the contract's constructor. No "precondition" check should take place in the proxy methods for require/asserts that are executed in the contract's constructor.

**Comment by pirapira** [comment]
> No "precondition" check should take place in the proxy methods for require/asserts that are executed in the contract's constructor.

I didn't know that.  Since I don't trust the Solidity compiler, I believe any state variable can change its values at any moment of time.
