### ISSUE TITLE
Add a type for the transaction receipt

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/raiden#4900]
## Abstract

The [type `Dict[str, Any]`](https://github.com/raiden-network/raiden/blob/1188c6c11fc9932bd7b4cdc9b7710046e416f16b/raiden/network/rpc/client.py#L642) is too broad and very easy to leave subtle bugs behind. 

## Motivation

Type safety.

## Specification

None

## Backwards Compatibility

No problems with compatibility

**Comment by palango** [comment]
This is now typed in web3: https://github.com/ethereum/web3.py/blob/5d7abc26a594be153118557cc572afe60913d842/web3/eth.py#L335

Ref https://github.com/raiden-network/raiden/issues/5467

**Comment by palango** [comment]
`poll_transcation` now returns a `TXReceipt`:
https://github.com/raiden-network/raiden/blob/3e9514262ca2bae9bdff5de63446d49bd249fea2/raiden/network/rpc/client.py#L827
