### ISSUE TITLE
Detect nonce gaps while using Parity

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/raiden#4921]
## Abstract

Issue https://github.com/raiden-network/raiden/issues/4749#issuecomment-528507120 hit a bug in the Parity client that culled a transaction from the pool, and because our JSONRPCClient implementation uses [`parity_nextNonce`](https://github.com/raiden-network/raiden/blob/a35698a550f738336bebcefa02f1a2a63504e5e2/raiden/network/rpc/client.py#L128-L131) the gap was never filled. This ended stagnating the node.

## Motivation

This is a time consuming issue to debug, and it leads to terrible usability, because it seems that Raiden is not doing anything. Fixing this is will result in better usability.

## Specification

Write a test that:

- sends a transaction `_available_nonce + 1`, leaving a gap of one transaction. This is used to simulate a transaction being culled
- assert the transaction is not removed from the pool (should be the case for local transactions)
- creates a new JSONRPCClient to get a fresh nonce
- sends a new transaction
- assert that both transactions are mined

And make the test pass.

The above is a very tricky problem, I would keep the following assumptions:

- Raiden controls the account. I.e. there is no other app sending transactions that could change the nonce unnoticed.
- There is only one Raiden instance running. (Having two instances would effectively break the previous point).
- Transactions can be culled for unknown reasons.

IOW, handling concurrent transactions for the same account from multiple apps is out of the scope of this issue, since this cannot be done without an external service.

## Backwards Compatibility

This is completely backwards compatible.

**Comment by karlb** [comment]
Closing because parity/openethereum is deprecated.
