### ISSUE TITLE
Update "Raiden Red Eyes Mainnet Tutorial" to Alderaan

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden#4922]
Currently the docs include the "Raiden Red Eyes Mainnet Tutorial". This needs to be updated to Alderaan.

**Comment by Dominik1999** [comment]
This is already finalized but we are waiting for the release to push, right?

**Comment by Dominik1999** [comment]
@jomuel

**Comment by jomuel** [comment]
Closing this in favor of the broader issue #5431
