### ISSUE TITLE
Fix race condition on `jsonrpc_client._available_nonce`

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/raiden#4923]
## Abstract

`JSONRPCClient._available_nonce` is private because it requires synchronization across multiple threads. The following code:

https://github.com/raiden-network/raiden/blob/a35698a550f738336bebcefa02f1a2a63504e5e2/raiden/network/rpc/smartcontract_proxy.py#L112-L115

Is reading the value outside of the synchronization barrier. This means the error can be for a transaction `2` while the value of `_available_nonce` is for another transaction with a value higher than `2`.

## Motivation

The above is a bug and can result in unexpected crashes.

**Comment by hackaugusto** [comment]
I created the issue because I realized that a private member was being used, however on a second though I believe the logic is broken even if the barrier is expanded. This is possible:

- Thread A sends a transaction with nonce=1
- Thread B sends a transaction with nonce=1 (this in itself would be a type of bug, however when nodes are restarting this is possible).
- The transaction from A is in the pool, this causes the transaction from B to raise an error.
- This happens concurrently:
  - While handling the error, B would query the state of the transaction based on the transaction hash (assuming the bug above is fixed, this would use the `nonce=1`).
  - Transaction from A is mined
- The result for B is `None`, because the transaction is not in the pending pool anymore.

In general, it is not possible to have two remote queries, one after the other, and expect the result to be consistent.

**Comment by rakanalh** [comment]
Wouldn't B in this case replace A because it has the same nonce? My understanding is that either of them will be mined but not both according to which one has a higher gas price right?

**Comment by hackaugusto** [comment]
> Wouldn't B in this case replace A because it has the same nonce? My understanding is that either of them will be mined but not both according to which one has a higher gas price right?

It really depends. It depends on the gas estimation, the gas price, and the transaction data. Above it was just an example if the same transaction happened to be sent twice.

If the transaction changes, but the gas price doesn't increase more than 15% then the error changes, it would become an under priced error:

https://github.com/raiden-network/raiden/blob/a35698a550f738336bebcefa02f1a2a63504e5e2/raiden/network/rpc/smartcontract_proxy.py#L92-L99

If the gas price increases by more than 15% then we would have a replacement transaction, and then the error would be in the polling code (there is no guarantee that the replacement will work, either of the transactions may be mined).
