### ISSUE TITLE
Configurable debug log size

### ISSUE THREAD

**Issue by kilrau** [raiden-network/raiden#4930]
## Abstract

Raiden logs quite some things and the current 4x2MB limit can be exhausted in a matter of days. 

## Motivation

We temporarily [hardcoded the log limit to 1GB in our raiden branch](https://github.com/ExchangeUnion/raiden/commit/e888346aecba0f48ddb55708cb6bbee562884f1a) to be able to debug things properly that happened further in the past. 

## Specification

Goal of this issue is to pass a config value to raiden for the user to dynamically determine the max total log size. Also, we recommend a new default in the range 128-512MB.

## Backwards Compatibility

N/A

**Comment by LefterisJP** [comment]
Perhaps our email conversation would be of use here.

> You got two options
>
>1. Quick and dirty. Edit the code here: 
>
>https://github.com/raiden-network/raiden/blob/90ac744b52be8770191581ce005612c454f06952/raiden/log_config.py#L212-L220
>
>And increase the size of each log and number of rotated files to keep to whatever you want. (we could also make them configurable via CLI).
>
>2. The above is the debug log kept by default. You can also disable it, and then use our cli args to configure the normal log (which is only INFO and only prints on stdout by default) to do whatever you want it to do. (Human readable or json, adjust size, adjust log level e.t.c.).


So as you can also see from the email contents this is only for the debug log. Your normal logs are still there and they are also already completely configurable via the python log-config. Perhaps we should have this documented better.

**Comment by LefterisJP** [comment]
So I think the best way to handle this is to disable the debug logfile and instead use the normal logs. Wrote something in the docs about how to configure them: https://github.com/raiden-network/raiden/pull/4939/files#diff-441370086b253c05e40d9e14b4669077R255

Is that satisfactory @kilrau ?

Normal logs have no size limits. Users are supposed to use external tools for log rotation.
