### ISSUE TITLE
Use constants for channel state values

### ISSUE THREAD

**Issue by konradkonrad** [raiden-network/raiden#494]
## Problem Definition

Right now, but even more so after #413, we're using strings to check for certain channel states in many places. Instead of relying on local string values in all those places it sounds more sensible to introduce class attributes for the `Channel` class. This will prevent bugs introduced by mismatches between `close` and `closed`, as well as typos (`seltted` vs `settled`).

## TODO
- [ ] introduce class attributes in `channel.py::Channel` for `STATE_OPENED`, `STATE_CLOSED`, `STATE_SETTLED`
- [ ] replace all literal uses of channel state strings (`'open'`, `'opened'`, `'closed'`, `'settled'`) with the class attributes.

**Comment by hrishikeshio** [comment]
Can we close this as #496 is merged?

**Comment by LefterisJP** [comment]
The contants were added in `state.py` as global constants instead, but the end result is the same. Yes this can be closed.
