### ISSUE TITLE
Smart contract proxies can crash nodes when multiple transactions in the same block touches the same channel

### ISSUE THREAD

**Issue by pirapira** [raiden-network/raiden#4944]
When a transaction fails in a block, proxies try to figure out the reason of the failure by executing the transaction again in the block.  However, these retries happen at the beginning of the block.  If the failure is caused by some preceding transaction in the same block, the diagnose is not possible.  In these cases most proxies raise `RaidenUnrecoverableError` and crash the node.

This issue keeps track of removing this kind of crashes.

One way to do it is to check stop raising `RaidenUnrecoverableError` when multiple transactions in the same block touch the same channel etc.

**Comment by rakanalh** [comment]
> When a transaction fails in a block, proxies try to figure out the reason of the failure by executing the transaction again in the block. 

Can you point to where these "retries" happen? 

And please be specific about the case/transactions you're referring to, otherwise the issue is too generic.

**Comment by pirapira** [comment]
Sorry.  I made a factual mistake.  I'm closing this issue and creating a new one.

**Comment by pirapira** [comment]
Here is the issue that replaces this one: https://github.com/raiden-network/raiden/issues/4953
