### ISSUE TITLE
Update every scenario to check final channel state

### ISSUE THREAD

**Issue by Dominik1999** [raiden-network/raiden#4962]
## Abstract

Many of our scenarios seem not to check the final channel state after the transfers. We should assert that. 

## Motivation

Since last week, our scenarios were green despite the fact that they already ran with mediation fees. The transferred amounts were too small for the fees to be deducted (rounded to 0) but we would not have noticed anyway, because we don't assert the final channel state.

**Comment by czepluch** [comment]
But we would have noticed, right? Since the assertions after payments would have different values. I will go through the scenarios anyway to see if there are some places we can add some additional meaningful checks, but I think we have the necessary checks in place in most cases.

**Comment by Dominik1999** [comment]
Thank you!
As far as I can see, in most scenarios, we have no assertion about channel balances after payments. At least in pfs1, pfs2, pfs3, pfs4, pfs5, pfs6, pfs8 and pfs9 we never check the final channel state / balance so we wouldn't see any deducted fees

**Comment by czepluch** [comment]
Fixed with https://github.com/raiden-network/raiden/pull/4987
