### ISSUE TITLE
Price Info from PFS not shown correctly or handled correctly

### ISSUE THREAD

**Issue by Dominik1999** [raiden-network/raiden#4970]
## Issue checklist

To help us more easily debug your issue please check the boxes for which requirements for safe usage or Raiden were followed: 

- [ ] The Ethereum node was always up to date with the chain tip and never stopped running.
- [ ] No Ethereum transaction was sent for the account that Raiden manages by another app.
- [ ] The Ethereum account used by Raiden always had sufficient ETH.
- [ ] The Raiden DB that exists by default at ~/.raiden was never altered or deleted.
- [ ] The Raiden node was never restarted. If yes please provide more info.
- [ ] The ethereum node was not switched while Raiden was running.
- [ ] The Raiden REST API is protected from public access.

-->

## Problem Definition

The remote PFS on Görli 
https://pfs-goerli-with-fee.services-dev.raiden.network/api/v1/info wants 100 tokens per request as shown in the endpoint 
```
{"price_info": 100, "network_info": {"chain_id": 5, "registry_address": "0x603882F4e7fAb5942a585048CADc71F91D6160c5"}, "version": "0.3.0", "operator": "John Doe", "message": "This is your favorite pfs for token network registry 0x603882F4e7fAb5942a585048CADc71F91D6160c5", "payment_address": "0x062C12c01D0f17fC9eAa33940D994594d91a0182"}
```

But when starting Raiden it shows a different price `Each request costs 1e-16 RDN`

```
You have chosen the pathfinding service at https://pfs-goerli-with-fee.services-dev.raiden.network.
Operator: John Doe, running version: 0.3.0, chain_id: 5.
Fees will be paid to 0x062C12c01D0f17fC9eAa33940D994594d91a0182. Each request costs 1e-16 RDN.
Message from the PFS:
This is your favorite pfs for token network registry 0x603882F4e7fAb5942a585048CADc71F91D6160c5

You are connected to the 'goerli' network and the DB path is: /home/pirate/.raiden/scenario-player/scenarios/PFS7-test/node_3_000/node_f6312ccc/netid_5/network_603882f4/v23_log.db
The Raiden API RPC server is now running at http://127.0.0.1:59191/.

See the Raiden documentation for all available endpoints at
http://raiden-network.readthedocs.io/en/stable/rest_api.html
You're running version 0.100.5.dev726+g8d86aed45. The latest version is 0.100.5a0
``` 

Somehow this line 
https://github.com/raiden-network/raiden/blob/8d86aed454e0e84ce4f016960a5c6d8478dfbe35/raiden/network/pathfinding.py#L303

confuses the default max fee of the Raiden Client, which is set here https://github.com/raiden-network/raiden/blob/8d86aed454e0e84ce4f016960a5c6d8478dfbe35/raiden/settings.py#L53
### System Description

Here add a detailed description of your system, e.g. output of the following script:

```
uname -a
command -v solc && solc --version
command -v geth && geth version
command -v parity && parity --version
command -v raiden && raiden version
[ -d .git ] && git rev-parse HEAD
```

**Comment by karlb** [comment]
The numbers are 100 RAI and 1e-16 RDN. 1e18 RAI = 1 RDN, so 100 RAI = 1e-16 RDN.

To me the numbers are right. Do you agree? Do we need a different presentation?

**Comment by LefterisJP** [comment]
Perhaps the scientific representation is confusing?

**Comment by karlb** [comment]
Yes, no everyone is used to it. But if you are, 1e-16 is a lot easier to read correctly than 0.00000000000000001. We could print it in RAI and hope the the fees are small enough that it stays readable. But then we would expect that people can convert from RAI to RDN.

**Comment by Dominik1999** [comment]
ah ok that was a stupid mistake. Nevermind. Leave it like this :)
