### ISSUE TITLE
bf1_basic_functionality fail

### ISSUE THREAD

**Issue by agatsoh** [raiden-network/raiden#5007]
Description
=========

```
{"task": "<SerialTask: {'name': 'Close channel between 3 and 4 while 4 is offline', 'tasks': [{'stop_node': 4}, {'close_channel': {'from': 3, 'to': 4}}, {'wait_blocks': 1}, {'assert': {'from': 3, 'to': 4, 'state': 'closed'}}, {'assert_events': {'contract_name': 'TokenNetwork', 'event_name': 'ChannelClosed', 'num_events': 1, 'event_args': {'closing_participant': 3}}}, {'wait_blocks': 500}, {'assert_events': {'contract_name': 'TokenNetwork', 'event_name': 'NonClosingBalanceProofUpdated', 'num_events': 1, 'event_args': {'closing_participant': 3}}}, {'wait_blocks': 10}, {'assert_ms_claim': {'channel_info_key': 'MS Test Channel 3-4'}}]}>", "event": "Task errored", "logger": "scenario_player.tasks.base", "level": "error", "timestamp": "2019-10-01 06:23:54.312331", "exception": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.7/site-packages/scenario_player/tasks/base.py\", line 74, in __call__\n    return self._run(*args, **kwargs)\n  File \"/usr/local/lib/python3.7/site-packages/scenario_player/tasks/execution.py\", line 41, in _run\n    task()\n  File \"/usr/local/lib/python3.7/site-packages/scenario_player/tasks/base.py\", line 74, in __call__\n    return self._run(*args, **kwargs)\n  File \"/usr/local/lib/python3.7/site-packages/scenario_player/tasks/blockchain.py\", line 178, in _run\n    f\"Expected number of events ({self.num_events}) did not match the number \"\nscenario_player.exceptions.legacy.ScenarioAssertionError: Expected number of events (1) did not match the number of events found (0)"} 
```

[Scenario_player_Logs-bf1_basic_functionality-1-latest-2019-10-01.tar.gz](https://github.com/raiden-network/scenario-player/files/3675208/Scenario_player_Logs-bf1_basic_functionality-1-latest-2019-10-01.tar.gz)

Edit:
Individual node logs for yesterdays run can be downloaded from here
http://68.183.70.168/bf1-nodes.tar.gz 
if above link does not work then download from here 
https://drive.google.com/file/d/1FftxMys7xNd8G_LQ8L_fIJc06AzdJR0p/view?usp=sharing
Preliminary examination of the individual logs in file `run-xxx.log` shows a MatrixError

`{"current_user": "@0x4d07b7083b98c78a841630f026bb772389140219:transport01.raiden.network", "node": "0x4d07B7083B98c78A841630F026bB772389140219", "transport_uuid": "43ed8585-be6a-40cf-bd19-1ac2e6baa671", "room_name": "#raiden_goerli_0x17e26d3a2597672a8dc8e263a9edbf240a6e3681_0x4d07b7083b98c78a841630f026bb772389140219:transport01.raiden.network", "error": ` **`"MatrixRequestError`** `('404: {\"errcode\":\"M_NOT_FOUND\",\"error\":\"Room alias #raiden_goerli_0x17e26d3a2597672a8dc8e263a9edbf240a6e3681_0x4d07b7083b98c78a841630f026bb772389140219:transport01.raiden.network not found\"}')", "event": "No room for peer, trying to create", "logger": "raiden.network.transport.matrix.transport", "level": "debug", "greenlet_name": "RetryQueue node:0x4d07B7083B98c78A841630F026bB772389140219 recipient:0x17E26D3A2597672a8DC8E263a9EdBF240a6E3681", "timestamp": "2019-10-01 03:51:02.510109"}`

Expected Behavior
===============
The raiden node should be correctly able to collect all the Events

**Comment by Dominik1999** [comment]
@agatsoh can you also here please provide the logs with the logs of nodes? also here the folders are empty and we need that for debugging. Can you please make sure that we have everything together in the morning when there is a scenario fail? 

Thank you for taking care of that

**Comment by Dominik1999** [comment]
and the first error in the issue you created seems not to be an error

``` 
{"task": "<TransferTask: {'from': 3, 'to': 0, 'amount': 1000000000000000, 'expected_http_status': 409}>", "event": "Starting task", "logger": "scenario_player.tasks.base", "level": "info", "timestamp": "2019-10-01 03:44:15.040445"}
{"url": "http://127.0.0.1:46097/api/v1/payments/0x62083c80353Df771426D209eF578619EE68D5C7A/0x271821e70f5eC1085ca2b7f1e0E59c8Bb93930b7", "method": "post", "json": {"amount": 1000000000000000}, "event": "Requesting", "logger": "scenario_player.tasks.api_base", "level": "debug", "timestamp": "2019-10-01 03:44:15.042156"}
{"json": {"errors": "Payment couldn't be completed because: there is no route available"}, "event": "Received response", "logger": "scenario_player.tasks.api_base", "level": "debug", "timestamp": "2019-10-01 03:44:15.803267"}
``` 

We expect that there is no route available, right? you can see that in the `task:` we expect a `409`

**Comment by agatsoh** [comment]
I will try to update the node logs here.

**Comment by Dominik1999** [comment]
@agatsoh can you change the title of the scenario and the initial post to delete the first error (which is intended behavior)?

**Comment by agatsoh** [comment]
@Dominik1999 I updated my original comment for the Issue with what I found as well as a link to download the logs.

**Comment by Dominik1999** [comment]
@rakan you fixed that, right?

**Comment by rakanalh** [comment]
yup
