### ISSUE TITLE
Decouple the Decoder logic from the NettingChannelLibrary

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/raiden#501]
## Problem Definition

The NettingChannelLibrary has the decoding logic built in, this means any change to the protocol format will required the channel to be closed and reopened with the new code in-place

## Tasklist

- [ ] Move the decoding logic to a separate smart contract
- [ ] Fix the routines used for testing, now the decoder need to be deployed prior to the NettingChannelLibrary

## Related

Protocol upgradability #491
Generalize the current implementation to support multiple applications #43

**Comment by hrishikeshio** [comment]
Who can change the decoder address, and hence upgrade the protocol? Can a malicious channel partner create and assign a decoder which gives her an unfair advantage? (e.g. change recipient, amount, type of transfer, etc. )

**Comment by hackaugusto** [comment]
Upgrade of the protocol is not defined yet, vide issue #491 . Definitely we don't want to allow a unilateral decision, the simplest solution is to require both participants to sign the new library address.

**Comment by hackaugusto** [comment]
#830 Removed the decoding logic from the smart contract, now the transport layer can be changed independently of the smart contract.
