### ISSUE TITLE
PFS4 use best path fail, Value mismatch error 

### ISSUE THREAD

**Issue by agatsoh** [raiden-network/raiden#5012]
## Problem Definition

Scenario Player fails with the `Value Mismatch` error 
`Value mismatch for \"balance\". Should: \"999000000000000000\" Is: \"1000000000000000000\" `
```
{"task": "<AssertTask: {'from': 4, 'to': 3, 'total_deposit': 1000000000000000000, 'balance': 999000000000000000}>", "event": "Task errored", "logger": "scenario_player.tasks.base", "level": "error", "timestamp": "2019-10-02 03:37:04.966523", "exception": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.7/site-packages/scenario_player/tasks/base.py\", line 74, in __call__\n    return self._run(*args, **kwargs)\n  File \"/usr/local/lib/python3.7/site-packages/scenario_player/tasks/api_base.py\", line 70, in _run\n    return self._process_response(response_dict)\n  File \"/usr/local/lib/python3.7/site-packages/scenario_player/tasks/channels.py\", line 155, in _process_response\n    f'Value mismatch for \"{field}\". '\nscenario_player.exceptions.legacy.ScenarioAssertionError: Value mismatch for \"balance\". Should: \"999000000000000000\" Is: \"1000000000000000000\" Channel: {'token_address': '0x62083c80353Df771426D209eF578619EE68D5C7A', 'total_deposit': 1000000000000000000, 'balance': 1000000000000000000, 'total_withdraw': 0, 'channel_identifier': 682, 'settle_timeout': 500, 'token_network_address': '0x9526EC0E58ac5Bb1e24d655E964f0eAA46054d16', 'state': 'opened', 'reveal_timeout': 50, 'partner_address': '0x4F05b7e20A284B8eF2C0e47CC04bDD5f5e29638A'}"}
```

[Scenario_player_Logs-pfs4_use_best_path-1-latest-2019-10-02.tar.gz](https://github.com/raiden-network/raiden/files/3680103/Scenario_player_Logs-pfs4_use_best_path-1-latest-2019-10-02.tar.gz)

**Comment by czepluch** [comment]
That makes very little sense. So the payment in the scenario should be successful since we assert that it returns status code `200` [here](https://github.com/raiden-network/raiden/blob/develop/raiden/tests/scenarios/pfs4_use_best_path.yaml#L57), but still the first assert after that is successful from 0 to 4, but 4 to 3 does not assert correctly [here](https://github.com/raiden-network/raiden/blob/develop/raiden/tests/scenarios/pfs4_use_best_path.yaml#L61).

**Comment by LefterisJP** [comment]
PFS4 passes for me with latest develop locally after merging https://github.com/raiden-network/raiden/pull/5018

**Comment by czepluch** [comment]
I don't see how that PR is relevant for the PFS scenarios though.

**Comment by LefterisJP** [comment]
Hmm you are right. It changes nothing PFS related. So maybe this is a false equivalency on our side. Perhaps the best thing to say is I can't reproduce this anymore.

**Comment by agatsoh** [comment]
Duplicate of #5019
