### ISSUE TITLE
Write thorough tests for the resolver functionality

### ISSUE THREAD

**Issue by rakanalh** [raiden-network/raiden#5022]
## Acceptance Criteria:
- [ ] Write tests for the resolver to cover 3 cases:
  - Should return `False` if `resolver_endpoint` is not specified
  - Should return `False` when the lock expires
  - Should return `False` when secret is not found in the resolver.
  - Should dispatch `SecretReveal` when the request succeeds.

**Comment by palango** [comment]
Tracked in https://github.com/raiden-network/raiden/issues/3949
