### ISSUE TITLE
PFS Path Suggestion Service & Raiden Client Protocol

### ISSUE THREAD

**Issue by loredanacirstea** [raiden-network/raiden#5041]
# Scope

Adoption.
Easy way for users to have a good connection within the Raiden network, with minimum amount of funds locked.

# Issue

`many-to-one` & `one-to-many` payments will incentivize service providers to use Raiden. Currently, there is no optimal way to build a network efficiently, in order to connect users with services. And there is no communication channel where users can at least ask for other users to open channels / make deposits in order to have good bidirectional connections.
Especially for `one-to-many` payments, nodes are forced to become Hub-like and lock funds in their open channels.

# Proposal (WIP)

## PFS Path Suggestion Service

If a user needs connections with several services or other users, the PFS should provide a service to find the most efficient way to connect him, at a given point in time.

1. Given an Ethereum address `A2` of a Raiden node and an amount of tokens `T`, it should suggest a list of actions that need to be taken by users (`A1` + other nodes) in order to have path `A1->A2` or `A1<-A2` or `A1<->A2`:
- list of users with whom `A1` needs to open a channel +/- deposit
- list of users who need to deposit tokens into the above channels & the minimum amount of tokens that would be needed at that point in time 
2. Point 1. can be extended to `A1` asking for connections with multiple Raiden nodes at the same time, decreasing the amount of locked funds.

PFS should have enough data to suggest these paths. If it has a somewhat global view of the network (as planned in the first phase), then classical machine learning techniques are enough. Otherwise, we will have to go into more advanced routing & AI.

## Raiden Client

(short description, needs more tech details)

The PFS Path Suggestion Service will not work without users being able to communicate between them.
This can be solved in two ways (both or either of them):

### Raiden Notifications API & UI

- allow 3rd party services (PFS, maybe useful for MS also) to send notifications to the user
- a dedicated Raiden client endpoint can be used for this
- notifications should be shown in the WebUI:
  - in this case, they will be the steps that the user needs to take:
      - open channel with `0x...`
      - make a deposit of `X tokens` in your channel with `0x...`
      - make a deposit of `X tokens` in your channel with `0x...`, because the channel may be used for frequent transfers and you get mediation fees
  - ideally, you could have an action button that does all the suggestions for the user automatically, if the user clicks on it

### Raiden Messages

I am proposing to add additional messages in the Raiden client:
- sending a `ChannelDepositRequest` from Raiden node `A1` to another Raiden node `Ax`
- sending a `ChannelDepositAnswer` from `Ax`, with the fee that `Ax` expects in return for locking up funds
- sending a conditional payment from `A1` to `Ax` that will be unlocked after `Ax` makes his deposit
- things become more complicated if `A1` needs to both open & deposit, based on `Ax`'s answer, because he may end up with a useless channel & locked up funds (needs more thinking)

**Comment by karlb** [comment]
Solved by PFS partner suggestion endpoint.
