### ISSUE TITLE
Docker hub tags outdated raiden version as latest

### ISSUE THREAD

**Issue by nephix** [raiden-network/raiden#5049]
## Problem Definition

When pulling the docker image `raidennetwork/raiden:nightly`, `raidennetwork/raiden:latest` or `raidennetwork/raiden:v0.200.0-rc1` I would expect to get the latest RC.

## Actual result
Docker pulled the version `0.100.5a1.dev504+g68448ac97`:
```
$ docker run -it raidennetwork/raiden:v0.200.0-rc1
Unable to find image 'raidennetwork/raiden:v0.200.0-rc1' locally
v0.200.0-rc1: Pulling from raidennetwork/raiden
Digest: sha256:373170d05c6cb528e1502848b61c65b421e67564c71c7785d46da0f9662d8ec5
Status: Downloaded newer image for raidennetwork/raiden:v0.200.0-rc1
Welcome to Raiden, version 0.100.5a1.dev504+g68448ac97!
...
```

### System Description

```
$ docker -v
Docker version 19.03.2, build 6a30dfc
```

**Comment by konradkonrad** [comment]
It seems, that the container was build from the `develop` branch, since on the master branch `python setup.py --develop` [returns the correct RAIDENVERSION](https://github.com/raiden-network/raiden/blob/cdffdde4a66f7eacec97ee77d3f39954f0b857ed/.circleci/config.yml#L103).

**Comment by rakanalh** [comment]
@konradkonrad where do we build/push the docker container?

**Comment by konradkonrad** [comment]
circleCI has a [`docker` stage](https://github.com/raiden-network/raiden/blob/cdffdde4a66f7eacec97ee77d3f39954f0b857ed/.circleci/config.yml#L648-L656) for nightly builds. still trying to figure out, where the release builds are generated

**Comment by konradkonrad** [comment]
the version tagged releases are auto-build from dockerhub. I disabled the "build caching" for the release builds and try to retrigger a build

**Comment by konradkonrad** [comment]
I found the culprit in the build logs from dockerhub for `Build in 'v0.200.0-rc1:/docker/Dockerfile' `:
```
Step 3/13 : ARG RAIDENVERSION=develop
---> Running in 1afe700a0631
```

**Comment by konradkonrad** [comment]
this "fails", because on dockerhub, there is no build argument provided, and instead the [default is used](https://github.com/raiden-network/raiden/blob/develop/docker/Dockerfile#L13-L15):

```
# use --build-arg RAIDENVERSION=v0.0.3 to build a specific (tagged) version
ARG REPO=raiden-network/raiden
ARG RAIDENVERSION=develop
```

**Comment by konradkonrad** [comment]
We will need to optionally set `Build Environment Variables` (on dockerhub build settings) for tagged releases, so that `RAIDENVERSION=${SOURCE_BRANCH}` (see https://docs.docker.com/docker-hub/builds/advanced/), when building a tagged commit.

I am not sure if this is going to work (or break other things), but I will try.

**Comment by konradkonrad** [comment]
okay, it seems that we need to add a build hook in order to pass `SOURCE_BRANCH` as `RAIDENVERSION`. See: https://github.com/docker/hub-feedback/issues/508 especially https://github.com/docker/hub-feedback/issues/508#issuecomment-222520720
