### ISSUE TITLE
Notify API user with proper error code for transfer timeouts

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#505]
## Problem Definition

The API transfer endpoint does not return a specific error code for the protocol transfer timeout.

## Solution

Add a proper HTTP error code as discussed [here](https://github.com/raiden-network/raiden/issues/440) for specifying that the underlying Raiden protocol transfer timed out.

Either a 408 or a 5xx error. Use this issue to discuss and decide on which HTTP error should be the most appropriate one.

## Tasklist

- [ ] Add the agreed upon error code as a returned result from the API transfer endpoint when we have timeouts.

**Comment by konradkonrad** [comment]
[504 Gateway Timeout](https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.5.5) sounds resonable at first sight: 
> The server, while acting as a gateway or proxy, did not receive a timely response from the upstream server specified by the URI (e.g. HTTP, FTP, LDAP) or some other auxiliary server (e.g. DNS) it needed to access in attempting to complete the request

**Comment by konradkonrad** [comment]
Furthermore, [wikipedia lists two unofficial 5xx codes](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#Unofficial_codes) for timeouts:

> **598 (Informal convention) Network read timeout error**
> Used by some HTTP proxies to signal a network read timeout behind the proxy to a client in front of the proxy

> **599 (Informal convention) Network connect timeout error**
> Used to indicate when the connection to the network times out

**Comment by hackaugusto** [comment]
Is this still a problem?

If the transfer failed, an error is returned:

https://github.com/raiden-network/raiden/blob/21479285bd821be82c9517fd781d2ccc0107950b/raiden/api/rest.py#L499-L504

And the transfer method waits on the async result to return a boolean:

https://github.com/raiden-network/raiden/blob/master/raiden/api/python.py#L433

**Comment by LefterisJP** [comment]
I think that the issue is just about a user facing error at this point.

The transfer can also have timed out which is not mentioned at the error.

Would also be really nice if we could detect a difference between a timeout and the "insufficient funds or no route to target" error.

**Comment by hackaugusto** [comment]
related: #451

**Comment by hackaugusto** [comment]
this should have been fixed by https://github.com/raiden-network/raiden/pull/5532
