### ISSUE TITLE
Raiden tries to put log files in root on macOS Catalina

### ISSUE THREAD

**Issue by taleldayekh** [raiden-network/raiden#5050]
After updating to macOS Catalina Raiden is trying to write log files to root resulting in this error on startup:

```[Errno 30] Read-only file system: '/raiden-debug_2019-10-08T09:54:50.200291.log'```

**Comment by taleldayekh** [comment]
To circumvent this error that happens in Catalina user has to add the Raiden binary to "Full Disk Access" in the "Security & Privacy" settings. **System Preferences -> Security & Privacy -> Privacy**

Raiden also needs to be started with the --log-file flag and --debug-logfile-name flag.

This should be documented if no better solution is found to handle the security changes in Catalina.

**Comment by taleldayekh** [comment]
I got another PermissionError. Have successfullt started two nodes using the solution in the previous comment. When I try to start a third node I get:

```PermissionError: [Errno 13] Permission denied: '/Users/taleldayekh/.raiden/node_0faa9bcd/netid_4/network_07147fe0/.lock'```

However, if i delete the database and start Raiden again using the same setting it works.

**Comment by rakanalh** [comment]
Please provide steps to reproduce.

**Comment by taleldayekh** [comment]
Running macOS version 10.15

1. Started Raiden with the following configuration and newly created Ethereum accounts:
```/Users/taleldayekh/Desktop/RaidenTesting/raiden-v0.200.0-rc1-macOS-x86_64 --pathfinding-service-address=https://pfs-rinkeby.services-dev.raiden.network --eth-rpc-endpoint http://geth.rinkeby.ethnodes.brainbot.com:8545 --api-address "http://localhost:5001" --keystore-path /Users/taleldayekh/Library/Ethereum/keystore --network-id rinkeby --environment-type development --log-config "raiden:debug" --accept-disclaimer```

2. Got following error:
```[Errno 30] Read-only file system: '/raiden-debug_2019-10-08T09:54:50.200291.log'```

3. Soloved it by draging and dropping my Raiden binary to:
**System Preferences -> Security & Privacy -> Privacy** and the **Full Disk Access** folder

and starting Raiden with a configuration similar to this:
```/Users/taleldayekh/Downloads/raiden-v0.200.0-rc1-macOS-x86_64 --pathfinding-service-address=https://pfs-rinkeby.services-dev.raiden.network --eth-rpc-endpoint http://geth.rinkeby.ethnodes.brainbot.com:8545 --api-address "http://localhost:5003" --keystore-path /Users/taleldayekh/Library/Ethereum/keystore --network-id rinkeby --environment-type development --log-config "raiden:debug" --accept-disclaimer --log-file /Users/taleldayekh/Desktop/RaidenTesting/node0x0falog.log --debug-logfile-name /Users/taleldayekh/Desktop/RaidenTesting/node0x0fa.log```

4. Tried to start Raiden again selecting selecting one of my Ethereum accounts created yesterday (before the Catalina update). Received this error:
```PermissionError: [Errno 13] Permission denied: '/Users/taleldayekh/.raiden/node_0faa9bcd/netid_4/network_07147fe0/.lock'```

5. Since the error mentions the path to the db I just decided to delete the db and start Raiden again. Worked fine then.

**Comment by taleldayekh** [comment]
Perhaps related to these changes in macOS, ["macOS Catalina Protects the OS in its Own Read-only Volume"](https://www.macobserver.com/analysis/macos-catalina-protects-os-read-only-volume/).

**Comment by Dominik1999** [comment]
We will close that because we have the issue https://github.com/raiden-network/raiden/issues/5100
We will try to apply to the Apple Developer Program

**Comment by LefterisJP** [comment]
There is a way around this for MacOS. You are getting hit by [OSX translocation](https://lapcatsoftware.com/articles/app-translocation.html) as it sandboxes the raiden app.

I had the same exact problem with Rotki: https://github.com/rotkehlchenio/rotkehlchen/issues/426

The proper way to store files in OSX is to just change the default directory of files for OSX to be the directory that the operating system assigns to us for files.

For Rotki, an electron application, that location was: `~/Library/Logs/rotkehlchen`. Perhaps we can do the same for Raiden?

Applying to be approved by OSX is not a bad move of-course but not every opensource project does it and still they work on OSX, just by adjusting where files are saved.

**Comment by Dominik1999** [comment]
thanks! We can use both approaches when we test our software on Mac. 

We will try to go for the clean way with respect to usability and try to get enrolled. This can happen in parallel and for only 100$ per year.

**Comment by LefterisJP** [comment]
Yeah sure that makes sense. For whoever looks into this here is a relevant SO answer: https://stackoverflow.com/questions/16744382/sandboxed-applications-where-to-save-files-without-user-interaction

**Comment by ulope** [comment]
I think this issue was closed prematurely. 
Talel said that he's running on on macOS Catalina (10.15.) which has a lot of changes regarding permissions etc.

Also it's interesting that the error message says raiden tries to write the log file into the root fs.

**Comment by LefterisJP** [comment]
So I tried to reproduce with my OSX machine (High Sierra - 10.13) and I can't reproduce. The problem does not exist in that version of OSX.

The sandoxing I mentioned [above](https://github.com/raiden-network/raiden/issues/5050#issuecomment-542630851) happens in 10.13 but only for bundled apps (app with GUI like Rotki). But it does not happen for CLI apps like Raiden. So for 10.13 (and from what I know also 10.14) Raiden is fine.

I will have to see if I can upgrade my machine to 10.15 or find someone with an OSX machine that has 10.15. My macbook air is about 9 years old :sweat_smile:

**Comment by LefterisJP** [comment]
All right so I can't reproduce this with my current hardware. My macbook air is from 2010 and High Sierra (10.13) is the last upgrade I can install on it.

Someone else will need to try and fix this or provide me with a machine that can have 10.15 installed.
