### ISSUE TITLE
Improve netting channel tests

### ISSUE THREAD

**Issue by czepluch** [raiden-network/raiden#506]
## Problem Definition

The netting channel smart contract is currently not tested very thoroughly. 

## Solution

Write more complete and thorough tests for the netting channel smart contract

## Tasklist

- [x] A modified message with must fail to decode
- [x] Testing the unlock function in `NettingChannelLibrary`
  - [x] ~Test message with a bad locksroot is ignored~ (splitted)
  - [x] A message with a tampered locks root must fail to withdraw
  - [x] Assert that a withdrawn lock can not be unlocked again
  - [x] Test interwoven locks, many locks added and unlock calls with a different ordering

**Comment by LefterisJP** [comment]
Assigning @hackaugusto  to this one since he is working on it at the moment.

**Comment by LefterisJP** [comment]
Backdated the estimate and sprint inclusion since this issue is being worked on during the sprint's duration.
