### ISSUE TITLE
Scenario to reproduce flaky matrix presence

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/raiden#5062]
## Problem

During manual testing we have discovered the following bug: https://github.com/raiden-network/raiden/issues/5059

During the nightly scenario player runs the error hasn't been discovered.

## Solution

Create a scenario or a set-up in which the error can be reproduced.

Potential solutions/ideas:
- Hosting the scenario player in a remote data center
- Use external Raiden nodes, which are running in a different data center: https://github.com/raiden-network/scenario-player/blob/master/examples/scenario-example-v2.yaml#L51-L55
- ...

**Comment by palango** [comment]
We found the issue that cause the flakyness and have a protection in place.and have
