### ISSUE TITLE
Decide cases where mediator's `waiting_transfer` needs to be acted upon

### ISSUE THREAD

**Issue by rakanalh** [raiden-network/raiden#5065]
## Abstract

Right now, Raiden's mediator state machine has an attribute called `waiting_transfer` which basically holds the transfer temporarily if the transfer cannot be moved neither forward(capacity / partner availability) nor backward(capacity).

## Motivation

Raiden only acts upon this `waiting_transfer` in case the forward channel partner becomes online. There are cases where the mediator cannot move the transfer forward/backward and set this `waitting_transfer`.

Example from #4998 where:
Assuming topology: A -> B -> C -> D
- C receives a mediated transfer from B to D.
- C looks at the `lock_timeout`, sees it's larger than the `settle_timeout` (lock_timeout = settle_timeout + 1) becacuse node C is 1 block behind A & B and decides that the channel C->D is not usable and sets `waiting_transfer`. Nothing happens to this `waiting_transfer` in this case until it's lock expires.

## Specification

- [ ] List possible validations that could fail which result in a transfer being set as a `waiting_transfer`.
- [ ] Write logic that would decide when to retry `waiting_transfer` based on external events (ex: each block).
- [ ] Unit / Integration tests

## Backwards Compatibility

This is internal logic therefore, completely backwards-compatible.

**Comment by konradkonrad** [comment]
The case from #4998 was already addressed in #5084.

**Comment by rakanalh** [comment]
Closing. Thanks @konradkonrad
