### ISSUE TITLE
Update to mypy 0.750

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden#5068]
Update to mypy 0.740 to get the latest improvements for type checking.

**Comment by Kaitou786** [comment]
Hi, @palango can you please elaborate on what I need to update. Actually, it's my first time contributing, really looking forward to helping in any way

**Comment by LefterisJP** [comment]
@Kaitou786 you just need to change the mypy version in the requirements files here: https://github.com/raiden-network/raiden/blob/develop/requirements/

And then run `make lint` and fix errors if any are found.

Actually mypy 0.740 is already out: https://pypi.org/project/mypy/ so it makes sense to upgrade directly to that.

**Comment by palango** [comment]
@Kaitou786 As Lefteris said the task is to update `mypy` and then check if new warnings occur and fix them.

For updating you need to run `requirements/deps upgrade mypy` from the raiden directory.

Let us know if you have any questions.

**Comment by Kaitou786** [comment]
@palango when i run the script  deps upgrade mypy....it is showing some errors. So i upgraded mypy using pip, so do i need to remove the errors which arises running deps upgrade mypy?

**Comment by LefterisJP** [comment]
@Kaitou786 what do you mean? What errors? Once you upgrade to mypy 0.740, it's possible that there will be type errors which you will have to fix.
