### ISSUE TITLE
Add "set_fee_schedule" to channel API

### ISSUE THREAD

**Issue by lullis** [raiden-network/raiden#5072]
Relates to #5011.

api/python.py already provides some methods to set attributes from a channel. It also needs to have a method to create a FeeSchedule.

It needs to be able to create FeeSchedule all of its possible attributes:

 - Flat fee
 - Proportional fee
 - Imbalance fees

**Comment by karlb** [comment]
Part of/duplcate of https://github.com/raiden-network/raiden/issues/5011
