### ISSUE TITLE
Not enough balance to deposit on ms1

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/raiden#5075]
## Problem Definition

Bug in ms1_simple_monitoring

```scenario_player.exceptions.legacy.RESTAPIStatusMismatchError: HTTP status code "402" while fetching http://127.0.0.1:40877/api/v1/channels. Expected 2..: {"errors": "Not enough balance to deposit. 0x62083c80353Df771426D209eF578619EE68D5C7A Available=0 Needed=1000000000000000000"}```

### System Description

Scenario Player nightly

**Comment by Dominik1999** [comment]
Please provide the logs of the nodes. 
From this error message it looks like a bug in the Scenario Player

**Comment by christianbrb** [comment]
The logs are not available
