### ISSUE TITLE
mfee3 fail, Value mismatch for \"balance\". Should: \"519999960000040000\" Is: \"500000000000000000\

### ISSUE THREAD

**Issue by agatsoh** [raiden-network/raiden#5103]
## Problem Definition

The mfee4 scenario fails because of a failure in an AssertTask 

> Value mismatch for \"balance\". Should: \"519999960000040000\" Is: \"500000000000000000\ 

`
{"task": "<AssertTask: {'from': 0, 'to': 1, 'total_deposit': 1000000000000000000, 'balance': 519999960000040000, 'state': 'opened'}>", "event": "Task errored", "logger": "scenario_player.tasks.base", "level": "error", "timestamp": "2019-10-16 05:38:57.733130", "exception": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.7/site-packages/scenario_player/tasks/base.py\", line 74, in __call__\n    return self._run(*args, **kwargs)\n  File \"/usr/local/lib/python3.7/site-packages/scenario_player/tasks/api_base.py\", line 70, in _run\n    return self._process_response(response_dict)\n  File \"/usr/local/lib/python3.7/site-packages/scenario_player/tasks/channels.py\", line 158, in _process_response\n    f'Value mismatch for \"{field}\". '\nscenario_player.exceptions.legacy.ScenarioAssertionError: Value mismatch for \"balance\". Should: \"519999960000040000\" Is: \"500000000000000000\" Channel: {'total_withdraw': 0, 'partner_address': '0x5a3Fb2C08974c33CCe4C84E53291424AB147003F', 'channel_identifier': 2473, 'balance': 500000000000000000, 'state': 'opened', 'reveal_timeout': 50, 'settle_timeout': 500, 'token_address': '0x62083c80353Df771426D209eF578619EE68D5C7A', 'total_deposit': 1000000000000000000, 'token_network_address': '0x9526EC0E58ac5Bb1e24d655E964f0eAA46054d16'}"}
`

[Scenario_player_Logs-mfee3_only_imbalance_fees-1-latest-2019-10-16.tar.gz](https://github.com/raiden-network/raiden/files/3733968/Scenario_player_Logs-mfee3_only_imbalance_fees-1-latest-2019-10-16.tar.gz)

**Comment by Dominik1999** [comment]
caused by #5078
