### ISSUE TITLE
"Uploading artifacts" step in CI unit tests is slow

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden#5106]
The step "Uploading artifacts" in the CI takes long, especially for the unit tests where there are lots of small files.

For example in https://circleci.com/gh/raiden-network/raiden/84582 the tests itself take 1:15min and the the upload step takes 1:03 min, nearly doubling the test runtime.

**Comment by hackaugusto** [comment]
implemented by https://github.com/raiden-network/raiden/pull/5846
