### ISSUE TITLE
Use coincurve instead of secp256k1-py

### ISSUE THREAD

**Issue by czepluch** [raiden-network/raiden#513]
## Problem Definition

It seems that secp256k1-py is not being maintained anymore and that http://github.com/ofek/coincurve are maintaining a library instead.

## Solution

Use http://github.com/ofek/coincurve instead of secp256k1-py
This should also remove the annoying warning from secp256k1-py when starting raiden.

**Comment by hrishikeshio** [comment]
I got functions for keys and address converted to use coincurve.
Sign functions do not seem to work work in coincurve as of latest version. 
https://github.com/ofek/coincurve/issues/1

**Comment by hrishikeshio** [comment]
Also, this: https://github.com/ofek/coincurve/blob/master/coincurve/ecdsa.py#L32

**Comment by ofek** [comment]
@czepluch @hrishikeshio Thanks for the interest in coincurve!

I've made the recovery workflow much easier in 4.2.0 by adding `PublicKey.from_signature_and_message`. Travis should be finished the deploy in less than an hour.

**Comment by hrishikeshio** [comment]
@ofek Thanks alot but now I am having a different issue. This function worked in earlier version.
https://github.com/ofek/coincurve/issues/2

@czepluch Perhaps we should keep secp256k1.py for now and use coincurve later once it is more matured. 
Also ethereum.py is using secp256k1.py so it is not easy to remove dependency on secp256k1.py completely.

**Comment by ofek** [comment]
Coincurve is stable!

@hrishikeshio You seem to be using coincurve as a drop-in replacement for secp256k1-py. This will cause issues because the 2 don't share the same API. Coincurve has an API that is MUCH easier to use. I've documented it here: https://github.com/ofek/coincurve#readme.

**Comment by czepluch** [comment]
@hrishikeshio Just make a PR for pyethereum changin to coincurve aswell.

**Comment by ofek** [comment]
@czepluch https://github.com/ethereum/pyethereum/issues/708 :)

**Comment by czepluch** [comment]
Ah, excellent :) Thanks.
