### ISSUE TITLE
Update mfee3 scenario (only imbalance fees) according to new calculation

### ISSUE THREAD

**Issue by Dominik1999** [raiden-network/raiden#5131]
After #5053 we need to update the mfee3 scenario.
We want to test the correct calculation of the imbalance fees as well as the function to enable and disable overall negative fees.

- We want to have 4 nodes and 3 channels in a line A - B - C - D
- B does not allow overall negative fees
- D does allow overall negative fees
- All channels are perfectly balanced at the beginning
- A sends several transfers to D until imbalance fee kicks in 

- [x] update scenario in raiden repo
- [x] adjust readme for mfee3 scenario

**Comment by christianbrb** [comment]
We should test, that rebalancing actually works within this scenario.

**Comment by karlb** [comment]
The work for this is done, I'm just waiting for a working SP setup, so that I can test the scenarios once before requesting a review.
