### ISSUE TITLE
Scenario bf1 failed with RequestCount assertion

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#5134]
As seen [here](https://github.com/raiden-network/raiden/issues/5078#issuecomment-544887822).

The scenario failed here:
https://github.com/raiden-network/raiden/blob/e34025fd39504da04697cc3a84f76b0b3086d0d1/raiden/tests/scenarios/bf1_basic_functionality.yaml#L126

with

```scenario_player.exceptions.legacy.ScenarioAssertionError: Expected request_count 11 but got 10 ```

Logs and DB for the scenario run are [here](https://we.tl/t-QxrZbnWMiQ)

**Comment by palango** [comment]
The PFS logs are gone for this issue, so we need to reproduce it to find out more.

**Comment by Dominik1999** [comment]
closed until we see it in the nightlies to get the logs
