### ISSUE TITLE
Create end to end API tests

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#514]
## Problem Definition

At the moment the API endpoints are only [unit tested](https://github.com/raiden-network/raiden/blob/c3c18e31b566f1c209051cdafc64c5fb1219ca4f/raiden/tests/api/test_api.py) and we don't have any end to end tests for the API.

## Solution

Create end to end tests using the API endpoints.
## Tasklist

Example:

- [ ] Create a new api test suite: `test_api_e2e.py`
- [ ] Write tests in the aforementioned test file that utilize all endpoints in an end to end fashion

**Comment by hackaugusto** [comment]
@LefterisJP [The `ApiTestContext` and monkey patches](https://github.com/raiden-network/raiden/blob/c3c18e31b566f1c209051cdafc64c5fb1219ca4f/raiden/tests/fixtures/api.py) were removed by 9079f8c5e6471744b6c5a10103b16d1cac5883a0, do you think this issue is still relevant?

**Comment by LefterisJP** [comment]
Hmm not as first defined. I would say it's still relevant in the fact that most of the stuff that test the python api now should do so through the rest API.

**Comment by LefterisJP** [comment]
This issue is no longer needed. Mocking is no longer in the rest api and a big part of the functionality is covered end to end.
