### ISSUE TITLE
Ensure cli argument for transport server is respected

### ISSUE THREAD

**Issue by konradkonrad** [raiden-network/raiden#5141]
While debugging federation, @err508 reported, that scenario settings for transport servers may not be fully respected, and available transports from `settings.py` were still contacted (`GET transportxx....`). This hints to, that the cli setting may not be fully propagated everywhere.

### What can be done
- [ ] Provide an integration test to reproduce it
- [ ] Add a guard around accessing the `settings.py` values, if transport was configured from cli

**Comment by konradkonrad** [comment]
@err508 could you provide me logs of what you saw and what made you suspect the issue?

**Comment by err508** [comment]
I saw it in a local synapse instance yesterday, I'll reproduce it

**Comment by rakanalh** [comment]
This is not what i've been able to gather. Also, when it comes to the servers list, the transport does not interact with `settings.py`. IMO, the issue description is invalid and the issue should be closed. 

We can re-open if any logs and steps to reproduce can prove me otherwise.
