### ISSUE TITLE
Remove **mode: managed** from all the scenarios

### ISSUE THREAD

**Issue by agatsoh** [raiden-network/raiden#5146]
## Abstract
Copying from https://github.com/raiden-network/scenario-player/issues/360 Issue 360 of the scenario player each scenario has a `mode: managed` config in most or all of the scenarios.
```
nodes:
  mode: managed
  count: 4
  raiden_version: local
```
## Motivation
Though this is pretty harmless since we do not use this feature any longer it is advised to remove it so that it doesnt create any confusion

## Specification
Removal of `mode: managed` from all the scenarios

## Backwards Compatibility
Since this is a harmless removal it does not need to be backward compatible.

**Comment by palango** [comment]
@czepluch Is this something we still want to do?

**Comment by czepluch** [comment]
Good question. If it's just about removing the `mode: managed` to get rid of confusion, we might as well do it. @agatsoh can you take care of it?

**Comment by ulope** [comment]
It can be safely removed. That flag is a no-op. There is no other mode besides `managed` anymore.

**Comment by agatsoh** [comment]
@czepluch Yeah I will take care of it.
