### ISSUE TITLE
Matrix room availability test

### ISSUE THREAD

**Issue by rakanalh** [raiden-network/raiden#5149]
## Abstract

When a transport server has a room `xyz:transport-host, messages and presence updates taking place in this room would be propagated to servers inside the federation. However, if this room-owning server goes down, we are not certain that this room would still be usable on the other servers.

## Specification
A test should be written such that:

- [ ] Write a test that spawns a transport cluster
- [ ] Take the room-owning server down
- [ ] Verify whether or not the nodes using the other servers are able to use the room.
- [ ] Add test for join_global_rooms function in the services

**Comment by ulope** [comment]
The room is available even when the originating server goes down. 
One federation of a room has started there is no such thing as an 'owning' server anymore.
This is a fundamental feature of the way Matrix federation works.
