### ISSUE TITLE
Update click options to reflect supported flags for services

### ISSUE THREAD

**Issue by nlsdfnbch** [raiden-network/raiden#5158]
Current state
-----------------
The scenario player uses `raiden.ui.cli` to read supported flags for the raiden binary. 
We obtain the flags as follows::

```
>>>from raiden.ui.cli import run as cli_run
>>>{param.name.replace("_", "-") for param in cli_run.params if param.is_flag}
```

Problem
----------
The parameters defined in `cli_run`are *not* up-to-date with the real-world, and stops users from making use of newer features in the scenario player (an example of this would be the `--no-cap-mediation-fees` flagm which is not listed).

Expected behavior
-----------------------
The above snippet should output *all* available flag options for the raiden binary's possible raiden-service configurations.

**Comment by karlb** [comment]
`raiden.ui.cli` looks fine to me, see https://github.com/raiden-network/scenario-player/pull/372#issuecomment-546852925

**Comment by nlsdfnbch** [comment]
In response to https://github.com/raiden-network/scenario-player/pull/372#issuecomment-546852925:

I disagree. The entire idea of having two options to toggle a state makes very little sense to me. One of those states is the default, the other is the exception. The exception should be listed in those parameters, and the default shouldn't even exist as a flag. 

So, `--no-cap-mediation-fees` is either the exception (and there are caps on mediation fees by default) or `--cap-mediation-fees` is the exception and there is *no* cap on the mediation fees by default.

Eitherway, one of these parameters should appear in the list I fetch from the `raiden.ui.cli` module, and the other should not be necessary to be passed.

The fact that you need `--no-cap-mediation-fees`, tells me that `--cap-mediation-fees` is implied. So I expect `--no-cap-mediation-fee` to show up in the flag list.

**Comment by karlb** [comment]
Allowing both makes it possible to change the default without breaking calls that use the flag.

I also think it is more straightforward to see the world as click does instead of adopting a different world view and converting back and forth. Consistency is important and we do use click quite a lot.

I can certainly provide you with a list of expected flags, but I would do the same thing to create it that I outlined in the comment. The list has to be generated from the click options or it will get out of date and there is not benefit in filtering out the default case.

**Comment by nlsdfnbch** [comment]
>I can certainly provide you with a list of expected flags, but I would do the same thing to create it that I outlined in the comment. The list has to be generated from the click options or it will get out of date and there is not benefit in filtering out the default case.

Great, thanks! The important part is that these options are provided by `raiden`. I should not be doing any magic to generate any "missing" ones on the SP side for exactly the reason you stated: it will get out of date otherwise.
