### ISSUE TITLE
`test_matrix_discovery_room_offline_server` is flaky

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/raiden#5176]
https://circleci.com/gh/raiden-network/raiden/86817#tests/containers/20

**Comment by LefterisJP** [comment]
Hmm @hackaugusto the linked container shows `test_regression_payment_complete_after_refund_to_the_initiator[matrix-False-0-5] ` as having failed and not `test_matrix_discovery_room_offline_server`.

The failure seems to be `RuntimeError: dictionary changed size during iteration`

And the build seems to have had been canceled. Which test was the issue made for? How would you like to proceed?

1. Skip one of the tests as flaky and investigate?
2. Close the issue as an one off?

**Comment by hackaugusto** [comment]
This was fixed by https://github.com/raiden-network/raiden/pull/5241
