### ISSUE TITLE
Don't rely on undocumented HTTP response codes.

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/raiden#5190]
The `_get_public_room` code is checking the HTTP status code when [an error happens](https://github.com/raiden-network/raiden/blob/1ff6e6e22017b16a22fcef0e23535d5c41c617cc/raiden/network/transport/matrix/transport.py#L1062-L1067), [which is not documented](https://matrix.org/docs/spec/client_server/r0.5.0#post-matrix-client-r0-rooms-roomid-join). On top of that there are additional error codes that are not documented and are not properly documented, namely `409` can be returned if the room exists and the partner node has joined it already. Because not all errors are documented and therefore are not properly handled, the exception handling code is currently doing the wrong thing and trying to create a new room when it is not necessary.

Found while debugging a integration failure, here is the general outline: https://gist.github.com/hackaugusto/45a1118ab4a637a06e724a589ba6a8ed

**Comment by rakanalh** [comment]
According to what @hackaugusto explained to me, this is directly related to multiple rooms being created for a single channel between both participants.
