### ISSUE TITLE
PFS scenarios fail with "No route found"

### ISSUE THREAD

**Issue by rakanalh** [raiden-network/raiden#5199]
## Problem Description

Most scenarios are currently failing with "No route found". We've rebooted the testing synapse servers with a bootstrap script which creates discovery / path finding and monitoring rooms.

**Comment by rakanalh** [comment]
I ran PFS with PFS7 scenario using the SP and transfers pass locally.

However, because we did not restart the testing deployment of the PFS, i think that they might have joined global rooms prior to the reboot of the synapse server and the scenario nodes are joining the new rooms. This could lead to the PFS not being notified about presence information for nodes that are brought up by the SP.

@karlb restarted the PFS so we should be able to run the scenarios again and see if that resolves the issue.

**Comment by rakanalh** [comment]
Issue is confirmed, restarting the PFS to join the new pathfinding room did the trick. Closing.

**Comment by LefterisJP** [comment]
@rakanalh That's the classic case of "Did you try to turn it off and on again"? :smile:

**Comment by rakanalh** [comment]
hahaha yea... it would have been hard to reason about if not for the long hours of staring at logs a couple of weeks ago.
