### ISSUE TITLE
Lock expired in pfs7 scenario

### ISSUE THREAD

**Issue by Dominik1999** [raiden-network/raiden#5203]
I ran the pfs 7 scenario locally with remote pfs with fee on goerli) and got

`"Payment couldn't be completed because: lock expired"`

Full logs are available here: 
[PFS7-Fail Lock expired.zip](https://github.com/raiden-network/raiden/files/3798163/PFS7-Fail.Lock.expired.zip)

**Comment by hackaugusto** [comment]
@Dominik1999 Every single node has a gap of 20 minutes in the log files:

log | gap
--- | ---
node_1_000/run-001.log | 0:19:59.326674
node_1_001/run-001.log | 0:19:59.365394
node_1_002/run-001.log | 0:19:59.546466
node_1_003/run-001.log | 0:19:59.475730
node_1_004/run-001.log | 0:19:59.409263

Did your computer go to sleep while the scenario was being executed? That would explain the problem we are seeing.

**Comment by Dominik1999** [comment]
@hackaugusto I do not know to be honest. I can try to reproduce this and prevent hibernation.

**Comment by Dominik1999** [comment]
Sure it is not related to this issue? https://github.com/raiden-network/raiden/issues/5236

**Comment by Dominik1999** [comment]
But if it cannot be analyzed by the logs, then just close it. @jomuel

**Comment by hackaugusto** [comment]
> Sure it is not related to this issue? #5236

These are different things, the issue #5236 does not have a huge gap in the logs, here are the gaps for **#5236**, which is on the time scale of seconds, not minutes:

log | start time | end time | total gap
--- | --- | --- | ---
node_4_000/run-004.log | 10:48:58.237749 | 10:49:07.415377 | 0:00:09.177628
node_4_001/run-004.log | 10:48:56.608643 | 10:49:07.275406 | 0:00:10.666763
node_4_002/run-004.log | 10:48:58.002907 | 10:49:07.023475 | 0:00:09.020568
node_4_003/run-004.log | 10:48:56.568363 | 10:49:06.943624 | 0:00:10.375261
node_4_004/run-004.log | 10:49:21.782807 | 10:49:32.390309 | 0:00:10.607502
