### ISSUE TITLE
Scenario for different non allowed operations

### ISSUE THREAD

**Issue by czepluch** [raiden-network/raiden#5210]
### Introduction 
During manual release testing for Red Eyes back in 2018, one of the tests that was carried out was to do try to do different non allowed actions such as opening the a channel with the same partner twice, depositing after close was called and trying to close the same channel twice. Currently this is not done in any of the scenarios and hence, a scenario doing this should be added.

### Specification
Setup topology of [0, 1] with deposit in both directions.
Node0 tries to open a channel with node1 again. Expected conflict.
Node1 withdraws its entire deposit.
Node1 tries to withdraw the same amount again. Expected conflict.
Node0 closes the channel.
Node1 tries to deposit again. Expected conflict.
Node0 tries to make a payment to node1. Expected conflict.
Node0 tries to close the channel again. Expected conflict.
Node1 tries to open a channel with node0 again before settlement is over. Expected conflict.

**Comment by czepluch** [comment]
Implemented, but need to discuss with @christianbrb to find out if it makes sense to merge according to the feedback on the PR

**Comment by Dominik1999** [comment]
How can I help here? @christianbrb

**Comment by Dominik1999** [comment]
Those operations are being tested in a unit test
