### ISSUE TITLE
Remove `force_resync` from `Room.get_joined_members`

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/raiden#5212]
## Abstract

That flag existed to force context-switches in a hot loop. This should be unnecessary after https://github.com/raiden-network/raiden/pull/4836/ , additionally, if the need for it comes back, one can just use `gevent.sleep` to give control back to the hub, and remove the extra lines of code.

## Motivation

This is just a small simplification.

**Comment by fredo** [comment]
The Flag still needs to exist, for checking how many members are in private rooms (security concerns). 

Fetching joined members is necessary in the following case:

- The user gets invited into a private room (by a user which is whitelisted)
- the room has a long history of events (> __LIMIT__ events -> that's the current timeline filter limit)
- The user could miss member join events and does not know if there are multiple participants in the room (maybe from different addresses). My current PR #5709 handles this case. 
- Upon joining a room the members are fetched to see independently from the sync call if there are too many members in the room. If this is the case it could be a potential privacy problem and user is leaving the room.

It must be said that currently there is no filtering on timeline events but for first_sync. Rooms with a large history should fetch all the timeline events currently at the first "normal" sync. If we want to change this in the future fetching the members become useful upon joining the room.

**Comment by fredo** [comment]
can be closed
