### ISSUE TITLE
MFEE2 gets 404 while fetching a route from the PFS

### ISSUE THREAD

**Issue by agatsoh** [raiden-network/raiden#5247]
## Problem Definition
Scenario in a nutshell
node 0 => `0x8201E3878D83c44645e4317AFF3674B6773fc77e`
node 1 => `0x001026412FD1b7Af1beA06bc4649c61c19745066`
node 2 => `0x8BB8a0C187900510b259D82A4A43B13ec1a3527e`
node 3 => `0xFa1B1e5AF004dEb277296a84b9cC955f4d05Afc5`

In the scenario Log
``` 
{
  "task": "<AssertPFSHistoryTask: {'source': 0, 'request_count': 1, 'target': 3, 'expected_routes': [[0, 1, 2, 3]]}>",
  "event": "Task errored",
  "logger": "scenario_player.tasks.base",
  "level": "error",
  "timestamp": "2019-11-07 03:19:04.919970",
  "exception": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.7/site-packages/scenario_player/tasks/base.py\", line 74, in __call__\n    return self._run(*args, **kwargs)\n  File \"/usr/local/lib/python3.7/site-packages/scenario_player/tasks/api_base.py\", line 59, in _run\n    f'HTTP status code \"{resp.status_code}\" while fetching {url}. '\nscenario_player.exceptions.legacy.RESTAPIStatusMismatchError: HTTP status code \"404\" while fetching https://pfs-goerli-with-fee.services-dev.raiden.network/api/v1/_debug/routes/0xDa1fBc048f503635950058953f5c60FC1F564ee6/0x8201E3878D83c44645e4317AFF3674B6773fc77e/0xFa1B1e5AF004dEb277296a84b9cC955f4d05Afc5. Expected 2..: 404 page not found\n"
}
```

while fetching this request the `node 0` gets `404` error from the PFS
`https://pfs-goerli-with-fee.services-dev.raiden.network/api/v1/_debug/routes/0xDa1fBc048f503635950058953f5c60FC1F564ee6/0x8201E3878D83c44645e4317AFF3674B6773fc77e/0xFa1B1e5AF004dEb277296a84b9cC955f4d05Afc5`

`0xDa1fBc048f503635950058953f5c60FC1F564ee6` : Token Network Address
`0x8201E3878D83c44645e4317AFF3674B6773fc77e` : Node 0
`0xFa1B1e5AF004dEb277296a84b9cC955f4d05Afc5` : Node 3

This task is on line 62
https://github.com/raiden-network/raiden/blob/develop/raiden/tests/scenarios/mfee2_proportional_fees.yaml#L62-L67

Logs of node 0
```
{"log_message": "Expecting value: line 1 column 1 (char 0)", "event": "An error with the path request occured", "logger": "raiden.routing", "level": "warning", "timestamp": "2019-11-07 03:18:17.678853"}
{"event": "Request to Pathfinding Service was not successful, falling back to internal routing.", "logger": "raiden.routing", "level": "warning", "timestamp": "2019-11-07 03:18:17.679680"}
```
1. **An error with the path request occured**
2. **Request to Pathfinding Service was not successful, falling back to internal routing**

[mfee2_proportional_fees.tar.gz](https://github.com/raiden-network/raiden/files/3819470/mfee2_proportional_fees.tar.gz)

**Comment by LefterisJP** [comment]
This appears to be due to the same underlying issue with the PFS not running properly last night: https://github.com/raiden-network/raiden-services/issues/616

Closing this issue.
