### ISSUE TITLE
MFEE1 scenario Node gets no route available answer from the PFS

### ISSUE THREAD

**Issue by agatsoh** [raiden-network/raiden#5248]
## Problem Definition

Scenario in a nutshell

node 0 => `0x4c26F6397eFD10C0dEf1B9969Ec83fB407fC7133`
node 1 => `0x2AC14a3F94Da8B3FEDE83c553d6B28Fb2d0ca22A`
node 2 => `0x5E2d31a49bd4e0F44D98784EDf9A1F6CD3d91D28`
node 3 => `0x5bD374500043EF4e962d8b65AF11FFC9DEc34688`

In the scenario logs we get the exception
```
{
  "task": "<TransferTask: {'from': 0, 'to': 3, 'amount': 10000, 'expected_http_status': 200}>",
  "event": "Task errored",
  "logger": "scenario_player.tasks.base",
  "level": "error",
  "timestamp": "2019-11-07 03:11:49.396402",
  "exception": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.7/site-packages/scenario_player/tasks/base.py\", line 74, in __call__\n    return self._run(*args, **kwargs)\n  File \"/usr/local/lib/python3.7/site-packages/scenario_player/tasks/api_base.py\", line 59, in _run\n    f'HTTP status code \"{resp.status_code}\" while fetching {url}. '\nscenario_player.exceptions.legacy.RESTAPIStatusMismatchError: HTTP status code \"409\" while fetching http://127.0.0.1:37831/api/v1/payments/0x62083c80353Df771426D209eF578619EE68D5C7A/0x5bD374500043EF4e962d8b65AF11FFC9DEc34688. Expected 200: {\"errors\": \"Payment couldn't be completed because: there is no route available\"}"
}
```

What does the exception say:

1. Payment couldn't be completed because: there is no route available

2. while fetching 
`http://127.0.0.1:37831/api/v1/payments/0x62083c80353Df771426D209eF578619EE68D5C7A/0x5bD374500043EF4e962d8b65AF11FFC9DEc34688`
where:
`0x62083c80353Df771426D209eF578619EE68D5C7A` : token address
`0x5bD374500043EF4e962d8b65AF11FFC9DEc34688` : Node 3

3. This task fails
`- transfer: {from: 0, to: 3, amount: 10_000, expected_http_status: 200}`
It is on line number
https://github.com/raiden-network/raiden/blob/develop/raiden/tests/scenarios/mfee1_flat_fee.yaml#L57

[mfee1_flat_fee.tar.gz](https://github.com/raiden-network/raiden/files/3819570/mfee1_flat_fee.tar.gz)

**Comment by LefterisJP** [comment]
This appears to be due to the same underlying issue with the PFS not running properly last night: https://github.com/raiden-network/raiden-services/issues/616

Closing this issue -- especially since the same scenario passed after the PFS was fixed.
