### ISSUE TITLE
BF1 scenario node gets No route available answer from the PFS

### ISSUE THREAD

**Issue by agatsoh** [raiden-network/raiden#5254]
## Problem Definition
Scenario in a nutshell
node 0 => `0x76F5bc06fC0b07865e04a245fC91A68D46Fb7d33`
node 1 => `0x2daE99bf7E29830AB2e529ac0A9a4aBce7e06f42`
node 2 => `0x481387D8855a1A105647348c9b9b279B80aA35AA`
node 3 => `0x444E2aCC6135Dc1e11E35f7a792c6fc3755BE40f`
node 4 => `0x549281a3a1c0de6b57933600AF1F09cD9034c597`

In the Scenario logs we get the exception here.

```
{
  "task": "<TransferTask: {'from': 3, 'to': 0, 'amount': 1000000000000000, 'lock_timeout': 30}>",
  "event": "Task errored",
  "logger": "scenario_player.tasks.base",
  "level": "error",
  "timestamp": "2019-11-07 02:56:15.480211",
  "exception": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.7/site-packages/scenario_player/tasks/base.py\", line 74, in __call__\n    return self._run(*args, **kwargs)\n  File \"/usr/local/lib/python3.7/site-packages/scenario_player/tasks/api_base.py\", line 59, in _run\n    f'HTTP status code \"{resp.status_code}\" while fetching {url}. '\nscenario_player.exceptions.legacy.RESTAPIStatusMismatchError: HTTP status code \"409\" while fetching http://127.0.0.1:54853/api/v1/payments/0x62083c80353Df771426D209eF578619EE68D5C7A/0x76F5bc06fC0b07865e04a245fC91A68D46Fb7d33. Expected 2..: {\"errors\": \"Payment couldn't be completed because: there is no route available\"}"
}
```

What does the exception say 

1. It fails in 
<pre>
< <b>TransferTask</b>: {'from': 3, 'to': 0, 'amount': 1000000000000000, 'lock_timeout': 30}>
</pre>

2. Payment couldn't be completed because: there is no route available

3. The API call that fails 
`http://127.0.0.1:54853/api/v1/payments/0x62083c80353Df771426D209eF578619EE68D5C7A/0x76F5bc06fC0b07865e04a245fC91A68D46Fb7d33`
where
`0x62083c80353Df771426D209eF578619EE68D5C7A` : Token address
`0x76F5bc06fC0b07865e04a245fC91A68D46Fb7d33` : Node 0
transferring from node 3 to 0

4. Fails at line number 228 
- transfer: {from: 3, to: 0, amount: 1_000_000_000_000_000, lock_timeout: 30}
https://github.com/raiden-network/raiden/blob/develop/raiden/tests/scenarios/bf1_basic_functionality.yaml#L228

[bf1_basic_functionality.tar.gz](https://github.com/raiden-network/raiden/files/3820403/bf1_basic_functionality.tar.gz)

**Comment by LefterisJP** [comment]
This appears to be due to the same underlying issue with the PFS not running properly last night: https://github.com/raiden-network/raiden-services/issues/616

Closing this issue -- especially since the same scenario passed after the PFS was fixed.
