### ISSUE TITLE
Supply /status endpoint to allow querying status of node

### ISSUE THREAD

**Issue by nlsdfnbch** [raiden-network/raiden#5281]
## Abstract
During startup of a raiden node, there currently is no way to tell if the API is working but still starting up, or broken and not accepting connections.

Currently, we must query the API until a connection is accepted, to know whether or not the API
is up and running, and there is no distinction between the API still starting up and the node being broken.

## Proposed Feature
Supply a simple `GET /status` endpoint which returns specifig http status codes indicating the status of the node.

The endpoint returns a `503` if the node/api is still spinning up, a `200` if the API is available and connection errors would indicate issues with the node itself.

## Specification

If the feature is technical in nature please write as detailed as possible a specification of what needs to be built.
```yaml
openapi: "3.0.0"
paths:
  /api/status:
    get:
      operationId: getAPIStatus
      summary: Indicate whether or not the API is available yet.
      responses:
        200:
          description: OK
        503:
          description: Service Unavailable
```

**Comment by jomuel** [comment]
We have a feature request for the raiden-installer to display a progress bar during the initial sync. So the `/status` endpoint should also report the numbers of synced blocks and of blocks yet to sync.
