### ISSUE TITLE
Add testing information to Alderaan Release Doc p.23 and p.24

### ISSUE THREAD

**Issue by Dominik1999** [raiden-network/raiden#5301]
We need some details for the section about testing in the Raiden Client in the Alderaan Release Doc. 

https://docs.google.com/document/d/1l0N6UpkD-ctK3lfx31Pa9s6IfnWaufP6i-KXx_2flBc/edit#

Please add the missing information on pages 23 / 24. 

As an example, please see the section about testing for the Raiden Services p. 25f

**Comment by LefterisJP** [comment]
Done.
