### ISSUE TITLE
Outcome Matrix Focus Group - Remerge Services Rooms

### ISSUE THREAD

**Issue by Dominik1999** [raiden-network/raiden#5310]
At the moment, there is no need for the PFS rooms to be global across all servers. The raiden nodes are not supposed to read those messages at all anyway and the PFS joins each room on every server.

We want to remerge all rooms into one. Hypothesis: This causes the problem of #5311 

We want to do that now.

**Comment by ulope** [comment]
Doing it

**Comment by ulope** [comment]
Done. Now there can only be one (room) again.

**Comment by Dominik1999** [comment]
ok so should we restart the services? Or do we remove some code from the services before that?

**Comment by ulope** [comment]
Paul said receiving messages multiple times shouldn't hurt. So a restart should be enough for now.
