### ISSUE TITLE
Add scenario for testing long paths

### ISSUE THREAD

**Issue by czepluch** [raiden-network/raiden#5325]
### Introduction
As part of raiden-network/team#664 it was discovered that we need to have the https://github.com/raiden-network/raiden/blob/develop/raiden/tests/scenarios/ci/long_path_mediated_transfers.yaml scenario updated to be run as part of the nigthly scenarios. This is done to make sure that transfers go through in cases where there are very long paths in the network topology.

### Description
An adjustment of the already existing scenario should be made so that it complies with the standard we use for the other scenarios. Is might make sense to add some fee calculations to this scenario since long path will have quite a lot of fees associated with them.

**Comment by christianbrb** [comment]
Decision has been taken to implement it with just one automtically selected Matrix server

@czepluch creates an issue to add different matrix servers

CC @Dominik1999
