### ISSUE TITLE
watch_for_unlock_failures is too slow

### ISSUE THREAD

**Issue by jomuel** [raiden-network/raiden#5334]
A profiling of some flaky integration tests show that they spend way too much time in the `watch_for_unlock_failures` context manager.

Proposed fix: Rather than recovering every event from the database, patch the WAL and count events as they happen.

Related issue: #4803 (Although there will be more problems with the stress test)

**Comment by rakanalh** [comment]
I read "patch" and thought i should step in.

The approach should not use the mock library's patch method.

We should create something like:
https://github.com/raiden-network/raiden/blob/d63e71ca4c9fba697c400b00e58bb594bee22bb0/raiden/tests/utils/protocol.py#L63

Where we specify that we want to wait for a certain state change / event to be seen by the wal and we get an `AsyncResult`. We wait for that AsyncResult and then we release it and continue to do whatever we want to check.

Another idea would be to use that same `HoldRaidenEventHandler` class to wait for `EventUnlockClaimFailed` to be emitted into the event handler.

Thinking about it now, I would prefer the second approach.

**Comment by jomuel** [comment]
Sure. The mock library makes no sense here. What I mean was just to overwrite `storage.wal.log_and_dispatch` on the tested nodes. `HoldRaidenEventHandler` may be a good idea too.
