### ISSUE TITLE
MS4 fails due Not enough balance to deposit

### ISSUE THREAD

**Issue by agatsoh** [raiden-network/raiden#5341]
## Problem Definition

Scenario in a nutshell
node0: `0x6b93E4A26248735eED10DD518D752995573cE3e7`
node1: `0xBdBce507D842d2c4a5E026cca63a00158adfef1F`

```
{
  "task": "<OpenChannelTask: {'from': 0, 'to': 1, 'total_deposit': 1000000000000000000}>",
  "event": "Task errored",
  "logger": "scenario_player.tasks.base",
  "level": "error",
  "timestamp": "2019-11-21 02:49:58.217213",
  "exception": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.7/site-packages/scenario_player/tasks/base.py\", line 74, in __call__\n    return self._run(*args, **kwargs)\n  File \"/usr/local/lib/python3.7/site-packages/scenario_player/tasks/api_base.py\", line 59, in _run\n    f'HTTP status code \"{resp.status_code}\" while fetching {url}. '\nscenario_player.exceptions.legacy.RESTAPIStatusMismatchError: HTTP status code \"402\" while fetching http://127.0.0.1:58281/api/v1/channels. Expected 2..: {\"errors\": \"Not enough balance to deposit. 0x62083c80353Df771426D209eF578619EE68D5C7A Available=0 Needed=1000000000000000000\"}"
}
```

what does the exception say:

1. Failure in the OpenChannelTask line 53

`- open_channel: {from: 0, to: 1, total_deposit: 1_000_000_000_000_000_000}`

2. `Not enough balance to deposit. 0x62083c80353Df771426D209eF578619EE68D5C7A Available=0 Needed=1000000000000000000`

Somehow available balance becomes 0 though we have `balance_fund: 10_000_000_000_000_000_000`.
whether it skips minting needs to be found

From logs of node0 we get
```
{
  "errors": "Not enough balance to deposit. 0x62083c80353Df771426D209eF578619EE68D5C7A Available=0 Needed=1000000000000000000",
  "status_code": 402,
  "event": "Error processing request",
  "logger": "raiden.api.rest",
  "level": "error",
  "timestamp": "2019-11-21 02:49:58.175814"
}
```
[ms4_udc_too_low_2019_11_21.tar.gz](https://github.com/raiden-network/raiden/files/3875149/ms4_udc_too_low_2019_11_21.tar.gz)

**Comment by palango** [comment]
This issue is quite old now and a lot of code changed since then. Please reopen if it happens again.
