### ISSUE TITLE
Bad Gateway Error in PFS7 scenario

### ISSUE THREAD

**Issue by agatsoh** [raiden-network/raiden#5370]
## Problem Definition

Scenario in a nutshell:
node0: `0x8e232Eee8b8e27795C5c6E8d4db03453161d93Ef`
node1: `0x361172E02dD7bd14c017f9a577723741EE14500a`
node2: `0x951Ec7BC1985F9b6439Fd4b25F557D1fDBf41536`
node3: `0x3EC67014720F2206fBA58cF75A3009Ab48Dd28fC`
node4: `0x689990f29883869E4b02BB62a58Eab6499075C29`

```
{
  "task": "<AssertPFSIoUTask: {'source': 0, 'amount': 10000}>",
  "event": "Task errored",
  "logger": "scenario_player.tasks.base",
  "level": "error",
  "timestamp": "2019-11-26 03:36:30.406802",
  "exception": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.7/site-packages/scenario_player/tasks/base.py\", line 74, in __call__\n    return self._run(*args, **kwargs)\n  File \"/usr/local/lib/python3.7/site-packages/scenario_player/tasks/api_base.py\", line 59, in _run\n    f'HTTP status code \"{resp.status_code}\" while fetching {url}. '\nscenario_player.exceptions.legacy.RESTAPIStatusMismatchError: HTTP status code \"502\" while fetching https://pfs-goerli-with-fee.services-dev.raiden.network/api/v1/_debug/ious/0x8e232Eee8b8e27795C5c6E8d4db03453161d93Ef. Expected 2..: Bad Gateway"
}
```

What does the exception say:

1. Bad Gateway Error

2. Occurs while calling

`https://pfs-goerli-with-fee.services-dev.raiden.network/api/v1/_debug/ious/0x8e232Eee8b8e27795C5c6E8d4db03453161d93Ef`
where 

`0x8e232Eee8b8e27795C5c6E8d4db03453161d93Ef` address of node0

3. Scenario fails at:
`- assert_pfs_iou: {source: 0, amount: 10000}`
line 92

[pfs7_multiple_payments_2019_11_26.tar.gz](https://github.com/raiden-network/raiden/files/3890339/pfs7_multiple_payments_2019_11_26.tar.gz)

**Comment by palango** [comment]
The PFS was restarting because of a crash at that time:
```
Nov 26 03:36:19 services-dev 59d9da4ad735[5820]: TypeError: can't compare offset-naive and offset-aware datetimes
```

The issue is tracked in https://github.com/raiden-network/raiden-services/issues/660
