### ISSUE TITLE
BF6 scenario fails with "no route available" error

### ISSUE THREAD

**Issue by czepluch** [raiden-network/raiden#5377]
### Intro
The BF6 scenario https://github.com/raiden-network/raiden/pull/5374 fails with "no route available" error 4 out of 5 times locally. 

Attached the logs from Dropbox since the file is too big: https://www.dropbox.com/s/og4ql1c23uczd1d/debug_logs.zip?dl=0

The scenario log files are only relevant until the "timestamp": "2019-11-26 12:29:39.456607", because I ended the scenario run after the payments started failing.

**Comment by palango** [comment]
This issue is quite old now and a lot of code changed since then. Please reopen if it happens again.
