### ISSUE TITLE
MFEE4 gets no route available from PFS

### ISSUE THREAD

**Issue by agatsoh** [raiden-network/raiden#5378]
## Problem Definition

Scenario in a nutshell:

node0: `0xfD0Ff3BB30109E39444d78D1f052e06f95028344`
node1: `0xf52bff8421F2bB95030E301a31b879a0044537Ea`
node2: `0xA9FfDa58534c6Df8321Ddfee41CA5627e42078cD`
node3: `0xDe0574Ab8FA684524Dd685b2a04B74AAbEC64D33`

```
{
  "task": "<TransferTask: {'from': 0, 'to': 3, 'amount': 500000000000000000, 'expected_http_status': 200}>",
  "event": "Task errored",
  "logger": "scenario_player.tasks.base",
  "level": "error",
  "timestamp": "2019-11-26 09:42:08.459842",
  "exception": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.7/site-packages/scenario_player/tasks/base.py\", line 74, in __call__\n    return self._run(*args, **kwargs)\n  File \"/usr/local/lib/python3.7/site-packages/scenario_player/tasks/api_base.py\", line 59, in _run\n    f'HTTP status code \"{resp.status_code}\" while fetching {url}. '\nscenario_player.exceptions.legacy.RESTAPIStatusMismatchError: HTTP status code \"409\" while fetching http://127.0.0.1:54989/api/v1/payments/0x62083c80353Df771426D209eF578619EE68D5C7A/0xDe0574Ab8FA684524Dd685b2a04B74AAbEC64D33. Expected 200: {\"errors\": \"Payment couldn't be completed because: there is no route available\"}"
}
```

What does the exception say:

1. `Payment couldn't be completed because: there is no route available`

2. Occurs while fetching 

`http://127.0.0.1:54989/api/v1/payments/0x62083c80353Df771426D209eF578619EE68D5C7A/0xDe0574Ab8FA684524Dd685b2a04B74AAbEC64D33`

where:
`0x62083c80353Df771426D209eF578619EE68D5C7A` : token address
`0xDe0574Ab8FA684524Dd685b2a04B74AAbEC64D33` : node3

3. `- transfer: {from: 0, to: 3, amount: 500_000_000_000_000_000, expected_http_status: 200}`

line 61

[mfee4_combined_fees_2019_11_26.tar.gz](https://github.com/raiden-network/raiden/files/3891997/mfee4_combined_fees_2019_11_26.tar.gz)

**Comment by karlb** [comment]
Same symptom as described in https://github.com/raiden-network/raiden/issues/5400#issuecomment-559720816, closing as duplicate.
