### ISSUE TITLE
Test with latest geth/parity

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden#5386]
We should check that Raiden works with the latest ethereum node version of parity/geth.

I tried to do this quickly in https://github.com/raiden-network/raiden/pull/5382, but that broke the tests.

**Comment by Dominik1999** [comment]
So we made sure that the latest geth and parity version work with Raiden. 
There is one test failing but that is not important and can be fixed after the release, see https://github.com/raiden-network/raiden/pull/5382#issuecomment-565431871

So we keep the issue open but not as a blocker for the Release
