### ISSUE TITLE
Make sure all BigInt’s are serialized as string

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/raiden#5395]
It is very common for C implementation to use a long or float as the storage for JSON's integers and fractions, this means the BigInt values used to represent Ethereum's int256 cannot be safely parsed by these implementations. The fix here is to always send the BigInts as string objects.

[one reference](https://github.com/esnme/ultrajson/blob/7d0f4fb7e911120fd09075049233b587936b0a65/lib/ultrajsondec.c#L127-L138)

**Comment by Dominik1999** [comment]
might be related to #5383
