### ISSUE TITLE
The current balance for the given token should be shown on the WebUI

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/raiden#5405]
## Abstract

When a user is opening a channel, the dialog bellow:

![image](https://user-images.githubusercontent.com/310139/69815552-53cef600-11d5-11ea-8bdb-cd23d4c0e1c0.png)

Should show along side the target channel balance, what is the current available balance for that given token.

Additionally it would be useful to validate the user input before the form is sent, instead of waiting for the server to reply an error, and provide visual feedback (e.g. change the color of the input field).

**Comment by manuelwedler** [comment]
Closing due to duplicate issue
See https://github.com/raiden-network/webui/issues/186
