### ISSUE TITLE
BF6 fails in Assert task for value mismatch for balance

### ISSUE THREAD

**Issue by agatsoh** [raiden-network/raiden#5412]
## Problem Definition

Scenario logs:

```
{
  "task": "<AssertTask: {'from': 6, 'to': 0, 'total_deposit': 1000000000000000000, 'balance': 500000000000000000}>",
  "event": "Task errored",
  "logger": "scenario_player.tasks.base",
  "level": "error",
  "timestamp": "2019-11-29 10:44:08.350764",
  "exception": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.7/site-packages/scenario_player/tasks/base.py\", line 74, in __call__\n    return self._run(*args, **kwargs)\n  File \"/usr/local/lib/python3.7/site-packages/scenario_player/tasks/api_base.py\", line 70, in _run\n    return self._process_response(response_dict)\n  File \"/usr/local/lib/python3.7/site-packages/scenario_player/tasks/channels.py\", line 168, in _process_response\n    f'Value mismatch for \"{field}\". '\nscenario_player.exceptions.legacy.ScenarioAssertionError: Value mismatch for \"balance\". Should: \"500000000000000000\" Is: \"499000000000000000\" Channel: {'token_address': '0x62083c80353Df771426D209eF578619EE68D5C7A', 'total_deposit': 1000000000000000000, 'total_withdraw': 0, 'reveal_timeout': 20, 'settle_timeout': 40, 'state': 'opened', 'partner_address': '0x7E99f2F4D10feA663E7F591a98664007802E9B27', 'balance': 499000000000000000, 'channel_identifier': 3894, 'token_network_address': '0xDa1fBc048f503635950058953f5c60FC1F564ee6'}"
}
```

what does the exception say:

1. Fails in the assert task

`- assert: {from: 6, to: 0, total_deposit: 1_000_000_000_000_000_000, balance: 500_000_000_000_000_000}`
line 131

2. `Value mismatch for \"balance\". Should: \"500000000000000000\" Is: \"499000000000000000\"`
Current asserted balance: 500_000_000_000_000_000
Actual balance          : 499_000_000_000_000_000

3. Shows current state of the channel

```
Channel: 
{
  "token_address": "0x62083c80353Df771426D209eF578619EE68D5C7A",
  "total_deposit": 1000000000000000000,
  "total_withdraw": 0,
  "reveal_timeout": 20,
  "settle_timeout": 40,
  "state": "opened",
  "partner_address": "0x7E99f2F4D10feA663E7F591a98664007802E9B27",
  "balance": 499000000000000000,
  "channel_identifier": 3894,
  "token_network_address": "0xDa1fBc048f503635950058953f5c60FC1F564ee6"
}
```

https://drive.google.com/file/d/1_Aku8gj2uBxGNrvTlpoomEbO82xd97ZK/view?usp=sharing

**Comment by agatsoh** [comment]
On 30thNovember the scenario this time fails at assert task:
`- assert: {from: 3, to: 0, total_deposit: 1_000_000_000_000_000_000, balance: 501_000_000_000_000_000}`
line 236

Attaching logs soon

**Comment by agatsoh** [comment]
On 1stDecember2019 the scenario fails of this assert task
`- assert: {from: 9, to: 0, total_deposit: 1_000_000_000_000_000_000, balance: 500_000_000_000_000_000}`
line 242

Attaching logs soon

**Comment by agatsoh** [comment]
On 4thDecember Assert task

```
{
  "task": "<AssertTask: {'from': 4, 'to': 0, 'total_deposit': 1000000000000000000, 'balance': 502000000000000000}>",
  "event": "Task errored",
  "logger": "scenario_player.tasks.base",
  "level": "error",
  "timestamp": "2019-12-04 09:29:44.676347",
  "exception": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.7/site-packages/scenario_player/tasks/base.py\", line 74, in __call__\n    return self._run(*args, **kwargs)\n  File \"/usr/local/lib/python3.7/site-packages/scenario_player/tasks/api_base.py\", line 70, in _run\n    return self._process_response(response_dict)\n  File \"/usr/local/lib/python3.7/site-packages/scenario_player/tasks/channels.py\", line 168, in _process_response\n    f'Value mismatch for \"{field}\". '\nscenario_player.exceptions.legacy.ScenarioAssertionError: Value mismatch for \"balance\". Should: \"502000000000000000\" Is: \"499000000000000000\" Channel: {'balance': 499000000000000000, 'partner_address': '0x1abbaBE0f812B8A8cd52Fc7fd6888e0054e19ee0', 'reveal_timeout': 20, 'token_address': '0x62083c80353Df771426D209eF578619EE68D5C7A', 'state': 'opened', 'total_withdraw': 0, 'settle_timeout': 40, 'channel_identifier': 4678, 'total_deposit': 1000000000000000000, 'token_network_address': '0xDa1fBc048f503635950058953f5c60FC1F564ee6'}"
}
```

1. Fails at the 

`- assert: {from: 4, to: 0, total_deposit: 1_000_000_000_000_000_000, balance: 502_000_000_000_000_000}`


2. `Value mismatch for \"balance\". Should: \"502000000000000000\" Is: \"499000000000000000\"`

`502_000_000_000_000_000` : Should
`499_000_000_000_000_000`: Is

3. Channel State at that point 

```
{
  "balance": 499000000000000000,
  "partner_address": "0x1abbaBE0f812B8A8cd52Fc7fd6888e0054e19ee0",
  "reveal_timeout": 20,
  "token_address": "0x62083c80353Df771426D209eF578619EE68D5C7A",
  "state": "opened",
  "total_withdraw": 0,
  "settle_timeout": 40,
  "channel_identifier": 4678,
  "total_deposit": 1000000000000000000,
  "token_network_address": "0xDa1fBc048f503635950058953f5c60FC1F564ee6"
}
```


[bf6_stress_hub_node_2019_12_04.tar.gz](https://github.com/raiden-network/raiden/files/3921687/bf6_stress_hub_node_2019_12_04.tar.gz)

**Comment by Dominik1999** [comment]
Happend again yesterday evening 

``` 
Value mismatch for \"balance\". Should: \"500000000000000000\" Is: \"497000000000000000\" Channel: {'total_withdraw': 0, 'state': 'opened', 'partner_address': '0xaAA05D5128b965eAe086989B835E5D4628A93ffF', 'reveal_timeout': 20, 'channel_identifier': 4772, 'token_address': '0x62083c80353Df771426D209eF578619EE68D5C7A', 'balance': 497000000000000000, 'settle_timeout': 40, 'token_network_address': '0xDa1fBc048f503635950058953f5c60FC1F564ee6', 'total_deposit': 1000000000000000000}"}
``` 

- [SP logs ](http://68.183.70.168:8000/scenario-player/scenarios/bf6_stress_hub_node/scenario-player-run_bf6_stress_hub_node_2019-12-04T23%3A47%3A36.log)
- [Node 0](http://68.183.70.168:8000/scenario-player/scenarios/bf6_stress_hub_node/node_8_000/)
- [Node 1](http://68.183.70.168:8000/scenario-player/scenarios/bf6_stress_hub_node/node_8_001/)
- [Node 2](http://68.183.70.168:8000/scenario-player/scenarios/bf6_stress_hub_node/node_8_002/)
- [Node 3](http://68.183.70.168:8000/scenario-player/scenarios/bf6_stress_hub_node/node_8_003/)
- [Node 4](http://68.183.70.168:8000/scenario-player/scenarios/bf6_stress_hub_node/node_8_004/)
- [Node 5](http://68.183.70.168:8000/scenario-player/scenarios/bf6_stress_hub_node/node_8_005/)
- [Node 6](http://68.183.70.168:8000/scenario-player/scenarios/bf6_stress_hub_node/node_8_006/)- - [Node 7](http://68.183.70.168:8000/scenario-player/scenarios/bf6_stress_hub_node/node_8_007/)
- [Node 8](http://68.183.70.168:8000/scenario-player/scenarios/bf6_stress_hub_node/node_8_008/)
- [Node 9](http://68.183.70.168:8000/scenario-player/scenarios/bf6_stress_hub_node/node_8_009/)-

**Comment by Dominik1999** [comment]
another issue describing that fail https://github.com/raiden-network/raiden-services/issues/675

**Comment by Dominik1999** [comment]
Is now tracked in #5463
