### ISSUE TITLE
[META] Find a way to reproduce our bugs more reliable and efficient than with the Scenario Player

### ISSUE THREAD

**Issue by Dominik1999** [raiden-network/raiden#5413]
## The scenario player is too inefficient and unreliable for reproducing bugs

Our last three major bug categories - presence bug, performance issues, general "No route found", we found by running scenarios on the scenario player. However, it is hard to reproduce any bugs and test bug fixes with the current scenario player setup. Running scenarios is simply too and complex slow to be used as a tool for bug fixing.

## Potential solutions
We need to find better and faster ways to reliably reproduce bugs than running scenarios. 

Potential workarounds:
- Change scenario player to be able to run 10 scenarios in parallel locally
- Having a group of 10 people, being able to run scenarios ad hoc and report bugs and provide logs
- ... [add other potential workarounds here]

Long term solution:
- Replace the scenario player by some sort of cheaper and faster integration test
- Requirements: 
- - ... [add requirements here]

**Comment by christianbrb** [comment]
@nlsdfnbch has got a branch in the scenario player which runs the scenarios in parallel. Testing had started, but we’ve been still finding issues and therefore where holding it back

**Comment by Dominik1999** [comment]
- Run scenarios in parallel

**Comment by Dominik1999** [comment]
@Dominik1999 creates issues for this sprint

**Comment by Dominik1999** [comment]
Alternatives 1, 3 and 4 are implemented. So closing this now
