### ISSUE TITLE
PFS6 Scenario PFS gives No route available 

### ISSUE THREAD

**Issue by agatsoh** [raiden-network/raiden#5415]
## Problem Definition

Scenario in a nutshell

node0: `0x41bee2A55BE225C626480F6F3DB020fFc84B492f`
node1: `0x22Dbd196688B894a94dF3f6aE664F419DAC89fBB`
node2: `0xB11368265e98e609b8E6625bE56CbfC7c26E1986`
node3: `0xf36639eE2D1F7c5Ca44934544aC6e90B9DA1254D`

```
{
  "task": "<TransferTask: {'from': 3, 'to': 0, 'amount': 1000000000000000, 'expected_http_status': 200}>",
  "event": "Task errored",
  "logger": "scenario_player.tasks.base",
  "level": "error",
  "timestamp": "2019-12-01 02:50:03.556105",
  "exception": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.7/site-packages/scenario_player/tasks/base.py\", line 74, in __call__\n    return self._run(*args, **kwargs)\n  File \"/usr/local/lib/python3.7/site-packages/scenario_player/tasks/api_base.py\", line 59, in _run\n    f'HTTP status code \"{resp.status_code}\" while fetching {url}. '\nscenario_player.exceptions.legacy.RESTAPIStatusMismatchError: HTTP status code \"409\" while fetching http://127.0.0.1:37689/api/v1/payments/0x62083c80353Df771426D209eF578619EE68D5C7A/0x41bee2A55BE225C626480F6F3DB020fFc84B492f. Expected 200: {\"errors\": \"Payment couldn't be completed because: there is no route available\"}"
}
```

what does the exception say

1. **Payment couldn't be completed because: there is no route available**

2. Occurs while fetching 

`http://127.0.0.1:37689/api/v1/payments/0x62083c80353Df771426D209eF578619EE68D5C7A/0x41bee2A55BE225C626480F6F3DB020fFc84B492f`
where
`0x62083c80353Df771426D209eF578619EE68D5C7A`: token address 
`0x41bee2A55BE225C626480F6F3DB020fFc84B492f`: node3 address 

3. Fails at Transfer task
`- transfer: {from: 3, to: 0, amount: 1_000_000_000_000_000, expected_http_status: 200}`

[pfs6_simple_path_rewards_2019_12_01.tar.gz](https://github.com/raiden-network/raiden/files/3911283/pfs6_simple_path_rewards_2019_12_01.tar.gz)

**Comment by czepluch** [comment]
Happened again in BF5 on 13/12/2019:

Logs:

- [Scenario log](http://68.183.70.168:8000/scenario-player/scenarios/bf5_join_and_leave/scenario-player-run_bf5_join_and_leave_2019-12-13T22%3A57%3A07.log)
- [node0](http://68.183.70.168:8000/scenario-player/scenarios/bf5_join_and_leave/node_27_000/)
- [node1](http://68.183.70.168:8000/scenario-player/scenarios/bf5_join_and_leave/node_27_001/)
- [node2](http://68.183.70.168:8000/scenario-player/scenarios/bf5_join_and_leave/node_27_002/)
- [node3](http://68.183.70.168:8000/scenario-player/scenarios/bf5_join_and_leave/node_27_003/)

**Comment by palango** [comment]
This issue is quite old now and a lot of code changed since then. Please reopen if it happens again.
