### ISSUE TITLE
Find a way to reproduce our bugs more reliable and efficient - Solution 2: Run with two different funding accounts

### ISSUE THREAD

**Issue by Dominik1999** [raiden-network/raiden#5418]
## The scenario player is too inefficient and unreliable for reproducing bugs

Our last three major bug categories - presence bug, performance issues, general "No route found", we found by running scenarios on the scenario player. However, it is hard to reproduce any bugs and test bug fixes with the current scenario player setup. Running scenarios is simply too complex and slow to be used as a tool for bug fixing.

## Possible solution 2 to that problem
We try to run the Scenario Player with two different funding accounts.

**Comment by czepluch** [comment]
I am quite sure we have been doing this since we started to have scenarios running on two different servers. Otherwise we would run into problems with wrong nonces. @nlsdfnbch can you verify that this is correct?

**Comment by rakanalh** [comment]
Yea using two funding accounts works. See: https://github.com/raiden-network/raiden/issues/5417#issuecomment-561072220

Closing.
