### ISSUE TITLE
MFEE3  gets No route available from the PFS

### ISSUE THREAD

**Issue by agatsoh** [raiden-network/raiden#5427]
## Problem Definition

Scenario in a nutshell:
node0 : `0xE24050FDff8917735475859D4bFfd332ca8c6C17`
node1 : `0x6Af8038aDF842dE8a3202F7af6824b0Da7625D11`
node2 : `0xD0118734834bA5eC73c2b86A2E3Dbd5568fE4a25`

```
{
  "task": "<TransferTask: {'from': 0, 'to': 2, 'amount': 500000000000000000, 'expected_http_status': 200}>",
  "event": "Task errored",
  "logger": "scenario_player.tasks.base",
  "level": "error",
  "timestamp": "2019-12-03 09:32:51.803893",
  "exception": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.7/site-packages/scenario_player/tasks/base.py\", line 74, in __call__\n    return self._run(*args, **kwargs)\n  File \"/usr/local/lib/python3.7/site-packages/scenario_player/tasks/api_base.py\", line 59, in _run\n    f'HTTP status code \"{resp.status_code}\" while fetching {url}. '\nscenario_player.exceptions.legacy.RESTAPIStatusMismatchError: HTTP status code \"409\" while fetching http://127.0.0.1:37185/api/v1/payments/0x62083c80353Df771426D209eF578619EE68D5C7A/0xD0118734834bA5eC73c2b86A2E3Dbd5568fE4a25. Expected 200: {\"errors\": \"Payment couldn't be completed because: there is no route available\"}"
}
```

What the exception say:

1. `Payment couldn't be completed because: there is no route available`

2. Occurs while fetching 
`http://127.0.0.1:37185/api/v1/payments/0x62083c80353Df771426D209eF578619EE68D5C7A/0xD0118734834bA5eC73c2b86A2E3Dbd5568fE4a25`
where 

`0x62083c80353Df771426D209eF578619EE68D5C7A` : token address
`0xD0118734834bA5eC73c2b86A2E3Dbd5568fE4a25` : node2 address

3. Fails at 

`- transfer: {from: 0, to: 2, amount: 500_000_000_000_000_000, expected_http_status: 200}`
[mfee3_only_imbalance_fees_2019_12_03.tar.gz](https://github.com/raiden-network/raiden/files/3916862/mfee3_only_imbalance_fees_2019_12_03.tar.gz)

**Comment by palango** [comment]
In the logs I only see 
```
Dec 03 09:32:51 services-dev b1fd6d4085a8[5820]: {"error": "NoRouteFound('Source does not have a channel with sufficient capacity')", "details": {"from_": "0xE24050FDff8917735475859D4bFfd332ca8c6C17", "to": "0xD0118734834bA5eC73c2b86A2E3Dbd5568fE4a25", "value": 500000000000000000}, "message": "Source does not have a channel with sufficient capacity", "event": "Error while handling request", "level": "warning", "logger": "pathfinding_service.api", "timestamp": "2019-12-03 09:32:51.609993"}
```

**Comment by palango** [comment]
This issue is quite old now and a lot of code changed since then. Please reopen if it happens again.
