### ISSUE TITLE
Include MatrixPresenceCheck in ConnectionManager

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/raiden#5453]
## Abstract

Currently, the ConnectionManager opens channels to nodes being offline.

## Motivation

It would drastically improve the UX for the WebUI and therefore for the standard user we are targeting with the Wizard and the WebUI, if nodes the ConnectionManager is connecting to would be online to directly make payments after the channels have been created and funded.

## Specification

@hackaugusto Could you help us making a spec? If it is not too difficult somebody from the solutions team would implement it.

## Backwards Compatibility

Should be backward compatible as nodes already send their presence information to the PFS.

CC @kelsos @manuelwedler @Dominik1999

**Comment by palango** [comment]
Tracked by https://github.com/raiden-network/raiden/issues/5583

**Comment by christianbrb** [comment]
Great, thanks for the implementation :)
