### ISSUE TITLE
Get info about matrix purge script and reestablish 

### ISSUE THREAD

**Issue by Dominik1999** [raiden-network/raiden#5462]
check with Ulo

**Comment by nlsdfnbch** [comment]
Also, point me towards it so I can convert it to ansible job - thx!

**Comment by palango** [comment]
The script is here: https://github.com/raiden-network/raiden-service-bundle/tree/master/purge

It should already run every day: https://github.com/raiden-network/raiden-service-bundle/blob/master/docker-compose.yml#L127

Can we first check what data is taking the space. Is it the DB or logfiles?

**Comment by palango** [comment]
Should be fixed by https://github.com/raiden-network/raiden-service-bundle/pull/75

**Comment by Dominik1999** [comment]
@ulope can we close this issue?

From my side, we can if the purge script is enabled and runs every day
