### ISSUE TITLE
Error performing REST-API call / Sudden Node Death

### ISSUE THREAD

**Issue by agatsoh** [raiden-network/raiden#5472]
## Problem Definition

```
{
  "task": "<TransferTask: {'from': 0, 'to': 3, 'amount': 1000000000000000, 'expected_http_status': 200}>",
  "event": "Task errored",
  "logger": "scenario_player.tasks.base",
  "level": "error",
  "timestamp": "2019-12-10 09:27:10.193048",
  "exception": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.7/site-packages/urllib3/connection.py\", line 160, in _new_conn\n    (self._dns_host, self.port), self.timeout, **extra_kw)\n  File \"/usr/local/lib/python3.7/site-packages/urllib3/util/connection.py\", line 80, in create_connection\n    raise err\n  File \"/usr/local/lib/python3.7/site-packages/urllib3/util/connection.py\", line 70, in create_connection\n    sock.connect(sa)\n  File \"/usr/local/lib/python3.7/site-packages/gevent/_socket3.py\", line 335, in connect\n    raise error(err, strerror(err))\nConnectionRefusedError: [Errno 111] Connection refused\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py\", line 603, in urlopen\n    chunked=chunked)\n  File \"/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py\", line 355, in _make_request\n    conn.request(method, url, **httplib_request_kw)\n  File \"/usr/local/lib/python3.7/http/client.py\", line 1229, in request\n    self._send_request(method, url, body, headers, encode_chunked)\n  File \"/usr/local/lib/python3.7/http/client.py\", line 1275, in _send_request\n    self.endheaders(body, encode_chunked=encode_chunked)\n  File \"/usr/local/lib/python3.7/http/client.py\", line 1224, in endheaders\n    self._send_output(message_body, encode_chunked=encode_chunked)\n  File \"/usr/local/lib/python3.7/http/client.py\", line 1016, in _send_output\n    self.send(msg)\n  File \"/usr/local/lib/python3.7/http/client.py\", line 956, in send\n    self.connect()\n  File \"/usr/local/lib/python3.7/site-packages/urllib3/connection.py\", line 183, in connect\n    conn = self._new_conn()\n  File \"/usr/local/lib/python3.7/site-packages/urllib3/connection.py\", line 169, in _new_conn\n    self, \"Failed to establish a new connection: %s\" % e)\nurllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fd87ce34518>: Failed to establish a new connection: [Errno 111] Connection refused\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.7/site-packages/requests/adapters.py\", line 449, in send\n    timeout=timeout\n  File \"/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py\", line 641, in urlopen\n    _stacktrace=sys.exc_info()[2])\n  File \"/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py\", line 399, in increment\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\nurllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=34477): Max retries exceeded with url: /api/v1/payments/0x62083c80353Df771426D209eF578619EE68D5C7A/0x94E968d8c6De67288755A9F9a9b901B2a4b8cd01 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd87ce34518>: Failed to establish a new connection: [Errno 111] Connection refused'))\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.7/site-packages/scenario_player/tasks/api_base.py\", line 51, in _run\n    method=self._method, url=url, json=self._request_params, timeout=self._timeout\n  File \"/usr/local/lib/python3.7/site-packages/requests/sessions.py\", line 533, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"/usr/local/lib/python3.7/site-packages/requests/sessions.py\", line 646, in send\n    r = adapter.send(request, **kwargs)\n  File \"/usr/local/lib/python3.7/site-packages/requests/adapters.py\", line 516, in send\n    raise ConnectionError(e, request=request)\nrequests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=34477): Max retries exceeded with url: /api/v1/payments/0x62083c80353Df771426D209eF578619EE68D5C7A/0x94E968d8c6De67288755A9F9a9b901B2a4b8cd01 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd87ce34518>: Failed to establish a new connection: [Errno 111] Connection refused'))\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.7/site-packages/scenario_player/tasks/base.py\", line 74, in __call__\n    return self._run(*args, **kwargs)\n  File \"/usr/local/lib/python3.7/site-packages/scenario_player/tasks/api_base.py\", line 56, in _run\n    raise RESTAPIError(f\"Error performing REST-API call: {self._name}\") from ex\nscenario_player.exceptions.legacy.RESTAPIError: Error performing REST-API call: transfer"
}
```

1.  **Error performing REST-API call: transfer**

2. Fails at line 82

`- transfer: {from: 0, to: 3, amount: 1_000_000_000_000_000, expected_http_status: 200}`

3. while calling API
`/api/v1/payments/0x62083c80353Df771426D209eF578619EE68D5C7A/0x94E968d8c6De67288755A9F9a9b901B2a4b8cd01`

[pfs8_mediator_goes_offline_2019_12_10.tar.gz](https://github.com/raiden-network/raiden/files/3944540/pfs8_mediator_goes_offline_2019_12_10.tar.gz)

**Comment by nlsdfnbch** [comment]
The following investigations took place:

I checked that the transport servers were available during the time of the node shutdown; them being unavailable at the time of execution was cause for sudden node kills in the past. The transport servers were up.

@paul and I checked the raiden service logs at the time of failure but found no issue

I checked the syslog logs, but found no irregularities at the time of execution

I checked the metrics of the node - neither CPU nor memory were anywhere near their respective max capacities.

**Comment by Dominik1999** [comment]
it happened also tonight in pfs8

- [SP Logs](http://68.183.70.168:8000/scenario-player/scenarios/pfs8_mediator_goes_offline/scenario-player-run_pfs8_mediator_goes_offline_2019-12-11T04%3A16%3A22.log)
- [Node0](http://68.183.70.168:8000/scenario-player/scenarios/pfs8_mediator_goes_offline/node_57_000/)
- [Node1](http://68.183.70.168:8000/scenario-player/scenarios/pfs8_mediator_goes_offline/node_57_001/)
- [Node2](http://68.183.70.168:8000/scenario-player/scenarios/pfs8_mediator_goes_offline/node_57_002/)
- [Node3](http://68.183.70.168:8000/scenario-player/scenarios/pfs8_mediator_goes_offline/node_57_003/)
- [Node4](http://68.183.70.168:8000/scenario-player/scenarios/pfs8_mediator_goes_offline/node_57_004/)

**Comment by czepluch** [comment]
MS3 also seems to fail like this from last night.

Logs: 
- [Scenario log](http://139.59.211.171:8000/scenario-player/scenarios/ms3_simple_monitoring/scenario-player-run_ms3_simple_monitoring_2019-12-12T02%3A07%3A35.log)
- [node0](http://139.59.211.171:8000/scenario-player/scenarios/ms3_simple_monitoring/node_66_000/)
- [node1](http://139.59.211.171:8000/scenario-player/scenarios/ms3_simple_monitoring/node_66_001/)

**Comment by czepluch** [comment]
Same goes for MS2:

Logs:
- [Scenario log](http://68.183.70.168:8000/scenario-player/scenarios/ms2_simple_monitoring/scenario-player-run_ms2_simple_monitoring_2019-12-12T01%3A43%3A49.log)
- [node0](http://68.183.70.168:8000/scenario-player/scenarios/ms2_simple_monitoring/node_7_000/)
- [node1](http://68.183.70.168:8000/scenario-player/scenarios/ms2_simple_monitoring/node_7_001/)

**Comment by czepluch** [comment]
MS4 from today also fails when performing close channel REST-API call:

Logs: 
- [Scenario log](http://139.59.211.171:8000/scenario-player/scenarios/ms4_udc_too_low/scenario-player-run_ms4_udc_too_low_2019-12-13T03%3A31%3A55.log)
- [node0](http://139.59.211.171:8000/scenario-player/scenarios/ms4_udc_too_low/node_67_000/)
- [node1](http://139.59.211.171:8000/scenario-player/scenarios/ms4_udc_too_low/node_67_001/)

**Comment by czepluch** [comment]
BF6 also fails like this. But there is updated logging with more info than the previous days.

Logs:
- [Scenario log](http://68.183.70.168:8000/scenario-player/scenarios/bf6_stress_hub_node/scenario-player-run_bf6_stress_hub_node_2019-12-12T22%3A37%3A23.log)
- [node0](http://68.183.70.168:8000/scenario-player/scenarios/bf6_stress_hub_node/node_18_000/)
- [node1](http://68.183.70.168:8000/scenario-player/scenarios/bf6_stress_hub_node/node_18_001/)
- [node2](http://68.183.70.168:8000/scenario-player/scenarios/bf6_stress_hub_node/node_18_002/)
- [node3](http://68.183.70.168:8000/scenario-player/scenarios/bf6_stress_hub_node/node_18_003/)
- [node4](http://68.183.70.168:8000/scenario-player/scenarios/bf6_stress_hub_node/node_18_004/)
- [node5](http://68.183.70.168:8000/scenario-player/scenarios/bf6_stress_hub_node/node_18_005/)
- [node6](http://68.183.70.168:8000/scenario-player/scenarios/bf6_stress_hub_node/node_18_006/)
- [node7](http://68.183.70.168:8000/scenario-player/scenarios/bf6_stress_hub_node/node_18_007/)
- [node8](http://68.183.70.168:8000/scenario-player/scenarios/bf6_stress_hub_node/node_18_008/)
- [node9](http://68.183.70.168:8000/scenario-player/scenarios/bf6_stress_hub_node/node_18_009/)

**Comment by ulope** [comment]
Ok the new logging worked:
```
Raiden node 8 died with non-zero exit status: -9
```

`-9` is `SIGKILL`. This means something actively killed the node. The only thing that I can think of right now that would do this automatically is the OOM (out of memory killer). 

Nothing is reported in the syslog, which normally should have an entry if something was killed by the OOM (but since the SP run happens inside a docker container I don't know what the expected behaviour should be).

However the monitoring shows we never exceeded ~30% RAM usage on the system. The monitoring only samples data every minute though, that means there could be a very sharp memory usage spike that then lead to the node being killed which would be invisible on the monitoring.

**Comment by nlsdfnbch** [comment]
If the OOM killed a container, that should show up in the syslogs. However, we can always limit the memory used for the container we run.
If we do not constrain the memory (as is the case atm), the OOM killer could possibly have killed the container. But as I said - it should still show up in the sys logs.

**Comment by czepluch** [comment]
Happened again on 13th of dec for BF6 with `RESTAPIError: Error performing REST-API call: assert`.

Logs:

- [Scenario logs](http://68.183.70.168:8000/scenario-player/scenarios/bf6_stress_hub_node/scenario-player-run_bf6_stress_hub_node_2019-12-13T23%3A28%3A24.log)
- [node0](http://68.183.70.168:8000/scenario-player/scenarios/bf6_stress_hub_node/node_19_000/)
- [node1](http://68.183.70.168:8000/scenario-player/scenarios/bf6_stress_hub_node/node_19_001/)
- [node2](http://68.183.70.168:8000/scenario-player/scenarios/bf6_stress_hub_node/node_19_002/)
- [node3](http://68.183.70.168:8000/scenario-player/scenarios/bf6_stress_hub_node/node_19_003/)
- [node4](http://68.183.70.168:8000/scenario-player/scenarios/bf6_stress_hub_node/node_19_004/)
- [node5](http://68.183.70.168:8000/scenario-player/scenarios/bf6_stress_hub_node/node_19_005/)
- [node6](http://68.183.70.168:8000/scenario-player/scenarios/bf6_stress_hub_node/node_19_006/)
- [node7](http://68.183.70.168:8000/scenario-player/scenarios/bf6_stress_hub_node/node_19_007/)
- [node8](http://68.183.70.168:8000/scenario-player/scenarios/bf6_stress_hub_node/node_19_008/)
- [node9](http://68.183.70.168:8000/scenario-player/scenarios/bf6_stress_hub_node/node_19_009/)

**Comment by czepluch** [comment]
Looks like something like this also happened on 15th of December for BF1 where it fails with: 
```
"message": "HTTP status code \"500\" while fetching http://127.0.0.1:36201/api/v1/channels/0x62083c80353Df771426D209eF578619EE68D5C7A/0xae8037d15CE130D298611a937c1142f9c3A22189. Expected 200: Internal Server Error
```

Logs:
- [Scenario logs](http://139.59.211.171:8000/scenario-player/scenarios/bf1_basic_functionality/scenario-player-run_bf1_basic_functionality_2019-12-14T22%3A03%3A03.log)
- [node0](http://139.59.211.171:8000/scenario-player/scenarios/bf1_basic_functionality/node_15_000/)
- [node1](http://139.59.211.171:8000/scenario-player/scenarios/bf1_basic_functionality/node_15_001/)
- [node2](http://139.59.211.171:8000/scenario-player/scenarios/bf1_basic_functionality/node_15_002/)
- [node3](http://139.59.211.171:8000/scenario-player/scenarios/bf1_basic_functionality/node_15_003/)
- [node4](http://139.59.211.171:8000/scenario-player/scenarios/bf1_basic_functionality/node_15_004/)

**Comment by czepluch** [comment]
Also happened to BF6 on 15th of December with `RESTAPIError: Error performing REST-API call: assert`

Logs: 
- [Scenario log](http://68.183.70.168:8000/scenario-player/scenarios/bf6_stress_hub_node/scenario-player-run_bf6_stress_hub_node_2019-12-14T23%3A15%3A10.log)
- [node0](http://68.183.70.168:8000/scenario-player/scenarios/bf6_stress_hub_node/node_20_000/)
- [node1](http://68.183.70.168:8000/scenario-player/scenarios/bf6_stress_hub_node/node_20_001/)
- [node2](http://68.183.70.168:8000/scenario-player/scenarios/bf6_stress_hub_node/node_20_002/)
- [node3](http://68.183.70.168:8000/scenario-player/scenarios/bf6_stress_hub_node/node_20_003/)
- [node4](http://68.183.70.168:8000/scenario-player/scenarios/bf6_stress_hub_node/node_20_004/)
- [node5](http://68.183.70.168:8000/scenario-player/scenarios/bf6_stress_hub_node/node_20_005/)
- [node6](http://68.183.70.168:8000/scenario-player/scenarios/bf6_stress_hub_node/node_20_006/)
- [node7](http://68.183.70.168:8000/scenario-player/scenarios/bf6_stress_hub_node/node_20_007/)
- [node8](http://68.183.70.168:8000/scenario-player/scenarios/bf6_stress_hub_node/node_20_008/)
- [node9](http://68.183.70.168:8000/scenario-player/scenarios/bf6_stress_hub_node/node_20_009/)

**Comment by palango** [comment]
https://github.com/raiden-network/raiden/issues/5472#issuecomment-566002792 is issue https://github.com/raiden-network/raiden/issues/5498

**Comment by czepluch** [comment]
Happened in ms4 on 15th of december with `Error performing REST-API call: close_channel`

Logs:
- [Scenario logs](http://139.59.211.171:8000/scenario-player/scenarios/ms4_udc_too_low/scenario-player-run_ms4_udc_too_low_2019-12-15T03%3A01%3A10.log)
- [node0](http://139.59.211.171:8000/scenario-player/scenarios/ms4_udc_too_low/node_69_000/)
- [node1](http://139.59.211.171:8000/scenario-player/scenarios/ms4_udc_too_low/node_69_001/)

**Comment by czepluch** [comment]
Happened in BF6 on 16th of december with `RESTAPIError: Error performing REST-API call: assert`

Logs:
- [Scenario log](http://68.183.70.168:8000/scenario-player/scenarios/bf6_stress_hub_node/scenario-player-run_bf6_stress_hub_node_2019-12-15T23%3A18%3A54.log)
- [node0](http://68.183.70.168:8000/scenario-player/scenarios/bf6_stress_hub_node/node_21_000/)
- [node1](http://68.183.70.168:8000/scenario-player/scenarios/bf6_stress_hub_node/node_21_001/)
- [node2](http://68.183.70.168:8000/scenario-player/scenarios/bf6_stress_hub_node/node_21_002/)
- [node3](http://68.183.70.168:8000/scenario-player/scenarios/bf6_stress_hub_node/node_21_003/)
- [node4](http://68.183.70.168:8000/scenario-player/scenarios/bf6_stress_hub_node/node_21_004/)
- [node5](http://68.183.70.168:8000/scenario-player/scenarios/bf6_stress_hub_node/node_21_005/)
- [node6](http://68.183.70.168:8000/scenario-player/scenarios/bf6_stress_hub_node/node_21_006/)
- [node7](http://68.183.70.168:8000/scenario-player/scenarios/bf6_stress_hub_node/node_21_007/)
- [node8](http://68.183.70.168:8000/scenario-player/scenarios/bf6_stress_hub_node/node_21_008/)
- [node9](http://68.183.70.168:8000/scenario-player/scenarios/bf6_stress_hub_node/node_21_009/)

**Comment by Dominik1999** [comment]
wow that happens a lot ...

**Comment by Dominik1999** [comment]
Planning - We thought about the following steps to approach that bug:
- [ ] Everyone gets access to the Scenario Player Servers (@nlsdfnbch got our ssh keys and will grant access)
- [ ] Check all logs on the server why we see `SIGKILL`
- [ ] Check how docker reacts to `SIGKILL`
- [ ] Looks into the Scenario Player Code when a node gets killed
- [ ] Everyone runs a bf1 scenario and we try to reproduce it locally

**Comment by czepluch** [comment]
BF7 failed like this on 17th of Dec too

Logs:
- [Scenario log](http://68.183.70.168:8000/scenario-player/scenarios/bf7_long_path/scenario-player-run_bf7_long_path_2019-12-16T22%3A24%3A04.log)
- [node0](http://68.183.70.168:8000/scenario-player/scenarios/bf7_long_path/node_12_000/)
- [node1](http://68.183.70.168:8000/scenario-player/scenarios/bf7_long_path/node_12_001/)
- [node2](http://68.183.70.168:8000/scenario-player/scenarios/bf7_long_path/node_12_002/)
- [node3](http://68.183.70.168:8000/scenario-player/scenarios/bf7_long_path/node_12_003/)
- [node4](http://68.183.70.168:8000/scenario-player/scenarios/bf7_long_path/node_12_004/)
- [node5](http://68.183.70.168:8000/scenario-player/scenarios/bf7_long_path/node_12_005/)
- [node6](http://68.183.70.168:8000/scenario-player/scenarios/bf7_long_path/node_12_006/)
- [node7](http://68.183.70.168:8000/scenario-player/scenarios/bf7_long_path/node_12_007/)
- [node8](http://68.183.70.168:8000/scenario-player/scenarios/bf7_long_path/node_12_008/)
- [node9](http://68.183.70.168:8000/scenario-player/scenarios/bf7_long_path/node_12_009/)
- [node10](http://68.183.70.168:8000/scenario-player/scenarios/bf7_long_path/node_12_010/)
- [node11](http://68.183.70.168:8000/scenario-player/scenarios/bf7_long_path/node_12_011/)
- [node12](http://68.183.70.168:8000/scenario-player/scenarios/bf7_long_path/node_12_012/)
- [node13](http://68.183.70.168:8000/scenario-player/scenarios/bf7_long_path/node_12_013/)
- [node14](http://68.183.70.168:8000/scenario-player/scenarios/bf7_long_path/node_12_014/)

**Comment by czepluch** [comment]
MS2 failed like this on dec 17th

Logs:
- [Scenario log](http://68.183.70.168:8000/scenario-player/scenarios/ms2_simple_monitoring/scenario-player-run_ms2_simple_monitoring_2019-12-16T23%3A22%3A52.log)
- [node0](http://68.183.70.168:8000/scenario-player/scenarios/ms2_simple_monitoring/node_12_000/)
- [node1](http://68.183.70.168:8000/scenario-player/scenarios/ms2_simple_monitoring/node_12_001/)

**Comment by czepluch** [comment]
BF6 failed like this on dev 17th with `RESTAPIError: Error performing REST-API call: assert`

Logs:
- [Scenario log](http://68.183.70.168:8000/scenario-player/scenarios/bf6_stress_hub_node/scenario-player-run_bf6_stress_hub_node_2019-12-16T22%3A07%3A16.log)
- [node0](http://68.183.70.168:8000/scenario-player/scenarios/bf6_stress_hub_node/node_22_000/)
- [node1](http://68.183.70.168:8000/scenario-player/scenarios/bf6_stress_hub_node/node_22_001/)
- [node2](http://68.183.70.168:8000/scenario-player/scenarios/bf6_stress_hub_node/node_22_002/)
- [node3](http://68.183.70.168:8000/scenario-player/scenarios/bf6_stress_hub_node/node_22_003/)
- [node4](http://68.183.70.168:8000/scenario-player/scenarios/bf6_stress_hub_node/node_22_004/)
- [node5](http://68.183.70.168:8000/scenario-player/scenarios/bf6_stress_hub_node/node_22_005/)
- [node6](http://68.183.70.168:8000/scenario-player/scenarios/bf6_stress_hub_node/node_22_006/)
- [node7](http://68.183.70.168:8000/scenario-player/scenarios/bf6_stress_hub_node/node_22_007/)
- [node8](http://68.183.70.168:8000/scenario-player/scenarios/bf6_stress_hub_node/node_22_008/)
- [node9](http://68.183.70.168:8000/scenario-player/scenarios/bf6_stress_hub_node/node_22_009/)

**Comment by Dominik1999** [comment]
- [ ] Nils to merge a PR from @hackaugusto 
- [ ] either no route found or node dies because of matrixsynctimeout -> SP kills it 
- [ ] Raiden waits for every http request to finish, so the Scenario Player kills it

**Comment by czepluch** [comment]
BF6 also failed on dec 18th

Logs:
- [Scenario log](http://68.183.70.168:8000/scenario-player/scenarios/bf6_stress_hub_node/scenario-player-run_bf6_stress_hub_node_2019-12-17T23%3A50%3A50.log)
- [node0](http://68.183.70.168:8000/scenario-player/scenarios/bf6_stress_hub_node/node_23_000/)
- [node1](http://68.183.70.168:8000/scenario-player/scenarios/bf6_stress_hub_node/node_23_001/)
- [node2](http://68.183.70.168:8000/scenario-player/scenarios/bf6_stress_hub_node/node_23_002/)
- [node3](http://68.183.70.168:8000/scenario-player/scenarios/bf6_stress_hub_node/node_23_003/)
- [node4](http://68.183.70.168:8000/scenario-player/scenarios/bf6_stress_hub_node/node_23_004/)
- [node5](http://68.183.70.168:8000/scenario-player/scenarios/bf6_stress_hub_node/node_23_005/)
- [node6](http://68.183.70.168:8000/scenario-player/scenarios/bf6_stress_hub_node/node_23_006/)
- [node7](http://68.183.70.168:8000/scenario-player/scenarios/bf6_stress_hub_node/node_23_007/)
- [node8](http://68.183.70.168:8000/scenario-player/scenarios/bf6_stress_hub_node/node_23_008/)
- [node9](http://68.183.70.168:8000/scenario-player/scenarios/bf6_stress_hub_node/node_23_009/)

**Comment by Dominik1999** [comment]
Actually the scenario failed due to #5498 you can see that in 

`FATAL: Processing Matrix response took 28.34271264076233s, poll timeout is 20s.` in the stdout of node0
