### ISSUE TITLE
error message from the PFS should be added to the error of the transfers

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/raiden#5481]
## Abstract

Add the message from the path finding service to the error returned in the rest api, this is important to aid debugging and give proper feedback to the user.

**Comment by rakanalh** [comment]
I checked this issue and what i found is that we already return the reason of the payment failure in the rest API:

https://github.com/raiden-network/raiden/blob/140c3e7b1b99844c6537f03717233fecff3ae695/raiden/api/rest.py#L1095-L1101

That is, if the PFS returns an error, this error will be added to `EventPaymentSentFailed` that is in turn set as the payment result's value.

https://github.com/raiden-network/raiden/blob/140c3e7b1b99844c6537f03717233fecff3ae695/raiden/raiden_service.py#L1364-L1373
