### ISSUE TITLE
API endpoint for UDC contract to deposit and withdraw RDN tokens 

### ISSUE THREAD

**Issue by Dominik1999** [raiden-network/raiden#5497]
We need an API endpoint to be able to deposit RDN tokens (or services tokens on the testnet) into the UDC. 

This is related to #5407

**Comment by manuelwedler** [comment]
I'm taking this over now to provide a better UX. After a discussion with @karlb, we decided to have 3 API calls: deposit, plan withdraw and withdraw.

For this it makes sense to have a new endpoint. I propose for it to be `/api/<version>/user_deposit`.

Methods:

- `POST /api/<version>/user_deposit`
`{total_deposit: <amount>}`
- `POST /api/<version>/user_deposit`
`{planned_withdraw_amount: <amount>}`
- `POST /api/<version>/user_deposit`
`{withdraw_amount: <amount>}`

The first two are idempotent. The parameters are exactly what the respective contract functions expect.

As we do with the other API calls which trigger an on-chain transaction we should wait for the transaction to be mined before returning the response. The call for planning a withdraw can then respond with the number of blocks for it to be ready.
