### ISSUE TITLE
PFS7 fails with wrong amount of requests

### ISSUE THREAD

**Issue by czepluch** [raiden-network/raiden#5503]
## Intro

PFS7 fails in the nightly run started December 12th at 23.00 with the following assertion error: `Expected request_count 100 but got 84`.

## Problem Definition

Logs are available here:

- [Scenario log](http://68.183.70.168:8000/scenario-player/scenarios/pfs7_multiple_payments/scenario-player-run_pfs7_multiple_payments_2019-12-13T01%3A32%3A37.log)
- [node0](http://68.183.70.168:8000/scenario-player/scenarios/pfs7_multiple_payments/node_59_000/)
- [node1](http://68.183.70.168:8000/scenario-player/scenarios/pfs7_multiple_payments/node_59_001/)
- [node2](http://68.183.70.168:8000/scenario-player/scenarios/pfs7_multiple_payments/node_59_002/)
- [node3](http://68.183.70.168:8000/scenario-player/scenarios/pfs7_multiple_payments/node_59_003/)
- [node4](http://68.183.70.168:8000/scenario-player/scenarios/pfs7_multiple_payments/node_59_004/)

**Comment by Dominik1999** [comment]
Node0 did request 100 times indeed. Might be a bug in the pathfinding service.

``` 
{
  "url": "https://pfs-goerli-with-fee.services-dev.raiden.network",
  "token_network_address": "0xDa1fBc048f503635950058953f5c60FC1F564ee6",
  "payload": {
    "from": "0x4CF2AABcFac2cB6Aed8C681710AaD04598Cc7Ae2",
    "to": "0xcA4Bf408B6082F154eF1f30878f8d7521c2e1bB2",
    "value": 15000000000000000,
    "max_paths": 5,
    "iou": {
      "sender": "0x4CF2AABcFac2cB6Aed8C681710AaD04598Cc7Ae2",
      "receiver": "0x062C12c01D0f17fC9eAa33940D994594d91a0182",
      "one_to_n_address": "0xB3C76048dB9Fe3092a7F88CeEBC580CcbC223A46",
      "amount": 10000,
      "expiration_block": 2012115,
      "chain_id": 5,
      "signature": "0x4f41f4679e7cdf5eaef9d5c00bd769b3456c1d4aef4d22e73f0fee79731d0b67735badaba8bbf473b418f9287deb3f3ed8155a0ad0dd2df3fbdb1dd2d9b75cf71c"
    }
  },
  "event": "Requesting paths from Pathfinding Service",
  "logger": "raiden.network.pathfinding",
  "level": "info",
  "timestamp": "2019-12-13 02:21:09.570291"
}
➜  ~ cat ~/Documents/Raiden/logs/pfs7-fail/run-059.log | grep "Requesting path" | wc   
    100    4100   85292

```

**Comment by Dominik1999** [comment]
Fix assert of pfs payments.
- we want to get the value of the latest IOU and compare with expected value instead of the number of requests, see #5503

**Comment by hackaugusto** [comment]
The logs from the PFS are not available anymore. I guess the PFS was restarted while the scenario was running, since the requests are kept in memory after a restart the list will be missing some entries.
