### ISSUE TITLE
PFS8 ScenarioError: Raiden node 4 died with non-zero exit status: 1

### ISSUE THREAD

**Issue by czepluch** [raiden-network/raiden#5505]
## Intro

In PFS8 we shut down a node in the scenario. When doing this, the node doesn't shut down correctly and the scenario fails with `ScenarioError: Raiden node 4 died with non-zero exit status: 1` See logs below for info.

## Logs

- [Scenario logs](http://68.183.70.168:8000/scenario-player/scenarios/pfs8_mediator_goes_offline/scenario-player-run_pfs8_mediator_goes_offline_2019-12-13T02%3A21%3A49.log)
- [node0](http://68.183.70.168:8000/scenario-player/scenarios/pfs8_mediator_goes_offline/node_59_000/)
- [node1](http://68.183.70.168:8000/scenario-player/scenarios/pfs8_mediator_goes_offline/node_59_001/)
- [node2](http://68.183.70.168:8000/scenario-player/scenarios/pfs8_mediator_goes_offline/node_59_002/)
- [node3](http://68.183.70.168:8000/scenario-player/scenarios/pfs8_mediator_goes_offline/node_59_003/)
- [node4](http://68.183.70.168:8000/scenario-player/scenarios/pfs8_mediator_goes_offline/node_59_004/)

**Comment by ulope** [comment]
The node is throwing an error in the APIServer during shutdown. See #5507.

The SP probably needs some additional synchronization as well so that it's not trying to monitor the nodes while they are being stopped.

**Comment by nlsdfnbch** [comment]
Perhaps collecting tasks and node greenlets separately might work? Then we could handle node shutdowns without them raising an error, i'd say.

**Comment by Dominik1999** [comment]
Did the Raiden Client in this particular case act as expected?

**Comment by ulope** [comment]
Hm actually I'm not sure if there's a problem in the SP.
The nodes are only shut down at the very end of `main::run()`. At that point all the other greenlets from the scenario run (including the node monitor) have already been stoppen and joined on...

@Dominik1999 no, see the issue I linked above

**Comment by hackaugusto** [comment]
Should have been fixed by https://github.com/raiden-network/raiden/pull/5512
