### ISSUE TITLE
BF4 error: Lock expired

### ISSUE THREAD

**Issue by czepluch** [raiden-network/raiden#5506]
## Intro

BF4 failed with `Payment couldn't be completed because: lock expired`.

## Logs

- [Scenario logs](http://68.183.70.168:8000/scenario-player/scenarios/bf4_multi_payments_same_node/scenario-player-run_bf4_multi_payments_same_node_2019-12-12T22%3A06%3A23.log)
- [node0](http://68.183.70.168:8000/scenario-player/scenarios/bf4_multi_payments_same_node/node_30_000/)
- [node1](http://68.183.70.168:8000/scenario-player/scenarios/bf4_multi_payments_same_node/node_30_001/)
- [node2](http://68.183.70.168:8000/scenario-player/scenarios/bf4_multi_payments_same_node/node_30_002/)
- [node3](http://68.183.70.168:8000/scenario-player/scenarios/bf4_multi_payments_same_node/node_30_003/)
- [node4](http://68.183.70.168:8000/scenario-player/scenarios/bf4_multi_payments_same_node/node_30_004/)

**Comment by Dominik1999** [comment]
Planning 16.12.:
- Analyze and find out what caused that thing

**Comment by karlb** [comment]
We get an UnlockFailed ~10mins after the payment is initiated.
```json
{
  "node": "0x9003DB792d90AeF8c9b3b7FA949ebb006BFB3C1E",
  "state_changes": [
    {
      "routes": [
        {
          "route": [
            "0x9003DB792d90AeF8c9b3b7FA949ebb006BFB3C1E",
            "0x6660D3Cc9635eE0Ec9fd8B51060Fc02beBeCE36e",
            "0x6b040E8CAA88d06939EE65094bc799d8Cd8AaCd8"
          ],
          "estimated_fee": "0",
          "forward_channel_id": "5972"
        }
      ],
      "transfer": {
        "payment_identifier": "14071411256995350828",
        "token_network_address": "0xDa1fBc048f503635950058953f5c60FC1F564ee6",
        "initiator": "0x9003DB792d90AeF8c9b3b7FA949ebb006BFB3C1E",
        "target": "0x6b040E8CAA88d06939EE65094bc799d8Cd8AaCd8",
        "token_network_registry_address": "0x62436bbadB629498107278486C2A367FfdFEb2f3",
        "lock_timeout": "30",
        "secret": "<redacted>",
        "amount": "1000000000000000",
        "secrethash": "0xc4fb1722ecc20934ce74b6af9a5c22a6ef174f57d684159eb34d11d0e5279a69"
      },
      "_type": "raiden.transfer.mediated_transfer.state_change.ActionInitInitiator"
    }
  ],
  "event": "State changes",
  "logger": "raiden.raiden_service",
  "level": "debug",
  "timestamp": "2019-12-12 22:18:50.862305"
}

...

{
  "secrethash": "0xc4fb1722ecc20934ce74b6af9a5c22a6ef174f57d684159eb34d11d0e5279a69",
  "reason": "lock expired",
  "node": "0x9003DB792d90AeF8c9b3b7FA949ebb006BFB3C1E",
  "event": "UnlockFailed!",
  "logger": "raiden.raiden_event_handler",
  "level": "error",
  "timestamp": "2019-12-12 22:28:38.700279"
}
```

**Comment by czepluch** [comment]
PFS8 also failed with an expired log on dec 19th

Logs:
- [Scenario log](http://68.183.70.168:8000/scenario-player/scenarios/pfs8_mediator_goes_offline/scenario-player-run_pfs8_mediator_goes_offline_2019-12-19T03%3A10%3A21.log)
- [node0](http://68.183.70.168:8000/scenario-player/scenarios/pfs8_mediator_goes_offline/node_65_000/)
- [node1](http://68.183.70.168:8000/scenario-player/scenarios/pfs8_mediator_goes_offline/node_65_001/)
- [node2](http://68.183.70.168:8000/scenario-player/scenarios/pfs8_mediator_goes_offline/node_65_002/)
- [node3](http://68.183.70.168:8000/scenario-player/scenarios/pfs8_mediator_goes_offline/node_65_003/)
- [node4](http://68.183.70.168:8000/scenario-player/scenarios/pfs8_mediator_goes_offline/node_65_004/)

**Comment by karlb** [comment]
Looking at @czepluch's latest logs, the payment was not processed byt node 2 and node 2's logs end with
```json
{"response": {"our_address": "0x6A33D4629bd6152C37BA753A44C2cB0937Aa7fDF"}, "status_code": 200, "event": "Request successful", "logger": "raiden.api.rest", "level": "debug", "timestamp": "2019-12-19 03:28:25.261571"}
{"response": {"our_address": "0x6A33D4629bd6152C37BA753A44C2cB0937Aa7fDF"}, "status_code": 200, "event": "Request successful", "logger": "raiden.api.rest", "level": "debug", "timestamp": "2019-12-19 03:28:25.766494"}
{"response": {"our_address": "0x6A33D4629bd6152C37BA753A44C2cB0937Aa7fDF"}, "status_code": 200, "event": "Request successful", "logger": "raiden.api.rest", "level": "debug", "timestamp": "2019-12-19 03:28:26.271863"}
{"response": {"our_address": "0x6A33D4629bd6152C37BA753A44C2cB0937Aa7fDF"}, "status_code": 200, "event": "Request successful", "logger": "raiden.api.rest", "level": "debug", "timestamp": "2019-12-19 03:28:26.777549"}
```
which is not a proper shutdown. But the stdout doesn't provide an error message, either.

**Comment by Dominik1999** [comment]
Closing it until it happens again, we cannot debug with the provided logs.
