### ISSUE TITLE
Nighly builds fail for armv7l and aarch64

### ISSUE THREAD

**Issue by karlb** [raiden-network/raiden#5511]
The nightly builds consistently fail for the architectures armv7l and aarch64

Example: https://circleci.com/workflow-run/851da911-bcb4-4017-adc3-aa11d041b9fc

```
Collecting coincurve==12.0.0 (from -r /tmp/tmpqg2muraj (line 8))
  Downloading https://files.pythonhosted.org/packages/4f/4b/c1c0aaa3a09d21e08de158f25e69134ea4b6563a8d5aee8d99e5f3e3447b/coincurve-12.0.0.tar.gz (948kB)
    Complete output from command python setup.py egg_info:
    WARNING: The wheel package is not available.
    WARNING: The wheel package is not available.
      Failed building wheel for cffi
    ERROR: Failed to build one or more wheels
    Traceback (most recent call last):
      File "/venv/lib/python3.7/site-packages/setuptools/installer.py", line 128, in fetch_build_egg
        subprocess.check_call(cmd)
      File "/usr/local/lib/python3.7/subprocess.py", line 347, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/venv/bin/python3', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmp2sc0cd5y', '--quiet', 'cffi>=1.3.0']' returned non-zero exit status 1.
```

**Comment by LefterisJP** [comment]
Looking at the logs It seems that for these architectures the wheel for `cffi` can't be built. Would it perhaps work if we add an `apt-get install libffi-dev` to the OS package requirements step of docker?

**Comment by LefterisJP** [comment]
I tried to add libffi-dev in a PR: https://github.com/raiden-network/raiden/pull/5573

Is there any way to actually test this locally? Or would we have to be doing PRs, merge them and check the nightlies?

**Comment by ulope** [comment]
Hm, this seem suspicious: `WARNING: The wheel package is not available.`

@LefterisJP yes with `binfmt-support` and `qemu-user-static` on linux, but it's pretty annoying to set up.

**Comment by palango** [comment]
Still fails:
- https://circleci.com/gh/raiden-network/raiden/99951
- https://circleci.com/gh/raiden-network/raiden/99947

**Comment by LefterisJP** [comment]
@ulope I guess the way to properly debug this would be to run the arm build locally and figure it out. Any guide on how to do it for whomever ends up taking this up?

@Dominik1999 Should we tackle this now or it's not a priority? As far as I am concerned I don't think this is a priority before we have fixed all bugs.

**Comment by Dominik1999** [comment]
@LefterisJP indeed let's fix all bugs first ...

**Comment by palango** [comment]
Fixed by https://github.com/raiden-network/raiden/pull/5891
