### ISSUE TITLE
MS3 value mismatch error for channel state

### ISSUE THREAD

**Issue by czepluch** [raiden-network/raiden#5514]
MS3 failed on 16th of December with `ScenarioAssertionError: Value mismatch for "state". Should: "closed" Is: "waiting_for_close"`

Logs:
- [Scenario log](http://139.59.211.171:8000/scenario-player/scenarios/ms3_simple_monitoring/scenario-player-run_ms3_simple_monitoring_2019-12-16T01%3A58%3A44.log)
- [node0](http://139.59.211.171:8000/scenario-player/scenarios/ms3_simple_monitoring/node_70_000/)
- [node1](http://139.59.211.171:8000/scenario-player/scenarios/ms3_simple_monitoring/node_70_001/)

**Comment by palango** [comment]
This issue is quite old now and a lot of code changed since then. Please reopen if it happens again.
