### ISSUE TITLE
Use Matrix filtering API to avoid downloading unecessary data

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/raiden#5535]
## Abstract

ATM `sync` is used without any filters, this means all messages from the `broadcast` rooms and the presence updates for all the users that are in these `room`s are downloaded, even though this data is not of interest to the client.

## Motivation

Reduce download size and load in the Matrix server.

**Comment by Dominik1999** [comment]
Is that related to https://github.com/raiden-network/raiden/pull/5343

**Comment by andrevmatos** [comment]
Related: https://github.com/raiden-network/light-client/issues/746

**Comment by Dominik2002** [comment]
@rakanalh and @hackaugusto split this into multiple issues
