### ISSUE TITLE
Implement adaptive range for event polling

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/raiden#5538]
## Abstract

The current limit:

https://github.com/raiden-network/raiden/blob/5ff86fa995f7b7a0b0954d2c9a10bcdc6def8d86/raiden/blockchain/filters.py#L29-L33

Is some what arbitrary, it was chosen to be high enough to be sufficiently performant, but low enough so that requests to remote nodes would not time-out.

However this is not optimal, and it is hard for an user to choose a good value.

## Motivation

Improve the startup speed of a cold node.

## Specification

Instead of using a hard coded constant the polling code should keep track of how long does it take to query a given range, and increase if it is not close to the socket read timeout.

Caveats: Spikes in events can throw this metric off, so this has to be tested with a high density of events for a given block range.

## Backwards Compatibility

This is internal only, so it is backwards compatible

**Comment by ulope** [comment]
See https://github.com/raiden-network/raiden/issues/6081#issuecomment-615280442 for the chosen values
