### ISSUE TITLE
Everyone in the Raiden Client Team can reproduce "Matrix Sync Error <20s" in Augusto's script

### ISSUE THREAD

**Issue by Dominik2002** [raiden-network/raiden#5562]
Goal: We want that everyone is able to reproduce #5498 in a fast and reliable way.

- [x] Augusto will show the script to everyone
- [x] The assignee will try to reproduce #5498
- [x] If not reproducible, fix the script 
- [x] If not reproducible until Wednesday, we will release

**Comment by Dominik1999** [comment]
@karl can you tomorrow explain @LefterisJP and maybe @rakanalh again how to use that stress test script?

**Comment by LefterisJP** [comment]
Would it not be easier if it's documented somewhere so that we can all just refer to it at any point?

**Comment by Dominik1999** [comment]
Indeed both possible. 

Here is the Readme https://github.com/raiden-network/raiden/blob/develop/tools/README.md 

It is just important that everyone can use this script such that we can quickly reproduce bugs or verify solutions.

**Comment by LefterisJP** [comment]
I have seen the readme. That is simply explaining with a few words what each script in the folder is doing. What would be needed is a step by step guide on running what you call here "Augusto's script" and with what arguments.

**Comment by Dominik1999** [comment]
Sure, That's why I posted the readme here again. We need to update it, such that everyone is able to reproduce with this script

**Comment by Dominik1999** [comment]
Is that done now? Does the new explanation work?

**Comment by karlb** [comment]
> Is that done now? Does the new explanation work?

@LefterisJP is currently following the steps and amending the instructions.
