### ISSUE TITLE
Scenario Failure: Payment couldn't be completed because: none of the available routes could be used

### ISSUE THREAD

**Issue by agatsoh** [raiden-network/raiden#5575]
## Problem Definition

Scenario in a nutshell:
node0 => `0x4a86D7cac59BE32Cca7b52117bB262f48278d73a`
node1 => `0xA70E182604906251307BAFF11A13CF663B2b263d`
node2 => `0x4D86073eE16638eB9CD360CaaF875800a5277F9e`
node3 => `0xE647BfcA234199EA80e643D5ECc2B2f8b49C3Dde`
node4 => `0xAcc75Fe387a73493ac766EFB7089Fb958f24C21e`
node5 => `0x3F4aB77390af0EFf66E0DF45CCF7e088ed95D27C`

```
{
  "task": "<TransferTask: {'from': 0, 'to': 5, 'amount': 1000000000000000, 'lock_timeout': 30}>",
  "event": "Task errored",
  "logger": "scenario_player.tasks.base",
  "level": "error",
  "timestamp": "2020-01-06 22:17:52.059769",
  "exception": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.7/site-packages/scenario_player/tasks/base.py\", line 74, in __call__\n    return self._run(*args, **kwargs)\n  File \"/usr/local/lib/python3.7/site-packages/scenario_player/tasks/api_base.py\", line 59, in _run\n    f'HTTP status code \"{resp.status_code}\" while fetching {url}. '\nscenario_player.exceptions.legacy.RESTAPIStatusMismatchError: HTTP status code \"409\" while fetching http://127.0.0.1:38989/api/v1/payments/0x62083c80353Df771426D209eF578619EE68D5C7A/0x3F4aB77390af0EFf66E0DF45CCF7e088ed95D27C. Expected 2..: {\"errors\": \"Payment couldn't be completed because: none of the available routes could be used\"}"
}
```

what does the exception say:

1. **Payment couldn't be completed because: none of the available routes could be used**

2. Fails at line 86
- transfer: {from: 0, to: 5, amount: 1_000_000_000_000_000, lock_timeout: 30}

3. Occurs while making a call to API
`http://127.0.0.1:38989/api/v1/payments/0x62083c80353Df771426D209eF578619EE68D5C7A/0x3F4aB77390af0EFf66E0DF45CCF7e088ed95D27C`

`0x62083c80353Df771426D209eF578619EE68D5C7A` : token address
`0x3F4aB77390af0EFf66E0DF45CCF7e088ed95D27C` : node5

Some finidings from node0 logs

```
{"event": "Pathfinding Service rejected our payment. Reason: The provided payment is lower than service fee. (2104). Attempting again.", "logger": "raiden.network.pathfinding", "level": "info", "timestamp": "2020-01-06 22:17:53.554632"}
```

**Comment by Dominik1999** [comment]
This happened tonight a lot, see 

## BF2

``` 
Expected 200: {\"errors\": \"Payment couldn't be completed because: none of the available routes could be used\"}", "event": "Run finished", "logger": "scenario_player.main", "level": "error", "timestamp": "2020-01-07 22:54:22.825259"}
```

- [SP Logs](http://139.59.211.171:8000/scenario-player/scenarios/bf2_long_running/scenario-player-run_bf2_long_running_2020-01-07T22%3A16%3A07.log)
- [Node 0](http://139.59.211.171:8000/scenario-player/scenarios/bf2_long_running/node_37_000/)
- [Node 1](http://139.59.211.171:8000/scenario-player/scenarios/bf2_long_running/node_37_001/)
- [Node 2](http://139.59.211.171:8000/scenario-player/scenarios/bf2_long_running/node_37_002/)
- [Node 3](http://139.59.211.171:8000/scenario-player/scenarios/bf2_long_running/node_37_003/)
- [Node 4](http://139.59.211.171:8000/scenario-player/scenarios/bf2_long_running/node_37_004/)

## BF4

``` 
Expected 2..: {\"errors\": \"Payment couldn't be completed because: none of the available routes could be used\"}", "event": "Run finished", "logger": "scenario_player.main", "level": "error", "timestamp": "2020-01-07 22:22:12.664171"}
```

- [SP Logs](http://68.183.70.168:8000/scenario-player/scenarios/bf4_multi_payments_same_node/scenario-player-run_bf4_multi_payments_same_node_2020-01-07T22%3A07%3A44.log)
- [Node 0](http://68.183.70.168:8000/scenario-player/scenarios/bf4_multi_payments_same_node/node_57_000/)
- [Node 1](http://68.183.70.168:8000/scenario-player/scenarios/bf4_multi_payments_same_node/node_57_001/)
- [Node 2](http://68.183.70.168:8000/scenario-player/scenarios/bf4_multi_payments_same_node/node_57_002/)
- [Node 3](http://68.183.70.168:8000/scenario-player/scenarios/bf4_multi_payments_same_node/node_57_003/)
- [Node 4](http://68.183.70.168:8000/scenario-player/scenarios/bf4_multi_payments_same_node/node_57_004/)
- [Node 5](http://68.183.70.168:8000/scenario-player/scenarios/bf4_multi_payments_same_node/node_57_005/)

## BF5

``` 
Expected 2..: {\"errors\": \"Payment couldn't be completed because: none of the available routes could be used\"}", "event": "Run finished", "logger": "scenario_player.main", "level": "error", "timestamp": "2020-01-07 23:00:29.517826"}
```

- [SP Logs](http://68.183.70.168:8000/scenario-player/scenarios/bf5_join_and_leave/scenario-player-run_bf5_join_and_leave_2020-01-07T22%3A22%3A19.log)
- [Node 0](http://68.183.70.168:8000/scenario-player/scenarios/bf5_join_and_leave/node_53_000/)
- [Node 1](http://68.183.70.168:8000/scenario-player/scenarios/bf5_join_and_leave/node_53_001/)
- [Node 2](http://68.183.70.168:8000/scenario-player/scenarios/bf5_join_and_leave/node_53_002/)
- [Node 3](http://68.183.70.168:8000/scenario-player/scenarios/bf5_join_and_leave/node_53_003/)
