### ISSUE TITLE
Include integration tests with light client

### ISSUE THREAD

**Issue by Dominik2002** [raiden-network/raiden#5580]
## Goal 
We want to include the Light Client SDK into our integration test to make sure we do not break the integration with our changes and if so that we know about it and can inform the team

## Approach
to be defined with @andrevmatos

**Comment by andrevmatos** [comment]
We've now a nice cli tool in https://github.com/raiden-network/light-client/tree/cli/raiden-cli which can easily be used for this. It can compile a standalone bundle script, which doesn't require any `npm install` or dependency beyond `node` itself, can be provided and downloaded from somewhere, and is capable of opening a channel, mintint, depositint & making a transfer to a reachable target.
Some simple asserts at the end of it, on the JSON final state, and/or at the HUB side would be enough to test it fully with a local `synapse` & private test chain.
This is the closest we can get at the moment for a inter-client e2e test, and would be a nice tool for enforcing compliance and possibly performance profiling.

**Comment by Dominik1999** [comment]
We will have an integrated test with the Scenario Player. This open question is if this is sufficient. To be discussed with @christianbrb and @andrevmatos

**Comment by christianbrb** [comment]
The Light Client Team is currently running nightly integration tests with Matrix, Contracts, PFS and the Raiden Python Client.

@kelsos Could you point @Dominik1999 to our integration test set-up?

**Comment by Dominik1999** [comment]
ok at the moment this is not needed

**Comment by kelsos** [comment]
For the light client we have an integration docker image https://github.com/raiden-network/light-client/tree/master/integration
This runs a private chain, with Geth, and the contracts deployed. It has a local synapse instance for the transport, and a local instance of the pathfinding service. 

It also has 2 python clients running with a channel open and funded.

Our integration tests are here https://github.com/raiden-network/light-client/blob/master/raiden-ts/tests/integration/integration.spec.ts

The integration tests run on this docker image, and like @christianbrb mentioned these tests run on our CI every night.
