### ISSUE TITLE
Avoid unnecessary fees due to channel partners being offline when using the connection manager

### ISSUE THREAD

**Issue by taleldayekh** [raiden-network/raiden#5583]
In its current implementation, the connection manager that is used for opening channels when joining a token network might also connect you with nodes that happen to be offline.

This leads to unnecessary fees that have to be paid for on-chain transactions just to move the funds around. Apparently, there is a quick fix for this. :)

**Comment by palango** [comment]
Similar to https://github.com/raiden-network/raiden/issues/5453
