### ISSUE TITLE
Test Raiden Service Bundle Setup

### ISSUE THREAD

**Issue by Dominik2002** [raiden-network/raiden#5590]
## Goal

We need to make sure that the Raiden Service Bundle installation script and manual still works after https://github.com/raiden-network/raiden-service-bundle/pull/47

## Test 

Someone needs to make a test setup and sets up the services before we give it to testing to @christian

**Comment by Dominik1999** [comment]
we test the Raiden Service Bundle with the test plan https://docs.google.com/spreadsheets/d/1p63N8a_k-uPIXGpD1UnZzN94a8GAs04kPRwSEjhmDx4/edit#gid=0
