### ISSUE TITLE
Remove wait tasks from all scenarios once they are all green

### ISSUE THREAD

**Issue by czepluch** [raiden-network/raiden#5654]
This issue should not be worked on before the nightlies have been green 3 times in a row.

Currently, a lot of the scenarios have wait tasks that assure that all transfers are propagated correctly throughout the network before asserting on the state. It should not be necessary to have these once the client is in good shape and the performance issues have been resolved.

**Comment by hackaugusto** [comment]
`Added time for synchronization` https://github.com/raiden-network/scenario-player/pull/563

**Comment by karlb** [comment]
We have configurable wait times, which is as good as we can get with our current semantics.
