### ISSUE TITLE
Sync timeout incorrectly specified in milliseconds instead of seconds

### ISSUE THREAD

**Issue by ulope** [raiden-network/raiden#5658]
## Problem Definition

The `matrix-python-sdk` [expresses timeout values in ms](https://github.com/matrix-org/matrix-python-sdk/blob/a469d531b6879c5687718937a0bfcb443155ce43/matrix_client/api.py#L105-L108).

Those are passed unmodified to `requests`, which however expects timeouts as `float`s of seconds 💥.

We changed the default from 30,000 to 20,000 ms which means the timeout is currently 5.5 hours.

We should probably fix it...

**Comment by hackaugusto** [comment]
These values are not given to the `requests` library, they are encoded in the URL's query string and sent to the Matrix server.

**Comment by palango** [comment]
I think as well that the timeout of requests isn't set:

According to https://2.python-requests.org/en/master/user/quickstart/#timeouts , the timeout is set over the `timeout` parameter. However, matrix uses `self.session.request(method, endpoint, params=query_params, ...)`, where `query_params` contains the timeout for the matrix server.

**Comment by karlb** [comment]
I agree with @palango and @hackaugusto. The timeout is only used to [build the `requests` dict](https://github.com/matrix-org/matrix-python-sdk/blob/a469d531b6879c5687718937a0bfcb443155ce43/matrix_client/api.py#L105-L108), which is not used as parameters for the requests library, but as [`query_params` to `_send`](https://github.com/matrix-org/matrix-python-sdk/blob/a469d531b6879c5687718937a0bfcb443155ce43/matrix_client/api.py#L122).

`_send` does not read from the `query_params` and only [uses it as payload for the request](https://github.com/matrix-org/matrix-python-sdk/blob/a469d531b6879c5687718937a0bfcb443155ce43/matrix_client/api.py#L723-L729). So I don't see at which place in the client the timeout could be wrongly interpreted as seconds.

**Comment by ulope** [comment]
*Doh*, you guys are correct. I misread it.
