### ISSUE TITLE
test_pfs_send_capacity_updates_on_deposit_and_withdraw is flaky

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden#5680]
- https://app.circleci.com/jobs/github/raiden-network/raiden/102831
- https://app.circleci.com/jobs/github/raiden-network/raiden/102830

**Comment by fredo** [comment]
I might be mistaken but looking into the logs it looks like the broadcast message of the update which is sent is not yet received by the other app. It can be seen in the attached logs at index 649. Where after the broadcast, a sync return should happen before the assertion which leads to the error. Instead 650 is already the failing test log. 

I assume that the sync call by app0 is not yet ready, letting the test execution continue. The test should wait until the current sync call of app0 is finished and the messages are processed. The `transport._client._sync_iteration` counter can help to wait for it. 

Here is how it is done in another test: 
https://github.com/raiden-network/raiden/blob/7ade3876da3760a4634d06adb437ec4bc0c319bd/raiden/tests/integration/network/transport/test_matrix_transport.py#L1192-L1201


[log.txt](https://github.com/raiden-network/raiden/files/4072394/log.txt) (rename it to .html)


I might be mistaken, but I offer my help to elaborate on this further if needed

**Comment by palango** [comment]
Thanks for looking into this!

The strange thing here is that I created the [TestMatrixClient](https://github.com/raiden-network/raiden/blob/develop/raiden/tests/utils/transport.py#L351) for these tests, that just store the sent messages. So we don't rely on the messages actually being sent, just that `broadcast` was called.
And this should happen in the state machine, before `deposit`returns.

**Comment by fredo** [comment]
If I'm not mistaken, the `broadcast` method stores the message only locally for each transport and then calls `super.broadcast`. So for a transport itself the message should be stored directly. I don't see how the local `dict` of each transport is shared among the other raiden apps. 

This would mean that broadcasting a message from one peer to the others indeed actually depends on receiving the message via matrix. 
looking at your links provided, you can see that the tests fail for `message1` and pass for `message0` which would make sense IMO.

**Comment by fredo** [comment]
I'm currently working on a mechanism how to serialize message sending amongst peers. So if this would help, I'm happy to share my ideas in a call with you.

**Comment by palango** [comment]
> I don't see how the local dict of each transport is shared among the other raiden apps.

That's not necessary in this case, as we just want to check that the node correctly broadcasted the message(s)

**Comment by palango** [comment]
We think we need to synchronize `app1`, and `app2`, so they are at the same block as `app0`.
