### ISSUE TITLE
By 15/02/2020 add an Etherscan API key or remove sync check

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#5688]
## Problem Definition

At 15/02/2020 Etherscan will [enforce](https://t.co/NAfojIV4yD?amp=1) the usage of API keys.

This will break the sync check we have in Raiden:

https://github.com/raiden-network/raiden/blob/152c7398172431b27cdc3b681481054bd75893bc/raiden/ui/checks.py#L204-L221

## Task

Possible solutions:

- Remove the sync check
- Add an API key for all users of Raiden
- Utilize a different service to query the latest block for the sync check

**Comment by palango** [comment]
https://api.blockcypher.com/v1/eth/main seems like a viable source
