### ISSUE TITLE
Rest API shutdown synchronization

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/raiden#5689]
It is possible for the REST API to try access the RaidenService while a shutdown is happening, then the following assert will be broken: 
```
AssertionError: raiden.wal not set
2020-01-17T10:55:42Z <Greenlet "APIServer|Greenlet-3" at 0x671dec23d950: <bound method APIServer._run of <raiden.api.rest.APIServer object at 0x671ddeed7310>>> failed with AssertionError
```
Logs

[logs.zip](https://github.com/raiden-network/raiden/files/4076512/logs.zip)

**Comment by Dominik1999** [comment]
- We should not crash but return a 500 "internal server error"

**Comment by Dominik1999** [comment]
Potential Approach: `_is_raiden_running` is only executed only at the beginning of the request, see https://github.com/raiden-network/raiden/blob/9b2c12d06ffb558c9a5acfbabc50ec468e195958/raiden/api/rest.py#L388

but we need to make sure that during the processing of any request the node isn't stopped. We might solve that by replacing the check on the `_is_raiden_running` with a lock and the Raiden service would not be stopped while this lock is aquired. 

The consecutive steps are
- [ ] Specify @hackaugusto approach and redefine with him
- [ ] Code that shit 
- [ ] write a test (!)

**Comment by karlb** [comment]
> We might solve that by replacing the check on the _is_raiden_running with a lock and the Raiden Service would not be stopped while this lock is aquired.

We should take care that this does not block the shutdown for too long. I don't want to wait for a transaction to be confirmed when I just want to stop my node.

**Comment by hackaugusto** [comment]
> We should take care that this does not block the shutdown for too long. I don't want to wait for a transaction to be confirmed when I just want to stop my node.

This is actually the good behavior we can have for now, if one does not wait for the transaction to finish, on restart the same transaction will be sent and unexpected errors will occurs (this happens because we don't inspect the transaction pool do see if there is an identical transaction in the pool, and if we did, it is hard to tell if the one in the poll is for something else, e.g. two approves of 10 would be identical, but would be for different channel deposits)

**Comment by karlb** [comment]
> ```
> AssertionError: raiden.wal not set
> ```

This error also happened in this flaky test https://app.circleci.com/jobs/github/raiden-network/raiden/111270/tests.

**Comment by palango** [comment]
> > We should take care that this does not block the shutdown for too long. I don't want to wait for a transaction to be confirmed when I just want to stop my node.
> 
> This is actually the good behavior we can have for now, if one does not wait for the transaction to finish, on restart the same transaction will be sent and unexpected errors will occurs (this happens because we don't inspect the transaction pool do see if there is an identical transaction in the pool, and if we did, it is hard to tell if the one in the poll is for something else, e.g. two approves of 10 would be identical, but would be for different channel deposits)

Where are we waiting for this? In the `RaidenService`? In that case we still show down the API after 5 seconds according to this:
https://github.com/raiden-network/raiden/blob/3ad70315695445c2a4f05966a98098bbfe41ed5c/raiden/api/rest.py#L498-L506
