### ISSUE TITLE
ConnectionManager should not spawn a greenlet on every new channel

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/raiden#5706]
The `ConnectionManager` runs in the background, and decides when a new channel should be open, this is done when a new address is available in the network:

https://github.com/raiden-network/raiden/blob/75e7924ba903c9a12891d06a0363cc974ee44e04/raiden/blockchain_events_handler.py#L19-L29

For a large network the code above will spawn a significant number of greenlets (one per channel, which may be thousands). This should be fixed by just signaling to the connection manager that a new channel is available.

To count the number of greenlets:

```
gevent.Greenlet.add_spawn_callback(lambda g: log.info("Starting greenlet", greenlet=g))
```

**Comment by karlb** [comment]
Does the ConnectionManager need to look for new nodes at all? We could limit the concept to "new nodes connect to the network, existing nodes no nothing". That would be simpler, but new nodes would not be able to send payments right away.

**Comment by palango** [comment]
@karlb Please open a new issue for the more general discussion, this issue is only about reducing the number of running greenlets.
