### ISSUE TITLE
Last nightlies (binary and docker) are from 2019-12-04

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/raiden#5737]
## Problem Definition

1. Navigate to https://developer.raiden.network/#Download
2. Click on `Download Nightlies`

### Expected
- Nightlies from 2020-12-23 are available for download

### Actual
- Latest nightlies are from 2020-12-04
- Latest [docker image](https://hub.docker.com/layers/raidennetwork/raiden/nightly/images/sha256-8ad25514bcd996cd6dadf9be46d76121fde9c3c98c7c78377a0bebbc2ca05739) is also from  `2 months ago`

CC @ulope

**Comment by palango** [comment]
I talked to Nils about this and we couldn't find a reason to have both `latest` (which is built after each commit) and `nightly`, which is build every night.

Thus my recommendation is to remove the `nightly` tag and use `latest` instead.

- Remove `build-nightly-image` task from CircleCI config
- Change link on website from `nightly` to `latest`

**Comment by palango** [comment]
Docker hub build task has been removed in #5869.

Now we need to fix the pyinstaller build: #5849

**Comment by palango** [comment]
The nightly is know up-to-date again.

**Comment by ulope** [comment]
I don’t think this was good idea. The reason there was both nightly and latest is that latest is the default docker pulls when nothing else is given. 

Latest was supposed to always point to the latest released version.

**Comment by palango** [comment]
@ulope I mixed the names there. `latest` is the latest released version. `develop` is the always-up-to-date `nightly`

**Comment by ulope** [comment]
Ah ok then it’s fine
