### ISSUE TITLE
Replace search_user_directory with discovery room member lookup

### ISSUE THREAD

**Issue by ulope** [raiden-network/raiden#5757]
## Abstract

Replace the (somewhat) expensive `search_user_directory` matrix API call with a local lookup in the discovery room members list.

## Motivation

For every peer that is getting whitelisted we proactively create a communication room.
While creating the room we search for matching matrix users by using the `search_user_directory` API call which means waiting for a server round trip.

## Specification

The API call should be unnecessary since every correctly behaving node will be a member of the discovery room. Therefore a local lookup in the room members should be sufficient.

We need to make sure the room member list is complete before implementing this.

## Backwards Compatibility

N/A, internal only change.

**Comment by karlb** [comment]
There is no discovery room anymore.
