### ISSUE TITLE
Add contract address to broadcast room name

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden#5776]
Currently we use one broadcast room per network id. This means that different versions of the client and services share the same room. This results in many users in these room which causes issues like https://github.com/raiden-network/raiden/issues/5774.

As the client(s) and the matching services work on a set of contracts we can add the address of a fundamental contract (like `TokenNetworkRegistry` or `ServiceRegistry`) to the name of the broadcast room. This shards the users of the big broadcast room and decreses the number of users in a single broadcast room.

**Comment by ulope** [comment]
That would indeed make a lot of sense, but is slightly problematic since the broadcast rooms are being created by a utility running alongside the synapse servers.
That means that utility would somehow need to know about the available registries and also get notified of updates.

**Comment by arun0930** [comment]
0x7F4B0fc7c8BD0fe9e472B9F66e89EEC1BE52089f

**Comment by karlb** [comment]
There are no broadcast rooms anymore.
