### ISSUE TITLE
BF1: balance mismatch

### ISSUE THREAD

**Issue by karlb** [raiden-network/raiden#5786]
The "is" and "should" values of this AssertionError look identical to me, but the SP has a different opinion. Maybe one of them is a string and the type difference is not visible in the output?
```
scenario_player.exceptions.legacy.ScenarioAssertionError: Value mismatch for "balance". Should: "1000000000000000000" Is: "1000000000000000000" Channel: {'balance': '1000000000000000000', 'state': 'opened', 'total_withdraw': '0', 'channel_identifier': '4973', 'total_deposit': '1000000000000000000', 'token_network_address': '0xDa1fBc048f503635950058953f5c60FC1F564ee6', 'partner_address': '0x46929C86998A28934cb405549a983Be5e9f0794B', 'settle_timeout': '40', 'reveal_timeout': '20', 'token_address': '0x62083c80353Df771426D209eF578619EE68D5C7A'}
```
See http://scenario-player.ci.raiden.network/scenarios/bf1_basic_functionality/scenario-player-run_bf1_basic_functionality_2020-01-29T22%3A03%3A41.log

**Comment by Dominik1999** [comment]
Looks like the logs are gone ... We will close that for now since it is not reproducible and we do not have logs to work with
