### ISSUE TITLE
Raiden node signal handling/stopping unreliable

### ISSUE THREAD

**Issue by karlb** [raiden-network/raiden#5790]
Raiden nodes don't reliably shut down when we want to stop them (e.g. in the SP or stress test). We might not send the signals properly, the signals could be lost somewhere or the signal handlers could have a different effect than intended.

There are probably multiple root causes for this. Find a way to reproduce this issue and make an issue for that specific case (or directly push a PR if the solution is obvious at that point).

look at this Monday afternoon

[SP *8]

**Comment by Dominik1999** [comment]
I think it happened again:

- http://scenario-player.ci.raiden.network/scenarios/pfs8_mediator_goes_offline/

**Comment by karlb** [comment]
I found three issue, the first two are already fixed (#5815 and #5794), and the missing check for clean shutdown in the SP will be fixed by either https://github.com/raiden-network/scenario-player/issues/468 or https://github.com/ClearcodeHQ/mirakuru/pull/381.

Since I don't see any specific shutdown issues left at the moment, I'll close this.
