### ISSUE TITLE
Greenlet handling guidelines

### ISSUE THREAD

**Issue by karlb** [raiden-network/raiden#5807]
The details of greenlet handling vary between different parts of the code and I'm not sure what's the right one. Questions I'm asking myself:

* Inherit from `Runnable`, from `Greenlet` or just use `spawn`?
* Should `stop` block until all children are dead?
* When to use `stop` vs `kill?`
* What should we do when greenlets take long to terminate? If we use a timeout, what should happen when the timeout is exceeded?
* Should I ever use `Greenlet.join`, which does not raise errors?
* What is the recommended way to propagate errors (`link` vs expecting the parent to call `get`)?

**Comment by karlb** [comment]
(https://github.com/raiden-network/raiden/blob/develop/raiden/utils/runnable.py)[Runnable] has some explanations along these lines in the docstrings. But `start` is defined to "Synchronously start task", while `Greenlet` and `BaseServer` instances use `start` without blocking.

**Comment by hackaugusto** [comment]
Related `Write ADR about greenlet monitoring and error handling` #5486

**Comment by karlb** [comment]
Duplicate of https://github.com/raiden-network/raiden/issues/5486
