### ISSUE TITLE
200203 - BF1 Balance Mismatch

### ISSUE THREAD

**Issue by Dominik1999** [raiden-network/raiden#5814]
Run 119 (2nd to 3rd Feb) shows a balance mismatch.

See http://scenario-player.ci.raiden.network/scenarios/bf1_basic_functionality/scenario-player-run_bf1_basic_functionality_2020-02-02T22%3A04%3A07.log.gz

See http://scenario-player.ci.raiden.network/scenarios/bf1_basic_functionality/node_119_000/

**Comment by palango** [comment]
In the logs of node 4 there are 20 logs with `SendSecretRequest` and only 19 `EventPaymentReceivedSuccess`. This means that the payment wasn't completely finished yet.

This is probably cause by https://github.com/raiden-network/raiden/pull/5810
