### ISSUE TITLE
Figure out why so many messages are being sent over Matrix 

### ISSUE THREAD

**Issue by Dominik1999** [raiden-network/raiden#5841]
For @ulope to spec out that issue

**Comment by Dominik1999** [comment]
We have done an analysis and we do not send "so many messages" anymore. @hackaugusto pls add analysis

**Comment by hackaugusto** [comment]
Metrics for # of dispatches:

messages | repetitions  
-- | --
745 | 1
16 | 2

Metrics for # of retries:

messages | repetitions
-- | --
739 | 1
34 | 2

Metrics for # of sends:
messages | repetitions
-- | --
16 | 1
757 | 2

The tables above show the total number of messages that were retried `x times. So, the first table says that there were 16 messages dispatched twice, and 745 messages dispatched once.

The results above were gathered by running the stress test and then:

``
grep -hi 'transport performance' node*/*out | jq '.counters.dispatch[][1]' | sort | uniq -c 
grep -hi 'transport performance' node*/*out | jq '.counters.retry[][1]' | sort | uniq -c
grep -hi 'transport performance' node*/*out | jq '.counters.send[][1]' | sort | uniq -c
```

Note that the numbers do vary, but from what we have seen the variations is because of load in the synapse servers, and not on Raiden itself

**Comment by Dominik1999** [comment]
thank you @hackaugusto 

On thing that is confusing me is that @karlb seems to get a completely different result. Or do I miss something here?

See https://github.com/raiden-network/raiden/pull/5881#issuecomment-585742636

**Comment by hackaugusto** [comment]
@Dominik1999 the broadcast messages are not included in these metrics:

https://github.com/raiden-network/raiden/blob/8f3ddf20f33140d423b61804df5afcdef9ec7cd8/raiden/network/transport/matrix/transport.py#L682-L725
