### ISSUE TITLE
Reduce number of pending open PRs (16)

### ISSUE THREAD

**Issue by Dominik1999** [raiden-network/raiden#5870]
There are currently 16 PRs pending on the Raiden Repo:

- https://github.com/raiden-network/raiden/pulls

We should reduce that number and do some housekeeping

**Comment by Dominik1999** [comment]
Introduce a fix up Friday: @palango has to organize that

**Comment by Dominik1999** [comment]
Dominik puts 5 PRs into Sprint Backlog

**Comment by palango** [comment]
We're now around 10
