### ISSUE TITLE
Remove 'pkg_resources.py2_warn' from list of hiddenimports

### ISSUE THREAD

**Issue by eorituz** [raiden-network/raiden#5874]
## Problem Definition

To work arround an issue with `setuptools>45.0.0` I added 'pkg_resources.py2_warn' to the list of `hiddenimports` in the [raiden.spec]( https://github.com/raiden-network/raiden/blob/develop/raiden.spec).

As soon as the [corresponding issue](https://github.com/pypa/setuptools/issues/1963) with setuptools is fixed we can remove `pkg_resources.py2_warn` from our hiddenpimports

**Comment by konradkonrad** [comment]
It seems the upstream issue got resolved? cc @eorituz

**Comment by eorituz** [comment]
@konradkonrad Yep seems that this is no longer an issue from `setuptools>=49.1.1` onwards.
If I'm not mistaken setuptools is not listed in any of raiden's requirements so we can remove the hotfix I did.

See PR https://github.com/raiden-network/raiden/pull/6661
