### ISSUE TITLE
Implement State Changes and Events for Direct Transfers

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#588]
## Problem Definition

At the moment we do not have any state changes or events for Direct Transfers, only for mediated transfers.

## Solution

Add events (same type as those generated from the state changes of mediated transfers) for the Direct Transfer scenario, incorporate them in the code and write them in the WAL.

## Tasklist

- [ ] Create ~StateChange and~ Event Objects for DirectTransfers
- [ ] Incorporate them in the codebase
- [ ] Write them in the Write Ahead Log

**Comment by konradkonrad** [comment]
needs follow up: Implement State Changes for Direct Transfers
