### ISSUE TITLE
Exchange Union Transport Server cannot be restarted anymore

### ISSUE THREAD

**Issue by fredo** [raiden-network/raiden#5885]
Exchange Union moved its infrastructure. Their running Matrix Server could not be restarted on the new infrastructure. The latest release `2019.11.1` as well as the one they were using before `2018.12.0` could not be brought up back into a healthy state.

## Problem Description
When trying to build a new docker some dependencies in Raiden might have changed that it caused the problem, that their fork of Raiden cannot connect to a local geth client anymore. This problem is also described in issue  #5557. Unfortunately, this is how their set up is built and they rely on it. They can continue their old setup but they would need a matrix server running for this. 

They asked for a quick solution and if we are so kind as to set up a Matrix Server for them until Alderaan is released.

### Possible quick Solution

We set up a Matrix Server for them using `raidentransport.exchangeunion.com` in the `.env` file. They will Point to this IP. 

## Alternative Approach

look if old images still exist somewhere and investigate if they can build their docker setup again. This might be more time-consuming. Once Alderaan is released they will switch to the latest releases so the solution would only last until then anyway.

In this issue, we can track the progress of this problem.

- [x] Decide how to solve the problem
- [x] Implement the solution
- [ ] Possible further investigation of the causes

**Comment by fredo** [comment]
The matrix server is set up on our servers and running for Exchange Union. They made an A record to point to that. 
Now a call with Kilian is planned to plan how to fix the issue for the future. No date set yet.

**Comment by fredo** [comment]
Call will take place mid of next week

I will invite Kilian and Dominik

**Comment by Dominik1999** [comment]
We helped Kilian with his issue, closing this for now, see email below. 
```
Hi,
sorry wegen heute - haben noch nicht released und bin etwas unter Wasser.
Frage: Welche version laeuft denn auf der aktuellen instanz die ihr fuer uns hosted? Funktioniert reibunsfrei, sollte also diese version sein.
Kilian

On Wed, 2020-02-26 at 17:34 +0100, frederik wrote:
>
> Hallo Kilian,
>
> da es heute leider nicht geklappt hat, sende ich dir am besten eine Mail mit den Punkten, die wir gerne mit dir Besprechen würden.
>
> Zunächst hoffen wir, dass bei euch alles stabil läuft und ihr euer Release erfolgreich gestalten konntet.
>
> Für das weitere Vorgehen habe ich folgende Punkte notiert.
>
>
> 1) Hat das Matrix Server Setup euer Problem gelöst?
>
> 2) Können wir euch die Ownership des aktuellen Servers übertragen? (Das funktioniert nur, solltet ihr Digital Ocean als Provider benutzen)
>
> 3) Falls nein, wie können wir Euch helfen, sodass ihr bis zum spätestens 06.03.20 euren eigenen Server am laufen habt?
>
>
> Zu Punkt 3 habe ich bereits zwei Dokumente vorbereitet, die euch helfen sollen möglichst reibungslos eure Version (2018.12.0) aufsetzen zu können.
>
> Dazu gehört einmal die ".env" Datei, welche die nötigen Umgebungsvariablen in Docker importiert.
>
> Andererseits ein Script, welches alle Befehle beinhaltet um den Matrix Server aufzusetzen.
>
>
> Ich stehe euch gerne bei weiteren Fragen diesbezüglich zur Verfügung.
>
>
> LG
>
> Frederik 
```
