### ISSUE TITLE
Avoid errors caused by early slow sync

### ISSUE THREAD

**Issue by karlb** [raiden-network/raiden#5898]
I've seen "PFS: source not online" errors in the stress test shortly after restarting nodes. The node was considered offline because it took too long to start the next sync. This should not happen and even when it happens, a clear error message would be better than just seeing the followup errors. 

## Approach 1: Strict check + more speed

Remove the exemption of first syncs for timeout. This will give us the earlier and clearer error (a sync timeout).

This only makes sense if we can make Raiden fast enough to not run into this error afterwards.
Doing the following could achieve this:
- Purge users from broadcast rooms: https://github.com/raiden-network/raiden-service-bundle/issues/82
- Matrix split mode: https://github.com/raiden-network/raiden/issues/5884
- Less HTTP requests to matrix: https://github.com/raiden-network/raiden/pull/5272
- Bug fixes: https://github.com/raiden-network/raiden/pull/5888, https://github.com/raiden-network/raiden/pull/5273

## Approach 2: Delay startup of rest API

When the rest API can't be used during the problematic time, we won't get any errors. But delaying the API startup makes Raiden API users blind to what's happening.

## Approach 3: Handle "not ready" cases in API

Possible changes:
- Additional "is node fully ready" endpoint, which could be checked by stress tests, SP, etc. before starting transfers
- Delaying transfers until we are in a known good state
- Returning "not ready for transfers, yet" errors when calling that endpoint too early

[SP 8] for deciding on the exact solution

**Comment by karlb** [comment]
In the problem case I investigated, the cause was mostly https://github.com/raiden-network/raiden/pull/5888, which makes me think that approach 1 would be realistic.

**Comment by karlb** [comment]
I've run 10 stress tests (which mean 50 startups) without any problems with the strict check as in approach 1. It looks like we're fast enough already and will get faster with the other linked issues. So I don't see a reason to not go with approach 1.

**Comment by Dominik1999** [comment]
Nice, efficient solution. Thanks!
