### ISSUE TITLE
Extract performance data from scenario runs

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden#5901]
We talked about getting performance data. On idea that came up is to use the information the SP provides: Here we know when each task is started and finished. This information can be extracted and visualized.

**Comment by christianbrb** [comment]
This repo https://github.com/raiden-network/performance-analysis-tool should be a good starting point

**Comment by palango** [comment]
@christianbrb Thanks for the link. I didn't know this existed.

A simpler version, just for the `transfer` tasks:
```sh
cat SCENARIO_LOG.log | grep successful | grep TransferTask | jq .runtime
```

**Comment by karlb** [comment]
See https://github.com/raiden-network/performance-analysis-tool
