### ISSUE TITLE
Stress test: none of the available routes could be used

### ISSUE THREAD

**Issue by karlb** [raiden-network/raiden#5914]
During the stress test I sometimes (though rarely) get `Payment couldn't be completed because: none of the available routes could be used` error when starting a fresh batch of payments after the nodes have restarted. I've added some additional logging to trace this back to the cause `channel doesn't have enough distributable tokens`.

I was hoping that https://github.com/raiden-network/raiden/pull/5865 resolves this issue, but it didn't.

Logs: https://drive.google.com/file/d/1DN01rdrnwECYezrxnkOe0fia_wbGyq8I/view?usp=sharing

**Comment by karlb** [comment]
Node `0x18ab39bdc54a2705f77e97f59190490359c02ba6` receives the Unlock for payment 597 (secrethash `0xb07f31448bdb716c46c3b03591854029a9343bec743a3b7823d59eb776a87c4f`) after it initiates the new round of payments and is thus lacking the funds for the last payment.

Why doesn't #5865 prevent this?

**Comment by Dominik1999** [comment]
Is this still relevant?
