### ISSUE TITLE
lock expired in several scenarios

### ISSUE THREAD

**Issue by karlb** [raiden-network/raiden#5918]
We see `Payment couldn't be completed because: lock expired` in several scenario runs. There might be heterogeneous reasons for that symptom. 

```
scenario_player.exceptions.legacy.RESTAPIStatusMismatchError: HTTP status code "409" while fetching http://127.0.0.1:56433/api/v1/payments/0x8856DCbbff6e3855128BbBAB8b7a142651F6c188/0x4cdF6e2E779A4DEB1c2793A0BC4dA89abcEC94c0. Expected 2..: {"errors": "Payment couldn't be completed because: lock expired"}
```
See run 605 of bf5 for example.

Possibly related to https://github.com/raiden-network/raiden/issues/5917.

We need to come up with a strategy on how to debug those scenario failures with respect to `lock_expired`. Maybe some sort of checklist to determine potential reasons for that symptom.

**Comment by Dominik1999** [comment]
This happens almost everytime we run bf5 remotely, see also http://scenario-player.ci.raiden.network/scenarios/bf5_join_and_leave/node_619_000/

**Comment by Dominik1999** [comment]
A potential approach to debug those issues (we see this symptom more often):
- get the secretHash from the Initiator (I)
- see if secretHash arrived at the Target (T)
- If not at T: 
  - Then get the route that was used from I and logs of all mediators, grep for State Changes and Events for this specific secretHash and compare, either
    - (1) Find a mediator that has a state change but no event for the given secretHash -> Use replay of WAL to see the problem, or
    - (2) Find the last mediator with the corresponding event to secretHash. 
       - For that last mediator look for the sending of the message (sendRaw atm)
       - If message was not sent, debug at the previous mediator
- If at T:
  - Grep in T logs for SendSecretRequest with same secretHash
    - if there is: Matrix failed 
    - if none: replay WAL

Error message above can not be seen with other message exchange between nodes

**Comment by karlb** [comment]
The stderr output shows AssertionErrors:
```
AssertionError
2020-03-13T12:17:23Z <callback at 0x7f3b23aa0408 stopped> failed with AssertionError
```

One of these for node2, two of them for node3. Unfortunately, they don't provide any messages, even after https://github.com/raiden-network/raiden/pull/5564.

**Comment by karlb** [comment]
The `AssertionError`s are most likely caused by https://github.com/gevent/gevent/issues/1540.

**Comment by karlb** [comment]
The healthcheck problems in bf5 are caused by force_check_address_reachability which is only used in the connection manager. When that is called, the address and its presence become known, which prevents the room from being created in immediate_health_check_for. I see two ways around it:

1. Change force_check_address_reachability to only return the current reachability without any side effects
2. Memorize which rooms are created and check that in the condition (complicated by the fact that rooms exist per matrix user, not per eth address)

I'm writing an integration test to reproduce the bug and plan to fix it using approach 1.

**Comment by karlb** [comment]
I managed to reproduce it in an integration test and fix that test: https://github.com/raiden-network/raiden/pull/5998

Unfortunately, the scenario still does not work reliably. Investigating...
