### ISSUE TITLE
Recover from the Write Ahead Log

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#592]
## Problem Definition

After having the Write Ahead Log written to we also need to be able to recover if Raiden restarts by reading and replaying all state changes from the log.

Also Write Tests.
## Solution

Read from the Write Ahead Log when raiden starts.

## Tasklist

- [ ] Write tests (xfailed) that specify the expected behaviour of a WAL recovery in both the happy path and situations where something changed in between.
- [ ] Read from the Write Ahead Log when Raiden starts and replay state changes to get to the latest state.

**Comment by LefterisJP** [comment]
After our latest discussion this issue is getting pushed outside of the Developer Preview milestone.

In order to complete this issue we need the channel logic to also be modified to use the state machine as does the transfer logic at the moment (Issue https://github.com/raiden-network/raiden/issues/507).

This is a part of making raiden recoverable from sudden shutdowns as defined in this meta issue: https://github.com/raiden-network/raiden/issues/205

**Comment by hackaugusto** [comment]
>  Read from the Write Ahead Log when Raiden starts and replay state changes to get to the latest state.

Was done by: https://github.com/raiden-network/raiden/pull/1349

>  Write tests (xfailed) that specify the expected behaviour of a WAL recovery in both the happy path and situations where something changed in between.

Moved to: https://github.com/raiden-network/raiden/issues/1562
