### ISSUE TITLE
Fix-Up Friday: Refactor Message Handling in Matrix.Client

### ISSUE THREAD

**Issue by fredo** [raiden-network/raiden#5921]
## Motivation
As a first idea for a fix-up Friday Ulo and me discussed a small refactoring of the message handling. Due to the recent changes of introducing the response handling queue and #5913 some refactoring might be possible to reduce code and complexity. 

## Specification
- [x] remove first sync flag
- [x] change location stop event condition in `_handle_messages`
- [ ] ~~reevaluate naming in the flow of handling messages from receiving sync until passing to `raiden_service`~~

**Comment by fredo** [comment]
- [ ] Check if Refactorings are possible after separating rooms and broadcast rooms in different dicts

**Comment by fredo** [comment]
From the call with @hackaugusto:

- [ ] change `extract_all_partner_addresses` to `has_multiple_addresses` such that it does not perform ecrecover on all addresses in the room (possible attack vector)

**Comment by hackaugusto** [comment]
- [ ] Remove the shared timeout (it should not be one per message, but one per target address)

**Comment by fredo** [comment]
> * [ ]  Remove the shared timeout (it should not be one per message, but one per target address)

Will create new issue out of that
