### ISSUE TITLE
Serialize transfer state during graceful shutdown

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#593]
## Problem Definition

~Depends on  #595.~ <-- Done

In the same way that we have serialized (pickled) the channel data during shutdown and recover from them we also need to do that for all transfer states.

- [x] Take snapshots (simple serialized pickled) of the transfer states during graceful shutdown of Raiden.
- [x] During restart of raiden deserialize this data and restart from where we stopped before.

**Comment by konradkonrad** [comment]
Will start working on this, based on #615

**Comment by konradkonrad** [comment]
After discussion, we agreed on storing the following items in snaphsots:
- `ChannelSerialization` (latest balance proofs) + ordered queue of messages/transfers still in-flight
- smart contract calls in-flight

A good point for issuing a channel snapshot is the end state of a transfer, i.e. a completed or a failed transfer.

**Comment by LefterisJP** [comment]
After our final discussion this issue is transformed to the issue of taking a snapshot of the transfer state in the same way that we currently take a snapshot (via pickle) of the channel state and queues during graceful shutdown.
