### ISSUE TITLE
Synapse split mode: Synthetically reproduce presence propagation issue

### ISSUE THREAD

**Issue by ulope** [raiden-network/raiden#5943]
Part of: #5884 

## Abstract

After setting up a separate federation of two Synapse servers in split worker mode:
- Run synthetic tests to provoke the federation presence propagation issue we've been seeing end of last year
- In parallel run load tests on the servers to 
  - Help provoke the issue
  - Get an idea of the difference in performance between "normal" and split mode

**Comment by ulope** [comment]
So far no conclusive evidence has surfaced. 
This means we should probably move on to #5944.

**Comment by Dominik1999** [comment]
we decided to move on to #5944
