### ISSUE TITLE
Raiden Performance - We want to see a measure (on a dashboard)

### ISSUE THREAD

**Issue by Dominik1999** [raiden-network/raiden#5956]
## Goal
We want to see how performant Raiden is and how this is changing over time. Eventually, we should aim to have a comprehensive dashboard similar to this one for Lightning Network - https://1ml.com/statistics

Therefore we need to define a measure to measure performance. Data should then be shown on a nice dashboard. 

## Approach

- [ ] discuss with @GataKamsky what to measure exactly
- [ ] Design approach how to measure constantly with keeping maintenance in mind 

Ideas:

It will be good to start with something basic and limited i.e. only some from the list (non-exhaustive) below:

**General**
- Number of Nodes
- Avg Single-Hop payment time
- Avg Dual-Hop payment time 
- Channel count
- Number of payments processed
- Avg Channel opening/closing times (Less RDN related)

**Liquidity**
- Avg channel capacity

**PFS related**
- Avg number of hops for payments
- Avg Fees 
  - Flat
  - Mediating 
  - Rebalancing

**Comment by GataKamsky** [comment]
It will be good to start with something basic and limited i.e. only some from the list (non-exhaustive) below:

**General**
- # of Nodes
- Avg Single-Hop payment time
- Avg Dual-Hop payment time 
- Channel count
- # of payments processed
- Avg Channel opening/closing times (Less RDN related)

**Liquidity**
- Avg channel capacity

**PFS related**
- Avg # of hops for payments
- Avg Fees 
  - Flat
  - Mediating 
  - Rebalancing

**Comment by GataKamsky** [comment]
Eventually, we should aim to have a comprehensive dashboard similar to this one on Lightning Network - https://1ml.com/statistics

**Comment by christianbrb** [comment]
There is already the repository https://github.com/raiden-network/performance-analysis-tool available. It's is far from perfect, but maybe a good start.

It builds on top of the scenario player logs.

![grafik](https://user-images.githubusercontent.com/35398162/76843172-b22eeb80-683b-11ea-89a9-8588304ebc1a.png)

**Comment by karlb** [comment]
The list in the issue mixes two different kinds of metrics:
* Metrics about the raiden software (changes with each commit)
* Metrics about the running production system (changes with wall-clock time)

For the first one, something like https://speed.pypy.org/ would be the long term goal.

**Comment by konradkonrad** [comment]
I think it also mixes

- usage statistics
- performance numbers

the first one is already somewhat addressed by the [Network Explorer](https://explorer.raiden.network/tokens/0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2).

IIRC, we cued this issue, because we wanted a dashboard for performance numbers.

**Comment by konradkonrad** [comment]
after clarification with @GataKamsky I created https://github.com/raiden-network/performance-analysis-tool/issues/3 and will work on that.

**Comment by konradkonrad** [comment]
Next steps:
- look into https://github.com/tobami/codespeed to see if it fits our data or how we would need to adapt
