### ISSUE TITLE
Revisit HealthCheck to incorporate invitation pings for NAT

### ISSUE THREAD

**Issue by konradkonrad** [raiden-network/raiden#596]
## Problem Definition

These are leftovers from #120 

- [x] add invitation pings for mediated transfer initiator (this is necessary to allow the target to send a SecretRequest)
- [ ] revisit HealthCheck tasks to include the logic of invitation pings (some cone NAT will only allow incoming packets after outgoing packets)

**Comment by konradkonrad** [comment]
second bulletpoint will be tackled through #595

**Comment by czepluch** [comment]
closing issue since first part is solved by #617 and second part is handled in another issue
