### ISSUE TITLE
Execute Alederaan Testplan with RC3 on Goerli

### ISSUE THREAD

**Issue by Dominik1999** [raiden-network/raiden#5990]
to be done after #5434 

## When we have a stable RC, we execute our test plan 

- [x] Verify test plan is executable on Goerli, open issues 
- - [x] DAI and W-ETH on Goerli https://github.com/raiden-network/team/issues/755 
- - [x] Adapt Scenario Player to different Environments https://github.com/raiden-network/team/issues/682
- [x] Execute testplan on Goerli, see [here](https://docs.google.com/spreadsheets/d/1p63N8a_k-uPIXGpD1UnZzN94a8GAs04kPRwSEjhmDx4/edit#gid=0)
+++ this needs to be properly planned with vacations and free days +++
- - [x] @karlb and @czepluch test smart contract parts (SC steps)
- - [x] @eorituz and @fredo and @czepluch  test RSB parts (RSB steps)
- - [x] @Dominik1999  and @czepluch and @agatsoh test client parts (Client steps)
- - [x] results need to be logged
- [x] @czepluch and @GataKamsky give the approval to proceed to mainnet testing
After successfully executing our test plan, we should proceed with manual testing on mainnet.

**Comment by czepluch** [comment]
Did the initial part of the spreadsheet. Will go through the results with @karlb tomorrow and make sure that the steps only the owner can execute are executed as well.

**Comment by Dominik1999** [comment]
The scenarios were successful in the test environment:
- BF1
- BF2
- BF3
- BF4
- BF5
- BF6
- BF7
- PFS1
- PFS1
- PFS1
- PFS1
- PFS1
- PFS1
- PFS1

**Comment by Dominik1999** [comment]
Steps `SC-19 SC-22` are missing, since we are waiting for initial RSB provider to join the federation once.

Results are logged [here](https://docs.google.com/spreadsheets/d/1p63N8a_k-uPIXGpD1UnZzN94a8GAs04kPRwSEjhmDx4/edit#gid=0)
