### ISSUE TITLE
BF5 fails with Deployment of CustomToken failed

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden#5994]
The deployment of the `CustomToken` fails.

Example transaction: https://goerli.etherscan.io/tx/0x64ed74171466de86bb78338df7ce045056381b78665048b79ae7775e3949711b

```
Traceback (most recent call last):
  File "/Users/paul/Projects/brainbot/scenario-player/scenario_player/main.py", line 290, in run_
    smoketest_deployment_data,
  File "/Users/paul/Projects/brainbot/scenario-player/scenario_player/main.py", line 358, in orchestrate
    scenario_runner.run_scenario()
  File "/Users/paul/Projects/brainbot/scenario-player/scenario_player/runner.py", line 385, in run_scenario
    gevent.joinall(greenlets, raise_error=True, count=1)
  File "src/gevent/greenlet.py", line 849, in gevent._greenlet.joinall
  File "src/gevent/greenlet.py", line 865, in gevent._greenlet.joinall
  File "src/gevent/greenlet.py", line 312, in gevent._greenlet.Greenlet._raise_exception
  File "/Users/paul/Projects/brainbot/scenario-player/venv/lib/python3.7/site-packages/gevent/_compat.py", line 47, in reraise
    raise value.with_traceback(tb)
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "/Users/paul/Projects/brainbot/scenario-player/scenario_player/runner.py", line 455, in setup_environment_and_run_main_task
    token_proxy = self.setup_token_contract_for_token_network(proxy_manager)
  File "/Users/paul/Projects/brainbot/scenario-player/scenario_player/runner.py", line 651, in setup_token_contract_for_token_network
    token_definition.symbol,
  File "/Users/paul/Projects/brainbot/raiden/raiden/network/rpc/client.py", line 1120, in deploy_single_contract
    contract_name
RuntimeError: Deployment of CustomToken failed. Contract address has no code, check gas usage.
```

**Comment by konradkonrad** [comment]
This is very likely due to https://github.com/raiden-network/scenario-player/pull/516/commits/b6207d55b5dc142284d5faa879b7d411486854c3 -- the monkeypatch for doubling gas estimations was removed. Since parity estimations are off, this now fails.

**Comment by konradkonrad** [comment]
Since [this is still an open issue](https://github.com/raiden-network/raiden/pull/5995), I think we need to run some assumption tests for the parity/geth gas estimations, in order to either
- have enough information to file an upstream issue
- better understand the systematics of parity's underestimation and come up with better patches

Shortterm for the scenario player itself: If we want to reintroduce the estimation patch, we should query the `EthClient` type first before patching.

**Comment by palango** [comment]
This problem just seems to occur with contract deployments. In https://github.com/raiden-network/raiden/pull/5995/commits/72aef35ebbd7f9909f0d934737e3447671bd175f#diff-79ef917c2473698777a5474a23dc119fR1235 I changed the `deploy_single_contract` function to have a 10% margin, and with that it works fine.

The problem is that **both** clients seem to underestimate the required gas:
```
raiden/tests/integration/test_balance_proof_check.py::test_node_can_settle_if_close_didnt_use_any_balance_proof[2-channels_per_node0-10]
DEPLOY SecretRegistry, using EthClient.GETH
Estimate:  292738
Limit:     322011
Receipt:   292738
DEPLOY CustomToken, using EthClient.GETH
Estimate:  1448047
Limit:     1592851
Receipt:   1463047
DEPLOY CustomToken, using EthClient.GETH
Estimate:  1433189
Limit:     1576507
Receipt:   1448189
DEPLOY TokenNetworkRegistry, using EthClient.GETH
Estimate:  4891794
Limit:     5380973
Receipt:   4906794
DEPLOY ServiceRegistry, using EthClient.GETH
Estimate:  2480072
Limit:     2728079
Receipt:   2480072
DEPLOY UserDeposit, using EthClient.GETH
Estimate:  1873982
Limit:     2061380
Receipt:   1873982
DEPLOY OneToN, using EthClient.GETH
Estimate:  1325909
Limit:     1458499
Receipt:   1325909

raiden/tests/integration/test_balance_proof_check.py::test_node_can_settle_if_close_didnt_use_any_balance_proof[2-channels_per_node0-10]
DEPLOY SecretRegistry, using EthClient.PARITY
Estimate:  292738
Limit:     322011
Receipt:   292738
DEPLOY CustomToken, using EthClient.PARITY
Estimate:  1448047
Limit:     1592851
Receipt:   1463047
DEPLOY CustomToken, using EthClient.PARITY
Estimate:  1433189
Limit:     1576507
Receipt:   1448189
DEPLOY TokenNetworkRegistry, using EthClient.PARITY
Estimate:  4891794
Limit:     5380973
Receipt:   4906794
DEPLOY ServiceRegistry, using EthClient.PARITY
Estimate:  2480072
Limit:     2728079
Receipt:   2480072
DEPLOY UserDeposit, using EthClient.PARITY
Estimate:  1873982
Limit:     2061380
Receipt:   1873982
DEPLOY OneToN, using EthClient.PARITY
Estimate:  1325909
Limit:     1458499
Receipt:   1325909
```

**Comment by Dominik1999** [comment]
Thanks, can you open a PR for it?

**Comment by hackaugusto** [comment]
> The problem is that both clients seem to underestimate the required gas for the CustomToken and TokenNetworkRegistry contracts.

Funny, and it is for the same smart contracts and even for serialized transactions. I wonder why this is not a problem in the `raiden` build, the gas estimation fix is setup only for parity: https://github.com/raiden-network/raiden/blob/445f3a6fe6b6ee7bd59a394078d7bfc0ff402774/raiden/tests/integration/fixtures/blockchain.py#L74-L81

**Comment by palango** [comment]
Should I clean up that PR so we at least work around that for now while finding the underlying issue?

**Comment by Dominik1999** [comment]
sounds reasonable to me. At least at the current stage. We can run our scenarios in the meantime

**Comment by palango** [comment]
A workaround is here: https://github.com/raiden-network/raiden/pull/5995

But we should find the underlying issue and/or report this to geth (as this changed from 1.9.11 to 1.9.12)

**Comment by Dominik1999** [comment]
- [ ] agree with Augusto on approach (workaround solution and create ticket for get and parity)
- [ ] get workaround merged
- [ ] create follow up issue (to create bug report in GETH repo) and ignore rest for Sprint 14

**Comment by palango** [comment]
Follow-up issue: https://github.com/raiden-network/raiden/issues/6006
