### ISSUE TITLE
Homebrew formula is broken

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden#6035]
The homebrew formula is broken and needs to be fixed. As it is updated automatically we probably need to fix the CI script.

See `v0.200.0-rc3a0-dev1-dev0` in here:
https://github.com/raiden-network/homebrew-raiden/blob/a38fe5dbc07d3d1997efd9221542ae1322953c07/raiden.rb#L4-L11

**Comment by ulope** [comment]
`v0.200.0-rc3a0-dev1-dev0` 😂 😩  

We should replace that fragile `sed` hacking thats currently done with filling values into a template file. https://github.com/raiden-network/raiden/blob/5ce09881cb3452cab4e49c131a6c80cc23b63d99/.circleci/config.yml#L598-L599

**Comment by palango** [comment]
> `v0.200.0-rc3a0-dev1-dev0` 😂 😩
> 
> We should replace that fragile `sed` hacking thats currently done with filling values into a template file.
> 
> https://github.com/raiden-network/raiden/blob/5ce09881cb3452cab4e49c131a6c80cc23b63d99/.circleci/config.yml#L598-L599

This is my next release name proposal

**Comment by Dominik1999** [comment]
Is this needed before we release Alderaan? @ulope @palango

**Comment by palango** [comment]
We should at least update it by hand

**Comment by palango** [comment]
Fixed for Alderaan: https://github.com/raiden-network/homebrew-raiden/commit/b497da90f22d1b3ace2dc10696f8c8f158a817c3

We still need to fix the for the future.

**Comment by palango** [comment]
See also https://github.com/raiden-network/raiden/issues/3407

**Comment by ulope** [comment]
We forgot to manually fix the formula for the 1.1.0 release :(
This really needs to be fixed properly...
