### ISSUE TITLE
Adjust Scenarios to mainnet setting RC8

### ISSUE THREAD

**Issue by Dominik1999** [raiden-network/raiden#6061]
## We want to run all scenarios on mainnet
There are some settings that need to be changed for the scenario runs on mainnet. 

- [x] Tokens fixed for fee settings need to be changed 
- [x] Matrix-Server addresses have been changed 
- [x] PFS addresses have been changed
- [x] Deal with lack of PFS without fees
- [x] PFS fees have changed
- [x] Min-settle-timeouts have been changed, therefore all scenarios that wait for settle need to be adjusted 
- [x] Verify that changes don't break the nightly (or fix the breakage)
- [x] Make SP reclaim ERC20 tokens (https://github.com/raiden-network/scenario-player/issues/543)
- [x] Choose correct `balance_per_node` value (https://github.com/raiden-network/raiden/pull/6105)
- [x] Test by running at least one scenario on mainnet
- [x] Avoid timeouts when running scenarios with >=4 nodes (https://github.com/raiden-network/raiden/issues/6106)

**Comment by karlb** [comment]
All changes that are known to be necessary are done. I assume that we will find some additional issues when actually running all scenarios on mainnet, but I suggest opening new issues for those, as this one already grew quite big.
