### ISSUE TITLE
Unknown event error after restart

### ISSUE THREAD

**Issue by konradkonrad** [raiden-network/raiden#6075]
After a node shutdown, on restart I see the following error in the log
```
2020-04-15 14:25:03.693682 [error    ] Unknown event                  [raiden.raiden_event_handler] event_type=<class 'raiden.transfer.architecture.ContractSendEvent'> greenlet_name=rs-handle_events node=0x13e1e3021e5ec6503A17963F933fad63576FC19C
```
And here is the debugger attached to `raiden_service._run`:
```
[0] > /home/konrad/Projects/raiden/raiden/raiden_service.py(394)_run()
-> self.greenlet.name = f"RaidenService._run node:{to_checksum_address(self.address)}"
(Pdb++) p chain_state.pending_transactions
[ContractSendEvent(triggered_by_block_hash=b'\xcd\xf4\xf3\x96\xdb/\x89\xb8\x8f\x92\x80\x87\x83#$5\xea\x91?\xc6!\xc5\x1f\x10\xe0\x88\x10\x12-\xef(e')]
```

**Comment by konradkonrad** [comment]
- try to reproduce with a manually created chainstate

- share db
- replay wal with db
- check `pending_transactions`

**Comment by hackaugusto** [comment]
suggestion of unit test:

- create a `ChainState` with a single transaction in the transaction queue.
- serialize and deserialize the object to and from JSON
- assert the instance type in the deserialized object is the same as the instance in the original one

**Comment by konradkonrad** [comment]
[db_node_13e1e30.zip](https://github.com/raiden-network/raiden/files/4487832/db_node_13e1e30.zip)
