### ISSUE TITLE
Throughput test

### ISSUE THREAD

**Issue by konradkonrad** [raiden-network/raiden#61]
### Tasklist

- [ ] Measure throughput of a node sending **mediated** transactions through `N` channels **without** mediation.
- [ ] The benchmark script must accept an argument for the minimum value for the TPS, and if the given value is not reached it should exit with a status of `1`
  - [ ] The benchmark must be added to the build with the minimum value for TPS set.

**Comment by LefterisJP** [comment]
@konradkonrad Is the throughput test viable in any way or form as of this moment? Should we try to revive it to measure throughput of our product before release so we can have proper benchmarks to support our claims?

**Comment by ulope** [comment]
This has a lot of overlap with #652

**Comment by hackaugusto** [comment]
@ulope yep, but I assume that #652 will not run on the build, correct?

**Comment by LefterisJP** [comment]
@ulope Can we use the scenario player to measure throughput now?

**Comment by ulope** [comment]
Yes, we just have to think about how we want to gather and export that data.

For gathering I see two options that can be added without much work:
- Sum up the runtime of all `transfer` tasks and then divide by number of transfers
- Add a `benchmark` parameter to the `transfer` task it so we have better control over what we measure

I'd prefer variant 2.

As for exporting, writing some form of json report should be enough.

**Comment by Dominik1999** [comment]
@konradkonrad can we close this issue or should we somehow try to revive it?

**Comment by karlb** [comment]
Some scenarios can be considered to be throughput tests.
