### ISSUE TITLE
Adaptive block range doesn't remember the size it should not use

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/raiden#6125]
Geth and Parity can not handle multiple nodes querying logs at the same time, because of this `Implement adaptive range for event polling` #5538 was introduced. The problem is that the current implementation will change the block range in respect to the last query. Meaning that a few nodes together will find the slow range, reduce from that, and in the next iteration increase it again. A run looks like this:

```
{"batch_size": 500, "previous_batch_size": 1000, "event": "Adjusting block batch size", "logger": "raiden.blockchain.utils", "level": "debug", "timestamp": "2020-05-07 08:44:44.250498"}
{"batch_size": 1000, "previous_batch_size": 500, "event": "Adjusting block batch size", "logger": "raiden.blockchain.utils", "level": "debug", "timestamp": "2020-05-07 08:44:45.142952"}
{"batch_size": 2000, "previous_batch_size": 1000, "event": "Adjusting block batch size", "logger": "raiden.blockchain.utils", "level": "debug", "timestamp": "2020-05-07 08:44:45.855426"}
{"batch_size": 1000, "previous_batch_size": 2000, "event": "Adjusting block batch size", "logger": "raiden.blockchain.utils", "level": "debug", "timestamp": "2020-05-07 08:44:53.152439"}
{"batch_size": 500, "previous_batch_size": 1000, "event": "Adjusting block batch size", "logger": "raiden.blockchain.utils", "level": "debug", "timestamp": "2020-05-07 08:45:00.821678"}
{"batch_size": 1000, "previous_batch_size": 500, "event": "Adjusting block batch size", "logger": "raiden.blockchain.utils", "level": "debug", "timestamp": "2020-05-07 08:45:01.345749"}
{"batch_size": 2000, "previous_batch_size": 1000, "event": "Adjusting block batch size", "logger": "raiden.blockchain.utils", "level": "debug", "timestamp": "2020-05-07 08:45:01.928643"}
{"batch_size": 1000, "previous_batch_size": 2000, "event": "Adjusting block batch size", "logger": "raiden.blockchain.utils", "level": "debug", "timestamp": "2020-05-07 08:45:52.224470"}
{"batch_size": 500, "previous_batch_size": 1000, "event": "Adjusting block batch size", "logger": "raiden.blockchain.utils", "level": "debug", "timestamp": "2020-05-07 08:45:59.708131"}
{"batch_size": 1000, "previous_batch_size": 500, "event": "Adjusting block batch size", "logger": "raiden.blockchain.utils", "level": "debug", "timestamp": "2020-05-07 08:46:00.371261"}
```

This fixes the problem of timeouts, but it results in horrible performance.

**Comment by ulope** [comment]
The block size is tuned according to the response time of the query not only timeouts. Therefore it’s expected to oscillate around the “optimal” value.

**Comment by hackaugusto** [comment]
@ulope good point, I don't have the logs to check if there were `Timeout while fetching blocks, decreasing batch size` entries, but it would be interesting to check with a new stress run. If we see regular timeouts than this should probably be done a bit faster, but I suppose these were just frequent changes. 

I still think we should use the state of the art, and there are plenty of algorithms used throughout the internet that we can use instead of relying on a exponentially increasing value. Algorithms like LEDBAT https://tools.ietf.org/html/rfc6817 or RENO https://tools.ietf.org/html/rfc6582 could be used as a battle tested alternatives, there are tons of research around congestion, with documented strengths and weaknesses.

**Comment by ulope** [comment]
Interesting, thanks for the pointers. Will definitely read up on those.

**Comment by karlb** [comment]
Since we optimized the blockchain event fetching, the performance is good as it is. No need to use more fancy algorithms under these circumstances.
