### ISSUE TITLE
Handling of the `opened` block number

### ISSUE THREAD

**Issue by konradkonrad** [raiden-network/raiden#613]
## Problem Definition

Currently there are chances for inconsistent opened block numbers between different representations of the netting channel (which can lead to an invalid nonce of `0` being used when creating a transfer):

- [the opened block for the smart contract is apparently only set after deposit](https://github.com/raiden-network/raiden/blob/a38a114b56f716c1275252e7a8db9fbb24183ae8/raiden/smart_contracts/NettingChannelLibrary.sol#L81-L103)
- in the python layer, the opened block is only updated on `handle_balance`
- the `ChannelEndState.nonce` does not seem to get updated on `set_opened` nor `handle_balance`
- the `ChannelEndState.nonce` calculation only happens in `__init__` but this is not called again during `handle_balance`
- something else/related `Channel.open_event` is nowhere used (other than being set through the `callback_on_opened`)

## Questions

- why only `open` the channel smart contract on `deposit` and not right during construction? we could just set `block.number` during construction of the netting channel
- what's up with those events for the [`Channel.<lifecycle>` stages](https://github.com/raiden-network/raiden/blob/a38a114b56f716c1275252e7a8db9fbb24183ae8/raiden/channel/netting_channel.py#L205-L207) -- are they just there for completeness sake? At least the event for `opened` is nowhere in use.
- should we change the handling of the `ChannelEndState` objects to always be the same instance (right now they are different instances during `RaidenAPI.open` and `handle_channelnew`, because both of these call `RaidenService.register_netting_channel`)? 

## Solution

It might be better not to call `register_netting_channel` in [`RaidenAPI.open`](https://github.com/raiden-network/raiden/blob/c33d5f88b43bea5834cebf76dd32ab8abc0f7c9d/raiden/api/python.py#L148-L153) and instead wait for the channel being registered through the event handler and only then return the registered instance. This would avoid the double call and would also allow to make a [`opened_block != 0` requirement for `ChannelEndState`](https://github.com/raiden-network/raiden/blob/56635add7744d26e36aa4302faa825b7c85c0823/raiden/channel/participant_state.py#L30) (and so avoid any scenario where `nonce` is considered to be `0` ) 

## Tasklist

- [ ] set `self.opened` during construction of the `NettingChannelContract`
- [ ] remove `register_netting_channel` from `RaidenAPI.open` and instead wait for the blockchain event that will register it before returning
- [ ] add an `opened_block > 0` requirement to `ChannelEndState.__init__`

**Comment by konradkonrad** [comment]
@hackaugusto @LefterisJP @czepluch RFC

**Comment by hackaugusto** [comment]
> why only open the channel smart contract on deposit and not right during construction? we could just set block.number during construction of the netting channel

This can be traced back to the [Mock implementation](https://github.com/raiden-network/raiden/blob/f551f21aa46914b816be1169af7bf9e03aff2600/raiden/contracts.py#L49-L50), the idea is that a channel is [not opened if there is no funds in it](https://github.com/raiden-network/raiden/blob/f551f21aa46914b816be1169af7bf9e03aff2600/raiden/contracts.py#L52-L55). I think it's a good idea to move the initialization of the variable to the constructor, but I also think we must renamed it to `created` and use the created block to compute the nonce ranges.

First [netting channel](https://github.com/raiden-network/raiden/blob//raiden/smart_contracts/nettingChannelContract.sol) implementation

> what's up with those events for the Channel.<lifecycle> stages -- are they just there for completeness sake? At least the event for opened is nowhere in use.

`opened` was just for completeness sake, the other events `closed` and `settled` are used for testing, and `closed` was used to kickstart the `updateTransfer`, I'm removing this as part of the [netting channel serialization](https://github.com/raiden-network/raiden/pull/615/)

> It might be better not to call register_netting_channel in RaidenAPI.open and instead wait for the channel being registered through the event handler

Agreed

**Comment by LefterisJP** [comment]
@konradkonrad  As discussed in person I also agree with your suggestions so we should go ahead with them since Augusto seems to also concur.
