### ISSUE TITLE
Add margin to gas prices for mainnet testing - "fast" is not fast enough

### ISSUE THREAD

**Issue by Dominik1999** [raiden-network/raiden#6132]
Make sure that every Raiden Module (Raiden Client, Raiden Services, Scenario Player) adds a margin to the gas price and uses "fast_gas_price_strategy"

### Step 1 - see if that's enough
- [x] Create a gas price strategy that's closer to ethgaspricestations "fast" (https://github.com/raiden-network/scenario-player/pull/557)
- [x] Use that strategy
  - [x] Raiden (https://github.com/raiden-network/scenario-player/pull/557)
  - [x] Services (https://github.com/raiden-network/raiden-services/pull/777)
  - [x] SP (https://github.com/raiden-network/scenario-player/pull/557)
  - [x] SP tools (https://github.com/raiden-network/scenario-player/pull/557)
  - [x] Wizard (https://github.com/raiden-network/raiden-wizard/pull/192 adapted for higher initial speed)
- [x] Update services in RSB, so we can test that on mainnet (https://github.com/raiden-network/raiden-service-bundle/pull/157)
- [ ] Update RSB on mainnet servers (@ulope @fredo )

### Step 2
Check if the above helps enough, otherwise iterate

**Comment by ulope** [comment]
Looks like web3 recently merged a change that will allow weighing more recent blocks higher: https://github.com/ethereum/web3.py/pull/1614

**Comment by palango** [comment]
Most work is done until we test again on mainnet.

Deployment of the updates RSB is tracked in #6140
