### ISSUE TITLE
Can't send payment in any channel

### ISSUE THREAD

**Issue by durkmurder** [raiden-network/raiden#6167]
## Problem Definition

Minted tokens, opened channel on two different test tokens(TTT, TDAI), network goerli. Can't send payment on any of those. On different node I see that payment is in flight and nothing happens. Just stays like this.
Moreover I have closed TTT channel and those payments are still present as in flight.

I am running two nodes from my machine, startup commands:
- alice: `./raiden-v0.200.0-rc8-linux-x86_64 --keystore-path alice-wallet --eth-rpc-endpoint https://goerli.infura.io/v3/INFURA_ID --network-id goerli --datadir raiden-goerli-alice --accept-disclaimer --gas-price fast --environment-type development --routing-mode private --api-address 127.0.0.1:5001 --resolver-endpoint https://127.0.0.1:6001`
- bob: `./raiden-v0.200.0-rc8-linux-x86_64 --keystore-path bob-wallet --eth-rpc-endpoint https://goerli.infura.io/v3/INFURA_ID --network-id goerli --datadir raiden-goerli-bob --accept-disclaimer --gas-price fast --environment-type development --routing-mode private --api-address 127.0.0.1:5002 --resolver-endpoint https://127.0.0.1:6002`

[Logs and dbs are attached](https://drive.google.com/open?id=1gr1zUW09JmMyN8K8XeNv7WZfkHD5dAgT)

- [ ] Split issue in two (before and after restart)

### System Description

18.04.1-Ubuntu SMP Tue Mar 31 04:17:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
Raiden version:
```
{
  "raiden": "0.200.0rc8",
  "raiden_db_version": 26,
  "python_implementation": "CPython",
  "python_version": "3.7.6",
  "system": "Linux 64bit_ELF 5.3.0-46-generic",
  "architecture": "x86_64",
  "distribution": "bundled"
}
```

**Comment by hackaugusto** [comment]
```
{
  "current_user": "@0xa6af4c9e671a7e70eba8fb4509a119471116d5bc:transport.transport04.raiden.network",
  "node": "0xa6af4c9e671a7e70eba8fb4509a119471116d5bc",
  "transport_uuid": "95c09752-5d33-475b-b4f2-680d70d42f24",
  "for_address": "0xbcec907fa6718daa757929cdf65dfa7c9f4b0212",
  "room_ids": [
    "!zzjzpctjhlabrhcrsq:transport.transport04.raiden.network"
  ],
  "event": "room ids for address",
  "logger": "raiden.network.transport.matrix.transport",
  "level": "debug",
  "greenlet_name": "retryqueue node:0xa6af4c9e671a7e70eba8fb4509a119471116d5bc recipient:0xbcec907fa6718daa757929cdf65dfa7c9f4b0212",
  "timestamp": "2020-05-15 08:53:09.590628"
}
{
  "current_user": "@0xa6af4c9e671a7e70eba8fb4509a119471116d5bc:transport.transport04.raiden.network",
  "node": "0xa6af4c9e671a7e70eba8fb4509a119471116d5bc",
  "transport_uuid": "95c09752-5d33-475b-b4f2-680d70d42f24",
  "receiver": "0xbcec907fa6718daa757929cdf65dfa7c9f4b0212",
  "event": "no room for receiver",
  "logger": "raiden.network.transport.matrix.transport",
  "level": "warning",
  "greenlet_name": "retryqueue node:0xa6af4c9e671a7e70eba8fb4509a119471116d5bc recipient:0xbcec907fa6718daa757929cdf65dfa7c9f4b0212",
  "timestamp": "2020-05-15 08:53:09.590958"
}
```
The room is not being ignored as a broadcast room. So it is a presence bug.

**Comment by durkmurder** [comment]
I was running two nodes from local machine if that's matters, and they both were online.

**Comment by Dominik1999** [comment]
Hey @durkmurder we will come back to you next week with this. We are about to release a new version and we need to focus on that for now.

**Comment by ulope** [comment]
Notes for further debugging later:
- Both nodes were restarted at around ~`09:40`, before that they didn't seem to be able to communicate (needs more looking into)
- After the restart this happens:
  - `09:41:57.225048`: `0xa6Af` starts sending `LockedTransfer`s
  - `09:42:02.402038`: `0xBCeC` receives LT
  - `09:42:02.405208`: `0xBCeC` sends `Delivered` back
  - `09:42:02.501524`: `0xa6Af` receives `Delivered`

This now repeats. `0xBCeC` doesn't seems to be processing the transfer for some reason. No log messages are apparent why.

**Comment by palango** [comment]
@durkmurder In the meantime we released a new version of Raiden. Could you please try with [that one](https://github.com/raiden-network/raiden/releases/tag/v1.0.0) again?

**Comment by palango** [comment]
> This now repeats. `0xBCeC` doesn't seems to be processing the transfer for some reason. No log messages are apparent why.

@ulope From what I see the `LockedTransfer` is processed and the `ActionInitTarget` state change dispatched properly. Matrix then tries to send the messages for the resulting events (`SendProcessed` and `SendSecretRequest`) and that fails with:
```json
{
  "wait_for": 5,
  "_exception": "MatrixHttpLibError(\"Something went wrong in PUT requesting https://transport.transport04.raiden.network/_matrix/client/r0/rooms/%21zzJzpCtjhlabRhcRsQ%3Atransport.transport04.raiden.network/send/m.room.message/91589536831348: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))\")",
  "event": "Got http _send exception, waiting then retrying",
  "logger": "raiden.network.transport.matrix.client",
  "level": "debug",
  "greenlet_name": "RetryQueue node:0xBCeC907Fa6718daa757929cdf65dfa7c9F4B0212 recipient:0xa6Af4c9e671a7E70ebA8fb4509a119471116D5BC",
  "timestamp": "2020-05-15 10:00:31.392527"
}
```

**Comment by palango** [comment]
@durkmurder The problem you saw stems from the resolver not working correctly. You enabled the resolver by using `--resolver-endpoint https://127.0.0.1:6001`.
- Was that intentionally?
-  If so, which resolver did you run?

**Comment by durkmurder** [comment]
Right, I am using my own resolver, someway I didn't think that it might be the issue. I will test again without it. Thanks

**Comment by palango** [comment]
@durkmurder Cool, what is the resolver for? Let us know if you run into any other problems.

**Comment by durkmurder** [comment]
Hodl invoices. I will be working on it pretty soon so I will keep you updated if I run into any problems.
