### ISSUE TITLE
Update Raiden Alderaan Mainnet Tutorial in docs.raiden.network

### ISSUE THREAD

**Issue by Dominik1999** [raiden-network/raiden#6179]
We do have an Alderaan Mainnet Tutorial in https://raiden-network.readthedocs.io/en/latest/alderaan_mainnet_tutorial.html

We need to transfer this to the new docs in docs.raiden.network.

The goal is: A user should be able to do a mediated transfer following this tutorial. That includes getting the right tokens, RDN and DAI/W-ETH and depositing into the UDC.

Depositing into the UDC is explained here https://raiden-network.readthedocs.io/en/latest/overview_and_guide.html#depositing-tokens-to-pay-the-services

**Comment by taleldayekh** [comment]
Link to the GitBook version for review: https://docs.raiden.network/using-raiden/alderaan-mainnet-tutorial
