### ISSUE TITLE
Init of created genesis block fails

### ISSUE THREAD

**Issue by mcdee** [raiden-network/raiden#618]
## Problem Definition

Attempting to create a new network using the tools provided in Raiden results in an invalid genesis json file.  Specifically, there appear to be three issues.  The first is that values for the "code" key should start with "0x" but do not.  For example:

    $ python tools/config_builder.py full_genesis > mycustomgenesis.json
    $ geth --datadir /tmp/privategeth init mycustomgenesis.json
    Fatal: invalid genesis file: missing 0x prefix for hex data
    $

This first issue can be overcome (as a hack) with a sed command, but this runs in to a second issue:

    $ python tools/config_builder.py full_genesis > mycustomgenesis.json
    $ sed -e 's/"code": "/"code": "0x/g' mycustomgenesis.json >mycustomgenesis2.json
    $ geth --datadir /tmp/privategeth init mycustomgenesis2.json
    Fatal: invalid genesis file: hex string has length 2, want 64 for Hash
    $

I'm unsure of exactly what is causing the second issue, but it looks like it is due to the key for the  "storage" entries created by the smart contracts being addresses whereas geth expects them to be hashes, for example

    $ cat mycustomgenesis2.json | jq '.alloc[].storage | select(length > 0)'
    {
      "0x06": "0x48302e3100000000000000000000000000000000000000000000000000000008"
    }
    $

Although not a fix, the fact that this is the issue can be shown by removing the storage objects from the genesis JSON:

    $ python tools/config_builder.py full_genesis > mycustomgenesis.json
    $ sed -e 's/"code": "/"code": "0x/g' mycustomgenesis.json >mycustomgenesis2.json
    $ cat mycustomgenesis2.json | jq -c 'del(.alloc[].storage)' >mycustomgenesis3.json
    $ geth --datadir /tmp/privategeth init mycustomgenesis3.json
    Fatal: invalid genesis file: missing 0x prefix for hex data
    $

The third issue is that the 'extraData' field in mk_genesis of tools/genesis_builder.py isn't hex-encoded.  The line

    genesis['extraData'] = CLUSTER_NAME

should be

    genesis['extraData'] = '0x' + CLUSTER_NAME.encode('hex')

At which point the chain can be created:

    $ python tools/config_builder.py full_genesis > mycustomgenesis.json
    $ sed -e 's/"code": "/"code": "0x/g' mycustomgenesis.json >mycustomgenesis2.json
    $ cat mycustomgenesis2.json | jq -c 'del(.alloc[].storage)' >mycustomgenesis3.json
    $ geth --datadir /tmp/privategeth init mycustomgenesis3.json
    WARN [05-25|12:36:10] No etherbase set and no accounts found as default 
    INFO [05-25|12:36:10] Allocated cache and file handles         database=/tmp/privategeth/geth/chaindata cache=16 handles=16
    INFO [05-25|12:36:10] Successfully wrote genesis state         database=chaindata                       hash=a523ae…454e0c
    INFO [05-25|12:36:10] Allocated cache and file handles         database=/tmp/privategeth/geth/lightchaindata cache=16 handles=16
    INFO [05-25|12:36:10] Successfully wrote genesis state         database=lightchaindata                       hash=a523ae…454e0c
    $

## Tasklist

- [ ] Ensure that "code" values are written as correct hex starting with '0x'
- [ ] Ensure that storage keys and values are written in a way suitable for geth to import
- [ ] Merge pending PR to fix creation of 'extraData' field when creating the genesis json

### System Description

Raiden from master
geth 1.6.1-stable-021c3c28 running on linux (also tested with master 1.6.2-unstable-b596b4ba)
All Python requirements taken from requirements.txt / requirements-dev.txt

**Comment by LefterisJP** [comment]
Thank you @mcdee. Your PR: https://github.com/raiden-network/raiden/pull/619
should have addressed the issue.
