### ISSUE TITLE
Better handle/explain potential problems with small transfers

### ISSUE THREAD

**Issue by Dominik1999** [raiden-network/raiden#6188]
## Background

We need to execute manual tests with WETH as well. It looks like the imbalance fee behaves differently in that token network.

I had 3 nodes with somewhat balanced channels (0.0003 <-> 0.00015 , 0.00015 <-> 0.0003) and I **cannot** send 1 wei due to 

```
Payment couldn't be completed because: none of the available routes could be used and at least one of them exceeded the maximum fee limit
``` 

## To do
- [x] find out and explain why one can send 1 * 10 ^ -18 DAI but not W-ETH with current settings (we had the wrong DAI address, see https://github.com/raiden-network/raiden/pull/6191)
- [x] explain with example in release blogpost 
- [x] explain this in docs.raiden.network (https://github.com/raiden-network/raiden/issues/4696)
- [x] show in old WebUI a warning if amount to be sent is smaller than limit @palango and link to mediation fee docs (with example) (https://github.com/raiden-network/webui/issues/432)
- [x] adjust above error message and link to docs.raiden.network and make it clearer (https://github.com/raiden-network/raiden/pull/6199)

**Comment by palango** [comment]
Ca you attach thee logs?

**Comment by Dominik1999** [comment]
[Node Logs RC9 WETH fail.zip](https://github.com/raiden-network/raiden/files/4675799/Node.Logs.RC9.WETH.fail.zip)

It should be reproducible as well

**Comment by Dominik1999** [comment]
[Raiden Node Logs RC9 WETH Error.zip](https://github.com/raiden-network/raiden/files/4675900/Raiden.Node.Logs.RC9.WETH.Error.zip)

**Comment by palango** [comment]
This is expected behaviour.

We have default fees enabled (proportional fees and imbalance fees, capped) and even flat fees for WETH and DAI. (https://github.com/raiden-network/raiden/pull/4802/commits/1fc742b66627fb96a781b46617e87daeb563e48a#diff-14a4915b775dfbab039e080a28553d78R74-R75)

```py
DEFAULT_DAI_FLAT_FEE = 10 ** 12
DEFAULT_WETH_FLAT_FEE = 10 ** 10
```

Is https://github.com/raiden-network/raiden/issues/4751 we decided that transfers which fees would surpass 20% of the transferred amount would be blocked. This is what happened to you.

We need a better UI for this and fees in general, but we won't change the before Alderaan.

**Comment by Dominik1999** [comment]
perfect, thank you. Then we need to explain that to a user quite prominently and with examples. What is the amount a user could send if he deposits x?

**Comment by palango** [comment]
Yes, we need to explain that better.

> What is the amount a user could send if he has x in the channel?

Everything should work fine in a direct channel. The above restriction only apply to mediated payments.

**Comment by Dominik1999** [comment]
Warning in WebUI implemented in https://github.com/raiden-network/webui/pull/434
