### ISSUE TITLE
Add Alderaan default values into the docs

### ISSUE THREAD

**Issue by czepluch** [raiden-network/raiden#6196]
Alderaan is deployed with some default values. These should be reflected in the docs. The values can be found here: https://github.com/raiden-network/team/issues/541

**Comment by Dominik1999** [comment]
OK we have reflected some default values in the docs now. 
- Default values in the client for the services https://docs.raiden.network/installation/starting-raiden-manually#certain-defaults-for-the-usage-of-the-raiden-services-are-set
- Default values for mediation fees https://docs.raiden.network/using-raiden/mediation-fees#default-fee-schedule

**Comment by Dominik1999** [comment]
Smart contracts default values are not reflected in the docs now

**Comment by czepluch** [comment]
Okay. This should be fine.
