### ISSUE TITLE
Broken raiden/raiden_service.py::message_refundtransfer

### ISSUE THREAD

**Issue by konradkonrad** [raiden-network/raiden#620]
## Problem Definition

Running `pytest -s --log-config=":DEBUG" raiden/tests/unit/test_transfer.py` reveals that there is an expected property missing in the `RefundTransfer` class:

```
INFO:raiden.raiden_service	message received message=<RefundTransfer [msghash=765e72fd]>
ERROR:raiden.network.protocol	unexpected exception raised. 
Traceback (most recent call last):
  File "/home/konrad/Projects/raiden/raiden/network/protocol.py", line 358, in receive
    self.raiden.on_message(message, echohash)
  File "/home/konrad/Projects/raiden/raiden/raiden_service.py", line 823, in on_message
    self.message_refundtransfer(message)
  File "/home/konrad/Projects/raiden/raiden/raiden_service.py", line 905, in message_refundtransfer
    target = message.target
AttributeError: 'RefundTransfer' object has no attribute 'target'
```

There is one more issue in the `raiden/raiden_service.py::message_refundtransfer` method:

https://github.com/raiden-network/raiden/blob/master/raiden/raiden_service.py#L903-L914 incorrectly expects a single value to be stored in the `identifier_to_statemanagers` dictionary (it maps lists of state managers to identifiers instead.

TODO:
- [x] add the missing `target` attribute
- [x] fix handling of state manager list: loop through the list
- [x] add a test that would have seen this issue!

**Comment by hackaugusto** [comment]
Fixed by: https://github.com/raiden-network/raiden/pull/680 and https://github.com/raiden-network/raiden/pull/643
