### ISSUE TITLE
Add install guide without the Wizard to the docs

### ISSUE THREAD

**Issue by czepluch** [raiden-network/raiden#6201]
The new version of the docs does not have a guide for installing Raiden without the Wizard. I think the Wizard is nice, but ideally people should install Raiden themselves and there should definitely be a guide on how to do this along the lines of the one in the old docs that can be seen here: https://raiden-network.readthedocs.io/en/latest/overview_and_guide.html

**Comment by Dominik1999** [comment]
This is supposed to be the Alderaan Mainnet Tutorial. The Wizard should be explained in the Quick-Start section.

**Comment by Dominik1999** [comment]
It should be this section https://docs.raiden.network/using-raiden/alderaan-mainnet-tutorial

**Comment by czepluch** [comment]
I think this should also include the "Firing it up" part from the old docs.

**Comment by karlb** [comment]
See https://raiden-network.readthedocs.io/en/stable/overview_and_guide.html#and-2-the-synced-ethereum-node-keystore
