### ISSUE TITLE
Add "Requirements for Safe Usage" to the new docs

### ISSUE THREAD

**Issue by czepluch** [raiden-network/raiden#6202]
The old docs used to have a section for Safe Usage. I cannot find this in the new docs. I think it is important from all perspectives to have this as part of the doc. It will help ensure that users don't run into weird problems and it will help users understand some of the current limitation and out side factors that might affect the use of Raiden.  

The old docs section about this can be found here: https://raiden-network.readthedocs.io/en/latest/overview_and_guide.html#requirements-for-safe-usage

**Comment by czepluch** [comment]
Who ever implements this, just reach out and I can give a couple of more point to the list. We should also remove the one about Raiden having to always be online.

**Comment by Dominik1999** [comment]
We now use the list under **Important security notes for usage** https://docs.google.com/document/d/12lXtTaWrLF3cUwAYHr7AFrTkekM_gzUqY0Jp6p6JZlw/edit#heading=h.2ai5ko8jufu7

**Comment by czepluch** [comment]
Yes, that should suffice. And also that is nice since we then are consistent.
