### ISSUE TITLE
Reduce time for initial sync by providing a JSON

### ISSUE THREAD

**Issue by Dominik1999** [raiden-network/raiden#6209]
## Goal
Initial sync, especially on mainnet, does take a long time and it will get worse in the future. We need to tackle that problem for testing and usability.

## Approach
We (tbd) provide a JSON containing events of our smart contracts for download. This JSON will be created periodically.

After we have decided to remove internal routing, this issue might not be needed anymore, since we do not have to fetch so many events. 

## Potential Issues
- [ ] Safety, we sign the JSON and clients can opt-out
- [ ] Legal implication, clarify with Jake, write him an email with the approach

**Comment by fredo** [comment]
Alternative Approaches: 

- Probing the contract for address tuples (Potential Addresses from Discovery Room)
- PFS providing the State for a little fee

**Comment by karlb** [comment]
The script to create snapshots is at https://github.com/raiden-network/raiden/blob/develop/tools/generate_snapshot.py

**Comment by karlb** [comment]
See also https://github.com/raiden-network/raiden-contracts/issues/705 for previous thoughts on this problem area.

**Comment by Dominik1999** [comment]
Anyblock can provide help here, meaning they could host the JSON file or even allow to query those events initially with their elastic search engine. We will contract Anyblock when this issue is finally designed.

**Comment by karlb** [comment]
Closed in favor of https://github.com/raiden-network/raiden/issues/6497.
