### ISSUE TITLE
Missing broadcast rooms should not crash Raiden

### ISSUE THREAD

**Issue by ulope** [raiden-network/raiden#6212]
## Problem Definition

Raiden needs several Matrix broadcast rooms (discovery, pfs, ms) to work.
These are being created server-side which means that a misconfigured server or one just joining the federation may not have these (yet).

[Currently this leads to a crash with a `RaidenUnrecoverableError`](https://github.com/raiden-network/raiden/blob/07b21ac2bf8a935e26347267b2379e63726e630b/raiden/network/transport/matrix/utils.py#L548-L547)

In cases where the user explicitly selected a matrix server (via config file or cli option) this is fine.

However when Raiden is autoselecting a server it's problematic since the user may not easily get out of this situation if the misconfigured server is consistently the 'fastest' during server selection.

## Possible solutions

Unfortunately in the current architecture sever selection is performed at initialization time while login and broadcast room joining is done at start. This means it's not straightforward so re-select another server. 

Some testing would need to be done how and if this can be solved straight forward.

**Comment by karlb** [comment]
See also https://github.com/raiden-network/raiden/issues/5263

**Comment by fredo** [comment]
Can this be closed now since we only have one room left and we expect to have this room on each server? 

Or is it possible, that the server is up, but not yet accepted from the federation and therefore does not have the room yet (I guess in this case the server should not be in `acitve_servers`, right?)

**Comment by karlb** [comment]
> Or is it possible, that the server is up, but not yet accepted from the federation and therefore does not have the room yet (I guess in this case the server should not be in acitve_servers, right?)

This is also my understanding. Let's close this.
