### ISSUE TITLE
Payment couldn’t be completed because: there is no route available

### ISSUE THREAD

**Issue by czepluch** [raiden-network/raiden#6213]
## Problem Definition 

I am experiencing this error:
```
2020-05-28 13:48:23.847916 [error    ] Error processing request       [raiden.api.rest_utils] errors=Payment couldn't be completed because: there is no route available status_code=<HTTPStatus.CONFLICT: 409>
```
whenever I try to make payments. Even direct payments to a node that I know for sure is online gives me this error.

Logs: 
[raiden-debug_2020-05-28T11:09:30.051530.log](https://github.com/raiden-network/raiden/files/4696241/raiden-debug_2020-05-28T11.09.30.051530.log)

This happens with version 1.0.0 of Raiden

I tried restarting my node and this fixed the problem.

**Comment by czepluch** [comment]
The only thing I can think of that I did that might get the node into some unexpected state is that I, while the node was running, deposited to the UDC with the Raiden node as beneficiary, from another node.

**Comment by czepluch** [comment]
Adding logs for the successful run after a restart: 
[raiden-debug_2020-05-28T14:39:55.633521.log](https://github.com/raiden-network/raiden/files/4728997/raiden-debug_2020-05-28T14.39.55.633521.log)

**Comment by konradkonrad** [comment]
From what I can see in the logs, the partner `0xf1f41e5F35E3be655779a55d3544Df1Ad137b7C6` was never seen as online/`REACHABLE`:
```
{
  "transport_uuid": "259e72f2-9f46-4842-9546-e0bb4c20e546",
  "current_user": "@0xf8f857026c39bdea5fcc2eb652dd02a23a07cf13:transport.raiden.dappnode.io",
  "node": "0xf8f857026c39bdea5fcc2eb652dd02a23a07cf13",
  "address": "0xf1f41e5F35E3be655779a55d3544Df1Ad137b7C6",
  "prev_state": "<AddressReachability.UNKNOWN: 3>",
  "state": "<AddressReachability.UNREACHABLE: 2>",
  "last_change": "datetime.datetime(1970, 1, 1, 0, 0)",
  "change_after": "datetime.timedelta(days=18410, seconds=52072, microseconds=344656)",
  "event": "Changing address reachability state",
  "logger": "raiden.network.transport.matrix.utils",
  "level": "debug",
  "greenlet_name": "Greenlet<fn:_health_check_worker>",
  "timestamp": "2020-05-28 12:27:52.344927"
}
{
  "node": "0xF8F857026C39BDeA5Fcc2Eb652DD02A23a07cF13",
  "state_changes": [
    {
      "node_address": "0xf1f41e5f35e3be655779a55d3544df1ad137b7c6",
      "network_state": "UNREACHABLE",
      "_type": "raiden.transfer.state_change.ActionChangeNodeNetworkState"
    }
  ],
  "event": "State changes",
  "logger": "raiden.raiden_service",
  "level": "debug",
  "greenlet_name": "Greenlet<fn:_health_check_worker>",
  "timestamp": "2020-05-28 12:27:52.345746"
}
```

So, at the time of trying the transfer, it was reasonable to [exclude the routes involving the partner](https://github.com/raiden-network/raiden/blob/v1.0.0/raiden/transfer/mediated_transfer/initiator.py#L240-L242).

Another question is, why did the node network state not change before?

**Comment by konradkonrad** [comment]
> Another question is, why did the node network state not change before?

From what I can see, your node seems to have switched transport servers, after the restart:
```
grep transport /tmp/issue6213/raiden-debug_2020-05-28T11.09.30.051530.log|jq|grep current_user|uniq
  "current_user": "@0xf8f857026c39bdea5fcc2eb652dd02a23a07cf13:transport.raiden.dappnode.io",
grep transport /tmp/issue6213/raiden-debug_2020-05-28T14.39.55.633521.log|jq|grep current_user|uniq
  "current_user": "@0xf8f857026c39bdea5fcc2eb652dd02a23a07cf13:transport.mainnet.raiden.anyblock.tools",
```

**Comment by konradkonrad** [comment]
In order to proceed, I'll need to have a filtered look into the pfs logs:
```
docker logs rsb_pfs_1 |& grep "2020-05-28 13:" > /tmp/pfslog_issue6213.txt
```
I would need the `pfslog_issue6213.txt` file from both servers:
- `transport.raiden.dappnode.io`
- `transport.mainnet.raiden.anyblock.tools`

@czepluch @ulope can you guys help me here?

**Comment by vdo** [comment]
I did the log dump in my server and it's empty for that day. I'm uploading the logs and giving them to you via another channel.

**Comment by konradkonrad** [comment]
@vdo just to make sure: the container is called `rsb_pfs_1` on your system, too? I.e.
```
docker ps | grep rsb_pfs_1
```
is not empty?

**Comment by vdo** [comment]
there's no `rsb_pfs_1` package. The name is `raiden-service-bundle_pfs_1`

**Comment by ulope** [comment]
It's usually better to use `docker-compose logs <service-name>` from inside the project directory. That way you don't have to known the exact container name.

**Comment by Dominik1999** [comment]
This issue is now open for two weeks. 

- is this a bug?
- if so, is the bug reproducible? 

if not, please close the issue and reopen if we see that symptom again.

**Comment by konradkonrad** [comment]
- service logs that I saw are empty for the time frame
- no new reports of the issue in the wild

I'd bet on a federation fluke in the initial service deployment, but can't know for sure.
Closing for no further input, sorry @czepluch
