### ISSUE TITLE
Example Payment Request is wrong in Raiden Docs

### ISSUE THREAD

**Issue by fredo** [raiden-network/raiden#6218]
I found that under the following link https://docs.raiden.network/using-raiden-on-mainnet/make-a-payment the example command for making a payment is not correct. 

There is the `target_address` missing

**Comment by palango** [comment]
@fredo I see:
```
curl -i -X POST \
http://localhost:5001/api/v1/payments/0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2/<target_address> \
-H 'Content-Type: application/json' \
--data-raw '{"amount":"42"}'
```

Isn't that right?

**Comment by fredo** [comment]
such a long time ago. Looks good now. closing it
