### ISSUE TITLE
Payment identifier is stated as String in Raiden docs

### ISSUE THREAD

**Issue by fredo** [raiden-network/raiden#6219]
In the API tutorial the identifier is defined as a string, but actually it must be a valid integer. 
At least in v1.0.0, a valid integer must be used as the identifier in the body. 

https://docs.raiden.network/raiden-api-1/api-tutorial/3-make-a-payment

**Comment by palango** [comment]
@fredo Is it only the id, or also the amount?

**Comment by fredo** [comment]
I was only talking about that in the note box identifier is declared as a string. I think it is possible to pass a string if it represents a valid integer. It will not accept the request otherwise

**Comment by palango** [comment]
Fixed as of https://app.gitbook.com/@raiden-network/s/raiden-network/~/drafts/-MBcegSUVx8H81U1whM1/raiden-api-1/api-tutorial/3-make-a-payment/@activity/-MBcfMBGGk_11MyuFMHo
