### ISSUE TITLE
"The monotonic clock must have nanosecond resolution..." exception

### ISSUE THREAD

**Issue by BOR4** [raiden-network/raiden#6224]
![image](https://user-images.githubusercontent.com/40821065/83644119-367a4a80-a5b1-11ea-967a-f9c7d0b84246.png)

Happened to one of the community members. He was nice enough to provide logs:
[raiden-exception-2020-06-03T13-27jx8_wfcj.txt](https://github.com/raiden-network/raiden-wizard/files/4723726/raiden-exception-2020-06-03T13-27jx8_wfcj.txt)

**Comment by konradkonrad** [comment]
@hymner can you try the adjusted command from below and report the result?

> @hymner please run this command and report the result:
> 
```
python -c 'import time; print(time.clock_gettime_ns(time.CLOCK_MONOTONIC_RAW))'
```

**Comment by hymner** [comment]
@konradkonrad result from command: 3857438742600

**Comment by konradkonrad** [comment]
the trailing `00` look suspicious. Could you run it once more?

**Comment by hymner** [comment]
still some zeroes: 4286390247500

**Comment by ulope** [comment]
Can you also run `python -c 'import time; print(time.clock_getres(time.CLOCK_MONOTONIC_RAW))'`?

**Comment by hymner** [comment]
result: 1e-09

**Comment by konradkonrad** [comment]
There seem to be more general clock resolution differences in Windows (independent of using the linux subsystem or not): https://www.python.org/dev/peps/pep-0564/#windows

**Comment by ulope** [comment]
Hm but that's weird. [The assert checks that the resolution is below or equal to `1E-9`](https://github.com/raiden-network/raiden/blob/13ddc687cb5803577c7ab7927b877379b1134895/raiden/storage/ulid.py#L70). Which means it shouldn't have triggered here.

@hymer is that the same python you ran Raiden with?

**Comment by konradkonrad** [comment]
> @hymer is that the same python you ran Raiden with?

it's running from the binary bundled python, so most likely not

**Comment by ulope** [comment]
Ah, didn't read the issue closely enough. 

The bundled version is still built with Python 3.7.0. It could be that this is something that was fixed in one of the later point releases.

**Comment by konradkonrad** [comment]
Further investigating this

**Comment by konradkonrad** [comment]
Further investigating this

**Comment by konradkonrad** [comment]
> result: 1e-09

hmm, now this result is actually weird. I'm testing in a [Win 10 Evaluation VM](https://developer.microsoft.com/en-us/windows/downloads/virtual-machines/), and at least there I get 
```
python3
Python 3.8.2 (default, Mar 13 2020, 10:14:16)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from time import CLOCK_MONOTONIC_RAW, clock_getres
>>> print(clock_getres(CLOCK_MONOTONIC_RAW))
1.0000000000000001e-07
```

which is "correctly" above `1e-09`.

**Comment by hymner** [comment]
I'm also getting that result from same box as earlier:
hymner@CAAHW-00541:~$ python3
Python 3.8.2 (default, Apr 27 2020, 15:53:34)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from time import CLOCK_MONOTONIC_RAW, clock_getres
>>> print(clock_getres(CLOCK_MONOTONIC_RAW))
1.0000000000000001e-07

**Comment by konradkonrad** [comment]
@hackaugusto regarding

https://github.com/raiden-network/raiden/blob/13ddc687cb5803577c7ab7927b877379b1134895/raiden/storage/ulid.py#L65-L69

It seems that the Windows Ubuntu subsystems only offers `microsecond` resolution, which is still below milliseconds. Any reason we couldn't lower the resolution requirement there?
