### ISSUE TITLE
limit and offset applied wrongly to payments endpoint

### ISSUE THREAD

**Issue by manuelwedler** [raiden-network/raiden#6226]
## Proposed solution
- [ ] If true, first filter and then limit
- [ ] Write a proper test for that 

## Problem Definition

There seems to be a bug with the pagination of the `payments` endpoint. 
I experienced the following: While `GET http://localhost:5001/api/v1/payments/0x59105441977ecD9d805A4f5b060E34676F50F806` returns an array of 22 events, `GET http://localhost:4200/api/v1/payments/0x59105441977ecD9d805A4f5b060E34676F50F806?offset=3&limit=4` returns only 3 events. As the limit is set to 4 and there are enough events, I would expect to also get 4 events. 

I checked the response of `GET http://localhost:4200/api/v1/payments` and found out that the 6th event is the only one for a different token. Most probably the issue here is that the limit and offset parameters are applied before the filtering for the token address happens. The order should be the other way round.

### System Description

- client v1.0.0
- Goerli testnet
- development mode

**Comment by Dominik1999** [comment]
We do apply `offset` and `limit` before filtering for the token networks

https://github.com/raiden-network/raiden/blob/87b43344bdd35d21dce65d639925e567a7b7bf6a/raiden/api/python.py#L1148-L1171

I will try to reproduce that bug in a test and then fix it by reverting the order.
