### ISSUE TITLE
Interal routing generates only one route per direct channel

### ISSUE THREAD

**Issue by karlb** [raiden-network/raiden#6227]
Raiden's internal routing generates routes by iterating over all direct partners and calculating the shortest path starting with that partner. When a node is connected to only a single other node (or only that channel has sufficient capacity), this results in only a single route. When that route fails the whole payment fails, even though the network contains other possible routes.

Suggested solution:
- Go through the list of partners in a round robin fashion until a desired number of routes (e.g. 5) has been calculated or all possible routes are found

This issue was found by @marcosmartinez7, see his [gitter message](https://gitter.im/raiden-network/raiden?at=5ed8106222dd444224f89093)/

**Comment by konradkonrad** [comment]
@karlb ready to close this one?

**Comment by karlb** [comment]
Closed by removal of internal routing
