### ISSUE TITLE
Rank routes based on heuristic

### ISSUE THREAD

**Issue by konradkonrad** [raiden-network/raiden#623]
## Problem Definition

Right now the chosen paths/routes/next hops for mediating are ordered by the amount of hops to the target (see "Shortest Path" below). However, this may not be the best heuristic for success. This issue is used to discuss and collect constraints and strategies for the ordering.

Here is a first non-exhaustive list of channel properties to look out for:

### With local view only
Where "local view" means that we only look at channels with our channel partners. Assuming our channels are properly synced, we are able to judge all transient state (current distributable amount) of the channels.

- **Backwards Balance**: if the non-locked channel backwards balance (`distributable`) is lower than the transferred amount, choosing this route will make it impossible for our channel partner to backtrack with a `RefundTransfer`. These channels should be only tried as a last resort.

### With some advanced view
Where "advanced view" implies that we have means to look at channels "further down the road". This could mean knowledge about transient state gained through some discovery mechanism, as well as global "static" state in the blockchain.

- **Channel Age**: the "age" (tbd) of a channel can be used as a proxy for the channel reputation, since misbehaving nodes will have their channels closed.
- **Channel Connectivity**: Nodes with a high connectivity (number of channels) may have a higher likelihood for successful forwarding.
- **Shortest Path**: In principal it is possible to search through the network graph and order the next hops by the remaining route length. However, the search may turn out complex and the channels on the shortest path may not be the best ones when judging the other properties discussed here.

@hackaugusto @heikoheiko @LefterisJP @czepluch 
Please augment and comment!

**Comment by hackaugusto** [comment]
This is being handled by the path finding service: https://github.com/raiden-network/raiden-pathfinding-service/issues/7
