### ISSUE TITLE
Duplicate scenario definition files

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/raiden#6265]
### Problem
Within https://github.com/raiden-network/raiden/tree/develop/raiden/tests/scenarios the same scenarios are stored within the CI folder and in the root folder.

### Proposed solution
As the scenario definition files in https://github.com/raiden-network/raiden/tree/develop/raiden/tests/scenarios are younger than the ones within https://github.com/raiden-network/raiden/tree/develop/raiden/tests/scenarios/ci I would propose to delete the ones within the ci folder.

@nlsdfnbch @Dominik1999

**Comment by nlsdfnbch** [comment]
The files in the ci folders are symlinks to the ones at the scenario root. I'm currently not sure if we can remove them (I believe they may still be required by the nightlies).

**Comment by ulope** [comment]
I'm pretty sure they are used by the nightlies.

@christianbrb Is probably seeing them as duplicates because of Windows.

**Comment by christianbrb** [comment]
@nlsdfnbch @ulope Thanks for your answers :)

I have looked at them through the GitHub interface and have seen now that they are simlinks (eg. https://github.com/raiden-network/raiden/blob/develop/raiden/tests/scenarios/ci/sp1/bf1_basic_functionality.yaml)
