### ISSUE TITLE
Prototype aiortc on Raiden.

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/raiden#6299]
## Abstract

For `Build in WebRTC for sub-second payments` #6198 we decided to use `aiortc`, this issue is about implementing a first prototype. This will be built on the tests done by @fredo on his prototype https://github.com/fredo/aiogevent

## Motivation

https://github.com/raiden-network/raiden/issues/6198 is the goal.

## Specification

For this first prototype, we are targeting two nodes with the same code, IOW, no need for capabilities, nor any need to handle corner cases.

Code to be based on @fredo  's prototype:

- [x] To use the `aiortc` compatibility among gevent's loop and the asyncio library is necessary.
  - [x] The new event loop policy has to be registered early on, to avoid creating a default `epoll` loop, and it has to cover the integration tests, smoke test, and normal execution. [For this reason the event policy should be set just after the patch_all calls](https://github.com/raiden-network/raiden/search?q=patch_all&unscoped_q=patch_all)
  - [ ] @ulope is it needed to extend the [pyinstaller patch?](https://github.com/raiden-network/raiden/blob/f651457b175436b53b9a21978877e96bf0ff6828/tools/pyinstaller_hooks/runtime_gevent_monkey.py)
- [x] The `GMatrixHttpApi` needs a new method to send an `invite`.
- [x] Since capabilities are not going to be used at this stage, opening the channel will be done by default. At this stage the RTC channel should be open in `_maybe_create_room`
- [x] The `GMatrixClient::_handle_response` needs to handle `invite`s and `answer`s. This should be based on the exiting prototype. Each of this needs a separate callback.
- [x] For this first prototype only RTC communication will be enabled, and matrix communication will not be a fallback. This first implementation should use the existing queue, and instead of sending messages [through the matrix room](https://github.com/raiden-network/raiden/blob/255b4beac633bea87aceda520b628c48ef8ccd86/raiden/network/transport/matrix/transport.py#L290-L291), it should use the RTC channel.

## Future steps

- Handle data concurrency among the asyncio kingdom and the gevent land.
- Integration testing with RTC
- Recovering from broken RTC channels. After this stage only one channel is open during `_maybe_create_room_for_address`. A reliable implementation must handle closed RTC channels because of network problems, and user roaming.
- Capabilities are necessary for this, since existing nodes in Alderaan do not suport this. https://github.com/raiden-network/raiden/issues/3283 
  - Alternative: Check the current number of online nodes, if low, we make a new release without capabilities for this.
- Callbacks from asyncio to gevent will not be available, since moving to the `nio` library is a goal, we should convert the existing code from callback based, to a poll base version of the code. Initially this should only be done for `GMatrixClient <-> MatrixTransport` communication.

## Backwards Compatibility

This must be implemented into a `feature` branch. At this stage it is not production complete and not compatible with other clients.

**Comment by fredo** [comment]
It seems that the state of the connection is not consistently updated, when the partner closes the connection. 

In some cases I received an `iceconnectionstatechange` to `failed` in other it stayed at `completed`

It needs further investigation how to properly detect a connection break on the other side. 

One idea would be a self made healthcheck sending messages back and forth

**Comment by fredo** [comment]
A current prototype is worked on in [this branch] (https://github.com/fredo/raiden/tree/web-rtc-proto)

Current status is: 

- Stable running asyncio event loop
- creating webRTC channel via Matrix signalling
- A test performing a transfer passes
- At the teardown a greenlet blocks forever (needs more investigation)

**Comment by fredo** [comment]
First Impressions of the prototype: 

One hop mediated transfers in local network

Using Matrix: 4.0 - 4.9 sec
Using WebRTC: 2.3 - 2.7 sec

One hop mediated transfers with mediator in India

Using WebRTC: ~ 3.5 sec

**Comment by ulope** [comment]
Regarding a pyinstaller patch for aiogevent:
I don't think it's necessary. We should put the registration of the aiogevent policy into the regular Raiden entrypoint (`__main__.py`).

The reason we have the gevent pyinstaller patch is that gevent can't monkeypatch modules after they have been imported (and pyinstaller itself if using parts of the stdlib during startup`).
The same is not true for the aio loop policy since that one will only be used in the transport module.

**Comment by fredo** [comment]
thanks,  @ulope. This issue can be closed. If assumptions did not met we can open a specific issue to that.
