### ISSUE TITLE
Release Raiden and stuff with new WebUI

### ISSUE THREAD

**Issue by Dominik1999** [raiden-network/raiden#6301]
- [x] Create a new contracts Release
- [x] Create a Raiden RC
- [x] Sohan to test with new WebUI
- [x] Create a Wizard RC
- [x] Rename Raiden RC to Raiden Release (Look into the Star Wars Fan Wiki something, something Alderaan)

**Comment by manuelwedler** [comment]
We found two bugs during testing the RC:
- https://github.com/raiden-network/webui/issues/476
- https://github.com/raiden-network/webui/issues/475 / https://github.com/raiden-network/raiden/issues/6318

First one is critical as no POST / PUT requests work with the RC.
