### ISSUE TITLE
Restructure repos according to Git Flow and eliminate automated PR's to Master

### ISSUE THREAD

**Issue by ghost** [raiden-network/raiden#6345]
## Abstract

As it stands, the current non-standard repo structure poses many issues for external developers when it comes to navigating the source, tracking changes and otherwise interacting with this repository as well as other repos in the Raiden eco-system. For instance, if an external developer such as myself should wish to run automated builds against the Master branch (e.g. for the purpose of building custom Docker images), then the fact that the branch is inundated with automated PR's puts me in the position of having to either:

1. Rebuild after every automated PR merged - given the volume of PR's this is intensely wasteful 
2. Filter out the automated PR's - still not a good choice in terms of build and test consistency
3. Manually triggering my own builds based on manual review of merge activity - obviously not an option
4. Waiting for full releases and only running builds against the release - would make it much more difficult to contribute to the repo, but at least can be consistently target by automation, would also prevent someone from being able to anticipate the compatibility of their work with upcoming releases as one can no longer work in parallel

## Motivation

It is my belief that implementation of clean source control structure will greatly improve the ability for developers both internal and external to contribute code, run tests, and improve and extend CI/CD processes and automation. That said, it is also my belief that the current configuration constitutes a critical bottleneck in the development process, and is in need of fixing regardless of the weight of reconfiguration and reintegration tasks involved.

## Specification

**1.  Implement Git Flow:**

Git Flow dictates that PR's to Master should originate strictly from either a Release branch or a Hotfix branch only. Currently the situation is that there is no release branch, with developers merging their Feature branches back to Develop, and those PR's being merged directly to Master -- this is incorrect as the Master branch should reflect the latest approved release; if the code is not contained in the latest release then it belongs in the Release branch:

![image](https://user-images.githubusercontent.com/67315834/85397348-b2820580-b553-11ea-9896-7188b473b630.png)

A PR to the release branch should comprise of at the very least one complete feature implementation, and in most cases more than that when there's a team involved. Keep in mind this doesn't mean that all new features since the last release should come into the Release branch under a single PR -- that's how PR's to Master should look.

**2.  Disable automated PR's to Master:**

The situation is currently that for every PR merged to downstream branches, as PR is also created on the Master branch such that you end up with PR's made to Master that are entirely inappropriate such as:
![image](https://user-images.githubusercontent.com/67315834/85400323-82893100-b558-11ea-8708-c7cccaf609b3.png)

Every one of the above PR's should never have made it to Master, and should instead be collated under parent PR's (each forming and RC) from the Release branch.
PR's on Master should always be essentially manually created, as they should consist only of all changes made since the last full release. At the moment RC's seem to be defined on the Develop branch, likely resulting in regular holdups for developers as delayed RC's prevent implementation of  as well as further butchering the release history.

## Backwards Compatibility

No changes to the protocol but likely to require significant changes in CI/CD processes

**Comment by karlb** [comment]
I'm not sure what you mean with "automated PR's to Master". The PRs in your screenshot are from May 2019, a time at which the development happened on the master branch. During the last 12 months, development PRs have been merged to the develop branch.

**Comment by karlb** [comment]
We don't have automatic commits to master and AFAICS our current process matches git flow (at least in this repo). If you spot any recent actions that deviate from git flow, feel free to reopen.
