### ISSUE TITLE
I as a user do want to send a MonitorRequest if it is not worth it - Naive Approach

### ISSUE THREAD

**Issue by Dominik1999** [raiden-network/raiden#6353]
## Abstract

If `--enable-monitor True` the Raiden Client sends a `MonitorRequest` regardless of having any capacity in the channel. This can lead to an attack. 

## Motivation

In theory, Raiden Client A could open a Channel to Raiden Client B, who runs with monitoring enabled. If Raiden Client A then closes the channel when Raiden Client B is not online anymore, Raiden Client B would pay 5 RDN automatically to a Monitoring Service. Raiden Client A could collude with the Monitoring Services to get RDN for free. 

## Specification

In the future, a user of the Raiden Client should be able to enable monitoring of a specific channel proactively. 

For now, we will implement a naive solution to the problem

Until we invest more time into a more sophisticated Client / MonitoringService feedback solution, we should re-enable a certain threshold value `MONITORING_MIN_CAPACITY`

https://github.com/raiden-network/raiden/blob/fbc816a044e77645f5b75cb261eb01bce1127cf6/raiden/settings.py#L94

The Raiden Client should not send out a MonitorRequest if the channel capacity is below that value. 

We do only need to define values for WETH and DAI, since only those tokens are allowed on Mainnet so far. 

Create a followup issue for the more sophisticated solution

## Backwards Compatibility

This feature is backwards compatible.

**Comment by palango** [comment]
> Until we invest more time into a more sophisticated Client / MonitoringService feedback solution, we should re-enable a certain threshold value `MONITORING_MIN_CAPACITY`

I think event `balance > 0` is a decent fix.

**Comment by palango** [comment]
See also https://github.com/raiden-network/raiden/issues/4951
