### ISSUE TITLE
Support for private key and unlock API. 

### ISSUE THREAD

**Issue by durkmurder** [raiden-network/raiden#6375]
## Abstract

I would like to have a way of using private key instead of keystore file.

## Motivation

I am trying to use raiden node without user interaction, it's clumsy to do it with keystore. Using raw private key would be easier.
Currently I use keystore file and I need to do two things to start the node:
1) Select address
2) Enter password. 

I would like to avoid it.

## Specification

I would need a way to pass private key, probably as startup argument. It makes sense to encrypt key in some way with password, so it's not raw bytes. If the is encrypted user will need to provide a password to decrypt the key. So a new RPC call is needed to provide password. Obviously it has to go via secure channel.

## Backwards Compatibility

Doesn't apply.

**Comment by ulope** [comment]
You can avoid the interactive account selection by combining the `--keystore-path`, `--address` and `--password-file` options (see `--help` for details on those).

**Comment by durkmurder** [comment]
Still it requires to manage keystore file, even if my software doesn't use keystore files...

**Comment by ulope** [comment]
We decided to use keystore files since they provide better at-rest security. Raw private keys are notorious targets for data theft.

Could you expand on your usecase fore preferring them?

**Comment by durkmurder** [comment]
I need private keys mainly because our software is a wallet and manages different types of private keys. Introducing support for keystore is of course possible, just introduces extra level for us.

**Comment by durkmurder** [comment]
What I mean that our wallet operates with raw private keys that are derived from seeds.
