### ISSUE TITLE
Docs update Installation from source requires native dependencies

### ISSUE THREAD

**Issue by fredo** [raiden-network/raiden#6388]
## To update
In order to install raiden from source no native dependencies are mentioned. Upon `make install-dev` pillow failes due to missing dependencies. This is fixed by installing (on ubuntu) `libjpeg-dev`. 

Also the latest link should be updated to the latest release

### ToDos
- [ ] Make a better Description of dependencies when installing from source
- [ ] Update "Download the latest raiden" to the latest release (currently still on 1.0.0)

**Comment by karlb** [comment]
Pillow is a dependency of matrix-synapse, which is only a dev-requirement, so it makes sense to not have this requirement in the documentation for "normal" users. `libjpeg-dev` is also not required if a wheel of pillow is available for install. Will developers need the information to install `libjpeg-dev` or is the error message in that case good enough for a developer to fix it without explanation in the docs?
