### ISSUE TITLE
Check why capping Ethereum client versions is needed and if not, remove upper bound

### ISSUE THREAD

**Issue by Dominik1999** [raiden-network/raiden#6423]
## Unclear why there is an upper bound for Ethereum Clients
In https://github.com/raiden-network/raiden/blob/9bd24b1ca72555e7594540a16438534a00f19620/raiden/constants.py#L184-L187 we cap client versions to an upper bound. Ethereum clients are supposed to be backwards compatible. We need to check why we have this upper bound and if it is not needed, we should remove it. 

## Related issues 
- #6317 
- #6422

**Comment by karlb** [comment]
Having an upper bound on the versions will prevent users from running raiden on potentially incompatible eth clients. If both projects properly observe semantic versioning, then only comparing the major number would be sufficient. Are the any arguments against this approach?

**Comment by karlb** [comment]
Since we do have found compatibility problems in minor version changes, I would suggest that we keep the upper bounds. But we could reduce the error to a warning if this check causes more problems that it solves.

**Comment by Dominik1999** [comment]
That sounds reasonable, replace it to a warning.
