### ISSUE TITLE
Change counter-deposit behaviour

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/raiden#6440]
## Abstract

Change counter-deposit behavior to support the Light Client receiving transfers from well-connected Raiden clients (Hubs)

## Motivation

According to @andrevmatos the likelihood of counter-depositing is high if I open a channel with a Raiden client which has got 3 or 4 channels. 

Using the Light Client it would be beneficial to connect to a Raiden client with a lot of channels (Hub) to just open one channel instead of several ones. 

As a result, I would either have to choose to connect to a client with 3 or 4 channels to get a counter-deposit or to a well-connected client without a counter-deposit.

Related: 
https://github.com/raiden-network/raiden-services/issues/684
https://github.com/raiden-network/light-client/issues/211

CC @karlb

**Comment by karlb** [comment]
We don't do any counter-deposit by default, anymore.
