### ISSUE TITLE
Send Raiden version in user-agent to PFS

### ISSUE THREAD

**Issue by ulope** [raiden-network/raiden#6455]
## Abstract

Send Raiden version in user-agent to PFS

## Motivation

We want to know which versions are being run in the wild.

## Specification

TBD.
Also using a session for the PFS requests would be nice.

## Backwards Compatibility

N/A

**Comment by konradkonrad** [comment]
I'd go with
```
("Raiden/" + "/".join(str(v) for v in version.values())).replace(" ", "-")             

'Raiden/1.1.1.dev125+g8d4028c74/26/CPython/3.7.7/Linux-64bit_ELF-5.7.10-arch1-1/x86_64/source'
```

where `version` is the dictionary with the output of `raiden version`.
