### ISSUE TITLE
Support candidates Gathering `m.call.candidates`

### ISSUE THREAD

**Issue by fredo** [raiden-network/raiden#6475]
# Abstract
By exchanging `offer` and `answer` ICE candidates are submitted as well. Since ICE candidates might change during the connection lifetime caused by roaming or such new candidates can be exchanged by `candidates`. In matrix this is defined with the message type `m.call.candidates`. This could keep a channel alive by changing to new candidates.
In WebRTC standard this is also used to start trying the candidates before receive an `end-of-candidates notification`.

# Feature parity with LC
The light client already supports processing this message.

IMHO this is not a high priority though. If connection breaks also a completely new channel could be created. Furthermore, it is not a high priority to have a very fast rather than a reliable connection.

**Comment by andrevmatos** [comment]
You don't need to gather the candidates, you just need to handle the messages and add them. By not doing it, currently, the PC can't connect with the LC. This is a priority IMO.
