### ISSUE TITLE
Monitor test network

### ISSUE THREAD

**Issue by konradkonrad** [raiden-network/raiden#650]
We need monitoring for the test network.

### Parameters

- load (memory, cpu, storage, network i/o) per physical node
- livelyhood of `raiden` nodes
- livelyhood of `geth` node(s)
- connectivity of `raiden` nodes (number of open channels, balances per channel)
- sent/received transfers (log file or RPCAPI)
- log collection

### Tasklist

- [x] log collection via logstash
- [ ] chose stats collection framework
- [ ] chose monitoring frontend
- [ ] implement the collection for the parameters from above

**Comment by ulope** [comment]
Centralised logging has been implemented via logstash. 
The other todos remain.

**Comment by LefterisJP** [comment]
@ulope What is the status of this issue?

**Comment by ulope** [comment]
Closing this because there is no more test network. In spirit this will live on in the scenario player.
