### ISSUE TITLE
Decide on documentation tool

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden#6517]
Currently there are two sets of documentation. We need to decide on one to go forward and remove the other one.

- There is the sphinx based documentation under `docs`, which is generated and available at https://raiden-network.readthedocs.io/en/latest/
  - Pro:
  - Con:
- There is a more recent documentation based on gitbook available at https://docs.raiden.network/
  - Pro:
  - Con:
    - Not managed in same repo as the source code

## Tasks
- [ ] Decide on a solution to go forward
- [ ] Remove the unused docs

**Comment by karlb** [comment]
We use readthedocs and https://docs.raiden.network/ is a redirect to readthedocs now.
