### ISSUE TITLE
Create scenario player for the test network

### ISSUE THREAD

**Issue by konradkonrad** [raiden-network/raiden#652]
We want a "scenario player" for repeatable directed case testing on the test network. The scenario player should not only allow for planned execution, but also include assertions and reporting of expected outcomes (and failures). The reporting may or may not be resolved by the same means as the general monitoring of the test network #650.

### Scenarios

- interwoven mediated transfers of different tokens to different targets
- interwoven receiving and sending of mediated transfers
- interwoven receiving and sending of mediated and direct transfers
- graceful handling (rerouting) when mediators disappear
- timeout cases, e.g. the initiator of a mediated transfer does _not_ reveal the secret after being contacted by the target

### Tasklist

- [ ] create or chose a framework for scenario creation (descriptive or programmatic)
- [ ] define or chose an outcome assertion description (descriptive or programmatic)
- [ ] create a "player" for running the scenario (needs timed "orchestration" of several nodes)
- [ ] create outcome reporting

**Comment by LefterisJP** [comment]
This is taken out of the initial release of the dev preview.

**Comment by ulope** [comment]
We finally closed this in #2524 🎉
