### ISSUE TITLE
Nightlies not working since 1 month

### ISSUE THREAD

**Issue by Dominik1999** [raiden-network/raiden#6544]
## Problem Definition

At the 21th of July we had the nightlies the last time running according to #monitoring 

We want to see the nightlies run every night. The nightlies were running on https://tower.brainbot.com/ but the server / instance seems down.

**Comment by karlb** [comment]
They can be run manually right now. The tasks to make the changes permanent and trigger automatic runs are described in https://github.com/raiden-network/scenarioplayer.ci.raiden.network/pull/2.
