### ISSUE TITLE
Benchmark WebRTC in different cases

### ISSUE THREAD

**Issue by karlb** [raiden-network/raiden#6547]
In https://github.com/raiden-network/raiden/issues/6198 we implement WebRTC to increase the speed of transfers. But without somewhat reproducible benchmarks, we don't know if we reached the goal of sub second transfers and in which cases.

Things that might make sense to vary across benchmark cases:
- [ ] Number of mediators (direct channel, one mediator, multiple mediators)
- [ ] Time of first transfer vs time of later transfers
- [ ] Time including/excluding PFS
- [ ] Transfer from/to light client instead of python client

Instead of covering all cases in detail, we should find a low-effort way to cover the most important cases.

**Comment by konradkonrad** [comment]
I plan to fix the scenario player's github.com/raiden-network/performance-analysis-tool to show us a metrics per number of hops again.

**Comment by fredo** [comment]
closed in favor of #7232
