### ISSUE TITLE
Release blockchain event handling bug fix on mainnnet

### ISSUE THREAD

**Issue by karlb** [raiden-network/raiden#6549]
https://github.com/raiden-network/raiden/issues/6474 should be fixed in a mainnet release.

- [x] Find out which commits should be cherry picked
- [ ] Merge to master
- [ ] Run scenarios
- [ ] Release

Related PRs:
https://github.com/raiden-network/raiden/pull/6484
https://github.com/raiden-network/raiden/pull/6470
https://github.com/raiden-network/raiden/pull/6469

**Comment by konradkonrad** [comment]
This release should also include the new capabilities, see https://github.com/raiden-network/raiden/pull/6572

**Comment by karlb** [comment]
Closed in favor of https://github.com/raiden-network/raiden/pull/6577 and https://github.com/raiden-network/raiden/issues/6596
