### ISSUE TITLE
WebRTC: Align on signalling message format between LC / PC

### ISSUE THREAD

**Issue by ulope** [raiden-network/raiden#6560]
## Abstract

Continuation of the discussion in https://github.com/raiden-network/raiden/pull/6477#discussion_r491987581

@andrevmatos @fredo and myself had a call to align on the signalling message format for WebRTC.

## Motivation

The current WebRTC signalling implementations in the light client and python client aren't aligned.

## Specification

We will use `m.room.message` with `msgtype` set to `m.notice` messages to exchange the signalling messages.
Details TBD

## Backwards Compatibility

N/A

**Comment by andrevmatos** [comment]
`msgtype: "m.notice"`, as described in spec for signaling. `body` needs to be a string, so we should go with JSON-object serialized strings on this property:
- `{ "type": "offer" | "answer"; "call_id": string; "sdp": string; }`: invite/answer schema
- `{ "type": "candidates"; "call_id": string; "candidates": any[]; }`: candidates exchange
- `{ "type": "hangup"; "call_id": string; }`: hangup signaling event, if implemented

Later we may use some ECIES or other encryption-based validation of p2p connection, and may require adding other properties to these objects for this, maybe even encryption of the payload.

Switching to signaling via plain `m.room.message` events  also enables full communication over `ToDevice` messages, negotiated through its own capability, TBD on a later issue/PR (out of scope of this one).

**Comment by andrevmatos** [comment]
`ToDevice` protocol demonstrated/implemented in the LightClient on https://github.com/raiden-network/light-client/pull/2174

**Comment by fredo** [comment]
closed in favor of [LC](https://github.com/raiden-network/light-client/issues/2158) and #6556
