### ISSUE TITLE
mypy doesn't check tools subdirectories

### ISSUE THREAD

**Issue by ulope** [raiden-network/raiden#6562]
## Problem Definition

Mypy doesn't check some parts of our `tools` folder.
It's actually only "recursive" for Python packages not regular directories (see https://github.com/python/mypy/issues/8548 for details).

The ones currently missing are:
- `tools/debugging` (and it's subdirectories)
- `tools/pre-commit`
- `tools/pyinstaller_hooks`

(And of course those are full of warnings when checked explicitly.)

## Possible solutions

1. Explicitly pass all package roots in the Makefile / CI setup
1. Use some `find` (or equivalent) magic to automatically find package roots
1. Make sure the tools directory tree is a continuous package (i.e. add `__init__.py` files to all sub-directories)

I'm leaning towards 3. as the least disruptive option, however it feels a bit unclean since for example the `pyinstaller_hooks` really aren't part of any package structure.

**Comment by karlb** [comment]
> Make sure the tools directory tree is a continuous package (i.e. add __init__.py files to all sub-directories)

Done.
