### ISSUE TITLE
max_unresponsive_time, send_ping_time not part of the cli app() argument list

### ISSUE THREAD

**Issue by agatsoh** [raiden-network/raiden#658]
## Problem Definition
While starting the raiden cli there is [an error](https://gist.github.com/agatsoh/cbc719783fb8ebdb0cbd6deeeed4dbc0)
Both  `  --max-unresponsive-time` and `--send-ping-time` are missing in the parameter list of `app()` function in cli.py. 
The command that I try to run is 

`(env2) krishna@Krishna:~/raidenforked/raiden$ raiden --eth-rpc-endpoint 127.0.0.1:8545 --registry-contract-address 7d73424a8256c0b2ba245e5d5a3de8820e45f390 --discovery-contract-address 08425d9df219f93d5763c3e85204cb5b4ce33aaa --keystore-path ~/privategeth/keystore --console`

## Tasklist
Add `max_unresponsive_time, send_ping_time` as  arguments in the `app()` function of the cli.py and take care of any subsequent errors that arise thereof.
- [ ] add max_unresponsive_time
- [ ] add send_ping_time

### System Description
Geth Version: 1.5.9-stable
solc Version: 0.4.11+commit.68ef5810.Linux.g++

**Comment by hackaugusto** [comment]
Fixed by: https://github.com/raiden-network/raiden/pull/664
