### ISSUE TITLE
Send `ping` message after establishing web rtc channel

### ISSUE THREAD

**Issue by fredo** [raiden-network/raiden#6585]
## Abstract

The Light Client experienced some odd behavior when creating web rtc channels. Somewhere in the rtc library the channel gets stuck in a hot loop and CPU usage is at maximum. Meanwhile the `readyState` is shown as open, but messages do not get through. Until this bug is fixed, a workaround is to accept a channel only as open when a `ping` message went through. If it doesn't the `WEB_RTC_CHANNEL_TIMEOUT` will drop the channel and start a new attempt. It only happens on the creator's side of the channel.

## Motivation

In order to ensure compatibility between the clients, PC needs to send a ping message in order to accept the channel as open by the LC. Even though the problem has not occured yet in `aiortc`. The PC can simply ignore this message and does not need to react on it.

## Backwards Compatibility

In regards to the PC it is backwards compatible.

**Comment by karlb** [comment]
Won't fix according to https://github.com/raiden-network/raiden/pull/6699#issuecomment-752060305.
