### ISSUE TITLE
bf2: lock expired

### ISSUE THREAD

**Issue by karlb** [raiden-network/raiden#6592]
In bf2, `<TransferTask: {'from': 0, 'to': 3, 'amount': 200000000000000000, 'lock_timeout': 30, 'identifier': 162372100021000016}>` fails with
```
scenario_player.exceptions.RESTAPIStatusMismatchError: HTTP status code "409" while fetching http://127.0.0.1:57277/api/v1/payments/0x59105441977ecD9d805A4f5b060E34676F50F806/0x2a1C2AaEa9D151202DD91Cb6E7b86b2bd2990B4f. Expected 2..: {"errors": "Payment couldn't be completed because: lock expired"}
```

Logs and db: https://drive.google.com/file/d/19_EwaPRicpAgljwDt8T7OlqQ3z8X_JZU/view?usp=sharing

**Comment by konradkonrad** [comment]
### Findings
- The failing payment with identifier `162372100021000016` is never seen by any other node.

**Comment by karlb** [comment]
Most likely caused by https://github.com/raiden-network/raiden/issues/6612.
