### ISSUE TITLE
Transaction rejected because the nonce has been already mined

### ISSUE THREAD

**Issue by taleldayekh** [raiden-network/raiden#6626]
## Problem Definition

When minting TestTokens using the WebUI my Raiden Python node suddenly shut down with the following messages in the terminal. The selected account was only used by this node and the expected outcome was for the minting to succeed without the node getting killed.

```
Traceback (most recent call last):
  File "raiden/network/rpc/client.py", line 1315, in transact
  File "web3/eth.py", line 395, in sendRawTransaction
  File "web3/manager.py", line 153, in request_blocking
ValueError: {'code': -32000, 'message': 'nonce too low'}
```
```
Transaction rejected because the nonce has been already mined.. Please make sure that this Raiden node is the only user of the selected account
```
## Logs
[logs.zip](https://github.com/raiden-network/raiden/files/5429814/logs.zip)

**Comment by karlb** [comment]
Let's rather spend our time on more recent bug reports.
