### ISSUE TITLE
No `--version` argument

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden#6669]
Raiden has a `version` subcommand, but no `--version` or `-v` flag. 

I think it's common to have a verison flag, and I'd argue we should change from the subcommand to the flag.

**Comment by ulope** [comment]
I don't think there's any reason not to add a version flag, but I'd keep the `version` command since it outputs the version (and additional useful information about the installation / system) in machine readable format.

**Comment by konradkonrad** [comment]
Does this need any further input?

**Comment by palango** [comment]
> Does this need any further input?

My take is `raiden version` should continue to work, but `raiden --version` should also print a short version and exit afterwards.
