### ISSUE TITLE
Reduce aiortc dependencies

### ISSUE THREAD

**Issue by karlb** [raiden-network/raiden#6672]
aiortc depends on ffmpeg, but we don't use that part of the functionality at all. Can those dependencies be removed from aiortc?
They have an option to skip deps when building the documentation. Can this be used by us, too?

**Comment by ezdac** [comment]
A short summary of the current findings for later reference:

There is a `READTHEDOCS` env variable that excludes `av` and the audio codec cffi dependencies from the install process:
https://github.com/aiortc/aiortc/blob/2362e6d1f0c730a0f8c387bbea76546775ad2fe8/setup.py#L31

If I don't allow wheels for the package, this works to exclude `av` from the installed packages:
```sh
READTHEDOCS=True pip install aiortc --no-binary "aiortc,"
```

Unfortunately the `av` module is needed even if you import the classes used in Raiden that don't rely on the video encoding:
```
In [2]: from aiortc.rtcdatachannel import RTCDataChannel
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-437cb2b5dba6> in <module>
----> 1 from aiortc.rtcdatachannel import RTCDataChannel

~/job/bbot/aiortc/.venv/lib/python3.8/site-packages/aiortc/__init__.py in <module>
      3 from .about import __version__
      4 from .exceptions import InvalidAccessError, InvalidStateError
----> 5 from .mediastreams import MediaStreamTrack, VideoStreamTrack
      6 from .rtcconfiguration import RTCConfiguration, RTCIceServer
      7 from .rtcdatachannel import RTCDataChannel, RTCDataChannelParameters

~/job/bbot/aiortc/.venv/lib/python3.8/site-packages/aiortc/mediastreams.py in <module>
      6 from typing import Tuple
      7
----> 8 from av import AudioFrame, VideoFrame
      9 from av.frame import Frame
     10 from pyee import AsyncIOEventEmitter

ModuleNotFoundError: No module named 'av'
```
They get by this by mocking the modules during building of the docs:
https://github.com/aiortc/aiortc/blob/main/docs/conf.py#L67-L72


Also, we argued that passing an environment variable through all our tooling might be cumebersome.

**Comment by ezdac** [comment]
Since `aiortc` is meant as a python implementation of the WebRTC standard, the media-stack support is considered to be essential and there are no plans to split data-channel only functionality into a `core` package at the moment.
For more insight on their reasoning see the references in https://github.com/aiortc/aiortc/issues/436.
We decided to keep the dependencies and try to fix the builds of failing platforms (which concerns only ARM AFAIK)
