### ISSUE TITLE
Ping with toDevice messages to determine presence

### ISSUE THREAD

**Issue by karlb** [raiden-network/raiden#6677]
The presence information provided by synapse does not work reliably for us. We could send toDevice messages to other nodes to check if they are online.

**Comment by andrevmatos** [comment]
Please, not. Let's not exchange messages to know about presence. We've that in the past with UDP protocol, and it gave us a lot of trouble.
Instead, I'm working on a proposal to connect WebRTC channels without relying on presence, and then using its state as a complement to presence.

**Comment by karlb** [comment]
This issue is mostly the result of running out of options to make the presence detection reliable, so alternative solutions are very welcome! When making a suggestions, please take into account that the PFS needs to know the presences, too.

**Comment by ezdac** [comment]
It seems that this is no optimal solution and will not be needed any longer, since the presence seems to be more stable now?

**Comment by ezdac** [comment]
Will close this, feel free to open again if significant presence problems reoccur.
