### ISSUE TITLE
Check if our custom gevent-joinall pylint rule is still necessary

### ISSUE THREAD

**Issue by ulope** [raiden-network/raiden#6683]
## Problem Definition

We have a custom pylint checker (`gevent-joinall`) that enforces using sets as the argument to `gevent.joinall(...)`:

https://github.com/raiden-network/raiden/blob/c1ab0e6ea6289c5853247700d066f1dcc9e1cf87/tools/pylint/gevent_checker.py#L143

This is because a bug in gevent (used to?) cause a deadlock if the same greenlet was passed multiple times (for example in a list).

From reading [this ancient issue](https://github.com/gevent/gevent/issues/64) it seems that the cause was an inconsistency in how gevent handled links internally. Since then the `AbstractLinkable` base class has been introduced which seems to have removed that problem.

In any case this runs without hanging:
```
import gevent
from gevent.event import AsyncResult


def s(r):
    print('sleeping', r)
    gevent.sleep(1)
    r.set(1)
    print('awake', r)


r1 = AsyncResult()
g1 = gevent.spawn(s, r1)

gevent.joinall([g1, r1, g1, r1], raise_error=True)
g2 = gevent.spawn(s, r1)

gevent.joinall([g1, r1, g1, r1, g2], raise_error=True)

print("Done")
```

Therefore I vote for removing that pylint check. 
Any opinions?

**Comment by konradkonrad** [comment]
If the above shows the buggy behavior in a previous version I'd be convinced.

**Comment by ulope** [comment]
Yes it does: https://asciinema.org/a/JkNKdPPtbh1wDEVo2g9nXrISw

**Comment by konradkonrad** [comment]
perfect!
