### ISSUE TITLE
Block raiden startup until the ethereum client is fully synchronized

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/raiden#670]
## Problem Definition

Raiden may be connected to an ethereum client that is not fully synchronized, under this circumstance the ethereum client will not provided the latest events required by the Raiden node, this would effectively make Raiden unaware of channel changes and could lead to token loss.

## Solution

Wait for the geth node to fully synchronize before starting to operate.

This is only a proper solution if the Raiden node is starting fresh, i.e. the first run without pending transfers, and it's only as a tool to prevent bad behavior, it's not sufficient for scenarios were the ethereum client had it's database deleted, we cannot prevent that from happening and there is not way to recover aside from wait until the database is synchronized, for this scenario third parties are required to provide safe operation and are outside of the scope of this issue.

## Tasklist

- [ ] On startup query the ethereum node and hold until it's synchronized.

**Comment by LefterisJP** [comment]
Also note that to determine syncing and if the user is using a light node then the `eth_syncing` call does not seem to work.

**Comment by roynalnaruto** [comment]
@hackaugusto @LefterisJP I would like to work on this issue.

**Comment by LefterisJP** [comment]
@roynalnaruto Sorry for getting back later to you. Please go ahead if you want to.

**Comment by LefterisJP** [comment]
It's fixed by #882
