### ISSUE TITLE
Nightly builds failing

### ISSUE THREAD

**Issue by karlb** [raiden-network/raiden#6705]
See
* https://app.circleci.com/pipelines/github/raiden-network/raiden/10458/workflows/e6c73aec-de67-4911-ae01-6158e3ac704f/jobs/156348
* https://app.circleci.com/pipelines/github/raiden-network/raiden/10458/workflows/e6c73aec-de67-4911-ae01-6158e3ac704f/jobs/156372

**Comment by ezdac** [comment]
# WIP
## findings for failing  MacOS nightlies:
- `web3` recently [upgraded](https://github.com/ethereum/web3.py/commit/cff084ed6c935d1fac20ac0e7551c14f883c5eb6) to `ipfshttpclient==0.7.0a1` 
- the MacOS distiller on CircleCI uses python 3.7.0 which is incompatible with this pre-release:
```
    Link requires a different Python (3.7.0 not in: '>=3.5.4,!=3.6.0,!=3.6.1,!=3.7.0,!=3.7.1'): 
https://files.pythonhosted.org/packages/43/85/e77debad71477195cb67f3e6c84b65d23297c50a5960321909fd812b1e87/ipfshttpclient-0.7.0a1-py3-none-any.whl#sha256=a45fb0ef087d71647c77b02e0cb3a033045377f134971dfcdc1c6f21cd8ad87c (from https://pypi.org/simple/ipfshttpclient/) (requires-python:>=3.5.4,!=3.6.0,!=3.6.1,!=3.7.0,!=3.7.1)
```
