### ISSUE TITLE
Is the correct participant doing the unlock?

### ISSUE THREAD

**Issue by karlb** [raiden-network/raiden#6706]
@mauricioirace [in gitter](https://gitter.im/raiden-network/raiden?at=5fbff163846eed6b67aece77):

> Let's assume we have a channel between A and B. There is a locked amount of X tokens from A to B, and the secret has been registered on chain.
What the documentation says is that after the channel has been settled, B will unlock the tokens on chain, and they we'll be transferred to it
> But debugging the code we note that A is the one which calls the unlock method of the contract, instead of B (granting the tokens to B, anyway).
> Indeed, we saw that both restore the channel_state to an state when the secret was not yet registered, forcing A and B to think B cannot claim the tokens (What it actually can).
> Is this correct or we're missing something? Is that the expected behaviour?

To have nodes act to their on benefit, I would expect the following behavior:
* When the secret is registered on-chain, the receiver (B) should call unlock
* When the secret is not registered, the locked amount can be reclaimed by the sender (A), so the sender should call unlock

We have tests checking that the unlocks happen, but I could not find a check which node calls the unlock. So we might miss cases where the wrong node calls unlock.

**Comment by Dominik1999** [comment]
Is this a critical bug, meaning that someone can lose money?

**Comment by karlb** [comment]
The only money that can be lost are the transaction fees for an unlock that won't benefit you. Apart from that, all tokens are safe in the contract. Raiden might just not unlock that for you automatically. That's highly inconvenient, but not really dangerous.
