### ISSUE TITLE
Add API endpoint for transfer with given route

### ISSUE THREAD

**Issue by karlb** [raiden-network/raiden#6709]
Add a new endpoint to Raiden's REST API (or extend the existing one) to trigger a payment with a route given in the request payload.

Use cases:
* External routing algorithms
* Debugging
* Performance measurements

# To be done
- [x] extend API
- [x] Integration test
- [x] Add to documentation

**Comment by karlb** [comment]
I suggest that the endpoint takes route information in exactly the same format as PFSes return it. This will allow passing in matrix user names and reduces the amount of code we have to add.

This issue will also help us to fulfill the TGE obligations, since it reduces the dependency on the PFS.

**Comment by fredo** [comment]
Question to be answered: if metadata are incomplete, should the missing data be fetched from the PFS?

**Comment by karlb** [comment]
I would go with exactly the same behaviour as with a real PFS response (which I assume means "no" to your question) for now. We can still refine it and be more flexible in the future. It is easier to start strict and allow more input as needed.

**Comment by karlb** [comment]
Implemented in https://github.com/raiden-network/raiden/pull/7349.

For documentation see https://raiden-network.readthedocs.io/en/latest/rest_api.html#post--api-(version)-payments-(token_address)-(target_address)
