### ISSUE TITLE
Handle potential race with blocknumber in log_events()

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#672]
## Problem Definition

At the moment in [`transaction_log.log_events()`](https://github.com/raiden-network/raiden/blob/a525609403bcc20c453de9e15b713064336a51e9/raiden/raiden_service.py#L1344) we get the block number by using `get_block_number()` function from the raiden service.

By the time we reach the logging stage a new block could have been mined and we would be using that instead of the actual block in which the event occured.

## Solution

Instead of just adding the block number only at the time of logging, make sure that each task knows the current block number and its value is updated by the Block state change. That can be achieved in one of 2 ways:

1. Adding the block_number as an attribute to all events generated by state change transitions
2. Passing the block_number around by wrapping it around the event as they are.

## Tasklist

- [ ] Make sure each task knows the current block number.

**Comment by hackaugusto** [comment]
This was solved by the Wal class, the block_number is given as an argument:

https://github.com/raiden-network/raiden/blob/3686b3275ff7c0b669a6d5e2b34109c3bdf1921d/raiden/storage/wal.py#L24-L40
