### ISSUE TITLE
Explicitly set presence with different status message after coming online

### ISSUE THREAD

**Issue by fredo** [raiden-network/raiden#6752]
## Abstract

As described by @andrevmatos [here](https://github.com/raiden-network/raiden/issues/6724#issuecomment-747528603) setting the presence status explicitly by calling the API endpoint triggers a new propagation of the presence if and only if the presence event is different than before.

Luckily, a different `status_msg` value already triggers the new propagation. Since we experience the presence bug upon high load (multiple users coming online and creating rooms, creating traffic), setting the presence at a different point in time helps to repropagate. 

If users set there presence somewhat undeterministacally, calling the presence api endpoint at different times, helps to distribute load over a longer period of time thus making it more unlikely to trigger the bug again.

**Comment by karlb** [comment]
From what I can see, this is done by https://github.com/raiden-network/raiden/pull/6755.
