### ISSUE TITLE
Monitoring Request does not reach MS

### ISSUE THREAD

**Issue by karlb** [raiden-network/raiden#6756]
In December we had multiple ms1 scenarios fail with `scenario_player.exceptions.ScenarioAssertionError: Expected number of events (1) did not match the number of events found (0)`. The failure was last observed on 2020-12-10.

Relevant observations:
* This happened for both the Python Client and Light Client, so it was probably triggered by some infrastructure change (matrix server?).
* It looks like the client does not send the monitor request.
* Rate limiting on the matrix side might prevent sending of messages without an immediate error on the client side.

**Comment by konradkonrad** [comment]
See
https://github.com/raiden-network/raiden/issues/6760#issuecomment-756006384

I suggest to guard the broadcast queue from being shut down in a non-empty state.

This doesn't solve the infrastructure side of things (sending to a room should not take as long as it sometimes does), but secures the client from shutting down without having issued a monitoring request.

**Comment by karlb** [comment]
I suggest the following steps:
- [ ] Remove `wait_blocks: 1` from MS1
- [ ] Check that the scenario (usually) fails now
- [ ] Wait for broadcast queue to be processed before shutting down
- [ ] Check the MS1 reliably succeeds now
