### ISSUE TITLE
Check Raiden client behaviour when synapse rate limits

### ISSUE THREAD

**Issue by karlb** [raiden-network/raiden#6760]
- [ ] set low rate limiting threshold @ulope 
- [ ] trigger rate limiting and check results @konradkonrad @ezdac 

This might give us insights regarding https://github.com/raiden-network/raiden/issues/6756

**Comment by konradkonrad** [comment]
Testbranch in https://github.com/konradkonrad/raiden/tree/ratelimit_test_broadcast

**Comment by konradkonrad** [comment]
We saw more failures, even without any rate limiting kicking in. Current understanding is the actual sending of the message
https://github.com/raiden-network/raiden/blob/fa7304257b763e05ad1e6c98b0ebf6d4c3c32620/raiden/network/transport/matrix/transport.py#L799
can take a long time (sometimes > 10s) to succeed.

This blocks any further broadcast messages from being processed.

If the node shuts down in the meantime, this can lead to messages being lost/never being sent (see https://github.com/raiden-network/raiden/issues/6723#issuecomment-742523229).
