### ISSUE TITLE
Monitoring not enabled by default in production mode

### ISSUE THREAD

**Issue by ulope** [raiden-network/raiden#6779]
## Problem Definition

The `--enable-monitoring` option defaults to `False`.
On mainnet / production mode it needs to be enabled by default to provide a safe default for users and prevent possible loss of funds.

The flag should be changed to a binary choice (e.g. `--enable-monitoring` / `--no-enable-monitoring`).

We need to work out how to implement this with the current system.

**Comment by Dominik1999** [comment]
It was a decision to default monitoring to false, see https://github.com/raiden-network/team/issues/541

The reason is that users need more RDN to be able to start the Raiden Client. We can change that now, then you would also need to change that in the Raiden Wizard. Or we just inform the user that monitoring is a feature that can be used and set to be True.

**Comment by ezdac** [comment]
Is this a possible legal decision, or do we have free hand in choosing this?
I would argue that most commonly, the end-user will want to enable monitoring.

What about leaving it default off for now, but letting the user confirm an additional prompt if the value was not explicitly chosen (by e.g. `--no-enable-monitoring`)?
If the prompt is not desired, the user is forced to make a choice and set this (CLI or config) explicitly.

**Comment by Dominik1999** [comment]
No, it is not a legal decision. It was a UX decision. 

In the past, our own assumptions about UX and what the user wants were not outstanding. And I see your point. I am afraid that you can argue in every direction. If we enable that by default the amount of ETH and RDN needed will increase from an already high level (~40$) to simply start Raiden. 

To me, this is something the Product Owner should decide @GataKamsky - in an ideal world this decision should be based on actual user feedback and data.

**Comment by ezdac** [comment]
Agreed - it's hard to argue in any direction without user-input. So going for a defensive strategy (spending overhead wise) makes sense.

What I will implement for now is to simply warn the user if `--no-enable-monitoring` is used implicitly by a default value in production.
