### ISSUE TITLE
Nightly CI builds failing due to py-spy dep

### ISSUE THREAD

**Issue by karlb** [raiden-network/raiden#6782]
[prepare-python-macos-3.7](https://app.circleci.com/pipelines/github/raiden-network/raiden/10815/workflows/64cccf27-2dd3-4ddb-a052-be0eb2293070/jobs/163553) fails with `Could not find a version that satisfies the requirement py-spy==0.3.4`, although [there is py-spy release of that version](https://pypi.org/project/py-spy/0.3.4/). Is that version not valid on MacOS?

**Comment by benfred** [comment]
What version of OSX are you running on your  CI?  I'm wondering if you hit this problem with the 0.3.4 release https://github.com/benfred/py-spy/pull/350

**Comment by karlb** [comment]
@benfred Thanks for the feedback! We're using `xcode: "10.1.0"`, which means an image with High Sierra 10.13.6 is used, if I read https://discuss.circleci.com/t/xcode-10-1-image-released/26350 correctly. I didn't find an explicit mention of the MacOS version in our config or the resulting log files.
I will try a run with a more recent version and report back with the result.

**Comment by karlb** [comment]
Updating to a newer xcode/MacOS image seems to solve the issue: https://app.circleci.com/pipelines/github/raiden-network/raiden/10828/workflows/48e89159-8076-473e-b390-27aa40c0fa6b/jobs/163834
