### ISSUE TITLE
Nightly builds fail: Too long with no output (exceeded 10m0s)

### ISSUE THREAD

**Issue by karlb** [raiden-network/raiden#6798]
The nightly Raiden builds for both Linux and MacOS failed repeatedly over the last days with the error

```
Too long with no output (exceeded 10m0s): context deadline exceeded
```

while or after handling the pyinstaller hooks.

Linux: https://app.circleci.com/pipelines/github/raiden-network/raiden/10871/workflows/7b41753e-6055-4d82-80cb-87197a5c80a5/jobs/164830
MacOS: https://app.circleci.com/pipelines/github/raiden-network/raiden/10871/workflows/7b41753e-6055-4d82-80cb-87197a5c80a5/jobs/164829

Latest fully successful nightly on Jan 19th: https://app.circleci.com/pipelines/github/raiden-network/raiden/10807/workflows/78b60e22-5a4b-4610-988f-ea960ca7c47d
If we only look at build-binary-linux-x86, that run successful on https://app.circleci.com/pipelines/github/raiden-network/raiden/10836/workflows/d406b49b-699a-4f8b-85ff-f0a07be47021/jobs/164037

**Comment by ezdac** [comment]
If this is not a problem with pyinstaller itself, one idea is to set `PYTHONUNBUFFERED=1`.
It looks like pyinstaller takes quite some steps/time, maybe it's just CircleCI killing the build due to lack of STDOUT.

**Comment by karlb** [comment]
But why did it start happening now? Did CircleCI get slower, or did we make the build slower?

**Comment by karlb** [comment]
> If this is not a problem with pyinstaller itself, one idea is to set `PYTHONUNBUFFERED=1`, and/or to get more verbose output from pyinstaller.

I'll give that a try. If any single step takes more than 10 mins, than something really is wrong.

**Comment by ezdac** [comment]
I don't know, this is just something to consider. Maybe it was 9:50 min before and something changed?
I had a similar problem while modifying the MacOS builds (I think building Python), and adding a `--debug` or `-vv` flag helped to make the CircleCI job-runner happy.
Maybe for some reason the stdout is only flushed after the whole `pyinstaller` step is completed?

**Comment by karlb** [comment]
This has nothing to do with our CI setup. The build step hangs in pyinstaller's hook_raiden step, even when run locally. The problem has been introduced [when updating eth-utils](https://github.com/raiden-network/raiden/pull/6794). To be more precise, it is caused by eth-utils' dependency eth-hash. eth-hash 0.2.0 works but 0.3.0 shows the problem.
