### ISSUE TITLE
Improve 'net_contract.py' (note: py mock)

### ISSUE THREAD

**Issue by konradkonrad** [raiden-network/raiden#68]
https://github.com/raiden-network/raiden/blob/master/raiden/blockchain/net_contract.py
! this should be split in sub-issues
- [ ] define penalization
- [ ] allow for deposits on open channels
- [x] improve events and event data (not completely spec'ed yet)
   - [ ] generate the events
- [ ] refactor naming of methods&variables
- [x] implement `close`
- [ ] implement `settle`
- [ ] test lock-claiming

**Comment by LefterisJP** [comment]
Is this issue still valid? It is my understanding that we now want to keep it all in the solidity side.
