### ISSUE TITLE
What should i do after extracting the tar file?

### ISSUE THREAD

**Issue by noahsalvadordenjo** [raiden-network/raiden#6802]
I've downloaded the latest version of raiden and extracted it with ```tar -xvzf raiden-<version>-linux-x86_64.tar.gz``` but
```raiden``` and ```raiden-<version>-linux-x86_64``` are still unknown commands even after ```chmod u+x```
what should I do next?

**Comment by ezdac** [comment]
An executable is only available as a *command* from anywhere if it is found in your `PATH`. Consider either adding it to the path directly, add it to one of the common folders for executable packages on linux (e.g. `/usr/bin`)  or invoke the executable directly, e.g. with `./raiden-<version>-linux-x86_64`  from the folder you unpacked it.

Please also consider using the [raiden-wizard](https://docs.raiden.network/installation/quick-start/download-and-run-the-raiden-wizard#download-the-raiden-wizard) for an easier installation and setup experience if you just want to use raiden without a highly customised configuration.

**Comment by noahsalvadordenjo** [comment]
thank you so much

**Comment by konradkonrad** [comment]
I'm closing this, looks like it got resolved :)
