### ISSUE TITLE
PFS communication send by to_device

### ISSUE THREAD

**Issue by fredo** [raiden-network/raiden#6814]
# Introduction
#6813 stores PFS and MS addresses in the transport class. 

The matrix user_id to send to_device messages to can be deducted by the following pattern: 

`@address:localhomeserver`

All services have clients on all homeservers. To bring best performance we only send to the users on the user's homeserver

For MS and PFS there must exist different device id's to differntiate the receiving services. Suggestions can be found [here](https://github.com/raiden-network/raiden-services/issues/916)

###  to_device call content
Multiple messages to multiple users can be attached to the json content. This means that messages can be send to all PFSes with one API call. 
Furthermore I suggest to use `MatrixTransport.send_raw()`. This would allow to even send per webRTC if this makes sense in the future.

Please check though how the Capabilities of the services' clients are set.

**Comment by ezdac** [comment]
Should we consider sending to a non-local user-id (not our homeserver) for a service, when the one on our homeserver is offline?
We talked about this, but I'm not sure wether we came to a conclusion.
Is the scenario even likely that the service looks offline to us, while the service is actually reachable on another homeserver ?

Also (somewhat) relevant to this: #6817

**Comment by fredo** [comment]
I think we discussed that it is not necessary to do that as we have the retry mechanism for PFSs clients in place. A downtime either means that the whole PFS is down (then other users are down as well) or it will reconnect soon. Pending toDevice messages are stored in the database. 
#6817 addresses the fact that a whole PFS is down and therefore we should evaluate if it is even necessary to send messages at all.

**Comment by fredo** [comment]
I think this issue needs to be merged before #6815 (or togther with)
