### ISSUE TITLE
Only join discovery room

### ISSUE THREAD

**Issue by fredo** [raiden-network/raiden#6815]
Raiden Nodes only need to join discovery rooms once to_device messaging to the services is implemented

**Comment by ezdac** [comment]
Should this even be implemented, before we decide on wether we use "sharded, PFS guided" discovery?
The same question arises for #915, although the PR is already pending

**Comment by fredo** [comment]
Yes we should definioetly do this now, because the PFS guided solution is not implemented in the next days

**Comment by ezdac** [comment]
Agreed!
