### ISSUE TITLE
[META] Renew discovery room frequently to clean up RSB

### ISSUE THREAD

**Issue by fredo** [raiden-network/raiden#6820]
## Abstract

With the change for toDevice messages to services we only need one global room in order to receive presences. The setup of a global room where every user joins brings one major disadvantage. The State DAG of the room will become very large and cannot be pruned.

## Proposed solution
The idea is to delete global rooms once in a while. A suited service for doing this could be the Room Ensurer which is checking the global rooms once an hour anyway.
Unfortunately, deleting a room can only happen locally. Deleting a room:
- will purge all local users from the room
- delete all DB content for this room on the local server
- a new room can be chosen to add the local users to it

In order to have synchronism through out the whole lifetime of an RSB we need a back up room while the room to be renewed is out of sync. It should be enough to have two global rooms where any user joins. These rooms need to be renewed (deleted and recreated) in an alternating manner.

## ToDos
- Extend the Room Ensurer
  - In the Case of the first server in the list: Trigger the clean up process of the rooms
  - in the case of every other server: Once it detects a new room and switches to it (already in place) also delete the old room (cleaning up DB).
  - add users from the old room to the new room
- Raiden Node: 
  - join two discovery rooms
- Services:
  - join two discovery rooms

**Comment by karlb** [comment]
We don't use matrix rooms anymore, so renewing them is unnecessary.
