### ISSUE TITLE
Write channel state changes in the WAL

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#684]
## Problem Definition

Channel state changes, once implemented also need to be stored in the WAL.

## Solution

As a step towards channel recoverability we need to be able to store the channel state changes of the channel state machine in the WAL so that recovery can happen.

Depends on https://github.com/raiden-network/raiden/issues/507

## Tasklist

- [ ] Write the channel state changes in the WAL

**Comment by hackaugusto** [comment]
Finalized by: #1329
