### ISSUE TITLE
Request User ID from PFS upon direct payment 

### ISSUE THREAD

**Issue by fredo** [raiden-network/raiden#6841]
On the way to the presence less raiden client, the Raiden client needs to know the user_id from its peer when initiating a direct payment. For mediating payments the PFS will include user ids in the route information.

The PFS will have a new Endpoint providing user_ids and presences as it needs to have this information for the whole network anyway. For direct payments, the raiden node must request the user id from the PFS.

**Comment by karlb** [comment]
I'm waiting on https://github.com/raiden-network/raiden/issues/6848 and https://github.com/raiden-network/raiden-services/pull/942/files before improving my current draft at https://github.com/raiden-network/raiden/pull/6868.

**Comment by ezdac** [comment]
This was implemented in #6914
