### ISSUE TITLE
Remove Presence from internal State

### ISSUE THREAD

**Issue by fredo** [raiden-network/raiden#6842]
## Abstract

Raiden keeps track of the reachability state in the state machine in order to prevent payments to be initiated if a peer is offline. Going to a presence less raiden node we need to remove state changes and the check whether a user is online or offline.

Instead the PFS will provide these information by an endpoint for now. This could be optimized in the future. The raiden node will only need to ask for presence for direct payments as requesting routes will do this check implicitly.

**Comment by ezdac** [comment]
Thanks for opening the issue.
Just to clarify, this means we want to get rid of the `NetworkState` and the concept of user-presences completely?
We then would work with user-ids on a per route basis (e.g. attach the PFS user-id information to the `RouteState`):
- on `ActionInitInitiator` include the user-ids in the route-metadata 
- on each incoming `ActionInit[Mediator, Target]` just assume the user-ids in the route-metadata are online

**Comment by fredo** [comment]
Yes, there a PR already merged that passes the user_id information down the route request. https://github.com/raiden-network/raiden-services/pull/929
This should be passed to the transport when initiating a transfer. 
https://github.com/raiden-network/raiden/blob/f68aaf0282a3a0314916160ad062b5b448c72a25/raiden/network/transport/matrix/transport.py#L1444 this is the presence feed into the state machine

**Comment by ezdac** [comment]
But the concept of `NetworkState` should be removed completely from the codebase?
