### ISSUE TITLE
API: How to handle Channel schema using `NetworkState` of partner's nodes

### ISSUE THREAD

**Issue by ezdac** [raiden-network/raiden#6852]
The REST API returns Channel information on all endpoints returning a channel-state ( leave_channel, get_channel_list, deposit, withdraw, set_reveal_timeout, close).

Decide on:
- keep interface and return the state:
  - proxy PFS user-id endpoint
  - infer from last message sents and webrtc connection ? (sounds bad)
  - return dummy `NetworkState.UNKNOWN` for all ChannelStates
- deprecate the field from the ChannelState schema

**Comment by karlb** [comment]
My vote is for

> return dummy NetworkState.UNKNOWN for all ChannelStates

Returning this is correct and we could start to put useful information back into these fields at a later time. E.g. we might have presence information from WebRTC channels in some cases.

**Comment by ezdac** [comment]
I agree with that this is the best solution without changing the API, and also the best solution overall. Although we should somehow communicate that the concept of NetworkState is not used at the moment and thus should not be built upon...

Is a release with release notes enough for this, or should there be some kind of warning emitted?

**Comment by ezdac** [comment]
Well it turns out this field in the response was not documented at all in the `channels` API resource.
