### ISSUE TITLE
Re-enable skipped tests for presence-less Raiden

### ISSUE THREAD

**Issue by ezdac** [raiden-network/raiden#6861]
## Problem Definition

#6847 skipped some tests that were still relying on health-checks and wait-for's.
This was done in order to move forward faster and wait for a better defined state of the presence less 
Raiden feature branch before working on the tests.

## What to do
Remove health-checks and wait-for's from the tests, make them pass again and remove the skips from the tests before merging the feature branch to develop.

Changes possibly related to the skipped tests: #6855

**Comment by karlb** [comment]
Looks like the tests are already reenabled.
