### ISSUE TITLE
Become compatible with Geth 1.10.x (replay protected txs)

### ISSUE THREAD

**Issue by ulope** [raiden-network/raiden#6872]
## Abstract

Starting from `v1.10.0` geth [by default no longer accepts non-replay protected tx submitted via RPC](https://blog.ethereum.org/2021/03/03/geth-v1-10-0/#chainid-enforcement).
We need to figure out what needs to be done to sign our tx in this way.

## Motivation

We want to remain compatible with geth.
Also replay protection is a valuable thing to have in itself.

## Specification

IIUC replay protected tx need the chain-id as the `v` value in the signature.
Since we manually construct the transaction details [we seem to be missing passing the chainId parameter](https://github.com/raiden-network/raiden/blob/aaad593af88077d78022c9b2de8515649c767f98/raiden/network/rpc/client.py#L1285-L1323) to `sign_transaction`.
A quick test confirms that passing `chainId` in the `transaction_data` fixes the issue with geth 1.10.

## Backwards Compatibility

EIP-155 has been accepted in 2016, so this should work with any client currently in use.

**Comment by Tunji17** [comment]
Ran into an issue when deploying the Raiden contracts on a private geth network `v1.10.0-stable` using
```
python -m raiden_contracts.deploy raiden --rpc-provider $PROVIDER --private-key $PRIV_KEY --gas-price 10 --gas-limit 8000000 --contracts-version $VERSION --max-token-networks $MAX_UINT256
```
 I noticed the `SecretRegistry` contract deployed successfully and returned an address but the `TokenNetworkRegistry` error out with a `cumulativeGasUsed` showing the entire gas limit and this vague error `ValueError("Status 0 indicates failure”)` 
 
 
 
 ![image](https://user-images.githubusercontent.com/26358047/110904841-dff12800-8309-11eb-9e31-7af8eaf905cb.png)

**Comment by palango** [comment]
I added `--rpc.allow-unprotected-txs` to the goerli geth node for now. Hope this helps, but we should remove it once this issue is resolved.

Ref: https://blog.ethereum.org/2021/03/03/geth-v1-10-0/
