### ISSUE TITLE
Flaky Test:  test_participant_selection[3-6-True-False-0-6]

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#691]
## Problem Definition

The [test_participant_selection[3-6-True-False-0-6]](https://github.com/raiden-network/raiden/blob/411c642c8da53b979c4416cd548f07e879b15c5f/raiden/tests/long_running/test_token_networks.py#L90) is a very frequent flaky test as also reported in the [flaky tests issue](https://github.com/raiden-network/raiden/issues/389#issuecomment-307843675).

We have to fix it.

## Solution

[Read](https://github.com/raiden-network/raiden/issues/389#issuecomment-307843675), [all](https://github.com/raiden-network/raiden/issues/389#issuecomment-309602263), [3](https://github.com/raiden-network/raiden/issues/389#issuecomment-311981120) documented instances of this flaky test, investigate why it happens and fix it. 

## Tasklist

- [ ] Fix the flaky test_participant_selection[3-6-True-False-0-6] test

**Comment by palango** [comment]
github.com/raiden-network/raiden/blame/master/raiden/tests/long_running/flaky/test_token_networks.py#L60-L64 compares a `list`with an `int`. The `int`is always smaller in py2: stackoverflow.com/questions/3270680/how-does-python-compare-string-and-int

**Comment by LefterisJP** [comment]
I see no reason to have multiple issues open for different flaky tests. Closing in favour of: https://github.com/raiden-network/raiden/issues/389

**Comment by andrevmatos** [comment]
Fixed in #2015
