### ISSUE TITLE
Plan merging of Wizard into Raiden client

### ISSUE THREAD

**Issue by karlb** [raiden-network/raiden#6916]
Having the Wizard as a separate program from the python client causes problems:
- Wizard not available for all versions
- Harder to explain
- Can't swap tokens after initial startup
- Harder to maintain (different repos, release schedule, frameworks)
- Usability problems (e.g. how to stop raiden node)
- Harder to provide the wizard functions via API

What would be the right way to merge the wizard into the python client?

# Proposal

## Starting Raiden
Starting Raiden with a `--wizard` flag will open the Wizard/WebUI, which allows the user to create an ethereum key and set all the essential settings. If this has already been done before, the previous settings will be reused. To allow GUI users to start the wizard, we can provide a` wizard.sh` and `wizard.bat` that call `raiden --wizard`.

## Backend code

Most of the wizard code will be moved into the python backend and the features will be made available to the WebUI via the raiden REST API. This will make it necessary to run the REST API without an ethereum account and node.

## Frontend code

Previously, the Wizard and the WebUI frontend code didn't use the same framework. The Wizard code should be adapted or rewritten to work with the WebUI. This reduces maintenance work and allows better integration between the new/Wizard and old/WebUI functionality.

## Calling Wizard functionality from the WebUI

All functionality that was previously in the Wizard will be available from the WebUI at any point in time. The user will be able to change the ethereum node or acquire additional tokens at any time, not just during the first run, as it was the case previously. Some changes (e.g. changing ethereum node) might require restarting raiden, which will happen automatically in those cases (WebUI won't be available for some seconds).

# State

Early discussion

**Comment by ulope** [comment]
I think this is a good idea.

PyInstaller can create "GUI" bundles which don't cause a terminal window to open when launched as a GUI app. It may be possible to automatically detect in which mode we're being started and act accordingly.

**Comment by manuelwedler** [comment]
We won't do this because of legal concerns.
