### ISSUE TITLE
Make testnet release with geth 1.10 fix

### ISSUE THREAD

**Issue by karlb** [raiden-network/raiden#6918]
We should try to bring https://github.com/raiden-network/raiden/pull/6898 to users quickly, as more and more will update to geth 1.10. Infura also seems to use geth 1.10, now.

- [x] green scenario runs on develop
- [x] update changelog
- [x] bumpversion
- [x] merge to master
- [x] green scenario runs on master
- [x] release
- [x] switch SP back to develop
- [x] Fix [failing PyPI upload](https://app.circleci.com/pipelines/github/raiden-network/raiden/11410/workflows/79f615df-8c26-416f-8edb-bd3c7ff6de48/jobs/178666)
- [x] Update homebrew formula, if that should be done for an alpha release.

**Comment by konradkonrad** [comment]
Prerequisite:
- [ ] setup scenario player runs for `develop` (alongside `presence_less_client`)

Plan:
- Release current `develop` as a testnet only `-beta` release

**Comment by konradkonrad** [comment]
Currently running scenario player against develop 3ad2481eeff89b2962c0f967daa5fa38ce44b7ec

**Comment by manuelwedler** [comment]
The Wizard is broken because of this.

**Comment by karlb** [comment]
https://github.com/raiden-network/raiden/releases/tag/v2.0.0-a0
https://pypi.org/project/raiden/2.0.0a0/
