### ISSUE TITLE
Scenarios fail with "Expected IOU, but no IOU exists"

### ISSUE THREAD

**Issue by karlb** [raiden-network/raiden#6945]
Eight scenarios currently fail with "Expected IOU, but no IOU exists" when run on the presence_less_client_rebase branch.

Why is that the case? The presence should have no influence on the handling of IOUs in the PFS.

**Comment by ezdac** [comment]
It looks like the SP again uses a different Raiden version than expected:
```
{"version_info": {"raiden": "1.1.1.dev551+gc5292d631", "raiden_db_version": 26, "python_implementation": "CPython", "python_version": "3.7.10", "system": "Linux 64bit_ELF 4.15.0-130-generic", "architecture": "x86_64", "distribution": "source", "scenario_player": "0.6.5", "raiden-contracts": "0.37.0"}
```

**Comment by konradkonrad** [comment]
Same error in #6944 --- we should investigate this closer in https://github.com/raiden-network/raiden-services/issues/961

**Comment by konradkonrad** [comment]
solved, see https://github.com/raiden-network/raiden-services/issues/961
