### ISSUE TITLE
Remove fallback of sending to all possible user ids (possible vulnerability)

### ISSUE THREAD

**Issue by fredo** [raiden-network/raiden#6953]
As discussed with the broader team, sending messages to all possible user ids introduces a vulnerability which was avoided by validating the displayname. 
The vulnerability can happen if a matrix server does not use the `EthAuthProvider` or uses a different one additionally. By validating the displayname, a raiden node ensures that the user who holds the private key also signed the explicit user id. 

Therefore we need to avoid sending payments to user ids blindly. This implies, that having metadata inplace must be a requirement for now. This means that either the PFS sends route metadata with the route or for every other case, the PFS endpoint to request metadata needs to be used.

**Comment by konradkonrad** [comment]
ToDo:
- remove fallback from send mechanism
- introduce PFS metadata query to _all_ messages (at least [withdraw messages](https://github.com/raiden-network/scenario-player/issues/668#issuecomment-824611718) are still missing)

**Comment by fredo** [comment]
- revert #6972
