### ISSUE TITLE
Test db compatibility

### ISSUE THREAD

**Issue by karlb** [raiden-network/raiden#6965]
As preparation for the Bespin release (2.0), we should test that databases from the previous release (1.2) can be used without problems.

- [ ] Start two raiden nodes on v1.2
- [ ] Make a direct transfer
- [ ] Update to v2.0 and start nodes
- [ ] Make a direct transfer over the same channel

**Comment by konradkonrad** [comment]
I don't think this is enough, as this won't test any Mediator states.

**Comment by karlb** [comment]
Closed in favor of #6986
