### ISSUE TITLE
Implement temporary ban

### ISSUE THREAD

**Issue by ms83** [raiden-network/raiden#7]
ban == not init a transfer involving node X

X seem to be unresponsive. Could be a network glitch, but also X gone byzantine. Therefore we should be him say 10 minutes, then try again, if not good, double the ban, etc. if ban > X, close channel.

**Comment by hackaugusto** [comment]
Health check was added by https://github.com/raiden-network/raiden/pull/242 and improved with https://github.com/raiden-network/raiden/pull/615 , https://github.com/raiden-network/raiden/pull/835 .
