### ISSUE TITLE
Forward generic Metadata from message as a Mediator 

### ISSUE THREAD

**Issue by fredo** [raiden-network/raiden#7021]
Each LockedTransfer contains of a field called [Metadata](https://github.com/raiden-network/raiden/blob/fbd78ad560752199fe3ee9b27361c0d76756f47d/raiden/messages/metadata.py#L58). It's used to pass routes and AddressMetadata along the route. 

Currently Mediators receive these metadata, manipulate them and create what they want to forward. As this field might be used in the future to pass information along the route from initiator to target, a mediator might not be compatible with these information. 

If unknown Metadata are acknowledged/recognized by the mediator it should always forward them as they may contain important information for the target (or later mediator).

**Comment by ezdac** [comment]
Superseded by #7113
