### ISSUE TITLE
Retry registration in case of insufficient funds

### ISSUE THREAD

**Issue by ulope** [raiden-network/raiden#704]
## Problem Definition

Selecting an account that doesn't hold enough ether to perform the registration transaction causes an exception (including traceback) to be printed to the console. The raiden node continues to run but of course isn't registered at this point.

## Solution

The user should be prompted to fund the account and a retry logic should be implemented.

## Tasklist

- [ ] Implement registration retry
- [ ] Implement message prompting user to fund the account

**Comment by LefterisJP** [comment]
This issue should be closed by #770
