### ISSUE TITLE
Remove naive datetime usage

### ISSUE THREAD

**Issue by netcriptus** [raiden-network/raiden#7043]
We've been using many different methods to get the current time around the code, from `time.time()` to `datetime.now()` and `utcnow()`.

There should be a standard way to get the current time, preferably a non-naive, UTC fixed time. We should consider using [Pytz](https://pypi.org/project/pytz/)

**Comment by karlb** [comment]
I don't think there is a need to add pytz. The only time zone we need is datetime.timezone.utc, isn't it?

**Comment by netcriptus** [comment]
> I don't think there is a need to add pytz. The only time zone we need is datetime.timezone.utc, isn't it?
> 
> Using that, we can call `datetime.datetime.now(datetime.timezone.utc)` to get the current timezone-aware datetime.

The pytz implementation is there to solve imprecisions and ambiguities that exist in the `datetime.timezone` implementation. From the documentation:

> This library differs from the documented Python API for tzinfo implementations; if you want to create local wallclock times you need to use the localize() method documented in this document. In addition, if you perform date arithmetic on local times that cross DST boundaries, the result may be in an incorrect timezone (ie. subtract 1 minute from 2002-10-27 1:00 EST and you get 2002-10-27 0:59 EST instead of the correct 2002-10-27 1:59 EDT).

You can check more details [here](http://pytz.sourceforge.net/) if you want.

But since the code seems to [actively reject](https://github.com/netcriptus/raiden-services/blob/master/src/pathfinding_service/service.py#L341) the use of timezone aware timestamps, and the reason is unclear, for now I'll just make sure all timestamps being used are coming from `utcnow` instead of just `now`.

**Comment by karlb** [comment]
I still don't see what pytz will change as long as UTC is the only time zone we use, since we then avoid local times and DST.

> But since the code seems to actively reject the use of timezone aware timestamps, and the reason is unclear, for now I'll just make sure all timestamps being used are coming from utcnow instead of just now.

That is just making sure that no time zone is passed in via the message. The spec mandates that it is UTC. This is both done because serializing time zones is messy. You are free to use tzaware timezones in the implementation.

Continuing with native timestamps is also fine when it is done consistently.
