### ISSUE TITLE
Graceful Start of Raiden instance with raiden address of already closed channel

### ISSUE THREAD

**Issue by agatsoh** [raiden-network/raiden#708]
## Problem Definition

I had a channel open, only one of the parties participating in the channel was online the other wasn't, which means I had one raiden instance open. At this stage I close the channel with the other party.
  
I try to start the raiden instance having raiden address of the other party in the channel.
I get this [error](http://gist.github.com/agatsoh/418ce2c1248a33dc9b3b8bc4124772f5)

## Tasklist

Raiden addresses(instances) whose associated channels are closed when they are offline, should be able to start gracefully without any errors

- [ ] Implement proper closing of channels with offline participants
- [ ] Implement error free start of the raiden instance with associated closed channels

### System Description
Geth Version 1.5.9
I follow [this](https://gist.github.com/agatsoh/90c33881b840866a27e93bf4c14fa403) while using raiden in a private setup.

**Comment by hackaugusto** [comment]
This is fixed by: https://github.com/raiden-network/raiden/pull/683

**Comment by hackaugusto** [comment]
Closing because #683 is merged, this issue is fixed
