### ISSUE TITLE
Dont prune route on mediation

### ISSUE THREAD

**Issue by fredo** [raiden-network/raiden#7090]
In the discussion of #7021, it must be discussed whether we should manipulate expected route metadata such as the route itself.
If we decide to passthrough all metadata, routes should be kept as is and a node should be able to find himself in the route to find the next hop.

Currently the PC expects to be the first one in the list upon mediation.

**Comment by ulope** [comment]
This also has privacy implications, IIRC that was the main reason we implemented route pruning in the first place.

**Comment by ezdac** [comment]
The hard requirement for LC-compatibility here is that we don't **rely** on pruned routes for mediation (index-based access for finding the next_hop). 

*Note: I'm already working on this*

So if we think not pruning is problematic we could still prune. More opinions on that? The LC plans to not prune at all.

**Comment by ezdac** [comment]
We decided to not do the pruning anymore and behave the same way the LC does.
This will be implemented as part of #7162
