### ISSUE TITLE
fix handling of `CancelTransfer` messages

### ISSUE THREAD

**Issue by konradkonrad** [raiden-network/raiden#71]

**Comment by hackaugusto** [comment]
Commit 276b2f18bcbac4adc4f5ad36353f12b8b03cb8fa renamed `CancelTransfer` to `RefundTransfer` and added the following semantics:

- for nodes that are initiating a transfer and receive a `RefundTransfer`, generate a new secret and hashlock and tries a new path
- for nodes that are mediating a transfer and receive a `RefundTransfer`, register the transfer to get the refund and try a new path with the same hashlock
- for nodes that are mediating a transfer and don't have avaiable paths left, create a `RefundTransfer`, send to the previous node and register a `LogListenerTask` if the previous node reveals the secret only in the blockchain.

**Comment by hackaugusto** [comment]
Merged into master with 50359ab6338fd777dbd5a30ed3c8860cec517050
