### ISSUE TITLE
Create a stresstest

### ISSUE THREAD

**Issue by konradkonrad** [raiden-network/raiden#711]
## Problem Definition

Current unit and integration tests all assert correctness of operation for low numbers of channels and transfers (<5). We should add a test scenario that goes beyond that and guarantees correct operation for more complex setups.

## Solution/Tasklist

Create an integration test 
- [x] for 100 nodes that
- [x] does many to many transfers
- [x] interweaves direct and mediated transfers
- [ ] interweaves the `initiator`, `mediator` and `target` roles
- [ ] tracks the expected balances for all nodes
- [ ] before settlement
- [ ] after settlement

## New Edit by Lefteris

This issue now tracks the completion of the new (08/2018) stress tests we work on at #2309

**Comment by pcppcp** [comment]
noting for later: it would be nice to make raiden_network fixture look like a real world network topology, i.e. [1][2]. This can be easily done with a help of the networkx library that is already being used in Raiden.

[1] https://en.wikipedia.org/wiki/Barabási–Albert_model
[2] https://en.wikipedia.org/wiki/Watts_and_Strogatz_model

**Comment by LefterisJP** [comment]
Hijacking this issue to describe the very important tests we working on at #2309
