### ISSUE TITLE
Add a removedb command

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#719]
## Problem Definition

Apart from doing `rm -rf ~/.raiden` there is no cleaner way to clean up all of raiden's caches and database.

## Solution

Add a console command `removedb` which would be cleaning the database and the pickled/cached data. In the future also the WAL.

Note: Unlike `rm -rf ~/.raiden` this command would only clean the data corresponding to your raiden address as the data in the `.raiden` directory are partitioned by address.

## Tasklist

- [ ] Add a `removedb` command

**Comment by devium** [comment]
Implemented in #794.
