### ISSUE TITLE
Make tests and smoketest work with latest contracts

### ISSUE THREAD

**Issue by karlb** [raiden-network/raiden#7203]
Raiden requires `raiden-contracts==0.38.0`, but since https://github.com/raiden-network/raiden-contracts/blob/master/raiden_contracts/constants.py#L11 still set's the version to `0.37.0` (which is confusing and can hopefully be avoided for future releases), the 0.37 contracts are still used.

Contract changes since 0.37 (probably related to https://github.com/raiden-network/raiden-contracts/pull/1428) cause the deployment of the ServiceRegistry to fail in the raiden integration tests. I guess this can be fixed by changing the deployment to take the library into account like in https://github.com/raiden-network/raiden-contracts/pull/1428/files#diff-267c4094488da5b1ae76661deeae9830b91c6042bc76ca3718fe472866fe5c96R227.

**Comment by istankovic** [comment]
After meeting with @karlb it was agreed to
- always use latest contracts in raiden tests
- delegate all contract deployment to `raident-contracts` (i.e. don't use `JSONRPCClient` to deploy contracts)
- see if removing the contract bytecode checking from proxies is acceptable; if not, check for possibility of ignoring resolved bytecode references to library code in already deployed contracts

**Comment by istankovic** [comment]
We decided to remove the bytecode check as it is not deemed useful enough.
