### ISSUE TITLE
Patch Release 2.0.1

### ISSUE THREAD

**Issue by fredo** [raiden-network/raiden#7208]
We have to release the planned patch. 

Included features:
 - WebRTC
 - public key encryption
 - Allow generic metadata in messages
 - Cooperative Settlement

Release Checklist:
- [ ] RSB ready
  - [ ] RSB release made 
  - [ ] Mainnet RSBs updated (can we do that without braking mainnet?)
  - [ ] At least two RSB providers running which are not about to expire
- [ ] Update Docs, if necessary (https://github.com/raiden-network/raiden/issues/6981)
- [ ] Test db compatibility/upgradability (https://github.com/raiden-network/raiden/issues/6965)
- [ ] Check changelog for missing entries
- [ ] Testnet SP run done
- [ ] Get ETH for mainnet test
- [ ] mainnet SP run done
- [ ] minimal manual mainnet testing
- [ ] Official OK for release
- [ ] Released
- [ ] Update Wizard
- [ ] Update "stable/beta" link on https://raiden.network/
- [ ] Release comms

**Comment by fredo** [comment]
Mainnet Testing: 

Manual Testing Excel 
successful BF1

**Comment by karlb** [comment]
We're going directly to 3.0 instead.
