### ISSUE TITLE
Check immutable metadata compatibility with LC

### ISSUE THREAD

**Issue by konradkonrad** [raiden-network/raiden#7295]
When https://github.com/raiden-network/raiden/pull/7253 was merged, it claimed it "implemented part of https://github.com/raiden-network/raiden/issues/7242".

Since then, some e2e tests with the light client showed problems.

This issue is to investigate what the implementation status is.

**Comment by ezdac** [comment]
Note https://github.com/raiden-network/raiden/issues/7242#issuecomment-899605747 
This should not be relevant for failing tests that don't have `immutableMetadata=0` nodes though
