### ISSUE TITLE
Make database path configurable

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#738]
## Problem Definition

Database path is the same for all raiden nodes running on a machine.
## Solution

Make it configurable

**Comment by LefterisJP** [comment]
I would also add as a requirement to this to change the default database path to use `pex(self.raiden.address)` as a subdir under `.raiden` much like the pickled data files do.

Since @konradkonrad already made it configurable in #718 I will change the defaults in another PR.

**Comment by konradkonrad** [comment]
I extracted the database dir flag from #718 and will remove the commit 727c57066a1f2e0558b165e6ea85901122c5ba92 from said PR, if this one comes earlier.
