### ISSUE TITLE
Python client does not call openChannelWithDeposit function

### ISSUE THREAD

**Issue by agatsoh** [raiden-network/raiden#7383]
## Problem Definition

The python client does not call the `openChannelWithDeposit` but only calls the `openChannel` function while with the  same API call the raiden CLI correctly calls the `openChannelWithDeposit` when the `total_deposit` option has been mentioned in the json payload of the API

```
curl -i -X PUT \
http://localhost:5010/api/v1/channels \
-H 'Content-Type: application/json' \
--data-raw '{"partner_address": "0xEa45D7385e5020797F5Ab2ABEB0E40fc06CB3aeB", "token_address": "0x6B175474E89094C44Da98b954EedeAC495271d0F", "total_deposit": "10000000000000000000", "settle_timeout": "500"}'
```

The raiden CLI `openChannelWithDeposit` call
https://etherscan.io/tx/0x676d510c6cb9e3670f1a11fa161de6ed30891237911cbce596b2bf67f2b94a69

The Python client `openChannel` call
https://etherscan.io/tx/0x42f779190970c69fa2b35da63b70c095c840b1419e2b1fc36a28e5dbcaa37b21

Python client debug logs:
----------------------------

[raiden-debug_2021-09-28T09:50:04.661476.log](https://github.com/raiden-network/raiden/files/7243053/raiden-debug_2021-09-28T09.50.04.661476.log)
[debuglog1log2.tar.gz](https://github.com/raiden-network/raiden/files/7243058/debuglog1log2.tar.gz)

Normal logs(file mentioned in the command)
---------------------------
[node_df1031_mainnet_28thSeptember2021_python.log.tar.gz](https://github.com/raiden-network/raiden/files/7243066/node_df1031_mainnet_28thSeptember2021_python.log.tar.gz)

### System Description

Here add a detailed description of your system, e.g. output of the following script:

```
uname -a
command -v solc && solc --version
command -v geth && geth version
command -v parity && parity --version
command -v raiden && raiden version
[ -d .git ] && git rev-parse HEAD
```

**Comment by palango** [comment]
Tracked in https://github.com/raiden-network/raiden/issues/7315
