### ISSUE TITLE
Create docker images

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden#7410]
Currently, no docker images are created for develop and the RCs. This leads to people on gitter having problems trying raiden, so we need to fix this.

The simplest way seems to be: https://github.com/docker/metadata-action#basic but we might prefer a CircleCI based solution.

**Comment by ulope** [comment]
Branch / tag mapping:
- `develop` / `develop` (optionally also `<git-describe --tags>`)
- `<tag>` / `<tag>` and `latest`
