### ISSUE TITLE
Too low settle_timeout on channel open causes 500 in Rest-API

### ISSUE THREAD

**Issue by ulope** [raiden-network/raiden#743]
## Problem Definition

Calling `PUT /api/1/channels` with a `settle_timeout` < `DEFAULT_SETTLE_TIMEOUT` causes `500 Internal Server Error`. The reason is that `RaidenAPI.open()` raises a `ValueError` in this case which isn't handled in `RestAPI.open()`.

## Solution

Handle `ValueError` in `RestAPI.open()` and return a descriptive error message.

## Tasklist

- [ ] Handle `ValueError` in `RestAPI.open()` and return a descriptive error message.

**Comment by LefterisJP** [comment]
I will handle this. Thank you for the report @ulope .
