### ISSUE TITLE
AttributeError: 'ChannelSerialization' object has no attribute 'block_number'

### ISSUE THREAD

**Issue by czepluch** [raiden-network/raiden#745]
## Problem Definition

When restarting a Raiden node after having done some transactions that goes to the blockchain, there is a problem with recovering. More specifically with the ChannelSerialization object not having a `block_number` attribute:
```
AttributeError: 'ChannelSerialization' object has no attribute 'block_number'
```
https://github.com/raiden-network/raiden/blob/9650f9ce94b075f4ae12c7bfffdfaca582bbcec7/raiden/channel/netting_channel.py#L817

Full stack: https://gist.github.com/agatsoh/26f4329193eeac84d2d1f33012d6d2d9

## Solution

~Add a `block_number` attribute to the `ChannelSerialization` object~
The error is most likely due to this line: https://github.com/raiden-network/raiden/blob/9650f9ce94b075f4ae12c7bfffdfaca582bbcec7/raiden/raiden_service.py#L564
It seems that `block_number` is unused here https://github.com/raiden-network/raiden/blob/1b59f65939a01cbac1f187870b6c802a2006765a/raiden/network/channelgraph.py#L222
Removing the `block_number` arguments seems to be the solution

## Tasklist

~- [ ] add `block_number` attribute to `ChannelSerialization` object.~
- [ ] remove `block_number` argument from `add_channel` https://github.com/raiden-network/raiden/blob/1b59f65939a01cbac1f187870b6c802a2006765a/raiden/network/channelgraph.py#L222

**Comment by hackaugusto** [comment]
Don't add the block_number to the channel serialization. I removed it because it because it affect equality checks.

Please post the full stack trace, I believe the error is because of this line:

https://github.com/raiden-network/raiden/blob/9650f9ce94b075f4ae12c7bfffdfaca582bbcec7/raiden/raiden_service.py#L564

**Comment by czepluch** [comment]
Added @agatsoh 's gist with the full stack
