### ISSUE TITLE
Missing return in RestAPI connect() and leave()

### ISSUE THREAD

**Issue by ulope** [raiden-network/raiden#748]
## Problem Definition

Both `RestAPI.connect()` and `RestAPI.leave()` are missing `return` statements to return a HTTP response.

## Solution

Return appropriate values from both methods.

## Tasklist

- [ ] Return Rest response from `RestAPI.connect()`
- [ ] Return Rest response from `RestAPI.leave()`

**Comment by LefterisJP** [comment]
I will handle this one too. You mean a simple 200 OK for success as defined in the [API docs](https://github.com/raiden-network/raiden/blob/master/docs/Rest-Api.rst#possible-responses-8), right? Or something else?

**Comment by ulope** [comment]
TBH I haven't really thought about what would be an appropriate response. I just noticed that both don't return anything which implicitly means `None` is returned which gets turned into `null` by flask-resful.

**Comment by LefterisJP** [comment]
200 OK should be fine unless we need more data. Indeed we are missing a return. It's super simple to add.

**Comment by LefterisJP** [comment]
@ulope Are you sure there is not a 200 OK by default even though there is no return statements? The API tests we have check for 200 OK and it is returned.

**Comment by ulope** [comment]
@LefterisJP Right it does return code 200 but also the string `null`. Which doesn't make much sense IMO. I'd argue those methods should return `204 No Content` and no response body.
