### ISSUE TITLE
implement configurable timeouts

### ISSUE THREAD

**Issue by konradkonrad** [raiden-network/raiden#75]

**Comment by hackaugusto** [comment]
- [ ] network timeout
- [ ] `lock_expiration` per channel:

  > lock_expiration = current_block_number + channel.settle_timeout - reveal_timeout

**Comment by hackaugusto** [comment]
276b2f18bcbac4adc4f5ad36353f12b8b03cb8fa implemented `lock_expiration` per channel.
https://github.com/raiden-network/raiden/commit/276b2f18bcbac4adc4f5ad36353f12b8b03cb8fa#diff-47f574997fd6a3b54c548636aa8df63bR118

**Comment by hackaugusto** [comment]
Closing because the network timeouts are better explained by #374
