### ISSUE TITLE
Make `smoketest` configurable to allow for other ethereum client backends

### ISSUE THREAD

**Issue by konradkonrad** [raiden-network/raiden#758]
## Problem Definition

The implementation of the `smoketest` command tries to allow to specify other ethereum client backends via environment variables. The implementation is however not complete:
- the command for running the ethereum client backend is configurable via `RST_GETH_BINARY`
- the init phase with the smoketest genesis is **not** configurable.

Therefore, it is not possible to use an ethereum client for the smoketest, that does not follow `geth` s CLI spec for `init`.

## Solution

Either remove the customization code to make the existing smoketest implementation simpler, or add a scheme that allows to also define the initialization phase with the smoketest genesis JSON file for other clients.

**Comment by hackaugusto** [comment]
this is possible since https://github.com/raiden-network/raiden/pull/4048
