### ISSUE TITLE
Move smoketest test utilities into general `utils` package

### ISSUE THREAD

**Issue by konradkonrad** [raiden-network/raiden#771]
## Problem Definition

The smoketest setup phase relies on a couple of modules from `raiden.tests`, namely
- `raiden.tests.utils.tester_client`
- `raiden.tests.utils.genesis`
- `raiden.tests.fixtures.tester_state`

Because of these dependencies, we need to bundle `raiden/tests` with our source distribution.

## Solution

It should be perfectly fine (semantically as well as technically) to move the dependent code into the general `raiden.utils` package.

## References
The following PRs introduced the changes to our packaging:
- #718 added the smoketest and changed the `setup.py` `packages=find_packages(...` entry
- #769 changes the `MANIFEST.in` entries to no longer `prune raiden/tests`

**Comment by ulope** [comment]
This is not really fixed. The smoketest ist still unable to run in the binary distribution (or when just installing the runtime requirements) since its using tools from the tests which import dev requirements.
