### ISSUE TITLE
handle expired messages in protocol queue

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/raiden#779]
## Problem Definition

Raiden protocol messages are ordered to maintain the monotonicity property of the messages, it may be the case that a locked transfer is added to the queue while the receiving node is offline, the node may come back online *after* the message in the queue has expired. The protocol won't be able to progress, since the newest message is the queue is always going to be invalid.

## Solution

Either recompute the messages in the queue or allow a node to receive messages with expired locks

**Comment by pcppcp** [comment]
closed on request by @LefterisJP
