### ISSUE TITLE
Token already registered yet not in tokenlist

### ISSUE THREAD

**Issue by ulope** [raiden-network/raiden#784]
## Problem Definition

Two node setup:
- Register token on first node
- Registering the token on second node gives `409 Conflict` (i.e. Token already exists)
- Token list on second node remains empty

## Solution

The token list and token registration should use the same source of truth.

## Tasklist

- [ ] Ensure token list and token registration are in sync

**Comment by LefterisJP** [comment]
@ulope A question about the scenario when this happened. When you did the first step `Register token on first node` was it the first time this token was registered in the network, iow was there a channel manager already generated or was it that call which generated the channel manager?

**Comment by hackaugusto** [comment]
> Token list on second node remains empty
Does the token list stay empty for ever? The conflict is fine, that is just a race condition and returning a conflict is the correct response, but the list must be populated.
