### ISSUE TITLE
Trying to create a channel with oneself causes confusing error

### ISSUE THREAD

**Issue by ulope** [raiden-network/raiden#785]
## Problem Definition

Trying to open a new channel where `partner_address == own_address` results in a confusing error message "JSONRPCClientReplyError: Transaction execution error." The underlying reason is an OOG in `estimateGas` of `newChannel`.

## Solution

Prevent users from trying to create a channel with themselves by providing a descriptive error.

## Tasklist

- [x] Prevent channel creation with partner_address == own_address by raising an appropriate error
- [x] Handle in REST-API

**Comment by pcppcp** [comment]
@ulope 
I'd like to reproduce the error & write test for that. How did you open the channel? console, API, webUI... ?

**Comment by ulope** [comment]
@pcppcp I used the rest api, but the problem should be reproducible via any interface.

**Comment by pcppcp** [comment]
Thanks! I've reproduced it both in the testcase and api, now I am going to make rest return something more descriptive than Internal Server Error.

**Comment by LefterisJP** [comment]
@pcppcp It should also return `409 Conflict` as it already does for other invalid arguments.

```
        except (InvalidAddress, InvalidSettleTimeout) as e:
            return make_response(str(e), httplib.CONFLICT)
```
