### ISSUE TITLE
Contracts as Solidity Contracts

### ISSUE THREAD

**Issue by heikoheiko** [raiden-network/raiden#8]
translate https://github.com/heikoheiko/raiden/blob/master/raiden/contracts.py .

**Comment by konradkonrad** [comment]
@czepluch this can be closed, right?

**Comment by czepluch** [comment]
Depends on when we define something as done? We can close this and split up the small remaining tasks such as testing in to other issues?

**Comment by konradkonrad** [comment]
Yeah, let's do that!

**Comment by konradkonrad** [comment]
closing in favour of more specific tickets #51 #52 #53
