### ISSUE TITLE
Discovery

### ISSUE THREAD

**Issue by heikoheiko** [raiden-network/raiden#80]
Nodes need to send messages to other nodes. They need to lookup endpoints based on addresses. 

Ideas:
- Use p2p discovery
- use ethereum BC as a central registry hotfix

**Comment by heikoheiko** [comment]
use ethereum BC as a central registry as a temporary solution until discovery is extended.

**Comment by heikoheiko** [comment]
https://github.com/zsfelfoldi/go-ethereum/wiki/Network-topology-and-peer-discovery-mechanism

**Comment by konradkonrad** [comment]
The current solution solves these issues: 
- it allows to lookup nodes
- it should scale okay

The current solution has (at least) these drawbacks:
- it leaks information as in linking endpoints with actual ethereum/raiden accounts ~centrally (on the blockchain)
- it does not solve roaming of nodes (no mechanism yet that informs the node of a new network configuration)
- it costs tx fees for updating the registry

The following (potentially related) items are not discussed in this issue:
- discovery of (asset specific) paths, i.e. Routing
- discovery of the local network configuration, i.e. [NAT-traversal](#120)

**Comment by hackaugusto** [comment]
@konradkonrad @LefterisJP I believe this has been moved to the transport layer, and for the matrix transport it's seems to be a solved problem. I think we can close this issue and open issues if required by different transports

**Comment by LefterisJP** [comment]
I agree @hackaugusto. Closing issue.
