### ISSUE TITLE
Timeout on endpoint registration leaves Raiden in undefined state

### ISSUE THREAD

**Issue by ulope** [raiden-network/raiden#802]
## Problem Definition

In case the tx polling in `ContractDiscovery.register()` times out after `DEFAULT_TIMEOUT` (currently 180s) either due to the eth node not being available or congestion, Raiden lingers in an unusable state.

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/gevent/greenlet.py", line 534, in run
    result = self._run(*self.args, **self.kwargs)
  File "/app/raiden/network/discovery.py", line 74, in register
    self.discovery_proxy.register_endpoint(node_address, endpoint)
  File "/app/raiden/network/rpc/client.py", line 508, in register_endpoint
    timeout=self.poll_timeout,
  File "/usr/local/lib/python2.7/site-packages/pyethapp/rpc_client.py", line 753, in poll
    raise Exception('timeout when polling for transaction')
Exception: timeout when polling for transaction
<Greenlet at 0x7fb5989cf4b0: <bound method ContractDiscovery.register of <raiden.network.discovery.ContractDiscovery object at 0x7fb59815e990>>('\x8b\x1d\x82\x01\x81\xda6u\xdbpOxx\x1d-E\xc4\x19\, '54.173.163.74', 40001)> failed with Exception
```

## Solution

The two easy solutions are either retrying to register (or extending the timeout) or terminating with an explanatory message.

## Tasklist

- [ ] Decide whether we want to re-try or terminate
- [ ] Implement result of decision

**Comment by pcppcp** [comment]
This one was hard to reproduce, but I've got it:

1) set breakpoint before Discovery::register_endpoint() starts polling
2) kill geth rpc port i.e. `iptables -A INPUT -p tcp --dport 8545 -s localhost -j DROP`
3) wait for timeout

I'd say lets catch the failing greenlet and give the user a descriptive error message. Raiden can't continue to do anything sensible anyway.

**Comment by ulope** [comment]
Well we could re-try the registration but I think exiting with a descriptive error message should be fine for now.

**Comment by hackaugusto** [comment]
> re-try the registration
Retry doesn't seem like a good solution. The new transaction will either fail because the nonces are out-of-order (assuming the previous one was discarded), or it won't change the state of the smart contract (assuming the previous transaction was processed afterwards).
