### ISSUE TITLE
CLI client

### ISSUE THREAD

**Issue by heikoheiko** [raiden-network/raiden#81]
CLI client to access the Raiden node process leveraging its API.

Features:
- [x] list assets
- [ ] list channels for asset
- [ ] add asset (configures the node to open channels for asset)
- [ ] remove asset
- [x] transfer 
- ?

**Comment by LefterisJP** [comment]
@heikoheiko @konradkonrad Can this Issue be closed? We do have a CLI interface, which is the default interface at the moment.

**Comment by hackaugusto** [comment]
Closing since we have the CLI interface.
