### ISSUE TITLE
InsufficientFunds during channel deposit causes 500 in Rest-API

### ISSUE THREAD

**Issue by ulope** [raiden-network/raiden#818]
## Problem Definition

When trying to refill a channel while not holding enough tokens to do so a `InsufficientFunds` exception is raised form the Python API which isn't caught in the Rest-API leading to `500 Internal Server Error`

## Solution

Handle `InsufficientFunds` exceptions in the Rest layer and return an appropriate response.

## Tasklist

- [x] Handle `InsufficientFunds` exceptions in the Rest layer and return an appropriate response.

**Comment by pcppcp** [comment]
I have a PR ready for this. I will publish it once #825 is merged.

**Comment by pcppcp** [comment]
Fixed in PR #829
