### ISSUE TITLE
Add synchronization for netting channel external state calls

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/raiden#819]
## Problem Definition

ChannelExternalState methods may be called more than once, e.g.:

- Two concurrent tasks are running against a node that goes offline
- Once each task reaches the unsafe region, both will emit the ContractSendChannelClose
- Without some sort of check, close will be called twice

## Solution

Flag the ChannelExternalState for "waiting_for_close", and only call `close` once.

## Tasklist

- [ ] Write a test
- [ ] Fix the problem

**Comment by LefterisJP** [comment]
Fixed by #821
