### ISSUE TITLE
Monitor Channels & Dispute

### ISSUE THREAD

**Issue by heikoheiko** [raiden-network/raiden#82]
**Estimate for sprint 2:** 1
Monitor closing/settlement relevant state changes in the channel + engage in dispute actions if necessary.

**Comment by konradkonrad** [comment]
please expand

**Comment by hackaugusto** [comment]
If Alice and Bob have a channel opened, both participants need to watch the blockchain for closing events, once a channel is closed the other participant/a thirdparty needs to check the published messages for the correct `transferred_amount`, if there is a mismatch for the latest value a dispute should be made.

**Comment by LefterisJP** [comment]
I am picking this issue up.
