### ISSUE TITLE
TypeError: token_swap_and_wait() got an unexpected keyword argument 'from_token'

### ISSUE THREAD

**Issue by agatsoh** [raiden-network/raiden#820]
## Problem Definition

While testing for token swaps through the Raiden API I encountered an error. 
`TypeError: token_swap_and_wait() got an unexpected keyword argument 'from_token`
[https://gist.github.com/agatsoh/6df8e25dab518044cf566393f9d2a20b](https://gist.github.com/agatsoh/6df8e25dab518044cf566393f9d2a20b)

I have also described the curl call that i made and also a scenario in the github gist

## Solution

Mostly looks like mismatch in naming between variables but still needs deeper introspection.

### System Description
geth version 1.6.6-stable
solc version 0.4.11+commit.68ef5810.Linux.g++

**Comment by czepluch** [comment]
Also remember to add a test for the failing behaviour.

**Comment by czepluch** [comment]
Solved by #826
