### ISSUE TITLE
Automatic Channel Provisioning

### ISSUE THREAD

**Issue by heikoheiko** [raiden-network/raiden#83]
Automatically open and close channels based on 
- the configuration  
- channel performance

**Comment by konradkonrad** [comment]
I propose a multi stage approach towards achieving this:
- [ ] allow for a simplified `connect(token, available_funds)` API method that hides the `open(token, partner, funding)` steps from the user
- [ ] add a listener that will "join" freshly opened channels by depositing some `available` funds
- [ ] develop performance monitoring for channels (flag underperforming channels for eventual replacement)
- [ ] implement balancing (i.e. open new channels on bad performance)
- [ ] allow for user preferences for the above behavior

**Comment by czepluch** [comment]
@konradkonrad can we close this?

**Comment by LefterisJP** [comment]
@czepluch The PR by konrad is only the simplified form of channel provisioning. But that is also what was part of the sprint and of the developer preview. The more involved approach should be its own issue.

**Comment by konradkonrad** [comment]
closed with #400
