### ISSUE TITLE
'RaidenService' object has no attribute 'on_message'

### ISSUE THREAD

**Issue by ulope** [raiden-network/raiden#839]
## Problem Definition

`RaidenService.on_message` is assigned in the `__init__` method after the `AlarmTask` gets started (and callbacks are registered on it). This causes a race condition since network messages can arrive before the `on_message` method is available which then leads to `AttributeError: 'RaidenService' object has no attribute 'on_message'`

## Solution

Delay starting the alarm task until after the `on_message` attribute has been set.

## Tasklist

- [ ] Delay starting the alarm task until after the `on_message` attribute has been set.

**Comment by pcppcp** [comment]
I'll fix this one - great opportunity to learn about how task sync in gevent works.

**Comment by pcppcp** [comment]
This seems to be easy to fix, just alarm.start() after setting up the callback.

The thing I don't understand is where the context switch occurs - if I understand gevent correctly, it should switch task cooperatively, so code in RaidenService.__init__() must yield somewhere, but I don't see any suspicious code that would cause that.

**Comment by pcppcp** [comment]
Hmmm, is AlarmTask really involved? RaidenService.on_message() gets executed only within RaidenProtocol class..

**Comment by ulope** [comment]
@pcppcp Yes looks like you're right. I've been trying to re-create this and I had one occurrence even with `alarm.start()` commented out.

**Comment by pcppcp** [comment]
Thanks for trying this! 
Main suspect seems to be UDPTransport.  In its constructor, it will start DatagramServer greenlet, and when context switch occurs and there are data waiting to be read from the socket, it will attempt to call this on_receive() method, raising the exception.
