### ISSUE TITLE
Use best practice security patterns in the smart contracts

### ISSUE THREAD

**Issue by heikoheiko** [raiden-network/raiden#84]
https://github.com/androlo/solidity-workshop/blob/master/tutorials/2016-06-30-contract-oriented-programming-I.md
https://medium.com/@gavofyork/condition-orientated-programming-969f6ba0161a#.j7gxi354l

**Comment by heikoheiko** [comment]
Comprehensive collection:
https://github.com/ConsenSys/smart-contract-best-practices

**Comment by heikoheiko** [comment]
Are we testing for proper NatSpec? 
https://github.com/ethereum/wiki/wiki/Ethereum-Natural-Specification-Format

**Comment by czepluch** [comment]
The compiler let's you know if the natspec does not comply with the actual parameters of a function.

**Comment by czepluch** [comment]
This is something that I think we do to a pretty good extend at the moment. We should however make sure to thoroughly reiterate and audit the smart contracts before the MVP.

**Comment by LefterisJP** [comment]
Closing issue as work for it has been done and the title is too vague.
