### ISSUE TITLE
Swap Tokens functionality always returns success, even when it can't succeed

### ISSUE THREAD

**Issue by andrevmatos** [raiden-network/raiden#840]
## Problem Definition

Swap Tokens API and tests doesn't cover when some required pre-condition fails and the tokens call can't be completed. API always returns `201 CREATED`, misleading users on which the call succeeded or failed.

From @hackaugusto, requirements for a token swap are something like:
_Use case_: **UserA** wants to exchange **M** tokens **T1** for **N** tokens **T2** with **UserB**

1. Both users must be participating in both token networks, T1 and T2
2. UserA must have a path through the T1 network to pay for the M T1 tokens, lets call P1
3. UserB must have a path through the T2 network to pay for the N T2 tokens, lets call P2
4. All nodes from P1 and P2, including UserA and UserB nodes, must be online at the time of the operation

## Solution

Ensure that both the `maker` and `taker` calls fails with `404` (Path Not Found) and/or other proper HTTP error if any of above conditions fails, and succeed with `201` (Created) only if everything goes ok.

Tests covering this feature which needs to be updated:
- [tests/unit/api/test_python_api.py::test_token_swap](https://github.com/raiden-network/raiden/blob/ffbb19c5bc26e718af081328eac98e8519b254c8/raiden/tests/unit/api/test_python_api.py#L147-L191)
- [tests/api/test_api.py::test_api_token_swaps](https://github.com/raiden-network/raiden/blob/ffbb19c5bc26e718af081328eac98e8519b254c8/raiden/tests/api/test_api.py#L861-L915)

Test helper functions which may need to be adapted (from `tests/utils/apitestcontext.py`):
- [specify_tokenswap_input](https://github.com/raiden-network/raiden/blob/ffbb19c5bc26e718af081328eac98e8519b254c8/raiden/tests/utils/apitestcontext.py#L66-L77)
- [token_swap](https://github.com/raiden-network/raiden/blob/ffbb19c5bc26e718af081328eac98e8519b254c8/raiden/tests/utils/apitestcontext.py#L272-L276)
- [expect_token_swap](https://github.com/raiden-network/raiden/blob/ffbb19c5bc26e718af081328eac98e8519b254c8/raiden/tests/utils/apitestcontext.py#L278-L283)

## Tasklist

- [ ] Implement all possible checks for all required pre-conditions, and raise proper exception if any fails, with proper error messages.
- [ ] Handle above exceptions in the http API, and respond user with proper HTTP error.
- [ ] Expand swap tokens tests with expected-to-fail testing code.
- [ ] Handle these errors in webUI and show informative messages to users.

**Comment by hackaugusto** [comment]
Implementing these checks at the moment is a bit overkill, the REST API should just use the `async_result` and return a corresponding HTTP RESULT CODE if the transfer succeed or fails.

**Comment by andrevmatos** [comment]
The token swap is currently disabled, and will be rewriten after Red Eyes, this issue isn't relevant anymore.
