### ISSUE TITLE
RaidenAPI.transfer should support external hashlocks

### ISSUE THREAD

**Issue by heikoheiko** [raiden-network/raiden#85]
hashlocks act as transfer ids. 
they should be an optional parameter in the API `transfer` method. 

https://github.com/raiden-network/raiden/blob/master/raiden/raiden_service.py#L50
https://github.com/raiden-network/raiden/blob/master/raiden/transfermanager.py#L37

**Comment by ezdac** [comment]
for reference: the `secret` is meant here

**Comment by hackaugusto** [comment]
Could we add an identifier field of some sort? if we use the secret provided by the user and a timeout occurs from one of the paths we cannot retry the transfer.

**Comment by heikoheiko** [comment]
yes, we need an identifier

**Comment by hackaugusto** [comment]
Issue for identifiers #139
