### ISSUE TITLE
Handle change of channel state on restart gracefully

### ISSUE THREAD

**Issue by pcppcp** [raiden-network/raiden#857]
## Problem Definition

Raiden stores serialized state of a channel on exit and uses it to restore state on startup. If the stored state differs from the contract's (blockchain) state, raiden will fail with an exception.
This situation may happen i.e.
- if contract address has changed
- if geth node is connected to a differrent network
- channel is removed from the contract for some reason
- (if user accidentally starts two nodes with the same configuration/account)

## Solution

- store contract addresses on first run inside of configuration db and warn user if the address changes
or
- derive configuration directory/db path from contract addresses . 

## Tasklist
- [ ] Discuss which approach should we use
- [ ] handle state disparity and give the user some meaningful info how to solve the situation

**Comment by hackaugusto** [comment]
This issue cover a few different problems, I'm closing it in favor of more specific issues.

> if contract address has changed

for netting channels, that means the previous channel was closed and a new one was opened, this needs to be handle by #669 

for the other smart contracts that means a different network is being used and that should be handled by #348

> if geth node is connected to a differrent network

Create a new issue for this, #1328

> (if user accidentally starts two nodes with the same configuration/account)

This is not allowed by the database lock.
