### ISSUE TITLE
Make landing page of webui more interesting

### ISSUE THREAD

**Issue by czepluch** [raiden-network/raiden#859]
## Problem Definition

Currently the landing/home page of the webui just holds some of the same data as the old raiden.network site does. We should write something more interesting here and maybe display some stats of the current token networks.

## Solution

Update the home page to have more interesting content. See above for some ideas.

## Tasklist

- [ ] Update content
- [ ] Add stats from active token networks
- [ ] Link to raiden documentation

**Comment by LefterisJP** [comment]
Closed since we now have a link to the docs in the webui and the other improvements have either been done or are not specific enough (read as: required) for the Developer preview milestone.
