### ISSUE TITLE
Add off-chain settlement period negotiation

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/raiden#864]
## Problem Definition

The choice for the settlement period is unilateral, it's chosen by the node opening the channel. Ideally the value chosen is good enough for both nodes, and the channel is used normally.

A problem arises when the creator uses a settlement period too small. The channel creator rationale is to reduce the waiting time required to withdraw, if the period is lower than the required reveal timeout by the partner, it will inadvertently create an unusable channel, since the counterparty will just ignore the channel considering the settlement period unsafe. 

## Solution

This may be fixed on-chain, allowing the nodes to *increase* settlement period while the channel is *opened*, the drawback is the additional transaction required (note that it may still be useful to support this operation to extend the maximum number of possible hops in a mediation path).

Additionally this may be done off-chain, exchanging setup configuration among the nodes *prior* to the channel instantiation.

## Tasklist

- [ ] Add a protocol message to inform a counterparty that a new channel will be opened and its properties
- [ ] Add a second message for the counterparty to inform the minimum and maximum valid configuration values, for the time only the settlement period seems to be required.

**Comment by hackaugusto** [comment]
https://github.com/raiden-network/raiden/issues/43 proposal for the off-chain settlement period:

> An alternative implementation removes the settlement period of the NettingChannelContract and add it to the message envelope, where the current highest expiration of all locks is used and signed along side with the merkleroot, and the smart contract will only allow settlement after this latest settlement period has elapsed plus a reveal timeout.

**Comment by pirapira** [comment]
I see the current max as:
```
DEPLOY_SETTLE_TIMEOUT_MAX = 555428  # ~ 3 months
```

**Comment by pirapira** [comment]
I think the idea makes sense.  We have to balance the cost of extra steps against the possible channel-opening attacks.  Maybe we can wait till we see those attacks.

**Comment by karlb** [comment]
We don't have variable settle timeouts since https://github.com/raiden-network/raiden-contracts/issues/1550.
