### ISSUE TITLE
Investigate gas usage of opening a new channel

### ISSUE THREAD

**Issue by ulope** [raiden-network/raiden#869]
## Problem Definition

@czepluch and I noticed that opening a new channel currently uses [947,812 gas](https://ropsten.etherscan.io/tx/0x1072aef7fc754e016a086d463d93423532ab7ff6fc60a8b91601aabcc2551ed1) which seems excessively high.

## Solution

Investigate whether this is the expected amount of gas usage and if there is anything that can be done to reduce it.

## Tasklist

- [ ] Investigate gas usage

**Comment by hackaugusto** [comment]
~30% of the gas cost is because of the `CREATE` opcode

**Comment by loredanacirstea** [comment]
High gas usage for opening a new channel is being solved by having a common smart contract for all channels of a Token network. New smart contracts are located here: https://github.com/raiden-network/raiden-contracts

Some gas costs from the old model:
addToken 760938 https://ropsten.etherscan.io/tx/0xef1df8e013a01db07f1939c146f22db88f559ab6a1b30bf6359408a138626c47
newChannel 947812 https://ropsten.etherscan.io/tx/0x1072aef7fc754e016a086d463d93423532ab7ff6fc60a8b91601aabcc2551ed1
newChannel 1198023 https://ropsten.etherscan.io/tx/0x147e5a1cb81bb6591e0e7de2542b9bdf1411f0201445609a2fab57466ce5bd9b
deposit 71163 https://ropsten.etherscan.io/tx/0xc1eb9234e329d0cb6692ba5f10ebd918813e4c414b22d242120d2b96e6e91f1f (0.0000004 tokens)
close 67655 https://ropsten.etherscan.io/tx/0x4205985083e869819a29e8aa93c40952f6b8758e39a51f4c79369184437d39e7
settle 34211 https://ropsten.etherscan.io/tx/0x7b2c780a5d6305c62a874a25041bba755148a9a0e8693a368068d3f7c4483fb4 (1 token transfer)
settle 28855 https://ropsten.etherscan.io/tx/0x92d9764e6e27e9808a7360162a34a6d3be21dfe528dd5f81941651e2cf7e41d6 (no token transfers)

Estimative gas costs for the in-work smart contracts: (will probably be optimized even further)
```
TokenNetwork.openChannel 110826
TokenNetwork.setDeposit 70862
TokenNetwork.closeChannel 106721
TokenNetwork.updateTransfer 67077
TokenNetwork.settleChannel 63701 (2 token transfers)

TokenNetworkRegistry DEPLOYMENT 3224456
TokenNetwork DEPLOYMENT 2734177
TokenNetworkRegistry.createERC20TokenNetwork 2100525
SecretRegistry.registerSecret 45508
```
