### ISSUE TITLE
Switch to py3

### ISSUE THREAD

**Issue by heikoheiko** [raiden-network/raiden#87]
Q: Shall we also break py2 compatibility and use new py3 features?
Yes, py3 only.

General information about the transition can be found in
- https://docs.python.org/3/howto/pyporting.html
- http://python3porting.com/preparing.html

## Preparation
  - [x] replace `encode('hex')` with a py3 compatible variant (#1158)
  - [x] replace `decode('hex')` with a py3 compatible variant (#1158)
  - [x] use compatible imports
- [x] get rid of own dependency forks
  - [x] pystun
    - looks like this is not maintained any more, what do we do about it? Seems to work for now.
  - [x] ethereum
    - We'll stay with 1.6.1 for now. It's compatible with py3 and doesn't break the API. In the long term we want to move to `web3.py` and `py-evm`.
- [x] Check library dependencies, `caniusepython3` lists 5 dependencies that need to be updated:
  - [x] filelock
  - [x] gevent-websocket
  - [x] marshmallow-polyfield
  - [x] miniupnpc
  - [x] tinyrpc

## Switch
- [x] Remove usage of `[value|keys|items]iter`
- [x] Remove `future` imports
- [x] Remove `__future__` imports
- [x] `bytearray` objects work differently

## Fix tests
This is an overview over which tests have been fixed already. See the `palango/py3-fixes` branch

- [x] unit
- [x] smart_contracts
- [x] property
- [x] long_running
- [x] integration
- [x] api

## Once on python3
- [x] Check division operators
- [x] Remove python 2 variants
- [x] See where `list(...)` around old `iter` calls is needed
- [x] switch HTTP statuses to <https://docs.python.org/3.6/library/http.html> HTTPStatus
- [x] Add type annotations to important interfaces

- [x] Run `mypy` analysis, see where type signatures make sense
  - see follow up: #1206 
- [x] Adapt linux and macOS build infrastructure for py3
  - see follow up: #1205 

## py3 porting gotchas

- Blockchain calls that used to return `None` now return `b''`
- Blockchain calls that used to return `str` now return `bytes`, we have to define how we want to handle this

**Comment by LefterisJP** [comment]
@heikoheiko Please let's not break `py2` compatibility.

But yes we should make raiden py3 compatible and have a separate tox environment for `py3` just like we have in pyethereum.

**Comment by andrevmatos** [comment]
I'm going to work on this for next sprint. As most of our dependencies already announced they're deprecating py2 support, I'd like to work in the direction of full migration to python3 when this gets fully solved.

**Comment by LefterisJP** [comment]
As discussed in the sprint planning meeting I have completely changed my mind since last year and I am wondering why do we want to keep py2 compatibiity instead of just deprecating it?

@konradkonrad @heikoheiko @hackaugusto Are there any reasons to support both py2 and py3 instead of just opting for a complete switch to py3?

The way I see it having a hybrid approach we end up putting quite a bit more work on ourselves as we have to write hybrid code for both python versions.
