### ISSUE TITLE
Increase deposit timeout for Dev Preview

### ISSUE THREAD

**Issue by czepluch** [raiden-network/raiden#878]
## Problem Definition

With Ropsten having quite long and inconsistent blocktimes we sometimes run into a timeout when depositing (https://github.com/raiden-network/raiden/blob/master/raiden/api/python.py#L223-L232). 

## Solution

Increase the timeout time to be 120 seconds rather than 60, in order to increase the changes of avoiding a timeout.

## Tasklist

- [ ] Increase timeout

**Comment by andrevmatos** [comment]
Further investigation pointed that we don't actually need to increase timeout, as the given method already waits for the transaction to be mined.
Instead, we made an approach ( #967 ) of making the first call ([token.deposit](https://github.com/raiden-network/raiden/blob/b490e2ee3fb434780733250f0c5a30879ad3a096/raiden/network/rpc/client.py#L636)) to not wait for the transaction to be mined, then call deposit right after it, and wait only for the later.
This way, [python.py' deposit](https://github.com/raiden-network/raiden/blob/b490e2ee3fb434780733250f0c5a30879ad3a096/raiden/api/python.py#L243) doesn't need to wait too long, as the whole wait is on the `netting_channel.deposit`, which actually waits up to `DEFAULT_POLL_TIMEOUT = 180s` for the block to be mined, but just preempt (usually, only once) through `gevent.sleep` to give opportunity of the events to be processed.
It can be closed as soon as #967 is merged.
