### ISSUE TITLE
Parity: Deposit not happening when opening channel with API

### ISSUE THREAD

**Issue by czepluch** [raiden-network/raiden#879]
## Problem Definition

Sometimes when opening a channel through the API with a balance included, it seems that a deposit does not happen. A channel is opened correctly, but the deposit never takes place. Neither does the `approve` call.

## Solution

We need to investigate why `deposit` and `approve` does not happen. 

## Tasklist

- [ ] Identify why above happens
- [ ] Implement solution for above

**Comment by LefterisJP** [comment]
It worked for me while opening a channel with a balance.

**Comment by czepluch** [comment]
Yes, only happens sometimes to me, too. I have not yet been able to determines what makes the  `approve` and `deposit` happen or not.

**Comment by czepluch** [comment]
This issue seems to happen when using parity. I have not run into this problem a single time since switching to geth.

**Comment by LefterisJP** [comment]
I am switching this to a parity only bug, as I have never seen it with geth.

**Comment by LefterisJP** [comment]
@czepluch or @andrevmatos or whoever please try to reproduce it with parity and latest master. If not possible we should close the issue.

**Comment by dylanseago** [comment]
I am also experiencing this issue when using parity! When I make an RPC call to open a channel I can see in the logs that it was created but the http request stalls indefinitely.

**Comment by LefterisJP** [comment]
@czepluch We have been using parity in our latest release quite a bit. I suppose this bug is no longer valid. Can we close the issue?

**Comment by czepluch** [comment]
yes.
