### ISSUE TITLE
EndpointRegistry.sol is very expensive to use

### ISSUE THREAD

**Issue by czepluch** [raiden-network/raiden#881]
## Problem Definition

It seems that everytime Raiden is started the `register_endpoint` is called (https://github.com/raiden-network/raiden/blob/d68cbe87381f7f949beb0cbf358638274aacad75/raiden/network/discovery.py#L74). This call to the smart contract is quite expensive and costs 500.000 gas. 

## Solution

There should be a way to not do this transaction so often and also the EndpointRegistry.sol should be reiterated to see if it can be improved.

## Tasklist

- [ ] Update the code so that it doesn't call EndpointRegistry.sol everytime Raiden is started
- [ ] Reiterate EndpointRegistry.sol to make it less expensive to interact with

**Comment by hackaugusto** [comment]
I don't think we should optimize the endpoint registry, this is just a work around while we don't have discovery implemented.

**Comment by czepluch** [comment]
Yeah, I also realized that it actually isn't as expensive as I thought. It's 50k gas and not 500k. Closing this.
