### ISSUE TITLE
pkg_resources.ContextualVersionConflict: (ipython 4.2.1 (/Library/Python/2.7/site-packages), Requirement.parse('ipython<6.0.0,>=5.4.0'), set(['pyethapp']))

### ISSUE THREAD

**Issue by cytl5yy** [raiden-network/raiden#896]
## Problem Definition
pkg_resources.ContextualVersionConflict: (ipython 4.2.1 (/Library/Python/2.7/site-packages), Requirement.parse('ipython<6.0.0,>=5.4.0'), set(['pyethapp']))

## Tasklist

Example:

**Comment by LefterisJP** [comment]
What problem are you trying to report? How did you get to this problem? What is your system's version?

**Comment by cytl5yy** [comment]
my system is     mac 10.12.5    python  2.7.10   ipython 4.2.1

the problem is  because i first install  pyethapp  the ipython version is 5.4.1 ,but when i install raiden the ipython version changed to 4.2.1  ,but the pyethapp(tip : pkg_resources.DistributionNotFound: The 'ipython<6.0.0,>=5.4.0' distribution was not found and is required by pyethapp) ,when i run raiden in cli it tip (pkg_resources.ContextualVersionConflict: (ipython 4.2.1 (/Library/Python/2.7/site-packages), Requirement.parse('ipython<6.0.0,>=5.4.0'), set(['pyethapp'])))

**Comment by LefterisJP** [comment]
Please read the [installation guide](https://github.com/raiden-network/raiden/blob/master/docs/overview_and_guide.rst#installation), follow it and only if you got problems with it, open an issue.

You have to create a virtual env and then run `pip install -r requirements.txt` and all the proper requirements will be figured out.

**Comment by LefterisJP** [comment]
Closing the issue. If you have other problems in installing and using raiden please wait until the developer preview release is ready and ask us questions/support in [gitter](https://gitter.im/raiden-network/raiden)
