### ISSUE TITLE
add callback support for API methods

### ISSUE THREAD

**Issue by ezdac** [raiden-network/raiden#90]
**Estimate for sprint 2:** 0.5
A `on_success` notification is desired for most of the API methods...
add support for callback execution `cb(success, id, reason=None)` for several methods accessed by the API:
- `open_channel()`
- `close_channel()`
- ...

**Comment by konradkonrad** [comment]
I have some hope that most of this is already supported, see commits:
fe6c90d4d86028090f6c7eaa0a0e7ed6fd56c922
aba63e952b08ab4aea0296d92ef55e23cb91773e
90515228d7dc8e0668e51e8d9aa994ee7a47dc0a
00da055be4a17b9d6a851438d56e919b2604edff
d6529f124394004f05821d4d1b9886ae8ec2dc7a
30783ef22643510609336007e14824a378e1c2f3

However, from an API consumer point of view (i.e. RPC) there may be some more requirements here, see also #10 #158

**Comment by LefterisJP** [comment]
Also create a Spec for the API so that we know what functions require callback, what functions are required e.t.c.

**Comment by ezdac** [comment]
Yes, these are the commits to feature callbacks for the `transfer_async()` and `register_on_withdrawable_callback()`,
but they probably need a review.
Like it is implied in the original post, once we have specs for a minimal protocol, we should include some default callbacks.
For example the creation of a `on_sucess_()` callback inside of a `transfer_async(..., id)` that posts a `success` message to some websocket/pubsub for that `id` on transfer completion.
There is a implementation hinted for this in my experiments with the WAMP protocol in https://github.com/raiden-network/raiden/blob/master/raiden/api/wamp_server.py#L150

I think that a notification for task-completion is desired in most of the current API-methods,
so I propose adding callback functionality for these methods:

- open()
- deposit()
- exchange()
- close()
- settle()

Please give some input and feel free to discuss!

**Comment by LefterisJP** [comment]
Closing this since for the MVP we don't need calbacks for the API. Callbacks may only be needed for the API used as a python library. What we want is a Restful webserver API so this issue is no longer valid.
