### ISSUE TITLE
Should we add github integration to gitter channel?

### ISSUE THREAD

**Issue by czepluch** [raiden-network/raiden#91]

**Comment by LefterisJP** [comment]
@czepluch I would say yes. 
@heikoheiko @konradkonrad Any of you oppose this?

**Comment by konradkonrad** [comment]
No opposition here.

**Comment by LefterisJP** [comment]
After more consideration, looking at the way we work this integration seems to be unnecessary since the gitter channel is just a public channel and not our internal dev channel.
