### ISSUE TITLE
Investigate STUN issues

### ISSUE THREAD

**Issue by ulope** [raiden-network/raiden#920]
## Problem Definition

It appears that our STUN implementation doesn't reliably open a port in many networking setups (for example "Symmetric NAT" seems problematic). 
Investigate what those circumstances are and if and how it can be fixed.

## Tasklist

- [ ] Investigate STUN behaviour

**Comment by konradkonrad** [comment]
For Symmetric NAT we are out of luck with STUN, see https://en.wikipedia.org/wiki/Network_address_translation#Symmetric_NAT. If we wanted to solve mappings for symmetric NAT for our standard UDP transport, we would need to add a signaling server (e.g. ICE) in between, or change the discovery to include port mappings for specific peers.
IMO it is not worth it to solve symmetric NAT now. We may switch to a different transport and will add light clients at some point in time.

**Comment by ulope** [comment]
No, let's close this for now.
