### ISSUE TITLE
Implement API endpoint for querying connection to token network

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#921]
## Problem Definition

We have API endpoints to [connect](https://github.com/raiden-network/raiden/blob/f0d57190aa92258e7e4cf70b6c845719d6bb2121/docs/rest_api.rst#connecting-to-a-token-network) and to [leave](https://github.com/raiden-network/raiden/blob/f0d57190aa92258e7e4cf70b6c845719d6bb2121/docs/rest_api.rst#leaving-a-token-network) a token network.

Once a user is connected to a token network, a connection manager has been created for that network which manages the user's connections to channels of that network. There is currently no way for users to query if they are connected to a token network.

## Solution

Create a way for users to query if they are connected to a token network through the REST API.

The simplest way to achieve this is to add the possibility to perform two new requests to the REST API.

#### Checking existence of connection to a token network

 a `GET` request to the connection endpoint for a token. e.g.:

`GET /api/<version>/connection/<token_address>`

If there is no connection it should return a `204 No content` and if there is a connection a `200 OK` with the allocated funds for the connection manager, much like the `PUT` request does.

#### Getting all connections to token networks.

A `GET` request to:

`GET /api/<version>/connection`

Always returns 200 OK and if there are no connections it should return an empty list, but if there are connections it should return a list of the tokens we have a connection to.

**Comment by ulope** [comment]
IMO the better HTTP code for "not joined" would be 404.

Also will this endpoint really be that useful (esp. in context of the webui)? Usually I'd imagine a user would want to get a list of all his joined networks not query for them one token at a time.

**Comment by LefterisJP** [comment]
>IMO the better HTTP code for "not joined" would be 404.

@ulope Yes I am not sure about the `204`. Perhaps 404 is indeed the more appropriate return code, but the reason I did not put it there is that it's the default return code for any non-existing endpoint by the REST server.

> Also will this endpoint really be that useful (esp. in context of the webui)? Usually I'd imagine a user would want to get a list of all his joined networks not query for them one token at a time.

Both would be useful I think. It's easy to add what you say by doing a:

`GET /api/<version>/connection`

which should return always with a `200 OK` and a list of joined tokens, and an empty list for no connected tokens. By connected it's always meant that a connection manager is active.

Sounds good @ulope ?

**Comment by ulope** [comment]
> @ulope Yes I am not sure about the 204. Perhaps 404 is indeed the more appropriate return code, but the reason I did not put it there is that it's the default return code for any non-existing endpoint by the REST server.

Good point. While `404` is technically correct (the best kind ;)) its not very helpful to the user and also ambiguous. 

> Both would be useful I think. It's easy to add what you say by doing a:

True. I worded that badly. I didn't mean to suggest that we shouldn't have the single query endpoint. 

> `GET /api/<version>/connection`
>
> which should return always with a 200 OK and a list of joined tokens, and an empty list for no connected tokens. By connected it's always meant that a connection manager is active.
>
> Sounds good @ulope ?

Jup :)

**Comment by czepluch** [comment]
closed with https://github.com/raiden-network/raiden/pull/934

**Comment by andrevmatos** [comment]
Actually, I'm having some issues with it. I've a channel manager with only one of the two tokens currently registered, and it was the only Join Network I've ever done, and I've channels only with this one. Despite that, GET to `/api/1/connection` returns both tokens in the list, and GET to `/api/1/connection/<token_address>` always returns `0`, even if I actually deposited funds in the first token (on join). Should I open a new issue for it, or just reopen this one? I can work on that soon.

**Comment by czepluch** [comment]
Let's just reopen this.

**Comment by andrevmatos** [comment]
Just for the records, in talks with @konradkonrad and @LefterisJP , we decided to change the API compared to OP in this issue. All information requested here are provided, but in a different form, and fixes were made. Full documentation on the changes are in #1001 .

**Comment by LefterisJP** [comment]
@andrevmatos Can you still put a quote of the actual changes here for the benefit of people linking directly from the changelog?

**Comment by andrevmatos** [comment]
Of course. Mostly from [this comment](https://github.com/raiden-network/raiden/pull/1001#issuecomment-328890894):

> Instead of different API endpoints for connection manager funds, sum_deposits, "valid channels", etc, we ended up with a unified API. `GET` on `/connection` will return `200 OK` statuso code, with JSON object where each key is a token address which was previously joined (assuming having open channels for that token is an indicator for a joined network token), and the values are objects like: {"funds": 100, "sum_deposits": 50, "channels": 3}.

Full documentation can be seen [here](https://github.com/raiden-network/raiden/blob/f2c46673318dd2e1f2307222f1d9bafad7ee2828/docs/rest_api.rst#querying-connections-details) .
