### ISSUE TITLE
Allow a channel re-open or a new channel to be created after a close

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/raiden#93]
Remove the channel address from the manager once the channel is settled is a possible solution, this allows a new contract to be created.

**Comment by czepluch** [comment]
Should this happen right after `settle` is called?

**Comment by hackaugusto** [comment]
I think so, the users will to wait for `settleTimeout` until that can happen, but we don't lose the address from the channel manager (it is useful for third-parties calling unlock and/or updating the transfers)

**Comment by czepluch** [comment]
Also clean up the BC when a channel is settled my calling suicide

**Comment by czepluch** [comment]
If we're planning on making changes to the messages anyway, we might as well add `channel_address` to the messages, and use this as an identifier to prevent double spending.

**Comment by heikoheiko** [comment]
I'm strongly against adding another field to the message (making it longer) unless necessary. 

There are two alternative ways of solving the problem:
1) hash the `channel_address` into the signature. That is sign sha3(msg+channel_address).
2) Use nonce ranges. I.e. the starting nonce could be `block.number * 2^192`

I'm in favor of 2)

**Comment by czepluch** [comment]
I agree 2) is the best solution. 

I will however need to change the messages to change the length of the `nonce`. Right now it's only 8 bytes and I think that's not quite enough. @hackaugusto you see any problems with this?

**Comment by hackaugusto** [comment]
Increasing the `nonce` field seems backwards, after all the decision to not add a new field is to not increase the message size and this would increase the size just to support the ranges.

Why not go with option 1?

**Comment by czepluch** [comment]
Valid point. If we try to avoid increasing the size of the messages, then it makes more sense to go with option 1.

**Comment by heikoheiko** [comment]
how is 8 bytes not enough? 4bytes for all possible block offsets during the next 100 years and 4 billion transfers during the lifetime of the channels sounds good to me.

**Comment by heikoheiko** [comment]
my assumption would be that hashing in the address of the contract might be more changes to the code base. but no strong preferences.

**Comment by czepluch** [comment]
This issue is very close to being done. PR will be submitted tomorrow.
