### ISSUE TITLE
Implement proper error reporting for mediated transfers failure

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#939]
## Problem Definition

Right now if mediated transfers fail we have no way to let the user know that it failed and no way to report why.

As a simple example picture a mediated transfer from `A` -> `B` -> `C`.

Channel `A` - `B` has `settle_timeout`: 60 and `reveal_timeout`: 30
Channel `B` - `C` has `settle_timeout`: 65 and `reveal_timeout`: 30

If `A` tries to send to `C` through `B` then when the mediated transfer reaches the target it will be [deemed](https://github.com/raiden-network/raiden/blob/a025b2f5b56888ce327bf1cb4d2ee5e16d7fc657/raiden/transfer/mediated_transfer/target.py#L83) to be [unsafe](https://github.com/raiden-network/raiden/blob/a025b2f5b56888ce327bf1cb4d2ee5e16d7fc657/raiden/transfer/mediated_transfer/mediator.py#L83) to wait.

And thus `C` will never send a `SecretRequest` to `A` and then `A` has no way to know what happened.

The above is just one example of a failure during mediated transfers. There are a lot others, like the node being offline e.t.c.

## Solution

Figure out how to handle all these situations and provide proper error reporting to the users.

**Comment by hackaugusto** [comment]
Error reporting cannot be reliably implemented, it's impossible to distinguish network problems from byzantine behavior, and it adds a degree of trust on the error messages. There should be only one error mode and it's the expiration of the lock, this should be informed to the user either by setting the async result to false or with a proper http response code.

**Comment by LefterisJP** [comment]
@hackaugusto What do exactly mean by byzantine behaviour?

> There should be only one error mode and it's the expiration of the lock, this should be informed to the user either by setting the async result to false or with a proper http response code.

That's a good step towards the right direction of making the system useable. And with a sensible lock expiration it would also not take "too much" time.

**Comment by hackaugusto** [comment]
> What do you mean exactly by byzantine behaviour? Can you elaborate?

Anything out of the expected. Forged messages, software/hardware bugs, etc.

**Comment by LefterisJP** [comment]
Yes so that makes sense, so we can at least inform the user with a proper http response code for mediated transfers.

**Comment by karlb** [comment]
The PFS will report proper errors for many cases. This is good enough for now.
