### ISSUE TITLE
Update natspecs for smart contracts

### ISSUE THREAD

**Issue by czepluch** [raiden-network/raiden#97]
Go through the smart contracts and update the natspecs

**Comment by czepluch** [comment]
This is something that needs to be done at some point, but it's more of an improvement. Would say it should be done for all functions before the MPV is launched in order for the community to easily understand the code.

**Comment by LefterisJP** [comment]
Yes Please.

**Comment by czepluch** [comment]
@heikoheiko guess this could be added to the MVP too.

**Comment by czepluch** [comment]
closing since dublicate of https://github.com/raiden-network/raiden/issues/335
