### ISSUE TITLE
UDP transport send unordered messages in parallel

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/raiden#981]
## Problem Definition

Messages sent using the global queue  don't need to be ordered, e.g. [RevealSecret](https://github.com/raiden-network/raiden/blob/master/raiden/transfer/mediated_transfer/target.py#L160-L166) and [SecretRequest](https://github.com/raiden-network/raiden/blob/90f0d39dd9eb2e686b4a3df0fd253e50abb17ea7/raiden/transfer/mediated_transfer/target.py#L112-L120). It is fine to send these messages in parallel because they don't contain a balance proof, so the validity of these messages don't depend on the order in which they arrive at the target.

Currently the messages are ordered, for each recipient there is a global queue plus one queue for each open channel. The  which adds unnecessary latency for these messages, this latency is shared among all channels with the recipient node.

## Solution

Introduce a new retry mechanism for unordered messages, i.e. that doesn't rely on a queue, and use it for sending these messages.

## Related

Collapse multiple raiden messages within a single transport packet. #309

**Comment by rakanalh** [comment]
UDP Transport was removed. Closing
