### ISSUE TITLE
Raiden on a Raspberry 3 with geth in syncmode light mode

### ISSUE THREAD

**Issue by dstreppa** [raiden-network/raiden#989]
## Problem Definition

I am trying to install and play with Raiden on a Raspberry PI 3 (with geth running with the `-syncmode light` option on the testnet network). I realized to install Raiden but it seems not to work with geth in "-syncmode light" mode. Is it mandatory to have a full ethereum node on the Raspberry to work with Raiden?

### System Description
<pre>
pi@smartpi:~ $ cat /etc/os-release 
PRETTY_NAME="Raspbian GNU/Linux 8 (jessie)"
NAME="Raspbian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
pi@smartpi:~ $ raiden version
{
  "python_version": "2.7.9", 
  "python_implementation": "CPython", 
  "system": "Linux 32bit_ELF 4.9.35-v7+", 
  "raiden": "0.0.6+git.ref6b10e"
}
pi@smartpi:~ $ geth version
Geth
Version: 1.6.7-stable
Git Commit: ab5646c532292b51e319f290afccf6a44f874372
Architecture: arm
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.8.3
Operating System: linux
GOPATH=
GOROOT=/usr/local/go
pi@smartpi:~ $ solc --version
-bash: solc: command not found
</pre>

**Comment by czepluch** [comment]
Can you be more specific as to what isn't working? When do you encounter an error? What kind of error is it? Did you follow the steps from the documentation for installation?

**Comment by konradkonrad** [comment]
+1 on @czepluch s request for a more detailed error description

Anyway, you will need `solc` or (if you're into tinkering) copy the `raiden/smart_contracts/*.static-abi.json` files over from an installation on a machine with `solc` installed (call `python setup.py compile_contracts` to generate the static abi files).

Lightclient should work in general (it's just pretty slow for events querying).

**Comment by dstreppa** [comment]
@czepluch sorry for the loss of details. Now, after a lot of try and re-try, the light node is correctly synced to Ropsten. The problem was the slowness of the syncing, hugely amplified by the usage of a Raspberry. Now I am trying to install solc for Raspbian, I am compiling from the sources because it seems not to exist a precompiled package for armv7.

I apologize again for the loss of details and thank you for the suggestions.

**Comment by LefterisJP** [comment]
@dstreppa Please tell us if there is anything else we can help you with. If not then can we close this issue and you can open another one when you have a specific problem?

**Comment by dstreppa** [comment]
@LefterisJP yes, it is better to close the issue.
