### ISSUE TITLE
Find better variable names for `updateTransfer` and `closeSingleFunded`

### ISSUE THREAD

**Issue by czepluch** [raiden-network/raiden#99]

**Comment by hackaugusto** [comment]
Note: `closeSingleFunded` was renamed to `closeSingleTransfer` on commit fb1fb3b7cd6d845cdd49703d4427afa01867dc22
https://github.com/raiden-network/raiden/commit/fb1fb3b7cd6d845cdd49703d4427afa01867dc22#diff-09cebda618db5fb2268a55de8de94279R167

**Comment by czepluch** [comment]
I believe we're happy with the naming we have now. The is no `closeSingleTransfer` anymore since https://github.com/raiden-network/raiden/pull/276 and `updateTransfer` seems to be fine.
